### ISSUE TITLE
[Suggestion] Default search when selecting root of context menu

### ISSUE THREAD

**Issue by TChilderhose** [ssborbis/ContextSearch-web-ext#1]
Firstly, thanks a lot for making this. Was one of the few addons I really missed in FF57.

Would it be possible to add the ability to select a "default search engine" that will change the root of the context menu from "Search with" to the search engine name so that when you press that it will do that search instead of having to go into the menu and selecting one. For example, I use Google 90% of my searches, so to be more efficient to not have to go into the menu to select Google.

**Comment by ssborbis** [comment]
I think the new web-ext API forces the actions of a Root menu with a submenu to open the submenu without the possibility of any other action.  I'll take a look, but from what I've seen so far with FF 57+, the control over the context menu is pretty limited.  You might try the latest builds (1.0.1b2+) where I've added a quick-menu (experimental, enable in options) on either hold right-click or a button of your choice. If you set Menu Items to 1 and Google is the first search engine on your list, you'll get a single icon popup with google.  Let me know how it works out for you.

**Comment by TChilderhose** [comment]
Bah. That sucks. Wonder what their reasoning was for forcing that. Hopefully they open it up a bit more.

Cool. I'll try it out. Thanks!
