### ISSUE TITLE
What exactly does 'ContextSearch Native App' install?

### ISSUE THREAD

**Issue by ghost** [ssborbis/ContextSearch-web-ext#10]
Hi,

I discover with latest _ContextSearch web-ext 1.2.0_ the availability of installing _ContextSearch Native App_ ( ContextSearch_installer.exe for Windows) in order to have the user's search engines modifications automatically integrated to _ContextSearch web-ext_

Could you inform on what exactly is performed by this _ContextSearch Native App_, what is installed, where? Does it modify the Registry and/or Firefox install itself, does it add/modify components in the very install folder of Firefox? I ask because I've never had to deal up to now with an add-on/extension that would proceed this way, that is which would propose to install anything else but itself.

Thanks for a great extension which I thought would never be possible starting Firefox 57.

**Comment by ssborbis** [comment]
Sure, I'll add more detail to the readme file and give you a breakdown here.  The source code is available to view and build yourself if you're uncomfortable installing 3rd party software.  For windows, I've also included the NSIS build script (the script that builds the installer.exe).

The ContextSearch_installer.exe does the following

Creates folder C:\Program Files (x86)\ContextSearch with the following files
 - ContextSearch.exe
 - ContextSearch.json
 - README.md
 - uninstaller.exe

Adds the following key to the registry
HKLM\SOFTWARE\Mozilla\NativeMessagingHosts\ContextSearch

Once installed with the ContextSearch web-ext Add-on, the native app is called by Firefox on certain events (tab change, window.focus) and checks the user's search.json.mozlz4 file (as specified in Options) for changes.  If the file has been modified by adding, removing, or reordering search engines, the Add-on calls the native app again to send a base64 encoded copy of search.json.mozlz4 for parsing and the ContextSearch web-ext search engine list is updated.  That's about it.

**Comment by mazesy** [comment]
OK, clear enough. _ContextSearch Native App_ is installs as a Windows application (on Windows OSs of course) and may be uninstalled as easily I presume (from Windows Uninstall). Got it. This is both a smart and unusual way of proceeding, required of course by Firefox 57+ API limitations.
