### ISSUE TITLE
1.8.0 and FX 63.0.1: Broke Context Menu

### ISSUE THREAD

**Issue by MarkRH** [ssborbis/ContextSearch-web-ext#101]
1.7.0.2: Highlight something and right-click I get this Context Menu:
![image](https://user-images.githubusercontent.com/8035962/47824242-e2a2e200-dd39-11e8-9578-b7ad77cec7cd.png)

1.8.0: Highlight something and right-click I get no sub-menu:
![image](https://user-images.githubusercontent.com/8035962/47824281-1f6ed900-dd3a-11e8-8fd9-4bf70a66b969.png)

Clicking on that item does nothing.

Going back to 1.7.0.2. and it works again.

**Comment by MarkRH** [comment]
Tried with a clean profile and also doesn't work there.

**Comment by reembar** [comment]
I confirm this problem with version 1.8.0
The search menu doesn't open in both Firefox 63.0 and 63.0.1

**Comment by ssborbis** [comment]
working on it

**Comment by MarkRH** [comment]
Version 1.8.1. works fine.  Thanks for the update! :)
