### ISSUE TITLE
Double Click Issue

### ISSUE THREAD

**Issue by jesse9212** [ssborbis/ContextSearch-web-ext#107]
There is an issue where double clicking on links etc. on websites (ie Reddit) the context menu pop up shows for a split second. Some delay needed to fix the issue.

https://imgur.com/0c06a488-7b72-4508-acd9-4121f33c8f1c

**Comment by ssborbis** [comment]
link is dead. 

Why are you double-clicking links?

Which method are you using to open the Quick menu?

What platform are you on? Mac & Linux need some about:config tweaks to work properly with some opening methods

**Comment by jesse9212** [comment]
Sometimes if you have a table where you can click on the column name to change sort order, if you click too fast twice it pops up.

Or reddit:
![popup](https://user-images.githubusercontent.com/1355846/48591453-f3468100-e911-11e8-94bd-b8c0d4dbad13.gif)

**Comment by ssborbis** [comment]
Ok, I've got a 50ms timeout to check whether pre-timer selected text === post-timer selected text. It seems to eliminate that particular problem. It worked at 5ms also, but I'll leave a bit of padding.  I'll update the repo in case you want to test.

**Comment by ssborbis** [comment]
100ms works even better for the inadvertent double-click / triple-click that accidentally selects text in an element. I might add the timeout ms as an option.
