### ISSUE TITLE
Options to Disable Pop-up

### ISSUE THREAD

**Issue by jesse9212** [ssborbis/ContextSearch-web-ext#108]
Would be nice to have an option:

Do not show pop-up when selection contains more than [X] characters or words.

**Comment by ssborbis** [comment]
Using Auto?

**Comment by ssborbis** [comment]
Done

![untitled](https://user-images.githubusercontent.com/24310997/48589184-1a945280-e900-11e8-80f9-d2c21ce84761.png)

**Comment by jesse9212** [comment]
Perfect!
