### ISSUE TITLE
Include urls

### ISSUE THREAD

**Issue by mazesy** [ssborbis/ContextSearch-web-ext#11]
If I right-click over an url I have in the drop-down menu an item _Search [URL] with [my default search engine]_ but _ContextSearch Web-ext_ only appears if the search query is "totally hovered" (I don't know the word in English, I mean on background color as if ready to be copied). Would it be possible for _ContextSearch Web-ext_ to appear as well?
Thanks.

**Comment by ssborbis** [comment]
You want to right-click a link (http://example.com) and see the menu item **Search for http://example.com With->[engine list]** in the context menu?  Sure, I think that's doable

**Comment by mazesy** [comment]
Exactly. My history is that I've installed an url expander search engine which runs ok but concerns mainly "active" urls. At this time I have to go through the hassle of hovering such an url in order to have your great add-on appear in the right-click context menu ...

I really don't want to be one of those users who bother but I hope you see what I mean! Gosh, I lack so much in English :=)

**Comment by ssborbis** [comment]
Try 1.2.1b1
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta

**Comment by mazesy** [comment]
Gorgeous! I just installed 1.2.1b1 and it does the job perfectly!
1- You really do answer so quickly, truly appreiciated,
2- How you managed to build 1.2.1b1 so quickly is amazing.

Many thanks, really.
