### ISSUE TITLE
sidebar: widget and close button should share the same place

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#110]
next wish :-)

I think it would be more convenient, if the "magnifying glass" would morph into the close button (shortening the search field).
Most extensions or tray icons work this way, you can open and close them at the same place.
Also, the close button standing out gets in the way sometimes.

**Comment by ssborbis** [comment]
Bah, I misread your comment. I'll try some things

**Comment by ssborbis** [comment]
Reworked the layout. Close button only displays when mouseover the container
