### ISSUE TITLE
sidebar/widget: conflicting namespace

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#111]
I saw this once before and again today. I think it was the same kind of page, in this case:

https://bugs.launchpad.net/mactel-support/+bug/262408

the sidebar widget is unusual wide
![cs-wide-widget](https://user-images.githubusercontent.com/4707597/48797862-9aa52880-ed03-11e8-9450-522e575c7e99.jpeg)
and after a click the close button also too wide and at a wrong position:
![cs-wide-widget-after-click](https://user-images.githubusercontent.com/4707597/48799339-27051a80-ed07-11e8-8b3a-761c74d28f3a.jpeg)

--- after some DOM inspection ---

The issue seems to be caused by conflicting classes with some page css (combo.css which uses a selector div.right with width: 50% etc.).
```
<div id="CS_sbOpeningTab" style="transform: scale(1); top: 543px;" class="right">
```

I guess, because the widget is injected (unlike the quick menu?), it lives in the same namespace as the page. So you probably need some prefixes for the class names.

**Comment by ssborbis** [comment]
Looks like I need to make my subclasses more unique. I'd been using the prefix CS_ for element ids, but not the classes.

**Comment by ssborbis** [comment]
CSS updated in the repo. Seems to have fixed that issue.

I thought about moving all the sidebar elements into a single iframe, but I think it would get really messy with dnd moving and resizing  (menu iframe + opener tab -> container -> parent iframe). The page messaging is already more convoluted than I would like and I don't expect much conflict with the CS_ prefix

**Comment by hg42** [comment]
"CS_" might be a little bit short...and it might be an abbreviation for something else.

I wonder, why using a selector like `#CS_sbContainer.right` didn't work already, shouldn't it be more specific than `div.right`?
Maybe the problem is the inner `<div>`
```
<div id="CS_sbContainer" style="transform: scale(1); top: 488px;" class="right">
  <div id="CS_sbOpeningTab" class="right"></div>
</div>
```
together with `#CS_sbContainer.right #CS_sbOpeningTab`. Does `div.right` win here? Oh I see, I think the size is defined by `div.right`, because it is not specified in #CS_sbOpeningTab.

Apart from that, this fix or the other changes now prevent dropping text on the search field or an engine.

Btw., dragover should also highlight search engines as it does for folders.

**Comment by hg42** [comment]
I always pull first before testing. My current commit is 05ee51a2862e752ecd32a1ec33e0199c0d1d0e91 from 3 hours ago. A pull doesn't get anything new.

To be more precisely:
Drop doesn't work, if the menu opens after dragging over the widget. Neither search field, nor engine nor folder.
However, it works with the menu already open.

**Comment by ssborbis** [comment]
It's definitely working for me, and i just checked my diffs and there doesn't appear to be any changes that would prevent the dnd. I'll push what I've got now ( might be a css glitch here or there, but should be 99% functional ).

**Comment by hg42** [comment]
a little video:

[drop-does-not-work-2018-11-21_13.57.04.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/2604300/drop-does-not-work-2018-11-21_13.57.04.zip)

(sorry, I first tried gif conversion, but this looses information and is bigger)

**Comment by ssborbis** [comment]
Strange. What's your FF version and OS?

**Comment by hg42** [comment]
note how the symbol flies back to it's origin (not sure, may be drop canceled?).
and it worked at some time before, I'll start to test older versions...

FF 65.0a1, Linux

**Comment by ssborbis** [comment]
The opening handler, which appears to work, is in inject_sidebar.js
The drop handlers are in tilemenu.js.

If there's a problem with the drop/search, that's where it should be. I can think of why the animations would cause the issues. There aren't any animations on drop.

> (btw. I don't like that anyway, everything should be as fast as possible for me, could you allow to disable animations?)

Hmm, probably. I have some events triggered on `transitionend` so I'll have to look at that.

**Comment by hg42** [comment]
* 7804185fedaf27182aa1f1bae29fb3c91be2dded fails for drops (also note that there is no highlighting for folders as before)
* fc67ad44f20dc2e24240ab509e65e5932e183f06 dragover doesn't open the menu

**Comment by hg42** [comment]
I also wait some time, so all animations should be finished.
Also tried to drop somewhere else in the search field.

But the key to the problem might be the missing highlight for dragover a folder, I guess (because I have no experiences with drag and drop for html), the element doesn't accept a drop when asked on dragover, or dragover isn't sent or sent to the wrong object etc...

**Comment by ssborbis** [comment]
Try the latest push. I removed the mouseenter code for animating the close button (fy the close button is missing)

**Comment by ssborbis** [comment]
> But the key to the problem might be the missing highlight for dragover a folder,

The dnd for the searchbar should still work I think even if there was a problem with the search tiles

**Comment by hg42** [comment]
no change

**Comment by ssborbis** [comment]
I'll have to load up your FF ver in ubuntu and see what's going on. I'll be a while

**Comment by hg42** [comment]
> The dnd for the searchbar should still work I think even if there was a problem with the search tiles

I think the missing highlight may indicate that the drag and drop protocol doesn't work. Don't know about how it's handled in html, but usually while drag over an element is asked if it could be a drop target. If it doesn't respond to dragover at all, it wouldn't get the drop event at all. And it also looks like this, because the drag icon flies back to it's start for al targets.

**Comment by hg42** [comment]
originally there was a dragstart in `inject_sidebar.js` (the code in `openingTab.addEventListener('click', () => {`), where is it gone? on a quick look I didn't find a replacement...

**Comment by hg42** [comment]
sorry, I see it's for dragging the close button...

**Comment by ssborbis** [comment]
Quick test on FF62 on ubuntu works as expected.

I'll grab FF65.0a1

**Comment by hg42** [comment]
also doesn't work on 63.0

**Comment by ssborbis** [comment]
Hmm. this is odd we're not getting the same results. Add-on conflict? Same problem on a blank profile? I use the web-ext tool to test on fresh profiles. Might not be so easy for you.

**Comment by ssborbis** [comment]
FF65.0a1 working in ubuntu.

**Comment by hg42** [comment]
you are right
`web-ext -v run -p default -s /z/src/firefox/ContextSearch-web-ext/src`
works.

But I already tested `firefox --safe-mode` and loading the extension via `about:debugging` which behaves identically (fails on drop).
So it doesn't seem to be a conflict with other extensions.

I'll like to start with my whole configuration but from fresh settings for CS. Where are the settings stored? It looks all different from the last time I did something like that...

**Comment by hg42** [comment]
19bbbe39ca38007d65b1c470e2b6fd00e8908294 still doesn't work

**Comment by ssborbis** [comment]
Ok now I'm seeing the problem too after removing the config setting.

**Comment by ssborbis** [comment]
I'm only seeing the problem intermittently on linux. It appears that dragging text is not giving the iframe focus, causing the dnd to fail

**Comment by ssborbis** [comment]
adding iframe.focus() after opening the menu seems to fix the problem

**Comment by ssborbis** [comment]
I'm pushing that simple fix, but I'm seeing some odd behavior like the opening tab disappearing. I'll investigate more. It could be some mouse issue with the virtual machine

**Comment by hg42** [comment]
yes,
```
		// open sidebar if dragging text over
		openingTab.addEventListener('dragover', (e) => {
			if ( getIframe() ) return;
			openingTab.dispatchEvent(new MouseEvent('click'));
			getIframe().focus()
		});
```
works here.

**Comment by ssborbis** [comment]
Phew! No idea how that problem popped up, seemingly on linux only too.

**Comment by hg42** [comment]
btw. the startOpen is still disabled in your branch...
My current code is the change dragover->dragenter + iframe focus on top of f6ba1f906f4520a3a21c9efa8032e26d16f98c98, which works.

**Comment by ssborbis** [comment]
We made the same changes, so I'll put the startOpen back and update the main branch.

**Comment by ssborbis** [comment]
> Adding focus to dragenter may be directly related to the cause.

Originally, it was dragover, but I figured no sense in repeating the event. Unless I'm mistaken, the result of dragenter & dragover is the same, except dragover is repeated for every mousemove.

> But I wonder if adding the focus to the end of the click handler would be more versatile (for other situations).
Should the menu always have the focus after it is opened?

For dnd, probably. I can't think of a time when someone would be dragging text over the menu and not intend to give focus (accidental drag-over maybe?)

**Comment by ssborbis** [comment]
I'll push the latest changes with a .01s transition time (needed some for the current code to work). That should effectively eliminate the animations for you. I'll get something more user-configurable at another time

**Comment by ssborbis** [comment]
> my sentence wasn't about dragenter (which I understand and agree to), I meant adding it only to the dragging over the widget may solve this part, but a more general solution might be better and more general.
The code for opening the menu might set the focus which would be reverted by the dragenter event afterwards.

I see. A minor concern, but I'll think on it. I may want to leave .focus() to the dnd handler because I _think_ the options to focus the search bar on open in the quick menu options apply here as well, and setting .focus() on opening the menu would override that potentially.

> mostly used for some minor optical pleasure

Hey, some people like a little eye candy. I prefer a little ease-in for my menus, but I get the preference for none.

**Comment by hg42** [comment]
> Ok, I agree. I'm too tired to pick up on subtlety at this point

this could also be delayed to the point in time when it starts to matter somehow. Just keep that in mind.

> injecting user-defined css rules

nice, I am a real fan of user styles :-)
I do this heavily for Tree Style Tab.

**Comment by ssborbis** [comment]
simple close icon in the repo

**Comment by hg42** [comment]
while looking at the `hover` class added in tilemenu/dragover (that might be called CS_hover?), I added a console.log(side) and found out the side is never "middle" for a search engine, only for a folder. So it cannot be highlighted.
The code explicitly ignores the "middle" area for search engines:
```
    return ( e.x - rect.x < .5 * rect.width ) ? "before" : "after";
```

The "middle" area also feels too small for dropping in case of searching. In this case the whole area could be used instead.
I guess something like:
```
   if ( is_text_dragging  || side == "middle") {
```
would do the job, but a quick test with `is_text_dragging = e.dataTransfer.getData("text")` didn't work.

**Comment by hg42** [comment]
> simple close icon in the repo

this makes me happy :-)

**Comment by hg42** [comment]
apparently getData isn't possible (security?).

However dataTransfer.types can be used. This doesn't work either, because dragging engines or folders also contains text.

So i came up with:
```
    let is_dragging_items = document.getElementById('dragDiv');

    if ( ! is_dragging_items || side === 'middle')
        targetDiv.style.backgroundColor = 'lightblue';

```
which works.

I think it would be better to completely separate these cases.
* dragging text -> whole item highlighted
* dragging items
  * before -> border left as insertion point (red?)
  * after -> border right as insertion point
  * middle -> some indicator for "drop into" (highlight as it is now, may be another color, or an icon overlay / kind of curved arrow pointing to inside)

**Comment by hg42** [comment]
also simple but better:
```
				let is_dragging_items = document.getElementById('dragDiv');

				if ( ! is_dragging_items )
					targetDiv.style.backgroundColor = 'lightblue';
				else
				if( side === 'middle')
					targetDiv.style.backgroundColor = 'yellow';
				else
					targetDiv.style.backgroundColor = 'lightblue';
```
yellow as indicator for "folder".
Eventually the lightblue could be more strong in case of items, because of the semi-transparent cursor covering it.

**Comment by ssborbis** [comment]
@hg42 
I made the changes you suggested to get the folder formatting working but applied a css class instead of explicit styling. I'm trying to move everything I can to css rules to work with user-supplied styling. The drag handlers that add/remove the class seem to get a bit glitchy thought, but for now you can get an idea of what I was going for.

I widened the "middle" zone a bit to .3 < middle < .7 but you may want more.

New textarea at the very bottom of options to apply user css. Right now it only applies to elements within the tile menus, not to things like the widget but there's plenty of room for color styling, search engine icon padding, etc. Be aware, the css is subject to change as I clean up code and move more styling to css so your custom rules might need changing as well. 

FYI, it's a holiday weekend so any bugs that pop up won't get fixed right away

**Comment by hg42** [comment]
> I made the changes you suggested (with some modifications)

thanks...
perhaps the "+" sign could be red or any color but black, because overlaying the black text looks a bit "dirty"

> trying to move everything I can to css rules to work with user-supplied styling
> ...apply user css

nice

> it's a holiday weekend

enjoy and relax!

**Comment by ssborbis** [comment]
Pushed a lot of css / dnd changes to the repo. 

Added a 'drop to which side' indicator when moving tiles
Removed corner styling for folders
Removed folder dnd + icon, changed to blue background with white text when dropping into folder

**Comment by ssborbis** [comment]
Added option Enable Animations under QM look & feel

Uncheck to disable almost all menu transition events ( hover animations still work currently )

**Comment by ssborbis** [comment]
dnd text over sidebar opens folders when hover > 500ms. Works with back button also

**Comment by ssborbis** [comment]
I'm continuing to move explicit styling to css. Still trying to improve the folder tile styling but I'm liking the new direction.

This userStyles gets pretty close to the FF dark theme if you're interested
```
:root {
    --hover: #666667;
}
BODY { 
    background-color:#323234;
    color:#f9f9fa; 
}
.tile {
    border-color:#444;
}
#suggestions, #searchBar { 
    background-color:#454547;
    color:#f9f9fa;
}
#suggestions {
    border-color:#535355;
}
#suggestions IMG {
    filter:invert(1);
}
#searchBarContainer > IMG {
    filter:invert(1);
}
.tile[data-type="tool"] {
    filter:invert(1) brightness(50%);
}
.tile[data-type="folder"] {
    background-color:#3293d4;
    color:#dedede;
}
.tile[data-type="folder"]:not(.singleColumn)::before {
    background-color:#287cb3;
    border-color:#777;
}
.tile[data-type="folder"]:not(.singleColumn) {
    color:#dedede;
}
```

**Comment by hg42** [comment]
> Pushed a lot of css / dnd changes to the repo

wow, that's an expressive number of improvements at once, must have been a very productive "holiday weekend"

> Added a 'drop to which side' indicator when moving tiles

works nice

> Removed corner styling for folders

the new folder look is great

> Removed folder dnd + icon, changed to blue background with white text when dropping into folder

well done, also how the corner is not highlighted which emphasizes the folder look.

> Added option Enable Animations under QM look & feel

thanks

> dnd text over sidebar opens folders when hover > 500ms. Works with back button also

my most appreciated improvement of the set

css styling is definitely nice, and I usually use such a lot, but everything looks (and works) perfect now, so I don't have anything to play with :-)

**Comment by ssborbis** [comment]
> THANKS A LOT!
No problem. Thanks for beta testing

Getting ready to release 1.8.2 sometime this week. Fixed a few minor bugs today, added an option to open the sidebar on page load, made some css tweaks but I think it's more or less ready.

**Comment by ssborbis** [comment]
Went ahead and released 1.9.0 ( formerly 1.8.2 )

I didn't get to adding blank tiles as an option in the quickmenu, but if you still want to organize your menu like you mentioned before, you can add a new engine, give it a bogus url and set the icon to a transparent data uri `data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7`

Copy that a few times and move them where you want. Not a perfect fix but funcitonal

**Comment by hg42** [comment]
1.8.2...1.9.0...well could have been 2.0 easily, because there's a lot of progress.

> just realized I added code to test for blank icons

well, that's the problem I had, when I tried :-)

> open the sidebar on page load

oh, yes, that's another wish...

I am using the same stratgy with my vertical taskbar, but at the end it's too much work if you often add or delete items. It's like writing text and inserting newlines by adding enough spaces at the end. Add one word and you have to rearrange everything after it.

**Comment by ssborbis** [comment]
Glad to hear the changes are working out. 

I'm going to close out this thread. If any bugs pop up, go ahead and start a new issue
