### ISSUE TITLE
In the chrome version, turn on the extended 1.9.1.2 version, and the page label shows slow loading

### ISSUE THREAD

**Issue by ufo1024k** [ssborbis/ContextSearch-web-ext#116]
In the chrome version, turn on the extension 1.9.1.2 version, the page label display is slow to load, turn off the extended page label load speed is normal.

**Comment by ufo1024k** [comment]
Process recording as GIF
https://i.imgur.com/b1UOve3.gif

**Comment by ufo1024k** [comment]
Re-delete the extension, after installation, seems to be resolved.

**Comment by ssborbis** [comment]
I can't reproduce the bug but I'll look at the code to see if there's something that might be causing the page load to hang.

Are you still able to see the slow icon or is it gone completely after reinstall?

**Comment by ssborbis** [comment]
Good. I love bugs that fix themselves

**Comment by ufo1024k** [comment]
OK, if there's a bug, I'll keep reporting it.

**Comment by ssborbis** [comment]
Ok. I'm browsing the code now to see if I can see something. I'm guessing the icon loads after the `DOMContentLoaded` event fires, so something may have been holding that up. I'll check a few things

**Comment by ufo1024k** [comment]
OK, because I installed the proxy switchyomega extension, opening each page in version 1.9 will show that *.DDIPPGHIBEGBGPJCAAIJBACFHJJEAFJH cannot be loaded, but this issue does not occur in version 1.8.

**Comment by ssborbis** [comment]
can you share your proxy settings so I can test?

**Comment by ssborbis** [comment]
If the problem occurs with all proxies, I have my own

**Comment by ufo1024k** [comment]
Proxy Switchyomega Configuration
  https://pan.baidu.com/s/1-6HAyG-t-AdDR_btkFWl6w

**Comment by ssborbis** [comment]
Hmm... I have no idea what to click to get the file. 

Is there a login required?

Can you send it over email?

**Comment by ufo1024k** [comment]
Give me your email.

**Comment by ssborbis** [comment]
ssborbis@gmail.com

**Comment by ssborbis** [comment]
got it

**Comment by ufo1024k** [comment]
Okay, I'm bothering you.

**Comment by ssborbis** [comment]
Ok, I've got your settings loaded. How do I reproduce the error?

**Comment by ssborbis** [comment]
Ok, I'm seeing a 1 failed resource in the toolbar

**Comment by ufo1024k** [comment]
After you open each site, Proxy Switchyomega a prompt that cannot be loaded on the toolbar icon

**Comment by ssborbis** [comment]
I'll let you know when I find the problem.

Is this error effecting your web browsing in any way or is it just throwing the error in the proxy plug-in?

**Comment by ufo1024k** [comment]
At present did not find the impact of site browsing, just feel that in version 1.8 did not have this problem, but in version 1.9 will appear, just mentioned the site label icon load slowly, so I thought it is this version of the problem, to give you a reaction.

**Comment by ssborbis** [comment]
Ok, I know what the problem is. I have 2 images that are injected as web_accessible_resources that the proxy is attempting to load that don't have a true URL. The error popped up when I added the sidebar widget to the code. `Options -> Toolbar -> Sidebar -> Enable Widget` to see the icon

![untitled](https://user-images.githubusercontent.com/24310997/49274430-fe370080-f43d-11e8-8a08-2bd9208e7925.png)

It's a harmless error. I'll see if I can do a workaround.
