### ISSUE TITLE
Middle click on folder invokes autoscrolling

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#118]
When middle clicking on a folder in the quick menu, then autoscroll / smooth scroll is invoked. Autoscroll should only be activated, when you middle click somewhere on a page, but not in the quick menu. Happens only with folders, on search engines autoscroll isn't activated.

Started to happen after a 1.9.* release. Observed on Firefox 63.0.3 on Ubuntu 18.10.

**Comment by ssborbis** [comment]
Hmm that should have been fixed. 

Oh, folders only? I'll check that. The fix only applied to engines i guess. I'll check it out

**Comment by ssborbis** [comment]
Ok, fix is ready. I'll update the repo
