### ISSUE TITLE
Optional permission

### ISSUE THREAD

**Issue by bdcomp** [ssborbis/ContextSearch-web-ext#12]
Hi,

I used this add-on and would like to continue to use, without any additional auto-magic features, like the new introduced in V1.2.

Is it possible to declare the pretty scary "Exchange messages with programs other than Firefox" permission as optional [1] to users who prefer automatic loading and updating search engines?

[1] [optional_permissions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/optional_permissions)

**Comment by ssborbis** [comment]
Hmm, I don't see nativeMessaging on the list of optional_permissions.  Might not be doable without a separate build

**Comment by ssborbis** [comment]
The addon works fine if the nativeMessaging permission is dropped; only the automatic reloading feature would stop working which does nothing if you don't install the native app anyway.  Would be a simple fork

**Comment by bdcomp** [comment]
Thanks for the prompt reply.

Any other idea how to avoid this permission?
I prefer to not open an additional door for my Firefox, especially for something that worked great till about yesterday...

Separate build - in fact, it may be a great idea to have a "Lite" version, without the auto-magic features.

**Comment by ssborbis** [comment]
Separate build might be the only way.  It was a tough decision to do the native app, but looked like the only way to automatically reload the search engines.  I'm sure the added permissions scared some people off, even without downloading the native app. I'm also very skeptical of additional permissions so I know the feeling.  That's one reason I'm making the source code public.

I'll look into doing a 'lite' version.  I'll reply to this thread when I have something.

**Comment by ssborbis** [comment]
Here, try this one
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta?page=1#version-1.2.1liteb4

If it works, I'll continue doing a lite build.  For now, the Automatic options are still there.  I'll filter those out later

**Comment by bdcomp** [comment]
V1.2.1liteb4 works great.
Thank you!

**Comment by Zlewness** [comment]
Why does this addon request access to html canvas on its settings page in Firefox Nightly?

**Comment by ssborbis** [comment]
It uses canvas.toDataURL(); to convert the search engine icons to base64 for localstorage

**Comment by bdcomp** [comment]
While the currently V1.2.2_lite_rc works great, the proposed update (V1.2.3_lite_rc ?) asks again for the "Exchange messages with programs other than Firefox" permission.

**Comment by ssborbis** [comment]
Whoops, sorry about that.  I probably didn't save the manifest after
removing the permission and built with the NativeMessaging still in there.
I tested the latest to be sure.
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta

**Comment by bdcomp** [comment]
Not sure why (start of beta versions removing [1] ?), but I still prompted for "Exchange messages with programs other than Firefox" permission.

Maybe it's time to separate lite release?

[1] https://github.com/mozilla/addons-server/issues/7163

**Comment by ssborbis** [comment]
I'm not getting the prompt for Native Messaging.  Not sure why you are.  What version of FF are you running and what distro?

**Comment by bdcomp** [comment]
Firefox 57.0.4
Kubuntu 17.10 64bit

You should add the exact version and "lite" to the changelog, to be sure that version I got.

**Comment by ssborbis** [comment]
Are you building from source or using the Add-ons beta page?

**Comment by bdcomp** [comment]
As it's already installed, I use "Check for Updates" within my Firefox.

**Comment by ssborbis** [comment]
Will that setting check for betas?

**Comment by ssborbis** [comment]
If you want automatic updates, I think I'll need to make a separate release

**Comment by bdcomp** [comment]
Very strange, as the changelog that I got is:
> Hotfix
Manual Loading page appeared stalled when favicon wasn't found

I will wait for your separate release...

**Comment by bdcomp** [comment]
Probably the logic is:
`if releaseVer > betaVer
   update to releaseVer`

**Comment by ssborbis** [comment]
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext-lite/versions/

**Comment by bdcomp** [comment]
Separate Lite version works great.
Thank you very much!

**Comment by ssborbis** [comment]
:+1:

**Comment by EMBBlaster** [comment]
Seems this could be closed.
