### ISSUE TITLE
[Feature request] Quick menu for links and images

### ISSUE THREAD

**Issue by narcolepticinsomniac** [ssborbis/ContextSearch-web-ext#120]
Title's pretty self explanatory. Also, it'd be convenient if image search engines were restricted to images, and text search engines were restricted to text, so they aren't provided as options in scenarios where they're not useful.

**Comment by ssborbis** [comment]
Might be doable without too much of a headache by adding a {imageUrl} param to the template. Any method will require user input. i don't see how to flag reverse image engines programmatically.

**Comment by narcolepticinsomniac** [comment]
Yeah, image searches have unique strings like `q=imgurl` or `image_url=`, which I imagine is true across the board, but definitely more of a headache. A user defined param would be great though.

**Comment by ssborbis** [comment]
If there's a standard, that would be great. I could just scan the templates. No user input required

**Comment by narcolepticinsomniac** [comment]
Don't think there's a standard per se, but unique strings for all common image searches shouldn't be too difficult to account for if you want the feature to work automatically.

**Comment by narcolepticinsomniac** [comment]
I don't have tineye by default, but aren't they strictly images? Those stings above are Google and Bing. Keying on unique strings in the engine URL would work the same as keying on a user defined param, except automatic, no? Not sure which others even do reverse image, but Yandex would be `/images/search?source=`. I don't think DDG or a lot of the smaller ones even do them.

**Comment by ssborbis** [comment]
I'd prefer not to code caveats for specific engines and tagging any engine with `image` or `img_url` in the template, for instance, could accidentally break it. No telling what a user has installed or what their templates look like. Could be custom, foreign, a non-reverse image search engine, etc..

Most reverse-image add-ons are basically using the same list of engines to choose from so adding caveats maybe isn't a big deal, but it feels like bad practice for some reason. I'll mull it over though.

**Comment by narcolepticinsomniac** [comment]
You're probably right. A user defined variable would still be dope though. Something to keep reverse image engines from showing up on text, and make them the only ones that show up on images.

What was the verdict on quick menu for links and images, btw?

**Comment by ssborbis** [comment]
> What was the verdict on quick menu for links and images, btw?

I'll have to dig through some code. Default behavior is to only open when text is selected to prevent  unwanted popups.. I had forgotten you could only do links / reverse image searches with the context menu. Looks like dnd works also, but no direct click.

**Comment by ssborbis** [comment]
Seems to work ok for click and hold methods. Right now the context and quick share the same url vs text setting for links. Repo updated

**Comment by narcolepticinsomniac** [comment]
Very cool. Mostly works as expected with a couple quirks, one weird, one minor.

Weird: `http://www.jimmyr.com/`

When using quick menu on any aggregated links, instead of searching link text, it's grabbing the URL of the hover background-image and searching that:

```
a.bl:hover {
    color: #1122FF;
    background: url(../images/list_hover.gif) no-repeat 0px 3px;
    border-bottom: 1px solid #888;
}
```

Minor: 

Using quick menu to open a search doesn't seem to re-initialize right-click on links, so if you use it to open a search, then go back to the original page, if you try to immediately do a regular short right-click on a link to open the actual context menu, it won't work till you left-click the page.

Right-click outside of links works, as does long right-clicks. Only short right-clicks directly after using quick menu on a link to open search. An edge case that's well worth the trade-off if unpreventable.

**Comment by ssborbis** [comment]
>Weird: http://www.jimmyr.com/
>
>When using quick menu on any aggregated links, instead of searching link text, it's grabbing the URL of the hover background-image and searching that:

Current priority is to look or images first, then links. Lots of images are wrapped in anchors making it difficult to search the image url vs the ahref.  I could bypass the background-image check but that kills searching for any images displayed using the background property. There will always be compromises here. Eventually I'll set up options and let the user decide.

> Using quick menu to open a search doesn't seem to re-initialize right-click on links, so if you use it to open a search, then go back to the original page, if you try to immediately do a regular short right-click on a link to open the actual context menu, it won't work till you left-click the page.

I noticed this too.I'll add it to the list.

**Comment by narcolepticinsomniac** [comment]
Come to think of it, I'm not even sure if a check for a child element with an image is necessary. I look at a lot of CSS, and while images are often wrapped in links, I don't think I've ever seen a link with text wrapped around any image other than the same type of `list-style` marker.

**Comment by ssborbis** [comment]
it's a good check to run. If there's text, assume link not image

**Comment by ssborbis** [comment]
> In case it matters, it might be worth mentioning that the behavior differed on those jimmyr links, depending on if you used the traditional context menu or the quick menu. The traditional context menu searched the text content.

Context Menu uses the built-in API to get link/image info. I'll get the two menus as close as I can but there might be some discrepancies.

Busy working on redoing the options page so the next couple pushes might not have the fix

**Comment by narcolepticinsomniac** [comment]
Whenever you get around to this, another issue with background image detection is that it doesn't filter out CSS gradients. Not sure how it deals with data-images, as I haven't come across an example yet. If it does reverse searches for them correctly, they should be included, otherwise they should also be ignored.

**Comment by ssborbis** [comment]
got an example?

**Comment by narcolepticinsomniac** [comment]
Google home page, "Google Search" button:

![google](https://user-images.githubusercontent.com/14100003/49836025-29d7b600-fd6f-11e8-8ec7-b17dcf1b4c78.png)

Search ends up: `kit-linear-gradient(top, rgb(248, 248, 248), rgb(241, 241, 241)`

**Comment by narcolepticinsomniac** [comment]
Data-images seem to be no good either, when I just briefly tested.

**Comment by ssborbis** [comment]
as background or img src?

**Comment by ssborbis** [comment]
nvm, i have no handlers for uploading data uris to a reverse image search

**Comment by ssborbis** [comment]
Ok I set up a test for `^url(` . I'm not too familiar with window.getComputedStyle() but I think any backgroundImage will be in that format. It filters gradients ok
