### ISSUE TITLE
Startpage custom plugin does not work with this addon.

### ISSUE THREAD

**Issue by Zlewness** [ssborbis/ContextSearch-web-ext#13]
The Startpage search plugin works fine in the search bar or the default Firefox right click search but fails when I try on this plugin. Steps to create broken plugin:

1. Visit https://www.startpage.com/do/preferences, change any settings (I just change theme to night for testing).
2. Click "GENERATE URL", wait for the page to scroll down.
3. Click "INSTALL CUSTOM PLUGIN", accept the Firefox dialogues (I set as default for testing).
4. Reload search engines (I use the file method).

**Comment by ssborbis** [comment]
Try the latest beta.  
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta

Must be some redirecting going on.  Latest betas should take care of it.  I still have some timing issues with POST (sometimes fails with blank page) but the plugin worked for me.

**Comment by Zlewness** [comment]
You are correct, it works with the beta. Unfortunately I can't test properly because now the page is claiming it's under high load but the error matches on both this addon and Firefox's built in search.
