### ISSUE TITLE
DnD doesn't open a folder on hover (while button pressed) in quickmenu (but it works in sidebar)

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#132]
note, I am using long press right mouse button with the quickmenu.

Because I didn't use the quickmenu with this specific feature for a while (mostly testing the sidebar), I cannot say when this stopped to work. May be it never did?
I think, all sub-features of DnD were added to the sidebar. But I thought the code of the search engine area is the same for both(?), so may be it's only because of the right button vs. the left button?

If it's not obvious to see where this fails, I can test with left button etc. But this would take a while, may be at the weekend.

**Comment by ssborbis** [comment]
It probably never worked. I use a variety of listeners to cancel mouse events depending on how the menu is opened to prevent accidental clicks. One of them is probably causing the failure. I'll look

**Comment by ssborbis** [comment]
Moved some mouseup listeners to a custom event. Hopefully it didn't break anything else. I'll post it for testing.
