### ISSUE TITLE
[Suggestion] "url or text" feature should depend on search engine

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#133]
The "url or text" feature is useful, but I found myself constantly toggling it, depending on which search engines I use for some task.
E.g. wayback archive would use the link, but google would usually use the text (and I would have another search engine using the link).

So one implementation would be a **setting for each search engine**.

An alternative implementation would be a **modifier key**. Generally most search engines may be used to consume both variants, so the modifier would reduce the number of engines.

Engines that can only consume URLs (wayback, scanner, proxy, images, etc.) are definitely limited to URLs, while I cannot think of a textual engine that cannot usefully search for URLs.
So the ideal way would be a switch ("**always use URL of link**") per engine **+** a **modifier** key for all others.

**Comment by ssborbis** [comment]
Mod key makes more sense to me ( probably easiest to set up ) or some kind of toggle tool

**Comment by ssborbis** [comment]
hold CTRL to toggles default setting

**Comment by ssborbis** [comment]
With regex-matching, context-matching, and the CTRL toggle, I'd say it's past time to close out this relic
