### ISSUE TITLE
Add an option to disable the update popup.

### ISSUE THREAD

**Issue by Zlewness** [ssborbis/ContextSearch-web-ext#134]
This is the only addon I have which semi-regularly opens a new page when it updates. Is it possible to add an option to opt out of this behaviour? I'm sure the update is always significant however it interrupts whatever I was doing and irritates rather than informs.

**Comment by ssborbis** [comment]
I was actually thinking about that when I added the update script. It's been pretty rare I include update info but there have been some significant changes of late. I'll open in the background from now on.
