### ISSUE TITLE
Separate shortcuts for search-engine in context menu

### ISSUE THREAD

**Issue by mecedo** [ssborbis/ContextSearch-web-ext#14]
Is it possible to implement every search-engine as a separate item in context menu after selecting word? I mean not expanding menu "Search with" and selecting engine but every engine directly in context menu.

**Comment by ssborbis** [comment]
I think the new API lets each extension have 1 top-level menu entry only.  

From the docs

> If you have created more than one context menu item or more than one tools menu item, then the items will be placed in a submenu. The submenu's parent will be labeled with the name of the extension.

**Comment by mecedo** [comment]
Sad :( It' was very useful possibility in Context Search X which I used before 57. Very useful because I'm doing searching very often.
Thanks.

**Comment by ssborbis** [comment]
Have you tried the quick menu feature at all?

**Comment by ssborbis** [comment]
I've added an option to open the quickmenu on right-click (not hold) and open the normal context menu on long right-click in the latest beta.  It's not exactly what you're after, but it should make searches quicker if you're used to right-click ->search.

https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta

**Comment by mecedo** [comment]
I’ve tried quickmenu with holding r-button. But I couldn’t accustom to it. Now it’s much better. I think it’s better than in previous addon which I used :)

 

Many Thanks.

 

Regards.

Mecedo.

**Comment by mecedo** [comment]
And I have another suggestion for improvement. If addon will recognize left and right click on selected search engine. It would be nice if after left-click results opens in current tab and after right-click results open in new tab.

 

Regards.

Mecedo.

**Comment by ssborbis** [comment]
There doesn't seem to be a way to recognize different mouse buttons in the context menu but it could work in the quick menu.  It will take some code overhaul though. I'll try to get something for the next release.

**Comment by ssborbis** [comment]
Check the latest 1.2.5 betas
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta

**Comment by mecedo** [comment]
Thanks, but there’s a bug in this version. I’m using right button long hold to invoke quick menu. And now if quick menu appears and you release right button (for moving cursor to  search engine you need) then first search engine (where the cursor was located during holding right button) is selected suddenly. After invoking quick menu you cannot release right button until you select proper search engine. it’s inconvenient. In previous version it worked much better :)

**Comment by ssborbis** [comment]
I think I've got that fixed now.  Try 1.2.5b2

Moved a lot of code around so there's bound to be a few bugs.
