### ISSUE TITLE
find bar: option - dock vs. overlay findbar

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#144]
the findbar (or any other such extensions like download status bar) usually hides some part of the page that might be necessary, there are even fixed elements that contain buttons etc.
It's basically the same thing like with the sidebar.

In general there are two options:
* move it anywhere (dragging)
* put it outside of the page by docking it like you did with the sidebar

**Comment by hg42** [comment]
well, I originally meant "drag around -> out of the way" **or** "dock", just the same functionality like the sidebar already has.
Though, "drag to dock/undock" would be intuitive, too.

However, the bar is always near a border, so how would you drag it to a border to dock it? only at a few pixels near the border?

**Comment by ssborbis** [comment]
> well, I originally meant "drag around -> out of the way" or "dock", just the same functionality like the sidebar already has.

Ah you were thinking sliding along the border. I went and made it more complicated.

> However, the bar is always near a border, so how would you drag it to a border to dock it? only at a few pixels near the border?

That's what I was thinking. Snap to border when close, drag away to have a fixed position, floating iframe that could be placed anywhere with the position saved sort of like PS / gimp or any number of apps use.  Sometimes it would be nice to grab one of those frames (sidebar, findbar) and move it somewhere else temporarily.

**Comment by ssborbis** [comment]
The lastest push has code to sniff out fixed divs and "dock" the findbar out of the way. I've tested on several sites with fixed banners and it seems to work pretty well. I don't see much need to add dock / undock functionality to the findbar if this latest fix works most places.

**Comment by hg42** [comment]
not sure if I see a difference on the pages I remember :-)
E.g. facebook, the right messenger column has a search field that is hidden behind the full width findbar.
For me, most page footers are still hidden, e.g. in google pages like
* calendar bottom left
* quasar v1 https://v1.quasar-framework.org/start/pick-quasar-flavour
* discord (my user entry bottom left and the last user bottom right cannot be accessed without moving the findbar away)

Thankfully, we can now move it around (nice!) and it switches to the minimum width (good!).
And I can now enable/disable with the same keys, which is most convenient if I opened it via the shortcut.

Also nice that I can go back to full width with double clicking the drag handle.
