### ISSUE TITLE
findbar options: hide highlights, hide highlight overview

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#146]
* sometimes highlighting makes reading difficult

* the highlight overview isn't always useful
* the highlight overview sometimes prevents clicking on some button etc.

not sure about the overview because of #145 , if it's docked it doesn't disturb much, but if it's not docked it's sometimes necessary to switch it off (without loosing search capabilities and highlighting)

**Comment by ssborbis** [comment]
> sometimes highlighting makes reading difficult

I've added an option to style highlighting by underline instead of background/foreground color. It's much more subtle and I'll make that the default option

> the highlight overview isn't always useful

I'll add an option to disable when using findbar

> the highlight overview sometimes prevents clicking on some button etc.

Let;s use #145 for discussing the overview

**Comment by hg42** [comment]
I already chose light colors, which I find more attractive than underlining.
I was mainly talking about pages with many find-spots (correct word?). It's a huge mosaic of colors then.
In such cases the highlighting isn't useful and I would disable it temporarily.

**Comment by hg42** [comment]
to be clear:

I can already close the highlight overview bar, but the button is small and far away in the other corner.
Also, the highlighting itself is independent from the overview.
Sometimes the findbar is open, but the overview is not.
So ideally two buttons in the findbar would be convenient.

Another thought I had today:
When using a search engine, the search page itself contains quite a lot of highlighted items, which isn't really necessary/interesting, but the pages opened from the search page are.

**Comment by ssborbis** [comment]
FYI, pressing ESC clears the highlighting also. 

> Another thought I had today:
When using a search engine, the search page itself contains quite a lot of highlighted items, which isn't really necessary/interesting, but the pages opened from the search page are.

There is an option to continue highlighting on external pages. I forget if it's on by default.

**Comment by ssborbis** [comment]
> Yes, I am using the "continue" functionality. My thought was to only use it on these pages but not on the search page itself.

Maybe a 'disable highlighting on ...' list would work? Add an entry to the context menu somewhere, the browser_action icon perhaps with a checkbox?

**Comment by hg42** [comment]
this would work, but I am not sure if it's worth the hassle.
Two toggle buttons for highlighting and overview should do well enough (with persistency).
Automatic solutions always carry the risk to not cover all cases.

**Comment by hg42** [comment]
btw. there are also cases, when highlighting is off and I want it on. Or even cases when I switch between reading and searching on the same page, I would eventually switch it on and off multiple times. So buttons seem to be the best solution.

I can think of three buttons highlighting, overview and one that toggles both. Not sure which I would use frequently.
"Both" might be unnecessary or the one used most often.
In general it should be independent.
The highlighting depends on the number of spots and how it disturbs reading, the overview is only a problem when hiding something.
Would I use overview without highlighting? eventually to quickly jump to places (but this should be more useful with highlighting).
Would I use highlighting without overview? sure. So a three state button could be a possibility "off", "on", "with overview".
Or two buttons, where overview would be active only if both are on (second would be "with overview").

**Comment by bottleblue** [comment]
Can you make an option to have your findbar replace FF's default findbar when pressing Ctrl+F or clicking its toolbar icon? 
I also hate that pressing the hotkey again does not close the findbar (FF's or yours). This seems like it would be an intuitive thing. It could be a little bigger too. I think FF's findbar is a perfect size.

**Comment by ssborbis** [comment]
@bottleblue 

> Can you make an option to have your findbar replace FF's default findbar when pressing Ctrl+F or clicking its toolbar icon?

Technically, you can use ctrl-F to override the default findbar right now, but you can't set the option because attempting to immediately opens the FF default findbar preventing the key from being set in Options. I'm fixing that now, but you should be able to set the option in the console.

1. Open the ContextSearch options page
2. Press Shift+Ctrl+K to open the console ( or Tools->Web Developer->Web Console )
3. Paste this code into the console input and press enter `userOptions.highLight.findBar.hotKey = [17, 70]; saveOptions();`

That should set the key combo to Ctrl-F

> I also hate that pressing the hotkey again does not close the findbar (FF's or yours). This seems like it would be an intuitive thing

Yeah I can do that, but it should only close when no text is selected.

> It could be a little bigger too. I think FF's findbar is a perfect size.

I sized them the same to as far as I can tell. Do you mean width? On the next update, the findbar will span the full width of the browser with better code for offsetting the page top so the findbar doesn't cover headers and banners. 

@hg42 

I'm still playing around with fixed div offsets but I'll get to the buttons soon.

**Comment by bottleblue** [comment]
> I sized them the same to as far as I can tell. Do you mean width? On the next update, the findbar will span the full width of the browser with better code for offsetting the page top so the findbar doesn't cover headers and banners.
> 

I mean the textbox and up/down buttons are wider (which is fine) but shorter in height than FF's. The size of the findbar in general looks to be slightly shorter than FF's.

I actually like and prefer that your findbar does not span the full width because I find that to be pointless and just covering up that area for no reason.

**Comment by ssborbis** [comment]
@bottleblue 

>I mean the textbox and up/down buttons are wider (which is fine) but shorter in height than FF's. The size of the findbar in general looks to be slightly shorter than FF's.

I've added about 4px in height to those elements along with some beautification. It does look better. Eventually I might add a scale option.

> I actually like and prefer that your findbar does not span the full width because I find that to be pointless and just covering up that area for no reason.

Then prepare to be disappointed. 

I'll add a panel / overlay option like I did with the sidebar eventually and leave it up to the user. There were several reasons for going full width. One being the addition of more buttons on the findbar to control highlighting, nav bar, etc. It's gonna get a bit wider no matter what.

**Comment by bottleblue** [comment]
> I've added about 4px in height to those elements along with some beautification. It does look better. Eventually I might add a scale option.

sounds good


> Then prepare to be disappointed.
> 
> I'll add a panel / overlay option like I did with the sidebar eventually and leave it up to the user. There were several reasons for going full width. One being the addition of more buttons on the findbar to control highlighting, nav bar, etc. It's gonna get a bit wider no matter what.

I guess if you're offseting the page top then the page is going to be shorter regardless if the bar is full width or not. I personally don't mind the bar covering up the header like it does now. I think it looks nicer when it's compact but it's not a big deal. I'm sure it'll be fine either way :)

**Comment by ssborbis** [comment]
@hg42 

Buttons for toggling navbar & highlighting have been added. The highlight toggle should mark / unmark for the current page but continue following links if those options are set. Right now, closing the findbar or pressing ESC will clear the highlighting and remove that tab from the highlighting tree.

**Comment by hg42** [comment]
nice...I am happy with it...

**Comment by hg42** [comment]
oh, wait...now the active item isn't highlighted any more? It has the same color like the other highlights.
...ah, if I enable blinking it does...so I guess you are testing with blinking.

**Comment by ssborbis** [comment]
> oh, wait...now the active item isn't highlighted any more? It has the same color like the other highlights.
...ah, if I enable blinking it does...so I guess you are testing with blinking.

Oops, I rearranged some CSS and screwed up the specificity. It's fixed. Just waiting to push

**Comment by bottleblue** [comment]
Are you still planning on making your find bar replace FF's find bar when pressing Ctrl+ F?
Also the findbar options (case sensitive, punctuation, highlight, etc.) get reset everytime you open them. I prefer to have them remembered.
Can you have the findbar stay up when changing tabs?

**Comment by ssborbis** [comment]
@bottleblue 

> Are you still planning on making your find bar replace FF's find bar when pressing Ctrl+ F?

You can set the findbar hotkey to whatever you want. If you use Ctrl + F, it will override the default find bar and show the contextsearch version instead. Just click on the current hotkey in Options->Highlight->Findbar->Opening and press a key combo.

> Also the findbar options (case sensitive, punctuation, highlight, etc.) get reset everytime you open them. I prefer to have them remembered.

I'll add an option

> Can you have the findbar stay up when changing tabs?

So you want the option to open the findbar in one tab and have it be opened in all currently opened tabs with highlighting?

**Comment by bottleblue** [comment]
> You can set the findbar hotkey to whatever you want. If you use Ctrl + F, it will override the default find bar and show the contextsearch version instead. Just click on the current hotkey in Options->Highlight->Findbar->Opening and press a key combo.

I already tried it. It still opens the default find bar.

> So you want the option to open the findbar in one tab and have it be opened in all currently opened tabs with highlighting?

Highlighting can be optional but yea have it open it all tabs.

**Comment by ssborbis** [comment]
> I already tried it. It still opens the default find bar.

Odd. I tried in Chrome and FF and it only opens the CS toolbar. Did you reload your tabs after changing the setting to Ctrl-F?

**Comment by bottleblue** [comment]
Nvm about the find bar thing. I was using a custom css tweak that turned the quick find bar into the full find bar. That must have been screwing with your find bar. Removing that code fixed it.

**Comment by bottleblue** [comment]
Thanks for the new update. However when I said I wanted the findbar open in all tabs I also meant with the current word in the search box included. So if I'm searching for something in multiple tabs I don't have to type the same word over and over.

Another thing I noticed is if I press Ctrl+F twice it will open your findbar and firefox's findbar. Is that just me?

**Comment by ssborbis** [comment]
@bottleblue 

> Thanks for the new update. However when I said I wanted the findbar open in all tabs I also meant with the current word in the search box included. So if I'm searching for something in multiple tabs I don't have to type the same word over and over.

I wasn't sure that was what you were after so I left the option out for simplicity, but the code is basically there. Would you want the `search all open tabs` option as a toggle button on the find bar?

> Another thing I noticed is if I press Ctrl+F twice it will open your findbar and firefox's findbar. Is that just me?

I've been using Ctrl+F without issue, but I did make some changes to the way hotkeys are handled and there could be a bug somewhere. You could try resetting your hotkey in options to see if that makes any difference, but the handler should be capturing the hotkey and cancelling the default behavior ( FF find bar ).

**Comment by bottleblue** [comment]
> I wasn't sure that was what you were after so I left the option out for simplicity, but the code is basically there. Would you want the `search all open tabs` option as a toggle button on the find bar?
It doesn't matter to me. But I guess more options are better?

> I've been using Ctrl+F without issue, but I did make some changes to the way hotkeys are handled and there could be a bug somewhere. You could try resetting your hotkey in options to see if that makes any difference, but the handler should be capturing the hotkey and cancelling the default behavior ( FF find bar ).
I did try resetting it but it still happens. If I spam Ctrl+F it will bring up both findbars but if I press it slowly it doesn't happen. Binding it to Ctrl+G (FF's Find Again) does the same thing. I tried Ctrl+H and the problem didn't occur. Seems like an issue with the default FF binds.
