### ISSUE TITLE
[idea] extend monogram icon functionality

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#149]
Generating an icon from a small text string would help to distinguish engines, especially when several use the same favicon, like all these google engines.

I am thinking of a small string, may be 1-3 characters, that would be rendered like the monogram icon?
A configurable color would help, too.
it could use a custom protocol name, some ideas:
```
CS:abc?color=red             (create "abc" icon)
generate:img?color=green     (create "img" icon)
genimg:?color=green&text=GI  (create "GI" icon for google images)
```

**Comment by ssborbis** [comment]
The code to handle generating the icons is trivial since it's mostly there already. I'll have to think on how to integrate the UI / scheme. In the meantime, you could make custom icons in PS/GIMP and use the data URI.

**Comment by ssborbis** [comment]
I probably need to add a dnd / local file handler for the icons too

**Comment by ssborbis** [comment]
Last push has a handler to test

`generate:?text=abc&textColor=white&backgroundColor=#2200ff&fontSize=10px&width=16&height=16&fontFamily=Georgia`

Or if you wanted to use mostly default settings

`generate:?text=abc&fontSize=10px`

**Comment by hg42** [comment]
(sorry for answering late, I was kind of offline for some time)

this is awesome...it is already very useful...thanks
the colors make visually grouping a breeze
using percent for the font size is very convenient (I hope the font would be scaled with the icon?)
I found a sans font easier to read and more compact for such a small size (nice that I can change it, though a some defaults would be nice instead of entering the same sequence in all items, hmm, oh, may be unnecessary because I can add this to my custom css, will try).

Eventually, could the icon displayed in the list be updated live while changing the icon url?
or better, an icon displayed near the input field, so it could be compared to the saved icon?

**Comment by hg42** [comment]
sorry, why the hell do I press "close and comment"?

**Comment by hg42** [comment]
> you could make custom icons in PS/GIMP and use the data URI

you are right...why disn't I think about it...I could even write a script to compose icons.
E.g. I would like to compose icons for goole search engines from the main google icon with an overlay of some letter(s) or another icon that symbolizes which kind of search it is.
Then, as you said, a drop handler would be useful...

**Comment by hg42** [comment]
still working :-)
