### ISSUE TITLE
SeaMonkey Support

### ISSUE THREAD

**Issue by Nz17** [ssborbis/ContextSearch-web-ext#15]
Could you please add support for Mozilla SeaMonkey to your XPI's?  I'd appreciate it very much.  Thank you.

**Comment by Nz17** [comment]
Thanks for investigating.  I also tried what you tried, and I tried to install a modified version of the old Context Search, but both were to no avail.  I'm looking forward to your future progress!

**Comment by ssborbis** [comment]
I tried the most basic WebExtensions example I could find (bordify) and it wouldn't work with the latest SeaMonkey release. It installs but doesn't seem to execute the content scripts. Unless it's an issue with temporary add-ons, I'm not too optimistic about getting my extension to work. Have you had any luck with other webextensions?

**Comment by Nz17** [comment]
I see.  How about the newest nightly from <https://www.seamonkey-project.org/dev/nightly>?  I believe SeaMonkey 2.57 is supposed to be the equivalent of Firefox 60.  Thanks again for your efforts. :-)

**Comment by ssborbis** [comment]
Tried the nightly and no difference. Unless I'm missing something, it looks like the API for the new WebExtensions standard is completely missing from SeaMonkey. I haven't dug through the code though.

**Comment by Nz17** [comment]
Thanks for looking.  I guess SeaMonkey is in an odd point in its history where it's playing catch-up to Firefox and where its Gecko engine is.  I guess integration of WebExtensions is in its nascent stages, i.e. preparations.

It's a shame - at this point, the SeaMonkey internals are too old for earlier extensions and too young for newer extensions.

**Comment by ssborbis** [comment]
Yeah the WebExt API is still evolving so maybe the SeaMonkey devs are waiting for the changes to settle before implementation.

I saw this on one of the SeaMonkey support sites

>https://wiki.mozilla.org/RapidRelease/Calendar 

Looks like Mozilla is keeping the ESR line updated at least until 2019. That gives the SeaMonkey team time to migrate code without falling too far behind the updates. I just don't know how much legacy support the devs have to break to implement the new API or how eager they are to do so. There didn't seem to be much talk about it in the dev forums.

**Comment by ssborbis** [comment]
I've tested this addon with FF 60ESR and it appears to be working fine. When SeaMonkey drops their v2.57 release based on 60ESR, it should be compatible.
