### ISSUE TITLE
javascript: url as search engine results in "ReferenceError: error is not defined"

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#150]
I used e.g. `javascript:console.log('{searchTerms}')` as url

the error is triggered at:
```
background.js:898:25

function onError() {
    console.log(`Error: ${error}`);   <---------------
}
```

**Comment by ssborbis** [comment]
See https://github.com/ssborbis/ContextSearch-web-ext/issues/147#issuecomment-465119926
