### ISSUE TITLE
Please add option to disable drag resize popup.

### ISSUE THREAD

**Issue by mmqmzk** [ssborbis/ContextSearch-web-ext#152]
I have a habit that clicking the text on web pages when reading, so sometimes resize the context search popup by mistake, then sometimes the popup cannot be resized back by drag, so I have to open the extension configure page to reset popup options, maybe it is a bug. Please fix it or add an option to disable this feature. Thanks.

**Comment by ssborbis** [comment]
Let me see if I have this correct so I can do some proper testing. Are you using the Auto method of opening the quick menu and it's positioned in such a way that when you click (double click?) text, the menu opens and the resize icon is under your mouse and it's starting a resize event that gets screwed up?

In any case, you can add the following style to CS Options -> General -> User Styles to hide the resize

`#CS_resizeWidget { display:none !important; }`

**Comment by hg42** [comment]
oh, I didn't notice we can now resize the quick menu, nice.
(now, could you add that to sidebar, too :-) )

**Comment by ssborbis** [comment]
> oh, I didn't notice we can now resize the quick menu, nice.
(now, could you add that to sidebar, too :-) probably at both lower corners)

I'm slowing migrating the sidebar code to use the same dock / undock methods as the findbar. When I get that done I'll look into adding the resize.

**Comment by mmqmzk** [comment]
Ok, I will use the custom user style, thanks.

**Comment by mmqmzk** [comment]
The custom CSS no longer take effect after upgrade to 1.9.7, because of the CS_resizeWidget is no longer an id but a class name. Just change the CSS to `.CS_resizeWidget { display:none !important; }`
