### ISSUE TITLE
small suggestion: error message misleading

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#153]
this situation is misleading for average users:

![screenshot_20190220_155406](https://user-images.githubusercontent.com/4707597/53100376-f3b17200-3527-11e9-9309-699285bd1c35.png)

after getting the message, I added the `{searchTerms}`, but the message wasn't cleared.

Also, when I first saw this "small capitals" font, I thought, that I have to use "all capitals".
Fortunately I knew this unusual font, so the bigger T made it clear enough for me, but I think average users will be confused.
Though, I am not totally sure why I get this font, is it only me?

**Comment by ssborbis** [comment]
> Though, I am not totally sure why I get this font, is it only me?

Nah, that's the font I've been using for section headers. Instead of changing the font, I think I'll regex replace any variation with the correct terms so anything resembling {searchTerms} is accepted

**Comment by ssborbis** [comment]
`...replace(/{searchterms}/i, "{searchTerms}");` works well

**Comment by ssborbis** [comment]
I also set error messages to clear on `Save`. That was confusing

**Comment by hg42** [comment]
thanks...working

According to this, I am not sure or it is not obvious, what happens if an error message appears.
An additional "(saved anyways)" or "(not saved)" could be helpful.

However, I would think, if there is no `{searchTerms}` variable, it could be saved and just not filled in when invoked.
At least the test "search engine" should still work (because it's really a bookmark, which would also be useful to have).

It would be also be nice to be able to save it with errors (at least if I say so, perhaps in two stages, so if I press "Save" again, it could be saved with the error).
This would also be useful to just save the wrong content and come back later.
Actually the old content is already gone, so it could also be saved directly, because I can get it back by `^Z` in both cases.

**Comment by ssborbis** [comment]
There are a few errors that are fatal and can't be saved like name errors, but template errors should be ok ( searches will fail silently )

I'm using a simple fade-out notice when clicking `Save`
I've added messages for `saving` and `saving with errors` and I'll add a message for `cannot save` as well. 

![save](https://user-images.githubusercontent.com/24310997/54747979-56854000-4b9e-11e9-8790-0867f07e6ec2.gif)

**Comment by hg42** [comment]
awesome :-)

**Comment by ssborbis** [comment]
Went with a simpler ✓ or X and errors are displayed when you open the engine for editing. Most people should get the message.

**Comment by hg42** [comment]
thanks, the ✓ is nice and clear.

I also appreciate that I can copy the {searchTerms} from the error message.
