### ISSUE TITLE
changes for 1.9.6 - released

### ISSUE THREAD

**Issue by ssborbis** [ssborbis/ContextSearch-web-ext#154]
Installation fix for FF 66+ !
Installing CS on beta versions of FF was failing due to the migration from storing user prefs in JSON to IndexedDB. There was a timing issue with the CS version check and prefs update that should be fixed in 1.9.6.

- added opacity options to highlighting
- fix for setting key combos using extended ascii keys
- fix for setting key combos that conflict with built-in shortcuts
- search form templates accept all protocols for urls
- menu scaling fix for some websites
- menus scale on page zoom
- custom search engines icons can be generated using a custom URI in the Icon URL field ( example: generate:?text=abc&textColor=white&backgroundColor=#2200ff&fontSize=10px&width=16&height=16&fontFamily=Georgia )
- local images can be imported as icons using the file browser
- bookmarklets can use the variable CS_searchTerms in scripts
- hiding menus on fullscreen is now default behavior - options removed
- findbar accepts regex patterns
- findbar can be docked / undocked and moved
- added buttons for toggling highlighting and navigation bar to findbar
- findbar searches can be performed automatically after a typing timeout
- hotkey closes findbar
- hotkey closes sidebar
- errors in the search engine manager edit form reset properly
- templates accept {searchTerms} in upper/lowercase

@DenB10 
I added a few new i18n strings

**Comment by streetwolf** [comment]
Changing the size of the Quick Menu text and icon does not change the size the way it did in the previous version.  The size increases as you specify higher sizes but they all are very small. Also the resizing arrow will appear well outside the menu depending on how large you set it's size.  At the max size it is very far from the menu. It's almost as if the resizing arrow thinks the menu is as large as it was in the previous version.  Using HiDPI if you remember our discussions.  Also still having the issue with msn.com as previously discussed.

**Comment by ssborbis** [comment]
I'll get a hotfix for the quick menu scaling ASAP.

**Comment by ssborbis** [comment]
@streetwolf 

1.9.6.1 going up now. I checked at 150% zoom in windows display settings with a couple different Quick menu scale settings and it seemed ok to me, even on msn. Let me know.

**Comment by streetwolf** [comment]
Will do.


-----
Gary

________________________________

**Comment by streetwolf** [comment]
Quick  Menu is scaling properly now.  However msn.com is still not right.  Not only is the Quick Menu lower than it should be I have to hold on to the mouse button in order to move my pointer over it.

![qm](https://user-images.githubusercontent.com/410799/53263835-8416c080-36a8-11e9-86b5-c7d20a21e015.jpg)

**Comment by ssborbis** [comment]
what do you have your QM scale set to?

**Comment by streetwolf** [comment]
150% for both menu and icons.


-----
Gary

________________________________

**Comment by ssborbis** [comment]
Yeah I am not seeing that behavior, even using the same url, qm scale, DPI, page zoom. What's your qm position and h/v offets?

**Comment by streetwolf** [comment]
[cid:image003.jpg@01D4CAB7.A4CA8A30]


-----
Gary

________________________________

**Comment by ssborbis** [comment]
@streetwolf 

- broken image - 

I tested with some random settings and didn't see any change.

I've tested on FF and chrome, no issues. You're using FF on windows 10, correct?

Do you have any userCSS that would be interfering? I just cant figure it. CNN looks good too, and that was the real headache last time.

**Comment by streetwolf** [comment]
On Windows 10 Pro 64 bit.  Also on the latest Fx Nightly 64 bit.

Not using userCSS.  CNN also works fine for me.  Let me try the add-on on a new profile.  Be right back.


-----
Gary

________________________________

**Comment by streetwolf** [comment]
New profile with CS and it’s defaults.  Menu is still lower than it should be on msn.com.  I don’t have to hold the mouse button down in order to move my pointer over an icon.  This part might be caused by another add-on.


-----
Gary

________________________________

**Comment by ssborbis** [comment]
I got it to glitch on the nightly. I'll let you know when I have something

**Comment by streetwolf** [comment]
The mouse button issue is caused by this add-on https://addons.mozilla.org/en-US/firefox/addon/absolute-enable-right-click/  Through this add-on I have made msn.com right clickable.  This is the only site I use the add-on.  This is why it only happens on msn.com.  I just disabled the add-on and the mouse button works as it should


-----
Gary

________________________________

**Comment by ssborbis** [comment]
Not sure if this is a bug in the nightly or a change in layout handling.

Testing on https://www.msn.com/en-us/news/politics/the-house-will-vote-tuesday-on-blocking-trumps-national-emergency/ar-BBTUHRd?li=BBnb7Kz

Toggling the document.body CSS property `position:relative` off fixes the positioning issue in FF67 nightly. In FF65, there's no effect and the menu displays where it should.

Setting the first child of document.body, element `<div class="head">` with the css properties

```
body:not(.view_overlay) div.head::after {
    background: linear-gradient(to left,rgba(255,255,255,0),rgba(0,0,0,.1));
    right: calc(50% - 81.2rem);
}
body:not(.view_overlay) div.head::after, body:not(.view_overlay) div.head::before {
    content: '';
    display: block;
    height: 100vw;
    position: absolute;
    top: 0;
    width: 1.2rem;
}
body:not(.view_overlay) div.head::before {
    background: linear-gradient(to right,rgba(255,255,255,0),rgba(0,0,0,.1));
    left: calc(50% - 81.2rem);
}
element {
    display: none;
}
div.head {
    background: #fff;
    border-bottom: solid .1rem rgba(0,0,0,.2);
    height: 8rem;
}
#conditionalbanner, div.head, div#maincontent, div#mestripebg, div.scrolled #header-common::before, #foot, #precontent, #precontent div#filmstripouter, #prefooter, #refreshbar, .uhf .euBanner {
    width: 160rem;
}
#conditionalbanner, div#mestripebg, div.head, div.scrolled #header-common::before, #foot, #precontent #filmstripouter, #refreshbar, .uhf .euBanner {
    left: calc(50% - 80rem);
}
.head {
    background: #f4f4f2;
    height: 11.8rem;
    left: 0;
    position: fixed;
    top: 0;
    width: 100%;
    z-index: 30001;
}
*, ::after, ::before {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}
body, .h1, h1, h2, h3, h4, h5, h6, th {
    font-weight: normal;
}
body, button, input, select, textarea {
    font-size: 1.5rem;
    line-height: 1.467;
    font-family: "Segoe UI","Segoe WP",Arial,Sans-Serif;
}
body {
    color: #333;
}
element {
    font-size: 62.5%;
    --cs-zoom: 1;
}
```

to `display:none` also fixes the issue. For some reason, the parent `document.body` is being shifted down, relative to the child `<div class="head">` causing the Quick menu to be offset by the height of the child div / shift.

**Comment by hg42** [comment]
> mouse button issue ... right click

as a side note:
I use something similar, but I changed it to enable right click menu only when also pressing shift (or whatever you like or can configure). This way the usual functionality of Google Drive and similar sites still work as expected.
