### ISSUE TITLE
quick menu: open several search engines, then close menu on last one

### ISSUE THREAD

**Issue by githubeing** [ssborbis/ContextSearch-web-ext#159]
my desirable use case is to open several search engines:

> 1. select text
> 2. quick menu opens
> 3. middle click on any item of quick menu
> 4. it opens in new background tab
> 5. the quick menu doesn't close
> 6. repeat step 3--5 as needed
> 7. finally, left click on any item
> 8. the quick menu closes
> 9. the clicked item opens in new tab (focused)

the key feature is that steps 3--6 are optional, therefore in everyday usage i omit them, but sometimes when i need to open several search engines at a time, i may easily go through all the steps

on step 3, if the item is a folder, i'd like that all its subitems open in new background tabs

on step 6, if the item is a folder, i'd like to right click this folder, and all its subitems open in new background tabs, and the tab with last subitem gets focused

in order to achieve the use case above, i could enable the following `search actions` options below:

> left button
> search engines: open in new tab (focused)
> folders: open folder
> 
> middle button
> search engines: open in background tab & keep menu open
> folders: open in background tab & keep menu open
> 
> right button
> folders: open in new tab (focused)

unfortunately, currently the extension doesn't allow me to:

1. select `open in background tab` & `keep menu open` actions simultaneously
2. select `open in new tab` action on `folders` column

could you please implement it?

btw, i don't understand why at all does user need to `open in background tab` if the quick menu closes immediately? imo, the `open in background tab` should always be coupled with `keep menu open`, otherwise it doesn't make sense imo 🤷

**Comment by githubeing** [comment]
P.S.: Chromium Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on Ubuntu 18.10 (64-bit)

**Comment by ssborbis** [comment]
I'll need think on how to set it up. Maybe another selection or checkbox for keeping the menu open.  One issue will be the toolbar search. I have 3 menus that share the qm search actions, but the toolbar is unique in that I have no control over keeping it open. It will always close when losing focus making any option to keep open useless. 

A simpler way to solve your issue may be to add a close option to the qm on tab unfocus and set the option to keep the menu open after a search to `true`. If you're default search behavior is to left-click to open a new tab in the foreground, that would always close the qm even with the `keep menu open` option enabled.

> btw, i don't understand why at all does user need to open in background tab if the quick menu closes immediately? imo, the open in background tab should always be coupled with keep menu open, otherwise it doesn't make sense imo

Personally, that's the behavior I use the most. I tend to search for terms in the current page, sending them to the background and continue browsing the page, checking the search results later.

**Comment by githubeing** [comment]
not sure what is the best way to do this. this is so many different cases, that it's difficult to understand how to fit them all nicely without making the ui complex to a user. 

imo the variant that requires the fewest changes is to add an option `open in background & keep menu open` to select box and an option `open in new tab` to `folders` select box. 

but "the fewest changes" doesn't necessarily mean "the best and most clear". donno 🤷

**Comment by ssborbis** [comment]
@githubeing 

Added `Open In Background Tab (Keep Menu Open) option to search engine actions. 

fyi I just released 1.9.7 so most of your suggestions / issues should be sorted out after the update.

**Comment by githubeing** [comment]
> I just released 1.9.7
currently available version at chrome store is 1.9.6.1. will the version you're talking about will be available there soon?

**Comment by ssborbis** [comment]
Might have taken a few minutes for the changes to show, but I'm seeing
1.9.7 in the store now

**Comment by ssborbis** [comment]
Welp, it shows 1.9.7 in the Chrome store, but my dashboard shows "Publishing in progress" so give it a few.

**Comment by ssborbis** [comment]
Should be up now. I had to cancel and republish due to this bug

https://stackoverflow.com/questions/25084330/chrome-extension-stalls-in-publishing-in-progress

**Comment by githubeing** [comment]
current behavior is inconsistent: the same action `open in background tab` behaves differently on folders and search engines: on folders it leaves the qm open and on search engines it closes the qm. 

as i can see, currently the `open in background tab` action on folders means the same as `open in background tab (keep menu open)` in search engines. and the `open in background tab` on search engines doesn't have an analogue on folders at all. this confuses the user imo

**Comment by ssborbis** [comment]
Folders have always been Keep Open. I didn't want to up and change the behavior on everyone

**Comment by githubeing** [comment]
the important thing is that it **works** :) :+1: 
and how it is called - is not so important :)
