### ISSUE TITLE
Problem with character encoding

### ISSUE THREAD

**Issue by toto-1** [ssborbis/ContextSearch-web-ext#16]
Hi,

The search plugin "Diccionari de la Llengua Catalana - multilingüe", apparently uses WINDOWS-1252 character encoding. The plugin can be obtained here:
http://mycroftproject.com/search-engines.html?name=Diccionari+de+la+Llengua+Catalana+-+multiling%C3%BCe

When using it with ContextSearch-web-ext Lite 1.2.6.1, some problem occurs with special characters, e.g. ü, ç are changed to ª, § respectively.
When searching for special characters using the Firefox search bar, there's no problem.

**Comment by ssborbis** [comment]
I'll take a look. I'm using the TextEncoder polyfill here https://github.com/inexorabletash/text-encoding for character encoding. It's been pretty good for Asian characters so far but I haven't tested a ton.

**Comment by ssborbis** [comment]
Would you mind trying to add a search engine from the console?  It's from an API I'm working on for future releases.

`window.external.AddSearchProvider("http://opensearch-api.appspot.com?SHORTNAME=www.multilingue.cat&DESCRIPTION=Diccionari%20Multiling%C3%BCe&TEMPLATE=http%3A%2F%2Fwww.multilingue.cat%2Fcgibin%2Fmlt00x.pgm%0A&POST_PARAMS=GECART%3D%7BsearchTerms%7D&METHOD=POST&ENCODING=UTF-8&ICON=http%3A%2F%2Fwww.multilingue.cat%2Ffavicon.ico");`

It's basically the same engine you're using but with the encoding changed to utf-8.  Try your searches and let me know if it's working like it should. I'm wondering if the Windows-1252 encoding is unnecessary or if the built-in toolbar search functions are using another method to set the encoding.

**Comment by toto-1** [comment]
Thanks for the idea.
Adding the search plugin in the way you propose leads to the correct results when using the context search; however, before you get to the search result page you first see an error 500 page and then you are forwarded to the results page (which is a somewhat annoying but probably the fault of the page itself).
Secondly, now searching for special characters from Firefox's own search bar through the newly added search engine shows problems with character encoding (ç becomes Ã§).
So Firefox and ContextSearch-web-ext somehow handle encoding differently.

I had actually played with changing the encoding to UTF8 and the form handling from GET to POST on the mycroft plugin page, getting the same results as with your idea.

**Comment by ssborbis** [comment]
Ok, I think I've got it solved.

Invalid (ContextSearch)
`http://www.multilingue.cat/cgibin/mlt00x.pgm?GECART=%fcber`

Valid (Mycroft plugin)
`http://www.multilingue.cat/cgibin/mlt00x.pgm?GECART=%FCber`

Looks like I need to uppercase the url encoded symbols, %fc to %FC.  I'll need to do some googling, but using uppercase is probably the standard across all character encodings. The lowercase encodings have been working everywhere I've tested previously so I'm guessing most servers read %xx to the proper symbol regardless of case. This particular server must not. I'll get a patched release up soon after I'm confident going to uppercase won't break anything.

**Comment by ssborbis** [comment]
Oh, and the error 500 is a result of how the add-on handles POST engines. Some engines that use POST wont work if the search originates from outside the host domain. To get around this, the add-on navigates to the url listed in the OpenSearch plug-in template before executing the search. Not all template urls are valid webpages so occasionally you'll see some weird behavior before the search executes. You won't see this with GET engines.

**Comment by toto-1** [comment]
That sounds great! Thank you!
In case that changing the url encoding to uppercase results in any troubles, please tell me and I will try to contact the people behind the web page.

Also thanks for the explanation on the error behaviour. Maybe for the sake of simplicity I will keep it GET.

And finally a suggestion, not sure if it's a improvement: Would it make sense to use the url in `<moz:SearchForm></moz:SearchForm>` to avoid the error 500 in the POST case?

```
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"
                       xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>Diccionari</ShortName>
  <Url type="text/html" method="post" template="http://www.multilingue.cat/cgibin/mlt00x.pgm">
    <Param name="GECART" value="{searchTerms}"/>
  </Url>
  <InputEncoding>UTF-8</InputEncoding>
  <moz:SearchForm>http://www.multilingue.cat/</moz:SearchForm>
</OpenSearchDescription>
```
(example, shortened)

**Comment by ssborbis** [comment]
That's definitely the better way to handle the landing page for POST searches. I'll put it on the to-do list.

**Comment by ssborbis** [comment]
Beta up

https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta

- url encoding uses uppercase letters only for symbols for broader server support (i.e. old way ü->%fc, new way ü->%FC
- <moz:SearchForm> urls are now used for POST landing pages

**Comment by toto-1** [comment]
I tested the ContextSearch web-ext Lite version and everything works well, no problems with character encoding in the dictionary and the new POST landing page also works.
If the option exists, I think it's preferable to use GET with contextSearch since it will be quicker.

Thanks for this very useful plugin!

**Comment by ssborbis** [comment]
Thanks for the feedback. 

FYI, You might need to reload your search engine list to take advantage of the new POST landing handler.
