### ISSUE TITLE
toolbar: not to save previous query, keep input clear

### ISSUE THREAD

**Issue by githubeing** [ssborbis/ContextSearch-web-ext#161]
when i open the toolbar, the input is populated with my previous query. could you add an option that it'd always open empty?

**Comment by ssborbis** [comment]
Sure

**Comment by hg42** [comment]
hmm, I think we already have both worlds in one.
By providing the previous input but selected, you can:
* start writing, the selection will be replaced
* start e.g. with a cursor movement or some mouse action, the selection is removed and you can edit the text
This is kind of standard behavior.

**Comment by githubeing** [comment]
@hg42, current behavior has two drawbacks:

1. first one is a privacy issue. previous input is displayed always, and what if i don't want people behind my back to see my previous input?
2. if i want to:

> 1. select text somewhere, where quick menu doesn't pop up (e.g. in textarea or outside of browser, e.g. in notepad)
> 2. in linux, selected text is automatically put into special "middle-click-clipboard". windows also allows that, this is VERY handy! (but on windows one have to install special programs for that, while in ubuntu this is an out-of-the-box feature, provided alongside with gnome)
> 3. open toolbar
> 4. paste previously selected text via middle click
> 5. search

-- in this case i want the input be empty at step 3, because if not, it'll mess up with pasted text. btw, even if i want to remove current text, there's no `clear` button, thus i have to right-click it and select `cut` action, polluting my regular clipboard by this, OR i have to use keyboard (e.g. `delete`) which i put away very often. this action doesn't have to force me use keyboard

**Comment by ssborbis** [comment]
![untitled](https://user-images.githubusercontent.com/24310997/53837888-590a5780-3f59-11e9-8bfd-9d5b7583c9bc.png)

**Comment by githubeing** [comment]
@ssborbis, emm... did you mean "display the last used search TERM"? (singular) if i understand it correctly, "terms" are several queries, "term" is a single last one?
