### ISSUE TITLE
toolbar: button to clean the input

### ISSUE THREAD

**Issue by githubeing** [ssborbis/ContextSearch-web-ext#162]
usually, in query inputs (especially if the input is populated with some text automatically) there's a button to clean the input. (usually it's displayed as `×`)
![screenshot from 2019-03-05 10-02-41](https://user-images.githubusercontent.com/29702626/53786831-f2237900-3f2d-11e9-9c6c-2e3d2455fc6e.png)

could you please add such?

**Comment by ssborbis** [comment]
That's doable now that I've moved some icons around. The close button for the sidebar is currently in the search box in the last release but it's in a menu bar on the latest push. I'll have something ready for the next release.

**Comment by ssborbis** [comment]
Looked weird with two X's stacked so I'm using the delete icon

![untitled](https://user-images.githubusercontent.com/24310997/53791928-2aa46200-3ef0-11e9-991a-8a869f70f904.png)

**Comment by githubeing** [comment]
fyi, currently a click on the delete button leads to that the input loses focus 🤷

**Comment by githubeing** [comment]
usually this button is used to type in something new, therefore if it makes input to lose focus, this means the user has to perform an extra unneeded click to put the focus to the input

**Comment by githubeing** [comment]
@ssborbis , as i understand, you aren't going to fix this (make it so that the input will auto focus when the delete button is pressed). did i get it right? (or maybe you just didn't notice my previous post... - idk, therefore i mention you this time)

**Comment by ssborbis** [comment]
I just forgot to do it. It'll be there in the next release

**Comment by githubeing** [comment]
maybe the cause why you forgot this is that you've already closed this issue? imo, if the issue isn't complete by 100%, it should be remain open until it'll be completely done, agree?
