### ISSUE TITLE
toggle bars on/off, propagation of hotkey events

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#163]
if I press the configured hotkey (currently with Ctrl-Alt-Y), the sidebar opens but pressing the key again doesn't close it.

After I click
* on the page
* on the empty space below the search engines

I can close it with the hotkey.

Other places don't work, like
* search box
* suggestions
* button bar
* search engine (selected by tab)
* empty search engine
* if findbar is active
* if toolbar menu is active

I would at least expect it to work on the parts of the sidebar.
Would also be nice if it would work from any other parts of CS.

**Comment by ssborbis** [comment]
Yep, I didn't add the handler to the sidebar iframe. It'll be there on the next push.

I really need to write a common handler for all the iframe menus but I'm preoccupied getting the sidebar working with the docking code. There are a few bugs left and I haven't figured out how to handle resizing the undocked window yet.

**Comment by hg42** [comment]
the docking sidebar is awesome, I am already using it

**Comment by ssborbis** [comment]
Findbar / Sidebar hotkeys should work from any iframe except the Toolbar. Not sure why yet, but the toolbar menu handles things differently. It may be because it's not a true "tab" and my bg messaging is failing. 

Sidebar docking looks pretty solid now. I'll release 1.9.7 soon.

**Comment by hg42** [comment]
nice...

it does not work in the firefox url bar and other global places. Is this impossible (I guess again for security reasons)?

**Comment by ssborbis** [comment]
> it does not work in the firefox url bar and other global places. Is this impossible (I guess again for security reasons)?

I think if the hotkey values were hardcoded into the manifest ( https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands ), it could work globally. But to keep them user-configurable, they can only work in content windows. :(

**Comment by hg42** [comment]
I explicitly tried several situations for a test.

It also seems to work well in daily usage scenarios.
I think, I was mainly confused by a combination of opening and closing both, sidebar and findbar. They blocked each others keys or something like that.
Since updating I wasn't confused any more.

**Comment by ssborbis** [comment]
Good deal. I'll close this issue then.
