### ISSUE TITLE
quick menu: middle click on folder (when set up to open background tabs) opens all search engines but last

### ISSUE THREAD

**Issue by githubeing** [ssborbis/ContextSearch-web-ext#165]
steps to reproduce:

1. set up quick menu to open in background tab on middle click on folder
2. create a folder with n search engines
3. select some text to open quick menu
4. middle click folder

expected result: 

1. quick menu stays open
2. all n search engines are opened in new background tabs

actual result:

1. quick menu stays open
2. n−1 (all but last) search engines are opened in new background tabs

version 1.9.7

**Comment by ssborbis** [comment]
Got it fixed. I'll release a hotfix after I collect a few bug reports
