### ISSUE TITLE
context menu: wrong text for search

### ISSUE THREAD

**Issue by githubeing** [ssborbis/ContextSearch-web-ext#166]
sometimes (quite rarely) in context menus, the following bug occurs: the menu item `search for "text_placeholder"` displays very strange text (i don't remember, maybe sometimes it's from clipboard, but more often it's simply 'false' or 'undefined')

i attach two screenshots made at the same time (one - some seconds after the other). i right-clicked the same image on the page. but the menu differs:
![Screenshot from 2019-03-21 20-54-50](https://user-images.githubusercontent.com/29702626/54773934-ad7d2a80-4c1b-11e9-91b7-4b1e7cceddd7.png)
![Screenshot from 2019-03-21 20-54-32](https://user-images.githubusercontent.com/29702626/54773935-ae15c100-4c1b-11e9-8a25-e675e1b844bd.png)

**Comment by ssborbis** [comment]
Does it only happen on images / links or also when you highlight text?

**Comment by githubeing** [comment]
no, i was mistaken, for some reason right now it occurs often. here's another example
![Screenshot from 2019-03-21 20-59-44](https://user-images.githubusercontent.com/29702626/54774308-76f3df80-4c1c-11e9-8bea-30ecd492ec41.png)
you may see that the embedded search item (which uses duckduckgo in my case) detects the selected text correctly. i also notice that contextsearch puts there the previously selected object (a uri in this case)

**Comment by githubeing** [comment]
[screencast-2019-03-21_21.04.22.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/2993396/screencast-2019-03-21_21.04.22.zip)
i succeeded to make a screencast, take a look, sure you'll understand it better than me

**Comment by ssborbis** [comment]
I'm doing the same things, but not seeing that behavior. I'm looking into the timing for setting the menu text. It's probably a difference in hardware.

**Comment by githubeing** [comment]
my computer isn't very slow. cpu load % is low. when you say about timings do you expect that the problem won't reproduce on my side if i will behave very slowly myself? if you want, i may repeat the experiment, doing everything slowly

**Comment by ssborbis** [comment]
Nah, I mean there are some asynchronous functions going on that may be out of order depending on processor speed. Just a possibility I'm considering.

I noticed in your screencast, you opened the quick menu and the context menu on the word `highlight`. Does that always happen or did you mean to only open the context and opened the quick by accident? What settings are you using to open the quick menu? I just want to test with similar settings.

**Comment by githubeing** [comment]
i use auto opening of qm
i attach my settings so that you can test
[ContextSearch.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/2993920/ContextSearch.zip)

**Comment by ssborbis** [comment]
Next time it happens, try completing a search and see if it's just the menu displaying the wrong term or if the wrong term is also being used in the search. I'm guessing it's just the menu, but worth testing. 

I'm leaning towards this being a timing issue on slower machines or some event order problem. To display the 'Search for ...' menu with the current search terms in the context menu, the extension has to figure out the current search terms ( highlighted text / image url / link text / etc ) and build the menu item between the user pressing the mouse button down and releasing. A quick click or a slow PC can cause the menu to not update in time, leaving the previous search terms displayed.

Another issue I've seen before is linux defaulting to display the context menu on mousedown vs mouseup. This will cause havoc with the menus for this extension. What's your behavior? Do you get a right-click menu on mousedown or when you release the button?

**Comment by githubeing** [comment]
1. it's just a menu, the search itself opens with correct term
2. even when repeating the steps slowly, the result is the same
3. the context menu opens on right mouse button down, not up

**Comment by ssborbis** [comment]
> the context menu opens on right mouse button down, not up

Yep, there's the problem. It's an ubuntu thing. 

Firefox added a user preferences to change the default behavior to contextmenu on mouseup ( windows style ) but I dunno about chrome. In the FF version of this addon, I put a notice regarding this issue at the top of the quick menu options page. There's probably a fix for chrome out there somewhere to get the proper behavior but I haven't tried to. I don't think I've installed chrome on my ubuntu vbox yet, but I'll have a look sometime.

**Comment by githubeing** [comment]
and what about invoking context menu from keyboard? does contextsearch consider this? i.e. via `context menu` key on keyboard or via `shitf+f10` shortcut? as i can see, such invokation event doesn't update the search term in the menu item at all, right?

**Comment by ssborbis** [comment]
Yep, the handler is only attached to the mousedown event. Using the keyboard should have no effect.

**Comment by qdinar** [comment]
as i remember, this consistently, as for what i have seen, happened in pdfs and in reader view in firefox. now, i have tried it, but the addon's menu item in the context menu diappeared at all in these cases.

**Comment by ssborbis** [comment]
@qdinar 
I opened a random pdf in reader mode for testing. The context menu search seems to work but it doesn't display the search terms in the menu. Is the menu item "Search with" not displaying at all?

Using http://gdlp01.c-wss.com/gds/6/0300002536/03/PSG11_CUG_EN_03.pdf

![Untitled](https://user-images.githubusercontent.com/24310997/58319663-af13cc00-7ddf-11e9-9ca2-8eba50543c6f.png)

**Comment by qdinar** [comment]
yes, it is not here at all, firefox 67.0 64 bit, context search 1.9.10

**Comment by qdinar** [comment]
i tried with local file. now, i tried with the link, and i see it is shown, but the above mentioned bug, 
![context search](https://user-images.githubusercontent.com/831259/58335433-4281e700-7e4a-11e9-861b-6c4a0e6e9327.png)

**Comment by ssborbis** [comment]
Ok, I see what is happening and I have a fix. I'm updating the repo now.

**Comment by ssborbis** [comment]
@qdinar 

I noticed after I released 1.10 that the new menu string doesn't work properly for image-only pages so I think I'm going to revert non-DOM pages back to displaying `Search With` instead of trying to display the highlighted string. The fix for displaying the wrong highlighted string will still work though.
