### ISSUE TITLE
bidvoy.net search doesn't work

### ISSUE THREAD

**Issue by Speciesx** [ssborbis/ContextSearch-web-ext#168]
I can add https://bidvoy.net to the contex search, but this is the search result.
![11](https://user-images.githubusercontent.com/1196375/55111095-de58d600-50d9-11e9-885a-49794202b1ac.PNG)

**Comment by ssborbis** [comment]
They're using some javascript processing, but it appears you can use a simple GET url with some modifications. This is working for me

![Untitled](https://user-images.githubusercontent.com/24310997/55114122-20b8ed80-50af-11e9-8df5-ef7647f45e98.png)

The regex line replaces spaces with underlines to match the results url formatting.

**Comment by Speciesx** [comment]
thx.
