### ISSUE TITLE
`add custom search` doesn't work after recent update

### ISSUE THREAD

**Issue by githubeing** [ssborbis/ContextSearch-web-ext#169]
after recent update (1.9.7 or 1.9.7.1, not sure which exactly), on any site, i get one of the two following scenarios:
1. either the `add custom search` item is absent in the context menu of any input at all (no matter is it open via right-click or via `context menu` key on keyboard, or via `shift+f10`)
2. or even if it is present there, clicking on it has no effect: the menu just closes and on the next opening the item is already missing there.

similar to what i described in https://github.com/ssborbis/ContextSearch-web-ext/issues/67#issuecomment-475335437, but much worse - the only way to add a new search engine is to add it manually on the `settings` page

to be sure, i've checked this on a new empty chromium profile (off topic: btw i love so much this feature in chromium on ubuntu! ❤️ `open in a new window with a temporary profile` - it's like incognito, but doesn't remember anything from your previous life)

the environment is the same as always: latest chromium on latest ubuntu

**Comment by ssborbis** [comment]
I just published a hotfix. Chrome was having issues with the new Add Custom Search code. The fix also contains the focus fix for the searchbar.

I have not tested on Ubuntu with Chrome so there may be issues still with Ubuntu's contextmenu on mousedown

**Comment by githubeing** [comment]
I'm not sure I've understood you correctly. Do you ask me to test the hotfix, or you just keep me updated?

**Comment by ssborbis** [comment]
I put a new version in the Chrome store... just waiting for the publishing to complete. I may have to republish if it hangs, but the notice says it could take up to an hour to updated.

You can always sideload to test though.

**Comment by ssborbis** [comment]
Looks like it just went through 1.9.7.2

**Comment by githubeing** [comment]
yes, looks like this helped.

- now the problem #2 has gone (now clicking on menu item does what it has to)
- but the problem #1 still remains (often the menu item is absent)

**Comment by ssborbis** [comment]
> but the problem # 1 still remains (often the menu item is absent)

That's the context menu on mousedown issue. There just isn't enough time to generate the menu before it's displayed. I'll have to add an override option for some users. It will cause a tiered menu in text boxes though. I'll reply here when I have something worth testing.

**Comment by ssborbis** [comment]
Let me know if problem #1 is fixed / reduced in release 1.9.8. I've tested on ubuntu with chromium and I'm getting good results.

**Comment by githubeing** [comment]
yes, now it works fine! 🎉
