### ISSUE TITLE
Opening search tabs at the end?

### ISSUE THREAD

**Issue by go2tom42** [ssborbis/ContextSearch-web-ext#17]
Search tabs are opened next to current tab even with 

about:config -> browser.tabs.insertRelatedAfterCurrent -> false

Would it be possible to have an option to open search tabs after last tab instead of next to current tab?

**Comment by ssborbis** [comment]
For the latest betas, I've removed code handling tab placement, leaving it to FF prefs. Looks like I've been duplicating default behavior so the code might be unnecessary anyway. Let me know how it works out. 

https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext-lite/versions/beta
