### ISSUE TITLE
Request a change to the Quick Menu toolbar

### ISSUE THREAD

**Issue by streetwolf** [ssborbis/ContextSearch-web-ext#171]
I would like the capability to put the tool icons somewhere that is not in the same rows as the search engine icons.  I think it would look nicer and be more usable to have them separate from the search icons.

**Comment by ssborbis** [comment]
Like this?

![Untitled](https://user-images.githubusercontent.com/24310997/55593257-c5b37600-5700-11e9-9080-7ad73bb6dba8.png)

**Comment by streetwolf** [comment]
Exactly!  Might even give the option to put them below the search icons.

_____
Gary


________________________________

**Comment by ssborbis** [comment]
Voila!

![Untitled](https://user-images.githubusercontent.com/24310997/55594354-e382da00-5704-11e9-9c93-0eff69b90b90.png)

![Untitled2](https://user-images.githubusercontent.com/24310997/55594355-e41b7080-5704-11e9-945c-7ea38a31c6c5.png)

**Comment by streetwolf** [comment]
Just when I thought CS couldn’t get any better.  Don’t forget to allow for folks who have less columns than the number of tool icons.

_____
Gary


________________________________

**Comment by ssborbis** [comment]
Currently, the div hides overflow when columns is less than tools count but you can scroll horizontally using the mousewheel. I need to add some arrow buttons or scroll-on-hover divs for other users

**Comment by streetwolf** [comment]
If you need me to test send me a copy.

_____
Gary


________________________________

**Comment by ssborbis** [comment]
I'll block out some other code I'm testing and make a push in a sec

**Comment by ssborbis** [comment]
Changes are in the repo

**Comment by streetwolf** [comment]
Any idea when this will make it to AMO?

**Comment by ssborbis** [comment]
I need to vet some other changes before pushing a new release. I had a nasty bug that I need to be sure is gone. Day or 2 maybe?

**Comment by ssborbis** [comment]
@streetwolf just updated the release at AMO
