### ISSUE TITLE
Search entries from a list

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#172]
I'm wondering if this add-on allows to search for entries from a normal list, one after the other, separated by paragraphs, like this:

bananas
apples
peaches
melons

The use case behind this would be that I have quite a lot of movies and books listed in a text file. Instead of copy-pasting each into the URL bar and searching each entry one by one, I would prefer to copy them into a certain field and search for each word or phrase consecutively.

**Comment by ssborbis** [comment]
Not natively, but a relatively simple bookmarklet should get you there. Bookmarklets added and used through CS have access to content script functions. 

If you're using the quickmenu, something like:

```
javascript:
window.getSelection().toString().split(/\r|\n/).forEach( line => {
     line = line.trim();
     if (!line) return;
     browser.runtime.sendMessage({
		action: "quickMenuSearch", 
		info: {
			menuItemId: "JNWIM4OVG7CBT",
			selectionText: line,
			openMethod: "openBackgroundTab"
		}
     });
});
```
the `menuItemId` needs to be the ID of the search engine you're trying to use the script with. Easiest way to get it is it open CS options, open the dev console and type `userOptions.nodeTree` and browse the object for the right `id` key.

To make a bookmarklet, add a new bookmark with the code above as the Location / URL and give it a unique name. Then open CS options -> Search Engines, right-click in the manager and choose "Add Bookmarlet". This should generate a new submenu containing any bookmarks that are seen as scripts ( starting with javascript: ) and choose the new bookmarlet you created. You should have a new tile in your menu with a `<\>` icon ( you can change the icon in the manager ).

**Comment by ssborbis** [comment]
If you're trying to use that script out of a textarea, it's not going to work. I'm checking for a workaround, but it might not be doable until I modify some code.

**Comment by sojusnik** [comment]
Wow, that was fast! Works great, thank you!

Regarding the text area: the way it's working now is completely sufficient.

The only question I have is how to add a second search engine? I've tried to add an `id` after the first one (f.i. `menuItemId: "JNYJ5SX8MJWGR", "JTPWI3QAZHJAR"`), but the bookmarklet refuses to work.

**Comment by ssborbis** [comment]
Nah, you'd have to add a separate browser.sendMessage section like this:

```
javascript:
window.getSelection().toString().split(/\r|\n/).forEach( line => {
     line = line.trim();
     if (!line) return;
     browser.runtime.sendMessage({
		action: "quickMenuSearch", 
		info: {
			menuItemId: "JNWIM4OVG7CBT",
			selectionText: line,
			openMethod: "openBackgroundTab"
		}
     });

      browser.runtime.sendMessage({
		action: "quickMenuSearch", 
		info: {
			menuItemId: "SEARCH_ENGINE_ID_2",
			selectionText: line,
			openMethod: "openBackgroundTab"
		}
     });
});

**Comment by sojusnik** [comment]
Works flawlessly! Thank you again!
