### ISSUE TITLE
import deletes all search engines!

### ISSUE THREAD

**Issue by githubeing** [ssborbis/ContextSearch-web-ext#175]
i've just nearly lost all my saved search engines!

steps to reproduce:
- install some of previous versions
- export your SEs (i've done this step many days/weeks ago)
- update to current version
- import you SEs (i've done this step today)

expected result:
- either they're imported successfully
- or the error is thrown but old SEs are kept!

actual result:
- neither they're imported
- nor the error is thrown
- and all SEs are GONE!

how to restore:
- if you're so lucky as i am and you have another copy of extension on another machine, proceed. otherwise, sorry, look for other ways. at least you have your old settings exported in file, maybe you'll somehow succeed in parsing json... good luck
- go to other machine. there should be new version installed already.
- export settings from there
- return to problem machine, import new version of settings
- your old SEs come back!
- don't forget to export your settings in new format so that you won't screw it up again the same way!

**Comment by ssborbis** [comment]
Can you post/email me a copy of the config that wont import? I just tried with an old config and it worked.

ssborbis@gmail.com

**Comment by githubeing** [comment]
did you know that github allows me to reply to you by sending a reply to the post notification it sends me? let's check this feature out! (i haven't tried it yet, it's interesting to test it) not sure if it can forward an attachment though! tell me if you received it or not  16.04.2019, 00:45, "ssborbis" <notifications@github.com>:Can you post/email me a copy of the config that wont import? I just tried with an old config and it worked.ssborbis@gmail.com—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ssborbis** [comment]
I don't see any attachment in email. Want to post and delete after I've got it?

**Comment by githubeing** [comment]
oh, i see now. it's posting it to the thread. ok, i've added your email to recipients list, now you should receive it 16.04.2019, 00:57, "gituser@yandex.com" <gituser@yandex.com>:did you know that github allows me to reply to you by sending a reply to the post notification it sends me? let's check this feature out! (i haven't tried it yet, it's interesting to test it) not sure if it can forward an attachment though! tell me if you received it or not  16.04.2019, 00:45, "ssborbis" <notifications@github.com>:Can you post/email me a copy of the config that wont import? I just tried with an old config and it worked.ssborbis@gmail.com—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ssborbis** [comment]
nvm, I see the attachment now

**Comment by githubeing** [comment]
it was an interesting experience for me ^_^

**Comment by ssborbis** [comment]
Ok, the good news is they do import. You just have to restart FF / addon to get the node tree back. I'll look into why.

**Comment by ssborbis** [comment]
Ok, import was using an older version of a function to update config objects. It wasn't seeing some nested objects and the options page got hung up because some config variables were missing. Reloading the browser / addon runs the config through the proper update function and restores the missing variables. I'll see about issuing a hotfix, but until then just restart the browser.

**Comment by ssborbis** [comment]
Fix released with v1.9.9
