### ISSUE TITLE
Simple Click to get the searched-for terms

### ISSUE THREAD

**Issue by Sagitee** [ssborbis/ContextSearch-web-ext#178]
What about an additional CS option to get the searched-for terms by just Clicking on them (without having to make a text selection previously)?
In this way, the search enhancing effectiveness of CS could be utilised to make the look-up of single words (which is probably the commonest case) and may be whole paragraphs or sentences not only quicker and easier, but above all POSSIBLE in those certain cases/sites where text selection is not allowed or is not in any way achievable.
A very common example of such a case is Youtube with its embedded (in the video area) subtitles/captions, which are not in any way selectable.

**Comment by ssborbis** [comment]
It might be doable. It would have to be disabled on any text that links, obviously. I'll try a few things.

The closest you could get now is to install an addon that enables text selection everywhere and use the auto opening method for the quick menu. Double-clicking a word selects it and would open the menu.

**Comment by Sagitee** [comment]
I assume the “links” issue might be bypassed by the users by selecting a proper Search Action in the CS Options.

The “enable selection” addons is a solution in some cases but unfortunately they usally don’t work and if they do they may break other major functions of the sites. This is the case of “Absolute Enable Right Click & Copy” addon on the pre-mentioned Youtube subtitles example.

If it helps, I have seen the proposed option to work fine (in the Youtube subtitles case too) in some FF addons (of a different field) like “Dict.cc” or “Wictionary & Google Translate” (they translate the clicked word) and “Copy Text with Alt-Click” (it copies the clicked paragraph).

*PS: I am the FF user that had proposed the recently added “open in sidebar option”. Excellent work. Thank you!

**Comment by ssborbis** [comment]
I've got a script working. but it feels a bit intrusive to have it work on any click, even optionally. Do those other addons require holding down a key, say CTRL and then click? Do they use left-click?

**Comment by Sagitee** [comment]
Such options are available:

![Quick_click_options](https://user-images.githubusercontent.com/50146787/57042563-b2e38100-6c6d-11e9-99a4-66f323de6b0f.jpg)

But, if the Simple-Click (or No-Selection or Any-Name) method was added as a forth Opening Option (alongside Auto, Keyboard and Mouse options) in the CS Settings

![OpeningOptions](https://user-images.githubusercontent.com/50146787/57042576-c1ca3380-6c6d-11e9-9636-e7be92be7b77.jpg)

then, wouldn’t be utilisable the CS Search Actions

![SearchActions](https://user-images.githubusercontent.com/50146787/57042603-d0b0e600-6c6d-11e9-94ac-c53cd9c31be7.jpg)

which make a much more advanced application of the same scope?

**Comment by Sagitee** [comment]
About the possible intrusiveness in the case of a simple (left) click (without additional keys) option selection, a well visible warning or/and a possible confirmation might be added too.

**Comment by ssborbis** [comment]
I've been testing with holding CTRL and it works nicely. It shouldn't interfere with other methods of opening the quick menu if I check for selected text. And the search actions are only for clicking search engine tiles. None of those options should have a conflict. If you're sideloading I can updated the repo for testing.

**Comment by Sagitee** [comment]
I suppose sideloading is something a non developer could do. Is there a help link that describes it?

**Comment by ssborbis** [comment]
No need to uninstall, and I haven't made a push to updated the repo so don't worry about testing just yet. I'll tweak a few things tomorrow and post the process to load a temporary addon.

**Comment by ssborbis** [comment]
Ok, I just made a push with the new code. You can sideload the temporary addon by:

0. First, it's a good idea to backup your ContextSearch settings using the Export button.
1. Downloaded the latest source code https://github.com/ssborbis/ContextSearch-web-ext/archive/native-app-support.zip
2. Extract the folder
3. Open `about:debugging` using the url bar,  click Load Temporary Add-on, and browse to the extracted source folder -> src / manifest.json and click Open

Now the temporary addon will replace your installed version of contextsearch until you close the browser. Do NOT click the button in about:debugging under the new temporary ContextSearch entry that says Remove! This has a habit of removing your original ContextSearch settings. Just restart the browser when you want to remove the temporary addon.

![Untitled](https://user-images.githubusercontent.com/24310997/57095149-c3304600-6cd7-11e9-87d4-154fa94790a6.png)

**Comment by Sagitee** [comment]
a) It works fine on English words consisted of Latin characters without accent marks, which are recognised properly.
But, Latin letters (eg. of English “borrowed”, French, Spanish or Italian words) with accent marks (eg. á, à, é, è, í, ó, ú, ü, ñ etc.) and especially non Latin alphabet (like Greek or Cyrillic which I tested on) letters are regarded by Simple Click as separate words. Eg. French “améliorer” is taken as 3 separate words: am, é, liorer and Greek “είμαι” is taken as 5 separate words: ε, ί, μ, α, ι.
b) Now Simple Click is activated after any kind of Click on words.
I would suggest for practical and non intrusiveness reasons, some selectable Click choices (Left, Right, Middle, Double) to be added too.

**Comment by Sagitee** [comment]
a) It works fine on English words consisted of Latin characters without accent marks, which are recognised properly.
But, Latin letters (eg. of English “borrowed”, French, Spanish or Italian etc. words) with accent marks (eg. á, à, é, è, í, ó, ú, ü, ñ etc.) and especially non Latin alphabet (like Greek or Cyrillic which I tested on) letters are regarded by Simple Click as separate words. Eg. French “améliorer” is taken as 3 separate words: am, é, liorer and Greek “είμαι” is taken as 5 separate words: ε, ί, μ, α, ι.

b) Now Simple Click is activated after any kind of Click on words.
I would suggest for practical and non intrusiveness reasons, some selectable Click choices (Left, Right, Middle, Double) to be added too.

c) When I tried to add this comment by left-clicking the “Comment” github button (on the word/letters part of it), the Quick Menu of CS opened as expected (as I had Simple Click activated without any of the Alt, Ctrl, Shift choices checked), but the comment was not sent (eg. the typical functioning of the button was canceled). Shouldn’t the two tasks/functions work parallelly both properly?

**Comment by ssborbis** [comment]
a) I'm looking into some robust regex matching for international characters. I knew it would be an issue, but I wanted to get something up for testing

b) I think alternate buttons should be doable without conflicts within this add-on.  I'll need to do some testing.

c) It should be one or the other, not both IMO. If a user is wanting to get a popup for a word, they probably don't want to execute the function of the link/button they're clicking, potentially changing the page and closing the popup. I would guess using a modifier key is going to be preferable for most users for that reason. I'll try to include enough options for everyone.

**Comment by ssborbis** [comment]
I updated the regex. Seems to work better.

**Comment by Sagitee** [comment]
Perfect!

**Comment by Sagitee** [comment]
A smart and usefull attitude that I notice Simple Click has (and which the prementioned addons lacked) is that by clicking on the single space or the dash between two words both are grabbed (eg. by clicking on “-” between “e” and “mail”, “e-mail” is looked-up word).

**Comment by ssborbis** [comment]
Total accident. I didn't check for the clicked character being one of the delimiting tokens I'm using `!\"#$%&\\\'()\*+,-./:;<=>?@[]^_`{|}~ `. If it is, the code keeps looking to the left and right for another token to stop, effectively grabbing the words to the left and right.

**Comment by Sagitee** [comment]
Very usefull though. I guess that the case of two words in sequence should be the second commonest case after that of a single word lookup.

**Comment by ssborbis** [comment]
Latest push has button options

**Comment by Sagitee** [comment]
Right and Middle Click (with or without Ctrl-Alt-Shift option) work fine. I could find just these two exceptions (the normal click attitude occurs concurrently with that of the Simple Click):
- Middle click on links still opens them
- Right click on youtube subtitiles still opens the youtube context menu.

Left Click with the Ctrl-Alt-Shift option works fine too.
When using the Left Click (with or without Ctrl-Alt-Shift option) one can circumvent the concurrent links opening by down-clicking on the link and up-clicking after moving the pointer away from it.
Left Click without Ctrl-Alt-Shift option of course suspends some major click functions like text selection and the relevant actions (context menu actions, drug & drop etc.) one can do with a selected text like.

**Comment by Sagitee** [comment]
I think that you have overcome the issue of two concurrent click actions, in the case of Selected text Mouse Opening method, where the Click breaks in two types, Click and Hold. Is that case similar and should the same be implemented here too?

**Comment by ssborbis** [comment]
> Middle click on links still opens them

I have this solved locally

> Right click on youtube subtitiles still opens the youtube context menu.

The youtube event has priority and I might not be able to cancel it.

**Comment by ssborbis** [comment]
> I think that you have overcome the issue of two concurrent click actions, in the case of Selected text Mouse Opening method, where the Click breaks in two types, Click and Hold. Is that case similar and should the same be implemented here too?

It complicates things but I could implement it. Initially, I probably won't even bother checking for conflicts between the Opening methods and simply leave it to the user to set their options to something that works.

**Comment by Sagitee** [comment]
Ok, thanks for the nice work.
I stand by if a newer push test is needed.

**Comment by ssborbis** [comment]
I've got a release in the queue for FF but they're having all kinds of issues right now at AMO. It might be a while before it goes through.

**Comment by Sagitee** [comment]
Unified/common Mouse and Simple Click options

Hi, I have used the previous days CS with the Simple Click option as it was recently implemented.
Mouse and Simple Click are in fact both methods of the same kind (mouse-click) and their implementation is well distinguished, by the existence or not of a text pre-selection. This means that in case where both options are activated, if a text selection has been made only the Mouse option is permitted and if not only the Simple Click is permitted.
So, the option to select separately different Click options (Left, Right, Middle) for each of them, practically seems (of course, from the user’s point of view, who can’t see any possible technical limitations) to unnecessarily complicate things a lot.
I would suggest unified/common options for Mouse and Simple Click, something like what is shown in the following pictures:

![Mousclick1](https://user-images.githubusercontent.com/50146787/57576110-66642680-7461-11e9-8d80-c9fc75c3ec37.jpg)

![Mousclick2](https://user-images.githubusercontent.com/50146787/57576114-7845c980-7461-11e9-812c-2b4ec04168fa.jpg)

**Comment by ssborbis** [comment]
I'll think on it. If I merge the settings, all I'd need for simple-click function is an option to require text selection or not.

**Comment by ssborbis** [comment]
After some testing, i think it's best to leave the settings separate to allow for more opening methods. If the settings were merged, I couldn't do what I do now; have both select + right-click and simple ctrl-left click options for opening the QM.

**Comment by Sagitee** [comment]
I see. It’s an additional option for the user.

The more important reason for which I proposed the unification was that that would also add some additional options for the user, like:

- Mouse with Middle Button
- Simple Click with Hold
- Mouse + Alt/Ctrl/Shft

Of course, those additional options might be feasible even without the merging in which case I would still suggest them.

A little, subjective and of secondary importance objection of me to an option like “select + right-click & simple ctrl-left click” is kept about its practical usefulness i.e. If one is able to use both Mouse select and One Click methods with one of the above choices (right-click or ctrl-left click) why would he/she wanted to use a separate choice for each one of the two methods, making things more complicated, difficult to remember and get used-accustomed to?

**Comment by ssborbis** [comment]
> why would he/she wanted to use a separate choice for each one of the two methods, making things more complicated, difficult to remember and get used-accustomed to?

Dunno, but in my experience, it's best to leave the option available. Someone will request it eventually.

**Comment by Sagitee** [comment]
I think you are right. It's more democratic all the chices to exist.
