### ISSUE TITLE
inject.css cause a failure rendering page.

### ISSUE THREAD

**Issue by chengtian5huang** [ssborbis/ContextSearch-web-ext#18]
# how to reproduce
visit _https://www.bilibili.com_ open a video.
go to  the comments section:
these grey bars is a failure casued by inject.css!

**here is what grey bars look like:**
screenshots from _https://www.bilibili.com/video/av19447709/_
![default](https://user-images.githubusercontent.com/34744187/37249738-fa2593d4-2527-11e8-8ea9-51c7db2eeaf9.PNG)

# check this page with F12:

**with ContextSearch-web-ext disabled:**
![default](https://user-images.githubusercontent.com/34744187/37249749-45b79266-2528-11e8-8a10-551d106e9589.PNG)

**when it enabled:**
![default](https://user-images.githubusercontent.com/34744187/37249785-06a3551e-2529-11e8-85ff-2bf656d08f1f.PNG)

# additional info:
i am using firfox 58.0.2 in win10.
addon version is 1.2.8.2 which is latest.
i have not found another website with this issue so far.

**Comment by ssborbis** [comment]
Ah, I pulled some style and code from the options page. The ids and class names were pretty generic. I'll rename them to something unique for the content scripts.

**Comment by ssborbis** [comment]
Nice detailed feedback. Much appreciated.

Betas going up. 

https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta?page=1#version-1.2.8.3b
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext-lite/versions/beta?page=1#version-1.2.8.3b
