### ISSUE TITLE
Feature request: always open mini-search bar results in new tab

### ISSUE THREAD

**Issue by arelkin** [ssborbis/ContextSearch-web-ext#180]
Maybe this feature already exists, but I could not seem to locate it in the preferences.
Having a checkbox in the preferences: "Always open mini-search-bar results in new tab"

![mini-search-bar](https://user-images.githubusercontent.com/213207/57347729-52e35380-7121-11e9-8254-86fa826b39d2.jpg)

**Comment by ssborbis** [comment]
That's the Firefox built-in search bar, not mine. Looks like you can set to open in new tab by changing a setting in the FF config.


>... type about:config in the address bar and hit Enter. You may be prompted to okay that you understand the "dangers" of using about:config. Once in the tool, type `browser.search.openintab` in the about:config search bar. The entry for `openintab` should appear and be set to false. To change that, double-click the entry, and it should shift to true. That's it. You can close about:config, and the next time you use the search bar, the results will open in a new tab, instead of your current working tab. 

https://www.techrepublic.com/article/how-to-configure-firefox-to-open-a-new-tab-for-search-results/

**Comment by arelkin** [comment]
Thanks. My bad for not thinking to look for that on my own. In my (much) older version of FF, either I forgot about this, or one of my older plugins did it for me.

Thanks again.

**Comment by ssborbis** [comment]
No prob
