### ISSUE TITLE
why when I add a new search engine, it doesnt add to one click search engines?

### ISSUE THREAD

**Issue by riza4** [ssborbis/ContextSearch-web-ext#182]
it gives this error:
Firefox could not download the search plugin from:
https://opensearch-api.appspot.com/?SHORTNAME=%20%20%D8%AC%D8%B3%D8%AA%D8%AC%D9%88%DB%8C%20Google%20%D9%87%D9%85%D9%87%20%D8%B2%D8%A8%D8%A7%D9%86%D9%87%D8%A7%20&DESCRIPTION=%20%D8%AC%D8%B3%D8%AA%D8%AC%D9%88%DB%8C%20Google%20%D9%87%D9%85%D9%87%20%D8%B2%D8%A8%D8%A7%D9%86%D9%87%D8%A7%20&TEMPLATE=https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3D%257BsearchTerms%257D%26hl%3Dfa%26as_qdr%3Dall%26biw%3D1366%26bih%3D632%26ei%3D7trYXPH3AYTSsAfd8JK4Aw%26gs_l%3Dpsy-ab.3..35i39l6.23907.23907..24445...1.0..0.0.0.......0....1..gws-wiz.....6.Hp8oGMYeQ0g&POST_PARAMS=&METHOD=GET&ENCODING=UTF-8&ICON=https%3A%2F%2Fwww.google.com%2Ffavicon.ico&ICON_WIDTH=32&ICON_HEIGHT=32&SEARCHFORM=https%3A%2F%2Fwww.google.com&VERSION=1.9.10

**Comment by ssborbis** [comment]
Dunno. It works for me adding it manually. Do you have another engine of the same name in Firefox's One-Click Search Engines?

open the console (Ctrl+K usually) and enter this

```
window.external.AddSearchProvider("https://opensearch-api.appspot.com/?SHORTNAME=%20%20%D8%AC%D8%B3%D8%AA%D8%AC%D9%88%DB%8C%20Google%20%D9%87%D9%85%D9%87%20%D8%B2%D8%A8%D8%A7%D9%86%D9%87%D8%A7%20&DESCRIPTION=%20%D8%AC%D8%B3%D8%AA%D8%AC%D9%88%DB%8C%20Google%20%D9%87%D9%85%D9%87%20%D8%B2%D8%A8%D8%A7%D9%86%D9%87%D8%A7%20&TEMPLATE=https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3D%257BsearchTerms%257D%26hl%3Dfa%26as_qdr%3Dall%26biw%3D1366%26bih%3D632%26ei%3D7trYXPH3AYTSsAfd8JK4Aw%26gs_l%3Dpsy-ab.3..35i39l6.23907.23907..24445...1.0..0.0.0.......0....1..gws-wiz.....6.Hp8oGMYeQ0g&POST_PARAMS=&METHOD=GET&ENCODING=UTF-8&ICON=https%3A%2F%2Fwww.google.com%2Ffavicon.ico&ICON_WIDTH=32&ICON_HEIGHT=32&SEARCHFORM=https%3A%2F%2Fwww.google.com&VERSION=1.9.10");
```

**Comment by riza4** [comment]
Ok thanks. now i solved my problem with another add on. the next one i wanted to add an engine i try your answer. thanks a lot.
