### ISSUE TITLE
selectdomain tree in site search doesn't work

### ISSUE THREAD

**Issue by ryans233** [ssborbis/ContextSearch-web-ext#184]
Sometimes the selectdomain tree only shows a "blank" entry. Sadly I can't reproduct this issue consistantly, but I can show you a screenshot. [Imgur](https://i.imgur.com/F0HeM1I.png)

BTW Could you make a default action like "with hostname" when I left clicking SiteSearch entry directly? I think it would be more convenient.

**Comment by ssborbis** [comment]
> Sometimes the selectdomain tree only shows a "blank" entry. Sadly I can't reproduct this issue consistantly, but I can show you a screenshot.

I bet it has to do with tabs loading in about:blank before redirecting to the proper url and the listener only seeing the updated url on tab change. I'll do some testing.

> BTW Could you make a default action like "with hostname" when I left clicking SiteSearch entry directly? I think it would be more convenient.

Hmm... I don't think so. There isn't any event triggered when clicking a parent folder in the context menu to bind to. But you could edit or duplicate your search engine template string and replace {selectdomain} with {domain} or {subdomain}.

**Comment by ssborbis** [comment]
I just made a push with code to rebuild the context menu on url change. That might fix your "blank" bug. I wasn't able to produce the bug to confirm.

**Comment by ryans233** [comment]
Thanks. I will test it later.

ssborbis <notifications@github.com> 于2019年5月23日周四 上午3:49写道：

**Comment by ryans233** [comment]
It seems working properly now, although I still have a advice for it.
When you opening a url without any path such as "https://www.google.com/", the selectdomain tree will show two entries: "www.google.com" and "www.google.com/". Personally I think the last one is unnecessary. Any idea on it?

**Comment by ssborbis** [comment]
Yep, a known issue I've been slow to fix due to other concerns. Not much happening right now so I can take a look. 

I've updated the repo with a fix for the trailing slash duplicates and updated the context menu handler to add the domain as well. I've only lightly tested so keep an eye out for bugs if you're sideloading.

**Comment by ssborbis** [comment]
I just released v1.10 with the updates. I've had pretty good results so far. Keep this thread open for a bit to check for bugs. When you're satisfied with the fixes, go ahead and close it out.
