### ISSUE TITLE
Support for reverse image search?

### ISSUE THREAD

**Issue by robertheadley** [ssborbis/ContextSearch-web-ext#185]
First I want to say, you have a wonderful extenstion here. I was looking for something to replace Context Menu Search and Image Search options with a single extension.

Most reverse image searches will allow you to search by image url, so that functionality at least would be appreciated. I couldn't find anything saying that it was currently supported.

imgops.com would be nice in particular. Thanks.

**Comment by robertheadley** [comment]
Ok. I see that one of the default engines is Image Google search, and that seems to work, however imgops seems to be replacing the special characters in the URL which breaks it. It doesn't do that if you just enter the search on imgops.com. Is it because of the encoding?

**Comment by ssborbis** [comment]
I'm not familiar with that engine but I'll take a look. If it's a case where certain characters in the GET url are replaced by the search engine ( i.e. spaces to %20 or underscores or vice versa ) you can use the regex field in the edit form for the search engine to make corrections to the search terms, in this case the url of the image.

**Comment by ssborbis** [comment]
Do you have an url that fails? I just did a quick check with a basic imgur.com url and it seemed to work.

**Comment by robertheadley** [comment]
I tend to search images from Facebook frequently. I am also forcing https so I wonder if it is failing with https links.

**Comment by robertheadley** [comment]
Every URL fails for me, but every url is also Https.

**Comment by ssborbis** [comment]
I just checked a facebook image and it seemed to work ok. Did you add imgops.com using the Add Custom Search option? Default templates, etc?

**Comment by robertheadley** [comment]
I tried to add using the add option from the search form on the page and then I tried cloning the google image search and editing the info. It is specifically not wanting to work with https links.

**Comment by robertheadley** [comment]
Using https everywhere. Very common extenstion.

https://www.eff.org/https-everywhere

**Comment by ssborbis** [comment]
Odd. I'm getting good results with https images and by changing the template url to https. Maybe there is a conflict with https-everywhere.

![Untitled](https://user-images.githubusercontent.com/24310997/58230967-5ff46b00-7cfb-11e9-8837-60c6a073bafd.png)

**Comment by robertheadley** [comment]
Ok, I copied your template, https://imgops.com/start?url={searchTerms} and now it works fine. 
I wonder if https everywhere causes an issue with the way that your extension detects the template?

**Comment by ssborbis** [comment]
Hmm. That could be. I just installed it so I'll have a look

**Comment by ssborbis** [comment]
Thanks. No prob

**Comment by ssborbis** [comment]
Using default settings for https-everywhere, I get the same working template for imgops.com. I did notice the results page shows a different url format than the search bar template's GET url ( redirect of some sort ). Sometimes if you try to use the Add Custom Search option from a secondary page / results page, the addon will see the wrong template url. Dunno of that's what happened to you, but I have seen it happen on other engines. If something similar happens again, post the broken template url, etc and I'll try to figure out what went wrong.
