### ISSUE TITLE
bug: loosing search term edits when opening tab in background from quick menu

### ISSUE THREAD

**Issue by githubeing** [ssborbis/ContextSearch-web-ext#188]
steps to reproduce:
1. select text on page
2. open quick menu
3. the selected text will be auto-copied to search terms input
4. edit the search terms
5. open search window in background tab
6. the quick menu will remain open

expected result:
7. search terms remain same as after step # 4
8. you may open other tabs in background or foreground using same edited search terms again and again

actual result:
7. search terms are reset to initial value as they were after step # 3
8. to open the same search terms as at step # 4, you have to re-edit it again and again for each new background tab

**Comment by githubeing** [comment]
see screencast below
![screencast](https://user-images.githubusercontent.com/29702626/59611597-412f9b80-9124-11e9-9f16-593fc1069918.gif)

**Comment by ssborbis** [comment]
Yep, i'm seeing it too on FF. I'll take a look

**Comment by ssborbis** [comment]
Ok, looks like the searchbar onchange event wasn't firing before the click event, preventing the search terms from being updated properly. Should be fixed in the repo.
