### ISSUE TITLE
Do not show deactivated search engines

### ISSUE THREAD

**Issue by Speravir** [ssborbis/ContextSearch-web-ext#19]
In Firefox settings one can deactivate search engines, but nonetheless they are shown in context menu of this addon. I have some engines deactivated which come by default with Firefox, so deleting won't help. 

It already helps a lot that an individual order is respected, but the more own search engine entries the more the context menu gets bigger.

**Comment by ssborbis** [comment]
Something changed around FF58 and the information for which engines are hidden is no longer in the search.json.mozlz4 file. The add-on did hide them prior to the update. I haven't found where the new info is kept yet.

**Comment by ssborbis** [comment]
I've also been seeing some weird behavior with hiding engines. Sometimes the changes don't stick. I've got 2 engines I can't seem to hide at all. Maybe there's a bug in the FF code

**Comment by ssborbis** [comment]
Looks like the hidden engine list has been moved to prefs.js

`browser.search.hiddenOneOffs`

That's gonna be a pain

**Comment by ssborbis** [comment]
I've got a basic handler for getting the prefs.js file with the native app, but there's a bug in FF's code for parsing the var. They're using a csv string of search engine names to filter out hidden engines but some engine names have commas in them screwing up the parse. That's why I've got 2 engines that I cant seem to disable. I'll hold off on doing anything on my end until the Moz devs fix their formatting.

**Comment by Speravir** [comment]
OK for now. I also noticed your note on the latest addon update.

**Comment by ssborbis** [comment]
v1.3.1.2 should hide the search engines properly if used with the native app. It's working for me on Windows 10, FF 59.0.1

**Comment by Speravir** [comment]
JFYI: Thanks for your efforts. I cannot check, though, because I do not use the native app.

**Comment by Speravir** [comment]
Tested it and unfortunately it does not work fully:

* Reordering is fine, it is applied immediately.
* _Hiding/deactivating does not work here at all._ I checked and unchecked different engines several times, but did not observe any change.
* I did not test deleting and do not intend to do this.

**Comment by ssborbis** [comment]
Hmm it's working here. What version of FF / OS are you using?

**Comment by ssborbis** [comment]
Nvm, I've only tested the quickmenu. It's not applied to the contextmenu.

**Comment by ssborbis** [comment]
Should be fixed in 1.3.4. Lots of new code for editing the Manual Import list so there's gonna be a few bugs. 

https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext-lite/

**Comment by Speravir** [comment]
> I've only tested the quickmenu. It's not applied to the contextmenu.

And I forgot to mention hat I only use the contextmenu, sorry for that.

> Should be fixed in 1.3.4. Lots of new code for editing the Manual Import list

Yes, it works now! Thank you. I consider this issue as closed.
