### ISSUE TITLE
middle click and right click for tab options, not in chrome?

### ISSUE THREAD

**Issue by nobletype** [ssborbis/ContextSearch-web-ext#191]
I see this option for middle and right clicking into new tabs/background tabs being available for Firefox, however there is only left click in Chrome. Is it just not feasible for some behind the scenes reason?

**Comment by ssborbis** [comment]
If you're referring to the context menu, Chrome does not recognize middle and right clicks whereas Firefox does ( last I checked anyway ). I'll certainly open the options to Chrome if they add it to the API.
