### ISSUE TITLE
Need help for fr/style.css

### ISSUE THREAD

**Issue by DenB10** [ssborbis/ContextSearch-web-ext#193]
Hi ssborbis,
Style issues in the options page, quick menu tab, see the screen captures:
![Capture-1](https://user-images.githubusercontent.com/9309147/61993930-b1aad000-b073-11e9-9edd-d58379784dd8.jpg)
![Capture-2](https://user-images.githubusercontent.com/9309147/61993937-e6b72280-b073-11e9-8dc5-94da64aecc22.jpg)
 Can you help me?

**Comment by ssborbis** [comment]
Yep, lemme switch my language and see whats going on.

**Comment by ssborbis** [comment]
I made a few tweaks to the main options.html css that looks like it fixed the issues. Try the latest push and see if it works for you. If so, I'll drop a new version

**Comment by DenB10** [comment]
It's better but:

- Check-boxes are not aligned anymore:
![Capture-1](https://user-images.githubusercontent.com/9309147/61996496-27736380-b095-11e9-9ece-595719dba36a.jpg)

- "Moteurs de recherche" is truncated:
![Capture-2](https://user-images.githubusercontent.com/9309147/61996515-55f13e80-b095-11e9-98f7-2ceb4290431a.jpg)

**Comment by ssborbis** [comment]
Try the latest

**Comment by DenB10** [comment]
Works fine, thanks ;)

**Comment by ssborbis** [comment]
Cool. I'll tidy a few things up and get an update out tomorrow
