### ISSUE TITLE
Issue with the left-click

### ISSUE THREAD

**Issue by Kiks67** [ssborbis/ContextSearch-web-ext#195]
Hello,

Since the update of 09/08/2019, there is a issue with the left click.
Selecting text by double-clicking automatically opens a search window (without using the menu).

It seems to work the first time, but the issue happens at the next time.

Thank you

**Comment by ssborbis** [comment]
Thanks. New version going up. I had to rush a patch for mozilla and didn't fully test a new feature.

**Comment by Kiks67** [comment]
Seems to work in the version 1.15
Thank you !
