### ISSUE TITLE
Tool icons appear in the main menu (version 1.16)

### ISSUE THREAD

**Issue by DenB10** [ssborbis/ContextSearch-web-ext#198]
The tool icons appear in the quickmenu, that's OK.
But they appear in the main button menu and the sidebar menu too, I think this is not normal, is it?

**Comment by ssborbis** [comment]
Definitely not normal. What are your settings? I can't replicate.

**Comment by ssborbis** [comment]
Ok, I'm getting it with qm and toolbar columns the same. I'll check it out.

**Comment by ssborbis** [comment]
I forgot, I DO display tool icons when qm and toolbar have the same column settings to keep the layout the same. But they shouldn't be usable, and it looks like they kinda are. I'll drop the title and onclick functions.

**Comment by DenB10** [comment]
> Ok, I'm getting it with qm and toolbar columns the same. I'll check it out.

That's it. As soon as I change the columns setting for the quickmenu or the main button, the tool icons disappears from the main menu. This didn't occur with the previous versions ?

**Comment by ssborbis** [comment]
> This didn't occur with the previous versions ?

I'm assuming by "main menu" you're referring to the Toolbar button. 

Some users found it confusing for the quick menu to display the tool icons, offsetting the search engines, but using the same column configuration in the Toolbar menu were seeing a different layout. Because of this, users who set tools position = top and do not display as a separate toolbar will see the tool icons in the Toolbar button menu to maintain the layout.

As far as I know, that was the norm. I rarely set my QM and toolbar menus to the same column count so I forgot that was the behavior.

If you're talking about something else, let me know.

**Comment by ssborbis** [comment]
I just noticed the tool icons always show in the sidebar. This is wrong and I've corrected it. They should only show if sidebar columns = quick menu columns to keep the same layout. Old bug.

The Toolbar menu shouldn't have issues though.

**Comment by ssborbis** [comment]
Looks like there was also a problem when using `Display as toolbar`. I've set that as the default setting now, and the code to build the toolbar and sidebar wasn't accounting for that option. Another bug taken care of.

**Comment by DenB10** [comment]
I'm sorry about the problems I'm raising.
Solved now with the latest repo, as far as I check the `Display tools in a separate toolbar` setting. 
Thank you.

**Comment by ssborbis** [comment]
> I have spoken too quickly as the lock icon to keep quickmenu open doesn't work anymore!

K, I'll work on it. I've moved a lot of code for the tools around so there's bound to be some bugs.

**Comment by ssborbis** [comment]
> I'm sorry about the problems I'm raising.

Dude, I need all the beta testing and bug reporting I can get. If something's broken, it's usually because I don't know about it.

The lock tool seems to work ok with my local code. If you're still getting it with the latest repos, post your method to reproduce.

**Comment by DenB10** [comment]
Simply, the lock button isn't clickable in the quickmenu.
I've tested with the latest depo temporarily loaded both on FF esr and developer edition, same result :(

**Comment by DenB10** [comment]
I tried to replace the line 125 of the tools.js file (`addTileEventHandlers(tile, (e) => {`) with the old code (`tile.onclick = function(e) {`) and that works!

**Comment by ssborbis** [comment]
Got it fixed.
