### ISSUE TITLE
Context menu issue

### ISSUE THREAD

**Issue by DenB10** [ssborbis/ContextSearch-web-ext#199]
I'm using daily Firefox ESR.
While testing version 1,16 with updated FF developer edition, I've noticed the context menu entry is not the same: `Search for "search terms"` with developer edition vs `Search for` only with esr.
I have to remove `visible: true` part of the line `browser.contextMenus.update("search_engine_menu", {visible: true, title: title});` in background.js to obtain the right entry in FF esr.

**Comment by ssborbis** [comment]
I try to retain as much compatibility as I can with FF57+, but some things just don't work well will older APIs. If i remember correctly, the visible: true / visible: false param was added to prevent the menu showing up when it isn't supposed to. If the ESR version doesn't handle that part of the API, I can see how it would cause problems. I'll take another look at the reasoning behind it, but I'm sure it was added to fix another issue.

**Comment by ssborbis** [comment]
I think this issue was cleared up when I got the addon compatible with Waterfox. If there are still issues with ESR, I'll reopen.
