### ISSUE TITLE
"Add Custom Search" yet another step to a tedious procedure

### ISSUE THREAD

**Issue by osrambilux** [ssborbis/ContextSearch-web-ext#20]
"Add custom search" adds yet another step to a tedious procedure that began with FF58 fucking up the search box functions.   Can you add the ability to remove the "add custom search" option from the right-click options?  I moved to your addon to decrease the steps involved with searching.  Now you've added another step.

**Comment by ssborbis** [comment]
Are you doing a lot of context-menu based searches from text boxes and seeing the combined menu?

**Comment by ssborbis** [comment]
Check the betas.  FYI I did very little testing

https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta?page=1#version-1.2.9.1b
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext-lite/versions/beta?page=1#version-1.2.9.1b

**Comment by ssborbis** [comment]
v1.2.9.1b2 attempts to address the 2-tier menu in the context-menu when right-clicking selected text in an <input> element. Try leaving the Show Add Custom Search option enabled and see if the new code doesn't take care of your issues.

https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta?page=1#version-1.2.9.1b2
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext-lite/versions/beta?page=1#version-1.2.9.1b2

**Comment by ssborbis** [comment]
v1.3.0

**Comment by osrambilux** [comment]
v1.3.0 works like a charm on all my setups.  Thanks for all your work.
