### ISSUE TITLE
Something's gone wrong with Settings

### ISSUE THREAD

**Issue by DavidBE-UK** [ssborbis/ContextSearch-web-ext#203]
Just got an update to this extension in Firefox. The displayed Settings are now all wrong, including nothing listed under Search Engines - but it is actually still working as per what my settings were, including the search engines. Importing my previously exported settings did not change the incorrect and no-search-engines settings displayed, even after a Firefox re-start, but it is still actually working according to the settings I wanted and which Settings displayed before the update.

**Comment by DavidBE-UK** [comment]
And it's the same in Chrome. No search engines listed in Settings after the update, and settings not what they were (e.g. left-click action now showing open in this tab, not background tab as I had it), but in actual use all the engines show up in the Quick Menu, and the actions are what I had set (e.g. open in background tab rather than in same tab as showing in settings).

**Comment by ssborbis** [comment]
Sounds like a bug in the code for the options page. I tried an old config, but couldn't get the bug. Can you send me your config?

**Comment by ssborbis** [comment]
Also, if you open the console (CTRL+SHIFT+K in FF), what errors do you see?

**Comment by ssborbis** [comment]
I actually got it to happen once by importing and old config. The search engines didn't display, but when I refresh the page, they do. Is that what you're seeing?

**Comment by DavidBE-UK** [comment]
What I am seeing is that when I use the extension on a web page, everything is as it was and as I configured it (and presumably as still is in the attached options i saved to get the same configuration in Firefox - my usual browser - Google Chrome and Edge Dev, the new based on Chrome version of Edge MS is developing). But the actual settings page is both missing things and has settings that are neither what I set nor what the extension is doing.

In the Settings>Quick Menu, it is not displaying the tool icons in the Tools section. In the Search Engines section it is showing no engines at all, even though when I select text on a page the Quick Menu is showing all 28 I previously configured (plus all the tools, re-ordered as previously configured, that it is not showing in the Quick Menu Tools section). And in the Settings>Search Engines, as well as not showing any, clicking Add now has no effect.

It is also, in the Quick menu Search Actions, showing every one as Open in Current Tab, even though that's not how I configured them and in use it is doing what I did configure, which was Open in Background Tab.

(I'm afraid I've only been using your extension for a couple of days after moving from a similar one, and I'm not used to it enough to be sure I'm recognizing what setting may not be showing as set.)

I'm afraid I'm not up on use of the console - all I'm seeing is:

error options.js:1096:11
loaded @ moz-extension://9f92aa0e-adc3-4ea1-871d-33d081b03fcd/_locales/en/help.html options.js:1100:11

I am seeing the same issues as of today's update in Firefox, Chrome and Edge Dev.
[Config.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/3494300/Config.zip)

**Comment by ssborbis** [comment]
Using v1.16

When I import your settings, the options page shows empty/bad values and the search engine list is blank. I see the `error options.js:1096:11`. If I refresh the page, everything is back to normal and I can see all your engines and settings. If you refresh the page, do the settings update correctly? Doing a little testing is showing me that sometimes the options page doesn't show the imported settings correctly until the page is reloaded. I'm looking into that issue now. If your settings don't show correctly after refreshing the options page, we have some bigger issues. Let me know

**Comment by DavidBE-UK** [comment]
Well, I had tried refreshing the settings page in all 3 browsers several times earlier. Made no difference. But starting this reply I thought I should try again. In both Chrome and Edge Dev (which is the extension from the Chrome store) THIS time on refreshing the settings page went back to normal, showing the tools, search engines and changed settings.

However, multiple refreshes in Firefox and it is still as I described, no tools, no search engines, not showing open in background etc.

BTW, my settings have never been imported into Firefox. I set up what I wanted in Firefox after installing the extension, then exported, and then imported into Chrome and Edge Dev.

**Comment by ssborbis** [comment]
Strange. I'm always getting bad settings on import, but good settings on the first refresh every time.

K, a few questions ... lets stick with FF, since that's failing consistently.

What browser version? What OS?
Are you using a non-English language?
What's your hardware like? Old? New? (in case it's some timing issue in my javascript)

**Comment by DavidBE-UK** [comment]
FF 68.01. Windows 10 Home 64 bit 1903. English en-GB. Hardware is a Dell Inspiron 7577 Intel i7-7700 16GB RAM a bit over a year old.

**Comment by ssborbis** [comment]
Basically the same setup I'm testing on. I tried switching to en-GB from my en-US, but no effect. 

Just to be absolutely clear, the Options page doesn't display correctly, but all your ContextSearch menus and functions work as expected? If so, that means the settings are importing correctly and I can focus on the Options page.

**Comment by DavidBE-UK** [comment]
Yes, the extension appears to be working correctly and as I configured it; it is just the settings/Options page that is not working.

**Comment by DavidBE-UK** [comment]
The one thing I haven't tried is importing the settings into FF and seeing if that might kick the options page into working. I'm not sure what is more useful for you - me trying that and it maybe working; or me keeping it in the current state where the extension functions as intended but the options page is all wrong.

**Comment by ssborbis** [comment]
I think i've got it figured out. New version 1.17 going up for FF. Let me know if that fixes the issue and I'll update chrome

**Comment by DavidBE-UK** [comment]
Just got the update in FF. Opened the Options page and it appears to be fine now, showing the search engines, tools and the option settings I remember. Great work. :)

And thanks for the extensions - better than the ones I was using (and great that the Chrome one installs and works in MS Edge Dev too).

**Comment by ssborbis** [comment]
Phew, good deal. I've updated Chrome as well. 

Thanks for your help.
