### ISSUE TITLE
Search results need - in place of spaces

### ISSUE THREAD

**Issue by robertheadley** [ssborbis/ContextSearch-web-ext#205]
https://github.com/ssborbis/ContextSearch-web-ext/issues/83#issue-349631786
is similar, but in that case, spaces are replaced by + sites.

I understand that the regex option is there to give me an option to fix it, but I don't personally know how in this case. 

If I search for Firstname lastname on https://www.advancedbackgroundchecks.com/, the search operator comes back as firstname-lastname and I don't know how to make this search work with that. Maybe a section of the wiki  where existing regex examples can be given?

**Comment by ssborbis** [comment]
Looks like that engine changes the URL a bit from the template on the search form CS sees when adding it.

Using Template: 
`https://www.advancedbackgroundchecks.com/name/{searchTerms}`

and regex:
`"\\s","-"`

I was able to get a good query. Obviously if you want to set a zipcode or age in your template, you'd just follow the results page url format

> Maybe a section of the wiki where existing regex examples can be given?

The results URL switcheroo might have been what threw you, but there's a simple example shown in the regex field when empty. Not much more to it than that except it does allow for multiple replacements, one on each line ( the field is an expandable textarea )
