### ISSUE TITLE
Settings menu not scrollable

### ISSUE THREAD

**Issue by iav** [ssborbis/ContextSearch-web-ext#207]
Left pane on settings menu not have a scroll.
It makes impossible to access import export if screen size 1200x800 and taskbar and toolbar are active.
All UI components must be scrollable/paneable.

**Comment by ssborbis** [comment]
Fixed in the repo, if you're sideloading.

Just zoom the page out to see the buttons until I get a release out.

**Comment by ssborbis** [comment]
Looks like a few other things in the options page could use some low-res tweaks. I'll tidy a few things up.

**Comment by iav** [comment]
Thank you!

**Comment by ssborbis** [comment]
v1.18 is live. It *should* fix the low-res issues.

**Comment by iav** [comment]
Thank you!
