### ISSUE TITLE
Doesn't work on this page, http://bbs.fobshanghai.com/dig.php

### ISSUE THREAD

**Issue by gsessylu** [ssborbis/ContextSearch-web-ext#209]
Thanks for this useful addon.
But it doesn't work on this page, http://bbs.fobshanghai.com/dig.php
I use the chrome extension.

**Comment by ssborbis** [comment]
Seems to be working fine in Firefox but not Chrome. I'll take a look.

**Comment by ssborbis** [comment]
Ok, I think I have it fixed.

**Comment by ssborbis** [comment]
I'll get a new release out in a couple days, hopefully, with the fix.

**Comment by ssborbis** [comment]
If you were still having issues, I just pushed a new version (1.18) that has a workaround for that problem.

**Comment by gsessylu** [comment]
Many thanks! It works now! Great extension!
