### ISSUE TITLE
search terms enclosed in quotes - doesnt work with POST engines

### ISSUE THREAD

**Issue by sign-in-smth** [ssborbis/ContextSearch-web-ext#21]
hello

could you pls check, i just noticed i send smth in quotes to a GET engine its fine but not if its POST.
i think it used to work before in old versions though i'm not entirely sure.

thank you!

**Comment by ssborbis** [comment]
Looking at the code I'm guessing it never worked. 

https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/1.3.1b1
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext-lite/versions/1.3.1b1

FYI I added some native app code for getting the hidden engine list. If you're using the native app and FF58+, hiding the engines in Options->Search->One-click Search Engines should work but I haven't tested much so I'll made this patch a beta for now.

**Comment by sign-in-smth** [comment]
thanks for the update i tried it with 4 POST engines-
for 3 of them it fixed the issue, 
for 1 of them still not, its that adult db engine the pornteengirl, do you still have it?

about native app i honestly haven't used it yet because i rarely ever change any engines, manual option still works fine for me.

**Comment by ssborbis** [comment]
Hmm...the one that didnt work encodes to windows-1252. Were the other 3 that did work utf-8?

**Comment by ssborbis** [comment]
What search terms are you using for the one that didn't work? I'm getting the same results from the search plugin as the website form.

**Comment by sign-in-smth** [comment]
oh its my bad i see it now, some limitation of this engine i suppose, doesnt work with quotes neither from the webpage nor the search bar. my mistake sorry, so pls disregard.

the other three that did work were windows-1251 and utf-8.

one new thing: if i try to open search results from a POST engine in current tab (quick menu -> search action -> right button by default) then search doesnt work.

**Comment by ssborbis** [comment]
Nice find. I forgot to define a var for the Open In Current Tab function. Easy fix. I'll get a beta after I tie up some loose ends.

**Comment by ssborbis** [comment]
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/1.3.1b2
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext-lite/versions/1.3.1b2

**Comment by sign-in-smth** [comment]
thanks!

Q#1 
is there anything in current code that could cause random success of this fix? 
i noticed with one POST engine maybe in like 10-20% of test attempts search in current tab sent GET with empty parameters instead of POST with given params. 
but it seemed really random. like even i click back to original page from current failed search try again a time or two and it sends POST with search terms properly.

Q#2
with this engine below search in new tab works fine;
but search in current tab gives "information will be sent over insecure connection" dialog and fails.
https://www.sendspace.com/file/k4gcag

**Comment by ssborbis** [comment]
1. I'm pretty sure it's a timing issue on the code injection. I've played around with the different injection points the API provides but couldn't eliminate that particular problem. I'll give it another look though

2. I've experienced this when, say a search plugin has urls listed as http but a website redirects to https on the form site. You end up having a search plugin submitting form data to https over http and throws the error. The one engine I experienced this with I simply removed and added a custom engine. The old engine used to work fine but I'm guessing the server was upgraded to use https and the seach plugin wasn't updated.

**Comment by ssborbis** [comment]
2. Also seems to happen when searching a string from a https website to a POST form on a http website. I'll need to do some investigating.

**Comment by ssborbis** [comment]
Ok, looks like we're taking on a few separate issues with (2).

The listener for the POST landing page is being triggered before the url change when updating the current tab. I had been comparing the url to about:blank to time the code injection but that doesn't work for opening in the current tab where the url is never about:blank. I'm now comparing tab url to search engine url. Hopefully nothing gets weird due to redirects.

Some search engine plugins are not using the correct protocol, maybe because they're outdated. I'm now replacing the form action protocol listed  in the search plugin with the landing page protocol (window.location.protocol), with the assumption the two protocols should always match. May not be the case though so I'll keep an eye out for unwanted behavior.

Still not sure about problem 1. Maybe the two are related and this new code will help. We'll see.

https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/1.3.1b3
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext-lite/versions/1.3.1b3

**Comment by sign-in-smth** [comment]
oh this is so complex -) i'm just glad you are aware q1 may sometimes happen. i tried it again with this version, at first it seemed gone, then occurred once in a while again but not often and its really not that big a deal.

the q2 seems fixed, thank you!!

and most importantly its good to see the addon growing stronger and getting new features all the time. i sincerely admire the work you've done. if i notice any issue i'll be sure to report it for you here. my best regards.

**Comment by ssborbis** [comment]
No problem. And thanks for all the testing and bug reports. It's great to have users willing to contribute.
