### ISSUE TITLE
A couple quickmenu quirks

### ISSUE THREAD

**Issue by narcolepticinsomniac** [ssborbis/ContextSearch-web-ext#216]
Chromium 74.0.3729.169 {Cent)
Current master

Not sure if these are new, or if I'm just noticing them more recently because I've been using it more, but I'm running into them pretty often.

More often than not, quickmenu quickly flashes, unstyled, and out of position for a split second before it repositions and styles correctly.

When quickmenu is launched via long right-click toward the top of the viewport, if the search input ends up positioned under the cursor, the traditional context menu gets triggered inside the quickmenu upon right-click release.

[Screen record](https://streamable.com/dr4df)

**Comment by ssborbis** [comment]
There are several bugs in the main repo that don't appear in the latest release. I'm working with a few users to test some new features that have come with a glitches. I'll try to get a fix with the next push.

**Comment by narcolepticinsomniac** [comment]
I should've been more clear. I'm seeing both issues in the CWS version. I tested the master to confirm they were still problematic.

**Comment by ssborbis** [comment]
Ah, ok. Either way, I'm hopefully going to make a push in a few that might fix the qm opening unstyled. The mouseover the search bar might be more involved. I'll run a few tests on chrome first

**Comment by narcolepticinsomniac** [comment]
Cool. Yeah, I thought I saw some commits that might be related, that's why I checked the master.

On a side note, I just noticed one particular search engine failed to show up in the quickmenu after importing. It shows up in the other menus though. Not sure it's warrants opening a new issue, but maybe worth mentioning.

Template:
`https://www.google.com/search?q=intext:"{searchTerms}" intitle:"index.of" +(wmv|mpg|avi|mp4|mkv|mov) -inurl:(jsp|pl|php|html|aspx|htm|cf|shtml)`

![qmenu](https://user-images.githubusercontent.com/14100003/65496197-0016f800-de86-11e9-89bd-e5c50eb665a8.png)

**Comment by ssborbis** [comment]
Ok, I think the QM opening weirdness should be fixed in the push I just made. I'll need to dig around the code a bit to fix the context over searchbar bug.

The search engine not showing the qm is damn strange. the Toolbar and QM use the exact same code to do the layout.

**Comment by ssborbis** [comment]
Would you mind posting the json for that search engine?

Open CS options and open the console window and post the output to this:

```JSON.stringify(userOptions.searchEngines.find(se => se.title === "your_search_engines_title"))```

I'll try it on my config and see what's going on

**Comment by narcolepticinsomniac** [comment]
>I think the QM opening weirdness should be fixed in the push I just made.

Yep, LGTM. Nicely done.

[json](https://pastebin.com/ivsivZdn)

**Comment by ssborbis** [comment]
That engine shows up in the qm for me - last row, last engine, same as yours. You could try moving it to a different position in the menu. Bug or some weird cache issue, dunno.

**Comment by narcolepticinsomniac** [comment]
Huh. Didn't even think to inspect, but it's erroneously hidden for some reason. Must have something to do with the 'Maximum number of search engine icons per row' setting, which is set to '6'. If I set it to '7', it shows up, but obviously 6 per row should suffice.

![2019-09-24 05_31_17-A couple quickmenu quirks · Issue #216 · ssborbis_ContextSearch-web-ext - Cent B](https://user-images.githubusercontent.com/14100003/65500411-4459c680-de8d-11e9-9647-f7d14f8ab92e.png)

**Comment by narcolepticinsomniac** [comment]
>I'll need to dig around the code a bit to fix the context over searchbar bug.

I'm not sure I'd call it a bug. It's really expected behavior, it just only occurs when positioning is restricted so that the cursor is positioned to trigger the context menu. To prevent that, you'd probably need to disable the context menu until it's clearly triggered by a deliberate user action.

Maybe overkill, but something like this in `quickmenu.js` does the trick:

```
document.oncontextmenu = () => {
	if (!document.body.hasAttribute('data-context-menu-enabled')) {
    return false;
	}
}

function enableContextMenu() {
  document.body.dataset.contextMenuEnabled = '';
  document.removeEventListener('auxclick', enableContextMenu);
  document.removeEventListener('keydown', enableContextMenu, true);
}

document.addEventListener('auxclick', enableContextMenu);
document.addEventListener('keydown', enableContextMenu, true);
```

**Comment by ssborbis** [comment]
If I'm reading it right, that code would work for that particular opening method when opening over the qm, but cancel the first context menu event on other opening methods. 

Would it do the same thing as...?

`document.addEventListener('contextmenu', (e) => e.preventDefault(), {once: true});`

**Comment by narcolepticinsomniac** [comment]
![kevin](https://user-images.githubusercontent.com/14100003/65580449-a414a800-df47-11e9-8b87-d20aaa656757.jpg)

To be fair, I did acknowledge that it may be overkill, as is the case with most of the js I write - it's not exactly my strong suit. Not like I wasn't aware that `once` was the way to go, I just wasn't getting the syntax right, so I decided to write a short story instead. =)

**Comment by ssborbis** [comment]
No worries. I just wasn't sure if I was missing something. For what it's worth, I'm far from an experienced coder. This addon is essentially the first public software I've written. I think it's safe to say I'm learning on the fly, as I'm sure are a lot of other devs.

**Comment by narcolepticinsomniac** [comment]
>I just wasn't sure if I was missing something

Presumably, the only benefit of the longer version would be that if the context menu isn't erroneously triggered, the first invoking of the context menu should still always work, whereas with the shorter version, I don't guess it will. Depends if that matters much to you. 

I could lie and say my intention was to account for that, but even so, I'm sure there's a more concise way to do so. Canceling it once across the board is probably the way to go. Not many people are gonna be invoking the context menu, and worse case scenario, they need to do it twice.

**Comment by ssborbis** [comment]
I think this will work for all opening methods

```
// prevent context menu when using right-hold
function preventContextMenu(e) { if ( e.which === 3 ) e.preventDefault(); }		
document.addEventListener('contextmenu', preventContextMenu);
document.addEventListener('mousedown', function rightMouseDownHandler(e) {
	if ( e.which !== 3 ) return;
	document.removeEventListener('contextmenu', preventContextMenu);
	document.removeEventListener('mousedown', rightMouseDownHandler);
});
```

Basically, it cancels the context menu until the document first sees a mousedown event from the right-button.  Add it to quickmenu.js and it should take care of that bug.

**Comment by narcolepticinsomniac** [comment]
Whatever works. I've been using the code I posted, which isn't all that different as far as the goal it accomplishes. I added a keydown listener in case the context menu was launched via shortcut, but that's probably overkill. At some point, I'd prefer to switch back to the CWS version, so I hope you add a fix one way or the other.

**Comment by ssborbis** [comment]
I'll add the changes to the master. It'll be in the next release.
