### ISSUE TITLE
Source map error in lib/browser-polyfill

### ISSUE THREAD

**Issue by z87** [ssborbis/ContextSearch-web-ext#217]
A warning is logged in the Firefox console:

> Source map error: TypeError: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://3de46af9-67b1-4817-8361-980f15f8cdb7/lib/browser-polyfill.min.js
> Source Map URL: browser-polyfill.min.js.map [\[Learn more\]](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors#NetworkError_when_attempting_to_fetch_resource)

According to Mozilla [Bug 1437937: WebExtensions Doesn't Find Source Maps](https://bugzilla.mozilla.org/show_bug.cgi?id=1437937), source map would not load even if it was actually included in the extension.

It should be fine to remove browser-polyfill from `firefox_manifest.json` as it's a NO-OP in Firefox. Tested to work in 69.

For other browsers, maybe remove `sourceMappingURL` from `browser-polyfill.min.js`.

**Comment by ssborbis** [comment]
Thanks for the heads up. 

Looks like a new version of browser-polyfill was released 9 days ago. I'll check if that issue was addressed and go from there.

**Comment by ssborbis** [comment]
I'm looking to see if the new version throws the warning, but I'm not seeing the warning in the older version to compare. 

You're seeing it in the browser console? ( ctrl + shift + J )

When does it appear? At browser load? Temp extension load? Repeatedly?

**Comment by z87** [comment]
Sorry, should've provided more info.
STR:
1. load any webpage
2. open content console (Ctrl+Shift+K)
3. switch to Debugger tab and back
4. error now appears and will repeat on reload

I don't think new version of polyfill fixes that as it still includes the source map comment.

**Comment by ssborbis** [comment]
Yep, had to remove the sourceMap line

**Comment by z87** [comment]
Thanks! I've added a comment in the commit regarding an unrelated typo.
