### ISSUE TITLE
Strange pattern when hovering over link

### ISSUE THREAD

**Issue by Carottinger** [ssborbis/ContextSearch-web-ext#220]
Sometimes some pattern appear in the area where the quick box would appear even if nothing is triggered (clicked, highlighted) but already when hovering over a link
![Bildschirmfoto von 2019-10-29 15-02-18](https://user-images.githubusercontent.com/48221698/67776368-84016880-fa60-11e9-920c-09e3e9910e47.png)

**Comment by ssborbis** [comment]
What version / browser / OS are you using?

**Comment by Carottinger** [comment]
I use Firefox for Ubuntu canonical - 1.0 v70.0 (64-Bit) on elementaryOS 5.0 (Juno)

**Comment by ssborbis** [comment]
That's a weird one. I'm testing on an ubuntu vbox and can't reproduce the bug.

Does it stop if this addon is disabled?

Are you able to inspect the DOM elements to see if it's actually the quick menu or some other object from this addon? The colors almost suggest it's the highlighting navigation bar, but I don't know why it would be there. Next time it happens, try to Ctrl+Shift+C and inspect the element and see what it is. That will give me a place to start looking through the code.

**Comment by Carottinger** [comment]
The flickering is off when I deactivate ContextSearch (and reload the page, not before). This is the source code of the area containing the link an the debug view of it
![flicker](https://user-images.githubusercontent.com/48221698/68067255-958a8f00-fd44-11e9-8d80-8eda5f6035d2.jpg)
![debug](https://user-images.githubusercontent.com/48221698/68067256-98857f80-fd44-11e9-95ba-7e97d28e64bd.jpg)
[source.txt](https://github.com/ssborbis/ContextSearch-web-ext/files/3800196/source.txt)

The debug looks identical after I re-activated the plugin and the flickering starts again

**Comment by ssborbis** [comment]
Whoa, is that pattern showing up outside of the webpages in the toolbar / menu bar area? That's gotta be a FF bug. I'll take a look at my injected code for links, but nothing in this addon could be causing that pattern, excepting a bug in the browser code.

**Comment by Carottinger** [comment]
Currently I cannot reproduce the flickers but it the position was relative to the hover position and extended outside the webpage content into th FF header (menubar, favorite bar, address bar) - see left top from flicker.jpg)

**Comment by ssborbis** [comment]
I forgot to ask, are you using the latest release version of this addon or pulling from the master?

I've been looking on my ubuntu install with ff70 canonical and can't reproduce the bug. I have a vague memory of seeing something like this a few months ago. Given that it can occur over the browser menu area, it's definitely a FF bug this addon is triggering, but I can't do much to tease out the source until I see the bug in action. If you find a reproducible method, I can go from there.

**Comment by Carottinger** [comment]
I uninstalled the addon and re-installed it after restart (loaded the old settings though). After that it happened.

**Comment by Carottinger** [comment]
We could do a skype session if you want to take a look at my browser

**Comment by ssborbis** [comment]
Do you have a screen capture app like https://www.screentogif.com/ ? I'd like to see it in action.

**Comment by Carottinger** [comment]
This is a screen recording and the effect occurred in the last 30% but I can't see it in the recorded file. It mostly happens when opening a new window and hovering over the new page elements
![Peek 2019-11-30 10-58](https://user-images.githubusercontent.com/48221698/69899051-565e5680-1361-11ea-8a49-c93b0272892b.gif)

**Comment by ssborbis** [comment]
This is a difficult one to pin down. I'll keep an eye out on my ubuntu install and if I can trigger the bug, I'll let you know. I've been searching the moz dev pages for similar problems, but haven't found anything comparable.

**Comment by Carottinger** [comment]
Finally I managed to catch it! You can seee it at the end of the gif
![Peek 2019-12-07 11-06](https://user-images.githubusercontent.com/48221698/70372630-e8c2a500-18e1-11ea-8eb7-abd14889091e.gif)

**Comment by ssborbis** [comment]
Got it. Yeah, I'm pretty sure I've seen this before in FF. It's kinda like a video card glitch. No idea what could be causing it from this addon, though.

**Comment by ssborbis** [comment]
I assume this has been cleared up by the Mozilla devs. If not, I'll reopen.
