### ISSUE TITLE
Open results in new tab

### ISSUE THREAD

**Issue by Nessus85100** [ssborbis/ContextSearch-web-ext#221]
When opening search results in a new tab the tab it's not empty. It opens the Firefox Home default. Is this intentional?. If yes this is kind annoying because it shows only for a split of second and confuses users if you have many tabs opened it looks like the results have opened on top of some other currently open tab.

IMO you should open a blank tab or at least have an option so the user can choose?

Cheers
Nessus

**Comment by ssborbis** [comment]
> When opening search results in a new tab the tab it's not empty. It opens the Firefox Home default. Is this intentional?

There's a Firefox option under Settings -> Home -> New Tab that determines how new tabs are displayed ( FF Home / blank )

When this addon creates a new tab, it must initially respect that setting before loading a results page. There may be a delay in processing the results page ( networking / cpu load / etc ) that keeps the default FF Home displayed for a sec

**Comment by Nessus85100** [comment]
I'll have to disagree with that. That setting has nothing to do with the search results new tab and there is no reason to respect a setting for a split of second!. When i want that tab i can click on the + sing to get it. When the new tab search results opens it should be on blank tab. It's a new search results tab, not a Firefox Home default tab and then... search results tab.

But it's my opinion. If you want to leave it like this, like i said, at least add an option in extensions settings.

Cheers
Nessus

**Comment by ssborbis** [comment]
By respect, I mean I have no control over that setting. I have mine set to "blank" and get a blank page when opening a new tab.

**Comment by ssborbis** [comment]
After setting Firefox to open new tabs to Firefox Home, I'm not sure we're seeing the same behaviour. Here's a screencap when I open a search to a new tab.

![new_tab](https://user-images.githubusercontent.com/24310997/68454834-71ed9b80-01bf-11ea-9d95-93a3fbe98587.gif)

**Comment by Nessus85100** [comment]
That's happening only when the search engine is google. If you use any other search engine the behavior it's different even in a system (mine) with quad core cpu and 4GB ram.

> By respect, I mean I have no control over that setting. I have mine set to "blank" and get a blank page when opening a new tab.

Strange... the previous extension that i was using for search was showing a blank page even if my setting was to Firefox Home (Default).

Anyway, this is an annoying thing in an otherwise exceptional extension and it would be good if you can find a solution.

**Comment by ssborbis** [comment]
> Strange... the previous extension that i was using for search was showing a blank page even if my setting was to Firefox Home (Default).

You may be right that this is the default behaviour. I've set my new tabs to display the Firefox Home page and have yet to see it appear when opening to a new tab using any of my search engines. Can you take a screen cap of what's going on? Does it happen on a fresh profile?

**Comment by Nessus85100** [comment]
There is no need for screenshot. It's the page that you get when you click the + icon in the tab bar and you have set the default Firefox Home page in settings. And yes it happens in fresh profile.

**Comment by ssborbis** [comment]
I'm going through the code and I can't see why that would be happening, especially on a fresh profile.

The only place I can see it possibly happening is when using One-Click search engines.

Can you confirm the search engine's you're using are NOT One-Click search engines? Open CS options > Search Engines manager

Do the engines you're testing have a (FF) next to them, like IMDB in this example?

![ocse](https://user-images.githubusercontent.com/24310997/68710727-b4b3c880-055d-11ea-8f84-c20e687b54fe.png)

The other thing to test is how your browser is handling the tabs.create function in the web extensions API.

Go to `about:debugging` in the url bar, enable Addon Debugging and click the `Inspect` button for this addon.  In the console, enter `browser.tabs.create({url: "https://www.google.com/search?q=firefox"});`  or use some other URL to an engine you know is causing the FF home page to appear with new tabs. If you see the FF home page when calling the API directly, we can go from there.

**Comment by Nessus85100** [comment]
Yes, this is happening only to the one-click engines. All the others are working properly. The thing is that almost all of my search engines are like that and very phew of them are not one-click. So the problem is still very annoying. I mean... after the search results are open, the backward arrow is enabled to Firefox's back/forward navigation so to go back.... to the Firefox Home page.
IMHO this is completely wrong!. This should work the same for all types of search engines.

**Comment by ssborbis** [comment]
I think I have this fixed locally. If you're sideloading, I can update the repo. Be sure to backup your config first.

**Comment by Nessus85100** [comment]
Can you give me the .xpi file to test it?

**Comment by ssborbis** [comment]
I can give you a zip file to load as a temporary addon.

[contextsearch_web-ext-1.19.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/3952847/contextsearch_web-ext-1.19.zip)

1. export you CS config file to have a backup in case anything goes wrong
2. browse to `about:debugging`
3. enable debugging ( older FF versions ), click the `This Firefox` tab to the left ( new FF versions )
4. click `Load Temporary Add-on` button and browse to the zip file above.

When you want to unload the temp version, close FF. If you use the `Remove` button from the `about:debugging` page, it may remove your config file as well.

**Comment by ssborbis** [comment]
v1.19 is out and I think the fix for this issue is in there. Let me know

**Comment by Nessus85100** [comment]
Yes, i can confirm that it's fixed.
Thanks a lot for taking care of this.

Cheers
Nessus
