### ISSUE TITLE
context menu click just opens the ContextSearch Configuration page

### ISSUE THREAD

**Issue by roger21** [ssborbis/ContextSearch-web-ext#222]
I don't know what's up

just left clicking (or any other click) on the search engine entry from the context menu just redirects to the ContextSearch Configuration page

the quick menu works fine

any ideas ?

**Comment by ssborbis** [comment]
I have a fallback somewhere to open the config page if there are no engines found ( searchEngines length = 0 ). I can see a scenario where a user has all one-click engines / bookmarklets / folders / etc , but no type = CS search engine that might cause this.

Something to try:

open the browser console from the CS options page and type `userOptions.searchEngines` and see if anything comes up. If not, try adding a new search engine through the manager. If the array has even 1 entry, it shouldn't cause that problem.

If that doesn't work, we'll have to try some debugging.

**Comment by roger21** [comment]
> if there are no engines found

that was it, in the json export i noticed the searchEngines array was empty, everything was in the children array

i imported the search.json.mozlz4 file and all was good

since all my engine were already there at start i didn't feel like doing the import (and the quick menu was working, it still is)

thanks

**Comment by ssborbis** [comment]
I patched the code to prevent this from happening in the future. It'll be included in the next release.
