### ISSUE TITLE
Cant add search.json.mozlz4

### ISSUE THREAD

**Issue by Shinero** [ssborbis/ContextSearch-web-ext#223]
When Im trying to add search.json.mozlz4 file its stuck with "loading remote content" message. The list of search engines above is also empty and "Add" button doesnt work.
Fresh instal of Firefox 71 on Windows 7 x64. I tried to delete addon and redownload it, still doesnt work.

**Comment by ssborbis** [comment]
Just checked on my win10 FF71 install, and my search.json.mozlz4 file loaded ok. Do you get any errors in the console? (CTRL+SHIFT+K from CS options page)

**Comment by ssborbis** [comment]
You can try to zip up your search.json.mozlz4 file and post it here or email it to me directly ( ssborbis@gmail.com ) and I'll try importing from my install.

**Comment by Shinero** [comment]
Yeah, there are some errors, but I dont really know what they mean. And I dont think there is anything unusual with my search.json.mozlz4 file, I just reinstalled firefox, so its a new file with only a few search engines in there.

But the thing is, that the addon installed from my synchronization, so maybe I should try it on a new profile.

Here is the screenshot and the errors in plain text.
![45687er9](https://user-images.githubusercontent.com/20263394/70384008-27a33a00-1978-11ea-8522-a10b9e0338d3.png)

`K3WGWQLJMPMPB is not in node tree. Appending ... searchEngineManager.js:553:12
Native Messenger addon not installed. Removing native content options.js:707:11
error options.js:905:11
TypeError: root.children is undefined
searchEngineManager.js:554:4
loaded @ moz-extension://92d4779d-e072-478e-97d6-15a590d0edf4/_locales/en/help.html options.js:909:11
TypeError: userOptions.nodeTree.children is undefined
options.js:38:5
AniDB not included in userOptions.searchEngines options.js:32:13
`

**Comment by Shinero** [comment]
Ok, even on a new profile with default search.json.mozlz4 file it doesnt work. And actualy, I cant even use it to search anything from context menu or quick menu.

**Comment by Shinero** [comment]
Oh wait, I see now... I was using the Lite version which will not be supported anymore... Sorry, I didnt knew that.

**Comment by ssborbis** [comment]
> Oh wait, I see now... I was using the Lite version which will not be supported anymore... 

Ah, that'll definitely cause some problems. If you can export your config file from CS lite, you **should** be able to import it back into the most recent normal CS version. If i remember correctly, the lite version was the exact same as the normal version with the native messenger permission removed.
