### ISSUE TITLE
V1.19 Quickmenu shifts slightly when opened.

### ISSUE THREAD

**Issue by streetwolf** [ssborbis/ContextSearch-web-ext#224]
After upgrading to v1.19 I now notice that when the Quick Menu appears the icons and even the menu itself shifts slightly.  Sometimes the shift doesn't happen but testing shows it happens more often than not.  I set different menu/icon size percentages.  Whatever values I set results in the shift.  Played with Grid size and the other values controlling the Quick Menu with no luck.

I have a 4K monitor at 3840x2160 with a DPI of 200% if that helps.  Running the latest Fx Nightly under Windows 10 Pro.

**Comment by streetwolf** [comment]
Found the cause.  I use page zoom values higher than 100% for most sites because text and graphics are too small on my 4K monitor even at a DPI of 200%.  It appears that unless the page has a zoom level of 100% the Quick Menu will shift.  I suppose the higher the zoom level percentage the more the shift appears to be.  I don't recall seeing this behavior prior to v1.19.

**Comment by ssborbis** [comment]
I'm testing at 150% menu scale and 150% DPI and I see a slight shift in the menu. I was going to suggest trying this addon in chrome to see if the problem persists. I've run into a few cases where DPI changes cause bugs in FF but not in chrome. One of the more apparent being the mouse lag? when dragging the quick menu or side bar menu around the screen. The higher the DPI, the further the menu lags behind the mouse. If you add the lock tool to the quick menu and enable it, you'll get a menu bar you can grab to drag the qm around. You should see a ton of lag at 200% DPI in FF, but not chrome. Both problems would likely be fixed if I could find a work around for one, but it's been a persistent issue.

**Comment by ssborbis** [comment]
Nevermind about checking Chrome. I'm seeing it there too. This must be a rounding issue when setting the qm position. I didn't test with page zoom. I see it now.

**Comment by ssborbis** [comment]
How bad is the shift? A pixel or 2 or is it significant?

**Comment by streetwolf** [comment]
It’s noticeable but it seems to be only a pixel or two. But I’m running 4K so the shift might be more noticeable at say 1920x1080.  The shift can be in any direction.  Sometimes it’s just the box itself, sometimes both the icons and box. As stated it only started with the current version.

--------------
Regards,
Gary

**Comment by ssborbis** [comment]
I've got a potential fix in the repo

**Comment by ssborbis** [comment]
whoops, it only works on some sites. Doesn't work here

**Comment by streetwolf** [comment]
Back to the drawing board.

--------------
Regards,
Gary



________________________________

**Comment by ssborbis** [comment]
Did this resolve in the latest release? I can't get it to trigger, but it may be my settings.

**Comment by streetwolf** [comment]
My bad,I forgot about this issue.  The release I am on is 3.42.1 and things some to be OK now but tbh I haven't been looking for it.  Perhaps the reason is that you fixed it and therefore I never noticed it.  The few tests I just performed didn't have the issue.  I'll check some more today and update you about the results.  But for the moment it looks good. 

I do have another issue which might be an FX issue.  The Quick Menu will scale according to the zoom level I have chosen for the site.  The larger the zoom level the larger the QM will appear and vice versa.  I use a Zoom add-on but it works the same way without it if I zoom using Fx's zoom feature.

**Comment by ssborbis** [comment]
>  I'll check some more today and update you about the results. But for the moment it looks good.

cool

> The Quick Menu will scale according to the zoom level I have chosen for the site.

The qm *should* remain the same size when zooming. There might be a conflict with your Zoom addon.

Windows@150% dpi, qm@150% menu size, this page@160% zoom before opening, I can zoom all the way in or out and the qm remains the same size. It does move, however, since it's not being repositioned according to zoom.

What zoom addon are you using?

**Comment by streetwolf** [comment]
The original issue appears to be fixed based on a lot of testing.  Good job my friend.

As for the new issue II use Zoom Page WE.  But as I said I disabled it and tried the built in Zoom feature within Firefox and had the same results.  Remember I’m on Nightly Version 78.0a1 and Windows 10.  I’ve attached the output of about:support.  Perhaps I am running using different graphic Features than you are which are causing the issue.  Also it could be the monitor I am using 4K @ 3840x2160.

------------
Regards,

Gary

**Comment by ssborbis** [comment]
I tried on the nightly, 200% dpi Windows 10 ( also on a 4K monitor ) and couldn't reproduce. If you spot any inconsistencies that could narrow down the bug, post it here and I'll open this thread back up.

**Comment by streetwolf** [comment]
Found the trigger that’s causing my issue.  Go to the Firefox Options page.  Under General go to Zoom and UNTICK set ‘Zoom text only’ (I bet you have it ticked).  This will then activate full page zoom.  When I set it to Zoom text only I no longer get size differences in the Quick Menu.  My default zoom here is 100% btw.

I probably set it to full page zoom because of my zoom add-on although it is not a requirement.  I’ll see if being in Zoom test only mode affects anything.  You should now have a way to reproduce my problem if you were testing under Zoom text only.  The problem might still lie with Firefox but I’ll let you make the determination.

------------
Regards,

Gary

**Comment by streetwolf** [comment]
One more thing.  My add-on Zoom Page WE unticks Zoom text only to always force full page zoom.  I suppose it needs to do this to be able to do it's full page zoom.  I also have it set in ZP WE to default to full page zoom.  So now I don't know whose problem it is.  My guess it's the author of ZP WE.  

ZP WE is also a recommended extension so if you can reproduce my problem you can open up a bug report with him to discuss our findings.

**Comment by ssborbis** [comment]
Sweet. I'll see if there's a workaround.
