### ISSUE TITLE
v. 1.19: unable to edit folder in search engines manager

### ISSUE THREAD

**Issue by DenB10** [ssborbis/ContextSearch-web-ext#229]
Hi,
In the new version 1.19, a new feature makes possible to edit a folder in the search engines manager.
But I've noticed I'm unable to edit the folder just after I edit an engine in the group.

**Comment by ssborbis** [comment]
Thanks. Got a fix ready. I'm patching a few more bugs, then I'll add your translations and get an update out.

**Comment by ssborbis** [comment]
I added another entry to messages.js also, FYI. No rush. I won't make an update today

**Comment by ssborbis** [comment]
I had a critical bug to patch, so this fix is in the latest releases ( 1.19.2 )

**Comment by DenB10** [comment]
> 
> 
> I added another entry to messages.js also, FYI. No rush. I won't make an update today

Thank you for the fix but I don't see this another entry added you mentioned ???

**Comment by ssborbis** [comment]
> Thank you for the fix but I don't see this another entry added you mentioned ???

Nevermind. You added it already, I didn't.

**Comment by ssborbis** [comment]
This should be fixed now. I'll re-open if you see otherwise.
