### ISSUE TITLE
Quickmenu (popup) stopped working after v1.19 update

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#230]
Also tried other opening methods like auto and with a "simple click", but the popup doesn't appear. But searching from the traditional context menu or the sidebar still works.

Happens on Ubuntu 19.04 with Firefox v72.0.1.

**Comment by ssborbis** [comment]
are you seeing any errors in the console?

**Comment by ssborbis** [comment]
you can also email me your config and I'll test on my vbox

**Comment by sojusnik** [comment]
Where do I find the config?

**Comment by sojusnik** [comment]
And yes, I see an error message, but it's in German:

> Sicherheitsfehler: Inhalt auf https://github.com/ssborbis/ContextSearch-web-ext/issues/230#issuecomment-578875084 darf moz-extension://81e899ea-1fd2-4aef-ba48-d032cb374520/quickmenu.html nicht laden oder verlinken.

So the content isn't allowed to be loaded or linked. Don't know why, since I didn't change anything.

**Comment by ssborbis** [comment]
I don't think there were any manifest or code changes that would trigger any security policy issues either. Not sure what's up. I'll try your config if you want ( CS options -> Export )

**Comment by ssborbis** [comment]
I tested on Ubuntu 19.xx, FF 72.01 canonical, no issues with a nearly fresh config

**Comment by sojusnik** [comment]
You've got a mail!

**Comment by ssborbis** [comment]
got it. I'll need to make a new release for this bug

**Comment by ssborbis** [comment]
new releases going up, repo updated

**Comment by ssborbis** [comment]
fyi, you need 1.19.2 to get the fix

**Comment by sojusnik** [comment]
Works with v1.19.2! Thank you again for your great add-on!
