### ISSUE TITLE
How to disable icons on right click

### ISSUE THREAD

**Issue by tomncar** [ssborbis/ContextSearch-web-ext#231]
Hi, I'm a bit slow. Could anyone kindly explain how I can disable the "only icons" when I right click on highlighted.
Most of the time I get the icon with the name of the search engine (which is what I want every time)

Is there a way of disabling the random times the only icons pops up.
Any help would be greatly appreciated,
Thanks, Tom

**Comment by ssborbis** [comment]
It shouldn't be random. If it is, something weird is going on.

The menus ( I assume you're using the quick menu ) can be displayed in two ways

Grid: search engines are displayed as icons only, in rows and columns
Text: search engines are displayed as a single column with icons and text

Each folder can have a separate display mode, which can be toggled by 
1. editing the folder in the search engines manager
2. clicking the grid / text tool (if you have tools enabled)
3. Pressing CTRL+. (period)

Is the menu opening to a different view style randomly, or are your subfolders different that your main folder? Or is it something else?

**Comment by ssborbis** [comment]
After reading your post again, I'm wondering if you're wanting to use the context menu and disable the popup menu? You can disable the popup menu by going to tools -> addons -> contextsearch options -> quick menu -> uncheck Enable searching via popup menu

**Comment by tomncar** [comment]
Hi ssborbis, Many thanks for your quick reply and sorry for not replying sooner but I seem to be having all sorts of techy problems lately. I'm getting really fedup with Firefox updates disabling .css (for tabs on bottom & reduced height tabs)
I had disappearing icons in my FF search engines ! . Eventually deleted the json search folder and started again.
Yes the problem before was at random times instead of icon with text (which is what I want) it was randomly displaying the Icon only grid box (which I find difficult)
Sorry to ramble on but I uninstalled ContextSearch-web-ext and have started again . So thanks I found the setting for icon or icon+text . And I remebered again how to add search engines ( which I love  :o)
Now ! Lol. I have another curious thing happening (randomly)
I'm getting both my normal context menu plus ContextSearch-web-ext allready there without having to navigate  ? https://drive.google.com/file/d/1bw7oJXob37qbTmKk3YqqON5CakZs0l2j/view?usp=sharing
I actually really like that but sometimes it does it and other times it doesn't. Am I missing a setting ?
It would be great if both menu's opened with right click
Thanks for taking the time to read this, Cheers, Tom

**Comment by ssborbis** [comment]
> I'm getting both my normal context menu plus ContextSearch-web-ext allready there without having to navigate ? https://drive.google.com/file/d/1bw7oJXob37qbTmKk3YqqON5CakZs0l2j/view?usp=sharing
I actually really like that but sometimes it does it and other times it doesn't. Am I missing a setting ?
It would be great if both menu's opened with right click
Thanks for taking the time to read this, Cheers, Tom

There is a setting under the Quick Menu tab in CS Options `Hide the default context menu when opening the Quick Menu using right-click`

Make sure that is checked.

If you're still getting both the normal context menu and the tiled popup menu, you might try this

```
Linux and MacOS X users may need to set ui.context_menus.after_mouseup = true in about:config for mouse actions to work properly and prevent unwanted menus
```

**Comment by ssborbis** [comment]
You can also disable the quick menu entirely using the first setting in the quick menu

`Enable searching via popup menu`

**Comment by tomncar** [comment]
Was looking for this solution again lol. Firefox updates are a bl**dy nuisance.
Just wanted to say thanks for your additional replies. Much appreciated

**Comment by ssborbis** [comment]
No prob. Glad I could help
