### ISSUE TITLE
QuickMenu: Open folder in new window doesn't work

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#232]
I've configured "middle click" to open all search engines within a folder in a new window. But only the first search engine is shown in a new window, the remaining are opened as tabs in the original window.

Happens on Ubuntu 19.04 with Firefox v72.0.1.

**Comment by ssborbis** [comment]
Any idea if this is a new bug from 1.19+? I know this was working properly in the past. I don't know when it broke.

**Comment by sojusnik** [comment]
Can't help you on this, because I've discovered this feature only today.

**Comment by ssborbis** [comment]
Ok, I have what appears to be a fix. Do you sideload source code from the repo or wait on releases? I'll push the fix to the repo if you want to try it.

**Comment by sojusnik** [comment]
I always wait for the official releases, no need to push it to the repo only for me.

**Comment by sojusnik** [comment]
Works perfectly with the new version, thanks!
