### ISSUE TITLE
Setting to remove "+" after a grouped folder in QuickMenu

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#233]
Thanks for implementing the "group" feature for folders! It's very useful and saves clicks!

One thing that stands out is the "+" (plus sign to expand the grouped folder) after a folder, especially if you have many of them. It clutters the QuickMenu and is somehow redundant, since you can click on the folder, to see all the contained search engines. Therefore, IMHO, it would be very convenient to have a setting, that will allow to remove the "+".

**Comment by ssborbis** [comment]
Looks like setting the limit to a high number doesn't remove the + like it should. Try setting the limit to zero (no limit). That will take care of the issue until I get a patch

**Comment by sojusnik** [comment]
Just to make sure: I would prefer not to have the "+" even if the group limit is set f.i. to 3. The workaround with "no limit" would show all engines within the folder, but the main idea here is to have the most important ones, in my case, the first 2.

As always, many thanks!

**Comment by ssborbis** [comment]
There's a hidden setting to move the + to the group folder label tile. You could try that, and even set a user style to hide the + completely

open the console in cs options and enter `userOptions.groupLabelMoreTile = true;saveOptions();`

**Comment by sojusnik** [comment]
Is there a more user-friendly solution? Don't know how to use the console in CS options and would prefer to toggle it in the CS options.

**Comment by ssborbis** [comment]
Not at the moment. It's pretty simple, though.

1. Open the CS options page
2. Press CTRL+SHIFT+K to open the console ( assuming Firefox )
3. Paste `userOptions.groupLabelMoreTile = true;saveOptions();` into the input bar and press enter

If you want to undo, just replace `true` with `false` and repeat

**Comment by sojusnik** [comment]
With your instructions I was able to remove the + sign, but now the + sign is in the right top corner of the area where the folder icon is. Since I don't want to mess around with user style sheets in Firefox, I will wait for an update.

**Comment by ssborbis** [comment]
Ok, well in case you want to hide them before the next update, you can put this line in your user styles

`.groupLabelMoreTile {display:none;}`

**Comment by ssborbis** [comment]
Oh, and by user styles, I mean the ones in CS options -> General -> User Styles, not the global FF stylesheet

**Comment by sojusnik** [comment]
Did you find time to implement this in the new release? Was looking in the settings, but without success.

**Comment by ssborbis** [comment]
Not yet. It's kinda there, but disabled for further testing.

**Comment by ssborbis** [comment]
Option is in the repo

![groupmore](https://user-images.githubusercontent.com/24310997/79879331-28cb8580-83b4-11ea-8cec-4d97a1e531ff.png)

**Comment by ssborbis** [comment]
changes in v1.20.1
