### ISSUE TITLE
QuickMenu isn't closed automatically with folder actions

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#235]
I've enabled the two checkboxes under "Closing" in the QuickMenu settings. When handling with search engines, the QuickMenu popup closes accordingly, but not when using folders – it stays open after a click on a folder. In my case I use "open in new tab (background)" and "open new window" with middle and right click respectively.

The option to "Open in Background Tab (Keep Menu Open)" is also missing in the Folder's dropdown menu.

Happens on Ubuntu 19.04 with Firefox v72.0.1.

As always, a huge thanks for constantly improving this gem!

**Comment by ssborbis** [comment]
Folder are a special case that don't close on click. I'll have to rewrite the closing code to accommodate those options when searching a whole folder. No biggie.

**Comment by ssborbis** [comment]
A fix? for this is in the repo. I also added the option "Open in Background Tab ( Keep Menu Open ) for folders

**Comment by sojusnik** [comment]
Thanks, the new version works perfectly!
