### ISSUE TITLE
Toolbar popup doesn't show search engines

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#236]
When clicking on the toolbar icon, I only see the search field, but not the search engines. Curiously, when clicking on it several times in a row, the search engines sometimes do appear, but this happens very rarely.

Happens on Ubuntu 19.04 with Firefox v72.0.1.

**Comment by ssborbis** [comment]
Still happening? I see this occasionally when sideloading and testing. If you see any console errors, let me know. This is a nagging bug.

**Comment by ssborbis** [comment]
You can try emailing me your config. i tried with your old config and it works fine on my setup

**Comment by sojusnik** [comment]
Same here! Happens irregularly without console errors. Can't reproduce it either and will keep my eyes open.

**Comment by ssborbis** [comment]
I think this has been fixed with #241

**Comment by sojusnik** [comment]
It seems to work with the new version. Let's give it some time, if it won't work as expected, I'll comment here.
