### ISSUE TITLE
Some long history list entries can't  be deleted

### ISSUE THREAD

**Issue by Sagitee** [ssborbis/ContextSearch-web-ext#238]
Hi,

Sometimes, mostly accidentally, I make some searches for a selected long text e.g.
"arrière turque L’INFO EN CONTINU Journal du 8 février 2020 Asie: l'Iran propose une coalition régionale Iran: les GI's prennent la fuite La Résistance au cœur d'Israël Irak: Daech sauvera les USA? Pyongyang: Moscou prédit une surprise Syrie: la France, l'alliée secrète d'Israël? Hudaydah frappée: la riposte hybride? Congo Brazza: le méga chantage de Paris? Cisjordanie: la situation échappe au régime israélien Syrie: 1ère marche arrière turque La France défie Jupiter... Iran: contrôle téléguidé des drones US? BRICS: le coup fourré signe Paris? Plus d'articles"
which text is normally added in the history terms, but then it's impossible to delete those history entries from the list.

And a question: Which CS's file the current/actual settings and history terms are saved in?

Thank you.

**Comment by ssborbis** [comment]
I just tried your search and was able to delete the entry. Dunno what would be causing your issue. The delete methods are pretty straight-forward.

All search history is stored as an array in `userOptions.searchBarHistory`

Unless there's something weird going on when stringifying and parsing the userOptions, I can't imagine why you wouldn't be able to delete an entry.

**Comment by ssborbis** [comment]
I wonder if it's a character / character encoding issue and the searched string isn't matching up ( deleted newlines, tabs, etc making string1 !== string2 )

**Comment by ssborbis** [comment]
Finally got this figured out ( at least for the 1 entry I happen to have in my list that wouldn't delete ).

It seems to happen only on terms with multiple spaces in a row. I've been reading the innerText of the div to get the search terms, but extra spaces are automatically truncated making the suggestions search terms != the stored history terms.

**Comment by ssborbis** [comment]
I think this is fixed. I'll reopen if there are still issues.

**Comment by Sagitee** [comment]
Yes, it is fixed. Thanks a lot. Sorry for not being able to answer in time.
