### ISSUE TITLE
Settings for Quick Menu colours

### ISSUE THREAD

**Issue by DavidBE-UK** [ssborbis/ContextSearch-web-ext#239]
This is a great extension, but I'd just like to suggest that It would be good for people not up on css if there were specific settings for the colours in the Quick Menu so users can easily change them to match themes in Firefox (in my case, plus Chrome and the new Chromium Edge I also have this extension in) other than just dark and light.

I figured it could be done through the General>User Styles panel, although I don't know css syntax or the variable names, but after digging the quickmenu.css and dark.css out of the extension xpi and copying various likely looking bits into the General>User Styles panel and altering the colour hex numbers I've managed to get most of what I wanted, but am stuck on one small detail.

I've managed to change the background colour to match my toolbar with:

BODY {
	background-color:#025A6C;
}

and changed the folder tiles and their top right corners to something suitable. And I changed the tool icons to white - better on the dark-ish background colour - with the code from your dark.css modified slightly:

.tile[data-type="tool"] {
    filter:invert(1) brightness(100%);
	color:black;
}

The one problem is that I've left the tile borders at their default #e0e0e0 (might change it later), but the tool tile borders have gone dark, not matching all the other tiles  - presumably because the tool tile border colour is being inverted too, not just the icons. And I can't see how to get the white tool icons but with #e0e0e0 tool tile borders.

**Comment by ssborbis** [comment]
> presumably because the tool tile border colour is being inverted too, not just the icons

That's probably true. Did you post all the CSS you're using? I'll try it on my userstyles and see what's going on.

**Comment by ssborbis** [comment]
Yep, it's the invert + brightness(100%) that's causing the border to be white. A quick fix? is to set

```
.tile[data-type="tool"] {
filter:invert(1) brightness(100%);
color:black;
border-color:transparent;
}
```

You'll lose border colors altogether on tools, but it won't be as glaring as white borders.

You could also back off the brightness and try to find a value that would match the other borders 

Something like this is close
```
.tile[data-type="tool"] {
filter:invert(1) brightness(95%);
color:black;
border-color:#bbbbbb;
}
```

The problem stems from the inability to invert colors on background images without inverting the whole element. There may be some workarounds but getting them to play nice with the rest of the layouts might be tough.

**Comment by ssborbis** [comment]
I've added the root css variable `--tools-color` allowing more color options for the tools icons.

You can override this in the user styles css using

```
:root {
    --tools-color:red;
}
``` 

for example. Changes are in the repo for testing.

**Comment by ssborbis** [comment]
![colors](https://user-images.githubusercontent.com/24310997/78522693-dd9a5b80-7793-11ea-9cb0-9a206250c3d3.gif)

**Comment by ssborbis** [comment]
looks like it removes borders, but it's a start

**Comment by ssborbis** [comment]
I moved color handling to canvas vs css masks. Slower, but fixes border and hover issues. I had to tweak some of the svgs to work with canvas

**Comment by ssborbis** [comment]
v1.20+ includes the css color override

`:root {
    --tools-color:red;
}
`

add something similar to the cs custom user styles
