### ISSUE TITLE
Anyway to bypass Tokens?

### ISSUE THREAD

**Issue by bbley1** [ssborbis/ContextSearch-web-ext#240]
Some forum sites uses tokens.

 when i add site to contextsearch it generates something like this :
"
keyword={searchTerm}&_wvToken=4152287295,d2df8c64183g66efdbf5sabe883a1724
"
Token number changes everytime so it wont let me use contextsearch addon. (it gives error for using old tokens)

is there any way to bypass tokens? thanks in advance

**Comment by ssborbis** [comment]
No current way. I've run into this before also and haven't come up with a good, clean workaround. A lot depends on the site. Are you receiving the token as a session id after login or do all guests receive one? If it's guests, link me the forum and I'll take a look. It might be possible to append all the url params on the "landing" page to the search url. Most things are doable with enough coding and options, but it will take some effort to package it neatly.

**Comment by bbley1** [comment]
site requires registration/user login to make searches. and token changes everytime i refresh page. guess theres no easy way to bypass this then. thanks for the reply. i appreciate it.

**Comment by ssborbis** [comment]
I've added a new field to search engine settings (in the repo) that can execute code after opening a website. If your tokens show up somewhere, like in your url when you visit one of these pages your talking about, you can use some basic javascript to parse the token and add it to your search automatically.  Changes are in the repo and more discussion is in #248
