### ISSUE TITLE
QMtools is undefined

### ISSUE THREAD

**Issue by narcolepticinsomniac** [ssborbis/ContextSearch-web-ext#241]
Cent 4.2.7.116 (Official Build) (64-bit) (portable) (Chromium 80.0.3987.132)

In Chromium, when extensions are in the overflow menu (vertical ellipsis dropdown), when you click the icon, it'll slide out and the popup will open. When the CS icon is clicked, sometimes there's an error when it slides out and opens. Appears to only occur on the initial attempt after launching the browser. Subsequent execution seems fine.

![qm](https://user-images.githubusercontent.com/14100003/77129727-6f336a80-6a2b-11ea-945e-dbe722da2d9c.png)

**Comment by ssborbis** [comment]
The random toolbar menu failures are a known issue, but I've never seen a specific error with them using Chrome / FF. That menu is difficult to debug due to the fact it closes automatically when it loses focus, making an attempt to open a debugger window to inspect the code near-impossible. I'll see how QMtools is involved. I would be nice to squash this bug.

**Comment by ssborbis** [comment]
I'm gonna take a guess and say the script to build the menu is firing before the script containing QMtools. It may be as simple as re-arranging the loading order. If you can sideload, I've got an easy code mod to try.

**Comment by narcolepticinsomniac** [comment]
>That menu is difficult to debug due to the fact it closes automatically when it loses focus, making an attempt to open a debugger window to inspect the code near-impossible.

In Chromium, it's as simple as right-click to inspect. You could also open a separate instance for the background page simultaneously. In FF, it's a lot clunkier, but still way better than it used to be. 

[Demo](https://streamable.com/2x9rg)

**Comment by narcolepticinsomniac** [comment]
>If you can sideload, I've got an easy code mod to try.

Of course, I'll try it.

**Comment by ssborbis** [comment]
Try replacing searchbar.html with the copy in the zip. All I did was move the tools script before the menu script.

[searchbar.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/4357798/searchbar.zip)

**Comment by ssborbis** [comment]
> In Chromium, it's as simple as right-click to inspect. You could also open a separate instance for the background page simultaneously. In FF, it's a lot clunkier, but still way better than it used to be.

Ah, disable auto-hide. Nice. I'll see if that's an option in FF anywhere.

**Comment by narcolepticinsomniac** [comment]
That screen record was FF. =) Chrome stays open if inspected by default.

**Comment by ssborbis** [comment]
> That screen record was FF. =) Chrome stays open if inspected by default.

Damn. That could have saved me so much grief.  Anyway, i just found ui.popup.disable_autohide and life is good.

**Comment by narcolepticinsomniac** [comment]
>ui.popup.disable_autohide

I imagine the config is even more of a nuisance, but whatever works. 

As for the fix, LGTM so far.

**Comment by narcolepticinsomniac** [comment]
What's up with the grab cursor?

![grab](https://user-images.githubusercontent.com/14100003/77133257-d60b5080-6a38-11ea-9e9c-6aba6492556a.png)

**Comment by ssborbis** [comment]
Ah, that was meant for the floating sidebar menu. It's movable / dockable and the 2 menus share code / styles

**Comment by narcolepticinsomniac** [comment]
I'll let you know if I run into any issues with the popup, but I haven't been able to repro. I'd say it's probably good. Thanks!

**Comment by ssborbis** [comment]
Awesome. Thanks for posting that console error. Sometimes that's all it takes to pin down down the problem.
