### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Jackie-Blue** [ssborbis/ContextSearch-web-ext#243]
When I click on the CSE icon in the Chrome toolbar, the CSE search box with the search engines usually pops up, but not always. Sometimes a much smaller popup is displayed instead which has a magnifying glass and an options icon.

If I click the magnifying glass in the smaller popup, my previous searches are displayed.  From there I can select a previous search if I want.

The problem is I cannot find a way to control which of the 2 popups will come up.  Once in awhile I want to use the smaller popup, but can't get it to come up.  Sometimes when I don't want the small popup it comes up anyway, instead of the usual search box.

Is there a setting or some way to control which of these 2 popups comes up?

**Comment by ssborbis** [comment]
This sounds like the same bug addressed in #241 The popup should always be full-sized.

A fix is in the repo, but no new release yet. If you can, you could try sideloading and testing the repo code to see if that fixes the issue. Otherwise, wait for the next release. It shouldn't be long.

**Comment by Jackie-Blue** [comment]
How do you bring up the small menu when you want to use it instead of the full size menu?

Not familiar with sideloading, but if its easy I can give it a try.

**Comment by ssborbis** [comment]
> How do you bring up the small menu when you want to use it instead of the full size menu?

You can't, currently. I could add an option I suppose. 

So, normal behavior should be - you click the icon and a full menu opens with menu bar ( close, options), search bar, tools bar (optionally), and search engine icons.

You want to be able to open the menu in a smaller form by not displaying the search engine icons? What would your workflow be from there vs the larger menu? Using the history? Pressing {ENTER} and using your default search engine? I'm trying to understand the benefit a menu without search engine icons would be.

**Comment by Jackie-Blue** [comment]
If the user wants to use the small menu to access his previous searches he may have to click a lot of times before the small menu pops up.

Rather than removing the small menu from CSE maybe it would be better to just let users choose whether to bring up the large menu or the small menu, ie a right click option that includes a choice for the small menu; a left  click that always brings up only the large menu.

As it is now, the small menu comes up randomly. Apparently the user has no way to select which of the 2 menus will pop up.  

As far as I can see there is no way to access search history from the large menu; only the small menu gives access to search history.

The benefit of the small menu which doesn't have search engine icons might be best explained by whoever developed it that way.  Using the search history is the only benefit I know that the small menu offers.

**Comment by ssborbis** [comment]
Just a quick sanity check. You're saying you only can access the search history if the menu is glitching? ( small, no search engines). That's definitely not right. Here's a gif of proper behavior. The search history should be displayed in all menus ( toolbar, quick menu, sidebar menu ) when you click the magnifying glass. If you're not seeing it, and you do have the option enabled, it could be because of the bug in #241 .

![toolbar](https://user-images.githubusercontent.com/24310997/79328591-edc0e200-7edb-11ea-9973-ee544a7b5379.gif)

**Comment by ssborbis** [comment]
Ignore the green garbage in that gif. I don't think the image processed properly.

**Comment by ssborbis** [comment]
I pushed a release to AMO and Chromestore. Google has changed their privacy policy on submissions, so there will be a review process before the update shows. Might be a while. Once you get v1.20, see if the issues resolve.

**Comment by Jackie-Blue** [comment]
After reading your sanity check comment and seeing your graphic showing how to access history from the large menu I realized I could access history from the large menu. Before this I didn't know history could be accessed from the large menu.

Now that you've shown me a way to access history from the large menu, the small menu seems  redundant, less useful, without purpose. But it may have uses that I dont know about.

Is this history feature you explained in your sanity check comment documented at the Chrome webstore or anywhere ? There may be other features I haven't discovered.  Are there any instructions that list all the features and explain how to use everything? 

I'm tempted to suggest better documentation for CSE, better instructions, more explanation of its features, and how to use them.  But maybe instructions are already available and I just haven't been able to find them.

Just now I checked for the latest version of CSE at the Chrome Webstore, but it still shows version 1.19.2  What does AMO stand for ?

**Comment by ssborbis** [comment]
> Is this history feature you explained in your sanity check comment documented at the Chrome webstore or anywhere ? There may be other features I haven't discovered. Are there any instructions that list all the features and explain how to use everything?

Sometime, I'll have to actually document the features in this addon. When I have time to work on it, it's spent coding, not documentation.

> Just now I checked for the latest version of CSE at the Chrome Webstore, but it still shows version 1.19.2 What does AMO stand for ?

1.20 is still "Pending Review". Sometimes the system glitches and I have to resubmit to get it to go through.

AMO is the Mozilla Firefox version of ChromeStore.
