### ISSUE TITLE
Blue squares, when opening the quick menu

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#244]
As shown [here](https://mega.nz/file/HghRBI7L#rqCDmTVTA31orKNqtXe7-9mdmud6zgdwjDG_UaO-MAI), blue squares started to appear after updating to v1.20 when summoning the quick menu.

Happens with Firefox 75 on Ubuntu 19.10 with ContextSearch 1.20.

**Comment by ssborbis** [comment]
That's the resize handle. The cursor must be over it momentarily as the menu expands, causing it to show up. Does it remain there or does it move to the lower-right corner like it should?

You could disable animations in CS options -> General to see if that has any effect. It may just be a consequence of your menu positioning. I might have to add a delay in the handler.  Does that gif give an accurate representation of the menu speed on your pc? It seems a bit slow to me.

You can drag & drop images like that directly into your messages here FYI.

**Comment by ssborbis** [comment]
Fix in the repo. The resize widget is hidden for .5s while the menu settles.

**Comment by itge13** [comment]
Thank you so much for your great work ssborbis!!!

Have the same problem. Really annoying. This blue thing just pops up now for a short time, but if you make a movement, sometimes you resize by accident. Afterwards it moves like you suggested. Never seen this before though!

Disableing Animation doesnt change anything. Also with me it is faster than with OPs Gif.

75.0 (64-Bit) on Win 10 x64

**Comment by ssborbis** [comment]
@itge13 Can you try the code in the repo to see if it fixes your issue?

**Comment by itge13** [comment]
where do I need to add it?  To "Apply custom CSS styling to menus"? If yes it didnt do anything.

**Comment by ssborbis** [comment]
Nah, I mean install from the source code as a temporary add-on. Are you on FF or Chrome?

**Comment by itge13** [comment]
I dont know how. On FF.

**Comment by itge13** [comment]
I dont know how. On FF.

**Comment by ssborbis** [comment]
1. Open CS options and click the Export button to backup your CS config
2. Download this file and put it somewhere your can find it ( Desktop, etc ) 
[contextsearch_web-ext-1.20.1.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/4511596/contextsearch_web-ext-1.20.1.zip)
3. Type `about:debugging` into your URL bar and press Enter
4. Click "This Firefox" tab / button on the left
5. Click "Load Temporary Add-on" and browse / select the file you downloaded.

This will temporarily install the pre-release version of this addon, replacing the currently installed version until you close Firefox. DO NOT click the "Remove" button in about:debugging, as this will remove your CS config, but you should have a backup if you did step 1. Simply close Firefox and reopen to remove the temp addon. Refresh your tab or open a new one and test the changes. Let me know if it fixes the problem
I forget if there is an additional "Enable Debugging" button you need to press somewhere in there to get to steps 4 & 5.

**Comment by itge13** [comment]
Thanks so much :) It worked. There is still a square on the bottom right if you go there with the cursor, maybe you could add the option to fix resize, but only esthetic. 
![2020-04-22_111239](https://user-images.githubusercontent.com/39725549/79963932-4a973c00-848a-11ea-93cb-b39695e769dd.png)

**Comment by ssborbis** [comment]
new release v1.20.1 going up now

**Comment by ssborbis** [comment]
@itge13 

The dashed blue border is by design. If you don't like it, add
`
.CS_resizeWidget {
    visibility:hidden;
}
`

to your custom styles in CS options -> General

**Comment by ssborbis** [comment]
@itge13 

actually, the better style would be

```
.CS_resizeWidget { 
    border-color:transparent !important; 
}
```

then you can still resize
