### ISSUE TITLE
Please add the option of remembering the opened subfolders

### ISSUE THREAD

**Issue by molkes** [ssborbis/ContextSearch-web-ext#247]
Please add the option of remembering the opened subfolders, allowing to apply the options to Toolbar, Quick Menu and Sidebar. This is to avoid selecting search engines from the first level every time.

**Comment by ssborbis** [comment]
I pushed a change to the repo for testing. The last opened folder is remembered for the session. Try it out.

**Comment by molkes** [comment]
It's working fine. Thanks.

**Comment by ssborbis** [comment]
hidden option in latest push

in console from CS options `userOptions.rememberLastOpenedFolder = true; saveOptions();`

**Comment by molkes** [comment]
I don't understand how to enable the option. Modifying on DevTools has no effect.

![](https://user-images.githubusercontent.com/62471162/81025710-18360780-8eaa-11ea-8506-6e2a5302d2ca.png)

**Comment by ssborbis** [comment]
You enter it into the console ( the console tab near the bottom ) but no worries. The latest push has the new options in CS Options -> Advanced

![Untitled](https://user-images.githubusercontent.com/24310997/81026741-b8574680-8e40-11ea-9f23-67600e5dcbda.png)

**Comment by molkes** [comment]
Thanks. You may already know, but I still want to say: After enabling the option, it will not be displayed as enabled. It cannot be closed after being enabled.

**Comment by ssborbis** [comment]
> Thanks. You may already know, but I still want to say: After enabling the option, it will not be displayed as enabled. It cannot be closed after being enabled.

Whoops, forgot to add the new options into the load function. Fix in the latest push.

**Comment by molkes** [comment]
The problem still exists.

**Comment by ssborbis** [comment]
Yep, i was just about to post. There's a bug in the options menu somewhere. I'll post here when I push a fix.

**Comment by ssborbis** [comment]
try the latest

**Comment by molkes** [comment]
It's working normally.

**Comment by molkes** [comment]
The issues corresponding to the options:

- rememberLastOpenedFolder #247
- groupFolderRowBreaks #250
- autoCopyOnSearch #248
