### ISSUE TITLE
Automatically copy keyword

### ISSUE THREAD

**Issue by molkes** [ssborbis/ContextSearch-web-ext#248]
For search engines without the parameter `{searchTerms}`, after clicking the icon, please copy the keyword automatically before opening the search engine.

In addition, why is it not allowed to delete the Description when adding the search engine on INPUT elements? Is this a bug?

**Comment by ssborbis** [comment]
> For search engines without the parameter {searchTerms}, after clicking the icon, please copy the keyword automatically before opening the search engine.

I assume you mean copy to clipboard? It would have to be an opt-in option. Out of curiosity, what are you doing that doesn't open a search engine directly to a query using search terms?

> In addition, why is it not allowed to delete the Description when adding the search engine on INPUT elements? Is this a bug?

It's really only required for OpenSearch engines (Firefox One-Click Search Engines). A blank description will fail to install the search engine. I could probably fill in a junk description instead of failing.

**Comment by molkes** [comment]
Because some websites cannot be added as search engines:

- Sites that are not suitable for giving you feedback: sites that contain NSFW content or require registration.
- Identify linked websites, such as video downloads and web disk downloads.
- Translation websites, such as [Bing Microsoft Translator](https://www.bing.com/translator/).
- Websites that request verification codes every time they open.

## Video download sites

You can try the following video download sites, especially `https://www.jijidown.com/`, which will open the results in a new tab.

### For Youtube

Test link: https://www.youtube.com/watch?v=aqz-KE-bpKQ

Website:

https://www.urlgot.com/
https://www.clipconverter.cc/
https://youtube.iiilab.com/

### For bilibili

Test link: https://www.bilibili.com/video/av2271112

Website:

https://www.jijidown.com/
https://www.biliplus.com/
https://v.urlgot.cn/

**Comment by ssborbis** [comment]
Hmm... I see what you mean. I *should* be able to copy to clipboard ( it's a sloppy workaround, but still viable for now ) but I may be able to do you one better. I'll have to see what's possible with the API, but I might be able to add a field to each search engine that allows for generic javascript code eval() within the search landing page.  With the proper CSS / DOM selectors and event dispatching, it would be possible to automate a search on one of those javascript-driven search bars.

**Comment by ssborbis** [comment]
hidden option in latest push

in console from CS options `userOptions.autoCopyOnSearch= true; saveOptions();`

**Comment by ssborbis** [comment]
There's a new field in the search engines manager `Search Code`

javascript entered here will execute after the page loads. You can automate some search tasks that way.

For instance:

* Template: https://www.clipconverter.cc/2/
* Search Code: 
```
document.querySelector('#mediaurl').value = searchTerms;
document.querySelector('#submiturl').click();
```

... will fill in the search bar and take you to the next step. With a little more JS, you could automate the whole thing. I'm guessing the same principles can be applied to most of those javascript-driven forms.

The search engine manager layout needs work, so if you expand the Search Code TEXTAREA, you might hide the Save / Cancel buttons. Just a heads-up.

**Comment by molkes** [comment]
`Search Regex` and `Search Code` use multi-line text boxes without affecting the save button.

I found that the save button of the folder was blocked.

Thanks, I now know how to fill in `Search Code`.

**Comment by molkes** [comment]
I don't know how to fill in the "Search Code" of these sites:

https://youtube.iiilab.com/
https://www.jijidown.com/
https://www.biliplus.com/

**Comment by ssborbis** [comment]
https://www.biliplus.com/ adds fine for me through this addon

Do you know how to use CSS selectors?

For those 3, and probably a lot of other sites, you can simply select the first INPUT element on the page and assume it's probably the search bar.

```
document.querySelector('input').value = searchTerms;
```

Then find the selector for the Submit button and .click() it

**Comment by molkes** [comment]
I don't understand the code.

For https://www.biliplus.com/ , I did not find the ID of the Submit button. 

![image](https://user-images.githubusercontent.com/62471162/81131353-77188100-8f7d-11ea-9097-c797f77b305f.png)


"Search Code" I wrote:

```
document.querySelector('#inputbar').value = searchTerms;
document.querySelector('#inputbutton').click();
```

For https://www.jijidown.com/, it does not have a submit button, you need to use the Enter key to submit. I don't know how to simulate input keys.

![image](https://user-images.githubusercontent.com/62471162/81131668-78967900-8f7e-11ea-83b7-df3f99a61567.png)

"Search Code" I wrote:

```
document.querySelector('#go').value = searchTerms;
document.querySelector('#go').click();
```

**Comment by ssborbis** [comment]
https://www.biliplus.com/ should add through this addon. Are you doing something other than a normal search?

Template: `https://www.biliplus.com/api/do.php?source=bilibili&act=search&o=default&n=20&p=1&word={searchTerms}`

As for https://www.jijidown.com/, you can simulate the Enter key with:

`document.querySelector('input').dispatchEvent(new KeyboardEvent('keydown', {key: "Enter", keyCode:13} ))`

That site checks the `keyCode`, but I'll leave the `key` there for reference

**Comment by molkes** [comment]
https://www.jijidown.com/ Success, thank you.

https://www.biliplus.com/ Yes, I want to enter the video link. It allows input of video links and keywords. Test link: https://www.bilibili.com/video/av2271112

https://youtube.iiilab.com/ It doesn't use the parameter ID, I don't know how to input and submit. Test link: https://www.youtube.com/watch?v=aqz-KE-bpKQ

**Comment by ssborbis** [comment]
For https://youtube.iiilab.com/ try

```
document.querySelector('input').value = searchTerms;
document.querySelector('input + div > button').click();
```

**Comment by ssborbis** [comment]
I don't understand what you're trying to do with https://www.biliplus.com/

**Comment by molkes** [comment]
If you use `https://www.biliplus.com/api/do.php?source=bilibili&act=search&o=default&n=20&p=1&word={searchTerms}`, then `{searchTerms}` cannot be a video link, only keywords.

I want to enter a video link to get a parsed link. Enter `https://www.bilibili.com/video/av2271112/` and get `https://www.biliplus.com/video/av2271112/`. I don’t want to use the link replacement method, because then I need to add another search engine.

I recorded a GIF picture.

![](https://user-images.githubusercontent.com/62471162/81135459-dc26a380-8f8a-11ea-83a2-4ddcd761a63b.gif)

**Comment by molkes** [comment]
> For https://youtube.iiilab.com/ try
> 
> ```
> document.querySelector('input').value = searchTerms;
> document.querySelector('input + div > button').click();
> ```

Effect: Submit directly without entering a link.

**Comment by ssborbis** [comment]
Ok, so for https://www.biliplus.com use the same Search Code method and dispatch a keypress

```
document.querySelector('input').value = searchTerms;
document.querySelector('input').dispatchEvent(new KeyboardEvent('keydown', {keyCode:13}))
```

That should be all you need

**Comment by ssborbis** [comment]
Make sure you're template for https://www.biliplus.com is `https://www.biliplus.com` if you're just using the js method

**Comment by ssborbis** [comment]
https://youtube.iiilab.com/ uses some javascript events to set up the search

![Untitled](https://user-images.githubusercontent.com/24310997/81140191-1dd53100-8f2e-11ea-9291-9f2cdbf8ca08.png)

You have to account for these in some search engines. In this case, the search won't function until it sees an "input" event `Event("input")`.
```
let input = document.querySelector('input');
input.focus();
input.value = searchTerms;
input.dispatchEvent(new Event('input'));
document.querySelector('input + div > button').click();
```

**Comment by molkes** [comment]
All solved, thank you.
