### ISSUE TITLE
Use clipboard content to search

### ISSUE THREAD

**Issue by molkes** [ssborbis/ContextSearch-web-ext#249]
Please add two options:

- If the Search Bar is empty, use the content of the clipboard to search.
- When you open Toolbar and Sidebar, fill Search Bar with the content of the clipboard.

**Comment by ssborbis** [comment]
new advanced option `autoPasteFromClipboard`

**Comment by molkes** [comment]
I thought it would be troublesome to paste keywords on the Yandex browser for Android, so I wanted to use the clipboard content search directly. Now I think there is no need to add such a function.

**Comment by ssborbis** [comment]
Well if you ever need it, it's there now
