### ISSUE TITLE
Error: nativeApp(...).then is not a function

### ISSUE THREAD

**Issue by Zlewness** [ssborbis/ContextSearch-web-ext#25]
What is this error I see in the toolbox? Why does it trigger when I hover over browser elements?

**Comment by ssborbis** [comment]
Looks like it's from moving some of the nativeApp code into a Promise and returning a boolean false when using the 'lite' version with the nativeapp disabled. The nativeApp function is called on new tab and window focus events and always returns false in the 'lite' version. Is that what you're seeing? I'll add a check for type before running the then() function in the next release. That should take care of the error. Are you seeing any broken functionality or just the console error?

**Comment by Zlewness** [comment]
Just the console error, was wondering what it is.
