### ISSUE TITLE
Folder left aligned

### ISSUE THREAD

**Issue by molkes** [ssborbis/ContextSearch-web-ext#250]
In CS options > Search Engines, please add the left alignment option to the folder option "note: top-tier folders only".

The effect is as shown below, blue is the search engine, and the group color of the folder uses light yellow or yellow.

![](https://user-images.githubusercontent.com/62471162/80858004-0590b800-8c89-11ea-8244-0adcb0b76791.png)

**Comment by ssborbis** [comment]
hidden option in latest push

in console from CS options `userOptions.groupRowBreaks= true; saveOptions();`
