### ISSUE TITLE
Please add link replacement function

### ISSUE THREAD

**Issue by molkes** [ssborbis/ContextSearch-web-ext#251]
Please add a link replacement function. Because the link of the result page of some video download sites contains the ID of the original video link, this function can at least quickly open the video download page.

The way to achieve this may be to add a "Keyword replacement" column to the search engine. Please consider how to design better.

## Example

The keyword is `https://www.youtube.com/watch?v=aqz-KE-bpKQ`, click on the search engine `EachNow.com` will open `https://eachnow.com/watch?v=aqz-KE-bpKQ`.

Search engine `EachNow.com`:

- Name: EachNow.com
- Template: https://eachnow.com/{searchTerms}
- Keyword replacement: https://www.youtube.com/{searchTerms}

**Comment by ssborbis** [comment]
* Template https://eachnow.com/watch?v={searchTerms}
* Search Regex `".*v=(.*)","$1"`
