### ISSUE TITLE
Help with URL's converting 'slash' to %2F when highlighting text to search

### ISSUE THREAD

**Issue by peejaygee** [ssborbis/ContextSearch-web-ext#254]
I don't know if this is an issue, or an 'operator error' i.e. me!

Your extension is the closest thing I've found to a solution from a problem I have.

I have a website, I'm an affiliate with [I'm not going to provide real urls and real affiliate links, as I'm not trying to sell either]

So, their website doesn't allow/have pre-generated links yet, so I went on the hunt to be able to find a addon that I could highlight the url and pop in a new window with my affiliate link at the end.

I tried adding [pretend URL and affiliate link]

https://www.theirurlwouldbehere.com/en/{searchTerms}?ref=myaffiliatelinkwouldbehere

but when it opens up, it replaces all the / [slashes] into %2F which breaks the new tab results.

I've tried all the encoding choices, and I can't seem to stop it doing that? am I just setting the whole thing up wrong, or is there a known work around for the problem I'm facing?

Thanks for your time.
Regards
PJ

**Comment by ssborbis** [comment]
Hmm, I'm not seeing that behavior.

I added a search engine for testing with the following fields:

Template: `https://www.example.com/en/{searchTerms}?ref=http://testing.com/blah`
Form path: `https://www.example.com`

When I search using that engine for the word 'problem', I'm directed to the url `https://www.example.com/en/problem?ref=http://testing.com/blah`. I can't tell without more info if it's this addon or the server that's re-encoding the slash. What happens when you use the template I provided? Does your browser visit the proper url or convert the slashes?

**Comment by ssborbis** [comment]
Wait, is it the content of {searchTerms} that's being encoded? If so, you need to use the regex field.

(edit in a sec)

**Comment by ssborbis** [comment]
Actually, I may just add a None or Raw encoding option. That will skip the encodeURIComponent on the searchTerms.

**Comment by ssborbis** [comment]
update to the repo adds the encoding option `none / raw'

If you can sideload, try it out and see if it fixes your issue.

**Comment by peejaygee** [comment]
Thanks for coming back to me, yeah, it's the {searchTerms} that was encoding, as I'm not able to (as I wouldn't know were to start) sideload the update into my browser I'm hoping until the update/push goes out you can explain the RegEx.

So, you say about the Search Regex section. I tried something like "%2F","\\" and that didn't help me. [researched Google on Regular Expressions]

So can you help me with the workaround until the addon gets updated via official ways. What should I put in the RegEx to stop the %2F appearing?

Thanks for your time.
Regards
PJ

**Comment by ssborbis** [comment]
You can change the encoding of your search engine in the console to a phony encoding and the result would be the same as the added none / raw setting. I don't think it will cause any other issues, but i can't say for sure.

1. Open CS options
2. Open your js console ( CTRL+K for Firefox )
3. enter `userOptions.searchEngines.find(se => se.title === "YourEngineName").queryCharset = "none";saveOptions();` change YourEngineName to whatever you named that search engine.

That *should* do it. Try it out and let me know.

**Comment by ssborbis** [comment]
There's a new release for FF out. Just set your encoding to `no encoding` in the search engines manager

**Comment by peejaygee** [comment]
>     3\. userOptions.searchEngines.find(se => se.title === "YourEngineName").queryCharset = "none";saveOptions();

Seemed to help for me, the same link I tried worked with the tweak.

The browser I use this on (and the tweak) was Waterfox, which is not as up to date as FF (html5 web dev, I have multiple browsers install for testing) so it doesn't have the 'no encoding' in the search engine manager yet. [I do use FF, but for other reasons]

Thanks for your time and guidance.

**Comment by ssborbis** [comment]
No prob
