### ISSUE TITLE
Icon don`t show when backup file delete icon_base64String

### ISSUE THREAD

**Issue by polyproline** [ssborbis/ContextSearch-web-ext#256]
I think icon_base64String is too large for backup file.So I only settled icon_url and deleted icon_base64String.But It`s only work in setting html when I do that.
I want to only save icon_url or icon_base64String.They both can work well.
Thanks for all your hard work

**Comment by ssborbis** [comment]
How big is your backup file? 

Are you running into the storage limit or do you just want a smaller backup?

I believe there is a limit to the storage (5mb?) webextensions can use without requesting the unlimitedStorage permission.

**Comment by ssborbis** [comment]
The latest push has a fallback to read icon_url if there is no icon_base64String

**Comment by polyproline** [comment]
Sorry, I don`t have time in those days.
Yes, I want to have a smaller and readable backup file.
Only  download and cache the icon data When loading backup file.
Backup base64 data or URL can be alternative.
That I wants.

Thank you for you response

**Comment by ssborbis** [comment]
I'm adding and advanced option to export the config file without some base64 encoded icons ( icon_base64String and the icons for One Click Search Engines) which get re-encoded on import. Look for it in the next release.
