### ISSUE TITLE
Performance Impact

### ISSUE THREAD

**Issue by bbley1** [ssborbis/ContextSearch-web-ext#257]
EDGE Chromium
Win10x64

So ive made a benchmark test after ive noticed some slowdowns on my browser recently.

I used Speedometer 2.0 https://browserbench.org/Speedometer2.0/

With no addons installed  : 57.5 score
With my 29 addons installed (This includes context image-search addons - adblock plus and ublock origin (with 100k+ filters) - imagus - userscripts thats loaded in every page like picviewer ce+ - maximize video - adsbypassers - imagemaxurl etc..

Anyway. score with all 29 addons installed : 42.33 (which is about 15 score impact for 29 addons)

when i enabled contextsearch-web-ext 1.21.1 : score lowers to 29.80 (this extension alone makes about the same performance impact of all the other 29 addons combined)

i tried to disable (right-click) context menu stuff - quickmenu etc. (i only use this extension to make searches from toolbar) but it didnt help with the performance.

it'd be good if you look up for this issue. maybe add an option so the extension wont touch webpages and will only work in the toolbar? sorry for my bad english and thanks for reading

**Comment by ssborbis** [comment]
Speedometer 2.0 tests are misleading with this addon.

That test loads an IFRAME multiple times to calculate page loads / min.

Unlike other addons, this one watches for multiple user gestures, including inside IFRAMES which requires code injection into each IFRAME.

As a result, this addon will be injected into each Speedometer 2.0 IFRAME load, unlike most other addons, slowing down the test. It's not a practical comparison between addons.

I could inject the UI code only when that option is selected, and it would definitely score better in Speedometer 2.0, but the real-world performance gains would be negligible, only really showing up in a test like that.

It's really not as bad as it looks using that test, but I'll look into trimming some fat.

**Comment by ssborbis** [comment]
You can try the latest push. Disabling the option `Enable searching via popup menu` will disable the quickmenu code injection and significantly increase the Speedometer 2.0 test.

**Comment by bbley1** [comment]
Thanks for the quick update. Ive tested it and can confirm its fixed the speedometer. Also its good to know there is no performance impact in general usage. Thanks again.
