### ISSUE TITLE
Import of search engines from Firefox to Vivaldi (Chrome)

### ISSUE THREAD

**Issue by Pachuquero** [ssborbis/ContextSearch-web-ext#259]
This extension is a great time saver!

A minor issue I have after importing configuration file from Firefox version of Context Search is what appears to be some Firefox defined engines. These are marked FF and the right-click Delete option is unavailable for those (see attachment) and they cannot be edited either.

![ContextSearch_Options_-_Vivaldi-300x243](https://user-images.githubusercontent.com/5184994/83335088-8bdbf200-a267-11ea-8b2e-41a71c1ba690.png)

Though I cannot delete them I can hide them. Since I have 18 engines defined I haven't bothered to redo them from scratch. I suppose the only way to get rid of them would be to edit the export JSON file, which look rather complex?

Many thanks for this wonderful extension.

Cheers!

**Comment by ssborbis** [comment]
I'm adding a browser check and unhiding the delete option for non-FF browsers.

That, and maybe I should hide OCSE by default  on non-FF browsers.

**Comment by ssborbis** [comment]
K, both changes added to the repo if you're sideloading ( importing hides OCSE on non-FF browsers and Delete menu enabled )
