### ISSUE TITLE
Wrong Highlight colour

### ISSUE THREAD

**Issue by alexolog** [ssborbis/ContextSearch-web-ext#260]
The 4th highlight is configured as black on yellow, but it displays as white on yellow, making the highlighted term unreadable.

**Comment by ssborbis** [comment]
Got it. Looks like all 4 text colors are actually displaying as the first text color. Fix will be in the repo shortly.

Thanks.

**Comment by alexolog** [comment]
Thanks!

When will the fixed extension be available?

**Comment by ssborbis** [comment]
It will be a while. I'm busy and I'll need to check a lot of the changes in the repo before making a release. 

In the meantime, you can add this css to CS Options -> General -> User Styles to fix the color. It may mess with the active highlight text color but it's the best I can do for now.

```
.CS_mark[data-style="3"], #CS_highLightNavBar > DIV[data-style="3"] { 
    color:black !important;
}
```

**Comment by ssborbis** [comment]
You could also change the background color from yellow to something else that works better with white lettering. Click the yellow box and select a new color ( if you didn't know it could be changed )

**Comment by ssborbis** [comment]
v1.23 on AMO
