### ISSUE TITLE
Cannot configure the hold time

### ISSUE THREAD

**Issue by alexolog** [ssborbis/ContextSearch-web-ext#261]
The "hold" timeout is too short, often triggering a search when I want the context menu.

I tried adjusting quickMenuAutoTimeout in the advanced settings, but it doesn't seem to affect it.

This is very annoying.

**Comment by ssborbis** [comment]
Doesn't look like I ever made that configurable. 

Added `quickMenuHoldTimeout` to the advanced menu. Changes in the repo.

**Comment by alexolog** [comment]
Thanks!

Can you please push it to AMO?

**Comment by ssborbis** [comment]
I'll try to get something out tomorrow. I have a lot of changes since the last release to double-check.
