### ISSUE TITLE
feature request: fast access to last used search website

### ISSUE THREAD

**Issue by rezad1393** [ssborbis/ContextSearch-web-ext#262]
can we have an option that when enabled it would make it that opening search menu selects the last used search as its default so that I don't have to go through my submenus and select that last one?

for example say I want to use google translate for translation that I need today so every word I select I have to travel this addon submenu to get the translate search option.

but then the next day I have the same situation but this time for searching movies on imdb.
now I want to quickly search the words in imdb and have it work as the last time so that the same imdb search be used quickly.

is this possible? 
maybe another entry at top of this addon that is just the last used search.

thanks for the great addon.

**Comment by ssborbis** [comment]
What menu are you using primarily? If it's any of the tiled menus, you can enable the Tools Bar under CS Options -> Quick Menu and enable the 'Last used search engine' tool.

![tools](https://user-images.githubusercontent.com/24310997/85917101-0a9f5d00-b81d-11ea-83b1-f237fe879d38.png)

The only thing I can think to add is an option to use the Last used search engine when pressing Enter from the search bar. Pressing Enter defaults to the first search engine in the list, not that last used.

**Comment by rezad1393** [comment]
I dont use toolbar icon.
I meant menu in the right click menu.
or maybe something equivalent to that ,which would search the selected word in the last used search engine.

like maybe a shortcut, which would be better than both toolbar way and right click way.

for example when I press ctrl-some-key-not-used-by-others then a search on the highlighted text with the last used search engine is performed.
this would make it fastest way to do this.

**Comment by ssborbis** [comment]
Gotcha. I'll add an option to put the last used search engine at the top of the context menu.

I know you said you don't use the quick menu, but if you enabled it but unchecked the opening methods so it never actually opens, you can set the hotkey behavior ( new tab, background tab, etc ) in CS -> Quick Menu and enable the setting `allowHotkeysWithoutMenu` in the Advanced menu. Then, if you set hotkeys for some search engines ( G for google for instance ), you can select a word on the page and press G to perform a search. Hotkeys for search engines are set with the small bubble at the far right of each row in CS Options -> Search Engines.

If you need help setting it up, let me know. I started using that method after adding the `allowhotkeysWithoutMenu` option. It's nice.

**Comment by rezad1393** [comment]
I have no idea what quickmenu is and how it works.
I selected "Enable searching via popup menu"
I am on linux does that apply to the warning at top? I have set that too.
but I dont know what I need to do to just use the shortcut I have set for the test search engine (the g key)

if this doesnt pan out or if it messes with other shortcuts in firefox or system the first option (last used on top) would be great.

**Comment by ssborbis** [comment]
> I am on linux does that apply to the warning at top? I have set that too.

Nah, it should work on all platforms without any additional prefs settings.

Ok, I'll list the steps needed to use hotkeys without any menus

1. Open CS Options -> Quick Menu
2. Enable searching via popup menu ( top-most option )
3. Set Hotkey behavior under Search Actions ( Open In Background Tab for instance )
4. Click CS Options -> Search Engines tab
5. Choose a search engine and click the bubble on the far right and press a key ( g for instance )
6. Click CS Options -> Advanced tab
7.Enable allowHotkeysWithoutMenu

If you open a new tab, or reload a current tab, you should be able to select text and press G to search

**Comment by rezad1393** [comment]
thank you.
this works.
btw can this be enable disabled by an option that is maybe shown on addon icon in toolbar? so that it is not always on as so not mess with regular web browsing.
if not still no problem, this is great as it is.

**Comment by ssborbis** [comment]
Currently, there's no button. But you can add a bookmarklet with this code

```
javascript:(async () => {
	userOptions.allowHotkeysWithoutMenu = !userOptions.allowHotkeysWithoutMenu;
	browser.runtime.sendMessage({action: "updateUserOptions"});
	browser.runtime.sendMessage({action: "showNotification", msg: "hotkeys are " + (userOptions.allowHotkeysWithoutMenu ? "on" : "off")});
})();
```

1. create a new bookmark from Bookmarks -> Right Click -> New Bookmark
2. Name it `Toggle Hotkeys` or whatever and paste the code above as the location.
3. Open CS Options -> Search Engines
4. Right-click somewhere in the search engines table to bring up the custom context menu and choose Add Bookmarklet, then choose `Toggle Hotkeys` from the submenu.

You now have a toggle button for using hotkeys in you menus!

**Comment by rezad1393** [comment]
thanks for including it in new update

**Comment by ssborbis** [comment]
FYI, I added a hotkey toggle to the tools menu. In the repo for the next release.

![Untitled](https://user-images.githubusercontent.com/24310997/88245689-b2ae1780-cc5d-11ea-9631-8cf2811e680f.png)

**Comment by rezad1393** [comment]
thanks.
btw can I become somewhat greedy and ask for two recent search engine instead of one on top of menu?
now that I use it one is good but not great.
but if that adds to much complexity to addon then I can live with one two.
and again thanks for the addition.

**Comment by ssborbis** [comment]
I'll look into a Recent list and users can set the number

**Comment by rezad1393** [comment]
> I'll look into a Recent list and users can set the number

You are a champ.

**Comment by ssborbis** [comment]
Latest push has an option to show recently used engines in a folder

![Untitled](https://user-images.githubusercontent.com/24310997/88363421-9edde080-cd45-11ea-9911-61ce26f1ad75.png)

**Comment by rezad1393** [comment]
can you increase the number of recent entries (as you suggested two posts higher) instead?
the main issue is that I would have to open the second folder and that would make it a lot like the old behavior with no recent entry and would not be that time saving.
or maybe both?

**Comment by ssborbis** [comment]
latest push merges the lastUsed and RecentlyUsedList into one setting. You can set it to display as a folder or a list at the top of the menu and set the number of engines to display.

**Comment by rezad1393** [comment]
I got confused by you last post.
thanks for clearance.
