### ISSUE TITLE
Paste icon instead of copy

### ISSUE THREAD

**Issue by githubeing** [ssborbis/ContextSearch-web-ext#264]
![Screenshot from 2020-07-21 14-34-04](https://user-images.githubusercontent.com/29702626/88050330-48af4880-cb5f-11ea-9176-bb2f341a8755.png)
this icon with clipboard is usually used as a paste icon, not copy.
jetbrains ide: ![Screenshot from 2020-07-21 14-35-14](https://user-images.githubusercontent.com/29702626/88050409-709eac00-cb5f-11ea-950d-d4a1afb6e6b8.png)
libreoffice: ![Screenshot from 2020-07-21 14-36-13](https://user-images.githubusercontent.com/29702626/88050448-8d3ae400-cb5f-11ea-8c3c-686e7ad4456f.png)
gnome files nautilus: ![Screenshot from 2020-07-21 14-36-57](https://user-images.githubusercontent.com/29702626/88050510-a8a5ef00-cb5f-11ea-90a3-cc57bed0d7d6.png)
could you please change it to copy icon? - it confuses a little :)

**Comment by ssborbis** [comment]
Sure. I think it used to be the copy.png icon, which is still included in the addon. It may have been swapped several revisions ago when I was redoing icons.

**Comment by githubeing** [comment]
exactly 👍
![copy](https://user-images.githubusercontent.com/29702626/88222036-04f73480-cc6e-11ea-8fad-498ff67772b8.png)(chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/icons/copy.png)

**Comment by ssborbis** [comment]
update in the repo

**Comment by ssborbis** [comment]
fixed in v1.25
