### ISSUE TITLE
Weird duplicate search engine in context menu

### ISSUE THREAD

**Issue by vzjrz** [ssborbis/ContextSearch-web-ext#265]
![2020-07-22 13_55_04-Greenshot_proc](https://user-images.githubusercontent.com/930620/88218667-f71dc100-cc25-11ea-9ece-b798bdc64038.jpg)

Is there any way to disable this? It's messing with my hotkeys.

**Comment by ssborbis** [comment]
It's the last engine you used. The icon on the right is supposed to be a type of back-arrow. Must not be in your default font list.

I'll add the option to disable it.

Don't know if you know this, but there's an option in CS Options -> Advanced named `allowHotkeysWithoutMenu` that lets you select text and press the key set as the engine's hotkey in CS Options -> Search Engines -> [engine] -> Hotkey (bubble to the far-right of the engine title) without having to open a menu.

**Comment by ssborbis** [comment]
update in the repo if you're sideloading

**Comment by ssborbis** [comment]
Latest release v1.25 has some options under the Context menu section for handling the recently used engines list

**Comment by rediffusion** [comment]
@ssborbis 

> CS Options -> Advanced named allowHotkeysWithoutMenu

Context Search 1.41.1
Unfortunately, it doesn’t work!

**Comment by ssborbis** [comment]
@rediffusion 

Did you set a hotkey action under CS Options -> Shortcuts -> Hotkeys -> Search Action ?
