### ISSUE TITLE
No way to add DuckDuckGo to one-click search in Firefox 78+?

### ISSUE THREAD

**Issue by redactedscribe** [ssborbis/ContextSearch-web-ext#266]
I'm struggling to add DuckDuckGo to the Firefox one-click search engines.

I realize Firefox ships with a DDG engine, but it submits GET requests when I'd like POST. The previous version of this extension was able to add ContextSearch's POST DDG search engine to Firefox, but as far as I understand, the only way to add an engine now is via Firefox's search bar. The problem is, DDG doesn't show "Add Search Engine" in the Firefox search bar drop-down menu.

From a little reading, is this because DDG doesn't supply `<link rel="search" ...` code, or is something else up? What can be done for sites that do not include any code for Firefox to install a new search engine? Are we out of luck in that scenario?

There didn't seem to be any DDG search engine extensions that submit via POST either.

Thanks.

**Comment by ssborbis** [comment]
Mozilla dropped support for the old way to programmatically install OpenSearch engines, so things have changed a bit in FF78+.

The way it used to work: Right-click on a searchbar, select Add to Context Search -> Add -> ( Also Add to Firefox? ) -> Done

The way it works now:  Right-click on a searchbar, select Add to Context Search -> Add -> ( Also Add to Firefox? ) -> A new "Add ..." OpenSearch engine *should* appear in the Firefox search bar -> Add -> Done

I just checked, and I don't have any issues with adding DuckDuckGo, but the default method is a GET request vs POST. 

If you know what the POST template should be, you can open CS Options -> Search Engines -> DuckDuckGo (after installed to CS obviously), edit the engine / form to the appropriate POST settings and click the green circle with a plus icon. This generates an OpenSearch engine that can be installed to the Firefox search bar using the current settings for the engine (POST). After a few seconds, an OpenSearch engine should be available to add within the Firefox search bar. Add that and you have a POST version of DuckDuckGo.

Be aware you'll need to delete any old DDG engines from Firefox Options -> Search that share the same name before you can install a new one. Until you're sure it works, you might change the engine name within CS a bit so you can install the POST engine to FF search bar along with the current engine.

It's possible DDG no long supports a POST request when searching and this is all moot, but if they do, the right POST params can probably be found at mycroftproject.com.

**Comment by ssborbis** [comment]
This template worked for me

![Untitled](https://user-images.githubusercontent.com/24310997/88235623-dd3da780-cc40-11ea-9b83-9dc66e6e3fea.png)

**Comment by redactedscribe** [comment]
Thanks for the help, but something's not right.

Once I read your response and understood the process, I gave it a try, and it worked the first time. Because this was just a test, I removed it to add again with a better name. Maybe the process should be explained somewhere (sorry if I missed it), because the new image in the top-right that pops up showing Firefox's search bar isn't explanatory enough I found. The thing I didn't understand previously is that (supposedly) the extension generates a search engine to add, so the website doesn't need to natively support adding an OpenSearch engine, but it becomes an available option after running the wizard, which only has happened once for me so far.

Since then, I don't know why it's to hard to get this to work for DuckDuckGo (haven't tested other sites): I make sure I do not have the engine installed in Firefox or the extension, I visit DDG, make a search (probably unnecessary), right-click the search field and choose to add it to CS, then still via the wizard, I choose to add it to Firefox's One-Click search engines, a new tab opens that's got a warm gradient with the same image in the top-right. Why this new tab appears, I'm not sure. I've clicked the do-not-show-again message for the image, so what purpose is there to this blank tab with nothing other than a gradient? I then close it as I don't see a search engine appearing, now back on the DDG tab, no search engine in the search bar either, and the wizard asks was the search engine added correctly.

I fail to understand what I'm doing wrong. Also, in the CS options, clicking the green plus button does nothing after adding a DDG entry, and with no popup any more as I've hidden it, there's no sign of anything happening (if there even is). Seems to do nothing at all.

Sorry for the trouble, but hopefully you can spot an error.

Thanks.

**Comment by redactedscribe** [comment]
Oh, I just tried again naming it anything other than DuckDuckGo, and it works fine.

I guess Firefox isn't happy adding another "DuckDuckGo" even though it doesn't exist in CS or the list of One-Clicks. Is there some limitation here?

**Comment by ssborbis** [comment]
I was just about to reply that you probably need to change the name.

The issue is, the Firefox search bar comes installed with DDG. When you delete default engines from Firefox, they don't really delete. They're just hidden. As a result, the OpenSearch engine wasn't showing up in the Firefox search bar to be added because Firefox knew it was already installed.

**Comment by redactedscribe** [comment]
Thanks for the help. I'll keep it in mind.
