### ISSUE TITLE
Ability to backup/export?

### ISSUE THREAD

**Issue by 3d73a4a412** [ssborbis/ContextSearch-web-ext#27]
Great extension, actually phenomenal. BUT one biggie, for me at least, I don't see a way to export my (long) list of search shortcuts. Is there a file that can be copied? If not I'd like to request an option to backup the file in case ones computer implodes or perhaps one wants to use the same list on another computer or even export to json so one can have it in their search options in FF.
Thanks!

**Comment by ssborbis** [comment]
Ok I've got the basics coded. Ability to import/export will be in the next release

**Comment by ssborbis** [comment]
Import/Export added to v1.4.1. Windows serves the exported file as a download, but the linux distro I tested opens it as a text page requiring a 'Save As' but it works.

**Comment by hg42** [comment]
nice, thanks
