### ISSUE TITLE
quick menu stopped working -- FF 80, CS 1.26

### ISSUE THREAD

**Issue by sign-in-smth** [ssborbis/ContextSearch-web-ext#273]
it all worked fine yesterday. updated FF and CS this morning.
now, instead of search results, quick menu opens blank tabs
moz-extension://723c3b3e-fdd9-479d-bdad-c8fb7f356576/blank.html

tried the available ways to reset engine list via CS options -> Search Engines, didn't help

also noticed that import by Select file.. from search.json.mozlz4 stopped working too (nothing gets imported)

**Comment by ssborbis** [comment]
Send me your config

**Comment by ssborbis** [comment]
ssborbis@gmail.com

**Comment by ssborbis** [comment]
I see why `Select File...` is failing. Moz changed some formatting in the search.json.mozlz4 file. I have a fix ready.

I can't get the qm bug on any of my configs

**Comment by sign-in-smth** [comment]
i think the qm issue affects only my own created search engines.
the 12 CS default engines work fine. i just dont use any of those, keep them hidden.
i'll email config in a minute.

**Comment by ssborbis** [comment]
Can you also email me your search.json.mozlz4 file so I can get your Firefox engines? One issue is the new FF changes are preventing addons from reading the templates associated with the preloaded Firefox search engines making them impossible to fully import. I wouldn't think it would effect custom engines installed to the Firefox search bar ( working on my config ), but I'll import yours and see what's going on.

**Comment by sign-in-smth** [comment]
done

**Comment by ssborbis** [comment]
I pushed a fix for importing the mozlz4 file but it can no longer import the default engines installed to the FF search bar. I'm not seeing the qm issue you describe, but maybe that will be fixed as well. Can you sideload and test?

**Comment by sign-in-smth** [comment]
but did you receive my mozlz4 file?
my search engines don't produce blank tabs on your platform?

**Comment by sign-in-smth** [comment]
yes, with the repo version, if i import engines from file, quick menu works again, thank you !

but the other way, via API, no still not.

curious thing i also noticed earlier, this blank tab outcome sometimes does NOT happen, very rarely, like in 1% attempts
could it be then maybe some kind of timeout issue or something ?

**Comment by ssborbis** [comment]
> but the other way, via API, no still not.

Can you explain a bit? I don't understand. 

> curious thing i also noticed earlier, this blank tab outcome sometimes does NOT happen, very rarely, like in 1% attempts
could it be then maybe some kind of timeout issue or something ?

Could be. I'll need to see the bug in action before I know for sure.

**Comment by ssborbis** [comment]
> Can you explain a bit? I don't understand.

Never mind. I think i'm seeing it now. The FF one-click engines aren't working

**Comment by sign-in-smth** [comment]
> 
> 
> Can you explain a bit? I don't understand.
> 

i mean if i click Restore defaults, and engines get the yellow FF tag on the list

**Comment by ssborbis** [comment]
Yep, there's definitely a timing issue going on. I think it's due to a change in the browser.search API not working on blank pages / new tabs immediately. I added a slight delay (50ms) before performing a search using the browser.search API on a new tab. It seems to be working locally.

I think there's also an issue when using the "last used engine" tool with OCSEs causing a blank page, but I'll deal with that later. Check the repo for the changes and see if that fixes the blank page on search issue.

**Comment by sign-in-smth** [comment]
> 
> 
> Check the repo for the changes and see if that fixes the blank page on search issue.

i'm getting ~85-90% success rate with this version.
but this added delay sorta feels quite noticeable (with the gray background), before page loads.
i mean aesthetically, i dunno, is it even worth keeping this feature now?
and to fix it completely, would it require even greater delay? so even less prettiness..

but if i load engines from the mozlz4, it's all fast and looks clean as usual.
so overall, i think its what i'd rather use from now, even though it requires the upload step.
what do you think?

**Comment by ssborbis** [comment]
I may be able to get away with using about:blank since this section is only for FF. I updated the repo with a version that removes the delay and opens a new tab to about:blank. Try that

**Comment by sign-in-smth** [comment]
> 
> 
> Try that

yep, that did the track, now its fast and awesome like it was before !

and other small question, about Select all engines -> Delete
- in case i load engines from mozlz4, then Select all -> Delete, refresh settings page, CS fully repopulates the list with FF tagged engines
- in case i use FF tagged engines (or reload them by Restore default), then Select all -> Delete, refresh settings page, CS again fully repopulates the list with the same FF tagged engines, now with hidden status

maybe it's feature, not a bug, but it would seem to me that 'delete all' should produce empty list, and keep it that way, until directed otherwise. i just ran into it a few times today and it seemed confusing

**Comment by ssborbis** [comment]
v1.26.1 should be up

> and other small question, about Select all engines -> Delete

FF engines are always added on restart. Best to just hide them. Keeping a secondary list of *really really hidden* engines is a hassle with it's own set of problems. The only thing I might change is repopulating the FF engines whenever changes are made to the search engines list to give some immediate feedback to the user that they're still there.

**Comment by ssborbis** [comment]
Ancient issue cleanup!

New versions have an option to disable checking for FF engines so they don't automatically re-appear. This feature could use some testing, but it's there and working until I hear otherwise.
