### ISSUE TITLE
🐞report: After dragging the sidebar, the entire page is frozen

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#275]
## ❶ After dragging the `sidebar`,  ❷🐞Bug will have a chance. 
⚠Not every time such an operation will cause a bug, but the probability is very high.
📃Chrome⁸⁰ Win¹⁰
![bug](https://user-images.githubusercontent.com/10995302/91852903-09166900-ec94-11ea-9883-3618bb8f989d.gif)

**Comment by ssborbis** [comment]
This must be a bug in Chrome. Mouse events are passing through a hidden, top z-index div into the menu iframe. Do you know if it happened prior to Chrome 80?

**Comment by dnknn** [comment]
> Do you know if it happened prior to Chrome 80?

 　　 Well, I specifically test and 🐞 all reproduce on the `Chrome⁷⁸ ⁷⁹ ⁸⁰ ⁸⁴` .
---

This almost 99% sure shows that all Chrome versions can reproduce this 🐞

Test URL👉https://github.com/ssborbis/ContextSearch-web-ext
###  The chance of recurrence is about 30%-70%, So it needs to be tested repeatedly...

**Comment by ssborbis** [comment]
Ok I see what's happening. In Chrome, if the drop area is inside the menu iframe, the "move" event isn't ended. I'll get it fixed and post here when I have something in the repo worth testing.

**Comment by dnknn** [comment]
🆗👌

**Comment by ssborbis** [comment]
Fix in the repo

**Comment by dnknn** [comment]
Thank you very much, then  close this issue.
