### ISSUE TITLE
Can support the gbk encoding ?

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#276]
![207_31105338](https://user-images.githubusercontent.com/10995302/88994975-22866700-d31c-11ea-9ebd-1ef76fe7eee2.png)
![209_01205047](https://user-images.githubusercontent.com/10995302/91853477-d5880e80-ec94-11ea-8ab8-f32f7b246d1d.png)

The localized encoding of the Simplified Chinese character set is called `gbk` or `gb2312` or `cp936`
Can support be added 👆?
Yes, the post method can also be implemented, but it need second jump, and get method direct arrival, so want to request add for Simplified Chinese localization encoding.

-----
 `UTF-8` encoding of &ensp;&emsp;`中文`&ensp; is `%e4%b8%ad%e6%96%87`
 `gbk` &ensp; encoding of &ensp;&ensp; &ensp; `中文`&ensp; is `%d6%d0%ce%c4`

Related examples to reference, 👇

- Selection Search
&ensp;https://chrome.google.com/webstore/detail/gipnlpdeieaidmmeaichnddnmjmcakoe
&ensp;https://github.com/Pitmairen/selection-search

![207_31112203](https://user-images.githubusercontent.com/10995302/88996538-13a1b380-d320-11ea-9c6b-13c7e11cc2b2.png)

- search2
&ensp;https://chrome.google.com/webstore/detail/godjlopkhiadfppdjhbekbppchinkmpi
&ensp;https://github.com/wurenny/search2
![207_31113635](https://user-images.githubusercontent.com/10995302/88997369-18676700-d322-11ea-8776-67f9d59b0694.png)

![207_31114137](https://user-images.githubusercontent.com/10995302/88997686-cffc7900-d322-11ea-965e-89ee508643e7.png)

**Comment by ssborbis** [comment]
The encoding library I use can do it. I'll add it if you want to test.

**Comment by dnknn** [comment]
👏💪👍, thank you very much, of course, I am also very happy to take the local-encoding test.

**Comment by ssborbis** [comment]
Changes are in the repo if you want to test. 

Also, if you have a website that requires GBK encoding, could you post a link here with a search term I can use to test?

**Comment by dnknn** [comment]
> Changes are in the repo if you want to test.

Sorry, I am not a developer, I don’t know how to use repo at all

> could you post a link here with a search term I can use to test?

Here, I found a test example without login 👇

http://www.yxsanhu.com/forum.php

GET method 👇
`http://www.yxsanhu.com/search.php?mod=forum&orderby=dateline&searchsubmit=yes&srchtype=fulltext&srchtxt=摄影`

**Comment by ssborbis** [comment]
Using the search term you provided with the site **http://www.yxsanhu.com/forum.php** and the newly added GBK encoding, my results page was

![search](https://user-images.githubusercontent.com/24310997/92048161-9ae1ad00-ed4c-11ea-8065-9bb25df27892.png)

Looks good, so I'm going to assume the encoding is working properly.

**Comment by dnknn** [comment]
👍Yes it is perfect！Thanks！
