### ISSUE TITLE
Can remember the last switch state of the sidebar 💞 an icon ?

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#277]
![209_02181556](https://user-images.githubusercontent.com/10995302/91969230-5eac4d80-ed48-11ea-87aa-c3a13a8a2055.png) 👈 two options together ☑

----
- ## 💥 Current issue: 
　　when the page loads, the **default** state can only  `Open the sidebar`,
　　In other words,  can’t follow/memory/remember the last state.
- ## ❥ Expected behavior: Smart memory
　　1.  When `Open the sidebar` , you click `🗙` close button  to turn into a `🔍` icon,
　　2.  when the page loads/reload,  the default will be a `🔍` icon instead of `Open the sidebar`

<details>
<summary>🎬 gif demo</summary>

![111](https://user-images.githubusercontent.com/10995302/91971321-94066a80-ed4b-11ea-8aa9-cc0e464b0262.gif)

</details>

- ## ❓ How to achieve: 
　　Changed by default,  or Add a ON/OFF option.

**Comment by ssborbis** [comment]
Done. New option will be in the advanced menu.

**Comment by dnknn** [comment]
Great! thank you very much
