### ISSUE TITLE
invalid for single-letter hotkeys

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#278]
invalid for single-letter hotkeys , see at [comment](https://github.com/ssborbis/ContextSearch-web-ext/issues/278#issuecomment-691198042)

<details>
<summary>Details</summary>

`🅐🅑🅒🅓🅔.......🅦🅧🅨🅩0️⃣1️⃣......🔟#️⃣️*️⃣,./';\]'[]-=....`

<s>Bug for 🔠 keyboard hotkey 👇 invalid: doesn't work at all.
</s>

![209_12003535](https://user-images.githubusercontent.com/10995302/92951554-1ea84180-f491-11ea-8553-9419532da8dc.png)

![209_02200441](https://user-images.githubusercontent.com/10995302/91978934-8ce55980-ed57-11ea-9fba-e0891602e098.png)

</details>

**Comment by ssborbis** [comment]
Got it.

**Comment by ssborbis** [comment]
Fix is in the repo for testing.

**Comment by dnknn** [comment]
Thanks♪ 👏

**Comment by dnknn** [comment]
Hi @ssborbis  !
![209_12003535](https://user-images.githubusercontent.com/10995302/92950796-e2c0ac80-f48f-11ea-9147-025b3e0da495.png)

#   but 👇 still invalid 
![209_12003402](https://user-images.githubusercontent.com/10995302/92950709-b2790e00-f48f-11ea-9e11-0062669f7c3f.png)

### Or am I using the wrong way? Can you tell me the correct way to use it?

**Comment by ssborbis** [comment]
for search engine hotkeys ( select text, press letter ) you need to set hotkey action

![Untitled](https://user-images.githubusercontent.com/24310997/92962756-128f9600-f437-11ea-9d4b-b70ad3d825df.png)

And enable `Advanced -> allowHotkeysWithoutMenu`

**Comment by dnknn** [comment]
<details>
<summary>Details</summary>

> for search engine hotkeys ( select text, press letter ) you need to set hotkey action
> 
> ![Untitled](https://user-images.githubusercontent.com/24310997/92962756-128f9600-f437-11ea-9d4b-b70ad3d825df.png)
> 
> And enable `Advanced -> allowHotkeysWithoutMenu`
> 
> Originally, hotkeys only worked when the quick menu was open, so you need to set the advanced option

</details>

@ssborbis I finally understand now, Thanks♪(･ω･)ﾉ.
but see at :
https://github.com/ssborbis/ContextSearch-web-ext/issues/284#:~:text=📖%20Add%20help%20document/tooltip%20🌟

**Comment by rediffusion** [comment]
@dnknn 
 Maybe you can tell how this shit works? I need some screencast!

> "allowHotkeysWithoutMenu": false,
