### ISSUE TITLE
Options page#hash

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#280]
## If it is easy, I think `url#⚓hash/anchor` is better.

`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#ContextMenu`
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#QuickMenu`
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#Toolbar`
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#Sidebar`
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#Highlight`
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#SearchResults`
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#FindBar`
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#SearchEngines`
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#General`
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#Advanced`
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#Help`

　　
![url](https://user-images.githubusercontent.com/10995302/92454989-b7ba2c80-f1f3-11ea-9e72-b3bd18025682.gif)

　　

### Because many options, `url#hash` can helps to take notes 📝.

And GoogleChrome added a new URL-text API , It can automatically jump to that location and highlight it.

<details>
<summary> details for a new URL-text API of Chrome⁸¹ᐩ </summary>

> https://developers.google.com/web/updates/2020/02/nic80?hl=tr#more
> Starting from Chrome⁸¹ᐩ, URL`#:~:text=⚓` is a useful new feature.

First try: copy it 👇, then open it in a new tab and see .
`https://github.com/ssborbis/ContextSearch-web-ext#🦉:~:text=template should,simulate`
![209_08151415](https://user-images.githubusercontent.com/10995302/92444796-f943db00-f1e5-11ea-89c9-d596566aeec2.png)

### 　　　　[wicg.github.io/scroll-to-text-fragment/](https://wicg.github.io/scroll-to-text-fragment/)

The most commonly used syntax is url#:~:text=`textStart[,textEnd]`
![8145106](https://user-images.githubusercontent.com/10995302/92442755-00b5b500-f1e3-11ea-9ec6-902c6429b72b.png)

</details>

　

If you support `#hash` on the `left-sidebar` of the options page, you can directly use a URL to locate a specific location. 👇 

`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#QuickMenu#👁:~:text=Close menu by scrolling or using the`

![209_08150835](https://user-images.githubusercontent.com/10995302/92444267-30fe5300-f1e5-11ea-9673-92f87073ed65.png)

**Comment by ssborbis** [comment]
sure

**Comment by ssborbis** [comment]
> Means to agree and adopt this suggestion 😁🤦 ?

Yeah, it's basically done. I just need to fix a few things before updating the repo code.

**Comment by dnknn** [comment]
> Yeah, it's basically done. I just need to fix a few things before updating the repo code.

nice
