### ISSUE TITLE
❥ multi URLs in a single  template ❣

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#282]
fixed, see at  https://github.com/ssborbis/ContextSearch-web-ext#templateparameters

<details>
<summary>Title</summary>

<details>
<summary>Yes, can open multiple 🔍 in the form of a folder, but that is another matter, and for parameters such as `{selectdomain}`, it cannot be done.</summary>

![209_08172738](https://user-images.githubusercontent.com/10995302/92458963-ac1d3480-f1f8-11ea-9284-2e236ad2f86e.png)

</details>

<details>
<summary>What we are discussing now is this issue 
</summary>

![209_08171835](https://user-images.githubusercontent.com/10995302/92457892-5a27df00-f1f7-11ea-9a30-b4aec2264261.png)

</details>

`https://www.google.com/search?q={searchTerms}`
`https://www.bing.com/search?q={searchTerms}`

🖌 Add a special syntax format to support multiple URLs in a single template:
- ### 　　　For example using `{}` package 　　 👇
```
{https://www.google.com/search?q=site:{selectdomain}+{searchTerms}}{https://www.bing.com/search?q=site:{selectdomain}+{searchTerms}}
```

- ### 　　　Or  using `{AddSearchTerm}` parameter  　　👇
```
https://www.google.com/search?q=site:{selectdomain}+{searchTerms}{AddSearchTerm}https://www.bing.com/search?q=site:{selectdomain}+{searchTerms}
```

I suggest it is better to use split syntax parameters to connect multiple URLs,  because it is easier to read. for example: ` {&&}` mean: `and` in JavaScript code
##  　　　 　　` {&&}` 　　👇
`https://www.google.com/search?q={searchTerms}{&&}https://www.bing.com/search?q={searchTerms}`

........

----

<details>
<summary>Expected behavior : Just like `Bookmarklet` </summary>

`javascript:kw=prompt("open multiple 🔍", window.getSelection()); if(kw!=null){window.open('https://www.google.com/search?q=' +kw); window.open('https://www.bing.com/search?q=' +kw);}`

If want to can open multiple pages of `JavaScript:` code
`chrome://settings/content/popups`
![209_10200628](https://user-images.githubusercontent.com/10995302/92727226-589a1a80-f3a1-11ea-8bb0-2a79b1028da6.png)

![444](https://user-images.githubusercontent.com/10995302/92465336-09b57f00-f201-11ea-9a12-18402ee7630c.gif)

</details>

</details>

**Comment by ssborbis** [comment]
There is also {domain} and {subdomain} that can be used without the additional menu if you want to add similar searches to a folder and search all at once. If you really want the {selectdomain} feature with multiple engines, I'll look into a solution that doesn't require multiple URLs in a single template.

And yes, the documentation is missing for these params. I'll add something now.

**Comment by dnknn** [comment]
> If you really want the {selectdomain} feature with multiple engines, I'll look into a solution that doesn't require multiple URLs in a single template.

No, no, .... you don't understand the meaning at all ,  For `{selectdomain}`, I just give it an example, not for `{selectdomain}` but `{selectdomain}`.

----

> I'll look into a solution that doesn't require multiple URLs in a single template.

No, no, .... it must be require multiple URLs in a single template, just like `Bookmarklets` (can multiple URLs in a single template)

`multiple URLs in a single template` ⚔  `search all at once with a folder` ,

These two are not in conflict, have their own advantages, 
For example, every time you search both engines `A && B` at the same time, instead of using one of (`A || B`) the engines to search,
At this point, you don't need to use the folder method at all , The way you change to `multiple URLs in a single template` , It is simpler, you don't have to create a folder for `A and B`.
In addition, it can also work in ContextMenu, which currently cannot open folder at once.


---
If you want to implement it, I suggest it is better to use split syntax parameters to connect multiple URLs,  because it is easier to read.

For example: 　　` {&&}`
`&&`  mean `and` in JavaScript code

**Comment by ssborbis** [comment]
I understand now. I'll look into it.

**Comment by ssborbis** [comment]
A better way might be to make separate engines / templates and reference them in another template by id.

engine 1 template `https://www.google.com/search?q=site:{selectdomain}+{searchTerms}` 
id = JNWIM4OXP0V2S

engine 2 template `https://www.bing.com/search?q=site:{selectdomain}+{searchTerms}`
id = K5GJTRNZX952H

engine 3 template `CS://JNWIM4OXP0V2S+K5GJTRNZX952H` or something similar

**Comment by dnknn** [comment]
> A better way might be to make separate engines / templates and reference them in another template by id.

So here comes the question, how to get/check the 🆔  , 
I don't see any 🆔, Or i don't understand the operation

**Comment by dnknn** [comment]
> And yes, the documentation is missing for these params. I'll add something now.

@ssborbis Hi!
![209_18033013](https://user-images.githubusercontent.com/10995302/93518418-5adf1480-f95f-11ea-94d4-12eae0fb7122.png)

## `{inputEncoding}`

In addition, I would also like to ask what parameter is `{inputEncoding}` ❓	

https://github.com/ssborbis/ContextSearch-web-ext#template-parameters

**Comment by ssborbis** [comment]
> So here comes the question, how to get/check the 🆔 ,

I can list it in the search engine manager for each engine

> In addition, I would also like to ask what parameter is {inputEncoding} ❓

There are some standardized OpenSearch parameters that I do some rudimentary string replacement on in case they show up.

```
return template
		.replace(/{searchTerms}/g, searchterms)
		.replace(/{count[\?]?}/g, "50")
		.replace(/{startIndex[\?]?}/g, "1")
		.replace(/{startPage[\?]?}/g, "1")
		.replace(/{language[\?]?}/g, (navigator) ? navigator.language || navigator.userLanguage : "")
		.replace(/{inputEncoding[\?]?}/g, (document) ? document.characterSet || "" : "")
		.replace(/{outputEncoding[\?]?}/g, (document) ? document.characterSet || "" : "")
		.replace(/{subdomain}/g, domains.subdomain || "")
		.replace(/{domain}/g, domains.domain || "")
		.replace(/{selectdomain}/g, userdomain || "")
		.replace(/{.+?\?}/g,"") // optionals
		.replace(/{moz:.+?}/g, "") // moz specific
		.replace(/{.+?}/g, ""); // all others
```

**Comment by dnknn** [comment]
> I can list it in the search engine manager for each engine
> 
> >

No, I mean this feature already exists or it hasn't started yet ?

**Comment by ssborbis** [comment]
> No, I mean the 🆔 already exists or it hasn't started yet (Plan statu) ?

No, I haven't implemented any way to do multiple engines in one template. I'm toying with ideas, but nothing is coded yet. I'll let you know.

**Comment by dnknn** [comment]
> I'm toying with ideas

Well, I understand now. But 👇


> engine 1 template `https://www.google.com/search?q=site:{selectdomain}+{searchTerms}`
> id = JNWIM4OXP0V2S
> 
> engine 2 template `https://www.bing.com/search?q=site:{selectdomain}+{searchTerms}`
> id = K5GJTRNZX952H
> 
> engine 3 template `CS://JNWIM4OXP0V2S+K5GJTRNZX952H` or something similar


This is the internal coding logic of the code ?  or the user front end needs to operate like that ?

If `/options.html#engines` need to do that, I think it will be very complicated.

**Comment by ssborbis** [comment]
> If /options.html#engines need to do that, I think it will be very complicated.

I suppose, but doing it the way you describe will only work if both engines are GET and use the same encoding. Instead of ID I could use the engine name since they should be unique.

**Comment by dnknn** [comment]
> if both engines are GET and use the same encoding

I did not consider this situation ,  now I fully understand your idea.
now I have two idea, do you think it is feasible :

## 1️⃣ Add a menu item (your idea) on the Right-click-ContextMenu
　　　　Multiple URLs can use different eigenvalues.

![209_19100943](https://user-images.githubusercontent.com/10995302/93656882-65cd9e00-fa60-11ea-871f-54f1a7bfe262.png)

## 2️⃣ Operate directly in the template, no need to use id.
　　　　Multiple URLs must only use the same `get`, `encoding`, etc. [#issue-695720140](https://github.com/ssborbis/ContextSearch-web-ext/issues/282#issue-695720140)

---
The above two coexist and complement each other.

**Comment by ssborbis** [comment]
Update in the repo should allow multiple URLs in the template field using `/[;|,|\s]\s*http/` as delimiters (space, semicolon, comma)

For example, `http://example1.com http://example2.com`

**Comment by dnknn** [comment]
> Update in the repo should allow multiple URLs in the template field using `/[;|,|\s]\s*http/` as delimiters (space, semicolon, comma)

thank you very much, I tested it, it seems unstable or has bugs.

```
https://www.google.com/search?q=site:{selectdomain}+{searchTerms} https://www.bing.com/search?q=site:{selectdomain}+{searchTerms}
```

It works for the first time, but it is invalid later, it automatically become to👇
`https://www.bing.com/search?q=site:{selectdomain}+{searchTerms}`
I don't know why
![209_21235613](https://user-images.githubusercontent.com/10995302/93790843-0f31b100-fc66-11ea-8871-e1dd6c9f1131.png)

**Comment by ssborbis** [comment]
I had that happen also, but I thought it was fixed. I'll look into it.

**Comment by dnknn** [comment]
> I had that happen also, but I thought it was fixed. I'll look into it.

OK,  In addition, how to use this  `handler for CS://id+id format in template` 

did not see any 🆔 in the test

**Comment by ssborbis** [comment]
>  Now, multi-URLs is invalid, because It will automatically become single or even disappear completely.

That's exactly what I was seeing. For some reason, it worked all session, but when I loaded the code as a temporary addon for testing just now, it reverted to only displaying the last URL in the template. I'll let you know.

> did not see any 🆔 in the test

I didn't add anything visual yet, but the ID for each node will be logged to the console when you left-click on a row/node in the search engines manager

**Comment by dnknn** [comment]
> I didn't add anything visual yet, but the ID for each node will be logged to the console when you left-click on a row/node in the search engines manager

![209_22094705](https://user-images.githubusercontent.com/10995302/93837415-990a6a00-fcb8-11ea-9e25-f0619320c11b.png)
I understand, it turns out that can see 🆔 in the Chrome-DevTools \<Console\> ,great!

**Comment by dnknn** [comment]
> That's exactly what I was seeing. For some reason, it worked all session, but when I loaded the code as a temporary addon for testing just now, it reverted to only displaying the last URL in the template. I'll let you know.
> 
> >

Is this bug related to `Last used search engine` ❓	

![209_22095851](https://user-images.githubusercontent.com/10995302/93837849-416cfe00-fcba-11ea-8243-de432837cc4d.png)

`Last used search engine`   ,Currently it can only record a single template

**Comment by ssborbis** [comment]
> Last used search engine ,Currently it can only record a single template

Thanks. I'll make the changes

**Comment by dnknn** [comment]
> Thanks. I'll make the changes

It can follows the last engine exactly, whether it is a single or multiple-urls or a folder.

**Comment by ssborbis** [comment]
I have a fix but it may make going back to an older version of this addon problematic. The next update to the repo will include some changes that may be buggy.

**Comment by ssborbis** [comment]
Ok, changes are in the repo. I wouldn't expect multiple URL templates to work with {selectdomain} though.

**Comment by ssborbis** [comment]
Bah, I keep getting the template reverting back to a single url. There must be some URL error checking in there I'm not accounting for. I'll let you know.

**Comment by dnknn** [comment]
Thank you, I will wait for you to fix it, and then test it again.

**Comment by ssborbis** [comment]
I'm still having some templates revert back to single urls, but it may be due to going back and forth between the last release version and the temporary addon version. You can test it out if you want, but don't be surprised if your multi-URL templates get lost.

I'm probably going to stick with a `CS://url+url+url` style template format because I have a lot of code that requires the template to be an URL. You can still put in urls with spaces or + or whatever, and those should be converted to  `CS://url+url+url` format when you click the save button.

I'm working on getting the {selectdomain} to play nice with multi-URL templates. That's next on the list.

**Comment by dnknn** [comment]
Okay, I will retest it after you release the new version to the store.

**Comment by ssborbis** [comment]
> Can it remember the most recent non-single URL template (ie: folder/multi URLs in a single template)?

Yeah, I have that fix in the repo. I also finally tracked down the issue causing the templates to revert.

**Comment by dnknn** [comment]
> Yeah, I have that fix in the repo. I also finally tracked down the issue causing the templates to revert.

That's great, very great !!

**Comment by dnknn** [comment]
> I also finally tracked down the issue causing the templates to revert.

That's great, very great !!  It seems to be able to save multi-URL and works well.

> Yeah, I have that fix in the repo. 

For other situations, you have not taken care of them all. Now, there are now 3 bugs/issues :

1.  `sideBar.openOnResults`	can not work on the multi-URL.
![2010_06145721](https://user-images.githubusercontent.com/10995302/95168669-3f3f8f00-07e4-11eb-963f-c868e64f40f7.png)
sideBar only openOnResults at one of the multi-URL.

---
2. For URLs with different encodings, how to be in a template? Now have a good idea:
- like `{searchTerms}` , Add encoding parameter `{CodingGbk}`  to URL.  
The default (not written) is UTF-8 encoding.

`CS://url1+url2{CodingGbk}`　　url1 use UTF-8, url2 use Gbk.

Maybe only in this way can it be well supported.

---
3. `Last used search engine`  　　Now support multi-URL, but not `folder`. 
Include right-click contextMenu.
![2010_06151101](https://user-images.githubusercontent.com/10995302/95169879-289a3780-07e6-11eb-97dd-8eb27a53ef8e.png)

**Comment by ssborbis** [comment]
> 1. sideBar.openOnResults	can not work on the multi-URL.

What's your template? I'm getting normal behaviour using `CS://https://www.google.com/search?q={searchTerms}+https://www.google.com/search?q={searchTerms}` to test using the latest code in the repo.

> 2. For URLs with different encodings, how to be in a template? Now have a good idea:

Something like that should work. I'll let you know when I have something to test

> 3. Last used search engine 　　Now support multi-URL, but not folder.

It never supported folders, but I can add it.

**Comment by dnknn** [comment]
> > 1. sideBar.openOnResults	can not work on the multi-URL.
> 
> What's your template?

I finally found the source of the reproduced bug, I think you should reorganize the symbolic logic about `multi-URL`. Because it not only caused the problem of sideBar.openOnResults, but also caused many other problems......


![2010_07161713](https://user-images.githubusercontent.com/10995302/95305454-92831180-08b8-11eb-9782-128b2f8d68b2.png)



For example  | |   
--- |:---: |--- |
`https://www.google.com/search?q={searchTerms}` | ✔️ | 
`https://www.google.com/search?q={searchTerms}&ie=utf-8&newwindow=1` | ✔️ | 
`CS://https://www.google.com/search?q={searchTerms}+https://www.bing.com/search?q={searchTerms}` | ✔️| 
  |   |   
`&` is a very important key parameter in the URL , but all `&` parts will be ignored  |    |    
`CS://https://www.google.com/search?q={searchTerms}&ie=utf-8&newwindow=1+https://www.bing.com/search?q={searchTerms}&ie=utf-8&newwindow=1` | ❌| all `&` will be ignored
  |   |   
The `+` in the URL will be treated as a `space` output, right?  but all `+` parts will be ignored. The `+` of `CS://` and the `+` of the URL itself should be incompatible at present. This should be something you forgot to consider |   |   
`https://www.google.com/search?q=site:{selectdomain}+{searchTerms}` | ✔️ | 
`CS://https://www.google.com/search?q=site:{selectdomain}+{searchTerms}+https://www.baidu.com/s?wd=site:{selectdomain}+{searchTerms}` | ❌| all `+` will be ignored

----

`CS://https://www.google.com/search?q=test1+{searchTerms}+test2+https://url2....`
👆 It has 3 `+` , right? The internal logic cannot determine which `+` is the separator of `CS://` 

So, I think you should use another independent feature parameter for the `+` of `CS://`

For example: `{+}` or `\+` .etc

**Comment by dnknn** [comment]
@ssborbis look in https://github.com/ssborbis/ContextSearch-web-ext/issues/282#issuecomment-704777122

**Comment by ssborbis** [comment]
Whoops, the `&` in the regex was a mistake, but I get your point on the rest. I suppose I could just make the template accept an array and be done with it `["url1", "url2", "url3"]`. Also, most of this could be handled using folders, especially now that the lastUsed tool handles folders.

**Comment by ssborbis** [comment]
Recent push accepts an array that can be parsed by `JSON.parse(..)` in the form `["url1", "url2", "url3"]`

**Comment by dnknn** [comment]
> Recent push accepts an array that can be parsed by `JSON.parse(..)` in the form `["url1", "url2", "url3"]`

I don't know what you mean, so I want to test it, but I can't get started.
How to write it into the search engine template?



> Update in the repo should allow multiple URLs in the template field using `/[;|,|\s]\s*http/` as delimiters (space, semicolon, comma)
> 
> For example, `http://example1.com/{searchTerms} http://example2.com/{searchTerms}`

Is the previous grammar completely unusable❓, I find it seems to be invalid❓

**Comment by ssborbis** [comment]
> Is the previous grammar completely unusable❓, I find it seems to be invalid❓

You need to use the new format

an example would be

`["https://www.google.com/search?q=test1+{searchTerms}+test2", "https://www.google.com/search?q={searchTerms}&ie=utf-8&newwindow=1", "https://www.google.com/search?q=test1+{searchTerms}+test2"]`

**Comment by ssborbis** [comment]
Latest push allows multiURLs to set encoding with `{encoding=...}` format i.e. `{encoding=gbk}`

You should be able to put it anywhere in the URL.

**Comment by dnknn** [comment]
> You need to use the new format

Thank you, I fully understand and the test works.

> allows multiURLs to set encoding with `{encoding=...}` format i.e. `{encoding=gbk}`

I want to ask you, where should `{encoding=xxx}` be placed, The following positions are all allowed, right?

`["url1{encoding=xxx}", "{encoding=xxx}url2", "url3"]`

---
I feel very satisfied with the test, maybe the JSON syntax format is the most perfect💪

**Comment by ssborbis** [comment]
> I want to ask you, where should {encoding=xxx} be placed, The following positions are all allowed, right?

`"{encoding=xxx}url2"` may not work because the addon is looking for URLs, so it's best to put it somewhere after the protocol and domain

**Comment by ssborbis** [comment]
> Then I encountered a bug in both the last version and the latest version, and you should be able to reproduce it. see at: 👇

Thanks! I appreciate all your thorough debugging. Fixed and I updated the repo.

**Comment by dnknn** [comment]
The multi-URL function should be close to perfect, I close this issue.  Thank you so much for your hard work! Thanks again!

**Comment by dnknn** [comment]
HI @ssborbis  I guess you forgot to add the following content (multi-URLs in a single template) to [the help document](https://github.com/ssborbis/ContextSearch-web-ext#templateparameters) 📖 ❓ (I looked through all but couldn't find it! ^_^)


> Recent push accepts an array that can be parsed by `JSON.parse(..)` in the form `["url1", "url2", "url3"]`



> `["https://www.google.com/search?q=test1+{searchTerms}+test2", "https://www.google.com/search?q={searchTerms}&ie=utf-8&newwindow=1", "https://www.google.com/search?q=test1+{searchTerms}+test2"]`



> Latest push allows multiURLs to set encoding with `{encoding=...}` format i.e. `{encoding=gbk}`

**Comment by dnknn** [comment]
HI @ssborbis  

I guess you forgot to add the following content (multi-URLs in a single template) to [the help document](https://github.com/ssborbis/ContextSearch-web-ext#templateparameters) 📖 ❓ (I looked through all but couldn't find it! ^_^)

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/10995302/109873156-59ed3580-7ca8-11eb-8021-6b337e163521.png)

</details>


`["url1", "url2", "url3"]`

> Recent push accepts an array that can be parsed by `JSON.parse(..)` in the form `["url1", "url2", "url3"]`



> `["https://www.google.com/search?q=test1+{searchTerms}+test2", "https://www.google.com/search?q={searchTerms}&ie=utf-8&newwindow=1", "https://www.google.com/search?q=test1+{searchTerms}+test2"]`



> Latest push allows multiURLs to set encoding with `{encoding=...}` format i.e. `{encoding=gbk}`


　
　
---

## 💥🐞 Report two Bugs for:  `["url1", "url2", "url3"]`

> No problem in itself, but the functions related to it cannot work as normal as a single URL template. I found 2 bugs, and hope you can fix them! Thank you very much!

- ### Reproduce demo to reproduce: 
`["https://google.com/search?q={searchTerms}", "https://bing.com/search?q={searchTerms}"]`

----

- ## Bug1:  Cannot use the `Test` button 

<details>
<summary>Click to view the screenshot to understand the problem.</summary>

![image](https://user-images.githubusercontent.com/10995302/109884694-595c9b00-7cb8-11eb-9d8c-226ad429a75f.png)

</details>


open at 👇
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/[%22https://google.com/search?q=test%22,%20%22https://bing.com/search?q=test%22]`


----

- ## Bug2:  Can't be remembered (It also means that it Can't enter the Search History)

`{searchTerms}` of  ["url1", "url2", "url3"] , Can't be remembered and enter the Search History.

<details>
<summary>Click to view the screenshot to understand the problem.</summary>

![image](https://user-images.githubusercontent.com/10995302/109883472-7001f280-7cb6-11eb-86ff-c44b6cb1aa1a.png)

</details>

**Comment by ssborbis** [comment]
README.md updated and both bugs should be fixed in the repo

**Comment by dnknn** [comment]
🆗👌 💪👍 Thank you very much!!!

> README.md updated

@ssborbis  You seem to miss a document message [at here](https://github.com/ssborbis/ContextSearch-web-ext#templateparameters
)  👇

>  allows multiURLs to set encoding with `{encoding=...}` format,  i.e. `{encoding=gbk}`
> Note: This syntax can only be used in `["url1", "url2", "url3"]` array template.

**Comment by dnknn** [comment]
🆗👌 💪👍 Thank you very much!!!

> README.md updated

@ssborbis  You seem to miss a document message [at here](https://github.com/ssborbis/ContextSearch-web-ext#templateparameters
)  👇

>  allows multiURLs to set encoding with `{encoding=...}` format,  i.e. `{encoding=gbk}`
> Note: This syntax can only be used in `["url1", "url2", "url3"]` array template.


----

In addition, I would like to ask when can push the store version?

**Comment by dnknn** [comment]
> both bugs should be fixed in the repo

👌 Thank you very much!!!  👍bugs was successfully fixed after tested!!💪

> README.md updated

@ssborbis  You seem to miss a document message [at here](https://github.com/ssborbis/ContextSearch-web-ext#templateparameters)  👇

>  allows multiURLs to set encoding with `{encoding=...}` format,  i.e. `{encoding=gbk}`
> Note: This syntax can only be used in `["url1", "url2", "url3"]` array template.

> example: `["https://google.com/search?q={searchTerms}", "https://bing.com/search?q={searchTerms}{encoding=gbk}"]`


----

In addition, I would like to ask when can push the store version?

**Comment by dnknn** [comment]
> both bugs should be fixed in the repo

👌 Thank you very much!!!  👍bugs was successfully fixed after tested!!💪

> README.md updated

@ssborbis  You seem to miss a document message [at here](https://github.com/ssborbis/ContextSearch-web-ext#templateparameters)  👇

>  allows multiURLs to set encoding with `{encoding=...}` format,  i.e. `{encoding=gbk}`
> Note: This syntax can only be used in `["url1", "url2", "url3"]` array template.

> example: `["https://google.com/search?q={searchTerms}", "https://bing.com/search?q={searchTerms}{encoding=gbk}"]`


🗣: Because there is no public help document, this function will always be buried, because
the users will never know the function, so it will lose its existence value.


----

In addition, I would like to ask when can push the store version?
