### ISSUE TITLE
New tab is opened far of the current tab

### ISSUE THREAD

**Issue by ildar-shaimordanov** [ssborbis/ContextSearch-web-ext#283]
New tab with the result is opened in the end of list of tabs and could be far of the current one.

In previous implementations (before the version 1.26.1) new tab with search results was opened immediately after the current tab or (if search was performed in a pinned tab) as the first tab after all pinned tabs. In the recent version, new tab is opened in the end of all tabs.

Assume 10 or more opened tabs with the 3rd one as active. In the current version (1.26.1) new tab will be opened after 10th. In previous implementation before 1.26.1, it opened new tab much closer.

UPD:
The described behavior has to do with the search engines marked with the orange "FF" icon in the list of search engines on the proper settings page. Those search engines which are nit marked with this icon work properly as expected.

**Comment by ssborbis** [comment]
Thanks. It's fixed locally now. I'll get the repo updated in the next day or 2.

**Comment by ildar-shaimordanov** [comment]
Thank you, @ssborbis. I wait and update when it appear in the mozilla collection site. After testing on my side I'll give my feedbacks.

**Comment by ildar-shaimordanov** [comment]
@ssborbis 
Please advise when the addon will be published officially.

**Comment by ssborbis** [comment]
I'll post here. I have a lot of changes to check on before the next release so it may be a while.

**Comment by ssborbis** [comment]
v1.27 live on AMO. ChromeStore in a day or 2

**Comment by ildar-shaimordanov** [comment]
It seems became worse. All search engines marked with the orange "FF" open new empty tab but doesn't perform searching.

**Comment by ildar-shaimordanov** [comment]
I finished my tests. It works as expected:
-- new tab with search results is opened next to the current regular tab
-- new tab with search results is opened immediately next after all pinned tabs

I could require to update search engines by importing engines from the `search.json.mozlz4` file.

**Comment by ssborbis** [comment]
> I finished my tests. It works as expected

That's good.

> I could require to update search engines by importing engines from the search.json.mozlz4 file

That's a bit disconcerting. I'll try to figure out why that would be.

**Comment by ssborbis** [comment]
@ildar-shaimordanov 

I've updated the version at Mozilla to 1.27.4 

There was an issue with Firefox engines ( those not imported via search.json.mozlz4 ) causing blank pages when opened from the context menu. That *should* be taken care of now. Let me know if you're still experiencing any issues.

**Comment by ildar-shaimordanov** [comment]
I tried to update it via about:addons. However it was disabled for some time. And I am not sure that it was updated properly because its version is still 1.27.1.

**Comment by ssborbis** [comment]
> I tried to update it via about:addons. However it was disabled for some time. And I am not sure that it was updated properly because its version is still 1.27.1.

That's odd. I'm showing 1.27.4 in the store. Maybe it's a regional cache issue.

What do you see here? https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/

**Comment by ildar-shaimordanov** [comment]
Yes, I can see it in the store, I've seen it in the addon's list of the browser. I guess, something has happened and update wasn't executed properly. After reloading the browser I updated the addon. It works properly, but I can't give any feedback regarding my last issue with empty tabs because all engines are normal now (not marked as FF engines).

Let's assume for now all these issues are resolved. If one of them happens again on my side, I report about it here (or file a new issue).

**Comment by ssborbis** [comment]
Thanks
