### ISSUE TITLE
Several improvements

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#284]
1. # 💱 Localized translation 💞

<details>
<summary>Details</summary>

Is it possible to use transifex.com's translation method like `Stylus` extension ❓	
[github.com/openstyles/stylus/#contributing](https://github.com/openstyles/stylus/#contributing#:~:text=You%20can%20help%20us%20translate%20the%20extension%20on%20Transifex.)

If you can use the service of `transifex.com` for 🆓, I think it is more convenient, 
and it also has automated function:  
When there is a new translation string, 📡📧🔔 it can automatically push email notification.
![209_12022158](https://user-images.githubusercontent.com/10995302/92959642-c1b38800-f49e-11ea-9e47-d04504a9cbda.png)

　　
</details>

　　
---
---

2. # ⚡ Improve outdated/invalid prompt/warning

<details>
<summary>Details</summary>

`https://greasyfork.org/scripts/by-site/{selectdomain}`
`https://greasyfork.org/scripts/by-site/{domain}`

It should not be warned by error.

![209_12022955](https://user-images.githubusercontent.com/10995302/92960226-d9d7d700-f49f-11ea-9d75-a502100372e9.png)
Because see at:  [ContextSearch-web-ext#template-parameters](https://github.com/ssborbis/ContextSearch-web-ext#template-parameters)

　　
</details>

　　
---
---

3. # 📖 Add the help document/tooltip 🌟

<details>
<summary>Details</summary>

`/options.html#advanced ` add mouse-hover show details `tooltip`
![209_12032857](https://user-images.githubusercontent.com/10995302/92965286-1b6c8000-f4a8-11ea-8897-32e1fc0c0fcd.png)

For example: 
https://github.com/ssborbis/ContextSearch-web-ext/issues/278#issuecomment-691261721

strongly recommended that you can add a small help document in multiple places on the option page, especially for options that are related to each other between different option pages, especially for documentation assistance.
You add this, just write the most difficult ones and the different options related to each other first,
The content of other documents will be written slowly when there is time in the future.

for example: 

![209_12034728](https://user-images.githubusercontent.com/10995302/92966764-b2d2d280-f4aa-11ea-9fc9-6533e5d62e7c.png)

hotkeys ➰ |enable Hotkey➰ | allowHotkeysWithoutMenu➰
:---: |--- |--- |
 `/options.html#engines` ➰ | `/options.html#quickmenu`➰  | `/options.html#advanced`➰

## How to achieve ?

It is best to use screenshots to illustrate, you will understand at a glance.

⚓Link anchor to [ContextSearch-web-ext/wiki](https://github.com/ssborbis/ContextSearch-web-ext/wiki)

Or just like [Selection Search 👇](https://chrome.google.com/webstore/detail/gipnlpdeieaidmmeaichnddnmjmcakoe)
It is hidden by default, and clicking it to expand to view the help document tips.

![1111](https://user-images.githubusercontent.com/10995302/92964206-4d7ce280-f4a6-11ea-80a5-167513f9f419.gif)

or Link anchor to https://github.com/ssborbis/ContextSearch-web-ext/wiki

　　
</details>

　　
---
---

4. ## (&🔠) 　If it is easy, optimize the (&🔠) problem 

> This is not a big problem, if it is not easy to fix, then please ignore it.

<details>
<summary>Details</summary>

Anywhere on ❖Windows, if the name of the menu item contain `(&🔠)`, it can use this single letter hotkey.

For example: name attach `(&D)` , then It will be generated `(D)` in ContextMenu, at last, you can press `D` to open it.
![209_12025102](https://user-images.githubusercontent.com/10995302/92961998-d4c85700-f4a2-11ea-8fe9-5b30ce1d7890.png)

### Now the problem is coming on the `CS`, it is also displayed in non-ContextMenu places, which is very bad.

![209_12030005](https://user-images.githubusercontent.com/10995302/92962783-14dc0980-f4a4-11ea-89a1-a7b6086522b7.png)

So, is there an easy way to make it not display except ContextMenu ❓	
If not, 👓ignore this little problem 🤦🙈

</details>

**Comment by dnknn** [comment]
update

**Comment by ssborbis** [comment]
> Is it possible to use transifex.com's translation method like Stylus extension ❓
github.com/openstyles/stylus/#contributing

$139 / month? Not likely as this add-on has earned me exactly zero dollars.

> ⚡ Improve outdated/invalid prompt/warning

Yeah, that's an old warning. It's due for retirement.

> Add the help document/tooltip 

Ok, I'll give a brief description, but I won't bother using localized messages.

**Comment by dnknn** [comment]
> $139 / month? Not likely as this add-on has earned me exactly zero dollars.
> 

I don't know how to use, but it should be free to basic use , look again.

**Comment by ssborbis** [comment]
changes 2 and 3 are in the repo

**Comment by ssborbis** [comment]
For 4, what about appending the hotkey to the context menu item as (&*hotkey*)

Google -> hotkey `g` becomes 
Google **(G)**

**Comment by ssborbis** [comment]
Of course, on windows it will cycle through all menu items starting with G also

**Comment by ssborbis** [comment]
For 1, if you want a localized translation, you can edit a copy of [messages.json](https://github.com/ssborbis/ContextSearch-web-ext/blob/native-app-support/src/_locales/en/messages.json) and upload it here and I'll put it into the proper location OR add it to the repo if you're familiar with how to submit changes.

**Comment by dnknn** [comment]
Thank you so much for your warm reply !
