### ISSUE TITLE
Can add hotkeys to folders ?

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#285]
![055825](https://user-images.githubusercontent.com/10995302/93269527-b71c2a00-f7e1-11ea-975a-779a57752ddb.png)

`/options.html#engines` for  folders 

- ## 💥 Current issue:   　　Could not add hotkey.

- ## ❥ Expected behavior: 　　Can also.
 　　 　　Because the folder hotkey is also very useful ,and it will be very convenient.

**Comment by ssborbis** [comment]
That function was never implemented, but I can look into it.

**Comment by ssborbis** [comment]
update in the repo for testing

**Comment by dnknn** [comment]
nice, Thanks ssborbis

**Comment by dnknn** [comment]
@ssborbis   I tested it and it worked perfectly.

Then, is it necessary to support  👇

Here should also be increased synchronously 


`/options.html#quickmenu#:~:text=Search Actions
`

![209_16171109](https://user-images.githubusercontent.com/10995302/93317153-b4e8b880-f83f-11ea-9980-24a4ca0a1d33.png)

![Uploading 209_16171152.png…]()


> It doesn't matter if it is not easy.

**Comment by ssborbis** [comment]
Yep, I'll add it.

**Comment by dnknn** [comment]
good! Thanks♪(･ω･)ﾉ
