### ISSUE TITLE
Change background-color of folder in Quick-Menu

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#286]
Hello there, ... thank you for this wonderful addon! :-)

Is there a way to change the background-color of the folders in the Quick-Menu. Currently it is yellow. 

Maybe via "Apply custom CSS styling to menus"?

Best greetings!
Thomas

**Comment by ssborbis** [comment]
Yep, you can change it in User Styles

Add this and enable `Apply custom CSS styling to menus`
```
.tile[data-type="folder"] {
    background-color:red;
}
```

Change `red` to whatever you want

**Comment by ThomasSeeker** [comment]
Ah, wonderful! ... that did the trick! :-)

I also added: 

`.tile:hover {background-color:var(--hover);}`

So the background while hovering over it comes back. (It disappeared after changing the color.)

Wonderful!

Thank you very much @ssborbis!

**Comment by sojusnik** [comment]
Can somebody share the CSS of a folder, that is shown as `inline`, see `SE` in the following picture?
![grafik](https://user-images.githubusercontent.com/1245718/146637376-c830f87f-b074-4744-ba0c-901aad1dc2e0.png)

```
.tile[data-type="folder"] {
    background-color:red;
}
```
only changes the color of the folders at the bottom.
