### ISSUE TITLE
CSS for removing info-box in the toolbar-menu

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#288]
Hey guys, 

is there an easy way with css to remove the info-box in the toolbar-menu just below the search-field (which tells me, which entry I am currently hovering over)?

I guess it could probably be done with:

`identifier {display:none!important;}`

Is there a list somewhere, where I can see all the names of all the elements?

**Comment by ssborbis** [comment]
```
#titleBar {
    display:none;
}
```
should do it

**Comment by ssborbis** [comment]
> Is there a list somewhere, where I can see all the names of all the elements?

You can browse the DOM in Firefox from CTRL+SHIFT+i 

It's a bit harder to inspect the Toolbar menu than the Quick Menu or Sidebar Menu, but they're very similar.  You can also browse [quickmenu.css](https://github.com/ssborbis/ContextSearch-web-ext/blob/native-app-support/src/quickmenu.css) where most of the menu styling is.

**Comment by ThomasSeeker** [comment]
Ah thank you very much!

`#titleBar {
    display:none;
}`

Works great!

And thanks to the quickmenu.css I also manged to change a couple other things!

The only thing left: I would like to use the maximum possible size for the toolbar-menu.
I tried:

**Comment by ThomasSeeker** [comment]
Ah thank you very much!

`#titleBar { display:none; }`  ...  works great!

And thanks to the quickmenu.css I also manged to change a couple other things!

The only thing left: I would like to use the maximum possible size for the toolbar-menu. Increasing its height would give me a couple more lines.

I tried:
`HTML, BODY {height:1000px;}`

But that works only to make it smaller. I guess the limiting factor here is some firefox-css. But I couldn't find it with the DOM Inspector. 

Can you help me with this too?

**Comment by ssborbis** [comment]
> The only thing left: I would like to use the maximum possible size for the toolbar-menu. Increasing its height would give me a couple more lines.

That maximum is set by the browser and can't be changed via CSS.

**Comment by ThomasSeeker** [comment]
> That maximum is set by the browser and can't be changed via CSS.

Shouldn't that be possible to change via the userChrome.css in FF?

Also, I have another addon running for bookmarks, which opens a very similar drop-down menu ... but this uses the whole screen-height.

**Comment by ssborbis** [comment]
> Shouldn't that be possible to change via the userChrome.css in FF?

Maybe. I haven't messed with userChrome.css much

> Also, I have another addon running for bookmarks, which opens a very similar drop-down menu ... but this uses the whole screen-height.

What's the addon? Is it using a popup window or opening in the browser menu? The documentation says the limit is 600px by 800px. I don't set any window size limits in this addon. It's always been limited by the browser.

**Comment by ThomasSeeker** [comment]
> What's the addon?

I'm sorry, I have to correct. It is not an addon. It is the original FF-Bookmark-Toolbar-Button. It opens a list of my bookmarks in a drop-down window from the toolbar. And this window reaches all the way to the bottom. ...
