### ISSUE TITLE
[Feature-Request] Quick-Menu Closing-Behaviour 

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#289]
I would like the closing of the Quick-Menu to behave exactly like the closing of the regular FF-context-menu. I.E. it should close on a left click outside of the menu-area (which it does already) but without following links (in the case of that left-click happening on a link).

That would be great!

PS: Many thanks again for this wonderful addon! I am very new to it, but I am using it already all the time! Really great little helper! :-)

**Comment by ssborbis** [comment]
Done

**Comment by ThomasSeeker** [comment]
Wow! That was fast!

Looking forward to the next update then!   :-)

**Comment by ssborbis** [comment]
I'll post here when a new release is out

**Comment by ssborbis** [comment]
v1.27 live on AMO. ChromeStore in a day or 2

**Comment by ThomasSeeker** [comment]
Ah wonderful! ... :-)

Thank you very much!

I wish you a great weekend!
Quick-Menu rocks!

**Comment by ThomasSeeker** [comment]
Playing around and enjoying the new behaviour I also tried the youtube-page. And here it seems, that the links still get opened.

Example: https://www.youtube.com/watch?v=1HPCn3dOofk

Strange!

**Comment by ssborbis** [comment]
Just on the youtube page or elsewhere?

**Comment by ThomasSeeker** [comment]
On Facebook too, and also on the google-results-page.
But it does work on some pages though.

**Comment by ssborbis** [comment]
Ah, I only accounted for anchor links. All those sites are using click events. I have a fix in mind. I'll issue a hotfix soon.

**Comment by ssborbis** [comment]
Hotfix going up now to AMO. You'll need to enable `quickMenuPreventPageClicks` under the Advanced tab

`

**Comment by ThomasSeeker** [comment]
Ahh ... that does the trick!
Wonderful!
Thank you very much!

**Comment by ssborbis** [comment]
Sweet. I'll close this one out.

**Comment by ssborbis** [comment]
Just a heads up, there's a bug when using this option + opening the quick menu from an iframe. The no-click div gets left behind after closing the quick menu preventing mouse events in the iframe. . If you've been on some sites and lost your mouse after closing the qm, that's most likely the cause. I have a fix that I'm testing. I'll probably get a new release out in the next couple days.
