### ISSUE TITLE
quick menu columns

### ISSUE THREAD

**Issue by sign-in-smth** [ssborbis/ContextSearch-web-ext#29]
hey man, hows everything )

could you maybe take a look at this address
http://www.vicator.com/
noticed old issue with empty column popping up in quickmenu - but no such problem at other websites.
https://i.imgur.com/PlSKgJr.jpg

thanks!

**Comment by hg42** [comment]
works for me (on Linux) with 10 columns (does it matter)?
Perhaps you are using some userstyles or scripts? or userchrome.css or usercontent.css?

**Comment by sign-in-smth** [comment]
i have userchrome.css that only defines in what order different add-ons context menu entries should be. there's nothing else in it.

**Comment by hg42** [comment]
oh, nice, may be I could use that, too? could you send the file to my email address (on github)?

**Comment by sign-in-smth** [comment]
i think i just used a guide like this, it depends on extensions you have installed
https://www.reddit.com/r/firefox/comments/7dvtw0/guide_how_to_edit_your_context_menu/

**Comment by ssborbis** [comment]
Yep, I'm seeing it too. Wow that is strange. Since moving the quickmenu to it's own iframe, I thought all issues with a website's page styling would be gone. I'll look into it.

**Comment by ssborbis** [comment]
Looks like the page is overwriting min-width and max-width on the iframe. I'll see if I can make those more explicit when building the iframe element.

**Comment by ssborbis** [comment]
Added to inject.css

`#quickMenuElement {
	unset: all;
}`

That should take care of most styling conflicts.

**Comment by ssborbis** [comment]
v1.4.7.1 up

**Comment by sign-in-smth** [comment]
thank you sir, just installed the update, problem is gone -)
