### ISSUE TITLE
Feature Request: Exporting ContextSearch search engines to main Firefox search.json.mozlz4

### ISSUE THREAD

**Issue by CorpusBava** [ssborbis/ContextSearch-web-ext#290]
Would this be possible?  Thanks

**Comment by ssborbis** [comment]
Perhaps, but not directly without an additional native app.

Just thinking out loud... the process would need to be something like:

1. **click a button to browse / import search.json.mozlz4**
2. decode search.json.mozlz4 to json
3. add ContextSearch engines
4. re-encode to mozlz4
5. **prompt user to Download the newly created file**
6. **user moves new search.json.mozlz4 file to the Firefox profile directory**

Not a one-click solution, but if I had the encoder it should be possible ( as long as there are no hash checks to invalidate a modified file )

**Comment by CorpusBava** [comment]
> 
> 
> Perhaps, but not directly without an additional native app.
> 
> Just thinking out loud... the process would need to be something like:
> 
>     1. **click a button to browse / import search.json.mozlz4**
> 
>     2. decode search.json.mozlz4 to json
> 
>     3. add ContextSearch engines
> 
>     4. re-encode to mozlz4
> 
>     5. **prompt user to Download the newly created file**
> 
>     6. **user moves new search.json.mozlz4 file to the Firefox profile directory**
> 
> 
> Not a one-click solution, but if I had the encoder it should be possible ( as long as there are no hash checks to invalidate a modified file )

Do you know of any conversion utilities for FF to do this?  I find ContextSearch very useful and wouldn't mind having to do this manually for the time being just to consolidate all my ContexSearch search engines into my main browser's search engines..  thx

**Comment by ssborbis** [comment]
There are some tools out there for node, python, etc that can compress / decompress mozlz4 but I haven't used them. I'm looking into a javascript solution. If I come up with anything I'll post here.

**Comment by ssborbis** [comment]
Oh, I didn't ask.. are you familiar with the `Install to Firefox One-Click Search Engines` button in CS Options -> Search Engines -> [ engine ]?

![Untitled](https://user-images.githubusercontent.com/24310997/94772788-05076500-0380-11eb-99a4-dd48d505230d.png)

You can't bulk export them to the firefox search bar, but if you only have a few it's not so bad. There's an additional step since FF70-something to add them, but you should get a popup window explaining how.

**Comment by CorpusBava** [comment]
Thanks.  I'll check it out.  Yeah, I don't typically add a lot of search engines frequently but I like the conveniences of just right-clicking on a web site's search field and just adding it easily, which your extension does the most reliably, I feel.  I notice some websites can be stubborn about allowing the creation of custom search engines but ContextSearch has worked best for me..

**Comment by ssborbis** [comment]
I've added an option to copy the search.json.mozlz4 file, add CS engines, and export into a new search.json.mozlz4, effectively putting CS engines into the Firefox search bar. It also serves up a renamed copy of the original search.json.mozlz4 for safe keeping. How long it works depends on Mozilla keeping the same file format, but it is working for now.

It is relatively untested, but it's there ( in the repo ) and will be in the next release.

**Comment by CorpusBava** [comment]
> 
> 
> I've added an option to copy the search.json.mozlz4 file, add CS engines, and export into a new search.json.mozlz4, effectively putting CS engines into the Firefox search bar. It also serves up a renamed copy of the original search.json.mozlz4 for safe keeping. How long it works depends on Mozilla keeping the same file format, but it is working for now.
> 
> It is relatively untested, but it's there ( in the repo ) and will be in the next release.

great!  Makes things a lot more convenient.  Will test it ASAP.  Thanks.

**Comment by ssborbis** [comment]
v1.28 is up
