### ISSUE TITLE
can support to custom `folder` icon  ?

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#291]
Add custom icon function to `folder` of `/options.html#engines` .

Currently, it is not possible to customize `folder` icon, resulting in low recognition.

**Comment by ssborbis** [comment]
Most menus show the folder with a text label. Are you talking about the Last Used tool being a generic icon?

**Comment by dnknn** [comment]
> Most menus show the folder with a text label.

Yes, yes, but the recognition is definitely not as high as the icon, right?

![2010_10143322](https://user-images.githubusercontent.com/10995302/95647955-43cab700-0b06-11eb-8585-78ca98c7537b.png)


> Are you talking about the Last Used tool being a generic icon?

no, no, If you choose custom icon, it should be displayed by default in various(all) places, ie: Toolbar 、Quick Menu、 Last Used .etc


If the user uses a custom folder icon display, Then the current `the folder with a text label` will be replaced by a custom icon to display.

So the solution: 
![2010_10144111](https://user-images.githubusercontent.com/10995302/95648016-ade35c00-0b06-11eb-9c7d-768577ff5ba4.png)
The user can customize the folder icon, and can also **switch to** the current **default** form again separately (of course, use the default, keep the previous custom icon data option , so, user can switch to custom icon again)


I'm just talking about it, you decide it yourself!

**Comment by ssborbis** [comment]
The functionality has been added to the repo, but there's no UI yet. I'll look into it after the next release.

**Comment by dnknn** [comment]
Ok, when you push the new version on the store, I will test it again.

**Comment by dnknn** [comment]
I downloaded the latest repo and found that I can't use it directly, right?

**Comment by ssborbis** [comment]
> I downloaded the latest repo and found that I can't use it directly, right?

Nope, no UI yet. I'll get into it after the next release.

**Comment by ssborbis** [comment]
If you want to set an icon to a folder now, without the UI you might trying something like this in the console from the options page

```
findNode(userOptions.nodeTree, n => n.title === "Your Folder Name").icon = "https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/firefox/files/2017/12/firefox-logo-300x310.png";
saveOptions();
```

**Comment by dnknn** [comment]
This is more complicated, I don’t understand. It’s okay to take your time, I will test it after you add the UI.

**Comment by ssborbis** [comment]
added IconURI field in the edit form for folders
folders with an icon uri display icons instead of folder titles in menus

**Comment by dnknn** [comment]
> added IconURI field in the edit form

Thanks again, I saw this functional UI, a simple test found that it worked perfectly!
