### ISSUE TITLE
Bug: Found that an edit box will trigger  hotkey

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#294]
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#hotkeys#✅:~:text=Enable hotkeys`
![2010_27153443](https://user-images.githubusercontent.com/10995302/97270330-f1a9c580-1869-11eb-9658-b02b60bd7546.png)

Bug url: https://chromestatus.com/features

![image](https://user-images.githubusercontent.com/10995302/97270462-2cabf900-186a-11eb-9081-0ddcb1e2f69b.png)

**Comment by ssborbis** [comment]
got it. thanks

**Comment by dnknn** [comment]
> got it. thanks

^_^ :)

**Comment by ssborbis** [comment]
Needed more work than I initially thought due to new HTML5 input types, but I'll have a release out in the next couple days.

**Comment by dnknn** [comment]
> but I'll have a release out in the next couple days.

Thank you! It doesn’t matter at all, take your time, don’t worry!

**Comment by ssborbis** [comment]
should be fixed in v1.28
