### ISSUE TITLE
Suggest unification logo-icon

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#295]
chrome://extensions/?id=ddippghibegbgpjcaaijbacfhjjeafjh 👇
![image](https://user-images.githubusercontent.com/10995302/97461870-20629180-1979-11eb-911e-330f6f1ede61.png)
The icon of the toolbar is 👇
![image](https://user-images.githubusercontent.com/10995302/97462063-5273f380-1979-11eb-95e6-50d24b5b713a.png)

Suggest unification use ![image](https://user-images.githubusercontent.com/10995302/97462265-818a6500-1979-11eb-8c1c-f2fa57a94743.png)

This is not a big problem, if disagree, can close this issue directly

**Comment by ssborbis** [comment]
Mostly done now in the repo

**Comment by dnknn** [comment]
> Mostly done now in the repo

Good, Done! so close this.
