### ISSUE TITLE
Feature request : holding `Ctrl` to multi-select-list for the engines page

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#296]
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#engines`

For hotkey of multi-select-list/item : Normally it is holding `Ctrl`/ `Shift` / `Ctrl+Shift` , right?
-  Current: we only can use `Shift` , but not `Ctrl`.   not supporting `Ctrl+` is a big disadvantage.

- Below is the gif demo:

>  For Windows file manager and Chrome tab bar, they also support to pressing `Ctrl+Shift` , it without interrupting the current selected state;  but we can don’t to support `Ctrl+Shift`.

<details>
<summary>Details</summary>

- ## multi-select-list/item for ❖Windows file manager
![demo1](https://user-images.githubusercontent.com/10995302/98242092-e14ec480-1fa6-11eb-8230-57e45cb81c72.gif)

　　
- ## multi-select-list/item for ֎Chrome tab-bar (highlight multiple tabs)
![demo2](https://user-images.githubusercontent.com/10995302/98242088-df850100-1fa6-11eb-8f95-0e04a6d741dd.gif)

　　
　　
![multiple-tabs-seletecd](https://user-images.githubusercontent.com/10995302/86508137-4a170c00-be10-11ea-9512-a0b1c6f4120b.gif)

</details>

**Comment by ssborbis** [comment]
It will need testing, but the basic functions are in the repo now

**Comment by dnknn** [comment]
@ssborbis 

> It will need testing

- I tested it in a short time and it seems to work well.

- [Here is a similar script code for `Shift`](https://greasyfork.org/en/scripts/22587), you can take a look, but it is about `checkboxes`, so it does not need to use `Ctrl` key.
