### ISSUE TITLE
Search Engines Edits Not Saving

### ISSUE THREAD

**Issue by ChaosOrdeal** [ssborbis/ContextSearch-web-ext#298]
I have edited a Search Engine multiple times and saved it (it appears), and it works as intended, but seems to eventually revert to previous, unedited functionality.  When I go to edit it again, the changes have reverted.

**Comment by ssborbis** [comment]
What changes are you making to the search engine that won't save? Search form? Icon? 

Sometimes that can happen if you have multiple tabs open along with the tab for CS options. I have seen occasions where a tab updates the config file, causing some settings to revert.

Also, are you seeing any errors in the console for the config page? (assuming Firefox, CTRL+Shift+K to open)

**Comment by ssborbis** [comment]
I uploaded some fixes to the repo that may address the problems you've been having. Apparently, copied / new engines weren't being saved after creation causing form data to be lost.

**Comment by ssborbis** [comment]
should be fixed in v1.28
