### ISSUE TITLE
Use encodeURIComponent to escape &'s (ampersands)

### ISSUE THREAD

**Issue by vzjrz** [ssborbis/ContextSearch-web-ext#3]
Trying to select and search `Test one two & three` doesn't correctly search for the whole thing. It should be encoded to: `Test%20one%20two%20%26%20three`

**Comment by ssborbis** [comment]
Try [rc7](https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/1.0.1rc6)

**Comment by ssborbis** [comment]
This seems to be working now.  Thanks for the feedback

[rc8](https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/1.0.1rc8)
