### ISSUE TITLE
multi searches in a single template

### ISSUE THREAD

**Issue by itge13** [ssborbis/ContextSearch-web-ext#300]
How can I search with multiple enignes with one click?
E.g. one click opens two tabs for:
https://www.google.com/search?q={searchTerms}
https://www.bing.com/search?q={searchTerms}
?

**Comment by ssborbis** [comment]
1. Create a folder and move / copy the engines there and search a whole folder at once
-or-
2. use a well-formed array as the template
`["https://www.google.com/search?q={searchTerms}","https://www.bing.com/search?q={searchTerms}{encoding=gbk}"]`

If an engine in the array uses a different encoding than is saved in the from, you can override individual engine encoding by adding `{encoding=enc_type}` as shown in the example. This method is also limited to GET engines.

**Comment by itge13** [comment]
I can't do 1 because I loose focus if I activate shortcuts and with a click on the folder I only get a level down? Or am I missing something and there is a possiblity to search it all at once without a folder shortcut?:)

2 works. thanks a lot once mor:)

**Comment by ssborbis** [comment]
> am I missing something and there is a possiblity to search it all at once without a folder shortcut

I think middle-mouse button is the default to search every engine in a folder at once. You can change the behaviour under CS Options -> Search Actions

![Untitled](https://user-images.githubusercontent.com/24310997/99731959-3cdb8080-2a84-11eb-97a1-ab1b708ea613.png)

**Comment by ssborbis** [comment]
Oh, I wasn't accounting for the context menu. Searching a folder can only be used in CS menus (quick, toolbar, sidebar, page tiles, etc) not the browser's context menu

**Comment by ssborbis** [comment]
Let me know if you **ARE** looking to search whole folders from the context menu. I just thought of a solution if you're interested

**Comment by itge13** [comment]
> I think middle-mouse button is the default to search every engine in a folder at once. You can change the behaviour under CS Options -> Search Actions

ah sorry din't think about that. it works.
I never use the context menu so everything is perfect now! Thank you a lot!!
