### ISSUE TITLE
The "TEMPlATE" of the new engine is reset

### ISSUE THREAD

**Issue by liraqb** [ssborbis/ContextSearch-web-ext#301]
For the new engine generated by "Copy as New Engine" before, "TEMPlATE" automatically becomes the text of the original engine. If I modify the "TEMPlATE" of the new engine, the "TEMPlATE" will be restored after restarting the browser.

The affected engines found so far have "TEMPlATE" content similar to `https://www.google.com/search?q=site:youtube.com+{searchTerms}`. I usually use "Copy as New Engine", then change "youtube.com" to "fackbook.com" and add a new engine like this.

Hopefully the “TEMPlATE” for the new engine hasn’t really been reset, and I don’t want to modify them one by one.

**Comment by ssborbis** [comment]
can you walk me through, step by step?

I tried
1. Click `Add`
2. type name "test"
3. enter `https://www.google.com/search?q=site:youtube.com+{searchTerms}` as template
4. click `Save`
5. right-click "test" -> Copy -> As New Engine
6. accept name "test copy"
7. edit "test copy" template to `https://www.google.com/search?q=site:facebook.com+{searchTerms}`
8. click `Save`

This seems to save the template properly.

I did notice, however, that the Copy button at the bottom of the form page does not work correctly. I'll look into that.

**Comment by liraqb** [comment]
I tested it. This example has no problem.

The version I use is 1.27.5 Chrome Store version. I exported the backup file and tested it with 1.28 Github version, this bug has been fixed, and the "TEMPlATE" of the new engine can be modified, but it is not automatically restored to the previous text, it is still the text of the original engine.

There are only 3 new engines affected, one of which is not `https://www.google.com/search?q=site:`, well, the bug has nothing to do with this text. I modified these engines.

**Comment by ssborbis** [comment]
Hmm... Another user mentioned something about not being able to save template changes, but I didn't hear back from them. If you come across the problem again, send me your config file and walk me through which ones aren't saving.

**Comment by ssborbis** [comment]
Ok, I'm seeing some of the issues here. When a copy is made, it doesn't immediately save the new engine ( no green checkmark in the upper-right of the options page to indicate saving ). I'll update the repo to day with some fixes.

**Comment by ssborbis** [comment]
should be fixed in v1.28
