### ISSUE TITLE
Option to keep the menu open if middle-click is used to open tabs in background

### ISSUE THREAD

**Issue by Ede123** [ssborbis/ContextSearch-web-ext#308]
Context Search X had a very nice functionality that made it keep the context menu open when middle-clicking search engines, so the same term could be searched with multiple search engines at once, without having to re-open the context menu (possibly it interfaced with [Stay-Open Menu](http://forums.mozillazine.org/viewtopic.php?t=633732) but I don't fully remember that part).

This was really helpful and it would be great if ContextSearch web-ext would support it as well.

Unfortunately the referenced extension isn't around anymore since it was impossible to implement properly with webextensions and the attempts of the original author to get it implemented in Firefox core seem to have failed (except for the bookmark menu) as highlighted in the linked thread.

**Comment by ssborbis** [comment]
Context menu, no
not possible as far as I'm aware under the new webextensions API. The browser decides when to close the context menu.

Quick Menu, yes. 
You can keep the menu open after performing a search using the option `Open in Background Tab ( Keep Menu Open )`

**Comment by Ede123** [comment]
Thanks!

I was afraid you'd say something like that wrt context menu... I guess I finally have to make my peace with the fact that the webextension API is too limited to make great native implementations.

The quick menu does indeed exactly what I want, maybe I can get used to it at some point. I have to admit I switched just yesterday from FF56 (🤐) and have a lot of muscle memory in regards to what Context Search X offered.
