### ISSUE TITLE
Make top-level context menu entry clickable?

### ISSUE THREAD

**Issue by Ede123** [ssborbis/ContextSearch-web-ext#310]
Would it be possible to make the top-level context menu of ContextSearch clickable and do one of the following (possibly configurable via preferences):
* Search with the first search engine configured, i.e. Google in case of the screenshot below
* Search with a user-configurable search engine
* Search with the last search engine used, e.g. if I had performed a search on dict.cc before, search with dict.cc again when clicking the top-level entry

Of course there are bonus points for adjusting search text and icon accordingly. ;-)

![grafik](https://user-images.githubusercontent.com/904570/107150829-0c5b0280-6960-11eb-82ec-34db90826e61.png)

**Comment by ssborbis** [comment]
Unfortunately, no. The webextensions API only allows one action on menu items with sub-menus; open sub-menu. There's no developer access to that action and no event triggered when a "folder" item is clicked.

There are other tools in this addon that can help you out a bit though.

> Search with a user-configurable search engine

If you enable "hotkeys" and set the hotkey for google to `g` for instance, you can highlight word and press `g` to perform a search, bypassing the menu altogether.

> Search with the last search engine used, e.g. if I had performed a search on dict.cc before, search with dict.cc again when clicking the top-level entry

In the context menu options, you can enable a list of recently used engines. If you only want access to the last engine, you can set the limit to 1 and do not enable as a separate folder. This will display the last used engine at the very top of the context menu.

**Comment by Ede123** [comment]
Thanks, another one of these... 😭 

I have to admit I'm not a frequent user of hotkeys (don't really know myself why) but I'll think about it.

As for limiting the number, that won't help me, as I often user different search engines and by limiting it to one I'd have no way to change it quickly anymore (unless combining it with the quick menu or similar), but that would become even more confusing. I might just end up using the quick menu exclusively after all once I get used to it (but there's a lot of muscle memory involved and I constantly forget to do so).

Anyway thanks for the great help, keep up the good work!
