### ISSUE TITLE
I don't want Quick Menu opens at single click

### ISSUE THREAD

**Issue by gabri25ele** [ssborbis/ContextSearch-web-ext#312]
I have this setting

![sshot-1](https://user-images.githubusercontent.com/33927879/108050414-d8f83200-7049-11eb-900e-ca6dcef94219.png)

I want the Quick Menu only holding right click, instead it always opens as I click with the right button, this creates interference with other extensions ... how can I make it open only and only with the button pressed for a few seconds?

**Comment by ssborbis** [comment]
What browser / OS are you using? Are you only getting the Quick menu or are you also getting the default context menu?
Does it open when you press the mouse button down or when you release it?

**Comment by ssborbis** [comment]
You may also try raising this setting. Your "click" might be slow compared to the default timer setting

![Untitled](https://user-images.githubusercontent.com/24310997/108053950-aaf7fb00-7013-11eb-85f5-85b4b789478d.png)

**Comment by gabri25ele** [comment]
> What browser / OS are you using? 

Firefox + Windows 10

> Does it open when you press the mouse button down or when you release it?

it opens when I just click on (right) mouse

> (edit) Do you have any other opening methods enabled ( Simple click ? )

simple click?
where is this method?

anyway I had the **quickMenuHoldTimeout** empty... I don't know why... I inserted a value and now doesn't seem to interfere with the context menu

**Comment by ssborbis** [comment]
Good deal

**Comment by gabri25ele** [comment]
you have more items compared to me?
![sshot-2](https://user-images.githubusercontent.com/33927879/108055292-1364cd80-7050-11eb-95e5-f75c766e10b5.png)

a more recent version?

**Comment by ssborbis** [comment]
v1.29
I'm using the latest code in the repo

**Comment by gabri25ele** [comment]
I hope it will be available soon on addons.mozilla.org!

**Comment by ssborbis** [comment]
You can always set `xpinstall.signatures.required = false` in about:config and install from the source.

[contextsearch_web-ext-1.29.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/5988254/contextsearch_web-ext-1.29.zip)

**Comment by gabri25ele** [comment]
> You can always set `xpinstall.signatures.required = false` in about:config and install from the source.
> 
> [contextsearch_web-ext-1.29.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/5988254/contextsearch_web-ext-1.29.zip)
> 
> (edit) You have to rename it .xpi first, then drag it into the URL bar

always tells me "**not verified**"

**Comment by ssborbis** [comment]
It's not, but do you have the option to add it anyway after changing the about:config value?

**Comment by gabri25ele** [comment]
I have xpinstall.signatures.required = false
but firefox has not allowed unverified extensions for some time ... unless you use a nightly...
should it be, or not?

**Comment by ssborbis** [comment]
They install for me, and I'm using the regular FF version 85.0 (not Nightly) but I also enabled 'debugging'. Maybe that's making a difference. I'm also on a very old profile, so who knows what old settings are in there.

`about:debugging` -> Enable?

**Comment by gabri25ele** [comment]
> `about:debugging` -> Enable?

I don't know about:debugging
what can I enable there?
(I see "USB" and "network path")

**Comment by ssborbis** [comment]
I just tried a new profile and simply setting `xpinstall.signatures.required = false` allows me to install unverified .xpi files. I don't know why it's working for me and not working for you. You may just have to wait for the next release.

**Comment by gabri25ele** [comment]
if you want to try one copy of "my" firefox, portable, clean profile, you can download it from here
http://www.mediafire.com/file/i3rpwe2882imf9u/portable.zip/file

It's strange to me that you install an unsigned extension, it hasn't been possible for years. 
Even the famous "chrome store foxified" extension doesn't work anymore. 
What would I give to know how your firefox installs them!

but, what is the story of about:debugging?

**Comment by ssborbis** [comment]
The xpi in your portable.zip didn't work with that profile, but the one I built did.

[contextsearch_web-ext-1.29.xpi.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/6005424/contextsearch_web-ext-1.29.xpi.zip)

**Comment by gabri25ele** [comment]
firefox tells me "not verified" (again)
the mystery deepens

**Comment by ssborbis** [comment]
Yeah, I dunno. Here, this should be signed. Latest code

[contextsearch_web_ext-1.29pre1-an+fx.xpi.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/6009359/contextsearch_web_ext-1.29pre1-an%2Bfx.xpi.zip)

**Comment by gabri25ele** [comment]
yes OK, now works, thank you
but... 
for curiosity, is it possible to sign it also for us normal users or just developers??

**Comment by gabri25ele** [comment]
wait... disaster!
One time update I have quick menu with inverted rows:

![Immagine](https://user-images.githubusercontent.com/33927879/108507566-cfc1cc00-72ba-11eb-8418-52f407ef8c06.png)

no, no, I want search engines up and tools down

![Immagine2](https://user-images.githubusercontent.com/33927879/108507626-e9631380-72ba-11eb-914e-0bc43f6cb2d2.png)

I didn't find how to put this setting back in the new version.
😫

**Comment by ssborbis** [comment]
Here's the setting. Very odd that it would change

![Screenshot_2021-02-19_08-09-53](https://user-images.githubusercontent.com/24310997/108514842-ff0c1500-7289-11eb-91cc-bae78b287421.png)

**Comment by ssborbis** [comment]
> for curiosity, is it possible to sign it also for us normal users or just developers??

Only I can sign this addon. It requires a private key. I guess you could install the developer edition and build your own xpi. I still have no idea why I can install unsigned and you can't.

**Comment by gabri25ele** [comment]
sorry ssborbis, ma not works in this new update

I have this option:

![sshot-1](https://user-images.githubusercontent.com/33927879/108524099-f689fd80-72ce-11eb-87f5-d894203568de.png)

but no changes

![sshot-2](https://user-images.githubusercontent.com/33927879/108524133-01dd2900-72cf-11eb-814d-1509f09b9b28.png)

**Comment by ssborbis** [comment]
set `Position` to `bottom`

**Comment by gabri25ele** [comment]
> 
> 
> set `Position` to `bottom`

no changes

![sshot-1](https://user-images.githubusercontent.com/33927879/108588414-65139d80-7359-11eb-8312-f17baa6728eb.png)

![sshot-2](https://user-images.githubusercontent.com/33927879/108588417-680e8e00-7359-11eb-99ce-4801666b5c6b.png)

**Comment by ssborbis** [comment]
export your config and send it to me or zip it and post here

ssborbis@gmail.com

**Comment by gabri25ele** [comment]
[ContextSearchOptions.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/6014520/ContextSearchOptions.zip)

**Comment by ssborbis** [comment]
Ok, there were several bugs causing issues.

Your config was missing several values, mostly numbers, but other values were corrupted. I'm trying several old configs to see if that bug is fixed

The toolbar not moving to the bottom was a separate bug. 

You can try this. Hopefully, it will fix some of your bad values as well as the tools bar issue.

[contextsearch_web_ext-1.29pre2-an+fx.xpi.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/6014685/contextsearch_web_ext-1.29pre2-an%2Bfx.xpi.zip)

**Comment by ssborbis** [comment]
Better version in the repo. Loading it temporarily will fix some problems.

**Comment by gabri25ele** [comment]
> 
> 
> Better version in the repo. Loading it temporarily will fix some problems.

in fact something did not come back to me when I said... _"anyway I had the quickMenuHoldTimeout empty... I don't know why... I inserted a value and now doesn't seem to interfere with the context menu"_

When you say "Better version in the repo"... you mean in addons.mozilla.org? 
because the release page of github is empty (https://github.com/ssborbis/ContextSearch-web-ext/releases)

**Comment by ssborbis** [comment]
> When you say "Better version in the repo"... you mean in addons.mozilla.org?
because the release page of github is empty

I meant the source code. You can load it as a temporary addon from about:debugging -> This Firefox -> Load Temporary addon and browse to `src/manifest.json` in the unzipped source code.

It will go away when you restart FF, but some of the cleanup code will work as soon as you install it.

**Comment by ssborbis** [comment]
I'm closing out some older threads. I believe this issue has been taken care of, but if not, please reopen.
