### ISSUE TITLE
tools need to wrap

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#314]
tools need to wrap like the other icons, because if I have only a few columns (e.g. 3, which is nice for the sidebar), the tools get clipped

**Comment by ssborbis** [comment]
which tools? Do you have them set to display as a toolbar? They can be scrolled horizontally

**Comment by ssborbis** [comment]
looks like 

```css
#toolBar { white-space: normal; }
``` 
works

**Comment by ssborbis** [comment]
Keep an eye out for bugs, but new code should handle multi-row tools if you use that css

**Comment by hg42** [comment]
> which tools

the tool buttons in sidebar in my case

> can be scrolled horizontally

oh, didn't know that, but
* don't see how to scroll them in toolbar or sidebar
* scrolling may not work when dragging to the sidebar

> `#toolBar { white-space: normal; }`

nice, seems to work well.
Didn't know that white-space thing, interesting, thanks...
