### ISSUE TITLE
the toolbar menu doesn't work with many columns, width seems to be fixed?

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#315]
I planned to use a similar wide menu like in quickmenu, and started with 24:

Originally I wanted to use 99 columns, because I noticed for the quickmenu, that it will be cut down to the necessary columns.
But 99 columns is even worse :-)

![toolbar-menu-width](https://user-images.githubusercontent.com/4707597/109332372-4b44ef80-785e-11eb-8a85-407cede39e2a.gif)

**Comment by ssborbis** [comment]
I've been messing with that menu recently. I'll get a fix

**Comment by ssborbis** [comment]
Be aware, that window can only be so wide ( 800px maybe? ) so you'll get horizontal scrollbars if you set too many columns

**Comment by ssborbis** [comment]
I absolutely loath coding the browser_action window. There's no control over resizing. 

I tried a few things. Update in repo

**Comment by hg42** [comment]
> Be aware, that window can only be so wide ( 800px maybe? ) so you'll get horizontal scrollbars if you set too many columns

yes, I remember your comments on that, many months ago.
At least it worked with much more columns.
Though, the bigger buttons I get, because I increased icon size (in quickmenu!) for the dragging will reduce the columns when the size is limited pixel-wise.

Idea: I guess you can also detect a click on the toolbar button (without a menu). You could simply open a quickmenu at that position. This would probably also reduce the separate code you need now.

**Comment by hg42** [comment]
nice, the new code works perfectly (I'm on b8538e66)

**Comment by hg42** [comment]
btw. a minor thing:
could the menu be horizontally centered to the mouse? opening it to the left or right of the mouse results in longer distances.
Don't know if it's easy enough to add a "middle" case at least for wide menus?

![image](https://user-images.githubusercontent.com/4707597/109388825-c31c2400-7909-11eb-809c-e779b47a824c.png)

**Comment by ssborbis** [comment]
Nope, no control over that. It's all on the browser.

**Comment by hg42** [comment]
oh...I see, thanks...
that explains the same issue for several other extensions, that I placed at the left, they all reach out of the browser window.

**Comment by hg42** [comment]
> Nope, no control over that. It's all on the browser.

another reason for this if possible:
> Idea: I guess you can also detect a click on the toolbar button (without a menu). You could simply open a quickmenu at that position. This would probably also reduce the separate code you need now.
