### ISSUE TITLE
tool "Edit" allows only one drag

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#317]
if you enable Edit tool, it becomes blue and you can drag one item. After that you cannot rag another one.
The tool is still blue and you have to switch it off and on again to drag another

**Comment by ssborbis** [comment]
Got it, thanks

**Comment by ssborbis** [comment]
Fix in the repo

**Comment by hg42** [comment]
yes, works...nice...
You are quite fast. Awesome work.

I hope I don't bother you too much...
I'm just working my way back to the heart of the CS development and trying all the new features. I was conservative with updating for a long time, living on the edge at too many sides, trying not to risk such a useful tool.

E.g. I wasn't aware of that edit button, also not enabled in my tools, so I wondered, if the rearranging was gone. Luckily I found that tool, when looking for new tools.
