### ISSUE TITLE
after using the quickmenu the capture isn't released (EDIT: reason quickMenuPreventPageClicks)

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#318]
I noticed it, because I could only drag once on the same page.

In fact I cannot use links, input fields, or see the different cursors (e.g. beam), tooltips etc. 
I guess the mouse capture isn't released in some way.

https://user-images.githubusercontent.com/4707597/109389676-a550be00-790d-11eb-9a72-3e5d84761355.mp4

(sorry, the quick menu is opened too far away...only the input line is visible)

**Comment by hg42** [comment]
it's not related to dragging...
actually, if I disable dragging I still get this behavior.
I also wonder why the quickmenu doesn't close by ESC, I think I remember it did sometime before?

**Comment by hg42** [comment]
I'm on the way to find the commit...
at least in e565c8d9 the release worked (but not ESC, may be I imagined this?)

**Comment by hg42** [comment]
![image](https://user-images.githubusercontent.com/4707597/109390634-1d6db280-7913-11eb-8a8e-70062a43b16b.png)

**Comment by hg42** [comment]
not sure if it is "mouse capture", at least I can use firefox menu, also context menu on the page, and I have an extension to scroll the page with the middle button wich also works in this state.
But any kind of hovering events (or better: reactions to this) or clicks don't work. I have to reload the page to work again.

**Comment by hg42** [comment]
the capture is even active when opened qm with Ctrl-Alt-x
(btw. the hotkey is just what I needed, opening the quick menu without selecting text, nice, the toolbar menu becomes unemployed)

**Comment by hg42** [comment]
I tested on Chromium and it worked at first.
However
* I still used CS from the store, a "load unpacked" extension doesn't seem to replace the official one (for all pages, maybe reload would have helped?)
* exporting settings in firefox and importing them in chromium doesn't set all of them (but some of them? not sure).

The result of that excursion is:

**`quickMenuPreventPageClicks`**

I had it enabled at some point in firefox to test what it does.
What's the purpose of this setting?

Anyways, this blocks some things, which may be useful while the qm is open, but doesn't change when it closes.
The ESC to close the qm or even cancel the drag is also blocked by this.
Without it, the behavior is like expected (not sure what I loose? I expected to protect the page elements when closing the qm by clicking somewhere outside)

**Comment by hg42** [comment]
ok, I see, without `quickMenuPreventPageClicks`, I can use the page like normal,
each active element receives mouse events, which may be quite useful or dangerous...I will have a look on that...
LOL, now I want to move the qm around (e.g. dragging the background, empty places or around the tools, may be a drag handle tool could be useful, if no background)

**Comment by ssborbis** [comment]
> LOL, now I want to move the qm around (e.g. dragging the background, empty places or around the tools, may be a drag handle tool could be useful, if no background)

You get a menu bar that can be grabbed to move around the qm if you use the Lock tool. I thought about adding a "move" tool that lets you do the same thing without the menu being locked. If there was empty space to use as a handle, it could be done, but of course the qm was initially designed to be as low-profile as possible, so there's not a lot of extra menu to use.

**Comment by ssborbis** [comment]
> The result of that excursion is:
quickMenuPreventPageClicks

The `quickMenuPreventPageClicks` option was added because someone was using the 'click anywhere but the qm' to close method and accidentally triggering links.

> Anyways, this blocks some things, which may be useful while the qm is open, but doesn't change when it closes.
The ESC to close the qm or even cancel the drag is also blocked by this.

I'll look into this. That's definitely not the designed behavior. It should go away when the menu closes.

**Comment by ssborbis** [comment]
Ok, that was an easy fix. I just missed renaming a var when i was doing some code cleanup.

**Comment by hg42** [comment]
> > LOL, now I want to move the qm around (e.g. dragging the background, empty places or around the tools, may be a drag handle tool could be useful, if no background)
> 
> if you use the Lock tool

my qm is too big now (scaled up) to be open all the time

> I thought about adding a "move" tool that lets you do the same thing without the menu being locked

yeah, that's what I meant with drag handle tool, which I would like, because it's explicit...though experts profit from knowing that all the background can be grabbed

> If there was empty space to use as a handle

all kind of background or empty tiles (we could even add an empty engine for this purpose). With a wider menu you have lots of space on both sides of the tools.
Actually nearly everything in the window isn't draggable if not in edit mode. Perhaps drags can fall down to the background if not handled?

**Comment by hg42** [comment]
> Ok, that was an easy fix. I just missed renaming a var when i was doing some code cleanup.

nice, it works for me...

that's a nice part in some IDEs like Android Studio, that allow refactoring, which are often used for renames. This works, if the IDE knows the language, so it knows all usages of a name.

**Comment by ssborbis** [comment]
> Actually nearly everything in the window isn't draggable if not in edit mode. Perhaps drags can fall through to the background if not handled?

I'll see what can be done.

> that's a nice part in some IDEs like Android Studio, that allow refactoring, which are often used for renames. This works, if the IDE knows the language, so it knows all usages of a name.

My dev environment is pretty basic and I never really got into using a full-blown IDE. I tried eclipse a time or 2 for some java projects, but didn't stick with it . I moved to Sublime text a few weeks ago for the integrated git management, but that's about as fancy as I get. Any recommendations?

**Comment by ssborbis** [comment]
I'm trying making all qm drag events move the qm window. Also, double-click does a pseudo-docking and locks the menu open. Bound to be bugs, but it looks promising

**Comment by hg42** [comment]
> My dev environment is pretty basic

yeah, like me actually.
I usually stick to SciTE as an editor with some own lua code for folding and some text operations etc.
I also use a script system to apply intelligent operations on F5 for a file or F7 for the project.
F5 "runs" the current file, which depends on the file type, e.g. a py file will be run in the interpreter and a zsh file will be run in zsh. A scad file will start up in a 3D viewer etc. Do I usually have some zsh files around, that I load in the editor to do special operations (like deployment or similar).
F7 runs the project...depending what is found in the project, usually a build.zsh that describes what to do. But this may also be a makefile or similar.
So I usually edit something, then press F7 to see the result. Or F5 for special things.

I also tried several IDEs from time to time but always got back to SciTE.

The only IDE I really use is Android Studio. This happens to do just what I need there. But as always, I start to do special things, that are not supported, so at some point I will probably come back to the editor thingy.
Though, I really loved the refactoring...wish I could have this in my low level editor. I also think it's mainly possible because the java infrastructure is very mature and reflection is built in. Not sure if it exists or even can be done for javascript...

**Comment by ssborbis** [comment]
> I usually stick to SciTE as an editor

I've spent most of my time on Notepad++ but I recently moved my dev environment to linux, so now I'm on Sublime Text which has some nice github integration.

I know there's better software out there, but I can't convince myself to put in the time to learn it. Old dogs and all that.

**Comment by hg42** [comment]
well, it's certainly better to know your tools well (using them intuitively) than to always search for the best tools but only using some of their features.

Android Studio was the only one in the last years that gave me so much features, that I really use it. It also has nearly everything I use with my editor. E.g. I really need rectangular selections (unfortunately they are not as easy as in SciTE), folding, hotkeys for some actions (though it's kind of weak in AS).

**Comment by hg42** [comment]
anyways the issue is fixed...thanks a lot
