### ISSUE TITLE
✨Feature request: add an `❌sideBar.openOnResultsAutofocued`  option  to `☑sideBar.openOnResults`

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#320]
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#advanced`

![213_04020907](https://user-images.githubusercontent.com/10995302/109851410-9b70e700-7c8e-11eb-9040-1f2bfe9a5c32.png)

⚠Note: 
- 1. This option is only for the first load of the search result page, In other words, the default focus after the page loaded is the original default focus position of the page.

- 2. The default focus of the page remains unchanged, and then manually activate the CS-sideBar, it must be autofocus.

---
When ☑ `sideBar.openOnResults` , then:

- ## 💥 **Current behavior:** 
　　　🛇.  Will automatically focus on the Search-bar-input of the sideBar.
Take the simplest example:  You will not be able to use `Space/⇧+Space` to scroll the screen directly after the page is loaded, Or any other page hotkey.
because the focus at this time is on ☑ `sideBar.openOnResults` . 

- ## ❥ **Expected/fixed behavior:** 
　　　Will not autofocus after the first load of the search result page.

- ## 💡 **Implementation plan:**
　　　Changed by default, or at least add an ⬜OFF/☑ON option for it.

---

⚠Note: 
- 1. This option is only for the first load of the search result page, In other words, the default focus after the page loaded is the original default focus position of the page.

- 2. The default focus of the page remains unchanged, and then manually activate the CS-sideBar, it must be autofocus.

**Comment by ssborbis** [comment]
Sure

**Comment by ssborbis** [comment]
check the latest repo updates

**Comment by dnknn** [comment]
👌 Thank you very much!!!  👍was successfully fixed after tested!!💪
