### ISSUE TITLE
✨Feature request: keyboard naviga to the Last-used-engine button of tool-bar !

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#321]
New feature request see at👉  https://github.com/ssborbis/ContextSearch-web-ext/issues/321#issuecomment-793072266

<details><summary><s>done </s></summary>

- # ✨ 1: Support `Space` hotkey ꘌ click() 

Because we already support `Tab/⇧+Tab` for navigation,  but why not support `Space`?

<details>
<summary>🎬 Looking Gif demo `Tab/⇧+Tab`</summary>

![Tab+Space](https://user-images.githubusercontent.com/10995302/109892271-692eac00-7cc5-11eb-901f-b8595da584b0.gif)

</details>

-  **Current behavior:** 
　　　🛇. Only use the `Enter` hotkey, but not `Space`

-   **Expected behavior:** 
　　　✚. `Space` = `Enter` = `click`
　　　open a search engine or expand a folder.

-  **Why need do this ? :**
　　　Because the `Space` hotkey is very easy to press and is on the left hand of the keyboard.
　　　Because in other apps or web pages, most of them can be directly confirmed with `Space` after `Tab/⇧+Tab` navigation!

　
----

- # ✨2: Separator should not be navigated to by `Tab/⇧+Tab`

> Because Separator is not an interactive element/button/link

![image](https://user-images.githubusercontent.com/10995302/109893681-0c33f580-7cc7-11eb-9d53-bcd2b82fc559.png)

</details>

**Comment by ssborbis** [comment]
done

**Comment by ssborbis** [comment]
repo updated

**Comment by dnknn** [comment]
👌 Thank you very much!!!  👍bugs was successfully fixed after tested!!💪

**Comment by dnknn** [comment]
@ssborbis  

keyboard navigation is very easy to use/portable/fast! can you support an button keyboard navigation ?


## Expected behavior:

![213_09044125](https://user-images.githubusercontent.com/10995302/110379391-bc23ad00-8091-11eb-8989-587fecf314ea.png)

##  And make it the first keyboard navigation target.

## Why?
- because the first engine can use `Enter` to open it  (when focus at search bar),
- but the Last-used-engine has no keyboard navigated to open , so it can only be clicked with the mouse.

## achieved goals:

-  press `Tab` to navigate to it (just need one), then press`Space` ! 

- `Tab+Space` to open the Last-used-engine ! Wonderful ^_^!

**Comment by ssborbis** [comment]
Tools in a separate toolbar are not currently accessible by keyboard. This will get fixed eventually.

What about an option added to Shortcuts to access the last used directly by keyboard combo? A few tool functions already have shortcuts, so it would be a simple change.

**Comment by ssborbis** [comment]
Tools in a separate toolbar are not currently accessible by keyboard. This will get fixed eventually.

What about an option added to Shortcuts to access the last used directly by keyboard combo? A few tool functions already have shortcuts, so it would be a simple change.

**Comment by dnknn** [comment]
> ## Why?
> * because the first engine can use `Enter` to open it  (when focus at search bar),
> * but the Last-used-engine has no keyboard navigated to open , so it can only be clicked with the mouse.
> 
> ## achieved goals:
> * press `Tab` to navigate to it (just need one), then press`Space` !
> * `Tab+Space` to open the Last-used-engine ! Wonderful ^_^!

@ssborbis I add a suggestion, it feels good too:
:focus on the input, press `Ctrl+Enter⏎`  can open the last-used !

![image](https://user-images.githubusercontent.com/10995302/112153647-72ed6480-8c1e-11eb-918b-54f08aff1ac6.png)

**Comment by ZobaJakColbert** [comment]
So what's the solution? How to open last used engine with keyboard shortcut?

**Comment by ssborbis** [comment]
@ZobaJakColbert see #497

**Comment by ssborbis** [comment]
Last Used engine gets a shortcut under CS Options -> Shortcuts => Last Used. Default is ctrl+shift+L

Working in the latest beta 

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.40beta/contextsearch_web_ext-1.40rc1.xpi
