### ISSUE TITLE
Is it possible to put the search engine in the first place ?

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#322]
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html`

Because the most commonly used option page is the search engine manager !
The search engine is also the core module of the extension and the most commonly used, so it is necessary to put it in the first place!

Everything outside the search engine manager is a customization of the options/switches of the search engine.

![image](https://user-images.githubusercontent.com/10995302/109897235-5f10ab80-7ccd-11eb-99e7-23a6a962f325.png)

**Comment by ssborbis** [comment]
Beat you to it. That's how it is in the repo

**Comment by dnknn** [comment]
@ssborbis  Can you looking at  👉 https://github.com/ssborbis/ContextSearch-web-ext/issues/282#issuecomment-790142136
