### ISSUE TITLE
✨Feature request: Support `Esc` hotkey

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#323]
### `Esc` for Quick-Menu and Sidebar : 

> Why does need `Esc` ? 

> 1. often press `Esc` habitually to close/minimize, but no response...
> 2.  Sometimes accidents/errors popup or suddenly want to close, using `Esc` will be more casual/easy/convenient/direct... right?

⚠ But please note that Quick-Menu or Sidebar must have the focus to use Esc to work !

- for Quick-Menu : `Esc` to close Quick-Menu ! (⚠Esc only works when Quick-Menu gains focus)

- for Sidebar  : `Esc` to minimize Sidebar !  (⚠Esc only works when Sidebar gains focus)

⚠ But please note that Quick-Menu or Sidebar must have the focus to use Esc to work !

---
As a comparison, **Find-Bar** can be arbitrarily closed by `Esc` without getting the focus (currently implemented), which is normal (no problem).

**Comment by ssborbis** [comment]
Unless locked, the qm closes on ESC when not-in-focus. I didn't realize it wasn't working when in-focus. That's fixed.

ESC now minimizes the sidebar when in-focus

No repo push for a while.

**Comment by ssborbis** [comment]
fixes in the repo

**Comment by dnknn** [comment]
👌 Thank you very much!!!  👍bugs was successfully fixed after tested!!💪
