### ISSUE TITLE
✨Feature request:  Can we have search-engines-result-jumping to each other?

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#325]
Sorry, sorry....  the last question : 🤦🙈

![213_06025639](https://user-images.githubusercontent.com/10995302/110160911-9dba7900-7e27-11eb-8086-b9dfb84cd15f.png)

Currently, I don't know how to implement it in the global uniform scope.

For search engine results pages, query parameters are generally 
- `q` `word` `kw` `search_value` `keyword` `key` `wd` `search_query` `query`... etc.

1. Of course, users can customize this 👆 parameter...

So, can ContextSearch web-ext do something about this feature?

- for example, The current `{searchTerms}` is still the same, 

2. Then, add the modifier keys to achieve this function!

![213_06031255](https://user-images.githubusercontent.com/10995302/110162559-dbb89c80-7e29-11eb-9cfa-f6ea50216739.png)

**Comment by dnknn** [comment]
This `Bookmarklet` can extract the query parameters of the address bar, but still need to manually add the search engine again, so there is still no way to unify.

```js
javascript: var deurl = decodeURIComponent(location.search);
	var start = /&wd=|&q=|&kw=|&search_value=/i;
	var end = /&/;
	var searchTerm = deurl.split(start)[1].split(end)[0];
window.open("https://www.google.com/search?num=18&ie=utf-8&newwindow=1&q=" + searchTerm);
window.open("https://bing.com/...." + searchTerm);
```

**Comment by ssborbis** [comment]
Walk me through what you're wanting to achieve. 

> This Bookmarklet can extract the query parameters of the address-bar-URL, but still need to manually add the search engine again, so there is still no way to unify.

Bookmarlets *should* have access to most CS features, so there's probably a way to do what you're after

**Comment by dnknn** [comment]
> Bookmarlets _should_ have access to most CS features, so there's probably a way to do what you're after

Thanks for the response! what do you mean that?


By the way, @ssborbis  Can you take a look there? There are 2 bugs 👇

https://github.com/ssborbis/ContextSearch-web-ext/issues/282#issuecomment-790142136

**Comment by dnknn** [comment]
@ssborbis Haha, I thought of a possible way to satisfy this function :


![213_06064350](https://user-images.githubusercontent.com/10995302/110182140-53e18b00-7e47-11eb-882f-1ba011a6d044.png)

Can you think about it?

**Comment by dnknn** [comment]
@ssborbis Haha, I thought of a possible way to satisfy this function :


![213_06064350](https://user-images.githubusercontent.com/10995302/110182140-53e18b00-7e47-11eb-882f-1ba011a6d044.png)

Can you think about it?


---



> Bookmarlets _should_ have access to most CS features,

I suddenly thought that Bookmarklet might be able to do this, 
`document.querySelector('#searchBarContainer #searchBar').value = 'inp';`
but the results are disappointing, maybe you can guide 👇


```js
javascript: var deurl = decodeURIComponent(location.search);
	var start = /&wd=|&q=|&kw=|&search_value=/i;
	var end = /&/;
if (deurl.match(start) != null)	{
	var inp = deurl.split(start)[1].split(end)[0];
document.querySelector('#searchBarContainer #searchBar').value = 'inp';
}

```

**Comment by ssborbis** [comment]
Ok, I think I understand. You want to populate the CS search bar using the presumed search terms of the current web page found in the current URL.

The problem you're running into is, because the qm is in an iframe, you can't access the DOM directly.

Fortunately, there's already a method for this.

```javascript
javascript: var deurl = decodeURIComponent(location.search);
	var start = /\b(?:s|q|wd|kw|search_value)=/i;
	var end = "&";
	if (deurl.match(start) != null)	{
		var input = deurl.split(start)[1].split(end)[0];
	browser.runtime.sendMessage({action: "updateSearchTerms", searchTerms: input});
}
```

**Comment by dnknn** [comment]
> Fortunately, there's already a method for this.
> 
> ```js
>  ....
> 	browser.runtime.sendMessage({action: "updateSearchTerms", searchTerms: input});
> }
> ```

@ssborbis Unfortunately, did not see the perfect result (Sidebar or TrayPopup)?

**Comment by dnknn** [comment]
@ssborbis   I originally gave up the idea of this feature, but after I tried the extension below, I have a better idea and recommend it to you, so can you try to test the extension?

<details>
<summary>I think our extension can also integrate this function, because it is also a practical level!
</summary>

![image](https://user-images.githubusercontent.com/10995302/110220897-c617a580-7f03-11eb-8b82-28013823a9c8.png)


</details>


- Search All 　https://chrome.google.com/webstore/detail/kpdkbemdpepjjppbfgeapjienologapa

> The performance of this extension is very poor, but its 2 core functions for engine jumping are 100% perfect!
> If you also feel good, we can also consider adding modules with similar functions in the future.




![213_07042944](https://user-images.githubusercontent.com/10995302/110220022-e2b0df00-7efd-11eb-9e1d-0e50e5f5cd98.png)

---

- perfect 1: `%s` or `{searchTerms}` of search engine (added by users) will be automatically entered into the history record of the switch bar.

> ⚠ This history is automatically extracted from the search engine URL by the extension, ⚔As a comparison: the history of our extension only records the pages opened through our extension, right?
Therefore, if you want to add this functional module in the future, when the user enable the option of the switch bar on the search result page, we can also have this function!


- perfect 2 : The switch bar automatically appears on the search engine results page.

- perfect 3: `position` of the switch bar is `{position:absolute;top:0;}`

Disadvantages of this extension: In addition to the above advantages, they are all disadvantages. e.g. it seems to give up maintenance, poor performance (higher lethality),
The search engine manager is even more rubbish,  e.g. Can't drag to sort/order, folder/category not supported... etc.......


----

**Comment by ssborbis** [comment]
Sure, make a new feature request and we can go from there.
