### ISSUE TITLE
Bug : no icon of the last used engine for Bookmarklets

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#326]
![image](https://user-images.githubusercontent.com/10995302/110181004-d49f8780-7e45-11eb-956b-cb1b20f48727.png)

## Reproduce: 

1. use Bookmarklet to search.

2. reproduce

**Comment by ssborbis** [comment]
got it

**Comment by ssborbis** [comment]
updates in the repo

**Comment by dnknn** [comment]
👌 Thank you very much!!!  👍bug was successfully fixed after tested!!💪
