### ISSUE TITLE
add second confirmation for ⌦Delete etc. dangerous action

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#329]
Changed by default, or at least add an ⬜OFF/☑ON option for it.

- ## ❥ **Expected behavior:** 

![213_07221237](https://user-images.githubusercontent.com/10995302/110242709-3f5dd980-7f92-11eb-92ea-d89b45c46110.png)

## Why ?

Since we don't have a 🗑recycle-bin♻ feature, therefore, when a dangerous action is taken, it is necessary to add a second confirmation!

## 💡  **Implementation plan:**
　　　1. `confirm()` (simple)
　　　2. or create a `div` DOM-element to popup , like this extension: [Redirector](https://chrome.google.com/webstore/detail/ocgpenflpmgnfapjedencafcfakcekcd)  

![image](https://user-images.githubusercontent.com/10995302/110242658-058cd300-7f92-11eb-8dd0-dd4fe3e5626e.png)

**Comment by ssborbis** [comment]
There is a confirmation when you try to delete more than one node

**Comment by dnknn** [comment]
> There is a confirmation when you try to delete more than one node

yes, Of course I know that...

However, I personally think that deleting a single one should also be confirmed twice, 

Changed by default, or at least add an ON/OFF option for it, What is your opinion?

If you feel unnecessary, you can close this issue directly , Thanks!

**Comment by dnknn** [comment]
> There is a confirmation when you try to delete more than one node

@ssborbis  yes, Of course I know that...

However, I personally think that deleting a single one should also be confirmed twice,

⚠But not the UI interaction of your gif (that would be troublesome), but the pop-up confirmation. 

Changed by default, or at least add an ON/OFF option for it, What is your opinion?

If you feel unnecessary, you can close this issue directly , Thanks!

**Comment by ssborbis** [comment]
I think the confirmation used now is more convenient than the standard `confirm()` message. It requires less mouse movement and gives graphical feedback to the types of nodes being removed. I can add it for single deletes though. Maybe some other users can chime in.

**Comment by dnknn** [comment]
> the standard `confirm()` message.

Can don’t need mouse, because the standard `confirm()` support `Space` hotkey to confirm.


> I can add it for single deletes though. Maybe some other users can chime in.

Ok...🤦

**Comment by ssborbis** [comment]
What about a keyboard shortcut for `Delete` that prompts with a standard confirm() message. GUI users can get the popup, keyboard users get the confirm.

**Comment by dnknn** [comment]
I don't understand what you mean ?

**Comment by ssborbis** [comment]
Right now, keyboard key `Delete` does nothing. I can add that functionality and prompt with the default javascript confirm() message, allowing keyboard users to press Enter or Space to complete the deletion.
