### ISSUE TITLE
Bug: Import option data is missing

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#330]
![image](https://user-images.githubusercontent.com/10995302/110248418-f450c000-7fab-11eb-9284-113ccc1e43ef.png)

After importing, it was found that some options were missing, and the CSS code was not loaded at all.

> Cause: In order to test the latest repo, I exported the data from V1.28.1 (store version), and then imported it into the latest repo (v1.29) of another browser.

----

1. `Export from` the option datas of V1.28.1 (store version)  [ContextSearchOptions.json.txt](https://github.com/ssborbis/ContextSearch-web-ext/files/6097609/ContextSearchOptions.json.txt)

2. `Import to` the https://github.com/ssborbis/ContextSearch-web-ext/tree/37bb938a838abc68b3925bcebeb9e763e9ed26dc repo version.

3. At this point, you will find that except for the search engine, most of the other options' data is lost. For example, hotkeys/shortcuts options, CSS customization, Advanced options .... etc.

**Comment by ssborbis** [comment]
That seems to import fine for me using the latest local code. It probably will not import correctly to an older version ( store version ). Some user preferences were removed in the repo version that will cause problems if exported and imported to an older version. This is a known problem that I mentioned it in the readme.

I'll double-check using the repo code but I think it's essentially the same as I'm using.

**Comment by dnknn** [comment]
@ssborbis 
I know that the data is different between the old and new versions, but generally speaking: 

# Importing: 

- 🆕 -> old : Importing from the new version to the old version can cause problems,

- old -> 🆕 : Importing from the old version to the new version, is there no problem!

So what is your opinion?

If  `old -> 🆕 ` have problem, that means it is difficult to upgrade smoothly?

But it doesn't matter, what I want to ask is : I am now at the 1.28.1 store version. 
After you release the new version 1.29 to the store, will it affect this problem?

**Comment by dnknn** [comment]
In other words, at the 1.29 store version, do I need to reinitialize(Uninstall the extension and reinstall?) the configuration option data?

**Comment by ssborbis** [comment]
Wait, I see it now. Nice catch. Didn't notice because my values were very similar.

Updating the repo now with a fix and some other fixes you were asking about.

**Comment by dnknn** [comment]
Normally,  old(Export) -> 🆕(Import) : shouldn't be a problem, because this is an upgrade, not a downgrade.

You can open `.JSON` file, and then format (beautify), there are CSS data in it, but it will not be loaded when imported into the new version.

![image](https://user-images.githubusercontent.com/10995302/110263227-fab55b00-7ff0-11eb-8eae-851aea44a4b4.png)

**Comment by ssborbis** [comment]
I was able to import your custom CSS using the latest fix

![Screenshot_2021-03-07_19-35-40](https://user-images.githubusercontent.com/24310997/110263470-6dd0ba00-7f7c-11eb-8635-150573cec0b1.png)

**Comment by dnknn** [comment]
> using the latest fix

Great!!

Curious to know what causes the import to be unable to be upgraded?

**Comment by dnknn** [comment]
👌 Thank you very much!!!  👍bugs was successfully fixed after tested!!💪
