### ISSUE TITLE
search bar of the search engines manager page

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#331]
![213_08014010](https://user-images.githubusercontent.com/10995302/110249084-3fb89d80-7faf-11eb-9c73-e5890328cea8.png)

- ## `Ctrl+F` to focus this search bar ! 

>just like the manager  of [Tampermonkey](https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo) or [Stylus](https://chrome.google.com/webstore/detail/clngdbkpkpeebahjckkjfobafhncgmne).

- ## `Esc` to clear the input in the search bar (⚠when the focus is on the search bar)

>just like the manager  of [Tampermonkey](https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo) or [Stylus](https://chrome.google.com/webstore/detail/clngdbkpkpeebahjckkjfobafhncgmne).

**Comment by ssborbis** [comment]
check the latest

**Comment by dnknn** [comment]
👌 Thank you very much!!!  👍beautiful💪
