### ISSUE TITLE
Feature request:  add 👁 `Show/Hide` button for the tools of Quick-Menu

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#333]
![213_08104140](https://user-images.githubusercontent.com/10995302/110267488-e1b1a780-7ffa-11eb-8d54-84ea610ac488.png)

⚠ This 👁 button here, It will `Show/Hide all` hided in the search engine manager 

###  This button is **toggle**  type, 
- When the 👁btn is disabled(OFF), it is equivalent to the current .
- When the 👁btn is enabled(ON), It will show all engines (even if hidden in the manager).

💪Therefore, this 👁button is obviously also very beneficial/useful, users can intentionally hide some engines in the engine manager ("background"), and then show them again through this button in the "foreground".

> It is also obvious that this function can be used in many scenarios and is very suitable for various users.

**Comment by ssborbis** [comment]
I'm looking into reworking the tools. I'll revisit this after the new changes start to go into the repo

**Comment by ssborbis** [comment]
new tool show/hide in the dev branch repo
