### ISSUE TITLE
Search by Quickmenu doesn't work in some textboxes

### ISSUE THREAD

**Issue by simonbcn** [ssborbis/ContextSearch-web-ext#334]
```
Google Chrome 89.0.4389.82
ContextSearch 1.28.1
```

This is my `Quick Menu` configuration:
![Screenshot_20210310_142816](https://user-images.githubusercontent.com/428231/110636813-ff267300-81ac-11eb-8201-d2f28ffb0a9c.png)

When I try to do a search from a text field in _Facebook_ or _GMail_ it opens the search engine clicked but without text.

**Comment by ssborbis** [comment]
Thanks. The bug doesn't happen in Firefox, where I do most of my dev.

I didn't test Facebook, but GMail has an event that clears the text selection when you click in the text field. This addon watches for text selection changes to update the search terms. I have a workaround but I'll try to get something cleaner before updating the repo.

**Comment by ssborbis** [comment]
Fix seems to be working ( at gmail at least ) If you want to check the changes, export your config to backup your settings and try the latest repo. FYI, you will need that backup if you revert back to v1.28.1

**Comment by simonbcn** [comment]
Thanks. It works in both GMail and Facebook.
