### ISSUE TITLE
What is the correct syntax format of Search  REGEX_MODIFIERS ?

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#335]
https://github.com/ssborbis/ContextSearch-web-ext#62-modifying-search-terms

![image](https://user-images.githubusercontent.com/10995302/110970492-c6e18900-8394-11eb-9151-420ea507fd65.png)

👆The help document you did not give an example of `REGEX_MODIFIERS`, 

`FIND_REGEX, REPLACE_REGEX [, REGEX_MODIFIERS]`

The first two parameters are easy, but the `g/m/i` modifier is invalid in my test.

　|　
:---|---|
`"&.+" , "11"` |  ✔️
`"&.+" , "11" [,gi]` | ❌ (Can you give an example?)

![image](https://user-images.githubusercontent.com/10995302/110969884-2723fb00-8394-11eb-8c01-a6dbf7175a1c.png)

Related: https://github.com/ssborbis/ContextSearch-web-ext/commit/14d8854841f9dde6a0f5c836de79ba66f0a7ad4e

**Comment by ssborbis** [comment]
`"&.+" , "11", "gi"`

brackets are indicating optional
