### ISSUE TITLE
Chromium linux addon not show icons

### ISSUE THREAD

**Issue by darekpro** [ssborbis/ContextSearch-web-ext#336]
Hi, like in title addon not show icons latest ver chromium and addon.
![Zrzut ekranu z 2021-03-16 09-19-25](https://user-images.githubusercontent.com/58607093/111277514-d3860b80-8638-11eb-8164-e7573f5ee87b.png)

The same config in FF works fine.

**Comment by ssborbis** [comment]
AFAIK, chromium doesn't support icons in context menu subfolders

**Comment by darekpro** [comment]
Ahhh :( sad news...
