### ISSUE TITLE
sort advanced settings

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#337]
I am always searching for settings.
This would be especially nice, because most names are structured with group names (like quickMenuXXX)

**Comment by ssborbis** [comment]
I have a sorting function ready, but I may need to make sections, because some things should be grouped that aren't in alphabetical order.

**Comment by hg42** [comment]
yepp, or rename those settings...
Those that set such advanced setting will probably have no problem to adapt to it, all others will get the default anyways.
You could also use a "_" for separating the group name (e.g. quickMenu_XXX), use sections in the ui and remove the group part from the label.

**Comment by ssborbis** [comment]
k, should be sorted in the latest

**Comment by hg42** [comment]
thanks...I like that
