### ISSUE TITLE
Please add option to disable the context menu item in this case 

### ISSUE THREAD

**Issue by Marvinoo** [ssborbis/ContextSearch-web-ext#340]
When I right click on an image the context menu for this addon should not be their bcoz it has nothing to do with pictures, please allow removing the item from context menu for images.

**Comment by dnknn** [comment]
<img align=right width=30% src=https://user-images.githubusercontent.com/10995302/111908143-0db93800-8a93-11eb-8a81-30b641d54ad9.png>

`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#quickmenu#OFF:~:text=Enable%20on%20images`

**Comment by Marvinoo** [comment]
> 
> 
> <img alt="" width="30%" src="https://user-images.githubusercontent.com/10995302/111908143-0db93800-8a93-11eb-8a81-30b641d54ad9.png">
> 
> `chrome-extension:ddippghibegbgpjcaaijbacfhjjeafjh/options.html#quickmenu#OFF:~:text=Enable%20on%20images`

am asking about the **context menu** not the quick menu

**Comment by ssborbis** [comment]
@Marvinoo The menu is enabled on images so you can use the URL in reverse-image search engines.

**Comment by Marvinoo** [comment]
> 
> 
> @Marvinoo The menu is enabled on images so you can use the URL in reverse-image search engines.

aha excuse my limited knowledge sir, but i think.. i really don't need it so it's ok to provide an option to unload this item for ppl like me who don't need it so my context menu looks less crowded. thanks a lot sir.

**Comment by ssborbis** [comment]
I'll add the option but it may still show on some elements with background images due to timing between when the mouse button is pressed down and when the context menu opens. I'll leave the thread open til it's in a release.

**Comment by ssborbis** [comment]
@Marvinoo Changes are in the repo. Be sure to back up your config if you're testing.

**Comment by Marvinoo** [comment]
It works now.
