### ISSUE TITLE
search in a new tab: impossible?

### ISSUE THREAD

**Issue by gabri25ele** [ssborbis/ContextSearch-web-ext#341]
Settings in this way

![Immagine 2021-04-16 102630](https://user-images.githubusercontent.com/33927879/114995594-4be12600-9e9e-11eb-97d1-1b2508f93868.png)

![Immagine 2021-04-16 102650](https://user-images.githubusercontent.com/33927879/114995602-4e438000-9e9e-11eb-90ce-2d67d495435c.png)

in the quickmenu works!
but with the context menu the search is still in the same tab.

![Immagine](https://user-images.githubusercontent.com/33927879/114995959-a5e1eb80-9e9e-11eb-8bd2-feff711f3c72.png)

what can I do to open the searched word in a new tab also with the context menu?

**Comment by ssborbis** [comment]
Did you set the search action to Open in New Tab under the Context menu section? It looks like you posted a screenshot of the Quick menu section.

**Comment by ssborbis** [comment]
![Screenshot_2021-04-17_12-49-01](https://user-images.githubusercontent.com/24310997/115122043-748b1d80-9f7b-11eb-802b-0e5f7690b2d9.png)

**Comment by gabri25ele** [comment]
I can't see well ... 
I searched and searched and it was there. 
thank you very much and sorry for the trouble

**Comment by ssborbis** [comment]
No worries. Glad to hear you got it working.
