### ISSUE TITLE
Lost CS Config Through Quick Menu Interaction

### ISSUE THREAD

**Issue by GlasWolf** [ssborbis/ContextSearch-web-ext#342]
Just want to flag this up as a possible issue, but I'm not sure whether it'll be reproducible as I'm not exactly sure how it happened.

I long right clicked to bring up the CS quick menu, then I think I had a "hand twitch" and accidentally dragged across or off the QM.  Somehow that seemed to delete or reset my CS settings, so my menu went back to 3 x 2 (?), dark mode, right click (not hold), context menu not suppressed etc.

I was reading through [this thread](https://github.com/ssborbis/ContextSearch-web-ext/issues/312) as some of the fixes were similar (specifically the quickMenuHoldTimeout), and I notice that most of my Advanced settings are blank (I had to change the quickMenuOpeningOpacity from 80 to 100).

Sorry if this is a bit vague but maybe it'll help spot an odd bug somewhere.  Or it might be a feature I've missed!

FF 88.0, CS 1.28.1

**Comment by ssborbis** [comment]
It's nothing you did wrong. There's a bug in the release version that can cause the config to not be saved / loaded properly, usually corrupting from the options page. It should be addressed in the beta version. You might want to back up your settings and try it. It **should** fix the issue, but I haven't gotten much feedback either way.

https://github.com/ssborbis/ContextSearch-web-ext/releases

**Comment by GlasWolf** [comment]
Great, thanks, I've installed that.  I can't imagine I'll be able to replicate the original issue but if it happens again I'll let you know.
