### ISSUE TITLE
Options to enhance editable elements

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#344]
## 💡 **Expected behavior:**
　
![215_25153856](https://user-images.githubusercontent.com/10995302/119458471-5d580080-bd6f-11eb-9d9f-a48a6c34abb4.png)

　
> Because for example, use the middlebutton to trigger, it will not affect anything.

## ❓ **How to achieve:** 
> Add sub-options : 

![215_25155031](https://user-images.githubusercontent.com/10995302/119460173-fe938680-bd70-11eb-8ce7-7c2f609a20cf.png)

**Comment by ssborbis** [comment]
What is the specific problem you're experiencing so I can understand better?

**Comment by dnknn** [comment]
Sorry, please ignore this issue, 🤦
because the following two solutions can be easily achieved: 

to show `getSelection()` sidebar  in editable elements (`input[type=text]` / `textarea` / `contentEditable=true`)

```
chrome://extensions/shortcuts#:~:text=ContextSearch%20web-ext
	For example: Ctrl+E
```
or
![image](https://user-images.githubusercontent.com/10995302/119909708-23ae1200-bf88-11eb-86e7-ee3018268ead.png)
