### ISSUE TITLE
Bug/Optimization :  Attach `trim()` to `getSelection()`  to avoid accidental blank search !

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#346]
> @ssborbis This problem has been troubled for a long time, and now I have finally found out the specific cause.

- all `getSelection()` code :
https://github.com/ssborbis/ContextSearch-web-ext/search?q=getSelection%28%29
https://github.com/ssborbis/ContextSearch-web-ext/blob/66b17fbc7b2486252d4e0121437bf680ee93563d/src/inject.js#L18
https://github.com/ssborbis/ContextSearch-web-ext/blob/66b17fbc7b2486252d4e0121437bf680ee93563d/src/inject.js#L37

`window.getSelection().toString();` 　 　change to 👇
`window.getSelection().toString().trim();`
> `.trim()` will be fixed anything ❕
> Because can fix inexplicable accidental triggering of ContextSearch web-ext.

![216_07235810](https://user-images.githubusercontent.com/10995302/121051676-3af0c900-c7ec-11eb-9639-29fc05ac5399.png)

- So, can add `.trim()` to all `.getSelection().toString()` ?
   * 1 Because page elements have borders, when no real text is selected, the selection of `\n` line breaks will be triggered, the most common example is double-click.
   * 2 Obviously, the **pure** blank `\n` newline character has no practical meaning for searching, But currently it will still trigger ContextSearch to start the search.....
   * 3 Obviously, the white space on both sides of the `getSelection()` strings has no practical meaning either

**Comment by ssborbis** [comment]
Thanks. I'll get this added to the development branch soon.

**Comment by ssborbis** [comment]
Ok, should be in the dev repo now
