### ISSUE TITLE
1.29 problem

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#349]
[image](https://user-images.githubusercontent.com/10995302/122642861-20e5ad80-d13f-11eb-9418-c830852e46b8.png)

1.28.1 normal, ⚔ 1.29(last repo version) unavailable 👇 pages

```js
chrome-extension://.....
about:blank
chrome://settings/
......
```

```js

https?://		👈 no problem! 
```

**Comment by dnknn** [comment]
`searchbar.js` file

![image](https://user-images.githubusercontent.com/10995302/122643517-c77f7d80-d142-11eb-901f-ac629fb2c634.png)

**Comment by dnknn** [comment]
By comparing the two versions of the code, after I tested it, I finally found a fix, 
Please see the screenshot below, I don't know if this change will cause problems ?

![image](https://user-images.githubusercontent.com/10995302/122644116-2e526600-d146-11eb-9c31-00d5423e75ae.png)

**Comment by ssborbis** [comment]
I've seen this too. I think it's due to the new anti-tracking settings in Firefox. It's been driving me nuts. I'll try you fix and see if it integrates nicely.

**Comment by dnknn** [comment]
> I think it's due to the new anti-tracking settings in Firefox.

I am not using Firefox, Is this also the case with Chrome (the new anti-tracking settings) ?

**Comment by ssborbis** [comment]
If that's the case, it may simply be the code changes and the promise chain failing. Either way, good find and I'll get a fix going.

**Comment by dnknn** [comment]
I only know a little JavaScript. This is how I compared the code differences between the two versions, and then tried to make changes. The result was successful!
Below is a screenshot of my code changes, which may be helpful to you.

![image](https://user-images.githubusercontent.com/10995302/122644116-2e526600-d146-11eb-9c31-00d5423e75ae.png)

**Comment by ssborbis** [comment]
This change should be in the development branch. I say "should" because I'm having some odd behavior with git right now. It does seemed to have fixed the problem. Thanks!
