### ISSUE TITLE
1.4.9 is bug

### ISSUE THREAD

**Issue by DandyClubs** [ssborbis/ContextSearch-web-ext#35]
http://cnbtkitty.org/

path
http://cnbtkitty.org/

params
keyword={searchTerms}&hidden=true

1.4.8 is good work

but 1.4.9 not work.

just main page open

and etc some site is not work

**Comment by ssborbis** [comment]
Yep, looks like POST engines aren't working. I'll post again when I get a hotfix up.

**Comment by ssborbis** [comment]
v1.4.9.1 going up. Thanks for the heads-up
