### ISSUE TITLE
`floatingEditFormContainer`  optimization suggestion 

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#350]
<img align=right width=50% src=https://user-images.githubusercontent.com/10995302/122672611-05da7280-d1ff-11eb-80f6-3ccb4109c66e.png>

`#floatingEditFormContainer`

### 1️⃣ support `Escape`'s general key to close !
![image](https://user-images.githubusercontent.com/10995302/122672658-5782fd00-d1ff-11eb-97dd-d8b7a59d1a3a.png)
 

<details><summary> Ø<s>fixed</s>Ø </summary>

### 2️⃣ Default change or advanced options: ↴
`chrome-extension://mlhlcahflgfgallicofkjfedfcgngkno/options.html#advanced`

Mouse click on the outer blank space (i.e. `.overDiv`) does not close it !
> Because this often leads to unexpected behavior of false shutdown
The most obvious unexpected behavior is: When you use the mouse `getSelection()` to get out of the `div` container, it will trigger a close, which obviously does not meet our expectations
At present, every time you operate, unless you are careful and remember to have this behavior, it is very easy to trigger the unexpected shutdown behavior.

Because this is an `editbox`, not `alart()` dialog</details>

**Comment by dnknn** [comment]
edit/update: If you want/feel reasonable, you can also add:

- `CtrlS` / `Enter` to `save`

**Comment by dnknn** [comment]
> edit/update for `#floatingEditFormContainer`

### Can you ❓↴
```css
	#editSearchEngineForm input[name=template]
					// input👆 change to 👇textarea
	#editSearchEngineForm textarea[name=template]						
```
- Because we need → ` textarea[name=template] {resize:vertical} `
Why do we need `resize` ?

- Because [image](https://user-images.githubusercontent.com/10995302/122690805-21c13100-d25e-11eb-93be-dc954f2aa364.png)  `["url1", "url2", ...]` multi-URL-template.
Obviously this needs to be replaced with `textarea` to stretch and display very long strings.

**Comment by ssborbis** [comment]
> Mouse click on the outer blank space (i.e. .overDiv) does not close it !

Are you saying clicking outside the form **doesn't** close the form or are you suggesting that it **shouldn't** close the form?

I tested on chromium and it seems to be working as expected.

**Comment by dnknn** [comment]
sorry for my English..... and I can't express it correctly to make you understand.


> Are you saying clicking outside the form **doesn't** close the form or are you suggesting that it **shouldn't** close the form?
> I tested on chromium and it seems to be working as expected.

- For clicking outside the form :
  * 👎 **Current** behavior:    　 can **close**  the form. (donot want to behave like this)
    * then, suggesting change to ↴
  * 👍 **Expected** behavior:   　**doesn't** close the form.
  
The reasons for suggesting changes to the current behavior are:
The current behavior is very easy to trigger the closure, or it is very easy to accidentally trigger the closure of the form.


Do you understand the meaning now?, can you change by default or add an option ?

**Comment by ssborbis** [comment]
> If you don’t understand that overdiv.onclick => form.close brings a bad experience, I can show you a gif demo, you can know the bad result

That would be helpful. Most menus in this addon close when they lose focus by design.

**Comment by dnknn** [comment]
> That would be helpful. Most menus in this addon close when they lose focus by design.

Well, or add an option ?

- 🗣1 Because this is a special scene, this is an **editbox**, not `alart()` or simple dialog,
it is an **edit-box** : so means that if you accidentally or accidentally trigger the closure, then you will lose the hard-edited content.

- 🗣2 In addition, `getSelection()` of the `input` or `textarea` element in this editbox, this is a higher frequency operation, right. 
Then, press&holding the left-mouse button to `getSelection()`, if you release the mouse **outside** the editbox, the close will be triggered at this time.

> Of course, this is not a big problem, I'm just talking about the situation.
it's up to you ^_^

**Comment by ssborbis** [comment]
>  In addition, getSelection() of the input or textarea element in this editbox, this is a higher frequency operation, right.
Then, press&holding the left-mouse button to getSelection(), if you release the mouse outside the editbox, the close will be triggered at this time.

That might be a chrome bug. It isn't happening in Firefox. It seems that the "click" event fires even if the element seeing the mouseup event isn't the same as the element that received the initial mousedown event.

**Comment by dnknn** [comment]
> That might be a chrome bug.

Now think about it, it is true, `onclick` actually receives the `mouseup` event


It turned out to be a bug, I thought it was normal behavior

Is it this bug? https://crbug.com/1013201

https://github.com/ssborbis/ContextSearch-web-ext/commit/325e421467088625eb8d00bcbc2de630375bde58#diff-0a37814c5583b10bdad16cce8cffefb1858a7337507625a66d54750b94b1d946
tested && Successfully fixed !!!!

🤝 Thank you very much, there will be no problems now.
