### ISSUE TITLE
hotkeys

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#351]
![216_21092013](https://user-images.githubusercontent.com/10995302/122695038-e6c8f880-d271-11eb-9da5-2c67abb8c986.png)
> for QuickMenu

### 1. Can the triggering of modifier keys be restricted?

- Current behavior:
  For example: `ShiftE` will also trigger QuickMenu when `getSelection()`
- Expected behavior: ↴
```js
	&&!event.ctrlKey&&!event.shiftKey&&!event.altKey&&!event.repeat
```
> Obviously it can only be a single button/hotkey, So there is no need to attach modifier keys to trigger.

-----------------------------------------
　　　

### 2. `E` can be used to `$('#searchBar').focus();` after when QuickMenu is displayed.
<img align=right src=https://user-images.githubusercontent.com/10995302/122695201-5212ca80-d272-11eb-8434-673a6fb9b345.png>

> use `jQuery` selector to demo :)

### Then, expected feature behavior:
- 1.. `getSelection()`
- 2.. pressing `E` hotkey [image](https://user-images.githubusercontent.com/10995302/122696743-61941280-d276-11eb-926a-1286525800e4.png) to display QuickMenu. 
  * These are all okay, and then suggestions for functional enhancements↴
- 3.. At this point, continue to press `E`  can to :
`	!target.matches(`input[type=text]`) && $('#searchBar').focus();`

In other words, `E` has 2 function triggers : ↴

```js
if (event.key.toLowerCase()===`e` &&!Ctrl&&!Shift&&!Alt&&!event.repeat)	{
	if	(`$('body[data-menu=quickmenu]').length<1`)	{
		.... display QuickMenu  ....
	}else if(`$('body[data-menu=quickmenu]:visible')` &&! target.matches(`input[type=text]`))	{
		$('#searchBar').focus();
	}
}
```

- Of course, `E` is only for the quickmenu of `getSelection()`, 
But if, when `body[data-menu=sidebar]` or `body[data-menu=searchbar]` is displayed, it can also be used to focus the searchbar, it will be a unified logic.

> Finally, of course, this is not necessary, it depends on whether you think it makes sense, it is up to you! :)

---------------------------------------------------------------------
　　　

<details><summary>Done</summary>

### 3.  use `🔙Backspace` hotkey can to back

<img align=right src=https://user-images.githubusercontent.com/10995302/122698417-db79cb00-d279-11eb-8fe4-fe1b57a54866.png>

let $backBtn = #quickMenuElement .tile[data-type=tool][title=back]

```js
if (event.key===`Backspace` &&! target.matches(`input[type=text]`) &&!Ctrl&&!Shift&&!Alt&&!event.repeat)	{
..... $backBtn.click(); ....
}
```

</details>

**Comment by ssborbis** [comment]
1. That bug is fixed as far as I can tell. I tested FF and chromium with the latest dev code
2. Why not use the checkbox option for focusing the search bar on quickmenu open? Whats the advantage of leaving that option disabled and pressing 'e' a second time?
3. sure

**Comment by dnknn** [comment]
@ssborbis 
> 2\. Why not use the checkbox option for focusing the search bar on quickmenu open?

- because: 
focusing the search bar by **default**, 
Means you won’t be able to use it directly/default 👇

```css
#managerContainer li.treeNode .header .hotkey:not(.keyword)
```

For this reason, I set the search bar not to automatically focus by default.
Then, currently you can use `Shift+Tab` to focus the search bar.


Of course, it doesn’t matter, just let you know that there is such a thing, it’s up to you.

**Comment by ssborbis** [comment]
Looks like the modifier hotkey fix only worked when the qm wasn't open. New code fixes it when the menu IS open( Shift + G does not work with an engine with hotkey g )

**Comment by dnknn** [comment]
> New code fixes it when the menu IS open( Shift + G does not work with an engine with hotkey g )

@ssborbis  🤝ThankYouVeryMuch!  but have you considered this situation ? it cannot be disabled: 
 - - Because `AltE` is a hotkey that acts on itself, and it is a switch/toggle -type hotkey. 👇

![image](https://user-images.githubusercontent.com/10995302/124353332-71c5cd80-dc38-11eb-996d-d36bfd6d4c50.png)

**Comment by dnknn** [comment]
> New code fixes it when the menu IS open( Shift + G does not work with an engine with hotkey g )
> qm hotkeys disabled when modifier keys active

```js
if ( e.ctrlKey || e.altKey || e.shiftKey || e.metaKey ) return;
	// I can understand the meaning of this line of code, but I cannot understand the context code/logic ^_^
```

@ssborbis  🤝ThankYouVeryMuch!  but have you considered this situation ? it cannot be disabled: 
 - - Because `AltE` is a hotkey that acts on itself, and it is a **switch/toggle** -type hotkey. 👇

![image](https://user-images.githubusercontent.com/10995302/124353332-71c5cd80-dc38-11eb-996d-d36bfd6d4c50.png)

**Comment by ssborbis** [comment]
What specifically is the problem you're having?

**Comment by dnknn** [comment]
> What specifically is the problem you're having?

No problem, because I have not used the latest version 🤦
