### ISSUE TITLE
Show recently used engines at the top of all  the  `#quickMenuElement`

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#353]
<img align=right src=https://user-images.githubusercontent.com/10995302/122842419-ee4ed700-d32f-11eb-8efe-1dfbab8c3c49.png>

👍 This design is perfect! 👉
> But unfortunately, it only appears in the right-click-ContextMenu.

![216_22075940](https://user-images.githubusercontent.com/10995302/122842351-ce1f1800-d32f-11eb-9511-ec21236d4052.png)

- so, can you synchronous add to all  the  `#quickMenuElement`

> I personally think that the recently used function is very useful, so i feels necessary to display it in `#quickMenuElement`

**Comment by ssborbis** [comment]
It could be easily added as a tool

**Comment by dnknn** [comment]
> It could be easily added as a tool

![216_22092741](https://user-images.githubusercontent.com/10995302/122848447-1b08eb80-d33c-11eb-857f-2cfc095d89bf.png)
This i know, It can only display only 1 recent. I mean **recently used history**....

**Comment by ssborbis** [comment]
I meant I could write a new tool

**Comment by dnknn** [comment]
- UI Implement:
  Same as the right-click-ContextMenu && options.
  can also added as a tool.

**Comment by ssborbis** [comment]
in the dev repo for testing

reusing the history icon for now

**Comment by ssborbis** [comment]
added advanced option to show as folder atop tiled menus. i might remove the tool now

**Comment by dnknn** [comment]
> added advanced option to show as folder atop tiled menus. i might remove the tool now

🆗👌🤝 ThankYouVeryMuch!!
