### ISSUE TITLE
Display/map `single-hotkey` to the foreground engines

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#354]
### `single-hotkey` (background-UI)
```css
	#enginesTab input.hotkey:not(.keyword)	{text-transform:uppercase;}
```
![216_25071258](https://user-images.githubusercontent.com/10995302/123343667-c99f6d00-d584-11eb-846f-32e84ecaaa36.png)

- Then, the foreground-UI for the expected behavior: 👇

![216_25073226](https://user-images.githubusercontent.com/10995302/123344938-8397d880-d587-11eb-91bb-0305d1944af1.png)

> This is not a big problem. Only consider it if it is easy to implement, otherwise please close this issue directly.
In other words, the `single-hotkey` set by the user in the background will be displayed on the foreground UI.

- Probably similar to this (This is the default behavior of UA)
![216_25072655](https://user-images.githubusercontent.com/10995302/123344579-be4d4100-d586-11eb-90d2-258ac8289efa.png)

- Tip: 
  * It is also possible that the foreground-UI does not display these hotkey strings. 
  * The context-menu needs to be displayed before it can be used.

**Comment by ssborbis** [comment]
I don't think I want to display them on the tile menu, but the list view and tooltip seem good.

**Comment by ssborbis** [comment]
advanced option quickMenuShowHotkeysInTitle in the dev branch
