### ISSUE TITLE
Support back-button / forward-button of mouse

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#355]
```js
	event.button===0	//left mouse button
	event.button===1	//middle mouse button
	event.button===2	//right mouse button
					// and 👇
```

![216_28012333](https://user-images.githubusercontent.com/10995302/123553705-7826f600-d7af-11eb-97bc-143d9b61e4f8.png)

- Obviously, these 2 mouse buttons do not need modifier keys(`Ctrl`/`Shift`/`Alt`).
 - - - - Expected behavior 👇
　

![216_28011743](https://user-images.githubusercontent.com/10995302/123553592-a6f09c80-d7ae-11eb-8517-2086f121d7be.png)

　
> I don't know what you think?
- Because I think this is the code added by the way on the original basis, there will be no unnecessary impact, 
  - I think it allows users to achieve a more selective and personalized /diversity/practicality configuration scheme.

**Comment by ssborbis** [comment]
Proper implementation will require a good amount of code overhaul. I could simply add a few more buttons to the options, but it might as well be done right. I'll reply here when I have something.

**Comment by dnknn** [comment]
> Proper implementation will require a good amount of code overhaul.

Oh, I thought it could be achieved with simple template copy .. :)
Don't worry at all, take your time.If it is troublesome, can also ignore this issue :)

**Comment by ssborbis** [comment]
@DenB10 

When you test your buttons here, do they actually show up as button 4, button 5?

https://unixpapa.com/js/testmouse.html

**Comment by dnknn** [comment]
> When you test your buttons here, do they actually show up as button 4, button 5?

- `which=?` or `buttons=?` , I don't understand at all. 
- but `button=?` is no problem at all, It shows right (I'm sure!)!

```js
		button=3	// Browser backward
		button=4	// Browser forward
```


![image](https://user-images.githubusercontent.com/10995302/124354014-72606300-dc3c-11eb-8584-5b0e1b3506b7.png)

**Comment by ssborbis** [comment]
Ok, I must be seeing something different due to OS or mouse drivers, etc.

**Comment by ssborbis** [comment]
I've been looking into this, and I'm not sure it's possible. I can't seem to find a way to listen for and capture buttons 4 and 5. They simply perform the back and forward functions of the browser.

**Comment by ssborbis** [comment]
I've added the hidden option `customSearchActions`. You can add custom actions via the console on the options page like so:

```
userOptions.customSearchActions,push({
     event:"mouseup",
     button:3,
     altKey:false,
     ctrlKey:false,
     metaKey:false,
     shiftKey:false,
     action: "openBackgroundTab",
     folder:false
});
saveOptions();
```

The option is an array of custom search actions in the format above. The previous example sets button 3 ( back button ) to open search engines to background tabs.

Valid actions are `openFolder,openCurrentTab,openNewTab,openBackgroundTab,openBackgroundTabKeepOpen,openNewWindow,openNewIncognitoWindow,openSideBarAction,keepMenuOpen,noAction`

You can also set keyboard buttons to hold during the mouse click for additional actions. 

Set `folder: true` for custom actions on folders.

If you need help setting things up, let me know. It will be a while before I have any kind of UI, if ever.

**Comment by dnknn** [comment]
> I can't seem to find a way to listen for and capture buttons 4 and 5. They simply perform the back and forward functions of the browser.
> 
> (edit) That's the case in Firefox. Chrome appears to handle them.

I only know that to prevent the default behavior, need to add a `event.preventDefault();` statement

**Comment by dnknn** [comment]
> I can't seem to find a way to listen for and capture buttons 4 and 5. They simply perform the back and forward functions of the browser.

@ssborbis 
Okay, I think about it, I know the reason, sometimes the reason for effectiveness or inefficiency lies in the difference between `mousedown` and `mouseup`.

# `mousedown` ⚔🆚 `mouseup`

`button:3/4` 's browser default behavior uses `mouseup` , Instead of `mousedown`.

And our ContextSearch uses the mouse action of `mousedown` , 
So of course, even `event.preventDefault();` cannot prevent the default behavior.

### Implementation plan
If the realization plan is to be perfectly realized, you can only set up a separate mouse action, that is, `mouseup` can perfectly use `button:3/4`

```js
addEventListener(`mouseup`,e=>	{
	.....
});
```

**Comment by ssborbis** [comment]
Are you on a Windows platform then? Context menu / forward / back on mouseup vs mousedown? I've been developing on linux, which is mousedown.

**Comment by ssborbis** [comment]
I'm adding some code to try. I wish I had a virtualbox set up to test on Windows, but I currently don't.

**Comment by ssborbis** [comment]
Also, what browser are you on. I thought chrome, but I should check

**Comment by dnknn** [comment]
> Are you on a Windows platform then?

Yes, ❖Windows 10 , Never used Linux (not a developer)

> Context menu / forward / back on mouseup vs mousedown?

I do not understand you.

> Also, what browser are you on? I thought chrome, but I should check

Chrome/Chromium.

---


`button:3/4` will not work in `mousedown`, but will work at the moment of `mouseup` (when the mouse is released).

So, if your mouse `addEventListener` event uses `mousedown` to define `button:3/4`, then when you release the mouse, the system default behavior (i.e. forward/backward) will be triggered again.

And if it is `addEventListener('mouseup',e=>{` , there is no problem, It's just that the event occurs when the mouse is released.

At least in Windows and Chrome browsers, this behavior may help you understand the specific meaning!

**Comment by ssborbis** [comment]
I tested with chromium on a windows machine. The latest dev code seems to work fine using the example above ( back button )
