### ISSUE TITLE
Sugesstion for a better search action.

### ISSUE THREAD

**Issue by Marvinoo** [ssborbis/ContextSearch-web-ext#356]
The `<<Search all>>` item on top of the search items inside folders is good and everything, but would it be better to remove it and  make the multi-engine search process work when 'left mouse-double clicking' on the folder itself (?) We won't lose any functionality, plus, the sub-menus will be less cluttered. Thank you.

**Comment by ssborbis** [comment]
Did all your folders default to the 'block' layout? Or did you set them to 'block'?

Check CS Options -> Search Engines -> (folder) -> Group Layout

**Comment by Marvinoo** [comment]
It's default to 'Block'. But this is out of my question. All I'm asking for is to : 
1. Allow hiding / removing the `<<Search all>>`item that you created on top of the search engines inside folders. 
2. Add option to allow searching all the engines inside the folder by double left-clicking the folder itself.

**Comment by ssborbis** [comment]
Ok, you're referring to the Context Menu, correct?

> Now the 2nd request is all I ask for. (Just allow the multi search by double clicking with left mouse on folder)

The context menu doesn't support double-click events, or any click events on folders. The <<Search All>> option is the compromise.

**Comment by dnknn** [comment]
> Just allow the multi search by double clicking with left mouse on folder
@Marvinoo 

		clicking  ⚔ double-clicking 
		
- But have you ever thought about it? When a single click and a double click act on an element at the same time, how do you think it can be achieved?
The dblclick event will also generate a click event. If both of these events are applied to the same element, problems can arise.
Obviously, you need to add a time function in the code to determine whether you click or double-click, but obviously, this can easily bring negative effects...Bug...


- Existing features, why don't you try in depth first?
	 * Why don't you try to use the `right` or `middle` mouse button, or more?

![image](https://user-images.githubusercontent.com/10995302/124132809-c7bd3880-dab3-11eb-8f97-20fd2d928502.png)

**Comment by Marvinoo** [comment]
Well.
> But have you ever thought about it? 

Not before now but it turns out you're logically correct about the double click part. No that's a Mozilla problem. 

Aside from that, the behaviors you're pointing out to here, should these actions executed when I make the corresponding clicks on the items inside the folder or on the folder itself? Because I tried both but none of them worked. 

![image](https://user-images.githubusercontent.com/45720537/124138219-b6aa0280-da86-11eb-9b81-39f1ac8012e3.png)

**Comment by dnknn** [comment]
> Because I tried both but none of them worked.

you're referring to the Context Menu, correct?

If so, please close this issue, because of powerlessness/no way, It doesn't support anything other than one click.

**Comment by ssborbis** [comment]
@Marvinoo 

Those folder options are a mistake. They were copied over from the quick menu's template. They have no effect. I'll remove them
