### ISSUE TITLE
Request : Add new icons for toolbar button

### ISSUE THREAD

**Issue by Marvinoo** [ssborbis/ContextSearch-web-ext#357]
The current toolbar button icon doesn't look the best ![image](https://user-images.githubusercontent.com/45720537/125285431-ed033f80-e31a-11eb-9a78-0935df4b0bd7.png) (kinda looks basic) IMO. Can you please add some nice icons to select from?

**Comment by dnknn** [comment]
On the contrary, I think it is beautiful/simple/good-looking/personalise!!!

If want to support user replacement, should add optional options instead of replacing changes.

**Comment by Marvinoo** [comment]
![pngwing com(1)](https://user-images.githubusercontent.com/45720537/125304550-fc3fb880-e32d-11eb-957e-04238943b5fa.png)

**Comment by ssborbis** [comment]
I might be able to add an option to set it to whatever you want. I'll look.

**Comment by Marvinoo** [comment]
> 
> 
> I might be able to add an option to set it to whatever you want. I'll look.

Yes please. This is a better idea thank you so much.

**Comment by ssborbis** [comment]
The basics are in the dev branch for testing

![Peek 2021-07-14 10-23](https://user-images.githubusercontent.com/24310997/125648251-3825e022-36cc-4999-a2e7-d7fcdf17d9a0.gif)

**Comment by dnknn** [comment]
@Marvinoo Now your wish has come true, but can you show us how beautiful your icon is ^_^?

**Comment by Marvinoo** [comment]
> 
> 
> The basics are in the dev branch for testing
> 
> ![Peek 2021-07-14 10-23](https://user-images.githubusercontent.com/24310997/125648251-3825e022-36cc-4999-a2e7-d7fcdf17d9a0.gif)

Hmmm looks great!! but how can I install the dev version? I'm willing to test that ryt now

**Comment by Marvinoo** [comment]
> 
> 
> @Marvinoo Now your wish has come true, but can you show us how beautiful your icon is ^_^?

https://www.flaticon.com/search?word=search&type=icon&license=selection&order_by=4

may be this one =P  https://www.flaticon.com/free-icon/search-engine_3672404?term=search&related_id=3672404

**Comment by Marvinoo** [comment]
Tested latest version and worked great..
Will you make the icon in context menu also changeable?

**Comment by ssborbis** [comment]
> Will you make the icon in context menu also changeable?

Cant be done.
