### ISSUE TITLE
Required value 'version' is missing or invalid.

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#358]
![image](https://user-images.githubusercontent.com/10995302/125707283-a7de0f13-30eb-45d0-8bdf-d72098d4a313.png)

# ❌ error 🚫: 
> Required value 'version' is missing or invalid. It must be between 1-4 dot-separated integers each between 0 and 65536.

- https://developer.chrome.com/docs/apps/manifest/version/

So I have to manually change the version number, otherwise it cannot be updated.
I changed it to `1.30.1`

**Comment by ssborbis** [comment]
use the chrome manifest or change the value ( same difference ). Firefox allows letters, thats what I'm developing on
