### ISSUE TITLE
Bug and suggest for Recently Used

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#359]
![image](https://user-images.githubusercontent.com/10995302/125708763-b7dd63f4-4403-487c-8a08-87e214282434.png)	Chrome86

- Bug: for example:
	* You click 1️⃣ 5 times,
	* then, You must click 2️⃣ 5 times too, otherwise cannot back.

- The best advice:
	 * Why not make it into the form of switching for 1️⃣button ?
	 	* click 1 : RecentlyUsed
	 	* click 2 : back
	 	* click 3 : RecentlyUsed
	 	* click 4 : back
		* .........

**Comment by ssborbis** [comment]
got it

**Comment by ssborbis** [comment]
have you tried the new option to show recently used as a folder at the top of the menu?

**Comment by dnknn** [comment]
> have you tried the new option to show recently used as a folder at the top of the menu?

In the latest version, I checked/tried all the options at the time, but I don't know which one you are referring to. Can you take a screenshot?

**Comment by ssborbis** [comment]
![recent](https://user-images.githubusercontent.com/24310997/125991372-6183378c-0fc0-414f-a616-ed30a1e7d781.png)

![recent](https://user-images.githubusercontent.com/24310997/125991390-f0d4e02a-9386-4b02-897b-8379293aa699.gif)

**Comment by dnknn** [comment]
> [Thanks for the screenshot, I understand now, when I saw this option, I don't know its specific meaning.](https://user-images.githubusercontent.com/24310997/125991372-6183378c-0fc0-414f-a616-ed30a1e7d781.png)

**Comment by ssborbis** [comment]
Ok to close this issue?
