### ISSUE TITLE
Bookmark folder for context menu invalid when switching to included locales

### ISSUE THREAD

**Issue by ssborbis** [ssborbis/ContextSearch-web-ext#36]
I noticed when using DenB10's French translation, the bookmark folder for the context menu used a different name causing the old folder to no longer be recognized. I have code in 1.4.9+ to rename the folder but it has a small bug making it non-functional. Will be fixed in the next release.

**Comment by DenB10** [comment]
What's the problem? The bookmark folder works well by me, just changes in this folder (separators, new subfolders) need a browser restart.

**Comment by ssborbis** [comment]
Bug is the required restart. Had the wrong function name for rebuilding the context menu. Menus get rebuilt on restart so not a critical bug.

**Comment by ssborbis** [comment]
I'm still not seeing the correct behavior after fixing the function name. I can't debug right now because my addon-debugging window won't open for some reason.

**Comment by ssborbis** [comment]
Ok I got it. I was using a terms query instead of an explicit title query causing the wrong bookmark to be renamed.
