### ISSUE TITLE
Can 1 option be added?

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#360]
![217_15083218](https://user-images.githubusercontent.com/10995302/125709728-56c5751e-feaf-4a49-9788-3fb94eaa551f.png)

👆, can you add an option to hide/disable it completely?

> No why, I like to add it manually, usually I don't add engine casually , ^_^

**Comment by ssborbis** [comment]
I think you can simply hide it with css
```css
#addEngineBar {
    display:none;
}
```

**Comment by dnknn** [comment]
> I think you can simply hide it with css

I even forgot CSS, haha.

But it's not a purely local element, right? CSS just hides it on the surface, not really disabling features (for example, network requests adapt to the search engine of the current website)
