### ISSUE TITLE
Bug:  edit tool icon can not works

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#362]
![image](https://user-images.githubusercontent.com/10995302/125712524-fc666727-d818-479f-9adb-225cf6c4c597.png)
👆 it can not works, but no problem with the 1.29 version.

![217_15094641](https://user-images.githubusercontent.com/10995302/125715014-fe77091c-af00-4c90-af39-3da6a6875499.png)

**Comment by ssborbis** [comment]
it's disabled for now while I work out some issues

**Comment by ssborbis** [comment]
Partially enabled now for resizing the qm. No rearranging yet.

**Comment by ssborbis** [comment]
Everything should be functional now in the dev repo / pre-release.

There is also an override to allow rearranging without using the edit button 

`alwaysAllowTileRearranging`
