### ISSUE TITLE
The latest version is worse and has too many problems .....

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#363]
> At least on Chrome.  For example: 

[Bug](https://user-images.githubusercontent.com/10995302/125716712-a4b5fac8-9792-42ea-a085-c43e2837f75e.gif)

Therefore, I strongly recommend that you have time to try to use `display:flex` to layout.
Because `flex` is almost perfect, no matter what platform or screen size, it is adaptive and flexible...

　
　
-------------------------------

In addition, it seems that the performance of the latest version is too low. It seems that the performance of the computer will be greatly reduced,
The CPU has increased significantly because there is no such problem in version 1.29.
For example, in the translation site, very stuck, almost collapsed
- - https://translate.google.com/

Is there too many event listeners?

![217_15101044](https://user-images.githubusercontent.com/10995302/125717039-5692d2a5-a848-4072-a835-fd3cff7b401b.png)

> so, I think I should go back to version 1.29, the latest version cannot be used normally 😭-_-😢

**Comment by ssborbis** [comment]
I'm not seeing these issues. Send me your config

**Comment by dnknn** [comment]
> I'm not seeing these issues. Send me your config


No, no, Not the reason for config !

I used brand new data to test, and the result was the same.

Because I had the same idea as you at the beginning, I thought it was the configuration data that polluted/interfered with the normal operation of the latest version.

So I uninstalled completely, restarted the browser, and then installed a new test (initialized, not imported my own configuration), the result is the same.

**Comment by ssborbis** [comment]
I'm trying on Chromium Version 91.0.4472.114 and I'm not seeing those problems.

Did you email me your config? I don't see it in my inbox

ssborbis@gmail.com

**Comment by dnknn** [comment]
![217_18185750](https://user-images.githubusercontent.com/10995302/126064606-8bd0fb49-a920-4325-8f4b-b3d7459f35b1.png)

I know the reason for this, but I haven’t changed it, it’s become `1` for some reason.

**Comment by ssborbis** [comment]
I added a few checks for bad values when loading the config now. This should help prevent some config corruption like you experienced. I've had it happen too, I just haven't been able to narrow down the exact cause.
