### ISSUE TITLE
Search engine manager page, difficult to drag-drop sorting

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#364]
Search engine manager page, difficult to drag-drop sorting
Especially drag and drop folders, too difficult to operate, or misoperation, 

- 1. When dragging, flashing. 
	* I think it may have something to do with DPI. Some systems will have a slight difference of about `0.001px` after the system text is displayed, Although there is only a difference of `0.001px`, it will make the system unable to determine whether the mouse is hovering over the element or the border of the element, so the `event flashing`
	which causes the system to judge the pixels of the px and there is a difference, so flickering occurs.
	* To avoid flickering, we can increase the height when dragging and hovering, or solve it with a delay of `30ms`.

- 2. the success rate is too low.... 
	* For example, I want to drag and drop folders to sort, but the result is to move to the inside of the folder.

--------------------
I think the root cause of these problems should be the same, but I can't find out. 
In order to make the system 100% accurately determine whether the mouse is hovering over the element or the element boundary,
I think we can optimize, for example, when dragging and hovering, relax or add a little delay.

I think when dragging, a `placeholder div` should be created temporarily, 

It should be around `4px` in height for better operation and drag sorting!

**Comment by ssborbis** [comment]
can you make a gif of the bug? I'll take a look

**Comment by dnknn** [comment]
> @ssborbis  can you make a gif of the bug? I'll take a look

Remark: 
> This is the v2.91 version, and then I customized the CSS. 
But it doesn't matter, because I tested the initialized ContextSearch version on another brand new browser, and the results are exactly the same. In addition, in the latest ContextSearch development version, it seems even worse. It is more difficult to move folders for sorting. .


![demo](https://user-images.githubusercontent.com/10995302/127929649-b3c9d797-18b4-4377-80c6-f880ec1645c7.gif)

**Comment by dnknn** [comment]
> @ssborbis  can you make a gif of the bug? I'll take a look

Remark: 
> This is the v2.91 version, and then I customized the CSS. 
But it doesn't matter, because I tested the initialized ContextSearch version on another brand new browser, and the results are exactly the same. In addition, in the latest ContextSearch development version, it seems even worse. It is more difficult to move folders for sorting. .


Dragging and dropping the engine is still relatively easy, but it is more difficult to drag and drop folders.
For example: the following 4 are all **folders**, and they are close to each other.
	A
	B
	C
	D

Now I want to move the `X` folder to sort between them, it is very difficult, and it is easy to trigger the movement to the inside of the folder, instead of the expected behavior of sorting.

　　　　　　

![demo](https://user-images.githubusercontent.com/10995302/127929649-b3c9d797-18b4-4377-80c6-f880ec1645c7.gif)

**Comment by ssborbis** [comment]
Not sure if something changed in chromium, or it's the slightly altered code in the dev repo, but this issue seems better now.

**Comment by ssborbis** [comment]
@dnknn 

Re-open if this is still a problem.
