### ISSUE TITLE
Weird bug when searching from an extension page

### ISSUE THREAD

**Issue by Marvinoo** [ssborbis/ContextSearch-web-ext#365]
Well, I'm using this [RSS Feed reader](https://addons.mozilla.org/en-US/firefox/addon/feedbroreader/) on daily basis for some articles reading. The extension page appears to have this url > `moz-extension://1972f47b-3cc2-46a1-99e6-3a93abdd97c1/reader.html`
Now the problem is when I try to search a _plain normal text_  like this > 
![image](https://user-images.githubusercontent.com/45720537/126145655-04fc443c-b2d8-44fb-b7b1-529eb204b934.png)
the Search item from ContextSearch is gone, but when I activate this option > `Enable on images `
![image](https://user-images.githubusercontent.com/45720537/126146002-c56da1c3-8a5f-47c1-ab26-2f2e4e4be1ad.png)
the item will appear 
![image](https://user-images.githubusercontent.com/45720537/126146220-97bac85d-995d-42a6-a43e-74899ef44162.png)
and if I deactivate that option again, the item will disappear.

So I think there's a bug that makes ContextSearch treat the normal text I want to search as an Image.

**Comment by ssborbis** [comment]
I doubt addons can inject content script into other addons' extension pages. What you're probably seeing is some fallback code because the bulk of the CS code can't be used on that page.

**Comment by Marvinoo** [comment]
> 
> 
> I doubt addons can inject content script into other addons' extension pages. What you're probably seeing is some fallback code because the bulk of the CS code can't be used on that page.

I don't understand as I've no programming background, but if this cannot be fixed, never mind then!

**Comment by ssborbis** [comment]
@Marvinoo Nope, nothing I can do about it. Each addon has it's own address ( moz-extension://...) and those pages can't be changed by another addon. It's a security feature.
