### ISSUE TITLE
regex to remove leading zeroes?

### ISSUE THREAD

**Issue by robertheadley** [ssborbis/ContextSearch-web-ext#366]
What is the correctly formated regex to remove leading zeroes from my search string? 
A regex to also remove leading and ending whitespace and anything before and after the whitespace would also be great.

**Comment by ssborbis** [comment]
Something like this maybe? What's an example of your search string?

"(^\\s*0*\\s*)", ""

**Comment by robertheadley** [comment]
That absolutely does work for the leading zeroes.
The search string normally looks like "0012345678"
Sometimes, because the fastest way to select is to double click, if the div's are set up wonky, I will get a bunch of UI garbage included with it, so that is why I asked about stuff before and after spaces.

That might look like 
"garbage 001234567 garbage"

I only ask because taking the time to manually select really slows down my flow.

I appreciate your help very much.

**Comment by ssborbis** [comment]
You can chain the regex, one per line, if you need more precision.

You might try ... 
```
".*\\s+(\\d+).*", "$1"
"0+", ""

```

The first line removes anything before and after a string of numbers if there's a space present.
The second line removes leading zeros

**Comment by robertheadley** [comment]
This is resolved to my satisfaction. Thank you.
