### ISSUE TITLE
"Firefox could not download the search plugin from: https://opensearch-api.appspot.com/?..."

### ISSUE THREAD

**Issue by sign-in-smth** [ssborbis/ContextSearch-web-ext#367]
hello :)

i encountered this error just today trying to add a new search engine. 
tried another engine, to see if it happens again, and it did.
it's at very last step, after i finished all the settings in Advanced -> Create, and hit Add
[pic](https://i.imgur.com/C0GPg9v.png)

**Comment by ssborbis** [comment]
Check again. There was an issue with my server.

**Comment by sign-in-smth** [comment]
yes, it works now. sorry for the trouble, just thought it was something))

wish you all the best, dear sir. five years later this is still my favorite ff addon ever.
thank you so much for the work you've been doing !!

**Comment by ssborbis** [comment]
Cheers! 

And thanks for the bug report. I'd never check that particular function if you hadn't said anything. There's a lot this addon does that I never do in day to day usage.
