### ISSUE TITLE
[Feature suggestion] Open Quick Menu only when modifier key is pressed

### ISSUE THREAD

**Issue by kubalav** [ssborbis/ContextSearch-web-ext#368]
I miss option able to open the quick menu only when a modifier key is pressed.
Is it possible to add that option?

**Comment by dnknn** [comment]
- This requirement is meaningless, for the following reasons:
	1) At present, ContextSearch can be very convenient, When selecting text: 
		you can use the middle-mouse, 
		you can use the hotkey (`E` or `CtrlE` `AltE`)
	2) Just use modifier keys to trigger, this has serious compatibility problems, and you will still withdraw your thoughts in the end.
	> If you only use this extension or don't have any other usages, then it may be possible, but if you use it normally, this kind of operation will have considerable problems.

A summary of my personal opinions...^_^

**Comment by kubalav** [comment]
I don't want to open automatically, because I don't search every time, I select text.
I don't want to open via middle button, because it is little slower than select when modifier key is pressed.
The same reason for hotkey.

Hotkey collision occur even now.

**Comment by dnknn** [comment]
Now that the modifier keys are pressed, adding another key is also very straightforward?

![218_22002503](https://user-images.githubusercontent.com/10995302/130328459-5d02387c-b135-4e93-a841-26b0ba0bb6bd.png)

I have such a configuration, I think it is very easy/fast, almost without any inconvenience and compatibility issues.

**Comment by kubalav** [comment]
I also use keyboard hotkey now. I reasoned that using it just, when necessary, would be more efficient.

**Comment by ssborbis** [comment]
@kubalav 

Are you wanting to hold a modifier key ( shift for instance ) then select text and have the menu open when you release the left mouse button?

**Comment by kubalav** [comment]
Just like that.

**Comment by ssborbis** [comment]
@kubalav I'll see what can be done.

**Comment by ssborbis** [comment]
Good suggestion; I like it.

Changes in the dev repo. 

![auto](https://user-images.githubusercontent.com/24310997/131335705-b631b633-ecd8-4fc3-9022-4a7cc7992292.png)

**Comment by kubalav** [comment]
**It's awesome!** 
It' working very well 👍

**THANK YOU**
