### ISSUE TITLE
Feature request: Add option to rename [Search for] to anything of my choice.

### ISSUE THREAD

**Issue by Marvinoo** [ssborbis/ContextSearch-web-ext#369]
Simple yet very needed option. Please add it so I can rename the item in context menu to anything I want for it. Thanks a lot guys.

**Comment by ssborbis** [comment]
I'm curious, what would you change it to?

**Comment by Marvinoo** [comment]
I want to trim it to just 'Search' and take down 'for'. I'd also see if I come up with a good different term for it since I have few other extensions that has the same 'Search for' item name in context menu. If it's not possible we're still good and thanks for listening.

**Comment by ssborbis** [comment]
In the dev repo. 

![title](https://user-images.githubusercontent.com/24310997/132098765-bd6b53b8-0a01-4ab1-8acf-180a57e76a91.png)

**Comment by Marvinoo** [comment]
Looks awesome but I really don't know how to use/install the dev version? Can you please tell me?
I tried by Code > Download Zip, but Firefox add-ons manager says Zip file is corrupted when I tried to install it from there 
And can I know if these changes will be pushed to the official release version soon?

**Comment by ssborbis** [comment]
> And can I know if these changes will be pushed to the official release version soon?

Soon? No. I probably wont get a new release out until November. I'll throw a new signed beta up in releases. I could use more beta testers anyway.

Be sure to backup your config before installing

https://github.com/ssborbis/ContextSearch-web-ext/releases/tag/1.30a2

**Comment by Marvinoo** [comment]
Thank you so much indeed. it's so great now
