### ISSUE TITLE
New name for context menu item doesn't work on certain page

### ISSUE THREAD

**Issue by Marvinoo** [ssborbis/ContextSearch-web-ext#370]
The newly added option that allows user to rename the 'Search with' item in context menu doesn't work on pages like (i.e. https://raw.githubusercontent.com/dannycolin/fx-compact-mode/main/userChrome.css)
I've renamed 'Search with' to 'Search' and it works fine with all webpages I surf everyday but I noticed it doesn't work on the aforementioned page. And here is a screenshot from firefox shows the item has the unchanged name.

![image](https://user-images.githubusercontent.com/45720537/132969366-c1ff80ee-c8d4-4bc5-80eb-a0b3944cce74.png)

Thanks.

**Comment by ssborbis** [comment]
I forgot there's some fallback code for when selected text cant be determined. I'll see about updating that

**Comment by ssborbis** [comment]
This will be rolled into #384 and #403
