### ISSUE TITLE
The selected text in input textarea got unselected once the Quick Menu popups

### ISSUE THREAD

**Issue by c02y** [ssborbis/ContextSearch-web-ext#372]
When I select some text in an input texarea like Google search box or forum reply input text field, once the Quick Menu popups, when I need to delete those text using Backspace, since that text is unselected automatically, I am not able to do that(In my browser, it goes to the previous page).

I already enable `Enable on textarea and input elements` in configuration.

This is similar to https://github.com/ssborbis/ContextSearch-web-ext/issues/371 , this add-on conflicts with normal shortcuts.

**Comment by ssborbis** [comment]
what version are on and what browser

**Comment by c02y** [comment]
Firefox v92 + ContextSearch v1.28.1
Vivaldi v4.2 + ContextSearch v1.28.1

**Comment by ssborbis** [comment]
I made some changes to the dev repo you can test. Be sure to backup your config first.

**Comment by c02y** [comment]
Close this issue, replied in https://github.com/ssborbis/ContextSearch-web-ext/issues/371
