### ISSUE TITLE
Excellent addon. Could "Group Search"function be added?

### ISSUE THREAD

**Issue by minshifu** [ssborbis/ContextSearch-web-ext#373]
Thank you for providing such an excellent addon. It is versatile and makes searching much easier. Could "Group Search"function be realized? That is, 2 or more search engines are put into one group( a folder) .And when that group is clicked, those search engines can be activated at the same time, thus realizing simutaneous searches. That would make searching more convenient in many cases.

Thank you and best wishes!

**Comment by ssborbis** [comment]
Fortunately, that feature is already built in.

If you're using the Quick menu, choose how you want to display tabs when searching all engines in a folder here
![qm](https://user-images.githubusercontent.com/24310997/134453397-cdb5de74-7abf-4adb-b84e-ba934a1ec290.png)

If you're using the context menu, enable this option to including a `<< search all >>` option to each subfolder and then set the folder search action.


![cm](https://user-images.githubusercontent.com/24310997/134453619-b5c98c34-e972-4962-a0ff-8c0dafdc58b0.png)

**Comment by minshifu** [comment]
> 
> 
> Fortunately, that feature is already built in.
> 
> If you're using the Quick menu, choose how you want to display tabs when searching all engines in a folder here
> ![qm](https://user-images.githubusercontent.com/24310997/134453397-cdb5de74-7abf-4adb-b84e-ba934a1ec290.png)
> 
> If you're using the context menu, enable this option to including a `<< search all >>` option to each subfolder ~and then set the folder search action~ (edit) Context menu searches default to open in background tab I think..
> 
> ![cm](https://user-images.githubusercontent.com/24310997/134453619-b5c98c34-e972-4962-a0ff-8c0dafdc58b0.png)

Thank you so much!
