### ISSUE TITLE
Could it work with coinmarketcap.com?

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#374]
I'm wondering if your fantastic add-on could work with the following site: https://coinmarketcap.com

My aim is to search for a ticker of a cryptocurrency, f.i. BTC stands for [Bitcoin](https://coinmarketcap.com/currencies/bitcoin/), ETH for [Ethereum](https://coinmarketcap.com/currencies/ethereum/) using your add-on. The tricky part is: when you type the ticker, let's take BTC as an example, into the search field (see top right corner of the above mentioned website), then it will show Bitcoin in the dropdown menu, where it's already selected. Pressing enter will lead you to the desired page.

But when I search through your add-on, then the search result for our example looks like https://coinmarketcap.com/currencies/btc/, while the correct address should be https://coinmarketcap.com/currencies/bitcoin/.

So I'm wondering if there is a way that your add-on can, so to say, resolve the search query "BTC" into "Bitcoin" in order to get the correct search URL?

**Comment by ssborbis** [comment]
Probably. Try some search code.

I got as far as this, but couldn't trigger the submit.

```

(async () => {
let divs = document.querySelectorAll('div');
let sb = [...divs].find(d => d.innerText === "Search");
sb.click();
let input = document.querySelector('input');
await new Promise (r => setTimeout(r, 500))
input.value = searchTerms;
input.dispatchEvent(new Event('change', { 'bubbles': true }));
})();
```

**Comment by sojusnik** [comment]
Thanks for trying!

On my side it looks like this:
![grafik](https://user-images.githubusercontent.com/1245718/134649114-236b3112-8d2a-4899-9435-7923aedc9883.png)

When searching for BTC, I receive https://coinmarketcap.com/currencies/BTC/ while the search dropdown menu is expanded. Pressing enter will get me to the right address. Would be great if the last step, pressing enter, also somehow could be automated.

**Comment by ssborbis** [comment]
try with the edit above

**Comment by ssborbis** [comment]
You should probably also change your template to simply `https://coinmarketcap.com/`

**Comment by sojusnik** [comment]
Thank you very much, that worked!

**Comment by sojusnik** [comment]
Rather more often, than less, the search with your code isn't working. Don't know where to look or what to tweak. Could you give a hint where the problem could be?

**Comment by ssborbis** [comment]
You could try increasing the timeouts or adding some checks that the page is ready for the next step in the code.

**Comment by sojusnik** [comment]
Actually, I think that it has to do with the width of the browser window. When it's wide and the search field in the upper right corner can be seen, then it works. But if you narrow the window, so that the search field turns into a lens, then it doesn't work.

**Comment by sojusnik** [comment]
Thanks for the tip with https://www.coingecko.com/en/searchbox!

The right element should be `div.search-container`, but I have no javascript knowledge to find out what else to modify in your code, so I have to rely on you.

**Comment by ssborbis** [comment]
```js
(async () => {
await new Promise (r => setTimeout(r, 100));
let input = document.querySelector('input');
await new Promise (r => setTimeout(r, 500));
input.value = searchTerms;
input.dispatchEvent(new Event('input', { 'bubbles': true }));
await new Promise(r => setTimeout(r,200));
input.dispatchEvent(new KeyboardEvent('keydown', {key:"Enter", keyCode:13, bubbles:true}));
input.dispatchEvent(new KeyboardEvent('keyup', {key:"Enter", keyCode:13, bubbles:true}));
})();
```

**Comment by sojusnik** [comment]
Thank you, that did it!
