### ISSUE TITLE
I want to add Yandex & Start page to the list

### ISSUE THREAD

**Issue by YandexSearchEngine** [ssborbis/ContextSearch-web-ext#376]
Hi,

I would like to add Yandex & Start page to the list, I tired to do so but i couldn't figure out how to do it.

Yandex.com
Yandex.ru
startpage.com

Regards

**Comment by ssborbis** [comment]
Open yandex.com, right-click the search bar, click `Add to ContextSearch`. Should be the same with the others

**Comment by ssborbis** [comment]
![yandex](https://user-images.githubusercontent.com/24310997/134785962-10386194-d06f-4450-88ec-e4cd368b54f6.gif)
