### ISSUE TITLE
Search actions for Omnibox search

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#378]
Recently, I've started to use the [Omnibox search](https://github.com/ssborbis/ContextSearch-web-ext#omnibox) a lot, thanks by the way for such an useful feature, and realized, that you can't define the [search actions](https://github.com/ssborbis/ContextSearch-web-ext#search-actions), when using the Omnibox search. Would really appreciate it, if you could add them.

I think that the following combinations are worth adding:
enter
shift+enter
ctrl+enter
alt+enter

**Comment by sojusnik** [comment]
That's a pity! Can we at least modify the default behaviour when pressing enter? At the moment, it's open in a new tab in the background on my system.

**Comment by ssborbis** [comment]
You can. It's under the Omnibox tab in settings

**Comment by sojusnik** [comment]
Can't find it. This is how it looks here:
![grafik](https://user-images.githubusercontent.com/1245718/136273332-95c93c35-4797-48e0-8090-f19666dd7fe2.png)

**Comment by sojusnik** [comment]
The alpha looks slick! Found the setting, works fine!

Will this alpha automatically upgraded to a new version through Firefox, when you'll do a normal release?

**Comment by ssborbis** [comment]
Yep, it should. If I make a new pre-release, you'll need to install that manually, however.
