### ISSUE TITLE
Searching brings up a blank page

### ISSUE THREAD

**Issue by SomeDude77** [ssborbis/ContextSearch-web-ext#381]
After I removed some search engines (both from firefox and contextsearch options) searching something shows a blank empty page. Only a few search engines still work, Google, duckduckgo and wikipedia, the rest do not...

**Comment by SomeDude77** [comment]
Not really, I removed a few wiki and google translate engines that I had added myself to Firefox.

[https://drive.google.com/file/d/1J257282kzADzZ8wOba-d82FfYG1XeX9J/view?usp=sharing](url)

**Comment by ssborbis** [comment]
Your config shows you have 4 ContextSearch engines

```
Google
YouTube
DuckDuckGo
Wikipedia (en)
```

You also have these apparently missing Firefox engines
```
reddit
RARBG torrents 
The Pirate Bay 
IMDb 
Prisjakt 
Amazon Search Suggestions 
Google Images 
Google Maps 
Urban Dictionary 
Google Translate 
Wiktionary (en) 
Wiktionary (sv) 
Wiktionary (de) 
Wiktionnaire (fr) 
Wikcionario (es) 
Victionarium (la) 
ویکی‌واژه (fa) 
Wikipedia (sv) 
Wikipedia (de) 
Wikipédia (fr) 
Wikipedia (es) 
Vicipaedia (la) 
ویکی‌پدیا (fa)
```

Are those missing Firefox engines still in the Firefox search bar?

**Comment by SomeDude77** [comment]
I see, thanks for the help and for the unique extension. Here's the updated and working config:

https://drive.google.com/file/d/1aboWK2s4f4cyEM-ykJJnf1oortsEAos7/view?usp=sharing

**Comment by ssborbis** [comment]
I think this is related to #383 and #410

Hopefully, the latest 1.32.3 fixes that issue.
