### ISSUE TITLE
Bug: Firefox Search Engines load Blank Tabs.

### ISSUE THREAD

**Issue by MintMain21** [ssborbis/ContextSearch-web-ext#383]
The following bug only occurs when using Firefox Search Engines (That is, search engines the add-on fetches from the Firefox Search bar) from the Context Menu on Mozilla Pages (Firefox Add-Ons, The Add-On store, etc). In short, searches made under these conditions will open in blank tabs and fail to actually load a search. This bug is not duplicated when using search engines manually added to Context Search web-ext.

**Comment by ssborbis** [comment]
I saw the same problem when using the toolbar menu search from the CS options page. I think there's a bug in the browser.search.search API's promise fulfillment ( Firefox engines ). There is a fix in the dev repo. It required a small delay between the opening of the blank tab and performing the search.

**Comment by MintMain21** [comment]
Still unresolved as of November 19th. I keep on thinking it's resolved and closing it.

**Comment by MintMain21** [comment]
So, here's my update. As of November 30th 2021, it seems as if the initial search from a Mozilla Page with a Firefox Search Engine will fail, but a second attempt with a different search term will succeed, while future attempts to use the initial search term with fail. All this is undone, of course, when the extension/context menu refreshes, in which the bug start over again (in addition to the bug wherein the context menu will NOT auto-generate on Mozilla pages). 

We're getting there. That's the important part.

**Comment by ssborbis** [comment]
So we're on the same page ( literally ), what URL are you on when the menu fails?

**Comment by MintMain21** [comment]
about:addons is where I typically test this, but I've also encountered it on https://addons.mozilla.org.

**Comment by MintMain21** [comment]
#384 seems to be tied to this issue, and likewise in the pre-release this issue is absent alongside the context menu issue. Like the other one, I'll close this if I don't encounter the bug for a week.

**Comment by MintMain21** [comment]
Bug occurred when searching a Firefox Search Engine through a normal website, not a Mozilla Page (to be specific, both https://pianosheetmusiconline.com and Github itself). Can't close this issue yet, but I will rename it to reflect that it's no longer exclusive to Mozilla Pages. May still be tied to the aforementioned Context Menu Bug.

**Comment by ssborbis** [comment]
Let me see if I understand the issue. If you select text, open the context menu, and search using a Firefox engine ( tagged FF in the search engines manager ), the search won't complete? Just opens a blank tab?

**Comment by MintMain21** [comment]
Yes, that is correct. That is the bug in short. It is not exclusive to Mozilla Pages (at least not anymore). 

Upon further testing, the behavior seems identical to before, wherein upon loading/reloading of the context menu a initial search made with a Firefox Engine (or a FF Engine as marked in the manager) will blank, while secondary searches made either with different engines and/or different search terms will succeed. 

There are a few workarounds of course,

A: Make all initial searches with Extension saved engines (without the FF Tag)

B: Migrate all search engines via the JSON file as explained in the settings manager (I've only found this particularly helpful on Linux, where file management is more transparent)

or

C: Manually migrate all individual FF Search Engines (and all future search engine additions) exclusively through the Context-Search Web Ext itself (in other words, use the Extension's Context Menu to add the search engine to the extension, then select "Yes" when offered the ability to add it to Firefox Proper).

All of these are workarounds I can apply, but I feel the average user will sooner default to the migrated search engines as they are, and I want this extension to work effectively for them as well as for "power-users" like me. Furthermore, by default I find this extension's ability to handle FF Engines more versatile than similar extensions like Swift Search Selection (for example, in SSS you have to manually migrate FF Engines to sort them into folders and search in the background while CSWE offers this for FF and CSWE search engines). As a result, it's a shame to see this extension's excellent functionality held back by what I hope is a minor bug. 

Sidenote: So far I've been testing the latest update in Linux, I have yet to test for the bug in Windows. Will report back with updated info.

**Comment by ssborbis** [comment]
I cannot seem to trigger that bug. Can you give me a very specific example I can try?

I'm looking at the code to execute a firefox engine search, and it's pretty straight-forward. The only thing I see is I added a small delay as a workaround for some glitchy behavior in the API. I wonder if a longer delay would solve your issue. Are you in a position to sideload code for testing?

**Comment by ssborbis** [comment]
I updated the dev repo with a longer delay in the firefox search API code.

**Comment by MintMain21** [comment]
I'm having the damnedest time trying to recreate this on purpose, let alone figure out what causes it, but I did manage to record the bug in action, so that you can see what I'm talking about.

https://user-images.githubusercontent.com/91362684/146323956-76a669e6-fc7c-463e-8f1e-0f3f5381482f.mp4

Seems more prevalent on Linux (where I recorded this) than on Windows, but this could be the result of the specs of one laptop vs the other (rather than the actual Operating System). Alternatively, it could be the result of my lowered SWAP on Linux and/or certain about:config changes I made on Linux.

**Comment by ssborbis** [comment]
> I'm having the damnedest time trying to recreate this on purpose

I know that frustration all too well

I thought I may have triggered it once. I'll keep trying.

**Comment by ssborbis** [comment]
I'm almost certain it's the delay I mentioned earlier. If I remove it completely, I get a blank new tab every time. 500ms delay and everything works as it should. I originally had a 50ms delay.

**Comment by ssborbis** [comment]
Some better code in the repo now for testing. It watches the tab status for 'complete' before it tries the Firefox search API.

Good results so far.

**Comment by ssborbis** [comment]
I dropped a new release. Hopefully that fixes it

**Comment by MintMain21** [comment]
The bug is still present, but significantly less frequent. At this point, it seems the best workaround for when the bug occurs is to just search again and again with the same engine and phrase until it does work. Not ideal, but better than nothing. And again, importing the engines into the extension proper (be it individually, or in bulk via JSON file) is the best workaround.

It also appears that like the context menu reloading, that the bug is more likely to occur when system resources are limited (so, for example, making multiple queries in quick succession is more likely to activate the bug than otherwise).   

I'm not sure if I should close this, as there are still improvements that can be made, but I feel like the issue is no longer as pressing as it once was. It's just something that needs improvement in future releases.

**Comment by ssborbis** [comment]
Leave it open I'll try running a stress test while I see if I can trigger the bug.

**Comment by ssborbis** [comment]
Ok, I've got a repeatable cause.

I put several Firefox engines in a folder, and used the "Search All" button to search all-at-once. Only the first tab loads properly.

**Comment by ssborbis** [comment]
The problem is still the same as always. The search API needs a delay, but there's no accounting for how long of a delay. I thought fully loading the tab would be all that's necessary, but it still requires a delay for some reason. I'm putting this one on the Mozilla devs.

I'm pushing a new release to AMO, v1.32.3 with a built-in 500ms delay. This may not work for everyone, and eventually I'll have to add an advanced option. When in publishes, see if that takes care of your issues.

**Comment by MintMain21** [comment]
I have an idea for an advanced (or not so advanced) option in the event we can't figure out a proper work-around.  Either a way to disabled FF Engines in Context Web Search Ext (similar to the option to ONLY display FF Engines, but in reverse), an option to import individual FF Engines from the extension's settings menu without having to fish for the JSON file, or both. 

Maybe neither of these options are feasible, but on paper at least they sound like a decent compromise.

**Comment by ssborbis** [comment]
> an option to import individual FF Engines from the extension's settings menu without having to fish for the JSON file

Not possible. The API doesn't allow an addon to see the 'guts' of a search engine. Only the name and icon.

> a way to disabled FF Engines in Context Web Search Ext

Well, technically, you *can* select all FF engines and hide them from CS, so they don't appear in the menu.

**Comment by MintMain21** [comment]
Trying version 1.23.3, and I think we did it. We finally fixed it. I've tried and tried to make the bug manifest, but to no avail. I'll keep my eyes peeled for minor occurrences, but I think this takes cares of it.

Will close in one week if the bug doesn't manifest again, or if it doesn't prove to be a nuisance.

**Comment by ssborbis** [comment]
Phew!

The surest way to trigger the bug I found was to do a folder search with a bunch of FF engines. I still think a stressed machine may still trigger the bug, due to it being a timing issue, but I haven't had a blank tab yet with the 500ms delay.

Good luck
