### ISSUE TITLE
Fail of search engine editing

### ISSUE THREAD

**Issue by Zack11111** [ssborbis/ContextSearch-web-ext#386]
Hi
I have an issue again in the same site (bitru.org). I want to change word "seeders" to "size" in Template field. But, after saving the edit it works fine just until I restart browser. After restart there is "seeders" again. Same problem in both Chrome and Firefox. Could you help me to fix the issue?

> Could anyone help me to add this search engine http://bitru.org/browse.php?s=&sort=seeders&tmp=&cat=&subcat=&year=&country=&sound=&soundtrack=&subtitles=#content

- right click the search input, 
- click `Add custom search engine`, 
- click `Advanced`
- in the `Template` field, replace the text to: `http://bitru.org/browse.php?s={searchTerms}&sort=seeders#content`
- click `Add`

_Originally posted by @githubeing in https://github.com/ssborbis/ContextSearch-web-ext/issues/67#issuecomment-489109550_

**Comment by ssborbis** [comment]
Lets see whats happening when you save the template

Open the search engine manager and edit your engine, then click the save button

Open the console from the CS options page (Ctrl+Shift+K in FF, Ctrl+Shift+I in Chrome ) and type this in the console.

```js
JSON.stringify(userOptions.searchEngines.find(se => se.title === "bitru"))
```

Replace "bitru" for whatever the actual name of the engine is in your config.  Post the output

**Comment by Zack11111** [comment]
VM79:1 Uncaught ReferenceError: userOptions is not defined
    at <anonymous>:1:16

**Comment by Zack11111** [comment]
In Firefox's Console:

"{\"description\":\"\",\"hidden\":false,\"icon_base64String\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAv0lEQVQ4jaWTsQ0CMQxFre9QMwKjMAIjMAITnK5gAEaAM7qGhhEYhREYIIVpiGRyTpSApTTRz8v3d0JUKQH0Cow1TbUEUAFUmB//AQAlImp2k6xbwGfvkGBuTcBTQtgKoDFGjTHqQKw5qAixt1YBpUysKAGOWLkOJIRT8bAF5MvkMTYBUgs5YBkg874HIMznL8CF+f6TA0vsycCdwsy8S4KB2F0C6Ey0cQE3orU7spZHtJhI1lL3f0huJuBV070BHTcoahkAHckAAAAASUVORK5CYII=\",\"icon_url\":\"data:image/x-icon;base64,AAABAAEAEBAAAAAAAABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP///wD///8A////AP///wAAAKAPAgKi/wICoe////8A////AP///wD///8A////AP///wAAAAAA////AP///wD///8A////AP///wACAqL/AgKhnwICov8CAqL/AgKi/wICov////8AAgKif////wD///8AAAAAAP///wD///8A////AAAAoA8CAqL/AgKi/wICov8CAqL/AgKi/wICov8CAqL/AgKi/wICov////8A////AAAAAAD///8A////AP///wABAaJPAgKi/wICov8DAH3/AwB9/wMAff8DAH3/AwB9/wMAff8CAqL/AACjH////wAAAAAAAgKi/wICov8CAqGfAgKi/wICov8CAqL/+/v7//v7+//7+/v/+/v7//v7+//7+/v/AgKi/wICov////8AAAAAAP///wD///8AAgKgrwICov8CAqL/AgKi//v7+//7+/v/AwB9/wICov/7+/v/+/v7/wICov8CAqL/////AAAAAAD///8A////AAICoF8CAqL/AgKi/wICov/7+/v/+/v7/wMAff8CAqL/+/v7//v7+/8CAqL/AgKi/wICoZ8AAAAA////AP///wACAqL/AgKi/wICov8CAqL/+/v7//v7+/8DAH3/AgKi//v7+//7+/v/AgKi/wICov////8AAAAAAP///wD///8AAgKi/wICov8CAqL/AgKi//v7+//7+/v/+/v7//v7+//7+/v/+/v7/wICov8CAqL/AgKifwAAAAD///8A////AP///wACAqL/AgKi/wICov/7+/v/+/v7/wUCg/8CAqL/AgKi/wICov8CAqL/AgKi/wICoY8AAAAA////AP///wD///8AAgKifwICov8CAqL/+/v7//v7+/8DAH3/AgKi/wICov8CAqL/AgKi/wICob////8AAAAAAP///wD///8A////AAICod8CAqE/AgKi//v7+//7+/v/AwB9/wICov8CAqL/AgKi/wICov8CAqL/////AAAAAAD///8A////AP///wD///8A////AAICov8CAqJ/AgKi/wICov8CAqL/AgKi/wICoW8CAqL/////AP///wAAAAAA////AP///wD///8A////AP///wD///8A////AAICov8CAqL/AgKi/////wACAqJ/////AP///wD///8AAAAAAP///wD///8A////AP///wD///8A////AP///wACAqL/AgKi/wICob////8A////AP///wD///8A////AAAAAAD///8A////AP///wD///8A////AP///wD///8AAgKi/wICon////8A////AP///wD///8A////AP///wAAAAAA/n8AAPgfAADwBwAA8AcAAAADAADAAwAA4AEAAMADAADAAwAA4AEAAPADAADoAwAA+hcAAP4/AAD+PwAA/v8AAA==\",\"id\":\"JVYDAZA4KN7YQ\",\"method\":\"GET\",\"order\":12,\"params\":[],\"queryCharset\":\"UTF-8\",\"query_string\":\"http://bitru.org/browse.php?s={searchTerms}&sort=seeders#content\",\"searchCode\":\"\",\"searchForm\":\"http://bitru.org\",\"searchRegex\":\"\",\"template\":\"http://bitru.org/browse.php?s={searchTerms}&sort=size#content\",\"title\":\"Bitru.org\"}"

**Comment by Zack11111** [comment]
In Chrome in 3rd time:

"{\"description\":\"\",\"hidden\":false,\"icon_base64String\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAv0lEQVQ4jaWTsQ0CMQxFre9QMwKjMAIjMAITnK5gAEaAM7qGhhEYhREYIIVpiGRyTpSApTTRz8v3d0JUKQH0Cow1TbUEUAFUmB//AQAlImp2k6xbwGfvkGBuTcBTQtgKoDFGjTHqQKw5qAixt1YBpUysKAGOWLkOJIRT8bAF5MvkMTYBUgs5YBkg874HIMznL8CF+f6TA0vsycCdwsy8S4KB2F0C6Ey0cQE3orU7spZHtJhI1lL3f0huJuBV070BHTcoahkAHckAAAAASUVORK5CYII=\",\"icon_url\":\"data:image/x-icon;base64,AAABAAEAEBAAAAAAAABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP///wD///8A////AP///wAAAKAPAgKi/wICoe////8A////AP///wD///8A////AP///wAAAAAA////AP///wD///8A////AP///wACAqL/AgKhnwICov8CAqL/AgKi/wICov////8AAgKif////wD///8AAAAAAP///wD///8A////AAAAoA8CAqL/AgKi/wICov8CAqL/AgKi/wICov8CAqL/AgKi/wICov////8A////AAAAAAD///8A////AP///wABAaJPAgKi/wICov8DAH3/AwB9/wMAff8DAH3/AwB9/wMAff8CAqL/AACjH////wAAAAAAAgKi/wICov8CAqGfAgKi/wICov8CAqL/+/v7//v7+//7+/v/+/v7//v7+//7+/v/AgKi/wICov////8AAAAAAP///wD///8AAgKgrwICov8CAqL/AgKi//v7+//7+/v/AwB9/wICov/7+/v/+/v7/wICov8CAqL/////AAAAAAD///8A////AAICoF8CAqL/AgKi/wICov/7+/v/+/v7/wMAff8CAqL/+/v7//v7+/8CAqL/AgKi/wICoZ8AAAAA////AP///wACAqL/AgKi/wICov8CAqL/+/v7//v7+/8DAH3/AgKi//v7+//7+/v/AgKi/wICov////8AAAAAAP///wD///8AAgKi/wICov8CAqL/AgKi//v7+//7+/v/+/v7//v7+//7+/v/+/v7/wICov8CAqL/AgKifwAAAAD///8A////AP///wACAqL/AgKi/wICov/7+/v/+/v7/wUCg/8CAqL/AgKi/wICov8CAqL/AgKi/wICoY8AAAAA////AP///wD///8AAgKifwICov8CAqL/+/v7//v7+/8DAH3/AgKi/wICov8CAqL/AgKi/wICob////8AAAAAAP///wD///8A////AAICod8CAqE/AgKi//v7+//7+/v/AwB9/wICov8CAqL/AgKi/wICov8CAqL/////AAAAAAD///8A////AP///wD///8A////AAICov8CAqJ/AgKi/wICov8CAqL/AgKi/wICoW8CAqL/////AP///wAAAAAA////AP///wD///8A////AP///wD///8A////AAICov8CAqL/AgKi/////wACAqJ/////AP///wD///8AAAAAAP///wD///8A////AP///wD///8A////AP///wACAqL/AgKi/wICob////8A////AP///wD///8A////AAAAAAD///8A////AP///wD///8A////AP///wD///8AAgKi/wICon////8A////AP///wD///8A////AP///wAAAAAA/n8AAPgfAADwBwAA8AcAAAADAADAAwAA4AEAAMADAADAAwAA4AEAAPADAADoAwAA+hcAAP4/AAD+PwAA/v8AAA==\",\"id\":\"JVYDAZA4KN7YQ\",\"method\":\"GET\",\"order\":12,\"params\":[],\"queryCharset\":\"UTF-8\",\"query_string\":\"http://bitru.org/browse.php?s={searchTerms}&sort=seeders#content\",\"searchCode\":\"\",\"searchForm\":\"http://bitru.org\",\"searchRegex\":\"\",\"template\":\"http://bitru.org/browse.php?s={searchTerms}&sort=size#content\",\"title\":\"Bitru.org\"}"

**Comment by ssborbis** [comment]
From the same console, try `saveOptions()` and see if there's an error.

**Comment by Zack11111** [comment]
> 
> 
> From the same console, try `saveOptions()` and see if there's an error.

I copied everything what I got in Chrome Console after saving edit and entering your 2 commands:

_locales/en-US/style.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
​ crbug/1173575, non-JS module files deprecated.
(anonymous) @ chrome-error://chromewebdata/:7288
options.js:1305 loaded @ chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/_locales/en-US/help.html
options.js:1305 loaded @ chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/_locales/en/help.html
DevTools failed to load source map: Could not load content for chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/lib/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
JSON.stringify(userOptions.searchEngines.find(se => se.title === "Bitru.org"))
'{"description":"","hidden":false,"icon_base64String":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAARdJREFUOE+Nkz9SwlAQxr/djBOhcTyBNh7EE0jLMEK8gZ5AtLKktUugoIQjcA8LxxvQUrjrbMYNyUte4JVvd3/77T9Cz1syKwHzR5G3mBudApR21d1U9b7L9zwAgKkIrZhfQzWdAJeuwLyeVYFnAhYG8/8GoGD+JpEMzLvx4VD6vF9c4o61pd4hDYBJ9Ky9gFpPGgCT7qkc8JEOcYPflgIBFpnISwWoB5u3A8LIdZqWXz7ekwDvgQMd0OpBkSQzUs3DEmIAAfJM5KlSkBNtmGh0LqBS4LUbkYEsBMR60DnGAngg5q0FfR13pcGwnUhEbifAz38zj/ZP4GrAvO+7D7NFN9EDraywJA8M7yF6TK5Ggf1M5Dqm6g+Mco8RvwJtAgAAAABJRU5ErkJggg==","icon_url":"data:image/x-icon;base64,AAABAAEAEBAAAAAAAABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP///wD///8A////AP///wAAAKAPAgKi/wICoe////8A////AP///wD///8A////AP///wAAAAAA////AP///wD///8A////AP///wACAqL/AgKhnwICov8CAqL/AgKi/wICov////8AAgKif////wD///8AAAAAAP///wD///8A////AAAAoA8CAqL/AgKi/wICov8CAqL/AgKi/wICov8CAqL/AgKi/wICov////8A////AAAAAAD///8A////AP///wABAaJPAgKi/wICov8DAH3/AwB9/wMAff8DAH3/AwB9/wMAff8CAqL/AACjH////wAAAAAAAgKi/wICov8CAqGfAgKi/wICov8CAqL/+/v7//v7+//7+/v/+/v7//v7+//7+/v/AgKi/wICov////8AAAAAAP///wD///8AAgKgrwICov8CAqL/AgKi//v7+//7+/v/AwB9/wICov/7+/v/+/v7/wICov8CAqL/////AAAAAAD///8A////AAICoF8CAqL/AgKi/wICov/7+/v/+/v7/wMAff8CAqL/+/v7//v7+/8CAqL/AgKi/wICoZ8AAAAA////AP///wACAqL/AgKi/wICov8CAqL/+/v7//v7+/8DAH3/AgKi//v7+//7+/v/AgKi/wICov////8AAAAAAP///wD///8AAgKi/wICov8CAqL/AgKi//v7+//7+/v/+/v7//v7+//7+/v/+/v7/wICov8CAqL/AgKifwAAAAD///8A////AP///wACAqL/AgKi/wICov/7+/v/+/v7/wUCg/8CAqL/AgKi/wICov8CAqL/AgKi/wICoY8AAAAA////AP///wD///8AAgKifwICov8CAqL/+/v7//v7+/8DAH3/AgKi/wICov8CAqL/AgKi/wICob////8AAAAAAP///wD///8A////AAICod8CAqE/AgKi//v7+//7+/v/AwB9/wICov8CAqL/AgKi/wICov8CAqL/////AAAAAAD///8A////AP///wD///8A////AAICov8CAqJ/AgKi/wICov8CAqL/AgKi/wICoW8CAqL/////AP///wAAAAAA////AP///wD///8A////AP///wD///8A////AAICov8CAqL/AgKi/////wACAqJ/////AP///wD///8AAAAAAP///wD///8A////AP///wD///8A////AP///wACAqL/AgKi/wICob////8A////AP///wD///8A////AAAAAAD///8A////AP///wD///8A////AP///wD///8AAgKi/wICon////8A////AP///wD///8A////AP///wAAAAAA/n8AAPgfAADwBwAA8AcAAAADAADAAwAA4AEAAMADAADAAwAA4AEAAPADAADoAwAA+hcAAP4/AAD+PwAA/v8AAA==","id":"JVYDAZA4KN7YQ","method":"GET","order":12,"params":[],"queryCharset":"UTF-8","query_string":"http://bitru.org/browse.php?s={searchTerms}&sort=seeders#content","searchCode":"","searchForm":"http://bitru.org","searchRegex":"","template":"http://bitru.org/browse.php?s={searchTerms}&sort=size#content","title":"Bitru.org"}'
saveOptions()
Promise {<pending>}[[Prototype]]: Promise[[PromiseState]]: "fulfilled"[[PromiseResult]]: true


I dont see error in console after saveOptions() but still edit is not working after restart.

**Comment by Zack11111** [comment]
In Firefox:


loaded @ moz-extension://bf1acef7-9a62-4a1a-aaa3-02aab7d48822/_locales/en/help.html options.js:1305:11
JSON.stringify(userOptions.searchEngines.find(se => se.title === "Bitru.org"))
"{\"description\":\"\",\"hidden\":false,\"icon_base64String\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAv0lEQVQ4jaWTsQ0CMQxFre9QMwKjMAIjMAITnK5gAEaAM7qGhhEYhREYIIVpiGRyTpSApTTRz8v3d0JUKQH0Cow1TbUEUAFUmB//AQAlImp2k6xbwGfvkGBuTcBTQtgKoDFGjTHqQKw5qAixt1YBpUysKAGOWLkOJIRT8bAF5MvkMTYBUgs5YBkg874HIMznL8CF+f6TA0vsycCdwsy8S4KB2F0C6Ey0cQE3orU7spZHtJhI1lL3f0huJuBV070BHTcoahkAHckAAAAASUVORK5CYII=\",\"icon_url\":\"data:image/x-icon;base64,AAABAAEAEBAAAAAAAABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP///wD///8A////AP///wAAAKAPAgKi/wICoe////8A////AP///wD///8A////AP///wAAAAAA////AP///wD///8A////AP///wACAqL/AgKhnwICov8CAqL/AgKi/wICov////8AAgKif////wD///8AAAAAAP///wD///8A////AAAAoA8CAqL/AgKi/wICov8CAqL/AgKi/wICov8CAqL/AgKi/wICov////8A////AAAAAAD///8A////AP///wABAaJPAgKi/wICov8DAH3/AwB9/wMAff8DAH3/AwB9/wMAff8CAqL/AACjH////wAAAAAAAgKi/wICov8CAqGfAgKi/wICov8CAqL/+/v7//v7+//7+/v/+/v7//v7+//7+/v/AgKi/wICov////8AAAAAAP///wD///8AAgKgrwICov8CAqL/AgKi//v7+//7+/v/AwB9/wICov/7+/v/+/v7/wICov8CAqL/////AAAAAAD///8A////AAICoF8CAqL/AgKi/wICov/7+/v/+/v7/wMAff8CAqL/+/v7//v7+/8CAqL/AgKi/wICoZ8AAAAA////AP///wACAqL/AgKi/wICov8CAqL/+/v7//v7+/8DAH3/AgKi//v7+//7+/v/AgKi/wICov////8AAAAAAP///wD///8AAgKi/wICov8CAqL/AgKi//v7+//7+/v/+/v7//v7+//7+/v/+/v7/wICov8CAqL/AgKifwAAAAD///8A////AP///wACAqL/AgKi/wICov/7+/v/+/v7/wUCg/8CAqL/AgKi/wICov8CAqL/AgKi/wICoY8AAAAA////AP///wD///8AAgKifwICov8CAqL/+/v7//v7+/8DAH3/AgKi/wICov8CAqL/AgKi/wICob////8AAAAAAP///wD///8A////AAICod8CAqE/AgKi//v7+//7+/v/AwB9/wICov8CAqL/AgKi/wICov8CAqL/////AAAAAAD///8A////AP///wD///8A////AAICov8CAqJ/AgKi/wICov8CAqL/AgKi/wICoW8CAqL/////AP///wAAAAAA////AP///wD///8A////AP///wD///8A////AAICov8CAqL/AgKi/////wACAqJ/////AP///wD///8AAAAAAP///wD///8A////AP///wD///8A////AP///wACAqL/AgKi/wICob////8A////AP///wD///8A////AAAAAAD///8A////AP///wD///8A////AP///wD///8AAgKi/wICon////8A////AP///wD///8A////AP///wAAAAAA/n8AAPgfAADwBwAA8AcAAAADAADAAwAA4AEAAMADAADAAwAA4AEAAPADAADoAwAA+hcAAP4/AAD+PwAA/v8AAA==\",\"id\":\"JVYDAZA4KN7YQ\",\"method\":\"GET\",\"order\":12,\"params\":[],\"queryCharset\":\"UTF-8\",\"query_string\":\"http://bitru.org/browse.php?s={searchTerms}&sort=seeders#content\",\"searchCode\":\"\",\"searchForm\":\"http://bitru.org\",\"searchRegex\":\"\",\"template\":\"http://bitru.org/browse.php?s={searchTerms}&sort=size#content\",\"title\":\"Bitru.org\"}"
JSON.stringify(userOptions.searchEngines.find(se => se.title === "Bitru.org"))
saveOptions()
Promise { <state>: "pending" }
​
<state>: "fulfilled"
​
<value>: true

1

JSON.stringify(userOptions.searchEngines.find(se => se.title === "Bitru.org"))

2

saveOptions()

**Comment by robertheadley** [comment]
I feel like the search template is over complicated.
https://bitru.org/browse.php?s={searchTerms}&sort=size
Works just fine. 
![image](https://user-images.githubusercontent.com/1780455/139739065-36a5ce3b-9c18-4acc-baba-25c3dd42ebd9.png)

**Comment by ssborbis** [comment]
@Zack11111 

It appears the query_string `http://bitru.org/browse.php?s={searchTerms}&sort=seeders#content` is not updated but the template `http://bitru.org/browse.php?s={searchTerms}&sort=size#content` is not.

I assume you're on v1.28.1? I think I depreciated one of those params in the dev code.

Ok, lets set them equal, then save

From the console in options

```js
let se = userOptions.searchEngines.find(se => se.title === "Bitru.org");
se.template = se.query_string;
saveOptions();
```

**Comment by Zack11111** [comment]
> @Zack11111
> 
> It appears the query_string `http://bitru.org/browse.php?s={searchTerms}&sort=seeders#content` is updated but the template `http://bitru.org/browse.php?s={searchTerms}&sort=size#content` is not.
> 
> I assume you're on v1.28.1? I think I depreciated one of those params in the dev code.
> 
> Ok, lets set them equal, then save
> 
> From the console in options
> 
> ```js
> let se = userOptions.searchEngines.find(se => se.title === "Bitru.org");
> se.template = se.query_string;
> saveOptions();
> ```

It didn't help as well. Yes my version is 1.28.1

But, I sorted out my problem in other way. I deleted engine. First, I tried create new search engine using browser context menu "Add to ContextSearch" in website. But, after restart new created engine disappeared from list of search engines. Then, I created new one using ADD button in Options (Search Engines section). Manually entered needed template "http://bitru.org/browse.php?s={searchTerms}&sort=size".  And now it is saved and working after restart too. 

For your reference, I send you what I got in Chrome console after entering your last codes/command:

Failed to load resource: net::ERR_FILE_NOT_FOUND
​ crbug/1173575, non-JS module files deprecated.
(anonymous) @ chrome-error://chromewebdata/:7288
options.js:1305 loaded @ chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/_locales/en-US/help.html
options.js:1305 loaded @ chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/_locales/en/help.html
DevTools failed to load source map: Could not load content for chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/lib/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
let se = userOptions.searchEngines.find(se => se.title === "Bitru.org");
se.template = se.query_string;
saveOptions();
Promise {<pending>}[[Prototype]]: Promise[[PromiseState]]: "fulfilled"[[PromiseResult]]: true

**Comment by Zack11111** [comment]
Thank you @ssborbis  and @robertheadley

**Comment by ssborbis** [comment]
@Zack11111 

No prob, but it sounds like there's a bug in 1.28.1 causing your issues.  You may want to simply update to the latest code ( chrome ) or alpha ( firefox ). 1.30+ is a pretty significant update with tons of fixes and features.

**Comment by ssborbis** [comment]
I believe this is fixed in the newest versions. There was a second parameter for the template in some older engines, and the code was only keeping the longer string of the two. That extra parameter should be removed when the addon is loaded now.
