### ISSUE TITLE
An overlap between the menus 

### ISSUE THREAD

**Issue by jed84** [ssborbis/ContextSearch-web-ext#387]
Version 1.31.1

Given I set the settings as follow:
![obraz](https://user-images.githubusercontent.com/47121522/143292150-0d130c80-1423-4e09-9bef-281a0132ad31.png)

When I highlight a text on the website and hold the right mouse button

Then an overlap between the context menu and quick menu occurs:
![obraz](https://user-images.githubusercontent.com/47121522/143292573-1d259b73-06ce-41af-95b1-ecc321eaa562.png)

This worked without any issues on version 1.28.1 and now is broken in 1.31.1

Firefox 94.0.2

**Comment by ssborbis** [comment]
Are you on an OS that displays the default context menu on mousedown vs mouseup? If so, enable `rightClickMenuOnMouseDownFix` in the advanced menu. The old way was causing some missed clicks

**Comment by jed84** [comment]
Thank you, it solves the problem!

**Comment by ssborbis** [comment]
FYI, you'll need to double-click to get the default menu. It's a bit of a tradeoff, but I've yet to find a better way.
