### ISSUE TITLE
Bug: Toolbar Pop-up Layout (on Linux)

### ISSUE THREAD

**Issue by MintMain21** [ssborbis/ContextSearch-web-ext#388]
Most of the bugs I reported before seem to have been fixed, and I can now use it in Firefox Android, but a minor bug has occurred on Linux. When the layout for the Toolbar Popup is configured as grid, the layout of the engines is misaligned. 

![image](https://user-images.githubusercontent.com/91362684/143300485-6d1e27bc-7514-4499-bb65-b83e4de7c4cf.png)

A minor bug, mostly because I generally prefer to search with the context menu and/or the Awesome/Address Bar anyway, but I feel like it's worth reporting anyway, mostly because it seems exclusive to Linux (Mint 20.2). This bug is non-existent on Windows and Android. Could alternatively be a bug with my configuration file or something, but for now I'm assuming it's a Linux specific bug. 

PS: using Firefox 94.0

**Comment by ssborbis** [comment]
How many columns is the toolbar menu set to? I'm not sure if there's a gap or if an overflow bumped the last column down.

**Comment by MintMain21** [comment]
Changed it from 5 to Six and it's fixed.

**Comment by ssborbis** [comment]
I'm gonna open this back up for the moment. There's definitely a bug in there.

**Comment by ssborbis** [comment]
I just dropped a hotfix for this 1.30.2

Awaiting validation on AMO
