### ISSUE TITLE
Separators in quick menu cause odd layout (v1.31)

### ISSUE THREAD

**Issue by Ede123** [ssborbis/ContextSearch-web-ext#389]
Version 1.31 seems to have introduced separators in the quick menu.

Unfortunately they're shown vertically, which causes a very long and narrow layout in my case:
![grafik](https://user-images.githubusercontent.com/904570/143488016-1b85bedb-0442-4cc9-a7b2-86dbb89a9654.png)

Obviously this is not ideal. Is there a way to disable separators in the quick menu again or use a more compact style that does not start a new row with each separator (e.g. small vertical line between icons)?

I'd like to keep my separators intact if possible, as I like them in the context menu.

**Comment by ssborbis** [comment]
I'll look into a few options. In the meantime, you might need to hide / delete them from the search engines manager.

**Comment by ssborbis** [comment]
added advanced option quickMenuHideSeparatorsInGrid under the advanced menu in v1.30.3

**Comment by Ede123** [comment]
Greath, thanks for the quick update! 😀
