### ISSUE TITLE
"Copy to clipboard" button in the quick menu doesn't work (v1.31.2)

### ISSUE THREAD

**Issue by krisu5** [ssborbis/ContextSearch-web-ext#390]
Clicking the button doesn't copy the text nor does it show the checkmark icon after copying.

**Browser:** Firefox 94.0.2.

**Comment by Fanolian** [comment]
Last working: v1.28.1
Not working: 1.31, 1.31.1, 1.31.2

**Comment by ssborbis** [comment]
Thanks, I'll take a look.

**Comment by ssborbis** [comment]
I'm getting inconsistent behavior between by daily use profile and a test profile. I'm trying a few things, but do you have any issue with having to grant this addon the clipboardWrite permission before using the copy button? I'll need to alter some code, but it might be the only way to get around the issue.

**Comment by smsihe** [comment]
same problem

**Comment by ssborbis** [comment]
You'll probably need to grant the clipboardWrite permission before it will update, but 1.30.3 is going up now.

**Comment by krisu5** [comment]
> but do you have any issue with having to grant this addon the clipboardWrite permission before using the copy button?

Yeah, the "Input data to the clipboard" and "Get data from the clipboard" extra permissions don't fix the issue for me.

**Comment by Fanolian** [comment]
Just a minor issue: `Input data to the clipboard` is now both a required and optional permission:
https://github.com/ssborbis/ContextSearch-web-ext/blob/d36f468aac140a84bb6c5bf6bd95694d94c3a113/src/manifest.json#L41-L55

**Comment by ssborbis** [comment]
> Issue is fixed with 1.31.3, there's no checkmark anymore still after copying, but I guess that's on purpose? Not that I absolutely need it.

It should be there, but the code may have been disabled. I'll get it back on a future release

> Is it possible to request such permission only when this feature is used for the first time?
Personally I wouldn't mind granting extra permissions. But it is better to communicate it to other users, perhaps through a changelog.

I couldn't come up with a good way to initiate a prompt for the user due to browser security requiring a more direct event ( I had content scripts communicating with the background script to process the copy event ). I'll check for a better way. This was a quick fix.

**Comment by redactedscribe** [comment]
Copy to clipboard is still broken in 1.31.3 for copy to clipboard on _links_. Did Firefox's context menu always display when long pressing right-click to activate ContextSearch's pop-up menu? Ideally only the pop-up would show as I don't need both to open on a long press.

**Comment by ssborbis** [comment]
> Copy to clipboard is still broken in 1.31.3 for copy to clipboard on links.

Links, gotcha. Fix is ready. I'm looking to patch a few more bugs before dropping another release.

**Comment by ssborbis** [comment]
> Is it possible to request such permission only when this feature is used for the first time?
Personally I wouldn't mind granting extra permissions. But it is better to communicate it to other users, perhaps through a changelog.

Looks like my issues requesting permission are due to a Firefox bug. I have a workaround, so I'll remove the required permission on the next release.

**Comment by boromyr** [comment]
I'm experiencing the same problem in Edge 96, the copy done icon is displayed, but there is no copied text in the clipboard. 
Last version development.

**Comment by ssborbis** [comment]
@boromyr 

Is there a way on Edge to show what permissions the addon has? It requires clipboardWrite, but should prompt if it doesn't have it. Otherwise, I'm not sure why it would fail.

**Comment by boromyr** [comment]
Yes, the request popup appeared, and I confirmed, and in the extension manager the permission to copy and paste is on. I haven't tried installing the extension in a new clean profile yet, I just went along with the problem since others were reporting it too. I'll update the results as soon as I can.

**Comment by boromyr** [comment]
Update:
I tested the latest version in a new clean profile in Edge, the copy doesn't work.
I downloaded and tried the extension in Chromium, again the copy doesn't work.
In Firefox, it works correctly.

In all cases, I have obviously accepted the access permissions required to copy the text.

**Comment by ssborbis** [comment]
@boromyr 

I'm seeing it now. Chromium-based has some rather inconvenient security feature for the copy function. I'll look for a workaround.

**Comment by ssborbis** [comment]
Ok, to all the chromium-based users, I think this is finally fixed. 

Auto copy and the copy tool seem to be working properly in mozilla- and chromium-based browsers wtih the latest dev branch code. Please give it a test if you can.

**Comment by boromyr** [comment]
I'll confirm that in Edge 96 the copy works fine now, so I guess it applies to all Chromium derivatives. I tested the version from the Chrome Store.

**Comment by ssborbis** [comment]
Wasn't working for urls and images. Fix in the dev repo, next release.

**Comment by redactedscribe** [comment]
@ssborbis Confirmed as fixed again on the dev branch.

**Comment by redactedscribe** [comment]
@ssborbis Doesn't seem to work any more in v1.32.6. I'm not entirely sure if the fix ever made it to stable.

The permissions I've currently given to the extension are "Input data to the clipboard" _enabled_, and "Get data from the clipboard" _disabled_, so it shouldn't be a permissions issue.

To recap, when I use the Quick Menu on a link and choose the Copy to clipboard button in the top bar, nothing is copied. I can clearly see what the value of the link is in the "searchBarContainer" DOM element, so it's something to do with copying the value to the clipboard, not with being able to read what to copy.

ContextSearch 1.32.6
Firefox 96.0.0

**Comment by ssborbis** [comment]
@redactedscribe Did you try any of the recent betas?

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.33b1/contextsearch_web_ext-1.33b4-an+fx.xpi

**Comment by redactedscribe** [comment]
@ssborbis Works in the beta, thanks. Hoping to see a stable release soon.

**Comment by ssborbis** [comment]
@redactedscribe 1.33 is live
