### ISSUE TITLE
Weird context menu item (v1.31.2)

### ISSUE THREAD

**Issue by krisu5** [ssborbis/ContextSearch-web-ext#391]
This weird regex-like context menu item is now in the menu:

![Clipboard02](https://user-images.githubusercontent.com/3540275/143580691-25c15919-fd38-4195-93d9-de2225e78a99.png)

Clicking it does nothing (only closes the context menu).

**Browser:** Firefox 94.0.2.

**Comment by ssborbis** [comment]
Shoot, that's supposed to be off by default. Thanks, I'll update the code.

**Comment by ssborbis** [comment]
should be disabled in v.1.30.3

**Comment by krisu5** [comment]
Yeah, it's fixed now.
