### ISSUE TITLE
Feature request: Add Escape Key to 'Closing' options menu

### ISSUE THREAD

**Issue by wikiped** [ssborbis/ContextSearch-web-ext#393]
It would be great to have 'Escape' key as an additional option to close context menu:

![Closing](https://user-images.githubusercontent.com/5990528/143612127-8a2617be-bd37-4b2e-be67-ff893f7e036b.png)

Sometime the text is selected for some other reason (i.e. not for search) and it is easier / quicker to press escape to close menu (like in many other 'menu' cases).

I am hoping this is not too big of an ask.
Thank you very much for the great extension.

**Comment by ssborbis** [comment]
Escape should work by default to close the menu. If it's not, there may be an addon conflict, or some conflict within this addon's config.

**Comment by patjldeiM0IP** [comment]
Pressing escape works to close the menu _before_ clicking any of the search icons but once you click an icon escape no longer works to close the menu.

**Comment by wikiped** [comment]
Thanks. There must have been a conflict of shortcuts or something similar. Difficult to know in Firefox as there is no way to check for which shortcuts are being used for what (or I am not aware of it). Anyway after disabling other extensions escape works as expected. And it keeps working after all other extensions.
