### ISSUE TITLE
Is there a way to add the search from https://www.systemrequirementslab.com?

### ISSUE THREAD

**Issue by CrazieIvan** [ssborbis/ContextSearch-web-ext#395]
https://www.systemrequirementslab.com/cyri
When I try to add it says "template missing, hit OK and perform a search...." but it doesn't work.  I'm guessing this one can't be created?

**Comment by ssborbis** [comment]
Check some of the workarounds near the bottom of #67. You'll need to use the search code field in the search engine's settings

**Comment by CrazieIvan** [comment]
I appreciate the response!  
Unfortunately the stuff in that thread is way above my pay grade :-) If someone figures out what I should put in the search code field, I'll gladly give it a go.  
Otherwise it's no big deal, and thank you for the great addon!  It's one of my favorites.

**Comment by ssborbis** [comment]
add a new engine ( if needed ) through the search engines manager

Set the landing page url as the template and try this for the search code. Adjust the timeout values as needed and use the test button at the bottom of the form.

search code: 
```js
( async() => {
let input = document.querySelector('#select-repo-ts-control');
let button = document.querySelector('#button-cyri-bigblue');
await new Promise(r => setTimeout(r, 100));
input.value = searchTerms;
await new Promise(r => setTimeout(r, 100));
input.dispatchEvent(new Event('input'));
await new Promise(r => setTimeout(r, 1000));
input.dispatchEvent(new KeyboardEvent('keydown', {key: "Enter", keyCode:13}));
await new Promise(r => setTimeout(r, 100));
button.click();
})();
```

**Comment by CrazieIvan** [comment]
Thank you for the instructions!  
So, it seems to work when I enter the URL and search code and then use the Test button.  Then I save it and close the window. But when I try using the new engine, nothing happens, and if I open the engine configuration (right mouse > Edit), all fields are blank.  When I hit Save, I also see the "Saved" popup message, so I don't know why it's not saving it.

![2021-11-29_194935](https://user-images.githubusercontent.com/69615600/143918836-a89adfdf-1ce3-4325-811e-78c4e852190d.jpg)

![2](https://user-images.githubusercontent.com/69615600/143918873-2e39b74e-4455-43e9-bf32-00fe3affe13c.jpg)

**Comment by ssborbis** [comment]
You might need to close the options page after saving, and reload any opened tabs.

**Comment by CrazieIvan** [comment]
no luck.  I saved, restarted the browser, and the engine is blank.

**Comment by ssborbis** [comment]
are there any errors in the console from the options page? CTRL+K

**Comment by ssborbis** [comment]
sry, CTRL+SHIFT+K

**Comment by ssborbis** [comment]
it's not just you. I'm seeing a bug

**Comment by ssborbis** [comment]
v1.30.8 going live soon. See if that fixes it.

**Comment by CrazieIvan** [comment]
Oh yea!!! It's working now :D  Awesome!
Thanks very much for your help and for the quick bug fix.

**Comment by ssborbis** [comment]
No prob. Thanks for the bug report. I can't fix what I don't know is broken.
