### ISSUE TITLE
Feature request: Show search engine name in a title bar on the right-click Quick Menu

### ISSUE THREAD

**Issue by redactedscribe** [ssborbis/ContextSearch-web-ext#397]
When ContextSearch is added to Firefox's toolbar or overflow menu, clicking the add-on's icon shows the Quick Menu. In this particular Quick Menu, the UI shows ContextSearch's Search toolbar, then a title bar which previews the name of the grid/list item which is hovered over, then the Tools toolbar, and finally the grid/list items.

I would like to see this title bar available as a toolbar which can be added to _the Quick Menu that is triggered by holding right-click_. It should also show the names for the Tools toolbar items just like it does for the Quick Menu shown via Firefox toolbar. Currently this name preview title bar seems to be limited to only the Quick Menu shown via the Firefox toolbar / overflow menu and not shown in the right-click one. Why do I want this? I like using the Grid mode, but it's not always immediately clear which grid icon is the one I want without hovering over it to read its name (because some grid icons have the same favicon).

My ideal implementation:

Like the Tools and Search Bar toolbars, this title bar _should be a toolbar_ and so the user could define if it's displayed at the top or the bottom of the Quick Menu.

I'd also like to see an (advanced(?)) option that would _hide this title toolbar if the Quick Menu is displayed in List mode_ as it would only be redundant info on screen. So hidden when a grid icon is clicked which is configured to display as a list, or when the entire Quick Menu is switched to the List mode.

Finally, since there would now be three toolbars available to potentially display in the Quick Menu, I'd personally use the Tools toolbar on top, then the grid/list items, then the Search Bar toolbar, and finally the requests title bar toolbar at the bottom.

Thanks for your consideration!

ContextSearch 1.31.8
Firefox 94.0.2

**Comment by ssborbis** [comment]
I'll see what can be done.  In the meantime, you can get part-way there by adding this to your custom user styles under *CS Options -> General*

```css
[data-menu="quickmenu"] #titleBar {
    display:block !important;
}
```

**Comment by redactedscribe** [comment]
Thanks for that, but yes, I'd ideally have it placed at the bottom as it is just being displayed to the top of the Quick Menu (which I find to be in the way). Maybe it can be shifted to the very bottom via CSS?

**Comment by ssborbis** [comment]
I'm adding an advanced option to override the layout order. For now, it's a simple string list of DOM ids

`menuBar, searchBarContainer, optionsBar, quickMenuElement, addEngineBar, titleBar, toolBar`

Combined with the CSS you have, it should do the job.

**Comment by ssborbis** [comment]
updates in the dev repo

**Comment by redactedscribe** [comment]
I don't know how to download the dev XPI. Or am I supposed to load the source files myself? Are the fixes you made now in 1.32.2 stable? Also, I'm assuming the advance option will be in the Advanced section?

**Comment by ssborbis** [comment]
> Are the fixes you made now in 1.32.2 stable? 

yep

> Also, I'm assuming the advance option will be in the Advanced section?

yeah, `quickMenuDomLayout`

**Comment by redactedscribe** [comment]
Unfortunately, the title bar won't show for some reason.

CSS:
```css
[data-menu="quickmenu"] #titleBar {
    display:block !important;
}
```

And I'm using you suggested DOM layout value: `menuBar, searchBarContainer, optionsBar, quickMenuElement, addEngineBar, titleBar, toolBar`

**Comment by ssborbis** [comment]
send me your config.

It's working as expected for me

**Comment by redactedscribe** [comment]
Embarrassing mistake: The custom CSS contained a `//` comment, when CSS only accepts `/**/`. Now it's working 🙂

**Comment by redactedscribe** [comment]
A quick note: since this (or any Advanced option) doesn't seem to be documented other than via the UI, perhaps the small pop-up that explains quickMenuDomLayout could list the available quickMenu div ids, else questions about how to use this feature may come up.

**Comment by ssborbis** [comment]
Sure

**Comment by ssborbis** [comment]
I know this is closed, but I wanted to update you on some changes I'm working on.

Using the edit tool in the qm will allow you to rearrange parts of the menu as you see fit. I may add controls for hiding / unhiding elements as well, or I may just rely on CSS for that. Here are the changes in actions.

![rearrange](https://user-images.githubusercontent.com/24310997/147916239-c771ff8c-6c49-48b1-ac6a-51be1d88bfe8.gif)
