### ISSUE TITLE
Find Bar is no longer spanning across the top of the browser window

### ISSUE THREAD

**Issue by redactedscribe** [ssborbis/ContextSearch-web-ext#398]
I managed to double-click the ContextSearch's Find Bar in Firefox and now it no longer spans the top of the browser window's content area:

![firefox_contextsearch_find_bar](https://user-images.githubusercontent.com/25013746/144152887-10cb7eb6-e628-46db-9deb-d16d37531b44.jpg)

I couldn't find a way to drag or resize it back to normal. Now whenever I open the Find Bar, it's always in this shortened state.

Thanks.

**Comment by ssborbis** [comment]
try double-clicking the ||| icon

**Comment by ssborbis** [comment]
Also, the findbar layout looks a little off. This is what I see
![findbar](https://user-images.githubusercontent.com/24310997/144265666-cdf8d5cc-8aa5-40e6-950b-c402263ab6fa.png)

**Comment by redactedscribe** [comment]
It seems to be unreliable. Probably why I thought it was entirely broken. Seems that it's only partially broken: Sometimes double-clicking the ||| icon will only momentarily shift it to the top then spring it back to where the bar was at the time of double-clicking. I think this behaviour is introduced if the bar is not at the top of the window at the time of double-clicking the ||| icon.

And yes, all the icons, text, and the field are not vertically centered in the bar (in my screenshot, unlike yours).

**Comment by ssborbis** [comment]
i'm seeing it

**Comment by ssborbis** [comment]
Looks like the docking listeners are being added each time the findbar is opened on a page, causing several dock/undock events. FIx is in the repo

**Comment by ssborbis** [comment]
Pretty sure this is taken care of. Re-open if not.
