### ISSUE TITLE
Quick menu doesn't open

### ISSUE THREAD

**Issue by bottleblue** [ssborbis/ContextSearch-web-ext#399]
Quick menu doesn't open on the Steam review page popups.  If you go to a Steam review page like https://steamcommunity.com/app/924970/reviews/?browsefilter=mostrecent&snr=1_5_100010_&p=1 , click on a review it will open a popup window. Highlight a word and try to open the quick menu. It doesn't work.

**Comment by ssborbis** [comment]
Looks like the code is having trouble with the cursor position in the iframe, making it think you're doing a drag event. Try one of the other opening methods. They should work while I look for a solution.

**Comment by bottleblue** [comment]
I tried Auto and Simple Click and neither worked. I'll have to patiently wait for an update.

**Comment by ssborbis** [comment]
Ok, I think it's because that iframe is generated on the fly and the code for the menu isn't being injected. I'll let you know when I have something.

**Comment by bottleblue** [comment]
Cool no rush. Thanks for the continual updates.

**Comment by ssborbis** [comment]
I think this is fixed in the latest code / pre--release.  Menu opens in the iframe ok. It might have some positioning issues, but it does work.

**Comment by bottleblue** [comment]
Great I'll test it when it releases thx
