### ISSUE TITLE
Quick menu lagging 

### ISSUE THREAD

**Issue by minawaheed9697** [ssborbis/ContextSearch-web-ext#400]
On YouTube, when I scroll down with time and try to open qm, it is lagging and taking much time than usual.
`quickMenuHoldTimeout` is 250. 
Browser:- Vivaldi 5.0.2497.25 (Official Build) (64-bit)
OS:- Win 10 
In this GIF, when the mouse cursor is static, this means I am holding Rt click to activate qm. Look to the delay. 
![02_12_2021 17_33_11_800](https://user-images.githubusercontent.com/73688266/144453820-9a001cf9-58d1-4d3d-8b1a-5c4ab6660e27.gif)

**Comment by ssborbis** [comment]
Can you test one of the other opening methods to see if it's the opening method being slow or the menu?

**Comment by minawaheed9697** [comment]
> Can you test one of the other opening methods to see if it's the opening method being slow or the menu?

I tried context menu and working fine.

**Comment by ssborbis** [comment]
What about the other opening methods for the quick menu? Click vs hold, simple click, auto, drag, etc. I'm wondering if it's something specific to that opening method, or it's the menu itself slow to open.

**Comment by minawaheed9697** [comment]
> What about the other opening methods for the quick menu? Click vs hold, simple click, auto, drag, etc. I'm wondering if it's something specific to that opening method, or it's the menu itself slow to open.

All methods are the same. But, the drag is not there as I am on stable version of the extension.
Also, the problem is on reddit.

**Comment by ssborbis** [comment]
Both reddit and youtube have a lot of DOM content. That's probably the common factor, though I don't know why it would slow down the menu. How much more time does it take?

**Comment by minawaheed9697** [comment]
> Both reddit and youtube have a lot of DOM content. That's probably the common factor, though I don't know why it would slow down the menu. How much more time does it take?

I think 1-2 seconds to respond

**Comment by ssborbis** [comment]
I'm pretty sure it's due to the level of content on those pages. Nothing to do but render faster.
