### ISSUE TITLE
Can't drag quick menu icons 

### ISSUE THREAD

**Issue by bottleblue** [ssborbis/ContextSearch-web-ext#402]
Using latest version, I noticed the icons in the quick menu are not draggable. I downgraded to 1.28.1 and the function returned.

Also can you add an option to de-highlight the words after searching from the quick menu? Because I also use Gesturefy which lets me scroll tabs by holding right mouse button + scroll wheel. When I scroll back to the previous tab with the highlighted word it opens the quick menu again because I was holding right mouse button + scroll wheel.

**Comment by ssborbis** [comment]
In 1.30+, you need to click the Edit tool to move icons. This is to prevent accidentally moving icons, and it hides the resize handle under normal use.

> Also can you add an option to de-highlight the words after searching from the quick menu?

I think so.

**Comment by quaz33** [comment]
I'd prefer to move icons directly without edit mode. Perhaps as an advanced option?

**Comment by ssborbis** [comment]
> I'd prefer to move icons directly without edit mode. Perhaps as an advanced option?

Should be easy enough to add

**Comment by ssborbis** [comment]
alwaysAllowTileRearranging added to the advanced options. In the dev repo

**Comment by ssborbis** [comment]
> Also can you add an option to de-highlight the words after searching from the quick menu?

I'm trying to decide when this should happen when the option is enabled

1. when the menu closes
2. when any search is performed
3. when a menu-closing search is performed

Possible issues

(1) Some searches are sent to background tabs, while keeping the menu open. In these cases, the text won't deselect. In addition, if the menu is opened by accident, any selected text will deselect even if no search is performed

(2) Deselecting text while the menu is open will change the search terms unless a workaround is added

(3) If a user is sending searches to background tabs while keeping the menu open, the *last* search will need to be one that closes the menu, triggering the deselect. Normally, I don't even bother closing the menu before opening one of the search results tabs manually.

Thoughts? What's your workflow like?

**Comment by bottleblue** [comment]
> Thoughts? What's your workflow like?

Umm sometimes I open tabs in the background and sometimes I don't. I don't really open the menu accidentally. If I highlight a word and open the menu it's usually because I meant to.

What do you mean deselecting text while menu is open will change search terms? If you deselect text there won't be anything to search because it's blank?

I never keep my menu open after doing a search.

**Comment by ssborbis** [comment]
> What do you mean deselecting text while menu is open will change search terms? If you deselect text there won't be anything to search because it's blank?

Yes, if the menu stays open, any changes to text selection affect the searchTerms the menu uses, unless I can rig some special-case code. That might be the best option,though. There are, no doubt, features you don't use, but others do, that will be affected by a new 'deselect' setting.  I'm just trying to mentally account for them now.

**Comment by bottleblue** [comment]
I see. I hope you figure it out!

**Comment by CrazieIvan** [comment]
I thought maybe I had a bug in the latest version when I couldn't drag the icons in the quick menu.  But then I started thinking that maybe I never could, and i'm just losing my mind haha.
Is there a change log that we can refer to with every update, so that we can see some of the more significant changes and know what to expect when features get removed or added?  It would be really helpful.  :-)

**Comment by ssborbis** [comment]
New advanced option `alwaysAllowTileRearranging` live in the dev repo and there's a signed beta @ https://github.com/ssborbis/ContextSearch-web-ext/releases/download/v1.32a1/contextsearch_web_ext-1.32a1-an+fx.xpi for testing.

**Comment by bottleblue** [comment]
Dragging icons work but it always opens the website after dragging.

**Comment by ssborbis** [comment]
Do you mean it opens the search engine on the drop, or the menu thinks the old engine is the new engine?

**Comment by bottleblue** [comment]
Like if google icon is on the left and github icon is on the right and you move the google icon to github's place it will move it but then open github's website afterwards.

**Comment by ssborbis** [comment]
@bottleblue 

Thanks, I'll get that patched up. Are you only seeing it happen when using `alwaysAllowTileRearranging` ?

**Comment by bottleblue** [comment]
Yes if I disable alwaysAllowTileRearranging and use the edit button it doesn't happen.

**Comment by ssborbis** [comment]
K, I've got it.

**Comment by ssborbis** [comment]
@bottleblue 

Should be fixed in the latest release

**Comment by bottleblue** [comment]
It's working fine thanks a lot.

**Comment by ssborbis** [comment]
Thanks for the bug report
