### ISSUE TITLE
Feature Wanted：Specify in what situation should this webpage be added to the context menu

### ISSUE THREAD

**Issue by lshilshi** [ssborbis/ContextSearch-web-ext#403]
Displaying all search terms at the same time can be lengthy and inconvenient to choose sometimes.

Specify in what situation  which search terms  should be added to the context menu:
- selection: the webpage is added when right-click on a selected text
- page and frame: the webpage is added when right-click on the page
- link: the webpage is added when right-click on a link
...

Contexts： selection，page，frame，link，image，video，audio，all...

**Comment by ssborbis** [comment]
For testing, I added some checkboxes for setting the context for a particular engine. That's the easy part. The hard part is deciding on the layout.

This is a bit messier than you may realize.

Should the menu layout be as it is now, but simply omit engines without the current context checked?
* If I select the text of an url, any engines listed as `all`, `select`, and `url` will show, but how to decide whether to use the text or url for the search terms?

Should there be submenus for each context? ( sometimes there are multiple contexts active )
* now you'll get a submenu for `all` and  `select` even if you're just doing a basic text select. That added tier will always be there.

Should the menu be flattened without subfolders? yes/no based on how many engines are returned? Sort them by how they appear in the tree? Alphabetically?

**Comment by lshilshi** [comment]
I am wanting to decide what engines to display based on the right click content, and we can set which engines to adapt to when we add the search engine，such as selection，page，frame，link，image，video，audio，all...
![Selection Context Search](https://user-images.githubusercontent.com/36767310/145528375-325454e0-3a24-4000-9fc0-55b70c46566c.png)

If you are confused by what I am saying, you can refer to the following
https://chrome.google.com/webstore/detail/selection-context-search/kplgehmegmjifbhioeldcnphfkcfckjj
OR
https://addons.mozilla.org/en-US/firefox/addon/selection-context-search/

I am switching from this add-on to your project now.

**Comment by ssborbis** [comment]
You can test what I've got so far from the dev repo. Enable advanced option `contextMenuUseContextualLayout` and adjust contexts from the search engines manager. There is another option `contextMenuContextualLayoutFlattenLimit` which, when enabled, ignores folder layouts if the number of engines for that particular context is below the option value.

![contexts](https://user-images.githubusercontent.com/24310997/145653518-41cc48f6-f163-47d7-9576-501fdbb5c9b0.jpg)

**Comment by lshilshi** [comment]
ok，It's great！
thx ur reply！

**Comment by lshilshi** [comment]
> ok，It's great！
> thx ur reply！

It's time for you to officially release dev repo to the chrome webstore now.
Loading unziped dev addons  is not convenient for follow update.

**Comment by lshilshi** [comment]
It's already ver 1.31.9(Dec 1, 2021) CS in the mozila store，
but still ver 1.28.1(Jan 23,2021) CS in chrome webstore.

@ssborbis 
Maybe you forgot to update the CS  version in chrome webstore.

**Comment by ssborbis** [comment]
I'm waiting on a solid release, probably v1.32, for the chromestore. v1.31x was buggy.
