### ISSUE TITLE
"Alt" and "Shift" should override the default omnibox search behaviour

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#405]
When using the default address bar of Firefox, `alt` or `shift` determines how a new tab should be opened. After writing something in there, pressing `alt + enter` will always open the tab in a separate tab, while using `shift + enter` will open the tab in a new window.

Is it possible that this add-on also incorporates this behaviour, when using the omnibox search, thus overriding the default omnibox setting?

**Comment by ssborbis** [comment]
Taking a look at the API, I think it should work this way after I modify the code:

`Enter` > overridden by the CS Options -> Omnibox search action
`Alt+Enter` > default omnibox behavior ( new tab )
`Shift+Enter` > default omnibox behavior ( new window )

What do you think?

**Comment by ssborbis** [comment]
Those key combos must be platform-dependent or something. Shift+Enter doesn't do anything for me

**Comment by sojusnik** [comment]
> Those key combos must be platform-dependent or something.

They seem to be [OS-agnostic](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_media-shortcuts):

![grafik](https://user-images.githubusercontent.com/1245718/145277476-0026f473-f4e5-4171-b2e5-fc6793d8fd78.png)

I would just mimic the default shortcuts, if it's possible.

**Comment by ssborbis** [comment]
updates are in the dev repo if you want to test

**Comment by sojusnik** [comment]
> Those key combos must be platform-dependent or something. Shift+Enter doesn't do anything for me
> 
> (edit) Using the updated code, Atl+Enter works fine, but Shift+Enter only works using the default omnibox search. It doesn't seem to trigger any event when using the `cs` prefix. Odd.

Confirming that!

Do you want to leave this issue open because "shift + enter" isn't working?

**Comment by ssborbis** [comment]
> Do you want to leave this issue open because "shift + enter" isn't working?

It seems to me like it's a browser issue. I don't use the omnibox, so I'll ask you - do any other addons that use the omnibox have the same issue?

**Comment by sojusnik** [comment]
> I don't use the omnibox, so I'll ask you - do any other addons that use the omnibox have the same issue?
Can't say, because your add-on is the only one I use with those shortcuts.

BTW, as always, many thanks for your quick responses and your effort you put in this add-on. This is very appreciated!

**Comment by ssborbis** [comment]
The shift+enter search bug appears to be a Firefox issue. The omnibox API doesn't seem to handle that combo for extension prefixes, only for the built-in omnibox handler. I'm gonna close this issue out and see if anyone opened a ticket at mozilla.
