### ISSUE TITLE
Feature Request: Disable "Highlight Search Terms" by default (on Firefox)

### ISSUE THREAD

**Issue by MintMain21** [ssborbis/ContextSearch-web-ext#406]
Firefox is what I use daily, not Chromium Browsers. Firefox has a feature where you can search for specific words or phrases on a given webpage. I do not know if Chromium Browsers offer this feature, but I can presume not because ContextSearch-web-ext does by default. In any case, not only do I find this feature redundant on Firefox, but it's outright distracting and may even break pages. 

I can see why it is included and why it would be helpful, but I propose disabling it by default, at least on Firefox. Alternatively, make whether to enable or disable Highlighted Search Terms an option in my proposed on-boarding feature.

**Comment by ssborbis** [comment]
I just included that in my on-boarding draft not 5 minutes ago. It'll be there.

**Comment by MintMain21** [comment]
Good to know we're on the same page.

**Comment by ssborbis** [comment]
For clarity, I know FF has an additional API for highlighting, but are you saying there's a feature to highlight words after using a search engine?

**Comment by MintMain21** [comment]
No, as far as I know there's no "highlight search terms" feature. I was thinking of the "Find In Page" feature (which is what I use).

Thing is, I don't see the point in searching a term through a search engine and then having that search phrase highlighted perpetually. If there's a phrase I want to look for specifically, I'll use "Find in Page".

For example, lets say I was looking up on Wikipedia films staring Will Ferrel and I specifically wanted to know the name of the film where he was in a presidential campaign against Zach Galifianakis. What I would do first is search say, Will Ferrell on Wikipedia, and then I would "Find In Page" Zach Galifianakis. 

That's just my workflow, but you get the idea.

My biggest problem with the "Highlight Search Terms" feature is, last I used it, it cause text from my initial search query on say Duck Duck Go to reoccur through every webpage that I went to from the Duck Duck Go page. Not sure if this is still a bug but it annoyed me anyway.

**Comment by ssborbis** [comment]
> My biggest problem with the "Highlight Search Terms" feature is, last I used it, it cause text from my initial search query on say Duck Duck Go to reoccur through every webpage that I went to from the Duck Duck Go page. Not sure if this is still a bug but it annoyed me anyway.

That's an option under Highlighting -> Search Results

[x] Highlight search terms in search results page
[x] Continue highlighting pages on the search results website
[x] Continue highlighting on external websites linked from the search results page

Depending on how the page handles url changes ( hash vs href ), there could be errant behavior. Plus, I haven't checked that function for bugs in ages.
