### ISSUE TITLE
Quick Menu through two submenus

### ISSUE THREAD

**Issue by leex-leex** [ssborbis/ContextSearch-web-ext#407]
Hello
 CS1.31.9
On some sites, when searching from "search bar" the Quick Menu opens through two submenu.
For example here https://yandex.ru/images/search?text=auto

![submenu](https://user-images.githubusercontent.com/11260887/145732335-249fb3a1-e057-430e-b1b0-5312b56441ad.jpg)

On most other sites there is no such problem

**Comment by ssborbis** [comment]
Thanks. I'll take a look.

**Comment by ssborbis** [comment]
Fix in the works.  It'll be rolled into other context menu fixes in the next release

**Comment by leex-leex** [comment]
Thanks

**Comment by ssborbis** [comment]
Latest release to AMO and Chromestore is 1.32.6. If you see this problem again, re-open this issue.

Thanks
