### ISSUE TITLE
Highlight search terms only works with google search engine

### ISSUE THREAD

**Issue by DenB10** [ssborbis/ContextSearch-web-ext#408]
Hi,

I've just installed the new version 1.31.9 of Contextsearch in Firefox 91 esr: The search results are highlighted and the findbar appears only if I use the Google search engine and with no other engine.

I specify that the options "Highlight search terms in search results page" and "Show Find bar when highlighting" are well checked.

I tried on a new created profile with only ContextSearch as add-on and I have the same problem.

Moreover, when the findbar appears (with Google), its content isn't correctly centered vertically (problem already mentioned in a previous thread).

Can you reproduce this or is it from my configuration?
Thank you.

P.S.: I'm going to completely revise the French translation because there is a lot of work and some texts are not localizable!

**Comment by ssborbis** [comment]
Thanks for the heads up. I think it may be a fluke it's working on google. It probably shouldn't be working anywhere. I'm seeing the problem with the code now.

**Comment by ssborbis** [comment]
FYI, there are plenty of words I need to add to the translation pages that are currently hard-coded. Right now, I'm patching bugs so try not to get too far ahead of me.

**Comment by ssborbis** [comment]
Updates in the dev repo and I'll have a signed beta up shortly 1.32a2

**Comment by DenB10** [comment]
> FYI, there are plenty of words I need to add to the translation pages that are currently hard-coded. Right now, I'm patching bugs so try not to get too far ahead of me.

No problem

> Updates in the dev repo and I'll have a signed beta up shortly 1.32a2

Fixed issue except the findbar position:

![Presse-papiers-1](https://user-images.githubusercontent.com/9309147/145889444-91ebb405-4925-42cf-8ed8-672420c8f39d.png)

**Comment by ssborbis** [comment]
what OS/Browser are you on? And also, what CS theme?

**Comment by DenB10** [comment]
OS: Win7 64-bit
Browser: FF 91esr 64-bit
CS theme: lite (But it's the same with the other themes)

**Comment by ssborbis** [comment]
I'm not seeing this issue in any of my testing. 

I did notice some addon css being cached and not updating properly when I was developing. Man, that was a headache to track down.

Can you navigate to the findbar css and paste the contents ( maybe do a forced reload of the page once you get there ). The URL will be something like moz-extension://41824b79-6350-46a3-bee6-49e15ac840af/findbar.css , depending on what your current extension ID is. I found mine by opening CS options and replacing .../options.html with .../findbar.css. Then I can at least check your cache.

**Comment by DenB10** [comment]
I'm not sure I understand what exactly you want me to do. If I open the findbar.css file via the browser's address bar, its content is exactly the same as if I open it directly in the .xpi file with notepad!

Note that if I check the option to open automatically the finbar when the page is loaded, the problem no longer exists and the finbar is correctly displayed. Strange!

Another remark concerning the findbar: the up and down arrows for "next match" and "previous match" seem to be reversed and the tooltips do not appear. Small changes to be made in the findbar.html and findbar.js files?

**Comment by ssborbis** [comment]
> I'm not sure I understand what exactly you want me to do. If I open the findbar.css file via the browser's address bar, its content is exactly the same as if I open it directly in the .xpi file with notepad!

Ok, if the content is the same, it's probably not a cache issue. Though, I can't see any other reason why the formatting is different for you.

> Note that if I check the option to open automatically the finbar when the page is loaded, the problem no longer exists and the finbar is correctly displayed. Strange!

I'll try that

> Another remark concerning the findbar: the up and down arrows for "next match" and "previous match" seem to be reversed and the tooltips do not appear. Small changes to be made in the findbar.html and findbar.js files?

Fixed locally. I also removed the docking double-click handler from the next/prev buttons.

**Comment by ssborbis** [comment]
I added those changes to the dev repo, and used a trick to force the findbar css to reload if it was cached. May be worth a shot.

**Comment by DenB10** [comment]
I must be blind but I don't see anywhere the added changes you are talking about, the latest version I find is still 1.32a2.

Or maybe I'm stupid and I don't know where the "dev rep"o is!

**Comment by ssborbis** [comment]
Sorry, yeah I meant the dev repo; sideloading the source code

**Comment by DenB10** [comment]
I don't understand: the source code I downloaded under 1.32a2 seems to be dated September 24 and the manifest says version 1.29???

**Comment by ssborbis** [comment]
Ah, are you looking at the chrome_manifest.json? I'm certain that isn't up to date.

**Comment by ssborbis** [comment]
I pushed updates to chrome_manifest.json and firefox_manfest.json. Untested, but they should work

**Comment by ssborbis** [comment]
new release 1.32.3 should take care of this issue

**Comment by DenB10** [comment]
Titled issue effectively solved in the last versions, thanks.
I prefer open a new issue for the findbar because the layout is still not correct.
