### ISSUE TITLE
(Version 1.32a2 Pre-Release) Add-To-Context-Search missing.

### ISSUE THREAD

**Issue by MintMain21** [ssborbis/ContextSearch-web-ext#409]
I upgraded from Pre-Release 1.32a1 (which resolved my Context Menu issue) to 1.32a2 because I was curious about the "reworked Add to Context Search" update. I immediately right-clicked on a search input as usual, but the context menu option to add a search engine was missing. Then, I right-clicked on highlighted text on the same page and found the option at the top above my default search engine (DDG). Clicking that seemed to do nothing but make the option disappear again. 

Seeing as this is a Pre-Release, I'm more than happy to downgrade back to 1.32a1, but I felt like it was important to report this anyway seeing as it is a Pre-Release that could affect the final release on Firefox etc.

**Comment by ssborbis** [comment]
Thanks. That's definitely related to some code I'm working on.

**Comment by ssborbis** [comment]
Yep, it's working in the new contextual layout context menu, but not the legacy menu. I'll get it patched up. Thanks again.

**Comment by ssborbis** [comment]
probable fix in the repo
