### ISSUE TITLE
Couldn't update/install in Chrome Webstore.

### ISSUE THREAD

**Issue by lshilshi** [ssborbis/ContextSearch-web-ext#413]
It's nice to see the update of ver 1.32.

But couldn't update manually,
so I uninstall CS first,
then, couldn't install in Chrome Webstore.

Popup prompt
```
Image decode failed：“logo_notext.svg”
```

How to solve this error？
Thx！

**Comment by ssborbis** [comment]
Ugh, stupid chromestore. Lemme try another update with a png instead of an svg.

**Comment by ssborbis** [comment]
... still working on it

When you see it published on the chrome store, v1.32.3 might work.

**Comment by ssborbis** [comment]
Ok, 1.32.3 is live. It installs normally

**Comment by lshilshi** [comment]
> Ok, 1.32.3 is live. It installs normally

ok,I have installed success.
Thx!

**Comment by ssborbis** [comment]
Thank you, for the bug report. I'd never have known.
