### ISSUE TITLE
Template Parameters：Page url？

### ISSUE THREAD

**Issue by lshilshi** [ssborbis/ContextSearch-web-ext#415]
When I want to add Google's url translation,
I couldn't get the page or frame url，
{searchTerms} return blank？

I checked the readme，
```
{searchTerms} ：The current selection or link URL / image URL
```

How do I get the URL of the current  page or frame?

**Comment by ssborbis** [comment]
It's not you. The code isn't passing the url to the engines for page and iframe, and perhaps other contexts.

I'm looking into it now.

**Comment by ssborbis** [comment]
I made a push to the dev branch with some fixes. If you can sideload, give it a test.

**Comment by lshilshi** [comment]
> I made a push to the dev branch with some fixes. If you can sideload, give it a test.

```
switch ( context ) {
		case "selection":
			searchTerms = info.selectionText.trim();
			break;
		case "link":
			searchTerms = info.linkUrl;
			break;
		case "page":
			searchTerms = tab.url;
			break;
		case "frame":
			searchTerms = info.frameUrl;
			break;
		case "image":
		case "video":
		case "audio":
			searchTerms = info.srcUrl;
			break
```
is this？

ok，use {searchTerms} to get page/frame url too？
Wait ur stable release in chrome webstore.

Thx ur replies！

**Comment by ssborbis** [comment]
Yeah, that's some of the new code. All the relevant changes are in contextMenu.js

From what I can tell, frame and page contexts send the respective URL to the search engines as they should. I think google translate will work after the update.

It may be a day or 2 before I update the chromestore. I'm waiting to close out a few other issues before making a new release. Sit tight.
