### ISSUE TITLE
[Bug/How to do] Search Engines must be contain {searchTerms}?

### ISSUE THREAD

**Issue by lshilshi** [ssborbis/ContextSearch-web-ext#416]
Application Scene: query the whois of the current website.

Page url：
https://github.com/ssborbis/ContextSearch-web-ext

Target url：
https://www.whois.com/whois/github.com

So Search Engines set as：
```
https://www.whois.com/whois/{selectdomain}
```
Engine becomes a folder with all subdomains and paths listed separately correctly in context/quick menu style.

But after select wanted subdomains and paths，
1、conetxt menu
```
No Action！
```
2、quick menu
open 
```
https://www.whois.com/whois/
```
in new tab

why?

**Comment by ssborbis** [comment]
I'm not sure. It's working for me on FF and chrome ( except the context menu isn't showing the subdomains in chrome? No subfolder for {selectdomain} which is weird )

Can you send me your config? Or at least screenshot that engine's template

**Comment by ssborbis** [comment]
I'm putting up a new version. I noticed some other issues in chrome

**Comment by ssborbis** [comment]
Ok, I've patched that bug. I'll drop a new release tomorrow.

**Comment by ssborbis** [comment]
1.32.6 is in the Chrome Store. See if that does it.

**Comment by lshilshi** [comment]
> 1.32.6 is in the Chrome Store ( may not be listed quite yet ). See if that does it.

Thx!
I have updated v1.32.6.

This issue is fixed now.
But the quick menu don't show,
Even when I enabled the shortcut for quickmenu (CTRL+ALT+X), it did not work. 
Meanwhile, the shortcut of findbar (CTRL+ALT+F) is enabled and it works, which should prove that the shortcut is functional.
