### ISSUE TITLE
Findbar not correctly displayed

### ISSUE THREAD

**Issue by DenB10** [ssborbis/ContextSearch-web-ext#421]
I just attach a screenshot with the undocked findbar to explain.
I think you'll understand what I mean.
![findbar-sc](https://user-images.githubusercontent.com/9309147/146744187-6d1255cb-6bed-4c2c-81fd-69e20961c0bf.png)

**Comment by ssborbis** [comment]
I'm not seeing this problem in either FF or chrome.

Does it happen using english?
Do you use any custom CSS?

**Comment by ssborbis** [comment]
In any case, I added some hidden overflow to the findbar. Without it, if the iframe width is even a single pixel short, it will cause that wrapping you see. 

dev branch has a fix up

**Comment by DenB10** [comment]
> Does it happen using english?

Indeed, I just tried it in English and the wrap problem does not exist anymore.

> Do you use any custom CSS?

No, I even just reset my Firefox profile with just CS installed and the problem remains.

In addition to this problem, you also notice that the content of the bar is not correctly centered vertically, even if the bar is docked. (The search box touches the top border.)

**Comment by DenB10** [comment]
I think I must add something in the style.css file but I don't know what.

**Comment by DenB10** [comment]
> dev branch has a fix up

OK, it works, wrapping disappeared... but not the vertical defect I mentioned above.
In any case, thank you for your efforts.

**Comment by ssborbis** [comment]
Is the vertical spacing wrong using English?

**Comment by DenB10** [comment]
Yes. I managed to fix the problem by making some changes in findbar.css. Not sure it is very "academic":

`#findbar {
	padding-top:4px;
	position:fixed;
	top:1px;
}
#searchBar {
	width: 265px;
	padding:0 24px 0 8px;
}
#previous, #next {
	margin-left:3px;
}
#clearSearchBarButton {
	left:334px;
}`

**Comment by ssborbis** [comment]
Hey, whatever works. I still don't understand why we're seeing different layouts, though.

You could add those changes to CS Options -> General -> User Styles so you don't need to keep editing the files.

**Comment by DenB10** [comment]
> You could add those changes to CS Options -> General -> User Styles so you don't need to keep editing the files.

It's true. Actually, I didn't think of that.

**Comment by ssborbis** [comment]
I finally saw this issue and hope it's fixed.

It only happens for me when using the Find in Page tool, not when simply highlighting a word and opening the findbar with a shortcut. It's the weirdest thing - all the styling elements are the same, but toggling the padding-top:5px; off and back on fixes it. No idea whats going on, but I changed some CSS and it's fixed for me.

**Comment by DenB10** [comment]
It is fixed effectively, thank you.

**Comment by ssborbis** [comment]
1.33 is live in AMO and chromestore
