### ISSUE TITLE
On context.reverso.net (two-line element format not working)

### ISSUE THREAD

**Issue by leex-leex** [ssborbis/ContextSearch-web-ext#422]
Hi
I added the "context.reverso.net" 
Today I found that this search engine has been causes an error on the site page: "An error ocurred. Please excuse us.
Shortly you will be redirected to the homepage" if searching  two-line element format.

for example to search phrases:
"go to the cinema" search in one string - no problem
but
"go to
the cinema" - causes an error

**Comment by ssborbis** [comment]
You can use the Modify Terms Regex field to remove all newlines prior to sending the search to the engine.

Something like 
`"\\r?\\n|\\r", ""` ( untested )

**Comment by leex-leex** [comment]
Thank you It works! but merge lines into one without splitting 
"go tothe cinema"
How to divide it?

**Comment by ssborbis** [comment]
replace with a space?

`"\\r?\\n|\\r", " "`

**Comment by leex-leex** [comment]
Cool! works as expected.
Thanks Ssborbis :)

**Comment by leex-leex** [comment]
Ssborbis please tell Is it possible ignor quotation marks.
If I select it when searching, but so that are not search it on the page with the result?

There are other sites where quotation marks when searching create another condition

**Comment by ssborbis** [comment]
Use the same regex field. It accepts one regex replacement per line. Resize the field from the lower right corner if you need to.

something like this ( untested )
```
"\\r?\\n|\\r", " "
"\"", ""
```

**Comment by leex-leex** [comment]
Thank you it works!
