### ISSUE TITLE
Feature Suggestion: Left click to search all, hover the cursor to display the sub-menu

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#423]
<a href="https://sm.ms/image/zQB5wydeLiGYtMJ" target="_blank"><img src="https://s2.loli.net/2021/12/23/zQB5wydeLiGYtMJ.png" alt="quicker_91b2498b-771f-4e5c-b16f-26f00151f424.png"></a>
<img src='https://s2.loli.net/2021/12/23/1szClgTbOum3prW.png' title='quicker_cd041d58-5bcd-4326-b872-66cccb8cc859.png' />

**Comment by ssborbis** [comment]
I assume you found the options for the last two, and the first could not be done with the current API?

**Comment by yejinson** [comment]
> I assume you found the options for the last two, and the first could not be done with the current API?

Yes, I found it. The first one does not have a left-click function, but I think the quick menu is more efficient than the context menu, so I used it. The only drawback is that it is not beautiful. I will post a separate post to explain this problem, thank you.
