### ISSUE TITLE
Suggestion: About the quick menu

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#424]
1、<img src="https://s2.loli.net/2021/12/24/KD7rF2jPEkagHcq.png" alt="quicker_95b67ca5-d390-4bb7-8bcf-67cfbaa6eb09.png"></a>
And can the list mode of the quick menu look like the system context menu? Which is more coordinated and beautiful，Especially the background color of the menu should be white instead of gray.
2、The hollow font of the folder title in grid mode is difficult to read.When uploading the icon to the folder, there is still a box with a yellow background, which is not beautiful. And the folder title is missing, I want the title to be displayed below the icon.
<a href="https://sm.ms/image/9rY8AWekjuUcqSI" target="_blank"><img src="https://s2.loli.net/2021/12/24/9rY8AWekjuUcqSI.png" alt="quicker_36f7711e-3619-42d6-b79f-c7b819270d48.png"></a>

**Comment by ssborbis** [comment]
You can restyle the menus as you see fit.

See CS Options -> General -> User Styles

There's info in the readme too. https://github.com/ssborbis/ContextSearch-web-ext#styling

**Comment by ssborbis** [comment]
See #397 about the title bar

**Comment by yejinson** [comment]
> You can restyle the menus as you see fit.
> 
> See CS Options -> General -> User Styles
> 
> There's info in the readme too. https://github.com/ssborbis/ContextSearch-web-ext#styling
Well, I'm a novice, I don't know how to design css styles by myself, I hope to have win11 themes or css styles. 
<img src='https://s2.loli.net/2021/12/25/UpKMX25ultOfmY3.png' title='quicker_ca60f6fd-ba27-41d0-ac96-27f308879904.png' />
Is that right? It has no effect.

**Comment by ssborbis** [comment]
Did you copy & paste from #397 ? 

The spacing looks weird.

**Comment by yejinson** [comment]
> 你是从#397复制粘贴的吗？
> 
> 似乎很相似。

I tried again, not only did the menu bar not close, but there was also a blank area on it.
<img src='https://s2.loli.net/2021/12/25/NjhML2ndQAkGlwg.png' title='quicker_3fe05aa1-769b-4939-a13d-3db5cdad0523.png' />

**Comment by yejinson** [comment]
> Did you copy & paste from #397 ?
> 
> The spacing looks weird.

I tried again, not only did the menu bar not close, but there was also a blank area on it.
<img src='https://s2.loli.net/2021/12/25/vIZBFjiGRXPAhQd.png' title='quicker_2072b3c2-86cd-44ea-b428-ab08e4cad2ee.png' />

**Comment by ssborbis** [comment]
The empty space is for the engine title. Hover over an engine to see. That's what the css was for.

If you want to hide the tools bar are the top of the menu, do this.
![tools](https://user-images.githubusercontent.com/24310997/147369246-a6fe013d-b605-449d-b4b2-c9bbb5335a18.png)

**Comment by yejinson** [comment]
> The empty space is for the engine title. Hover over an engine to see. That's what the css was for.
> 
> If you want to hide the tools bar at the top of the menu, do this. ![tools](https://user-images.githubusercontent.com/24310997/147369246-a6fe013d-b605-449d-b4b2-c9bbb5335a18.png)

That's it, it works, thank you very much.

**Comment by yejinson** [comment]
> You can restyle the menus as you see fit.
> 
> See CS Options -> General -> User Styles
> 
> There's info in the readme too. https://github.com/ssborbis/ContextSearch-web-ext#styling

How to change the font of the folder in grid mode, I can't find any instructions or examples, I want to change to Microsoft Yahei.

**Comment by ssborbis** [comment]
It may depend on what CS theme you're using

```
.tile[data-type="folder"]::after {
    text-shadow:none;
}
```

Use that to remove the text shadow

**Comment by yejinson** [comment]
> It may depend on what CS theme you're using
> 
> ```
> .tile[data-type="folder"]::after {
>     text-shadow:none;
> }
> ```
> 
> Use that to remove the text shadow

I used the modern theme, and modified the CSS myself to change the background of the folder to white. According to your method, the font became white and it is invisible. Can I change the font to black? I tried the text-color is invalid.

**Comment by ssborbis** [comment]
```css
.tile[data-type="folder"]::after {
    text-shadow:none;
    color: black !important;
}
```

**Comment by yejinson** [comment]
> it works, thank you

It works, thank you.

**Comment by yejinson** [comment]
> ```css
> .tile[data-type="folder"]::after {
>     text-shadow:none;
>     color: black !important;
> }
> ```

It works, thank you.
