### ISSUE TITLE
Bug：About disabling the context menu

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#425]
When opening the Quick Menu using right-click, on some websites, the context menu will be hidden, but on others, the context menu will pop up. For example, https://en.wikipedia.org/  https://duckduckgo.com/  https://www.pinterest.com/ ,this is maddening. Is there a way to solve this?

**Comment by ssborbis** [comment]
What OS / browser are you on?

Does your context menu show on mousedown or mouseup?

**Comment by yejinson** [comment]
> What OS / browser are you on?
> 
> Does your context menu show on mousedown or mouseup?

windows11 22000.258  chrome 96.0.4664.45
The moment I clicked, I don’t know whether mousedown or mouseup.

**Comment by ssborbis** [comment]
It may be your normal click timing is close to the timeout for the menu. You can try changing the timeout: CS Options -> Advanced -> `quickMenuHoldTimeout`

Raise it to maybe 1000 and see if that helps

**Comment by yejinson** [comment]
> It may be your normal click timing is close to the timeout for the menu. You can try changing the timeout: CS Options -> Advanced -> `quickMenuHoldTimeout`
> 
> Raise it to maybe 1000 and see if that helps

What a coincidence, I tried this before, but it didn't work, I just tried it again and it was useless.

**Comment by ssborbis** [comment]
Do you have any other addons enabled that would be causing a conflict?

I don't know why it would only happen on some pages and not others.

Everything works for me as expected on Chrome + Win10

**Comment by yejinson** [comment]
> Do you have any other addons enabled that would be causing a conflict?
> 
> I don't know why it would only happen on some pages and not others.
> 
> Everything works for me as expected on Chrome + Win10

I found the reason, and conflicted with this:
https://greasyfork.org/zh-CN/scripts/23772-absolute-enable-right-click-copy
Is there any good solution?

**Comment by ssborbis** [comment]
> Is there any good solution?

Probably not. This addon attempts to suppress the context menu, that script prevents it. You can use a different method for opening the quick menu, or disable the script.

**Comment by yejinson** [comment]
> > 有什么好的解决办法吗？
> 
> 可能不是。这个插件试图抑制上下文菜单，该脚本阻止它。您可以使用不同的方法打开快捷菜单，或禁用脚本。

I got it, thanks
