### ISSUE TITLE
Feature request: add utf-8 to hexadecimal encoding

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#426]
as the title, Some websites require

**Comment by ssborbis** [comment]
example?

**Comment by yejinson** [comment]
> example?

https://www.838888.net/

**Comment by ssborbis** [comment]
I can probably add it, but you could use the Search Code field to perform the search using javascript

**Comment by yejinson** [comment]
> I can probably add it, but you could use the Search Code field to perform the search using javascript

I don't know how to write javascript, is there a related tutorial?

**Comment by ssborbis** [comment]
> I don't know how to write javascript, is there a related tutorial?

Then it may be difficult

https://github.com/ssborbis/ContextSearch-web-ext#javascriptengines

Some of the posts near the end of #367 

you can try something like this for the website above

```js
document.querySelector('#search').value = searchTerms;
document.querySelector('#btnSearch').click();
```

**Comment by yejinson** [comment]
> > I don't know how to write javascript, is there a related tutorial?
> 
> Then it may be difficult
> 
> https://github.com/ssborbis/ContextSearch-web-ext#javascriptengines
> 
> Some of the posts near the end of #67
> 
> you can try something like this for https://www.838888.net/
> 
> ```js
> document.querySelector('#search').value = searchTerms;
> document.querySelector('#btnSearch').click();
> ```

It's really hard to understand, I can only use the ready-made code, thank you for the code, it is very useful.
