### ISSUE TITLE
Help: How to add application/json post request search？

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#427]
Does ContextSearch-web-ext support it?

**Comment by ssborbis** [comment]
I'm not sure. I'd need an example engine.

**Comment by yejinson** [comment]
> I'm not sure. I'd need an example engine.

https://feiyu100.cn/

**Comment by ssborbis** [comment]
Here again, I would use the Search Code field

**Comment by ssborbis** [comment]
```js
document.querySelector('input').value = searchTerms;
document.querySelector('input').dispatchEvent(new Event('input'));
document.querySelector('button').click();
```

**Comment by yejinson** [comment]
> ```js
> document.querySelector('input').value = searchTerms;
> document.querySelector('input').dispatchEvent(new Event('input'));
> document.querySelector('button').click();
> ```

It works, thanks
