### ISSUE TITLE
Bug and suggestion: About automatic closing of the menu. 

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#428]
<img src='https://s2.loli.net/2021/12/26/l1peXmQPNDhFaEw.png' title='quicker_fc28ed52-6fd8-4184-be94-8432c1fd64d4.png' />
This option does not work. The menu is always there after searching. It is recommended to move the cursor outside the menu to automatically close.

**Comment by ssborbis** [comment]
What Search Action is bound to the mouse button you're using? If `Open In Background Tab ( keep menu open )` it will stay open.

If the menu is locked, ( using the lock tool ), it will stay open

**Comment by yejinson** [comment]
Open In Background Tab  no keep menu open.Where is the menu lock tool?

**Comment by yejinson** [comment]
> What Search Action is bound to the mouse button you're using? If `Open In Background Tab ( keep menu open )` it will stay open.
> 
> If the menu is locked, ( using the lock tool ), it will stay open

Open In Background Tab no keep menu open.Where is the menu lock tool?

**Comment by ssborbis** [comment]
It's working as expected for me.

The lock tool is this
![locktool](https://user-images.githubusercontent.com/24310997/147403724-48cbb174-ac08-4895-af64-5635a21ea86e.png)

If it's enabled, the menu will remain open.

**Comment by yejinson** [comment]
> It's working as expected for me.
> 
> The lock tool is this ![locktool](https://user-images.githubusercontent.com/24310997/147403724-48cbb174-ac08-4895-af64-5635a21ea86e.png)
> 
> If it's enabled, the menu will remain open.

The default is off, I did not enable it.

**Comment by ssborbis** [comment]
You may have turned it on by accident before hiding the tools. Otherwise, I don't know why the menu would stay open.

**Comment by yejinson** [comment]
> You may have turned it on by accident before hiding the tools. Otherwise, I don't know why the menu would stay open.

No, I reopened the toolbar and tested the switch, but it was useless. When the menu lock is turned on, you click on a blank place on the page, the menu will not be closed. I know the difference between the menu lock on and off.

**Comment by yejinson** [comment]
> You may have turned it on by accident before hiding the tools. Otherwise, I don't know why the menu would stay open.
<img src='https://s2.loli.net/2021/12/26/B2cnNJE1W9exjOU.gif' title='test.gif' />

**Comment by ssborbis** [comment]
Oh, folders. Yeah, I don't think that option ever worked on folders. I'll about patching that.

**Comment by yejinson** [comment]
> Oh, folders. Yeah, I don't think that option ever worked on folders. I'll about patching that.

Ok, Thank you for your effort.

**Comment by ssborbis** [comment]
fix in the dev branch repo

**Comment by yejinson** [comment]
> fix in the dev branch repo

Thank you, I don’t know how to use dev branch repo, when will it be released?

**Comment by ssborbis** [comment]
It will be a while. Lots of changes to critical code that needs to be tested first.

In the meantime, if you're on chrome, you can download the source code from the development branch and 'load unpacked' from chrome -> extensions

**Comment by yejinson** [comment]
> It will be a while. Lots of changes to critical code that needs to be tested first.
> 
> In the meantime, if you're on chrome, you can download the source code from the development branch and 'load unpacked' from chrome -> extensions

It's a success, it's great, thank you so much.
