### ISSUE TITLE
Suggestion:The separator is also valid in context menu mode.

### ISSUE THREAD

**Issue by lshilshi** [ssborbis/ContextSearch-web-ext#429]
Now separator are only available in quick menu mode.

I think the divided display is more eye-catching than the compacted display.

**Comment by ssborbis** [comment]
They aren't displayed if you're using `contextual layout` for the context menu. It would be weird to show all separators when the context ( page / selection / image / etc ) reduces the number of engines to display. You might end up with 1 engine and many separators.

**Comment by lshilshi** [comment]
Suddenly, I noticed that some custom engines were darkened and automatically bottomed out. 
After checking, the engine-related sites are available for access and there are no errors in the template.
How？

**Comment by lshilshi** [comment]
> They aren't displayed if you're using `contextual layout` for the context menu. It would be weird to show all separators when the context ( page / selection / image / etc ) reduces the number of engines to display. You might end up with 1 engine and many separators.

Probably could be a bit smarter, 
a separator is displayed before checking if there are engines before and after at the same directory level that need to be displayed (avoiding single separator display), 
then compress and remove duplicate separators (avoiding duplicate separators display) and directories.

**Comment by ssborbis** [comment]
> Suddenly, I noticed that some custom engines were darkened and automatically bottomed out.
After checking, the engine-related sites are available for access and there are no errors in the template.
How？

I don't understand your meaning.

**Comment by lshilshi** [comment]
> > Suddenly, I noticed that some custom engines were darkened and automatically bottomed out.
> > After checking, the engine-related sites are available for access and there are no errors in the template.
> > How？
> 
> I don't understand your meaning.

Like This.
![image](https://user-images.githubusercontent.com/36767310/147518747-b1c4708a-f67d-4b4b-bb6a-36640dc8ac0a.png)

Template is originally and correct.
![image](https://user-images.githubusercontent.com/36767310/147518844-e4a0282b-58c9-428f-af45-b8276cfe135b.png)

**Comment by ssborbis** [comment]
It looks like they've been "hidden". If you didn't do it, it might have happened if there is a bad drag & drop to rearrange in the quick menu.

Select all the ones to unhide, right-click, choose `Show` from the menu.

![show](https://user-images.githubusercontent.com/24310997/147519302-3a6bbbbb-2008-4b88-b524-a4e25ea0f339.png)
