### ISSUE TITLE
Function suggestion: When the cursor moves to the folder, the search engine menu is automatically displayed. 

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#430]
I am using the quick menu. I use a single search by right-clicking to open the folder and selecting the search engine. I found it easy to make mistakes that I left-click habitually Folder, so I hope to provide the function of automatically displaying all search engines when the cursor moves to the folder, just like the context menu.

**Comment by ssborbis** [comment]
CS Options -> Advanced -> `openFoldersOnHoverTimeout` set to your preferred timeout

**Comment by yejinson** [comment]
> CS Options -> Advanced -> `openFoldersOnHoverTimeout` set to your preferred timeout

This is not good, because the menu is displayed in the original location. When I need to search all, I accidentally enter the folder. What I mean is to display the secondary menu on the right side of the original menu, so that it is convenient to use a single search engine, And it does not affect the search all at the same time.

**Comment by ssborbis** [comment]
If you're wanting a cascading series of popup panels, similar to how the context menu displays, I don't think it's feasible, especially any time soon.  That would require a major rewrite to how this addon currently works.

I'm curious, why don't you use left-click to open the folder like the standard behavior is, and use a middle or right-click to 'search all'?

**Comment by yejinson** [comment]
> If you're wanting a cascading series of popup panels, similar to how the context menu displays, I don't think it's feasible, especially any time soon. That would require a major rewrite to how this addon currently works.
> 
> I'm curious, why don't you use left-click to open the folder like the standard behavior is, and use a middle or right-click to 'search all'?

That’s right. Well, it’s regrettable but it’s okay. I’ll wait, because I’ll make a mistake if I click it quickly. Right-click-select-left-click is the most common operation, but occasionally need to right-click-select-right-click, this time I will habitually click the left button. In addition, in the windows system, opening a folder is a left-click, which is also the reason why it is easy to make mistakes.

**Comment by ssborbis** [comment]
check issue #569 for updates

**Comment by yejinson** [comment]
> 

That's great, but there's a problem that makes the width setting of the singleColumn invalid.

**Comment by yejinson** [comment]
> check issue #569 for updates

That's great, but there's a problem that makes the width setting of the singleColumn invalid.
