### ISSUE TITLE
Function suggestion: add copy function to the quick menu

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#431]
I know that there is a copy button on the toolbar. I don’t need the toolbar and the copy button on the toolbar is too small. I mean that the copy function can be added where the search engine is added.

**Comment by ssborbis** [comment]
Display the tools bar with position 'top' or 'bottom' and uncheck "display as toolbar". Disable any unwanted tools.

**Comment by yejinson** [comment]
> Display the tools bar with position 'top' or 'bottom' and uncheck "display as toolbar". Disable any unwanted tools.

Wow, it turned out to be too great to be able to do this, thank you.

**Comment by ssborbis** [comment]
I'm adding the ability to add tools to the quick menu like you would add engines and folders, that can be moved anywhere in the menu. Eventually, I'll remove the non-toolbar way of displaying in favor of this new way.

![tools](https://user-images.githubusercontent.com/24310997/147789149-d8fb32a6-5a99-4752-8820-66e589767927.jpg)

**Comment by yejinson** [comment]
> I'm adding the ability to add tools to the quick menu like you would add engines and folders, that can be moved anywhere in the menu. Eventually, I'll remove the non-toolbar way of displaying in favor of this new way.
> 
> ![tools](https://user-images.githubusercontent.com/24310997/147789149-d8fb32a6-5a99-4752-8820-66e589767927.jpg)

I tried it, great improvement, thanks.

**Comment by yejinson** [comment]
> I'm adding the ability to add tools to the quick menu like you would add engines and folders, that can be moved anywhere in the menu. Eventually, I'll remove the non-toolbar way of displaying in favor of this new way.
> 
> ![tools](https://user-images.githubusercontent.com/24310997/147789149-d8fb32a6-5a99-4752-8820-66e589767927.jpg)

One small question, can the tool name be customized? For example, can I change “copy to clipboard” to“copy”? I clicked the right-click menu-Edit, but nothing happened. Just deal with it when you have time, no hurry, thank you and happy new year!
