### ISSUE TITLE
Feature request: Quick Menu hold area threshold

### ISSUE THREAD

**Issue by redactedscribe** [ssborbis/ContextSearch-web-ext#432]
In my case, I'm using right-click-and-hold to perform gestures via another extension.

The problem is, the Quick Menu uses the right-mouse button too and so the Quick Menu will appear at the end of my gesture wherever my cursor may end up. I can increase `quickMenuHoldTimeout`, but this means when I do want the Quick Menu, I'm waiting more time than necessary. I'd have to increase it to say 1-1.5s which is much more than the comfortable default of 250ms.

Preferably I'd be able to continue to use the extensions as they are currently set up, hence this feature request:

To summarise, if the Quick Menu had a threshold for the area that it considers a valid "hold", then I could set this value to be small.

For example, threshold set to 10px, if the cursor moves more than 5px in any direction (i.e. a circle) from its initial click location, the `quickMenuHoldTimeout` timer will cancel and no Quick Menu will display. By default, this could be set to `0` to keep the current behaviour (right-click-and-drag to any location, Quick Menu will appear there).

This solution would allow my gestures to easily break the threshold and I'd never see the Quick Menu, unless I was holding the cursor relatively still within my defined threshold.

Thanks!

ContextSearch v1.32.6
Firefox v95.0.2

**Comment by ssborbis** [comment]
This was the case until recently. I had a built-in 4px range movement before cancelling the opening event. I disabled it when troubleshooting and never turned it back on.

I'll see about moving it to a user preference and re-enabling

**Comment by ssborbis** [comment]
in the dev branch now

Be sure to back up your config if you test. I made some significant changes to how settings are restored and saved from the options page. I haven't had any issues, yet, but best to be safe.

**Comment by redactedscribe** [comment]
`quickMenuCancelDeadzone` works as expected. Thanks for the swift turnaround.

**Comment by ssborbis** [comment]
1.33 is live in AMO and chromestore
