### ISSUE TITLE
Multiple search ability

### ISSUE THREAD

**Issue by harryray33** [ssborbis/ContextSearch-web-ext#433]
I've ust come across this...brilliant, it's what I've been looking for.
The only thing lacking, as far as I'm concerned, is the ability to search across user chosen (via check boxes) multiple search engines at the same time.

I've seen a couple of other context addons that include the ability to do this but I like the layout of this.

Any chance of implementing this?

**Comment by ssborbis** [comment]
What menu are you using? The context menu or quick menu?

**Comment by harryray33** [comment]
The context menu...I've only just started using this so I haven't tried the quick menu..in fact, I didn't know there was a quick menu.

**Comment by ssborbis** [comment]
Do you have a link to one of those other addons?

**Comment by harryray33** [comment]
Yes, thanks, one of them is https://github.com/odebroqueville/contextSearch
The option to choose which engines to use with checkboxes is good and so are the options shown in the context menu.

What I don't like about contextsearch is that although it can search multiple engines at the same time it only includes a default list whereas yours has all the engines that I have included on my system.

**Comment by ssborbis** [comment]
Ok, I thought you meant the checkboxes appeared next to each engine in the context menu, and you checked the ones to search with. From everything I've seen, that isn't possible.

So currently there are a couple ways to "multisearch" here,  presuming you're exclusively using the context menu. 

1. Create a folder in the Search Engines manager and move or copy any engines there that you want to open simultaneously. Enable the option `Show an option to search the entire folder at the top of the menu` which adds a `<< search all >> ` entry to the top of the new folder in the context menu.

or

2. create a new engine in the Search Engines manager and set the template to an array of IDs corresponding to the engines you want to use. Not as simple as checkboxes, but I can help you get set up. Option 1 is probably better.

**Comment by harryray33** [comment]
Thanks, I'll give it a try. I could use the first option most of the time but occasionally the search engines I want to use differ from time to time.

Also, I tried using edit in the manager to get an idea of the path used for the engines...Edit works for the default engines but when I try using edit on engines I have included I get an error stating 'firefox engines must be imported.....'

**Comment by ssborbis** [comment]
> Edit works for the default engines but when I try using edit on engines I have included I get an error stating 'firefox engines must be imported.....'

You can't modify Firefox search engines. The API doesn't allow it. You can right-click -> copy though, if you're looking to make copies to place in folders.

If you really want to edit them, you'll have to import your search.json.mozlz4 file using the button below the search engines manger. However, these edits will not be reflected in the Firefox search bar. Effectively, they are separate lists.

**Comment by harryray33** [comment]
I don't want to edit them but just see the search parameters such as template etc.
eg. https://www.bing.com/search?q={searchTerms}

**Comment by ssborbis** [comment]
The 'guts' of Firefox engines are hidden behind the API. The only way to get them is to import the search.json.mozlz4 file.

**Comment by ssborbis** [comment]
Just a heads up, if you're looking at templates to add new engines, you don't need to do it by hand. You can browse to a website, right-click the search bar and choose `Add to ContextSearch`. I worry new users don't know about that. And if you wait a few days for the next release, I'm adding some nice integration with mycroftproject.com

**Comment by harryray33** [comment]
Yes, thanks, I've been using the add to contextsearch...really useful.

Do you think, in the future, you'll implement some sort of check box or choice system for multi find similar to contextsearch? 
At the moment I'll use the first option.

Could you talk me through how to set up the second option please?

Thanks for your help.

**Comment by ssborbis** [comment]
> Is there a way to back up the search engines so that I can re-import them easily in case of a problem. As far as I can see there's just an export for the settings.

The engines should export with the settings. Of course, engines you're adding / removing from Firefox's built-in search bar will not be included in the export - only *references* to those engines. Any engine marked with an orange (FF) in the manager is more of a *shortcut* than a self-contained engine. 

> Do you think, in the future, you'll implement some sort of check box or choice system for multi find similar to contextsearch?
At the moment I'll use the first option.

Maybe not checkboxes, but I already have code written that allows you to ctrl+click rows in the search engines manager to select multiple rows -> right-click -> New Multi-Search. It basically creates a new engine that searches using all the selected engines. Basically, the same function you're used to.

**Comment by ssborbis** [comment]
Here, I just posted a beta. 

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.33b1/contextsearch_web_ext-1.33b1-an+fx.xpi

**Comment by harryray33** [comment]
Great, thank you.

**Comment by ssborbis** [comment]
I noticed some bad recursion ( lots of tabs opening ) when mixing engine types (FF, CS) so I'm gonna replace that beta with another.

P.S. the developer of that addon you mentioned had some things to say #436

**Comment by ssborbis** [comment]
New beta up that should fix the runaway tab creation.

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.33b1/contextsearch_web_ext-1.33b2-an+fx.xpi

**Comment by ssborbis** [comment]
If you try the new way of doing method 2:

       select ( ctrl+click ) multiple engines -> right-click -> `New Multi-Search` 

 let me know how it's working out.

**Comment by harryray33** [comment]
Thanks , I'll give it a try...The reason I mentioned checkboxes is that it enables me to just use the mouse without the keyboard.

**Comment by ssborbis** [comment]
> The reason I mentioned checkboxes is that it enables me to just use the mouse without the keyboard.

I'll get there eventually.

**Comment by harryray33** [comment]
:0) Brilliant....Thank you.

**Comment by ssborbis** [comment]
Things are looking good. To get the checkboxes, you'll need to hold down the left mouse button for 1s

![Peek 2022-01-08 17-55](https://user-images.githubusercontent.com/24310997/148663918-174beaaa-9ee7-4b0d-b2f7-0b0d83afaed9.gif)

**Comment by ssborbis** [comment]
new beta https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.33b1/contextsearch_web_ext-1.33b3-an+fx.xpi

**Comment by ssborbis** [comment]
1.33 is live in AMO and chromestore
