### ISSUE TITLE
Bug: The text in the input box of some websites cannot pop up the quick menu

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#437]
For example:https://chrome.google.com/webstore/category/extensions

**Comment by ssborbis** [comment]
Chrome is probably going to block scripts on it's own addons domain for security reasons. Firefox does the same on addons.mozilla.org. If you use Firefox on the chromestore, or chrome on the firefox store, the menu  works.

**Comment by yejinson** [comment]
> Chrome is probably going to block scripts on it's own addons domain for security reasons. Firefox does the same on addons.mozilla.org. If you use Firefox on the chromestore, or chrome on the firefox store, the menu works.

Well, but neither of these two:
https://www.nordstrom.com/
https://www.elizabetharden.com/

**Comment by ssborbis** [comment]
Got it, thanks. Those websites are cancelling some bubbling mouse events. Looks like I need to set my listeners to capture. Fixes will be in the next version if they don't turn out to break anything else.

**Comment by ssborbis** [comment]
Well, one of them was. The other is a CSS conflict, also fixed ( for those sites anyway )

**Comment by yejinson** [comment]
> Well, one of them was. The other is a CSS conflict, also fixed ( for those sites anyway )

wow, fast and awesome, thanks a lot.
