### ISSUE TITLE
Feature suggestion: Don't open the page that already exists

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#439]
I found that when the same search engine is saved in different folders, the already searched content will be searched again, I hope the extension can recognize the currently opened page and don't open it repeatedly.

**Comment by ssborbis** [comment]
Can you elaborate? I don't quite understand.

**Comment by yejinson** [comment]
> Can you elaborate? I don't quite understand.

Sorry for the delay and didn't reply in time, I mean assuming I added google in both folder 1 and folder 2, I searched once with folder 1, and when I searched for the same keyword with folder 2, it would open The google page of the same search results, I hope not to open again, because it is already there.

**Comment by ssborbis** [comment]
I have something in the development branch worth testing

You'll need to enable `preventDuplicateSearchTabs` from advanced settings -> manual edit.

It should prevent any duplicate engine + duplicate search terms from opening a search tab until the original tab is removed or activated. It will probably only work as intended when opening to background tabs.

**Comment by yejinson** [comment]
> I have something in the development branch worth testing
> 
> You'll need to enable `preventDuplicateSearchTabs` from advanced settings -> manual edit.
> 
> It should prevent any duplicate engine + duplicate search terms from opening a search tab until the original tab is removed or activated. It will probably only work as intended when opening to background tabs.

I tried it, it works for the same folder, but not for different folders, and it still opens repeatedly.

**Comment by ssborbis** [comment]
Just to be clear, you copied some engines `As Shortcut` and placed those in separate folders? Or you made copies of an engine with slightly different names and moved those to separate folders?

**Comment by yejinson** [comment]
> 

The previous version doesn't seem to have a shortcut, only copy the search engine, I use the latter, I just tried the shortcut and it works, it's great, but there is a small problem, how can I identify the search engine in the folder The ontology or its shortcut, can you add an arrow similar to the windows icon or distinguish it in other ways?

**Comment by yejinson** [comment]
> Just to be clear, you copied some engines `As Shortcut` and placed those in separate folders? Or you made copies of an engine with slightly different names and moved those to separate folders?

The previous version doesn't seem to have a shortcut, only copy the search engine, I use the latter, I just tried the shortcut and it works, it's great, but there is a small problem, how can I identify the search engine in the folder The ontology or its shortcut, can you add an arrow similar to the windows icon or distinguish it in other ways?

**Comment by yejinson** [comment]
> Just to be clear, you copied some engines `As Shortcut` and placed those in separate folders? Or you made copies of an engine with slightly different names and moved those to separate folders?

Is there any functional difference between the two? If not, then this is fine, and there seems to be no need to differentiate.

**Comment by ssborbis** [comment]
I'll still need to change some code to get the shortcut copies to not open duplicates

**Comment by ssborbis** [comment]
Shortcuts are just references to a search engine. If you edit one, all other shortcuts for that engine are changed too. But I forgot, they have different IDs even though they point to the same engine, so don't bother testing the code just yet. I'll let you know when I have something.

**Comment by yejinson** [comment]
> Shortcuts are just references to a search engine. If you edit one, all other shortcuts for that engine are changed too. But I forgot, they have different IDs even though they point to the same engine, so don't bother testing the code just yet. I'll let you know when I have something.

  Okay, thanks for your efforts, you're the best developer, I've ever met, thanks again.

**Comment by ssborbis** [comment]
On a second look, I think attempting to search shortcuts in separate folders should be cancelled, as expected in the last push. Be aware, this will ONLY work for shortcuts. This code isn't clever enough to compare templates or anything like that. If you need something more robust, I'll have to think on implementation.

For testing, I Copy -> As Shortcut a few Google engines and placed into  empty folders. Then I ran folder searches from the quick menu to see if the duplicates were suppressed. It seems to be working like it should. YMMV

![shortcut](https://user-images.githubusercontent.com/24310997/151674174-a5220b3b-557f-4684-bedd-ae6b15c87934.jpg)


> The previous version doesn't seem to have a shortcut, only copy the search engine,

It was there, but broken ( failed to actually add the shortcut ). I anticipated a scenario like yours; same engine, different folder for convenience / folder search.

**Comment by yejinson** [comment]
> On a second look, I think attempting to search shortcuts in separate folders should be cancelled, as expected in the last push. Be aware, this will ONLY work for shortcuts. This code isn't clever enough to compare templates or anything like that. If you need something more robust, I'll have to think on implementation.
> 
> For testing, I Copy -> As Shortcut a few Google engines and placed into empty folders. Then I ran folder searches from the quick menu to see if the duplicates were suppressed. It seems to be working like it should. YMMV
> 
> ![shortcut](https://user-images.githubusercontent.com/24310997/151674174-a5220b3b-557f-4684-bedd-ae6b15c87934.jpg)
> 
> > The previous version doesn't seem to have a shortcut, only copy the search engine,
> 
> It was there, but broken ( failed to actually add the shortcut ). I anticipated a scenario like yours; same engine, different folder for convenience / folder search.

Why should I cancel searching for shortcuts in separate folders? No problem found.
Yes, for shortcuts, it works.
Well, that should be because I didn't pay attention before sorry.
