### ISSUE TITLE
Page Tiles show too easily for links

### ISSUE THREAD

**Issue by SomeDude77** [ssborbis/ContextSearch-web-ext#440]
I think this started since the next to last update, or maybe the last one. Many times just mere clicking on a link shows the page tiles. Any way to adjust the sensitivity of this? Or disable link searching for page tiles altogether?

**Comment by ssborbis** [comment]
Page tiles only open on drag events so you must be moving the mouse a little on the left-click? I'll see about adding some deadzone.

What OS and browser?

**Comment by ssborbis** [comment]
update in the repo if you want to try. Default is a 4px deadzone. You'll need to use the manual editor from the advanced menu ( button at the top-right ) and find 
```
pageTiles: {
     ...  
     deadzone: 4
 } 
```

**Comment by ssborbis** [comment]
* development repo

**Comment by SomeDude77** [comment]
I'm using Windows 11, Firefox 96.0.1.

I tried setting the deadzone to 400000, didn't change anything.

**Comment by ssborbis** [comment]
That's weird. I'm looking at the code now. There's no way a dragzone setting that high should trigger the pageTiles. Do you have some other addon that would dispatch a drag event?

Here's the relevant code. Unless something is messing with the event.clientX and event.clientY numbers, I don't see how you could be triggering the pagetiles

```js

let startCoords;
let searchTerms;

document.addEventListener('dragstart', e => {

	if ( !userOptions.pageTiles.enabled ) return;

	let dragOverHandler = e => {
		if ( !userOptions.pageTiles.enabled ) return;

		if ( Math.abs(startCoords.x - e.clientX) < userOptions.pageTiles.deadzone && Math.abs(startCoords.y - e.clientY) < userOptions.pageTiles.deadzone ) return;

		browser.runtime.sendMessage({action: "setLastSearch", lastSearch: searchTerms})
			.then( () => browser.runtime.sendMessage({action: "openPageTiles"}));

		document.removeEventListener('dragover', dragOverHandler);
	}

	startCoords = {x: e.clientX, y: e.clientY};
	searchTerms = getSelectedText(e.target);

	document.addEventListener('dragover', dragOverHandler);
	document.addEventListener('dragend', e => document.removeEventListener('dragover', dragOverHandler));
});
```

**Comment by ssborbis** [comment]
Could you double-check that your dragzone setting is saved? Open CS options, type 
`userOptions.pageTiles.dragzone` in the console.

**Comment by ssborbis** [comment]
Sorry, i kept saying dragzone, I meant deadzone... been looking at the drag events too much

**Comment by SomeDude77** [comment]
Hmm yeah i typed userOptions.pageTiles.deadzone in the console, and it stays until next time i load the extension's options... Or something else is supposed to happen after i type that in the console?

**Comment by ssborbis** [comment]
I just want to be sure the value is still 400000

**Comment by SomeDude77** [comment]
Well here's my full settings form the advanced tab: 

`{
    "addSearchProviderHideNotification": false,
    "allowHotkeysWithoutMenu": false,
    "alwaysAllowTileRearranging": false,
    "autoCopy": false,
    "autoPasteFromClipboard": false,
    "blockList": [
        "moz-extension://*",
        "chrome://*"
    ],
    "cacheIcons": true,
    "cacheIconsMaxSize": 32,
    "checkContextMenuEventOrder": true,
    "contextMenu": true,
    "contextMenuBookmarks": false,
    "contextMenuClick": "openNewTab",
    "contextMenuContextualLayoutFlattenLimit": 10,
    "contextMenuCtrl": "noAction",
    "contextMenuHotkeys": false,
    "contextMenuKey": 0,
    "contextMenuMiddleClick": "noAction",
    "contextMenuOnImages": true,
    "contextMenuOnLinks": true,
    "contextMenuRegexMatchedEngines": false,
    "contextMenuRightClick": "openCurrentTab",
    "contextMenuSearchLinksAs": "text",
    "contextMenuShift": "noAction",
    "contextMenuShowAddCustomSearch": false,
    "contextMenuShowFolderSearch": false,
    "contextMenuShowRecentlyUsed": false,
    "contextMenuShowRecentlyUsedAsFolder": true,
    "contextMenuShowSettingsFolder": false,
    "contextMenuTitle": "",
    "contextMenuUseContextualLayout": false,
    "contextMenuUseInnerText": false,
    "customSearchActions": [],
    "defaultGroupColor": "#CED7FF",
    "defaultGroupColorText": "#444444",
    "disableNewTabSorting": false,
    "enableAnimations": false,
    "exportWithoutBase64Icons": false,
    "forceOpenResultsTabsAdjacent": false,
    "forceOpenReultsTabsAdjacent": false,
    "groupFolderRowBreaks": false,
    "groupLabelMoreTile": false,
    "hiddenEngines": "",
    "highLight": {
        "enabled": false,
        "followDomain": false,
        "followExternalLinks": false,
        "showFindBar": false,
        "flashSelected": false,
        "highlightStyle": "underline",
        "opacity": 1,
        "styles": [
            {
                "color": "#ffffff",
                "background": "#ff00ff"
            },
            {
                "color": "#000000",
                "background": "#ffa500"
            },
            {
                "color": "#ffffff",
                "background": "#428bca"
            },
            {
                "color": "#000000",
                "background": "#ffff00"
            }
        ],
        "activeStyle": {
            "color": "#ffffff",
            "background": "#65ff00"
        },
        "navBar": {
            "enabled": false
        },
        "findBar": {
            "startOpen": false,
            "openInAllTabs": false,
            "searchInAllTabs": false,
            "showNavBar": false,
            "position": "bottom",
            "keyboardTimeout": 200,
            "windowType": "docked",
            "offsets": {
                "top": 0,
                "left": 0,
                "right": 9007199254740991,
                "bottom": 9007199254740991
            },
            "markOptions": {
                "separateWordSearch": true,
                "ignorePunctuation": true,
                "caseSensitive": false,
                "accuracy": "partially",
                "limit": 0
            },
            "scale": 1
        },
        "markOptions": {
            "separateWordSearch": true,
            "ignorePunctuation": true,
            "caseSensitive": false,
            "accuracy": "exactly",
            "limit": 0
        }
    },
    "lastUsedId": "JS2DBGIY5RLA4",
    "modify_mycroftproject": true,
    "nightMode": true,
    "omniboxDefaultToLastUsedEngine": false,
    "omniboxLastUsedIds": [],
    "omniboxSearch": "openBackgroundTab",
    "openFoldersOnHoverTimeout": 0,
    "pageTiles": {
        "enabled": true,
        "rows": 5,
        "columns": 9,
        "openMethod": "openNewTab",
        "grid": [
            "JS2DBGIY5RLA4",
            "JS2DBGJ0Z52TH",
            "KUR9PXA4NGKDO",
            "KUR9PXA45VF81",
            "KUR9PXA4ZKXJG",
            "KUR9PXA4F4V15",
            "KUR9PXA4SUBM6",
            "KUR9PXA4UE3AD",
            "KUR9PXA4DTFMJ",
            "KUR9PXA4Z0RVB",
            "KUR9PXA4EH4O9",
            "KUR9PXA4TINCD",
            "KUR9PXA4I5S32",
            "KUR9PXA4APFZA",
            "KUR9PXA489WQ5",
            "KUR9PXA4BTI8L",
            "KUR9PXA4A1ZSR",
            "KUR9PXA4RSQ5E",
            "JS2DBGJ1GLMKO",
            "KUR9PXA497BGC",
            "KUR9PXA4L38A1",
            "KUR9PXA48IHNF",
            "KUR9PXA4RM75O",
            "KUR9PXA4WOX62",
            "KUR9PXA4V1WBK",
            "JS2DBGJ38NMVK",
            "KUR9PXA449HSA",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        "paletteString": "93a3b1-7c898b-636564-4c443c-322214",
        "closeOnShake": false
    },
    "quickMenu": false,
    "quickMenuAllowContextMenuNew": false,
    "quickMenuAlt": "noAction",
    "quickMenuAlwaysShowMenuBar": false,
    "quickMenuAuto": false,
    "quickMenuAutoAlt": false,
    "quickMenuAutoCtrl": false,
    "quickMenuAutoMaxChars": 0,
    "quickMenuAutoOnInputs": true,
    "quickMenuAutoShift": false,
    "quickMenuAutoTimeout": 5000,
    "quickMenuBookmarks": false,
    "quickMenuCancelDeadzone": 400000,
    "quickMenuCloseOnClick": true,
    "quickMenuCloseOnEdit": false,
    "quickMenuCloseOnScroll": true,
    "quickMenuColumns": 5,
    "quickMenuContextualLayoutFlattenLimit": 10,
    "quickMenuCtrl": "noAction",
    "quickMenuDomLayout": "",
    "quickMenuDragAlt": false,
    "quickMenuDragCtrl": false,
    "quickMenuDragShift": false,
    "quickMenuFocusOnOpen": true,
    "quickMenuFolderAlt": "noAction",
    "quickMenuFolderCtrl": "noAction",
    "quickMenuFolderLeftClick": "openFolder",
    "quickMenuFolderMiddleClick": "noAction",
    "quickMenuFolderRightClick": "noAction",
    "quickMenuFolderShift": "noAction",
    "quickMenuHideSeparatorsInGrid": false,
    "quickMenuHoldTimeout": 250,
    "quickMenuIcon": {
        "enabled": false,
        "x": 0,
        "y": 0,
        "url": "icons/logo_notext.svg",
        "scale": 1
    },
    "quickMenuIconScale": 1.25,
    "quickMenuKey": 0,
    "quickMenuLeftClick": "openNewTab",
    "quickMenuMiddleClick": "noAction",
    "quickMenuMouseButton": 3,
    "quickMenuOffset": {
        "x": 0,
        "y": -20
    },
    "quickMenuOnDrag": false,
    "quickMenuOnImages": false,
    "quickMenuOnKey": false,
    "quickMenuOnLinks": true,
    "quickMenuOnMouse": true,
    "quickMenuOnMouseMethod": "hold",
    "quickMenuOnSimpleClick": {
        "enabled": false,
        "button": 1,
        "alt": false,
        "ctrl": true,
        "shift": false,
        "useInnerText": false
    },
    "quickMenuOpeningOpacity": 1,
    "quickMenuPosition": "top center",
    "quickMenuPreventPageClicks": false,
    "quickMenuRegexMatchedEngines": false,
    "quickMenuRightClick": "openCurrentTab",
    "quickMenuRows": 2,
    "quickMenuRowsSingleColumn": 6,
    "quickMenuScale": 2.5,
    "quickMenuSearchBar": "hidden",
    "quickMenuSearchBarFocus": true,
    "quickMenuSearchBarSelect": false,
    "quickMenuSearchHotkeys": "noAction",
    "quickMenuSearchHotkeysFolders": "noAction",
    "quickMenuSearchOnMouseUp": false,
    "quickMenuShift": "noAction",
    "quickMenuShowHotkeysInTitle": false,
    "quickMenuShowRecentlyUsed": false,
    "quickMenuTheme": "dark",
    "quickMenuTilesDraggable": true,
    "quickMenuToolbarRows": 1,
    "quickMenuTools": [
        {
            "name": "disable",
            "disabled": false
        },
        {
            "name": "close",
            "disabled": false
        },
        {
            "name": "copy",
            "disabled": false
        },
        {
            "name": "link",
            "disabled": false
        },
        {
            "name": "lock",
            "disabled": false,
            "persist": false
        },
        {
            "name": "lastused",
            "disabled": true
        },
        {
            "name": "repeatsearch",
            "disabled": true,
            "persist": false,
            "on": false
        },
        {
            "name": "toggleview",
            "disabled": true
        },
        {
            "name": "findinpage",
            "disabled": true
        },
        {
            "name": "openoptions",
            "disabled": true
        },
        {
            "name": "toggle_theme",
            "disabled": true
        },
        {
            "name": "toggle_hotkeys",
            "disabled": true
        },
        {
            "name": "edit",
            "disabled": true
        },
        {
            "name": "block",
            "disabled": true
        },
        {
            "name": "recentlyused",
            "disabled": true
        },
        {
            "name": "showhide",
            "disabled": true
        }
    ],
    "quickMenuToolsAsToolbar": false,
    "quickMenuToolsPosition": "hidden",
    "quickMenuTrackingProtection": true,
    "quickMenuUseContextualLayout": false,
    "quickMenuUseOldStyle": false,
    "recentlyUsedList": [
        "JS2DBGIY5RLA4",
        "JS2DBGJ0Z52TH",
        "KUR9PXA45VF81",
        "KUR9PXA449HSA",
        "KUR9PXA4Z0RVB",
        "JS2DBGJ38NMVK",
        "KUR9PXA4A1ZSR",
        "KUR9PXA4F4V15",
        "KUR9PXA4NGKDO",
        "KUR9PXA4ZKXJG"
    ],
    "recentlyUsedListLength": 10,
    "rememberLastOpenedFolder": false,
    "rightClickMenuOnMouseDownFix": false,
    "searchBarCloseAfterSearch": false,
    "searchBarColumns": 11,
    "searchBarDisplayLastSearch": false,
    "searchBarDomLayout": "",
    "searchBarEnableHistory": false,
    "searchBarHistoryLength": 1024,
    "searchBarIcon": "icons/logo.svg",
    "searchBarSuggestions": false,
    "searchBarSuggestionsCount": 20,
    "searchBarUseOldStyle": false,
    "searchBaricon": "icons/icon.svg",
    "searchEnginesManagerShowContexts": true,
    "shakeSensitivity": 3,
    "sideBar": {
        "enabled": true,
        "columns": 6,
        "singleColumn": false,
        "hotkey": [],
        "startOpen": false,
        "widget": {
            "enabled": false,
            "position": "right",
            "offset": 100
        },
        "windowType": "undocked",
        "offsets": {
            "top": 100,
            "left": 9007199254740991,
            "right": 0,
            "bottom": 9007199254740991
        },
        "position": "right",
        "height": 400,
        "closeAfterSearch": false,
        "rememberState": false,
        "openOnResults": false,
        "openOnResultsMinimized": false,
        "scale": 1,
        "domLayout": "",
        "setMinWidth": true
    },
    "syncWithFirefoxSearch": false,
    "userShortcuts": [
        {
            "alt": false,
            "ctrl": true,
            "meta": false,
            "shift": true,
            "key": "F",
            "id": 1,
            "enabled": false
        }
    ],
    "userStyles": "/* add custom styles to menus here */\n/* .tile { width:64px; } */\n\nuserOptions.pageTiles.deadzone",
    "userStylesEnabled": true,
    "userStylesGlobal": "",
    "version": "1.33.2"
}`

**Comment by ssborbis** [comment]
Are you using the latest code from the development repo for testing? I don't see the right variable in there anywhere.

Here, let me make a signed beta...

**Comment by SomeDude77** [comment]
Hmm i didn't find the dev repo, i installed the both the 133beta and 1.33, tried both.

**Comment by ssborbis** [comment]
By dev repo, I mean the source code in the development branch. No worries, here's a beta.

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.33.3b/contextsearch_web_ext-1.33.3b-an+fx.xpi

If you want to raise the value, look here:

![deadzone](https://user-images.githubusercontent.com/24310997/149795771-2aceb5fb-550e-435b-bf62-36c64a532bcc.png)

**Comment by SomeDude77** [comment]
Ah ye sorry, I found the dev repo now, but still failed to implement that part of the code. Too noob at coding I guess. Yeah it works. 

Any way to fix it so the tiles automatically hide if I drag a link but change my mind, just like they do when dragging regular text?

**Comment by SomeDude77** [comment]
Hmm for regular text if I just drop the text outside of the tiles then the tiles will go away, but not for links. I don't have the shake to cancel option enabled.

**Comment by ssborbis** [comment]
This is news to me. When you say "outside the tiles", do you mean a blank spot where a tile could be, but you've added an empty tile, or outside the browser, or what?

**Comment by SomeDude77** [comment]
Anywhere on the browser window, just not on any tile.
![34-06](https://user-images.githubusercontent.com/23091893/149798756-6ad00f87-bdab-4aaf-896c-9c1ce472b926.jpg)

**Comment by ssborbis** [comment]
Ok, I'm seeing it. Yeah, for some reason dropping links on an area without a tile isn't closing the menu. I'll check it out.

**Comment by SomeDude77** [comment]
Actually not anywhere it seems. doesn't work if dropped on a menu, or firefox tab.

Ok, thanks.

**Comment by ssborbis** [comment]
K, it's fixed. It will be in the next beta or release

**Comment by SomeDude77** [comment]
Thanks!

**Comment by ssborbis** [comment]
Had another bug worth fixing and making a new release. 1.33.4 is live

**Comment by SomeDude77** [comment]
Wow that was quick, thanks!
