### ISSUE TITLE
Dragging word to share not working sometimes

### ISSUE THREAD

**Issue by minawaheed9697** [ssborbis/ContextSearch-web-ext#443]
When I drag a word or words to search, sometimes the search bar as bellow GIF is empty, and the search page is empty. 
![19_01_2022 07_35_11_022](https://user-images.githubusercontent.com/73688266/150070518-4d93fa70-3f7d-446f-ad2f-dbede75fa725.gif)

**Comment by ssborbis** [comment]
I haven't been able to trigger that bug, but I'll keep trying. Lets try to narrow it down.

What browser / OS?
Does it happen everywhere or only on google?
Does it happen if you disable all other addons?

**Comment by ssborbis** [comment]
I  noticed the selected text is deselected as you start the drag event. That would definitely cause the terms to become blank. That is not normal behavior

**Comment by minawaheed9697** [comment]
Okay.
Browser: Vivaldi version 5.1.2553.3 (Official Build) (64-bit) 
OS: Win 10 Pro 
Till now on Google search and Google images while searing images also, not only words.
Not, I didn't try disabling other add-ons

**Comment by ssborbis** [comment]
I wonder if it's a conflict with `quickMenuDeselectTextOnSearch`. That setting never really made it to the default config, but you may check it's status and turn it off if it's on, just to check.

Open CS options -> open the console, enter 

`userOptions.quickMenuDeselectTextOnSearch`

if it's true, enter
```
userOptions.quickMenuDeselectTextOnSearch = false;
saveOptions();
```

and see if that fixes things.

**Comment by minawaheed9697** [comment]
I am sorry, but I can't find this `quickMenuDeselectTextOnSearch`.
And, do you mean the browser console??

**Comment by ssborbis** [comment]
> And, do you mean the browser console??

Web developer tools. Shift + Ctrl + K

**Comment by ssborbis** [comment]
If you enter `userOptions.quickMenuDeselectTextOnSearch` and it says `undefined` or `false`, the problem is elsewhere.

**Comment by minawaheed9697** [comment]
Yes, it gave me `undefined`

**Comment by ssborbis** [comment]
DId you trying disabling all other addons? Something is causing text to be deselected when you start dragging. I've tried in 3 browsers, include Vivaldi. That is not normal.

**Comment by minawaheed9697** [comment]
I disabled them all, but nothing happened.

**Comment by ssborbis** [comment]
Try disabling CS. Does the text get deselected if you drag?

**Comment by minawaheed9697** [comment]
Yes, it still deselected

**Comment by ssborbis** [comment]
If you've disabled all addons and it's still deselecting text, you've got a browser or OS issue. Text should not be deselected when you start a drag event. That is what is causing the empty search terms.

**Comment by minawaheed9697** [comment]
But, it's working on the same site sometimes.

**Comment by minawaheed9697** [comment]
Ok, thanks for help, bro.

**Comment by ssborbis** [comment]
No prob. If you figure out whats going on, let me know.
