### ISSUE TITLE
How to enable quick menu to prevent page clicks 

### ISSUE THREAD

**Issue by minawaheed9697** [ssborbis/ContextSearch-web-ext#444]
How to enable this feature?? 
<img width="1001" alt="19_01_2022 08_08_03_984" src="https://user-images.githubusercontent.com/73688266/150073917-0bc5d79e-8310-484a-8d7f-93b067050891.png">

**Comment by ssborbis** [comment]
Looks like that's another setting that got left out of the defaults. You'll have to set it from the console.  I'll get that patched

From console in CS Options ->

```
userOptions.quickMenuPreventPageClicks = true;
saveOptions();
```

**Comment by minawaheed9697** [comment]
Should I input this in the console or do you mean change setting manually button??

**Comment by ssborbis** [comment]
I would guess either way would work, but I meant the console

**Comment by minawaheed9697** [comment]
Nothing happens. Still false.
<img width="294" alt="19_01_2022 10_47_39_536" src="https://user-images.githubusercontent.com/73688266/150095603-129c9f1f-256f-41aa-88c1-73be26613aa9.png">

**Comment by ssborbis** [comment]
Looks like you'll have to wait for the next version. The entry in the advanced table is messing things up. I can get you a beta if you're in need.

**Comment by minawaheed9697** [comment]
If the next version will be soon, I'll wait no problem.

**Comment by ssborbis** [comment]
1.34 is up

**Comment by minawaheed9697** [comment]
> 1.34 is up

Thank you so much. It works.

**Comment by ssborbis** [comment]
Good to hear.
