### ISSUE TITLE
Possibility? Auto-paste contents copied from address bar to CS search bar 

### ISSUE THREAD

**Issue by Gd-Gordon** [ssborbis/ContextSearch-web-ext#445]
Now the "autoPasteFromClipboard" feature in advanced option does not work for contents copied from Chrome/Edge's address bar. Is it possible to get auto-paste worked with address bar?

**Comment by ssborbis** [comment]
Is the auto paste working at all? It looks like it needs fixing. 

I think the default behavior, even with that option disabled, is to copy text that has been selected within the current web page into this addon menu's search bars when opened. It doesn't rely on the clipboard at all. That may have been the original intention of that setting, but it's been depreciated now. If it were working properly, it should be doing what you're trying.

Just to be sure, can you walk me through a quick step-by-step of what you're wanting? I'll see about fixing the paste option in the meantime.

**Comment by ssborbis** [comment]
I've posted some fixes to the dev branch. Tested on FF and chromium. Looks good so far.

**Comment by Gd-Gordon** [comment]
Hi, I copied the text selection from browser address bar to system clipboard and it does not show up in CS search bar. I did not know that CS does not rely on clipboard. Sorry about that. The auto-paste feature works fine for selection on webpages.

What I want is to auto-paste selected texts in the address bar to CS search bar without using context menu or keyboard shortcut, just like CS auto-pasting selection on webpages. For example, I first select "github" word from the page link in address bar (Unlike selection on webpages, I found that the selection in address bar disappears when pressing CS toolbar button. So I used Ctrl-C shortcut to copy the selected text). Then, I click the CS toolbar button, and the copied text "github" would automatically show up in CS search bar. 

I don't know whether Chromium allows extension to read and copy contents in address bar. My lazy idea may be impractical and not a must.

**Comment by ssborbis** [comment]
The new code in the dev branch will allow the contents of the clipboard to be automatically pasted into this addons search bars when the menu is opened. However, any text selected outside of a webpage ( address bar in this case ) cannot be auto-copied, so you'll still need to ctrl-C to get the content of the address bar into the clipboard. 

> I don't know whether Chromium allows extension to read and copy contents in address bar. My lazy idea may be impractical and not a must.

Not contents, per se ( obviously, the current URL is exposed ), and certainly not the currently selected text in the address bar AFAIK.

How are you installing to Edge? Does it use the chrome store, or are you sideloading the source?

**Comment by Gd-Gordon** [comment]
I installed CS to Edge from Chrome web store. I also tried sideloading an unpacked CS with replaced files from your dev branch but still not get clipboard auto-pasting. I have little knowledge of extension programming and it 's better for me to wait for a major update in store. Thank you very much for your work!

**Comment by ssborbis** [comment]
I think autoPaste is actually working on Edge, but the prompt to get the ClipboardWrite permission is not.

Did you import your CS options from another install or browser? Try toggling the autoPaste option on and off. It should prompt for the permission again if it doesn't have it.

**Comment by ssborbis** [comment]
I should say, it's working using the latest code in the development repo.

**Comment by ssborbis** [comment]
1.34 is up

**Comment by Gd-Gordon** [comment]
Thanks for the update. I just tested CS 1.34 on Edge Canary 99 and it still cannot read my clipboard contents copied outside webpages including address bar. The "autoCopy" and "autoPasteFromClipboard" in advanced options are checked and "Read and modify data you copy and paste" permission is also given.  If there is restriction or difficulty, this feature can be dropped. Not critical at all.

**Comment by ssborbis** [comment]
Strange. I'm not having any problems, but I'm testing Edge on Linux ( dunno if that's creating a difference )

Just to be clear, you're not relying on autocopy from the address bar, correct? Also, what menu are you attempting to autopaste to?

**Comment by Gd-Gordon** [comment]
I used ctrl-C, not autocopy from the address bar. I am attempting to autopaste copied contents to CS toolbar menu.
<img width="957" alt="Snipaste_2022-01-26_22-52-24" src="https://user-images.githubusercontent.com/65262451/151186306-9aed103d-9269-49ae-b900-ba39ff4672f8.png">

**Comment by ssborbis** [comment]
can you post your config. I'll try it. Maybe there's a conflict with another setting.

Also, you might try disabling all the other addons in case there's a conflict there.

**Comment by Gd-Gordon** [comment]
Sure.
[ContextSearchOptions_2022-01-26_151227.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/7942843/ContextSearchOptions_2022-01-26_151227.zip)

I disable all add-ons except CS. The problem persists.
<img width="960" alt="Snipaste_2022-01-26_23-16-43" src="https://user-images.githubusercontent.com/65262451/151190908-2c2d792e-aa7a-4097-8f34-5bb44e4f1d0f.png">
<img width="960" alt="Snipaste_2022-01-26_23-08-04" src="https://user-images.githubusercontent.com/65262451/151190941-e1984d2f-e27f-4b01-8959-acd4068aa8cb.png">

Selected website text can be autopasted to sidebar and quickmenu searchbar, but clipboard text cannot be autopasted.

**Comment by ssborbis** [comment]
Everything works fine for me using that config. I'm not able to test on Windows, and I'm on Edge v97, but it's difficult to believe either of those is affecting the clipboard function.

Do you see any errors in the console when you open the menu? ( Click the Inspect Views -> Background page from the addon page, then try opening the menu and look for errors ). I did have to tweak the code a bit for it to work with Edge. Maybe there's more to do.

**Comment by ssborbis** [comment]
Now I don't have any issues with Edge for unpacked or chrome store versions. 

I'm seeing some inconsistent permissions behavior, though. I'm certain I needed to open the sidebar menu at least once with text in the clipboard to get a second prompt for allowing clipboard features, in addition to the prompt from the CS options page. After that, all the menus pasted as expected. Let me know if you are seeing any changes with the latest version ( 1.34.1 )

**Comment by Gd-Gordon** [comment]
Cool. The new version also works for me. You did an excellent job! Thank you so much for fulfilling a feature that not requested by many users. That may be the reason why CS is most feature-rich and flexible searching add-on I've ever found.

**Comment by ssborbis** [comment]
Good deal
