### ISSUE TITLE
1.33.4 keyboard not work

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#447]
This version will conflict with the keyboard button when editing the search engine, can't enter the specified location correctly.

**Comment by ssborbis** [comment]
When editing where? The options page or when you add a new engine?

What exactly happens?

**Comment by 7peanuts** [comment]
> When editing where? The options page or when you add a new engine?
> 
> What exactly happens?

when edit engine name and hotkeys

I made a GIF
![1](https://user-images.githubusercontent.com/82173614/151146818-d388a22b-61bd-4cea-8245-4158c3cdf06c.gif)

**Comment by ssborbis** [comment]
Thanks, I'll get a patch up soon

**Comment by ssborbis** [comment]
1.34 is up
