### ISSUE TITLE
"Open as link" in Quick Menu does not work since 1.34

### ISSUE THREAD

**Issue by Fanolian** [ssborbis/ContextSearch-web-ext#449]
### Steps to reproduce
1. In Firefox 96.0.2 or Nightly, install ContextSearch-web-ext 1.34.
2. highlight a link. Quick link: `https://www.example.com`.
3. Open Quick Menu.
4. Click/middle click "Open as link".

### Actual result
Nothing happens. The link does not open.
Web Console shows this error when I click the "Open as link" button:

````
14:47:44.912 Uncaught (in promise) Error: node is null browser-polyfill.min.js:1:9176
    o moz-extension://c7070be4-81d3-4149-b739-8a0a9259e007/lib/browser-polyfill.min.js:1
    o moz-extension://c7070be4-81d3-4149-b739-8a0a9259e007/lib/browser-polyfill.min.js:1
    o self-hosted:1225
    apply self-hosted:2732
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:635
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:837
    withLastError resource://gre/modules/ExtensionCommon.jsm:756
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:825
````

It worked in 1.33.4 but not 1.34.

P.S. Just a reference, I reported a similar issue (#292) a year ago, but it came with a different error meesage in Web Console.

**Comment by ssborbis** [comment]
Thanks! 

I have a fix ready, but mozilla is having some issues right now with authentications. 1.34.1 will go up as soon as possible.

**Comment by ssborbis** [comment]
1.34.1 is live

**Comment by Fanolian** [comment]
Confirm fixed. Thanks a lot.
