### ISSUE TITLE
Adding search engine to favorite images in Imgur

### ISSUE THREAD

**Issue by minawaheed9697** [ssborbis/ContextSearch-web-ext#451]
I don't know if that's possible or not.

I use "Imagus" to preview images and use CS to search for those zoomed images without needing to open them in new tabs.
Likewise, I want a search engine to favorite the zoomed image to "Imgur".

This is the URL of the image without favoring it: https://imgur.com/gallery/kyL3qPw
This is it after being favorite: https://imgur.com/account/favorites/kyL3qPw
What I want is a way to save it as favorite with an engine, e.g. an engine to convert the image link to a favorite link. 

Sorry for that silly thing, but "Imgur" doesn't have any button on the homepage, so I have to open every single image in new tab to save it.

**Comment by ssborbis** [comment]
Walk me through an example of exactly what you're trying to do.

Are you just wanting to modify the URL before searching with CS? Like, imagus shows an image with the URL https://imgur.com/gallery/kyL3qPw, but you really want to do a search for the URL https://imgur.com/account/favorites/kyL3qPw?

Or are you wanting to do a redirect after performing a search? I'm not even sure what search engine you're talking about using. Imgur's search engine? A reverse-image search engine?

**Comment by minawaheed9697** [comment]
I want the CS engine to save the image to "Imgur".
The saved image in "Imgur" is modified from this link: https://imgur.com/gallery/kyL3qPw to this link: https://imgur.com/account/favorites/kyL3qPw. 
So, what I was thinking about is an engine to modify this link automatically so that it can save the image to "Imgur".
Or any way to save the images to "Imgur" favorites.

**Comment by ssborbis** [comment]
I guess I'm not seeing where CS comes in. Take me through a typical scenario.

You're on what page using imagus?
You preview an image
You use a CS search engine to do something??? 
imgur comes in where?

**Comment by ssborbis** [comment]
FYI, I only get a 404 page using the 2nd link you're providing, so that's probably confusing me a bit

**Comment by minawaheed9697** [comment]
I am on the Imgur home page.
Use Imagus to preview the image.
Then open CS, normally I use it to search image in Google or Yandex. 
Now, I want CS engine to save this image to Imgur favorites.

**Comment by ssborbis** [comment]
Ok, I'm kinda getting it You want to perform a search AND run some task that saves to Imgur favorites. Does simply navigating to that 2nd url you provided do the work of "saving" or do you need to click a button? ( I don't have an imgur account so I may not be seeing everything you are )

**Comment by minawaheed9697** [comment]
Saving in Imgur is by opening the image in new tab and then clicking "Save" button. So, I don't know how can I make that with opening the image. I was thinking of using CS to modify the image URL, maybe it save it. Or use it to save that image by any other way.

**Comment by ssborbis** [comment]
To be clear, when you say "save", are you ultimately wanting to download the image to your pc, or are you just adding it to the imgur favorites?

**Comment by minawaheed9697** [comment]
I mean adding it to Imgur favorites. I am sorry for not clearing that.

**Comment by ssborbis** [comment]
No worries. I'm just unfamiliar with the process you're using. I just signed up to imgur to see exactly what's going on. I'll look around a bit and see if there's a way to do what you're wanting.

**Comment by minawaheed9697** [comment]
Okay. Thank you so much for your help.

**Comment by ssborbis** [comment]
Something like this should get it done, so long as the link CS sees points to a gallery image, not a direct link to the image

Template: {searchTerms}
Encoding: none
Post-Search Script:

```js
( async() => {
document.querySelector('.GalleryVote-favorite').click();
await new Promise(r, setTimeout(r, 1000));
document.querySelector('.FavoritesFoldersDialog-content button').click();
})();
```

If you're using links that don't point to the gallery link, you'll need to use some `Modify Terms Regex` to convert the {searchTerms} to the gallery link ( the page with the Add to Favorites button )

**Comment by ssborbis** [comment]
If you're wanting to add to a favorites folder other than the default, you'll need to change the 2nd selector

**Comment by minawaheed9697** [comment]
I made it like this, but nothing happened. It opens an error new tab. 
<img width="478" alt="28_01_2022 20_04_19_835" src="https://user-images.githubusercontent.com/73688266/151598765-5832b3e1-a756-4451-8854-1f63fe4ed7a8.png">

**Comment by ssborbis** [comment]
change encoding

Encoding: no encoding

**Comment by minawaheed9697** [comment]
I changed it. Now it opens the image URL, but not adding it to favorite. 
Did it work with you?? With using Imagus??

**Comment by ssborbis** [comment]
> Did it work with you?? With using Imagus??

No, because imagus was giving me a direct URL to the image, not the gallery URL

If it receives the gallery URL, it works fine

**Comment by ssborbis** [comment]
If imagus is showing CS the direct image link and not the gallery URL, you need to use Modify Search Terms to rewrite the URL from `https://i.imgur.com/9lNJgMc.jpg` to `https://imgur.com/gallery/9lNJgMc` for example

**Comment by minawaheed9697** [comment]
Woo-ow, it works. I just had to open CS directly by holding Rt mouse button on the image or GIF, i.e. not using Imagus. 

But, is there any way to make it doing this without opening a new tab?? It saves the image or GIF, but it opens the post in new tab.  I want it to do it without this opening. Is that possible??

**Comment by ssborbis** [comment]
Nah, you need the tab to exist or there's nothing to execute the javascript on. You can add a line to close the tab when it's done, I suppose.

**Comment by minawaheed9697** [comment]
How can I add this line??

**Comment by ssborbis** [comment]
Whoops. looks like the old `window.close()` doesn't work any more. You might not be able to easily.

**Comment by minawaheed9697** [comment]
Can I block this URL https://imgur.com/gallery/ by uBlock Origin??

**Comment by ssborbis** [comment]
Hmm, yeah but that would block the page you need to click the favorite button.

Instead, maybe at the end of the post-search script, you could set the window.location to some junk URL and let uBlock handle that?

**Comment by ssborbis** [comment]
I'm not sure it would close the tab, though

**Comment by minawaheed9697** [comment]
> Instead, maybe at the end of the post-search script, you could set the window.location to some junk URL and let uBlock handle that?

I didn't get that. Can you explain, please??

**Comment by ssborbis** [comment]
Well, at the end of the script that clicks the 'favorite' button

```js
( async() => {
document.querySelector('.GalleryVote-favorite').click();
await new Promise(r, setTimeout(r, 1000));
document.querySelector('.FavoritesFoldersDialog-content button').click();
})();
```

you could maybe add the line
```js
window.location = 'http://thisIsATotallyMadeUpURL.biz';
```

like so:

```js
( async() => {
document.querySelector('.GalleryVote-favorite').click();
await new Promise(r, setTimeout(r, 1000));
document.querySelector('.FavoritesFoldersDialog-content button').click();

await new Promise(r, setTimeout(r, 1000));
window.location = 'http://thisIsATotallyMadeUpURL.biz';
})();
```

So that tab would redirect to `http://thisIsATotallyMadeUpURL.biz`

If uBlock can close tabs, would it close that tab when the URL changes, provided you added it to the uBlock filters? I don't know enough about uBlock to say. Just a thought

**Comment by minawaheed9697** [comment]
No, there is no redirect happening. And the saving process is not happening too.

**Comment by ssborbis** [comment]
A few things
1. It looks like this code is unnecessary. It seems to save to favorites without needing to select a folder

```js
await new Promise(r, setTimeout(r, 1000));
document.querySelector('.FavoritesFoldersDialog-content button').click();
```

2. You need to make sure the URL being passed to CS is a /gallery/ URL
3. If the post-search code fails due to bad css selectors, it won't make it to the redirect line

**Comment by minawaheed9697** [comment]
> 1. It looks like this code is unnecessary. It seems to save to favorites without needing to select a folder

So, I should delete this code??

**Comment by ssborbis** [comment]
I would.

Change to

```js
( async() => {
document.querySelector('.GalleryVote-favorite').click();

await new Promise(r, setTimeout(r, 1000));
window.location = 'http://thisIsATotallyMadeUpURL.biz';
})();
```

... if you're still wanting the redirect. Otherwise, delete that too

**Comment by minawaheed9697** [comment]
This is working in saving part, but still not redirecting.

**Comment by ssborbis** [comment]
Is it trying to redirect? I know the URL is junk, so it should stall out.

**Comment by ssborbis** [comment]
Does it redirect if you use a legit url? http://google.com or something?

**Comment by minawaheed9697** [comment]
No, it doesn't even try. 
I'll try using http://google.com/

**Comment by minawaheed9697** [comment]
No, also http://google.com/ not redirect.

**Comment by ssborbis** [comment]
Weird. It's working for me

**Comment by ssborbis** [comment]
Chrome or FF?

**Comment by minawaheed9697** [comment]
This is the last engine settings. Is there something wrong??
<img width="472" alt="28_01_2022 21_28_52_793" src="https://user-images.githubusercontent.com/73688266/151609489-5cc4db50-7f0d-4a24-b228-7bab699b4e2e.png">

**Comment by ssborbis** [comment]
ah crap, bad code

remove the await ... timeout line, it's wrong

**Comment by minawaheed9697** [comment]
Now, it's redirecting. I should only find a way to make uBlock close it. 
Thank you so much for your effort  and your time. 
I am so sorry for those tons of questions.

**Comment by ssborbis** [comment]
No prob. Hopefully we can come up with a usable solution. If uBlock doesn't work, I'll see about adding a way to call for a tab to close in future releases

**Comment by minawaheed9697** [comment]
That will be a perfect idea.
I will contact you if I find a solution by uBlock. 
So, if it's possible, let me close the issue post, so I can reopen it if I find a solution.

**Comment by ssborbis** [comment]
Lasted push to the dev branch has means to call the following function from post-search code

`browser.runtime.sendMessage({action:"closeTab"});`

Place that at the end of your script and it will close the tab. I couldn't think of another way.

**Comment by minawaheed9697** [comment]
I made it like this, but nothing happened besides, it can't save to favorites, too. 
<img width="478" alt="29_01_2022 07_47_08_674" src="https://user-images.githubusercontent.com/73688266/151649282-e3efbbaf-8887-4dd2-82c5-99651dbd6ee3.png">
<img width="474" alt="29_01_2022 07_47_23_695" src="https://user-images.githubusercontent.com/73688266/151649283-6ee2613a-4d6a-4062-bfc2-261bb371d2da.png">

**Comment by ssborbis** [comment]
Like this

```js
( async() => {
    document.querySelector('.GalleryVote-favorite').click(); // click the favorite button
    await new Promise(r => setTimeout(r, 1000)); // give some time for the save to complete
    browser.runtime.sendMessage({action:"closeTab"}); // close the tab
})();
```

**Comment by minawaheed9697** [comment]
It's saving, but still not closing. 
<img width="479" alt="29_01_2022 14_44_50_095" src="https://user-images.githubusercontent.com/73688266/151661580-2057f70d-cccd-4d84-8570-69371337bf3d.png">

**Comment by ssborbis** [comment]
Are you using the source code from the development branch?

**Comment by minawaheed9697** [comment]
> Are you using the source code from the development branch?

Sorry, I didn't get that. What do you mean?

**Comment by ssborbis** [comment]
The changes that allow you to close the tab are not in a release. They're in the source code provided on this site. Specifically, in the development branch. Unless you download the source code and install as a temporary addon (Firefox) or unpacked extension ( Chromium ), you won't be able to use the closeTab function

**Comment by minawaheed9697** [comment]
> The changes that allow you to close the tab are not in a release. They're in the source code provided on this site. Specifically, in the development branch. Unless you download the source code and install as a temporary addon (Firefox) or unpacked extension ( Chromium ), you won't be able to use the closeTab function

Okay, what should I do, exactly??

**Comment by ssborbis** [comment]
What browser are you using?

**Comment by minawaheed9697** [comment]
Vivaldi

**Comment by ssborbis** [comment]
That's chromium-based, so download the source code [here](https://github.com/ssborbis/ContextSearch-web-ext.git) and extract the folder somewhere, then open `vivaldi://extensions/`, enable developer mode, Load unpacked -> browse the source folder to the directory with manifest.json and load it

**Comment by minawaheed9697** [comment]
Wow, it works. 
Can I modify the time after it the tab is closed?? 
And, when will this be added to new release??

**Comment by ssborbis** [comment]
> Can I modify the time after it the tab is closed??

Sure, change 1000 to whatever you want. It's in milliseconds so 1000 = 1 second

> And, when will this be added to new release??

Not sure, but it will be in the next release. In chromium, loaded unpacked extensions persist over browser sessions, so the source code you loaded will continue to work until the next release.

**Comment by minawaheed9697** [comment]
Okay, thank you so much for your help ❤. 
Hoping the new release will be soon.
