### ISSUE TITLE
Quick Menu Icon try input text moz-extension://a95f8cb0-4782-46f9-9e7e-18c10211d528/icons/logo_notext.svg

### ISSUE THREAD

**Issue by DandyClubs** [ssborbis/ContextSearch-web-ext#453]
https://i.imgur.com/xdkLTKm.jpeg

use Quick Menu Icon 

select input text

click icon

always search moz-extension://a95f8cb0-4782-46f9-9e7e-18c10211d528/icons/logo_notext.svg

**Comment by ssborbis** [comment]
Can you zip and post your config here? I can't get that bug.

**Comment by DandyClubs** [comment]
only firefox bug

 Enable on images

moz-extension://.... /icons/logo_notext.svg


not check  Enable on images

empty 

edge  browser is ok


https://www.upload.ee/files/13845759/ContextSearchOptions_2022-01-31_135629.json.html

**Comment by ssborbis** [comment]
I can't reproduce.  It seems like something is happening to the text selection.

Could you please try this? Select a large amount of text, enough that you are able to see some of the selection when you open the menu. Then, click the icon to open. Is the text still selected, or does it de-select?

**Comment by ssborbis** [comment]
Notice how the text is de-selected? That doesn't happen for me. 

It sounds similar to #443 

For some reason,  mouse actions are causing the text to be deselected. That is causing the problems with CS, but I don't know what is causing the de-selection.

**Comment by DandyClubs** [comment]
edge and firefox always de-selection when input text selected

but edge is work.

i try firefox create new profile and only install Context Search  add-on 

but is not work.

**Comment by ssborbis** [comment]
I've tested on Chromium, Firefox, Vivaldi, Waterfox, Edge, and my text is NEVER de-selected by simply clicking the icon.

I don't know why yours would be. It must be an OS issue.

**Comment by DandyClubs** [comment]
S3.Translator is work.

https://youtu.be/3c1KvfeSNI0

my os windows 10 21H2

**Comment by ssborbis** [comment]
I assume that addon isn't clearing the search term "cache" on de-select the way this addon does ( necessary for some functions to work properly ) I can look to make a workaround for the issue and add an advanced option to enable, but it will most likely cause issues elsewhere. My question is, what is causing the text to deselect. Another addon? An app?

**Comment by DandyClubs** [comment]
i already try firefox create new profile only install Context Search add-on

same error.

i use ESET INTERNET SECURITY, Adguard for Windows, CopyQ

**Comment by ssborbis** [comment]
Another user had a similar issue. The text was deselected even without this addon installed on a new profile. There's something else going on, maybe at the OS level. I just don't know, but I'll work on a fix. I'll let you know what I have something worth testing. Unfortunately, I can't test the fix myself.

**Comment by ssborbis** [comment]
Could you try the latest push in the development branch? I might have a fix for you.

https://github.com/ssborbis/ContextSearch-web-ext/archive/refs/heads/development.zip

**Comment by ssborbis** [comment]
Was this issue fixed when you tested the icon size in the other thread?
