### ISSUE TITLE
[FR] Context Search even in PDF.

### ISSUE THREAD

**Issue by boromyr** [ssborbis/ContextSearch-web-ext#455]
It would be a really pro feature to be able to use CT in PDF files as well. The operation of the extension would remain entirely the same as it is now, but it would be possible to call the search bar and pop-up menu in PDF files, online or offline.

**Comment by ssborbis** [comment]
Do you mean the in-browser pdf preview? The preview viewer isn't like a web page; there's no DOM. Because of that, there's no way to make use of the quick menu, find bar, side bar, page tiles, etc. 

The context menu should still work though. I just tested on a generic PDF, and it seems ok.

**Comment by boromyr** [comment]
Both preview and local files. I understand though, thank you!

**Comment by ssborbis** [comment]
No prob. Yeah, sorry, there's not much else I can do unless something changes with the API.
