### ISSUE TITLE
fix: missing settings in options quickMenuPreventPageClicks, quickMenuDeselectTextOnSearch

### ISSUE THREAD

**Issue by bottleblue** [ssborbis/ContextSearch-web-ext#457]
Where can I find these options? It was listed in 1.34. changelog.

**Comment by ssborbis** [comment]
You'll need to use the manual editor

![manual](https://user-images.githubusercontent.com/24310997/152811087-ea8c412e-4be3-4ab7-988b-b4fd2fedadd5.jpg)

**Comment by ssborbis** [comment]
> What does quickMenuPreventPageClicks do exactly?

Some people click somewhere on the page to close the quick menu. This setting prevents links from opening if you happen to click on one with the intention of closing the qm.

**Comment by bottleblue** [comment]
Ah that's useful. I'm gonna use that also thanks!
