### ISSUE TITLE
Install to Firefox one-click search engine does no longer work

### ISSUE THREAD

**Issue by jed84** [ssborbis/ContextSearch-web-ext#460]
Is it still possible to instal to firefox one-click search engine?

Currently, nothing is happening when I click on the "+":
![obraz](https://user-images.githubusercontent.com/47121522/154824851-630521bb-4aa9-4b45-80b1-f5cd8d9380fe.png)

Firefox 97.0.1
Context Search 1.34.4

**Comment by ssborbis** [comment]
The function to programmatically install those engines was removed several FF versions ago. Clicking that (+) should add the option to the engine to the Firefox search bar. From there, you can actually add the engine.

You should have seen this image pop up to notify you of the changes. Did you get one and check the "don't show again" box?

![add](https://user-images.githubusercontent.com/24310997/154825533-ba7dbbe8-1d36-4930-b5f0-faf463ebe0e6.jpg)

**Comment by jed84** [comment]
I don't remember checking the "don't show again" box, but it's possible. Is there a way to restore it?

**Comment by jed84** [comment]
So if the engine does not appear within the firefox search bar (there is no "+" icon), it's no longer possible to add it?

**Comment by ssborbis** [comment]
You don't need the notification to add engines. 

1. Click the 'Add to Firefox Engines' button in CS options.
2. Click the magnifying glass in the Firefox search bar ( should have a green circle with a + now )
3. Click the last icon in the list with the green circle with + ( hover over to see title.. should be the one you want )

**Comment by ssborbis** [comment]
I just tested. It's working for me.
![Peek 2022-02-19 20-18](https://user-images.githubusercontent.com/24310997/154825832-50afd6f9-e839-40e2-8d99-fe81890c4501.gif)

**Comment by jed84** [comment]
Thank you so much for explaining this - it's working! ^^
I am sorry for the false alarm.

**Comment by ssborbis** [comment]
No prob. Glad it's still working. I haven't tested that function in a long time.
