### ISSUE TITLE
Multi-search not available (version 1.35)

### ISSUE THREAD

**Issue by DenB10** [ssborbis/ContextSearch-web-ext#466]
Hi,
Creating a multi-search seems not to work anymore in the search engine manager as the context menu entry is grayed out.
Is it a bug or a bad configuration on my side?

**Comment by ssborbis** [comment]
Thanks. I accidentally added multisearch to the no-no list when multiple rows are selected. Patch is in the repo. I'll drop a new release soon. I've got your i18n patch ready to go too.

**Comment by ssborbis** [comment]
v1.36 is live
