### ISSUE TITLE
Messenger app is not connected

### ISSUE THREAD

**Issue by maggotb** [ssborbis/ContextSearch-web-ext#469]
Hello,

I installed the native app with install.py, the folder is created in Roaming, but I get "Messenger app is not connected".

I'm on the latest Firefox version. is there any way to fix this ? thanks in advance

**Comment by ssborbis** [comment]
Lets check a few things.

What version of CS are you on? Are you using a temporary install?

What version of the install.py did you use? ( if you took it straight from the github source on the master branch, it should be the latest )

What version of Python do you have? Did the install.py run via the proper version ( 3+ ) if you have both v2 and v3 installed?

Did you try running it from the command line to see if any errors came up? You can always re-run it.

What do the contents of ../Roaming/ContextSerach-webext look like? It should contain:
```
ContextSearch.bat
ContextSearch.py
[ separate folders for each browser ]
```

If you edit ContextSearch.bat, what are the contents? Anything like
```
@echo off
"C:\Users\[your username]\AppData\Local\Programs\Python\Python310\python.exe" -u ContextSearch.py
```
If you go into the browser-specific subfolder ( Firefox ), is there a `contextsearch_webext.json` file? What are the contents?

**Comment by maggotb** [comment]
> What version of CS are you on?

1.36, I don't know what a temporary install is, it's the "regular" version

> What version of the install.py did you use? ( if you took it straight from the github source on the master branch, it should be the latest )

From the github yes

> What version of Python do you have? Did the install.py run via the proper version ( 3+ ) if you have both v2 and v3 installed?

3.8.3 (because Windows 7), I only have this one installed, I never used python before this actually

> Did you try running it from the command line to see if any errors came up? You can always re-run it.

It says the operation completed successfully

The folder in roaming is as you said

bat is like this

```
@echo off
"C:\Users\username\AppData\Local\Programs\Python\Python38-32\python.exe" -u ContextSearch.py
```
the json file contains this

```
{
    "name": "contextsearch_webext",
    "description": "Launches external application",
    "type": "stdio",
    "allowed_extensions": [
        "{5dd73bb9-e728-4d1e-990b-c77d8e03670f}"
    ],
    "path": "C:\\Users\\username\\AppData\\Roaming\\ContextSearch-webext\\ContextSearch.bat"
}

```

**Comment by ssborbis** [comment]
Everything seems right. Are there any errors in the console on the options page? Anything else not working correctly?

Did you get the popup asking about allowing the NativeApp permission? Can you double-check that the permission was granted? about:addons -> this addon -> Permissions tab, check `Exchange messages with programs other than Firefox `

**Comment by ssborbis** [comment]
The only other thing I can think of is that your system requires the global registry keys. You can try this install.py I'm attaching. You'll need to run it from an administrative prompt

[install.py.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/8188950/install.py.zip)
.

**Comment by maggotb** [comment]
> Everything seems right. Are there any errors in the console on the options page? Anything else not working correctly?

I don't see the console, how do I enable it ?  I didn't have any other problems

> Did you get the popup asking about allowing the NativeApp permission? Can you double-check that the permission was granted? about:addons -> this addon -> Permissions tab, check `Exchange messages with programs other than Firefox `

yes to both

I tried installing the install.py you linked I get this [image](https://i2.paste.pics/56f3f813e8431cc98fbed653b8d6a956.png?trs=61bfdc54aaf424fd926c998a90d7b49630eb674926a7fd98302bb925629b67b1)

**Comment by ssborbis** [comment]
> I don't see the console, how do I enable it ? I didn't have any other problems

In FF, it's usually Ctrl+Shift+K

> I tried installing the install.py you linked I get this [image](https://i2.paste.pics/56f3f813e8431cc98fbed653b8d6a956.png?trs=61bfdc54aaf424fd926c998a90d7b49630eb674926a7fd98302bb925629b67b1)

Sorry, had a typo. Try this one
[install.py.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/8189049/install.py.zip)

**Comment by maggotb** [comment]
Nothing happens when I press Ctrl+Shift+K

Operation completed successfully with the install.py, still "Messenger app is not connected"

**Comment by ssborbis** [comment]
> Nothing happens when I press Ctrl+Shift+K

That's odd. What about Ctrl+Shift+i , or Menu -> More Tools -> Web Developer Tools

If you can get the console open, we can narrow down the problem.

From the console, opened from CS options
enter 
```
 browser.runtime.sendNativeMessage;
```
and post the output

Then try - 
```
browser.runtime.sendNativeMessage("contextsearch_webext",{verify:true}).then(r => console.log(r));
```

**Comment by ssborbis** [comment]
Another thing to check is the .bat file

Open a command prompt and navigate to C:\Users\username\\AppData\Roaming\ContextSearch-webext\

Then run ContextSearch.bat

It should idle until you type something and press enter. Then it should fail with some error about get_message(). I just want to be sure it at least runs.

**Comment by maggotb** [comment]
[Like this ?](https://i.imgur.com/t8GIkVM.png)

as for ContextSearch.bat, it says "can't find path" (in my native language), odd

**Comment by ssborbis** [comment]
Can't find path... hmm...

Can you verify the location of your python3 binary? Is it actually at `C:\Users\username\AppData\Local\Programs\Python\Python38-32\python.exe`?

Just an fyi, you can drag & drop images to the comments if you want to bypass imgur or whatever. At least I can, but maybe it's a git owner thing,

**Comment by ssborbis** [comment]
Just a quick sanity check, you are replacing your actual user name with *username* when you reference the paths, such as `C:\Users\username\AppData\Local\Programs\Python\Python38-32\python.exe` for privacy, correct? I assume so, but I need to check everything.

**Comment by ssborbis** [comment]
Maybe do this and post the output

Open command prompt
```
cd C:\Users\username\AppData\Roaming\ContextSearch-webext\
dir /b
ContextSearch.bat
```

If ContextSearch.bat actually runs, just press enter a few times to terminate it.

**Comment by maggotb** [comment]
> Can you verify the location of your python3 binary? Is it actually at `C:\Users\username\AppData\Local\Programs\Python\Python38-32\python.exe`?

It is

> Just a quick sanity check, you are replacing your actual user name with _username_ when you reference the paths in this thread, such as `C:\Users\username\AppData\Local\Programs\Python\Python38-32\python.exe` for privacy, correct? I assume so, but I need to check everything.

Yes I did

Here is the output

![output](https://user-images.githubusercontent.com/62154223/156883019-5f053243-4da5-401f-9c63-015191eac823.png)

**Comment by ssborbis** [comment]
Do you have any special characters in your name that is causing problems? ( non a-z )

**Comment by maggotb** [comment]
There"s a "ï" in my name, I tried opening another file (jpg) from the folder and it opened it though

**Comment by ssborbis** [comment]
I think that's the issue. Batch files really don't like special characters.

Ok, try this.

`echo  C:\Users\username\AppData\Local\Programs\Python\Python38-32\python.exe > path.txt`

Edit path.exe with notepad. Copy the path you see and replace the path in the batch file with what you copied.

**Comment by ssborbis** [comment]
So we're on the same page, when I do the commands above, `ï` is replaced with `‹`

**Comment by maggotb** [comment]
> echo C:\Users\username\AppData\Local\Programs\Python\Python38-32\python.exe > path.txt

Nothing happens when I do this, it just goes back to C:\Users\username in next line, path.txt isn't created in python folder

**Comment by ssborbis** [comment]
path.txt should be created in whatever folder you're currently in

**Comment by ssborbis** [comment]
An alternative is to add the python.exe folder to the windows path, and then simply call python.exe from the batch file

https://datatofish.com/add-python-to-windows-path/

if you do that, change the ContextSearch.bat file to read

```
@echo off
\python.exe -u ContextSearch.py
```

**Comment by maggotb** [comment]
> Edit path.txt with notepad. Copy the path you see and replace the path in the batch file with what you copied.

Well it works now (!) thanks for the thorough help

**Comment by ssborbis** [comment]
Glad to hear you got it working. I'll see if there's anything that can be done do the install.py to work around that issue.
