### ISSUE TITLE
When search via context menu is disabled, then custom search field doesn't appear

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#474]
If you disable the context menu search, then the entry to add a custom search when right-clicking on a INPUT field doesn't appear any more, althought it's activated in the settings. This started to happen only after some recent updates. Would love to have the old behavior back!

**Comment by ssborbis** [comment]
Easy fix. Changes in the repo / next release

**Comment by ssborbis** [comment]
1.39 going up. Let me know if that fixed it

**Comment by sojusnik** [comment]
Thanks for the fix!
