### ISSUE TITLE
I can't modify the templates

### ISSUE THREAD

**Issue by Saectar** [ssborbis/ContextSearch-web-ext#476]
I had originally added a couple of sites using the `{selectdomain}` template; later I wanted to change them to `{searchTerms}`; however, when I display the ContextSearch web-ext menu by clicking the add-on icon in Mozilla Firefox, the sites still have the `{selectdomain}` template.

It should be noted that if I use the opposite click on the page, the sites are shown to me with the correct template; this problem is only present when pulling down the menu from the add-on icon.

![01](https://user-images.githubusercontent.com/4337724/161514709-dd1d6d54-9400-467c-b56f-d35d67707093.png)
![02](https://user-images.githubusercontent.com/4337724/161514712-8859f490-a28e-4e9e-81b6-e0369192a01d.png)
![03](https://user-images.githubusercontent.com/4337724/161514715-ba01f439-972d-48e7-8ca2-9cb87e483630.png)
![04](https://user-images.githubusercontent.com/4337724/161514719-d009c9bc-7f43-44ab-ab93-e7ab135d834d.png)

Thanks for the answers.

**Comment by ssborbis** [comment]
I think I know what's going on. Can you export & zip your config and drop it here? I can use it to hopefully make a fix and repair it for you.

**Comment by ssborbis** [comment]
Actually, you can probably repair it yourself from the console.

1. Open the CS options page
2. Open the console ( Ctrl+Shift+K )
3.  Enter the following commands

```js
findNodes(userOptions.nodeTree, n => n.type === "siteSearchFolder").forEach( n => n.type = "searchEngine");
saveOptions();
```
Basically, this command recasts any engines that were branded as type "siteSearchFolder" back to the generic type "searchEngine". I think the problem occurs when engines are re-arranged via the tiled menus. This should solve your issue, at least until you rearrange again. I have a fix (hopefully) ready for the next release.

**Comment by Saectar** [comment]
It works! Thanks.

**Comment by ssborbis** [comment]
1.39 going up now. That should fix this issue from showing up again. Re-open if you have any further issues.
