### ISSUE TITLE
Is there a maximum limit to the number of search engines?

### ISSUE THREAD

**Issue by lshilshi** [ssborbis/ContextSearch-web-ext#477]
Is there a maximum limit to the number of search engines?
Some engines hide automatically sometimes.

**Comment by ssborbis** [comment]
There is no limit coded into this addon. There may, however, be limits elsewhere. I recently added the permission for "Unlimited Storage" to hopefully avoid a size limit to the preferences file.

Where exactly are you seeing the limit? The manager in CS options? Or are engines not being displayed in one of the menus?

**Comment by lshilshi** [comment]
> The manager in CS options

The manager in CS options.
And lost the folder sort.

I didn't notice whether the engine was showing up in the context.

**Comment by ssborbis** [comment]
Under some circumstances, especially using Firefox with a mismatched search engine list between this addon and the Firefox search bar engines ( one-click search engines ), some deleted engines may reappear at the bottom of the list as hidden engines. Also, if there's a glitch when moving engines between folders, there is fallback code that appends the lost engines to the end of the list. That may have been what happened to you, but I can't be sure without seeing a before/after list.
