### ISSUE TITLE
Many engines fail in the latest version of chrome

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#478]
All JavaScript and some post requests have failed in the Chrome 100, which is fine in the old version of chrome.

**Comment by ssborbis** [comment]
I've only tested running some scripts on google.com, but I am seeing issues. It's like chrome is now prepending "www" to hostnames in the location, but not in the URL bar. And because that no longer matches the template url ( in my case google.com != www.google.com ), the script doesn't know to run.

Do you have another website / template I can look at to see if that's the issue? Like I said, I've only tested using `http://google.com` as a template

**Comment by ssborbis** [comment]
I've made a push to the development branch that *may* fix things. If you can, load it into your chrome as an unpacked extension and test it out.

https://github.com/ssborbis/ContextSearch-web-ext/archive/refs/heads/development.zip

**Comment by yejinson** [comment]
> I've made a push to the development branch that _may_ fix things. If you can, load it into your chrome as an unpacked extension and test it out.
> 
> https://github.com/ssborbis/ContextSearch-web-ext/archive/refs/heads/development.zip

Great, it's been fixed, thanks.

**Comment by ssborbis** [comment]
new package (1.39) going up to chromestore & AMO. Thanks for the heads-up

**Comment by yejinson** [comment]
> new package (1.39) going up to chromestore & AMO. Thanks for the heads-up

It turned out to be on the store, which is convenient for downloading, but I still prefer to download the latest version here, haha, you are welcome, thank you for your efforts.

**Comment by yejinson** [comment]
> new package (1.39) going up to chromestore & AMO. Thanks for the heads-up

It stopped working after Chrome update Yesterday, I have tried the latest dev version 2 hours ago, and it doesn't work, please fix it again.

**Comment by ssborbis** [comment]
When is it not working? When you perform a normal search or when you use the "Test" button from the search engine edit modal?

The "Test" button may have an issue, but using a search engine normally seems ok to me.

**Comment by ssborbis** [comment]
fix for test button in development repo

**Comment by yejinson** [comment]
> When is it not working? When you perform a normal search or when you use the "Test" button from the search engine edit modal?
> 
> The "Test" button may have an issue, but using a search engine normally seems ok to me.
It is a normal search, not a test. I've reinstalled the extension and it works again. It's weird. Anyway, there is no problem. If there is any problem, I will give you feedback. Thank you.
