### ISSUE TITLE
allow both ways to open the quick menu, mouse and keyboard (not exclusive)

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#48]
the way I want to open the menu usually depends on the way I select the text.

**Comment by hg42** [comment]
no hurry, please don't feel pushed

**Comment by ssborbis** [comment]
repo updated with 1.5.8

Redid Opeing & Closing section with mixed opening methods
Added hotkey option to open quick menu without selecting text (fixed key for now Ctrl-Q)
Added search bar options

**Comment by ssborbis** [comment]
Bug with mouse hold / mouse click not triggering focus. Working on it

**Comment by hg42** [comment]
thanks for implementing this

Though I found two problems:
* ctrl-q is "Quit" on Firefox/Linux/en and seems to have priority (quick menu never opens, but quit)
* I'm not sure about the arrow keys. They cannot be used inside the text field.
  My initial idea was more like:
  * focus on text field:
    * left/right as usual
    * down jumps to search engines
    * (eventually: up moves to selected text on page)
    * tab moves to search engines
  * focus on search engines:
    * arrows move around
    * top row, arrow up: moves to text field
    * first engine: shift+tab moves to text field
    * last engine: tab moves to text field

I admit, the current behavior works, but with exceptions:
* there is no way to move inside the text field using the keyboard
* it's kind of unexpected that there is a cursor in the text field and a selected engine at the same time (looks like two focused elements)

**Comment by ssborbis** [comment]
Ah shit, I better change the ctrl-q soon. Don't need to be trolling users.

I'll update arrow key behavior.

**Comment by ssborbis** [comment]
Repo updated with new search bar key behavior, changed hotkey to ctrl-alt-Q until i get an option set up

**Comment by hg42** [comment]
> I'll update arrow key behavior

actually, I said:
> I'm not sure about the arrow keys

for a reason, but didn't know which.

Now I think, you implemented the current selection behavior, because when pressing Enter, the first engine will be used and I think that's why you selected it as default. May be it could be selected by a disabled selection color and by the normal selection color when it gets the focus?

Btw. the selection color is very light on my monitors, nearly invisible for me. Do you use the color from the theme?

**Comment by ssborbis** [comment]
It's definitely subtle. Changing border color might help.

Fixed the listener for ENTER

**Comment by ssborbis** [comment]
I added a darker inset box-shadow to make the selection more apparent. 

> Now I think, you implemented the current selection behavior, because when pressing Enter, the first engine will be used and I think that's why you selected it as default. May be it could be selected by a disabled selection color and by the normal selection color when it gets the focus?

I can do something to highlight the default engine when the search bar is focused. Not sure what would look best. I'll try a few things

**Comment by hg42** [comment]
1.5.9 works fairly well now...it's a big improvement and very useful

some remaining items:
* the inset shadow is not my favorite design, but it's a good compromise and I don't know a better one
* I still think the focus should be on the text box, when opening the quick menu (all text selected), at least when opened by keyboard. I guess everyone (>= me :-) ) expects to type a search term after `ctrl-alt-q` or the other keyboard key or to alter the text, if something was selected without first pressing `tab`. If I remember correctly, the other issue wanting the focus on the text on the page would also be solved by pre-selecting the search field?
* would it be possible to also move through the tools buttons by arrows and `tab` (but still starting at the first engine)

**Comment by ssborbis** [comment]
>EDIT2: the default engine is like a selection in a non focused element, this is usually selected gray instead of colored (see the selected text on the page if the search box has the focus)

Ah, I see what you mean. I tried highlighting it with the box-shadow used when selecting engines via keyboard but it does look odd when also focused on the search bar. My only concern with graying the tile would be users perceiving that as meaning 'disabled'. To a user who opens the quick menu and intends to use the mouse to select a search engine tile who also uses auto-focus will see the first engine as 'disabled'. That may be confusing.

**Comment by hg42** [comment]
> graying the tile

the selection indicator would be grayed, not the tile.

for text it usually looks like a selection (e.g. light text on dark background), but the background is gray instead of the selection color. The theme usually has a setting for this (something like "inactive selection").
If you select a tile with a colored shadow, the shadow would be gray or perhaps with a lighter color. The icon would still be fully colored.

**Comment by hg42** [comment]
the theme api doesn't contain an inactive selection color for anything:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme
It's either focused or not.

I think that's why the ui interface of the searchbox popup is a bit  weird (it's basically the same as the quick menu).

**Comment by hg42** [comment]
The quickmenu is very similar to the urlbar popup (more than the searchbox popup).
So it could probably look and behave similar. E.g. selection would be indicated by the background. It seems to use the popup focus color (`popup_highlight` in the theme api).

If you type a text in the urlbar, it will be searched with the first engine, but the engine isn't marked as selected.
They obviously have the same problem and try to indicate which search engine would be used by adding a new menu item `xyz -- Search with Google`.

Quickmenu does a better job for the arrow keys (moving also up and down, real arrow navigation makes much more sense here, because there can be more rows by limiting columns).

**Comment by ssborbis** [comment]
Ok, I see. Using the grey indicator like the One-Click Toolbar. Makes sense.

I completely forgot about themes. Are you using a custom theme and seeing a styling clash?

**Comment by ssborbis** [comment]
I tried using the same indicator gray as the One-Click toolbar

`#e0e0e0`

It's even lighter than my original. 

`#ccdbe8`

FF toolbar can get away with a lighter contrast because it has more background area relative to icon size 

The out-of-focus background color for text is 

`#b0b0b0`

That might be good to use for indicating the default engine when focused on the search bar since that's the standard style for 'selected but out of focus'

The standard selection color is

`#0078d7`

I'm not a fan of the darker selection color but it does keep it inline with the default style. 

I could get the current theme style for `popup_highlight ` and use that but it would require users grant the Theme permission
