### ISSUE TITLE
option to disable recent icon (clock icon) next to main icon of recently used search engine.

### ISSUE THREAD

**Issue by rezad1393** [ssborbis/ContextSearch-web-ext#480]
can an option to disable recent icon (clock icon) next to main icon of recently used search engine be added.
I now only use recent list and a folder at the bottom than contain my search engines.
so all the items that are shown when I right click a selected word are recent search engines and so I don't need to be reminded of that and the clock icon next to the icon of websites is redundant.
can this be hidden?
when I use the option   "Show as folder" for recent, they don't have that issue, but I don't want to use a folder for them.

**Comment by ssborbis** [comment]
Not currently, but I can add it

**Comment by ssborbis** [comment]
update in the development repo if you're sideloading

**Comment by rezad1393** [comment]
> sideloading

"I too like to live dangerously" NOT.

I no longer have the patience for playing with git level software.
thank you for the update.
should I close this or wait for stable release to close then?

**Comment by ssborbis** [comment]
Close it when you have a chance to test. If you're on Firefox, I can get you a beta

**Comment by rezad1393** [comment]
I will wait for stable release.

**Comment by ssborbis** [comment]
1.41.1 is out. This should be fixed now.

CS Options -> Advanced -> Manual Edit -> `contextMenuShowRecentlyUsedIcon: false`

**Comment by rediffusion** [comment]
> contextMenuShowRecentlyUsedIcon

 Can't find where is it? Maybe show me the screen, TYSM!

**Comment by rezad1393** [comment]
> @ssborbis
> 
> > contextMenuShowRecentlyUsedIcon
> 
> Can't find where is it? Maybe show me the screen, TYSM!

there isn't on screen.
you need to add that value in the Manual Edit ,
the Manual Edit is the button at the top right when you are in the advanced tab in setting of addon.

**Comment by ssborbis** [comment]
@rediffusion 
![recentlyusedicon](https://user-images.githubusercontent.com/24310997/182036901-7459bd85-36b3-427b-909b-06e1a12c6dbd.gif)
