### ISSUE TITLE
Wanted: Kept  the seprator and hide empty folder.

### ISSUE THREAD

**Issue by lshilshi** [ssborbis/ContextSearch-web-ext#481]
1.Hide empty search engineer folders in all context menus.
![image](https://user-images.githubusercontent.com/36767310/163718150-58e10bdb-c5fc-49ae-90bc-edfce158f6e7.png)

2.Keep the separator in the context menu of the selected search.
Also in the context  menu of Page mode, the separator is kept.
![image](https://user-images.githubusercontent.com/36767310/163718299-8fb7f217-3330-4d66-8729-d83d2fbcf117.png)

**Comment by ssborbis** [comment]
I'm guessing your "empty" folder contains separators? I have a fix.

> Keep the separator in the context menu of the selected search.
Also in the context menu of Page mode, the separator is kept.

This appears to be a chromium-based issue. I think I have a workaround.

Updates are in the development repo for testing

**Comment by lshilshi** [comment]
> I'm guessing your "empty" folder contains separators? I have a fix.
> 
> > Keep the separator in the context menu of the selected search.
> > Also in the context menu of Page mode, the separator is kept.
> 
> This appears to be a chromium-based issue. I think I have a workaround.
> 
> Updates are in the development repo for testing

yes,It  had "empty" folder contains separators.

**Comment by ssborbis** [comment]
v1.41.1 is out. If that solved your issues, go ahead and close this out. If not, let me know and I'll see what I can do.

**Comment by lshilshi** [comment]
> v1.41.1 is out. If that solved your issues, go ahead and close this out. If not, let me know and I'll see what I can do.

yes,It's good now!
