### ISSUE TITLE
Quick menu opens over youtube window

### ISSUE THREAD

**Issue by bottleblue** [ssborbis/ContextSearch-web-ext#482]
If the mouse cursor is over the youtube window and I hold right mouse button the quick menu opens even though nothing is highlighted. This is particularly annoying when tab scrolling with right mouse button and mouse wheel from another tab back to the youtube tab. Is there any way to disable this behavior? 

Using Firefox 99.01

**Comment by ssborbis** [comment]
Images, links, videos, etc are considered content that will open the quick menu if one of the opening methods is used.

If you don't use the qm on links or images, you can disable those checkboxes ( or just if you know which is causing issues ) under CS Options -> Quick Menu 

If you simply don't want the qm to ever open on youtube.com, you can add youtube.com to the blocklist under CS options -> General -> Blocklist, or enable the Blocklist tool in the Quick menu and click that to add the current domain to the list.

**Comment by bottleblue** [comment]
I have the Quick Menu options "Enable on Links" and "Enable on Images" already unchecked. I don't want to block all of youtube because of course there might be text I want to search.

**Comment by ssborbis** [comment]
The checkboxes only work on the preview videos I guess.

I'm assuming you're using the hold to open method? The simplest thing would be to add an option to cancel opening on mousewheel events.

**Comment by bottleblue** [comment]
Yea I'm using hold to open. 
That probably would be the simplest thing. Or maybe disable searching on video window since it doesn't seem to do anything useful

**Comment by ssborbis** [comment]
> Or maybe disable searching on video window since it doesn't seem to do anything useful

I might be able to add `video` alongside the checkboxes `links` and `images`. As for useful, since adding the app launcher, you can do any number of things with a video link. Even a blob might be useful, combined with some javascript.

**Comment by bottleblue** [comment]
I guess I should say it doesn't do anything useful for me hehe.

**Comment by ssborbis** [comment]
Changes in the development branch.

Hidden advanced option `quickMenuCancelOnMousewheel`. You'll need to use the manual edit button to change the setting ( top-right under the Advanced menu )

**Comment by ssborbis** [comment]
I should probably set the default to on, because I can't think of any reason why anyone would want the qm to open while using the mousewheel.

**Comment by bottleblue** [comment]
Great how do I download from the development branch?

**Comment by ssborbis** [comment]
I'm signing a beta now. I'll link you in a sec

**Comment by ssborbis** [comment]
https://github.com/ssborbis/ContextSearch-web-ext/releases/download/v1.40b1/contextsearch_web_ext-1.40b1-an+fx.xpi

**Comment by ssborbis** [comment]
You shouldn't have to change any settings. `quickMenuCancelOnMousewheel` is on by default

**Comment by bottleblue** [comment]
Hmm it doesn't work. I still get quick menu popups

**Comment by ssborbis** [comment]
Are you using an extension to do the tab scrolling?

**Comment by bottleblue** [comment]
Yea it's the Gesturefy extension.

Gesturefy options > Extras > Wheel Gesture - On,  Wheel Gesture mouse button - Right, Wheel Up - Focus Left Tab, Wheel Down - Focus Right Tab

**Comment by ssborbis** [comment]
That extension is probably capturing the scroll event. Can you try this? Open a youtube video without other tabs open, and try to long-click to open the qm. Then try to long-click, but also scroll the wheel. Does it still open?

**Comment by bottleblue** [comment]
Both long-clicking and long-clicking and wheel scrolling open the menu.

**Comment by ssborbis** [comment]
Yeah, that's a problem. I'll have to get back to you on this one.

**Comment by bottleblue** [comment]
K thx for looking into it

**Comment by ssborbis** [comment]
I have a workaround.

I added an option to close the qm if the tab changes. That should get you the results you want.

**Comment by bottleblue** [comment]
Great I'll try it and let you know if it works. Thx!

**Comment by ssborbis** [comment]
https://github.com/ssborbis/ContextSearch-web-ext/releases/download/v1.40b2/contextsearch_web_ext-1.40b2-an+fx.xpi

Audio / video options added alongside links / images
CS Options -> Advanced -> Manual edit button -> set `quickMenuCloseOnTabChange: true`

**Comment by bottleblue** [comment]
quickMenuCloseOnTabChange doesn't seem to do anything by itself. I still get the qm popup over youtube window.  Disabling audio/video option works though and does so whether or not I have quickMenuCloseOnTabChange enabled.

Something else I forgot to mention is that when text is highlighted (when I only want to copy the text) and I scroll to another tab and then back to the tab with the highlighted text it opens the quickmenu. Basically the same problem as the youtube window. It would be awesome if you could make an option to deselect text when scrolling to another tab.

**Comment by ssborbis** [comment]
> quickMenuCloseOnTabChange doesn't seem to do anything by itself

It should close the qm in the window you initially used hold right mouse + scroll to change tabs. It's working for me as intended.

1. open youtube and play a video
2. hold right-mouse + scroll to change tabs using Gesturefy

The qm would be triggered to open on the youtube page, but because I changed tabs, it's closed. 

Are you not seeing this behavior?

**Comment by bottleblue** [comment]
Ah I see. Yes if I keep the right mouse button held down and scroll tabs back and forth then it doesn't open the qm again. But if I scroll to the non-youtube tab and let go of the right mouse button then click right mouse button to scroll back to youtube window it still opens the qm. This isn't a problem though since you included the options to disable qm on audio/video. I have no need to search video windows using qm so it's fine.

**Comment by ssborbis** [comment]
I am seeing the qm open at times when it shouldn't using this workaround. I'll try a few things and see if I can't get more consistency.

**Comment by bottleblue** [comment]
ok but I consider the youtube problem solved b/c of the audio/video options so thank you for that. If you can also solve the text selection issue that would be amazing. (I hope I'm not being too nitpicky with my issues.)

**Comment by bottleblue** [comment]
I tested the latest beta build 1.40b3 and quickMenuCloseOnTabChange seems to be working properly. I haven't had any popup issues with youtube or with the highlighted text tab scroll. Looks good thanks!
