### ISSUE TITLE
Add a 6. option to Search Actions

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#483]
Hey there, 

I am using a firefox addon to open links in a new tab with a left double-click. It allows me full control, because I can open a link in the current tab (single left click), in a new tab in the foreground (double left click) and in a new tab in the background (middle click). (The right click of course is used for the context menu). This is all very convenient IMO. 

And I would wish to be able to use this in the ContextSearch menu in the same way. Unfortunately the left double-click is not available, so I chose the right click for opening a new tab in the foreground ... but its always confusing.

So this is a feature request. It would be wonderful IMO to have the left double-click as a 6. option in the Search Actions.

Do you think, this might be worthy?

Best greetings from Germany!

Thomas

**Comment by ssborbis** [comment]
Looking into it...

I'll let you know when I have something worth testing.

**Comment by ThomasSeeker** [comment]
Wow, this sounds promising! ... :-D

**Comment by ssborbis** [comment]
If you're on FF, I have a beta for testing. 
https://github.com/ssborbis/ContextSearch-web-ext/releases/download/v1.40b3/contextsearch_web_ext-1.40b3-an+fx.xpi

If chromium-based, grab the latest development repo code.

I'll have to walk you through setting up the double-click search action. There's no UI at the moment, but it's available to test.

Open CS Options -> Advanced -> Manual Edit button (top right) -> scroll down to `customSearchActions` and change it to the following:

```javascript
"customSearchActions": [
        {
            "event": "dblclick",
            "button": 0,
            "altKey": false,
            "ctrlKey": false,
            "metaKey": false,
            "shiftKey": false,
            "action": "openNewTab",
            "folder": false
        }
    ],
```

available options for the `action` are 
openCurrentTab,
openNewTab,
openBackgroundTab,
openNewWindow,
openNewIncognitoWindow,
openSideBarAction,
noAction

If you need help setting up for testing, let me know.

**Comment by ssborbis** [comment]
Oh, and if you have a double-click attached to an identical search action with a single-click, the single-click action will be on a 500ms delay. 

In other words, your single-left-click will have a slight delay before working. Double-click should execute immediately

**Comment by ThomasSeeker** [comment]
Oh, wow, ... thank you so much!
It works just wonderful!
No confusion anymore.

I wish all developers would care so good for their babies, like you do! :-)

**Comment by rediffusion** [comment]
@ssborbis 

 Maybe show some screencast for this:

```
"customSearchActions": [
        {
            "event": "dblclick",
            "button": 0,
            "altKey": false,
            "ctrlKey": false,
            "metaKey": false,
            "shiftKey": false,
            "action": "openNewTab",
            "folder": false
        }
    ],
```

Everything was added and preserved but didn’t understand how to use it?

**Comment by ThomasSeeker** [comment]
> Everything was added and preserved but didn’t understand how to use it?

This is for the very specific use-case, that you want to open your search result in a new tab in the foreground by a double-left-click.

**Comment by ssborbis** [comment]
@rediffusion 

Essentially, adding that object to the "customSearchActions" array will allow you to left-double-click on a tile/icon in the quick menu to perform a separate search action from whatever action you bound to single-left-click. In other words, if you have the left mouse button set to open search results in the current tab, performing a double-left-click will open them in a new tab, as denoted by `"action": "openNewTab"`. 

Sorry, still no UI for this, as it's quite untested.

**Comment by ssborbis** [comment]
UI for custom search actions has been added to CS Options -> Quick Menu -> Search Actions

Needs testing, but it's there in the dev branch. If it's not too buggy, it should be in the next release.


![Screenshot_2022-10-29_22-12-41](https://user-images.githubusercontent.com/24310997/198860909-b717fcc5-4c76-47c1-8b1d-8ca0f8b5c7f2.png)

**Comment by ThomasSeeker** [comment]
Ah, what a beautiful solution! :-)

I tested several different combinations and they all worked perfectly.

ssborbis, I very much like your style of enabling such a high degree of configurability! ... It tastes like freedom! :-)

Thank you!

**Comment by ThomasSeeker** [comment]
PS: 

In the case of a user fault, where 2 rules are contradicting each other ... would it maybe be better to choose the rule which was added manually over the one which is there by default with the setting "No Action"?

**Comment by ssborbis** [comment]
> In the case of a user fault, where 2 rules are contradicting each other ... would it maybe be better to choose the rule which was added manually over the one which is there by default with the setting "No Action"?

Do you have a use case where you **need** to override a preset with a custom setting? If so, that's not something I'd considered and I'd be interested so see what that is.

I admit I gave zero consideration to conflicting settings. Like you said, the defaults tend to take precedence, but I'm not even sure that's true 100% of the time. I may look into some solutions in the future, but for now I'll leave it to the user to manage duplicate settings since they don't seem to have any detrimental effects.

**Comment by ssborbis** [comment]
>  I just looked for ways things could go wrong, because you asked for testing the thing.

And I appreciate your thoroughness. I'll see about setting up some kind of notification for conflicting settings.

**Comment by ThomasSeeker** [comment]
> I'll see about setting up some kind of notification for conflicting settings.

Yes, this would probably be the best solution. But again: very very low priority IMO!

:-)

**Comment by ssborbis** [comment]
Dev branch has some conflict checks code to display a notification icon that should suffice. 

![image](https://user-images.githubusercontent.com/24310997/201185133-0b02b455-fbbe-4154-ac60-97a47c0f6109.png)

I think we can close this thread out now. Open a new issue for any other bugs you run into.

**Comment by ThomasSeeker** [comment]
Thank you very much ssborbis! 
:-)
