### ISSUE TITLE
How to change the width of the quick menu?

### ISSUE THREAD

**Issue by yejinson** [ssborbis/ContextSearch-web-ext#486]
Because the name of the folder is very short, the right side of the menu will appear empty, so I need to make the menu width smaller.

**Comment by ssborbis** [comment]
Can you post a screenshot?

**Comment by yejinson** [comment]
> Can you post a screenshot?
Like this, the right side is too wide, can I modify it in User Styles? I don't know the format.
<a href="https://sm.ms/image/nZhuqE4UG6IDXKO" target="_blank"><img src="https://s2.loli.net/2022/05/17/nZhuqE4UG6IDXKO.png" alt="quicker_fa3c01a5-e85f-49f6-8c49-34e1d20d4b13.png"></a>

**Comment by ssborbis** [comment]
It looks like you're using the list view vs the grid view.

You should be able to override with the following entry in CS Options -> General -> User Styles

```css
.tile.singleColumn {
	max-width:150px;
	min-width:150px;
}
```

**Comment by yejinson** [comment]
> It looks like you're using the list view vs the grid view.
> 
> You should be able to override with the following entry in CS Options -> General -> User Styles
> 
> ```css
> .tile.singleColumn {
> 	max-width:150px;
> 	min-width:150px;
> }
> ```
> 
> The default width is 300px

solved, thanks a lot.

**Comment by yejinson** [comment]
> It looks like you're using the list view vs the grid view.
> 
> You should be able to override with the following entry in CS Options -> General -> User Styles
> 
> ```css
> .tile.singleColumn {
> 	max-width:150px;
> 	min-width:150px;
> }
> ```
> 
> The default width is 300px

This method has been invalid for a long time, is there a new one?
