### ISSUE TITLE
How to use the Javascript-Driven Search Engines

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#488]
How to determine if a website uses  Javascript-Driven Search Engines and write a search code, is there a simple example?

**Comment by ssborbis** [comment]
> How to determine if a website uses Javascript-Driven Search Engines

If they don't add correctly from `Add to ContextSearch` and you can't find an engine at mycroftproject.com, it's a pretty good bet they're not GET or POST-based engines.

The example in the readme is pretty simple.

```javascript
let input = document.querySelector('input');
input.value = searchTerms;
input.dispatchEvent(new KeyboardEvent('keydown', {key:"Enter", keyCode:13, bubbles:true}));
input.dispatchEvent(new KeyboardEvent('keyup', {key:"Enter", keyCode:13, bubbles:true}));
```

Sometimes it's as simple as copying that to the "Post-Search Code" field.

Check the bottom posts in #67. Most have to do with hard-to-search sites. If you're still lost, post the website url and I'll walk you through it.

**Comment by 7peanuts** [comment]
Thank you very much, I'll try it.

**Comment by 7peanuts** [comment]
[http://www.duososo.com/site/movie/](url)
Could you help me write the search code for this page?
For a webpage with multiple search boxes like this, how to enter information into the specified search box.

**Comment by ssborbis** [comment]
That particular website appears to fill in all search boxes with the same search term?

Are you wanting to search all engines on that particular page? You could add those engines individually and search them all through this addon at once by putting them in a folder and doing a folder search.

Another way would be to fill in the main search box via the Post-Search script, and then have the script click on each submit button, which should spawn new tabs for each engine.

**Comment by 7peanuts** [comment]
> 
Thanks, I forgot about the Multi-Search.

[http://www.pictriev.com/](url)
This page has two buttons with the same name “span”, so how should the code?
Writing it like the following will select the first button.

`let input = document.querySelector('#urltext');
input.value = searchTerms;
document.querySelector('span').click();`

Some pages have the same seachbox, how should I choose?

**Comment by ssborbis** [comment]
You need to use more specific [CSS selectors](https://www.w3schools.com/cssref/css_selectors.asp)

The layout of that site is kinda messed up for me using English, but I think I see where the forms are.

![Screenshot_2022-05-30_09-53-08](https://user-images.githubusercontent.com/24310997/171017745-2b84f49d-de9d-4151-be0e-22ff669d31b4.png)

In this case, the best selectors are the id's. I think you want to be using the button vs the span. You can see the event is actually on the button, but it may bubble up and not matter.  

So you have a few ways of referencing that submit button or span

1. ```document.querySelector('#submit-url').click();```
2. ```document.querySelector('#submit-url > SPAN').click();```

I haven't tested, but I assume the first will work.

**Comment by 7peanuts** [comment]
Thank you very much. Both of them are work!

**Comment by 7peanuts** [comment]
I need your help, this webpage has a Visual Search button
[https://unsplash.com/](https://unsplash.com/)
![20220609105044](https://user-images.githubusercontent.com/82173614/172754053-5ca66189-8eba-45b1-8acd-fac2d546dac5.png)
I don't know how to choose which buttons to use.
``document.querySelector('#hzGh7 > [class="r7Rbd jpBZ0"]').click();``
``let input = document.querySelector('#visual-search-form-dropbox-input.ctM_F.gdt34');``
``input.value = searchTerms;``

**Comment by ssborbis** [comment]
try this:
```javascript
let input = document.querySelector('input[type="search"]');
input.value = searchTerms;
input.form.submit();

**Comment by ssborbis** [comment]
Oh, unless you're seeing a different site than I am, I was able to just right-click -> Add To Context Search on that engine. No script required.

**Comment by 7peanuts** [comment]
> Oh, unless you're seeing a different site than I am, I was able to just right-click -> Add To Context Search on that engine. No script required. ![Peek 2022-06-09 17-15](https://user-images.githubusercontent.com/24310997/172954306-15ead89a-57d7-4954-a669-a7b3d50dd067.gif) [ ](https://user-images.githubusercontent.com/24310997/172954306-15ead89a-57d7-4954-a669-a7b3d50dd067.gif) ![Peek 2022-06-09 17-15](https://user-images.githubusercontent.com/24310997/172954306-15ead89a-57d7-4954-a669-a7b3d50dd067.gif) [ ](https://user-images.githubusercontent.com/24310997/172954306-15ead89a-57d7-4954-a669-a7b3d50dd067.gif)

Not this `Search Unsplash` button, there is a `Visual search` button on the right side of the search box.

When you click it, you can paste an image or a URL to search, just like google reverse image search.

**Comment by ssborbis** [comment]
The form seems to need the URL to be pasted into the search. There appears to be some `paste` and `input` events required to trigger the search. I haven't teased out the exact functions, but I think that's what's going on.

**Comment by 7peanuts** [comment]
> The form seems to need the URL to be pasted into the search. There appears to be some `paste` and `input` events required to trigger the search. I haven't teased out the exact functions, but I think that's what's going on.

Yes, I tried to simulate the button click first and then input the text, but it didn't input the correct place.

**Comment by ssborbis** [comment]
I don't have a problem entering the url, but I can't trigger the search. This is what I have. Note that I'm wrapping everything in an async function so I can force a delay between the click and getting the input. This is because it takes a sec for the page to load the search form when you click the button:

```
(async() => {
  document.querySelector('#popover-visual-search-form-nav > BUTTON').click();
  await new Promise(r => setTimeout(r, 100));
  let input = document.querySelector('#visual-search-form-dropbox-input');
  input.focus();
  input.value = searchTerms;
})();
```

**Comment by 7peanuts** [comment]
It looks like a paste action is required to trigger the search, and I found that when I paste the URL to do a search,  this URL `https://unsplash.com/napi/search/by_image`  comes up. 
![20220611145630](https://user-images.githubusercontent.com/82173614/173177323-dd918664-126b-4c2d-9a68-f6c15ebe5add.png)

I don't use this site much, so that's it, thank you anyway. 😃

**Comment by 7peanuts** [comment]
This is a translation page, when I use the following script, it is not recognized.
[https://dict.cnki.net/index#](https://dict.cnki.net/index#)

````
(async() => {
  document.querySelector('textarea').click();
  let input = document.querySelector('textarea');
  input.focus();
  await new Promise(r => setTimeout(r, 100));
  input.value = searchTerms;
  document.querySelector('#app > BUTTON').click();
})();
````

**Comment by ssborbis** [comment]
I can't access https://dict.cnki.net/index# for some reason. I'll try again later.

**Comment by 7peanuts** [comment]
> This is a translation page, when I use the following script, it is not work.
>I wonder if this site can use script.
>
>https://dict.cnki.net/index
> 
I modified it, and now I can enter the text to the search box, but there is no result.

```js
(async() => {
  let input = document.querySelector('.trans-left-con > [name="translateArea"]');
  input.focus();
  await new Promise(r => setTimeout(r, 200));
  input.value = searchTerms;
  input.dispatchEvent(new KeyboardEvent('keypress', {keyCode:13, key:'Enter'}));
})();
```

**Comment by ssborbis** [comment]
Sorry, I can't load that site. It may be a regional thing.

**Comment by 7peanuts** [comment]
> Sorry, I can't load that site. It may be a regional thing.
> 
> I can tell you some pages watch for different events on the input boxes before they'll submit the search. You might want to open the web developer tools and inspect the input element. See what events are attached ![events](https://user-images.githubusercontent.com/24310997/177403199-e531eed4-1d1a-4600-8508-f6dc0ae7f910.jpg) .

Thanks, I'll try.

**Comment by ssborbis** [comment]
I'd try triggering change and input events before submitting

```javascript
input.dispatchEvent(new Event("input"));
input.dispatchEvent(new Event("change"));
```

**Comment by ssborbis** [comment]
I managed to load the site on virtual pc

I assume you just want the results to show up in the adjacent translation textarea?

```javascript
(async() => {
  let input = document.querySelector('.trans-left-con > [name="translateArea"]');
  input.focus();
  await new Promise(r => setTimeout(r, 200));
  input.value = " 用户帮助";
  input.dispatchEvent(new Event("input"));
  input.dispatchEvent(new Event("change"));
})();
```

**Comment by 7peanuts** [comment]
> I managed to load the site on virtual pc
> 
> I assume you just want the results to show up in the adjacent translation textarea?
> 

God, this is perfect. Love you, man, I'm truly grateful. You made a superb search tool!

Also, I'd like to ask if it's possible to simplify the post command a bit more, like  just find the CSS selector to post. 😆

**Comment by 7peanuts** [comment]
[https://risu.io/](https://risu.io/)

This site is a bit weird, no matter what you type, the search button will always perform one click before executing other commands.

However, the following script still gets search results, it just looks a bit odd.

```js
(async() => {
  await new Promise(r => setTimeout(r, 2000));
  let input = document.querySelector('#link_url.form-control');
  input.value = searchTerms;
  input.dispatchEvent(new Event("input"));
  document.querySelector('#url.btn.btn-primary').click();
})();
```

**Comment by ssborbis** [comment]
I tried your code. It seems good. Is there some other way you want to handle the resulting URL / link / QR code ?

**Comment by 7peanuts** [comment]
> Is there some other way you want to handle the resulting URL / link / QR code ?

I know very little about programming, so sorry can't be of much help.
But I got a few suggestions from this user script.
https://github.com/hoothin/SearchJumper

Can I switch between search engines, for example, after I use Google to search for `Witcher3`, then press a shortcut key on the Google results page to jump to Yandex search `Witcher3`.
Use REGEX rule to set the category and search engine to display on specific pages.

**Comment by ssborbis** [comment]
> Can I switch between search engines, for example, after I use Google to search for Witcher3, then press a shortcut key on the Google results page to jump to Yandex search Witcher3.
Use REGEX rule to set the category and search engine to display on specific pages.

Open a new feature request and I'll give progress updates there.

**Comment by 7peanuts** [comment]
> Open a new feature request and I'll give progress updates there.

Ok, is that right? #503 
If not, I would delete that issue.

**Comment by ssborbis** [comment]
What are you trying to translate to / from ?

**Comment by 7peanuts** [comment]
> What are you trying to translate to / from ?

I can add en-zh to the search template, but if I select other language then submit search, it can't get correct translate result.

**Comment by ssborbis** [comment]
> I can add en-zh to the search template, but if I select other language then submit search, it can't get correct translate result.

Can you elaborate on this? My understanding of what you said is: 

You have a yandex search engine template that uses `en-zh` as a parameter. But after seeing the results page, attempting another search through the website's search bar, after selecting a different language, yields incorrect results? Do I have that right?

**Comment by 7peanuts** [comment]
`https://translate.yandex.com/?lang=en-zh&text={searchTerms}`

The yandex template can only specify one language for translation, so if my template is English to Chinese, I get an error when I select Japanese for translation.

I don't know how to write a search template that translates from any language to Chinese.

**Comment by ssborbis** [comment]
Are you trying to use the auto-detect language feature?

**Comment by 7peanuts** [comment]
> Are you trying to use the auto-detect language feature?

But I don't know how to add auto-detect language to the search template

**Comment by ssborbis** [comment]
You need to land on the generic page `https://translate.yandex.com` and use post-search script to fill in the text area value and trigger a search. I noticed the input will default to auto-detect, but the output is set foremost by cookies / cache ( defaults to the last language used )

**Comment by 7peanuts** [comment]
> You need to land on the generic (泛型) page `https://translate.yandex.com` and use post-search script to fill in the text area value and trigger a search. I noticed the input will default to auto-detect, but the output is set foremost by cookies / cache ( defaults to the last language used )

Yes, but I couldn't find the element of the text input box.

```js
(async() => {
  let input = document.querySelector('#fakeArea.textarea.textinput.textlayer.textlayer_src');
  input.focus();
  await new Promise(r => setTimeout(r, 200));
  input.value = searchTerms;
  input.dispatchEvent(new Event("input"));
  input.dispatchEvent(new Event("change"));
})();
```

**Comment by ssborbis** [comment]
```javascript
(() => {
  let input = document.querySelector('#textarea');
  input.value = searchTerms;
  document.querySelector('#textbox').dispatchEvent(new Event("input"));
})();
```

**Comment by 7peanuts** [comment]
> ```js
> (() => {
>   let input = document.querySelector('#textarea');
>   input.value = searchTerms;
>   document.querySelector('#textbox').dispatchEvent(new Event("input"));
> })();
> ```

No input text, it seems that it is not #textarea

**Comment by ssborbis** [comment]
That code is working for me when the template is set to https://translate.yandex.com

I don't know why it's not working for you. You may need to add a delay or something.

**Comment by 7peanuts** [comment]
> 

Hmm, strange, it works on Firefox, not chromium.

**Comment by ssborbis** [comment]
It looks like on chrome, you need to set the innerText of the contenteditable div to get it to work.

```javascript
(() => {
  document.querySelector('#textarea').value = searchTerms;
  document.querySelector('#fakeArea').innerText = searchTerms;
  document.querySelector('#textbox').dispatchEvent(new Event("input"));
})();
```

**Comment by 7peanuts** [comment]
> It looks like on chrome, you need to set the innerText of the contenteditable div to get it to work.

Thanks, I guess I'll have to take some time to learn CSS 😆.

**Comment by 7peanuts** [comment]
I'm bothering you again, please help me with this site.
[https://www.iciba.com/fy](https://www.iciba.com/fy)

![20221003105428](https://user-images.githubusercontent.com/82173614/193493780-eec35bc7-d54f-4910-a5f9-1c6350eed705.png)

**Comment by ssborbis** [comment]
@7peanuts I can't load that page for some reason. Seems busy.

**Comment by 7peanuts** [comment]
hi, i need you help 😂
https://yi.qq.com/en-US/index

**Comment by ssborbis** [comment]
@7peanuts 

Have you tried bubbling the events?

```javascript
(async() => {
  let input = document.querySelector('#ORIGINAL_TEXTAREA');
  input.focus();
  await new Promise(r => setTimeout(r, 500));
  input.value = searchTerms;
  input.dispatchEvent(new Event("input", {bubbles:true}));
  input.dispatchEvent(new Event("change", {bubbles:true}));
})();
```

**Comment by 7peanuts** [comment]
> Have you tried bubbling the events?
> 

Thank you so much! I previously said I would like to learn some JS & CSS, but I haven't started yet. 😂
