### ISSUE TITLE
Quick menu opens at incorrect position 

### ISSUE THREAD

**Issue by wohoho-G** [ssborbis/ContextSearch-web-ext#489]
Since updated from version 1.28.1 to 1.39

When text selected, Quick menu opens at the lowest portion of screen but not near the cursor
site  [https://mcountdown.genie.co.kr/chart/info](https://mcountdown.genie.co.kr/chart/info)

Firefox 91.xx ESR, Windows 7

Thanks for creating this great extension ^^

**Comment by ssborbis** [comment]
Thanks. I'm exploring some workarounds. Websites overriding this addon's styling has been an ongoing problem, but the new code should take care of all of it when done. Changes should be in the next release.

**Comment by ssborbis** [comment]
I don't have an ESR version installed, but if you want to test the changes, they're in the development branch. Looks good on Chromium and FF though, so ESR should be OK too.

**Comment by wohoho-G** [comment]
Thanks for your reply.
With the development branch, Quick menu does show up at right place.

Wait for next stable release ^^

**Comment by ssborbis** [comment]
1.41.1 is out. Re-open this issue if it's still causing problems. I did make some changes that could potentially effect older browser versions (ESR included).
