### ISSUE TITLE
Is it possible to export just the search engine list?

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#490]
Because I use it on a few browsers, the appearance and other settings will be different.

And is it possible to select a part of the engine list for export when exporting?

**Comment by ssborbis** [comment]
Not currently, but this has been mentioned by another user. I'll see what can be done and post here when I have something to test.

**Comment by ssborbis** [comment]
I've been thinking, would it work just as well if the full config was exported, but on import, you were able to check boxes for what parts you wanted plus a replace / merge option?

**Comment by 7peanuts** [comment]
That's okay.

My previous idea was to export the search template to be able to use it for other similar add-ons or software.

**Comment by 7peanuts** [comment]
good

**Comment by ssborbis** [comment]
Well you can kinda do that through the console on the options page. You'll need to run some javascript on the array to get it in the correct format for other addons anyway.

The proper OpenSearch formatted engines are in the array `userOptions.searchEngines`

**Comment by 7peanuts** [comment]
> but on import, you were able to check boxes for what parts you wanted plus a replace / merge option?

Is this partial import function ready to use?

> You'll need to run some javascript on the array to get it in the correct format for other addons anyway.

Is there any tools to export template strings?
![20221019133210](https://user-images.githubusercontent.com/82173614/196605590-7107fcbe-3890-415b-87ad-b05cf9ded181.jpg)

**Comment by ssborbis** [comment]
> Is this partial import function ready to use?

No. I've been working on other things

> Is there any tools to export template strings?

Export how? What format are you wanting to get them into? Are you swapping between CS installs or between different addons?

**Comment by ssborbis** [comment]
Merging configs makes things more complicated. I'm working on something, but I'll roll it out slowly because I don't want a bug to cause config errors. I'll let you know when I have something to test.

**Comment by 7peanuts** [comment]
> Merging configs makes things more complicated. I'm working on something, but I'll roll it out slowly because I don't want a bug to cause config errors.

Just take your time, this feature is optional. 😎
I will find a software that can extract the search engines strings in bulk instead.

**Comment by ssborbis** [comment]
Latest push to dev branch will allow this. It needs testing and has some limitations, but looks good so far.

![Screenshot_2022-10-26_21-21-16](https://user-images.githubusercontent.com/24310997/198176273-96f26dc0-901f-4fbd-8d48-fd04d3367aed.png)

Use the same Import button, and it should recognize the file as a partial list import

**Comment by ssborbis** [comment]
Some fixes going up. It's a work in progress.

**Comment by ssborbis** [comment]
v1.46 has these enhancements.  Open an new issue if you run into bugs
