### ISSUE TITLE
add description

### ISSUE THREAD

**Issue by karinaardos** [ssborbis/ContextSearch-web-ext#491]
When you hover the mouse over an item, a tooltip with the name pops up. Can you add the ability to see the description of the menu item in the tooltip?

**Comment by ssborbis** [comment]
Should be easy enough to do. I'll let you know when I have something to test. What browser are you on?

**Comment by ssborbis** [comment]
Changes are in the development branch. You'll need to set `showDescriptionsInTooltips` to `true` from CS Options -> Advanced -> Manual Edit

**Comment by karinaardos** [comment]
Browser firefox . Thanks a lot.

**Comment by ssborbis** [comment]
This should be working (optionally) in v1.40+ Go ahead and close it out if its working correctly.
