### ISSUE TITLE
REGEX and Bookmarklets

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#492]
1️⃣ How to convert case with REGEX? The formatting of ContextSearch looks different.

2️⃣ How to use Bookmarklets, it doesn't work when I type like this.

The function of this script is to display all images, and it works well when saved as a bookmark to use.

![20220604184554](https://user-images.githubusercontent.com/82173614/171995860-9a2c9789-48c5-4c82-b5bd-c82badee2844.png)

`javascript:outText='';for(i=0;i<document.images.length;i++){if(outText.indexOf(document.images%5Bi%5D.src)==-1){outText+='<tr><td><img src='+document.images%5Bi%5D.src+'></td><td>'+document.images%5Bi%5D.height+'</td><td>'+document.images%5Bi%5D.width+'</td><td>'+document.images%5Bi%5D.src+'</td></tr>'}};if(outText!=''){imgWindow=window.open('','imgWin','width=800,height=600');imgWindow.document.write ('<table border=1 cellpadding=10><tr><th>Image</th><th>Height</th><th>Width</th><th>URL</th></tr>'+outText+'</table>');imgWindow.document.close()}else{alert('No images!')}`

**Comment by ssborbis** [comment]
Some of the script appears to be uri encoded `images%5Bi%5D`. I think that may be causing issues. 

It should probably be rewritten as `images[i]`

**Comment by ssborbis** [comment]
Hmm... I checked with the corrections and it isn't working. It seems the references to imgWindow don't seem to be accessible. I'll play around and let you know if I find anything.

**Comment by 7peanuts** [comment]
> Hmm... I checked with the corrections and it isn't working. It seems the references to imgWindow don't seem to be accessible. I'll play around and let you know if I find anything.

Thank you very much for your kind reply! The modified script can also be used after saving it as a bookmark.

**Comment by 7peanuts** [comment]
> And how to convert the case of search terms with REGEX?
> 
> `"[A-Z]","(???)"`

`\L$1` This replacement expression is also incorrect.

**Comment by ssborbis** [comment]
I don't think javascript regex supports `\L` . Is that a sed function?

**Comment by ssborbis** [comment]
Nope, doesn't look like javascript has that transformation. Most people use a callback function and call `.toLowerCase()`, which isn't doable here. You're best bet may be to chain a bunch of regex replacements for each letter

```
/a/A
/b/B
/c/C
...
```

**Comment by ssborbis** [comment]
Just a quick tip, you *should* be able to use either of these formats for regex. One tends to be cleaner than the other:

`"find", "replace"`
or
`/find/replace`

**Comment by 7peanuts** [comment]
> Nope , doesn't look like javascript has that transformation. Most people use a callback function and call `.toLowerCase()`, which isn't doable here. Your best bet may be to chain a bunch of regex replacements for each letter
> 
> ```
> /A/a/g
> /B/b/g
> /C/c/g
> ...
> ```
Since the REGEX is not so simple and cleaner, how to use JavaScript to convert the case?

**Comment by ssborbis** [comment]
If you're treating the engine like a javascript-based engine ( filling in and submitting the form via javascript ), just use something like

`input = searchTerms.toLowerCase()`

**Comment by justsome12** [comment]
> `javascript:outText='';for(i=0;i<document.images.length;i++){if(outText.indexOf(document.images%5Bi%5D.src)==-1){outText+='<tr><td><img src='+document.images%5Bi%5D.src+'></td><td>'+document.images%5Bi%5D.height+'</td><td>'+document.images%5Bi%5D.width+'</td><td>'+document.images%5Bi%5D.src+'</td></tr>'}};if(outText!=''){imgWindow=window.open('','imgWin','width=800,height=600');imgWindow.document.write ('<table border=1 cellpadding=10><tr><th>Image</th><th>Height</th><th>Width</th><th>URL</th></tr>'+outText+'</table>');imgWindow.document.close()}else{alert('No images!')}`

where did you get that one from? love it :)

**Comment by 7peanuts** [comment]
> Hmm... I checked with the corrections and it isn't working. It seems the references to imgWindow don't seem to be accessible. I'll play around and let you know if I find anything.

@ssborbis @justsome12 

I got it, reverted it back to URL encoding and it worked.
But the hotkey doesn't work, it can only be used by clicking the icon.

```js
javascript: outText = '';
for (i = 0; i < document.images.length; i++) {
    if (outText.indexOf(document.images[i].src) == -1) {
        outText += '<tr><td><img src=' + document.images[i].src + '></td><td>' + document.images[i].height + '</td><td>' + document.images[i].width + '</td><td>' + document.images[i].src + '</td></tr>'
    }
};
if (outText != '') {
    imgWindow = window.open('', 'imgWin', 'width=800,height=600');
    imgWindow.document.write('<table border=1 cellpadding=10><tr><th>Image</th><th>Height</th><th>Width</th><th>URL</th></tr>' + outText + '</table>');
    imgWindow.document.close()
} else {
    alert('No images!')
}
```

**Comment by ssborbis** [comment]
> But the hotkey doesn't work, it can only be used by clicking the icon, or when the mouse points to a picture or link and presses the hotkey at the same time to open the script.

Hotkeys expect a context of one of the following under the cursor ( link, image, audio, video ) or a text selection. They don't trigger without one of those. This was intentional to prevent unwanted hotkey triggering. I suppose I can add an option, but I don't think that should be the default.

**Comment by 7peanuts** [comment]
> Hotkeys expect a context of one of the following under the cursor ( link, image, audio, video ) or a text selection. They don't trigger without one of those. This was intentional to prevent unwanted hotkey triggering. I suppose I can add an option, but I don't think that should be the default.

Yes, that's good, this allows users to set their own way of using each search engine hotkey.
Maybe even add use of key combinations to start the search, e.g. Alt+A, and disable shortcuts while entering text.

**Comment by ssborbis** [comment]
I'm doing some issues housecleaning. Can this thread be closed or is this issue still unresolved?

FYI, %su and %sl can now be used in templates to specify uppercase and lowercase search terms.

**Comment by 7peanuts** [comment]
> Can this thread be closed or is this issue still unresolved?
> 
Thanks, I closed it.

**Comment by ssborbis** [comment]
#690 has a solution for that particular script no longer working. The issue is due to browser security updates to CORS.
