### ISSUE TITLE
mac trackpad secondary click on pics working not stably

### ISSUE THREAD

**Issue by 11100010** [ssborbis/ContextSearch-web-ext#493]
My device on MacOS 12.4, contextsearch Version 1.39, Chrome Version 102.0.5005.61 (Official Build) (arm64).

Secondary click ( right-click ) on trackpad onto pictures sometimes works, sometimes not. 
But clicking on blank space to display default context menu works well. 

Using mouse right-clicking will not encounter this problem even on pictures or blank space.

Anyway, this is just a small problem. Your extension is the best for my browsing experience.
Thank you so much for your awesome work.

**Comment by ssborbis** [comment]
I'll try to dig up a trackpad for testing. i don't have anything available right now. 

Is the secondary click a physical button on your pad, or a touch zone? I don't know that will make a difference, but it might be worth knowing.

**Comment by 11100010** [comment]
I'm normally using two finger tap on the touch zone

**Comment by 11100010** [comment]
the value of "quickMenuMoveContextMenuMethod" is indeed dblclick.
<img width="1280" alt="Screen Shot 2022-06-23 at 11 03 55" src="https://user-images.githubusercontent.com/87060114/175206766-7dd14605-a3db-4f36-bf87-6e586533399a.png">

**Comment by ssborbis** [comment]
I set up a virtual machine with macOS. I'll see if I can spot anything there.

**Comment by ssborbis** [comment]
I've yet to see anything odd using a trackpad. Do you have any other addons that could be causing a conflict?

You might also send me your config to try out, to rule out any setting conflicts.

**Comment by 11100010** [comment]
> I've yet to see anything odd using a trackpad. Do you have any other addons that could be causing a conflict?
> 
> You might also send me your config to try out, to rule out any setting conflicts.

I think you are absolutely right about this. It appears likely that there is some conflict between chrome extensions which i've installed, I tried to disable every other ones, let alone just ContextSearch and the problem disappeared. 
Maybe I should just live with this not-so-serious trouble. Thank you for your efforts helping me so much.
