### ISSUE TITLE
Doesn't work with yt-dlp.exe on Windows

### ISSUE THREAD

**Issue by runningcheese** [ssborbis/ContextSearch-web-ext#494]
Nice extension!

I tried everything.exe, photoshop.exe, potplayer.exe, Everything works fine, 

but doesn't work with yt-dlp.exe

Any thing wrong?

![](https://tva1.sinaimg.cn/large/e6c9d24egy1h3144gbd3xj20xv0llgo2.jpg)

**Comment by ssborbis** [comment]
There may be some command line escape issues between the python interpreter and windows. I'm almost exclusively testing on linux, so I'm not seeing these problems.

I'll try to sort out what @logusergithub is seeing, and maybe find the issue.

What's your exact command line to yt-dlp.exe?

**Comment by ssborbis** [comment]
I was able to get things working with this, using the "min" version ( the normal wasn't running on my virtual machine for some reason )

Command:
`yt-dlp_min.exe {searchTerms}`

Working directory:
`C:\Users\default\Downloads`

There is no popup window to show progress, however. For that, you probably need to use `start` at the beginning of the command

`start yt-dlp_min.exe {searchTerms}`

**Comment by ssborbis** [comment]
@logusergithub 

I tested this command, fixing a typo I believe (...Downloads% to ...Downloads\%), with good results

`start yt-dlp_min.exe -no-cache-dir -o --get-filename -o C:\Users\Mike\Downloads\%(title)s.%(ext)s "{searchTerms}"`

**Comment by logusergithub** [comment]
Only heaven knows why that '\' got lost when copying and pasting from the other extension, but it only affects the last folder.
Conversely, by setting up the 'Working directory' and using 'start' (without '_min') all now works fine, thanks!

Sorry, I wrote this wrong too but now I found by chance that it is also the solution:
"C:\Program Files\MPV\mpv.exe" --stream-record=R:\Streaming.mkv "{searchTerms}"
The original was: 
"C:\Program Files\MPV\mpv.exe" --stream-record=R:\Streaming.mkv <URL>  "{searchTerms}" 
It seems that this "<URL>" it is not even important to Open With.

So, it is better by default force the Working directory?

**Comment by ssborbis** [comment]
I the slashes may be disappearing due to html formatting on this site. If it matters, put a backtick ( \` ) on both sides of the path to keep the formatting clean, like \`this\`

> So, it is better by default force the Working directory?

Sometimes it makes no difference, but when in doubt, probably not a bad idea
