### ISSUE TITLE
Extra folders with Separator appear in the right-click context menu

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#495]
As you can see on the right, I created an empty folder with only Separator, but this empty folder appears in the context menu.

In the `Contxt Menu` setting,  `0` means there is no limit to the number of engines, but it doesn't take effect for a subfolder with Separator.

Subfolders with Separator are removed correctly only when the number is greater than the number of engines.

![20220611190600](https://user-images.githubusercontent.com/82173614/173185645-15afd92e-9afa-4b2f-84ba-d8b5c3859653.png)

**Comment by ssborbis** [comment]
This is not a setting I'm too familiar with, so bear with me.

I think a setting of 0 technically means the flattening is disabled. I don't know why I wrote `no limit`. Does that seem to fit with the behavior you're seeing?
