### ISSUE TITLE
[Request] select text search for everything software

### ISSUE THREAD

**Issue by DandyClubs** [ssborbis/ContextSearch-web-ext#496]
https://addons.mozilla.org/ko/firefox/addon/rich-select-menu/

https://addons.mozilla.org/ko/firefox/addon/everything-search-we/

yet have not chrome extention

**Comment by ssborbis** [comment]
Are you wanting to send selected text to an external application ( [Everything](https://en.wikipedia.org/wiki/Everything_(software) ) ) ? 

If so, that feature was developed in #459

There is also some info in the [readme](https://github.com/ssborbis/ContextSearch-web-ext#8-launching-external-applications)

**Comment by DandyClubs** [comment]
> Are you wanting to send selected text to an external application ( [Everything](https://en.wikipedia.org/wiki/Everything_(software)) ) ?
> 
> If so, that feature was developed in #459
> 
> There is also some info in the [readme](https://github.com/ssborbis/ContextSearch-web-ext#8-launching-external-applications)

thnaks!

**Comment by ssborbis** [comment]
What does your app launcher setup look like?

example:
![app_launcher](https://user-images.githubusercontent.com/24310997/175465746-ca07e4ec-4cb9-483e-812e-5c891eb4c506.jpg)

**Comment by justsome12** [comment]
> > Are you wanting to send selected text to an external application ( [Everything](https://en.wikipedia.org/wiki/Everything_(software)) ) ?
> > If so, that feature was developed in #459
> > There is also some info in the [readme](https://github.com/ssborbis/ContextSearch-web-ext#8-launching-external-applications)
> 
> thnaks!
> 
> es protocol is not work...

have you activated "url protocol" in everything setting:general?

**Comment by ssborbis** [comment]
This issue has been inactive for a while. If the problem hasn't been resolved, please re-open.
