### ISSUE TITLE
How to open last used engine with keyboard shortcut?

### ISSUE THREAD

**Issue by ssborbis** [ssborbis/ContextSearch-web-ext#497]
@ZobaJakColbert

from #321

I'll see about adding user-set keyboard shortcuts to tools.

**Comment by justsome12** [comment]
could you also add the possibility to use it as a normal folder? that I can open the whole folder (e.g. last 5 used). left/right/middle click all only open the submenue.

**Comment by ssborbis** [comment]
@justsome12 

I've updated the development branch with a fix that allows the regex folder and recently used folder to be searched as a folder ( all contents ). Note, this is the prepended folder, not the tool. ( CS Options -> Advanced -> `quickMenuShowRecentlyUsed`

**Comment by ssborbis** [comment]
> could you also add the possibility to use it as a normal folder? that I can open the whole folder (e.g. last 5 used). left/right/middle click all only open the submenue.

I believe this is working as expected. Please reopen if not.
