### ISSUE TITLE
Works well on Windows, but doesn't work on Mac?

### ISSUE THREAD

**Issue by runningcheese** [ssborbis/ContextSearch-web-ext#498]
thanks for your extension, you did a good job.

but when i try to lanugh a browser, it works well in windows, but doesn't work in mac?

did i miss out something?

<img width="829" alt="iShot2022-06-26 14 16 18" src="https://user-images.githubusercontent.com/4476264/175802236-e713b072-6a79-434d-b6d2-7e1b17fa1f4c.png">
<img width="954" alt="iShot2022-06-26 14 17 48" src="https://user-images.githubusercontent.com/4476264/175802250-12fa3cf9-6006-4cee-86c9-2f12e9cdde11.png">
<img width="1319" alt="iShot2022-06-26 14 18 22" src="https://user-images.githubusercontent.com/4476264/175802251-16342f5f-90d2-4e9f-8a0b-a6ab79d400ba.png">
<img width="1319" alt="iShot2022-06-26 14 18 39" src="https://user-images.githubusercontent.com/4476264/175802252-fbf7e4aa-d10f-4640-955a-cd1802e42551.png">

**Comment by runningcheese** [comment]
Anyway, i have made a big promotion in my soical network, to introduce your great extension to my following fans!

**Comment by ssborbis** [comment]
I am in the process of installing a MacOS virtual machine. I will update you when I have the app launcher feature up and working.

**Comment by runningcheese** [comment]
> I am in the process of installing a MacOS virtual machine. I will update you when I have the app launcher feature up and working.

thanks for your great work!

**Comment by ssborbis** [comment]
It looks like `/Applications/Firefox.app` is actually a directory. You need to point to the binary within.

`/Applications/Firefox.app/Contents/MacOS/firefox-bin "{searchTerms}"`

I assume the same is true of other `.app` listings found under `/Applications/`

**Comment by ssborbis** [comment]
Here we go. This is a better way to launch apps on Mac

`open -a 'Downie 3' "{searchTerms}"`
`open -a 'Firefox' "{searchTerms}"`

etc

**Comment by runningcheese** [comment]
> Here we go. This is a better way to launch apps on Mac
> 
> `open -a 'Downie 4' "{searchTerms}"` `open -a 'Firefox' "{searchTerms}"`
> 
> etc

Love you!

Everything works fine now!!!

But Photoshop still can't open an image directly, either windows or mac.

But it's fine for me.

Maybe because of the photoshop limitation.

**Comment by ssborbis** [comment]
if photoshop doesn't have a built-in way, you can use the `curl` trick I posted in #500 

for windows, it would probably be something like this
`curl "{searchTerms}" -o tmp & "c:\\path\to\photoshop.exe"  tmp`

If curl isn't included on macOS, it's easy enough to get. It should be similar syntax

**Comment by runningcheese** [comment]
> 
I just try curl command, but still can not open image directly.

It's fine for me, if cannot make it happen.

![截屏图片](https://user-images.githubusercontent.com/4476264/176586251-946b4cba-a2ae-4996-8250-7e890c83d38d.jpg)

**Comment by 7peanuts** [comment]
> if photoshop doesn't have a built-in way, you can use the `curl` trick I posted in #500
> 
`"D:\\path\to\photoshop.exe" -n -a "{searchTerms}"`

This can open PS, but no pictures.

`curl "{searchTerms}" -o tmp & "D:\\path\to\photoshop.exe" tmp`

This can also open PS, but PS doesn't support tmp format.

`Cannot complete the clear request because it is not the type of document referred to.`

![20220630113006](https://user-images.githubusercontent.com/82173614/176586898-26276d13-f057-4f7d-8e36-fa2dddbecdcc.png)

**Comment by ssborbis** [comment]
Sorry, I don't have photoshop for testing. ( Is there a free version? ). There's always a way.

**Comment by 7peanuts** [comment]
> Sorry, I don't have photoshop for testing. ( Is there a free version? ). There's always a way.

Yeah, it has a 7-day free trial.

**Comment by ssborbis** [comment]
The following script allows for downloading a file via cURL to the macOS temporary folder and opening the file, by name, with the application of choice.

download.sh
```sh
#!/bin/sh

cd $TMPDIR
FILENAME=`curl -OJs -w ${filename_effective} $2`
open -a $1 $TMPDIR/$FILENAME
```

Make sure to chmod +x the file, and place it somewhere you know. Then your application launcher command will look like this:

`/Users/virtualuser/download.sh "Firefox" "{searchTerms}"`

replace "Firefox" with whatever app can be called by `open -a`. If calling binaries more directly, you'll need to modify the script.

**Comment by runningcheese** [comment]
@ssborbis 

still not working! but it's fine, it's great enough for me.

**Comment by ssborbis** [comment]
I refuse to believe Photoshop can't open files from a shell script. If I can get PS installed, I'll figure out something.

**Comment by 7peanuts** [comment]
> I refuse to believe Photoshop can't open files from a shell script. If I can get PS installed, I'll figure out something.

Maybe you can download it from the Pirate Bay. I don't know if it's allowed in your region.

**Comment by runningcheese** [comment]
@ssborbis 

One more question please!

How to lanugh "yt-dlp" on macOS? it doesn't work with open -a command.

![7a6a15d5gy1gyqwjw57n9j223s19cnh0](https://user-images.githubusercontent.com/4476264/176995718-54e823d9-b74d-46a4-a52f-5de29424a8df.jpg)

<img width="713" alt="iShot2022-07-02 17 54 59" src="https://user-images.githubusercontent.com/4476264/176995725-ae06dc87-a691-444e-a48b-a5801a5e344e.png">

**Comment by ssborbis** [comment]
@runningcheese 

Have you tried calling yt-dlp directly, without the `open -a "Terminal"` ?

**Comment by runningcheese** [comment]
@ssborbis 

Unfortunatly, Not Working!

<img width="709" alt="iShot2022-07-03 10 04 18" src="https://user-images.githubusercontent.com/4476264/177021601-6d0389b4-acec-4d3c-8976-e0b1fe85f8e0.png">
<img width="702" alt="iShot2022-07-03 10 02 56" src="https://user-images.githubusercontent.com/4476264/177021602-875a7cae-3051-4b5b-bec5-2c24ad87ba42.png">

**Comment by ssborbis** [comment]
mac appears to be a bit of a pain to play nice with the terminal. This is the command I've had the best luck with. Edit to your specs

`osascript -e 'tell app "Terminal" to do script "/Users/virtualuser/Downloads/yt-dlp -P /Users/virtualuser/Desktop --no-playlist \"{searchTerms}\""'`

I'm having some ssl cert issues, so that command doesn't actually download anything, but it looks like the command is working.

**Comment by runningcheese** [comment]
> `osascript -e 'tell app "Terminal" to do script "/Users/virtualuser/Downloads/yt-dlp -P /Users/virtualuser/Desktop --no-playlist \"{searchTerms}\""'`

It works fine!! love you!

**Comment by ssborbis** [comment]
I had a mistake in the `download.sh` script. Put a $ when it should have been a %

Here's a corrected script that should work on mac and linux

```sh
#!/bin/sh

TMP="/tmp"
if [ "$OSTYPE" = 'darwin'* ]; then TMP=$TMPDIR; fi
cd $TMP
FILENAME=`curl -OJs -w "%{filename_effective}" $2`
$1 $TMP/$FILENAME
```

**Comment by ssborbis** [comment]
FYI, in future versions of this addon, you'll simply check a box on the app launcher edit modal to have the python native app download the file to be opened. No script needed. I'm testing now on linux. Looks good so far.

**Comment by runningcheese** [comment]
@ssborbis 
Thanks for your great work, looking forward to...

**Comment by ssborbis** [comment]
I posted a beta you can try out.

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.40beta/contextsearch_web_ext-1.40b5.xpi

Replace the param `{searchTerms}` with `{download_url}` in app launcher templates to direct the native app to download the file found at the URL you've presumably searched for through CS.

For example, to download a file by URL and open in GIMP in linux, I'm using this template

```
gimp -a "{download_url}"
```

You'll need the lastest version of the native app ( ContextSearch.py v2.15 )
https://github.com/ssborbis/ContextSearch-Native-App/raw/master/ContextSearch.py

**Comment by runningcheese** [comment]
@ssborbis 
Seems not happening!

and when i replace the 2.16 version of ContextSearch.py, it will show "message app is not connected".

i have retyped "python3 install.py".

and please try photoshop in linux：

https://linuxhint.com/install_adobe_photoshop_linux

<img width="780" alt="iShot2022-07-17 18 16 41" src="https://user-images.githubusercontent.com/4476264/179393803-69b086c1-8d6d-4fde-bd34-1c921c291001.png">

**Comment by runningcheese** [comment]
and one more question, how to lanuch yt-dl on linux?

this is what i did.

![WechatIMG217](https://user-images.githubusercontent.com/4476264/179402998-4a445c53-3d22-4be0-a1ca-d029dd960f22.png)

**Comment by ssborbis** [comment]
I just tried the install.py script. It seems to be working for me. What OS is it failing on? Any error messages?

**Comment by ssborbis** [comment]
> and one more question, how to lanuch yt-dl on linux?

I'm not familiar with deepin-terminal. The `--` command is probably gnome-terminal specific. Check the help output and see what it says about launching a new terminal.

**Comment by ssborbis** [comment]
> I just tried the install.py script. It seems to be working for me. What OS is it failing on? Any error messages?

You might also double-check that ContextSearch.py has permission to execute. ( chmod +x ).

**Comment by logusergithub** [comment]
Thanks for the new parameter.
I tried 1.40b5.xpi\2.17 with {download_url} and it seems to works fine with standard image\document links (on Windows: XnView, MSPaint, PS, SumatraPDF).
It's just gets better and better.

**Comment by 7peanuts** [comment]
> Replace the param `{searchTerms}` with `{download_url}` in app launcher templates to direct the native app to download the file found at the URL you've presumably searched for through CS.
> 
> For example, to download a file by URL and open in GIMP in linux, I'm using this template
> 
> ```
> gimp -a "{download_url}"
> ```

Thanks, I haven't tried Ps since the update, now I can open it. 😍

`"Photoshop.exe" - a "{download_url}"`

**Comment by ssborbis** [comment]
> For me, some image downloads require a proxy, so how do I get Messenger app to use a proxy to download?

Uh, I'm not sure. How does the proxy manage requests? If it's by tacking an url to the end of another url ( http://myproxyexample.com/url=http%3A%2F%2Furl.to%2Fimage.jpg ) or something similar, you can use the Modify Terms Regex field. If it's something more complicated, you might need to modify ContextSearch.py
