### ISSUE TITLE
[Request] Enable delete engine directly from the quick menu

### ISSUE THREAD

**Issue by CrazieIvan** [ssborbis/ContextSearch-web-ext#499]
This is a request for a QoL / convenience feature.  It's not anything essential, and I already love the addon as it is.  

Often times I end up creating identical or unnecessary search engines, and deleting them requires a lot of clicks:  click the overflow menu in FF, click the addon, click the gear icon, select search engines, scroll to find the engine, right click, select delete, select confirm, close the addon tab, go back to the previous tab.  

Would it be possible to enable deleting engines directly from the quick menu?  I think it would feel intuitive to be able to right click on an engine right there and delete it, given that we can rearrange them.  And I really don't need right-click to open search results, because we already have left-click or middle-click for that.  

Thanks for the great extension!

**Comment by ssborbis** [comment]
I'll need to think of a good way to do this. Maybe I can add a trashcan icon to the qm when in EDIT mode that tiles can be dragged to. Does that sound like a reasonable solution?

**Comment by ssborbis** [comment]
I have a decent fix in the development branch. I can sign a beta for you if you want to test it out. You'll need to set `allowDeleteEnginesFromTileMenu = true` from the Advanced -> Manual Edit menu.

**Comment by CrazieIvan** [comment]
That was quick  :)
If you want my feedback, I'll be happy to give this a try.  Otherwise, I can wait for the release.  Whatever is easier for you.

**Comment by ssborbis** [comment]
You can try this beta. I've done very little testing. Backup your CS config just in case.

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.40b4/contextsearch_web_ext-1.40b5.xpi

**Comment by ssborbis** [comment]
This feature has been in the releases for a while now, so I'll close out the issue.
