### ISSUE TITLE
Need more External Applications command syntax

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#500]
#https://github.com/ssborbis/ContextSearch-Native-App/issues/2

As in the issue, I made a simple mistake because I didn't understand the syntax of these commands 😅

**Comment by ssborbis** [comment]
On second thought, it makes more sense to answer it here.

I don't think mspaint can handle URLs. In that case, you'll need to write a script to download the image and open mspaint, and then call that script from this addon.

**Comment by ssborbis** [comment]
If you have something like curl installed, you can use a command like this

`curl "{searchTerms}" -o tmp & mspaint tmp`

curl downloads the URL to a file called `tmp` then opens `tmp` in mspaint

**Comment by 7peanuts** [comment]
How to open magnet link, this is not work.
Normally, after copying the link, the BitComet automatically creates a new BitTorrent task.

`BitComet_x64.exe "{searchTerms}"`

![20220709102352](https://user-images.githubusercontent.com/82173614/178088411-a325a71b-f1ee-45e7-b4ea-3a900d1984fe.png)

**Comment by ssborbis** [comment]
Doesn't clicking a magnet link automatically open it in BitComet? What's the point of going through this addon?

**Comment by ssborbis** [comment]
FYI you have to use `--url` to download magnet links. I got that from `bitcomet --help`

`BitComet_x64.exe --url "{searchTerms}"`
![bitcomet_help](https://user-images.githubusercontent.com/24310997/178090588-0908ff7c-167e-4847-9b9a-dd4e08b8cfab.jpg)

**Comment by 7peanuts** [comment]
> Doesn't clicking a magnet link automatically open it in BitComet? What's the point of going through this addon?

Thank you, because I also installed other BT download software 😊

**Comment by ssborbis** [comment]
> Thank you, because I also installed other BT download software

That's what I figured, but I wanted to double-check.
