### ISSUE TITLE
Bug Report on Chrome Browser!

### ISSUE THREAD

**Issue by runningcheese** [ssborbis/ContextSearch-web-ext#501]
About the Toolbar Search.

<img width="906" alt="iShot2022-07-02 18 13 21" src="https://user-images.githubusercontent.com/4476264/176996293-bb290590-f41e-48ab-bea3-3f9ac796e291.png">

Firefox Works.
Chrome doesn't Work.

**Comment by ssborbis** [comment]
Is the problem that the menu does close when you want it to stay open, or that it doesn't close when you want it to close?

Which search action are you triggering? In other words, what mouse button are you clicking and what is that mouse button bound to under CS Options -> Quick Menu -> Search Actions

I quickly tested on Chromium using my middle-mouse bound to Open in Background Tab and that setting appears to be working as expected. Can you give me more details on exactly what you're seeing?

**Comment by 7peanuts** [comment]
对的，看一下 Search Actions 里的鼠标动作选项。
![CopyQ bCRpuu](https://user-images.githubusercontent.com/82173614/177021406-8f12daeb-abfd-4de0-863a-8f2871f86e06.png)

**Comment by runningcheese** [comment]
@ssborbis  @7peanuts 

Thanks, 

The anwser is the option "Search Actions".
