### ISSUE TITLE
Sometimes the Search Engines Test doesn't perform the search

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#502]
[https://www.urbandictionary.com/](https://www.urbandictionary.com/)
Template
`https://www.urbandictionary.com/search.php`
POST params
`term={searchTerms}`
Method
`POST`

But the search can still be performed normally using shortcut and quick menu.

This problem also occurs with search engines that use post script.

![-gif-](https://user-images.githubusercontent.com/82173614/177257628-df3fe209-2a85-429f-a8fd-f2e74ccfe9cf.gif)

**Comment by ssborbis** [comment]
Thanks, I'll check it out. POST engines are pretty rare these days so I haven't run across this bug yet.

**Comment by ssborbis** [comment]
Odd. It's working ok for me. 

Am I seeing this correctly in your GIF. The test button works, but gives the wrong results?

**Comment by 7peanuts** [comment]
> Am I seeing this correctly in your GIF. The test button works, but gives the wrong results?

Yes, it should search the keywords `FYI` when I click the test button, but no search results actually.

**Comment by ssborbis** [comment]
What browser / OS ?

I can't seem to get that bug.

**Comment by 7peanuts** [comment]
`Win11 21H2 22000.739`

There are problems on these versions below:
```
Firefox 100.0 64-bit
Firefox 99.0 64-bit
Chromium 86.0.4240.198 64-bit
Chromium 95.0.4638.69 64-bit
```
But it works fine on this version:

`Chromium 103.0.5060.102 64-bit`

**Comment by ssborbis** [comment]
This may have been addressed already in the development branch. I'm on the latest code, so maybe that's why I'm not seeing it.

I did trigger the bug on windows using v1.39, and it was gone when using the latest code

**Comment by ssborbis** [comment]
You might check that this is also fixed in the latest beta 

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.40beta/contextsearch_web_ext-1.40rc1.xpi
