### ISSUE TITLE
How to run a simple bash script via ContextSearch

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#504]
Hello ssborbis,

I would like to run a simple bash script via ContextSearch. 
I tried to add one via "New Script", but couldn't get it to work. 

I tried copying in the whole bash script, ... as well as just inserting the path to the script on my computer.

What am I missing here?

Best greetings,
Thomas

**Comment by ssborbis** [comment]
"Scripts" are for javascript to be run within the current webpage. It's essentially the new "Bookmarklet" type, but without the need to actually save the javascript as a bookmarklet first. Code can be entered directly into the Script edit modal.

"App Launcher" is for running bash scripts, binaries, etc; anything outside the web browser.

You'll need to install the latest python v3 and the native app script.
https://github.com/ssborbis/ContextSearch-Native-App

Once python is installed, download the source from the link above and run `install.py`. Another user reported issues with the latest nativeapp so it's possible there's an issue with the installer. I'll try it myself here in a sec. Once the native app is installed, add a new App Launcher from the context menu like you would a script. You'll probably be prompted to grant the native messaging permission. You should see a message at the bottom of the App Launcher edit modal that says the version of the native app (v2.17). If there's a problem with the connection, it will say "Messenger not connected"

**Comment by ssborbis** [comment]
There are a few ongoing threads regarding the app launcher you can look through for some ideas also 

#459 

#498

**Comment by ThomasSeeker** [comment]
Wow, that was easy! ... Works like a charm!
Thank you very much, for your fast and reliable help, Sborbis!

It is always a pleasure to fine tune ContextSearch even a bit more. :-D
So many possibilities ... Wow!

**Comment by ThomasSeeker** [comment]
I read all the other threads. ... And I am able to load pictures directly to Gimp now (with the new beta-version and the {download_url}-feature). ... What a nice thing! :-)

Now I am trying to open links in Chromium. I copied your command (see in the screenshot) ... but that does not work. ... With the /^$/{url}/g expression I got it to open the whole page (instead of just the link) though. ... which would be the desired outcome for not clicking on a link (but somewhere else).

Unfortunately I have no clue about regex. And I am also not quite sure, if I understand the choices in the top row correctly. I.e. Audio, Frame, Image, Link, etc. Is this a filter to determine, where the app-launcher should be triggered and where not? ... (The tool-tip to the right next to them speaks of "Advanced - Filter Engines" ... but I could not find this option in the Advanced-Menu.)

Do you have some advice?


![Screenshot_20220719_150227](https://user-images.githubusercontent.com/44918701/179761721-e7693ba8-c70c-4f9e-a797-3376474605a3.png)

**Comment by 7peanuts** [comment]
> Now I am trying to open links in Chromium. I copied your command (see in the screenshot) ... but that does not work. ...
> 
You should enter the full Path in the `COMMAND` field. See the README here [8. Launching External Applications](https://github.com/ssborbis/ContextSearch-web-ext#toc)

Examples:

COMMAND
`"d:\\Program Files\\Opera\\launcher.exe" "{searchTerms}"`

or

COMMAND
`launcher.exe "{searchTerms}"`
WORKING DIRECTORY
`D:\Program Files\Opera\`


> Unfortunately I have no clue about regex. And I am also not quite sure, if I understand the choices in the top row correctly. I.e. Audio, Frame, Image, Link, etc. 
> 
This represents on which element types the engine takes effect, and if you check `Filter search engines...` in the `ADVANCED` options of the `Context Menu` or `Quick Menu`, then the engine will only be displayed on those checked element types.

![20220719233729](https://user-images.githubusercontent.com/82173614/179794838-55c91c00-21fb-46c1-9c90-bdb6788ff795.png)

If you don't select any element type, then by default the engine only works on type `selection`.

**Comment by ThomasSeeker** [comment]
@7peanuts 

Thank you for pointing out the Advanced settings! Now I found it and it works great! :-)

Regarding the command, .... I am running Linux and the first part seems right. I am doubting the argument-part.

@ssborbis 

Yes, in the terminal I use for instance:
`chromium-browser https://www.spiegel.de/thema/meinung/` to open this link.

If I use `chromium-browser "{searchTerms}"`as the command, and click on a that link, it just opens Chromium, but with an empty url and nothing is shown.

But if I use `chromium-browser {url} ` as the command, and click on the link, it opens not the link, but the whole parent-page, i.e. https://www.spiegel.de

**Comment by ThomasSeeker** [comment]
Ha, I found the problem:

In the general settings I had checked  to use links as text instead of url. ... Now it works! :-D

**Comment by ssborbis** [comment]
@ThomasSeeker 

That'll do it. Glad to hear you got it sorted out.

**Comment by ThomasSeeker** [comment]
This is just a minor thing, ... but would it be possible, to have both: Open Chromium with the link, if one clicks on a link ... AND open Chromium with the parent page, if one clicks everywhere except on a link?

But only, if it is really easy to do, because this is really just a minor thing.

**Comment by ThomasSeeker** [comment]
I had an idea. I am working on a little bash script, which gets triggered and receives the two arguments `"{searchTerms}" "{url}"`. And the script then decides if the first one is not url, i.e. no link, then it uses the second. ... I let you know, how it went. ... ;-)
