### ISSUE TITLE
when I try do rename a folder name del key deletes the folder instead of the letter

### ISSUE THREAD

**Issue by justsome12** [ssborbis/ContextSearch-web-ext#505]
in "Search Engines Manager" "del" key deletes the folder instead of a letter (only if 'double click folder to edit' mode). FF

**Comment by justsome12** [comment]
in "Search Engines Manager" "del" key deletes the folder instead of a letter (only if 'double click folder to edit' mode)

**Comment by ssborbis** [comment]
Thanks. Fixes in development branch.
