### ISSUE TITLE
bug/FR: tools "show/hide" also unhide engines in folder and subfolder

### ISSUE THREAD

**Issue by justsome12** [ssborbis/ContextSearch-web-ext#506]
FR: that in tools "show/hide" (eye icon) also unhide folder and subfolder so that i can search normal (5 searches per folder) and extended (5+5 hidden) if I am really interested in the topic.

**Comment by 7peanuts** [comment]
Do you want to click the `Show / Hide` button to show hidden engines in the folder and subfolder?

I tried it and it works. The prerequisite is that  you go to the folder first and then click on it. It will not be displayed after clicking the button in the outer menu and then going to the folder.

![-gif-](https://user-images.githubusercontent.com/82173614/179496631-3128337b-9c8d-4b81-abda-8826781d1b6a.gif)

**Comment by ssborbis** [comment]
@justsome12 

Are you wanting the show/hide function to persist when you enter a subfolder? If it's something else, please go into more detail about your workflow so I can better understand exactly what you're wanting.

**Comment by justsome12** [comment]
@7peanuts 
yes and I didnt have the icons after clicking on a folder. but with "seperate toolbar" option activated it works. so this part is solved. 
@ssborbis 
the other answer is a good workaround. But I would like to have it persistent till deactivated again. if this is also possible?

**Comment by ssborbis** [comment]
@justsome12 

I have a potential fix in the dev branch

**Comment by justsome12** [comment]
this will finally be released right? I dont wanna mess around with the profile, since I have so many engines installed and am a noob:)

**Comment by ssborbis** [comment]
You can try this release candidate if you're on Firefox

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.40beta/contextsearch_web_ext-1.40rc1.xpi

**Comment by justsome12** [comment]
@ssborbis there is still a minor bug: if you click the show button and then enter a folder (show button is still selected) it doesn't show the hidden file, you first have to click hide again and show again that it works. it works if you first click it inside the folder though.

**Comment by ssborbis** [comment]
@justsome12 

Ok, I think I have that fixed. I'll probably drop a minor release in the next few days.

**Comment by justsome12** [comment]
> @justsome12
> 
> Ok, I think I have that fixed. I'll probably drop a minor release in the next few days.

thank you, I will just wait for the next release. Dont need it often :)
