### ISSUE TITLE
%s instead of {searchTerms} for the current selection

### ISSUE THREAD

**Issue by justsome12** [ssborbis/ContextSearch-web-ext#507]
is it possible to change the "{searchTerms}"?

**Comment by ssborbis** [comment]
Not currently. I'll see about making that an option.

**Comment by ssborbis** [comment]
It's working in the latest code for search engines. It will not work for app launchers and possibly other types as well. %s = {searchTerms}

**Comment by justsome12** [comment]
> It's working in the latest code for search engines. It will not work for app launchers and possibly other types as well. %s = {searchTerms}

that is AWESOME. it is just that I can easier copy paste firefox based searched bookmarks. So only need it for engines.

**Comment by ssborbis** [comment]
Changes pushed to the dev branch for testing. What OS are you on?

**Comment by justsome12** [comment]
Windows 10 Pro x64 21H2. I dont know how "branches" work. does it not automatically update over Firefox?

**Comment by ssborbis** [comment]
Try this release candidate

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.40beta/contextsearch_web_ext-1.40rc1.xpi
