### ISSUE TITLE
[Request] Multiply Search terms

### ISSUE THREAD

**Issue by MachineThatGoesP1NG** [ssborbis/ContextSearch-web-ext#508]
Add Ability To Replace Multiple passages within a url.

Example:

https://offerup.com/search?radius=10&q={ SEARCHTERMS }&price_min={ SEARCHTERMS 2 }&price_max={ SEARCHTERM 3 }

This would allow me to search a min max price...

**Comment by ssborbis** [comment]
How would you get the 2nd and 3rd search terms in the normal course of selecting text and searching?

**Comment by MachineThatGoesP1NG** [comment]
I typically use the toolbar menu to search, so i was thinking (and I'm pretty much a noob so bare with me) 
Typing searchterm 1 as normal text then adding some sort of parameter like %2 before the second search term maybe enclosed in brackets {%2 Searchterm} %2{searchterm} that would correlate with the template.

So this is mainly for the toolbar search function.

**Comment by ssborbis** [comment]
Here's a better way to do it. Same method should work for any engine you want to use multiple params.  Search terms format for this specific replace would be `motorcycle 1000 2000`
![replace](https://user-images.githubusercontent.com/24310997/179575595-dcae32e8-158d-48ef-8d72-a7db81123522.jpg)

```javascript
let url = "https://offerup.com/search?radius=10&q=$1&price_min=$2&price_max=$3";
window.location = searchTerms.replace(/(\w+) (\d+) (\d+)/, url);
```

**Comment by MachineThatGoesP1NG** [comment]
Not sure i understand how to use that last one....

**Comment by MachineThatGoesP1NG** [comment]
Not sure i know how to use that last one...

**Comment by ssborbis** [comment]
??? Did you add an engine like the example I gave?

**Comment by MachineThatGoesP1NG** [comment]
I copied your image and typed in `motorcycle 1000 2000` And it takes me to the main url `https://offerup.com/`

![2022-07-18 23 21 35 ContextSearch Options — Mozill](https://user-images.githubusercontent.com/107629842/179680352-814d92c7-1321-4827-81fd-0a112ee271fc.png)

**Comment by 7peanuts** [comment]
> I copied your image and typed in `motorcycle 1000 2000` And it takes me to the main url `https://offerup.com/`
> 
I guess you use the `Test` to input keywords, it has a bug, use quick menu to search.
#502

**Comment by MachineThatGoesP1NG** [comment]
> > I copied your image and typed in `motorcycle 1000 2000` And it takes me to the main url `https://offerup.com/`
> 
> I guess you use the `Test` to input keywords, it has a bug, use quick menu to search. #502



Ok thankyou so that was the problem....

@ssborbis When i use this it only allows me to use a single search word i can not put for example `motorcycle helmet 1000 2000`.

I really like your first solution what i was thinking is it possible to put a 2nd template below the first you have written? I tried this and it will only run the second template....

I've also tried doubling the code so:


`browser.runtime.sendMessage({
	action: "quickMenuSearch", 
	info: {
		selectionText: searchTerms,
		openMethod: "openBackgroundTab",
		temporarySearchEngine: {
			template: "https://offerup.com/search?radius=10&q=" + searchTerms + "&price_min=" + prompt("Min") + "&price_max=" + prompt("Max"),
			method: "GET"
		}
	}
});

browser.runtime.sendMessage({
	action: "quickMenuSearch", 
	info: {
		selectionText: searchTerms,
		openMethod: "openBackgroundTab",
		temporarySearchEngine: {
		template: "https://sacramento.craigslist.org/search/sss?query=" + searchTerms + "&min_price=" + prompt("Min") + "&max_price=" + prompt("Max"),
method: "GET"
		}
	}
});`

And this work but it gives me 2 minmax windows {which could be useful in some cases} but i want to search multiple sites with the same parameters, sorry that i did not mention that at the beginning. 

Your code just needs some tweaking and i will be able to do this.. I'm trying to learn a little more and am playing around i don't know that i will be able to come up with a solution even though I'm sure it's simple..

**Comment by MachineThatGoesP1NG** [comment]
@ssborbis 

I already had multiple folders set up to do a number of price ranges and that is great but sometimes i would want a very specific price so i figured there had to be a way.. and you did it, Thankyou so much this is very useful to me I use your program everyday for this.

**Comment by ssborbis** [comment]
@MachineThatGoesP1NG 

No prob. Let me know if you need any help expanding on that script.

**Comment by MachineThatGoesP1NG** [comment]
@ssborbis 

Hello my friend so I'm having a issue where i go to search a term and it searches the previously searched term and it will do it with several searches always showing the last one i typed...

I'm guessing the search term in the script needs to be wiped before running again?

**Comment by ssborbis** [comment]
I think I can give you a workaround. It might not be necessary after the next release, because I've found the issue, but "fixing" it might break something else. 

Try adding this line at the beginning of the script

`browser.runtime.sendMessage({action: "updateSearchTerms", searchTerms: searchTerms});`

**Comment by ssborbis** [comment]
The workaround in my previous post appears to be unnecessary using the latest beta. It won't hurt to leave it there, but it can be omitted in any future scripts.

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.40beta/contextsearch_web_ext-1.40rc1.xpi

Can we consider this issue closed? I feel like this general workaround is as good as any built-in multi-variable solution. What is your opinion?

**Comment by MachineThatGoesP1NG** [comment]
Yeah go head and close it (or do i do that?) i think you did a great job...
