### ISSUE TITLE
Disable Autocopy on textarea and input elements

### ISSUE THREAD

**Issue by logusergithub** [ssborbis/ContextSearch-web-ext#510]
It seems to me that Autocopy behaviour is closely related to Quick Menu general options. On 1.39 I don't know if it's a bug or  how to do it, but currently the only way to disable Autocopy from text area and input elements is to unckeck 'Enable searching via popup menu' (not anymore on 1.40b5.xpi).  'Enable on textarea and input elements' is already unckecked.

If it is feasible, it it might be smoother to have separate options of when to use Autocopy (beyond the standard autocopy for selected text) in the advanced settings.
Thanks

**Comment by ssborbis** [comment]
I agree. This is a major annoyance. Fixes are in the development repo. Auto Copy options have been moved to CS Options -> General for the time being.

**Comment by logusergithub** [comment]
It seems to me that on the latest update everything works fine. Thanks
