### ISSUE TITLE
[Request] 'Search Engine Manager': search by 'Description'

### ISSUE THREAD

**Issue by logusergithub** [ssborbis/ContextSearch-web-ext#511]
As the title suggests add an option in 'Search Engine Manager ' panel to search engines based on description input element instead of name. A way to tag installed search engines.  It might also be comfortable if one has many search engines also an option to show folders when searching the engine by name.
Thanks

**Comment by ssborbis** [comment]
Showing the folders / hierarchy is an easy fix. Changes are in the repo.

I'll think on the description filtering

**Comment by logusergithub** [comment]
Thanks. But if it requires effort, it's not worth it considering that it's more of a relative option to manage many search engines (I doubt most will care). I was starting from the fact that aside from generically tagging, some sites use Google search, some strangely don't have yet a search form, and for others I still need to figure out how to set the search parameters. In any case, I already have a list to remember them.

The truth is that I have become addicted to using the Toolbar for opening sites like bookmarks, I am more than comfortable with it and there are no similar alternatives. 
Well, I'm writing it but will deny it if asked (moreover easier said than done): sometimes I think how nice to have a 'spin-off' of ContextSearch web-ext for bookmarks. :-)

**Comment by logusergithub** [comment]
> Would it simply display your bookmarks as tiles menus with subfolders, same as the current CS menus?

Exactly. I imagine it like this:
- an icon showing only the ContextSearch-web-ext Toolbar with the same functionality but for bookmarks.
- same 'Search Engine (Bookmarks) Manager' but manually importing  from browser bookmarks (I don't know if this is feasible with the API and it is not even so necessary but make life easier) and same 'Edit Panel' only with 'Name', 'Icon URI' and 'Form Path'. 

Since it does not have to interact like ContextSearch-web-ext there should be no limits regarding the overall performance based on number of items entered (and for ContextSearch-web-ext the limit is already high).
Any other functions related to an extension that handles bookmarks can be left aside, at most the actually Toolbar search bar could be reused to show a searched bookmark with a dedicated tile\text (totally optional).

Easy to say... I spent more than an hour making a simple AutoHotkey scripts to open selected text in Notepad, Notepad++ and Word via ContextSearch-web-ext App Launcher (and I am still grateful for '{download_url}'. Before it I tried with Python without success), so I certainly don't make requests for new extensions. :-)

**Comment by ssborbis** [comment]
After writing some bookmark code, I remembered why the functionality was removed. The bookmarks API does not allow access to bookmark favicons. To retrieve icons for displaying in CS menus, every bookmark URL would need to be opened in a tab and the favicon retrieved. I suppose it could be done, but it would be a lengthy process for anyone with a lot of bookmarks.

**Comment by logusergithub** [comment]
I currently have disabled favicons in Firefox.
I was thinking about an incremental synchronization (manual when needed) only with 'Name', 'Location' ('Form Path'), 'Tags' ('Description') preserving the already existing bookmarks if in the same folder tree structure (in this case updating only the  'Location').
The 'Icon URI' in the edit panel would not change to set the custom icon as now. A global button to set favicons (`https://www.google.com/s2/favicons?domain=${domain}&sz=${size}` can it be a solution?) in those bookmarks that do not have 'Icon URI' already set. 

But seriously, I just think of it as a friendly chat to how a hypothetical extension could be. :-) Moreover, although it would be a 'static' extension which does not need to interact during Firefox surfing I have my doubts that the current 'Search Engine Manager' panel can support a huge number of inserted elements. Even now I have painstakingly organized bookmark folders without overlapping those with search engines (set in CS) and those without (more than 3000).

In any case, since I sent you my config exported file the search engines have doubled in number, but I also changed the icons to 64x64 using compressed WebP images as the basis for Data URI generator (the result is slightly 'shorter' than the default png Data URI). In the end, the configuration file has been greatly reduced but with no corresponding increase in performance. If it helps, I seem to note that it is the number of engines entered that makes the difference compared to the overall size. Obviously the numbers here are a little bit exaggerated.

**Comment by ssborbis** [comment]
> I have my doubts that the current 'Search Engine Manager' panel can support a huge number of inserted elements

If it matters to you, and you have a ton of search engines, you might speed up the SEM by toggling the manual setting `searchEnginesManagerShowContexts` to false. It hides the context ( audio, image, page .. ) icons from the header row of each node in the tree. I find it gives a performance boost for on my modest pc.

**Comment by logusergithub** [comment]
`searchEnginesManagerShowContexts`

Thanks. I did not know this setting. Indeed there is an improvement when opening options and loading search engines. It's the panel for editing that has slowed down although it still holds up valiantly (a miracle if I have to consider another similar extension I tried at first). When I use it I have the perception that the cause is the auto-save option, it is as if every edit I make there is a constant loading in the same way as when I initially load the search engines from  the options.
After this for the rest:
- Quick Menu, Context Menu or the Toolbar from icon are not affected by the number of search engines (maybe an imperceptible and acceptable delay)
- the real problem are the pages in Firefox that load slower and there is excessive resource demand in about:performance. Again if it still helps, I have noticed using Google or DeepL Translate that the translation is quite slow and this is dependent on CS. Yet I don't understand what interaction is involved here.

That said, and with an even more modest computer, on the main profile I am using a 'light' version with 'less' search engines, but I continue on another profile to finish the work I started. As per the last comment on the Firefox CS page is 'By far the most important extension' (well, after uBlock if if you don't take offense), I love it and don't give a damn if I have any slowdowns. I trust in the next PC I have to buy :-)

**Comment by logusergithub** [comment]
Ah, if it is of interest (on Windows) to anyone but users here know a lot more about it than I do, I insert AutoHotkey scripts for opening text in Word, Notepad, Notepad++. Depending on the language of the OS there is to be careful what you see on the related program window (it took me precisely more than an hour to figure out what to insert after 'WinWaitActive'...). After that I used the AutoHotkey compiler, put the .exe files  in the CS Native App folder and set as example:

```
start Notepad++.exe "{searchTerms}"
C:\Users\Administrator\AppData\Roaming\ContextSearch-webext
```

If everything goes well, the result is this:
[![Notepad.gif](https://i.postimg.cc/xTpTtQ3H/Notepad.gif)](https://postimg.cc/jLNbSG9d)

```
Run, C:\Program Files\...\...\...\WINWORD.EXE /w
WinWaitActive Documento1 - Word
Send, ^v
return
ExitApp
```

```
Run, Notepad
WinWaitActive Senza nome - Blocco note di Windows
Send, ^v
return
ExitApp
```

```
Run, C:\Program Files\Notepad++\notepad++.exe
WinWaitActive new 1 - Notepad++ [Administrator]
Send, ^v
return
ExitApp
```

**Comment by ssborbis** [comment]
I was thinking the other day of making a master file of user-submitted commands. One file that everyone can edit and add their own commands, to help others get set up.

**Comment by logusergithub** [comment]
> I was thinking the other day of making a master file of user-submitted commands. One file that everyone can edit and add their own commands, to help others get set up.

Good idea. As soon as I see it I will copy the post above.  I already look at the one for search engine configuration from time to time trying to learn by examples.

**Comment by ssborbis** [comment]
> [Edit] It makes me wonder what a 'Master file' is now that I think about it. Not a dedicated post, a something like a ReadMe?

Correct. Anyone with a github account can contribute, and it will be available in the main source code repository, along with the readme.

**Comment by rediffusion** [comment]
@logusergithub 
 How did you put the status bar under the address bar?

![status bar](https://user-images.githubusercontent.com/30071027/181077929-9cf5a075-a0b6-454a-a10b-8b9c91acc579.png)

**Comment by ssborbis** [comment]
@logusergithub 

I changed the tooltips in the search engines manager to display descriptions. Hover your mouse over a row to see the description. Not searchable, but between the new hierarchy layout and this, you should be able to find the engine you're looking for.

**Comment by logusergithub** [comment]
@Rediffusion

> How did you put the status bar under the address bar?

I wish I could do such a thing! It's simply the Bookmarks Bar ('Always Show') and I dragged the extension icons onto it:
[![Bookmarks-Toolbar.png](https://i.postimg.cc/25X5Rd3T/Bookmarks-Toolbar.png)](https://postimg.cc/rdxT5r1t)

Also since the last Firefox update everything seems even 'bigger' to me. So I set the default zoom to 90% (text only) and I added this inside userChrome.css for the search box:

```
@-moz-document url(chrome://browser/content/browser.xhtml) {
  #PopupSearchAutoComplete .searchbar-engine-one-off-item[tooltiptext] {
    height: 23px !important;
    background-image: none !important;
    box-sizing: content-box !important;
    margin:0px !important;
    padding:2px !important;
  }
```


> How do I search for a request in a closed or already running [Reverso](https://www.reverso.net/) program. To see how it's translated?

Sorry but I didn't understand the question, is it because you saw the Reverso Context icon? I'll write down some of my settings, maybe there is what you need.
The Quick Menu is only set with 'Mouse: Hold+Left Button' and for text selection. I don't use Reverso Context for translation but for sentences. If possible I try to set 'Template' with 'English--->My language' and the 'Form path' with  'My language--->English'. Like this:

```
http://fanyi.baidu.com/#auto/it/{searchTerms}
http://fanyi.baidu.com

https://www.bing.com/translator/?from=a&to=it&setlang=it&text={searchTerms}
https://www.bing.com/translator/?from=it&to=en

https://www.deepl.com/translator#../it/{searchTerms}
https://www.deepl.com/translator#it/en/

https://translate.google.com/?sl=auto&tl=it&text={searchTerms}%0A&op=translate
https://translate.google.com/?sl=it&tl=en&ucbcb=1

https://libretranslate.com/?source=en&target=it&q={searchTerms}
https://libretranslate.com/?source=it&target=en

https://lingva.ml/auto/it/{searchTerms}
https://lingva.ml/

https://simplytranslate.org/?engine=google&sl=auto&tl=it&text={searchTerms}
https://simplytranslate.org/?engine=google&sl=it&tl=en

https://translate.yandex.com/?text={searchTerms}&lang=en-it
https://translate.yandex.com/?text=&lang=it-en

+

(Reverso Context inside 'Dictionary' folder)
https://context.reverso.net/traduzione/italiano-inglese/{searchTerms}
https://context.reverso.net
```

I also put you the icons I use for translations and dictionaries. On Mycroft Project there are many examples for Context Reverso. While I'm at it, I still haven't thanked @ssborbis for putting the 'CS icons' right on the Mycroft Project site (thanks as usual). <a href="https://privfile.com/download.php?fid=62e070b094782-MTQwMjM=">Translate-Dictionary Icons</a>


@ssborbis

> I changed the tooltips in the search engines manager to display descriptions. Hover your mouse over a row to see the description. Not searchable, but between the new hierarchy layout and this, you should be able to find the engine you're looking for.

Thanks. I enable manually "showDescriptionsInTooltips": true (is that it?). If I hover the mouse over a tile above the Quick Menu or Toolbar I actually see the description as well. On the SEM I only see the name of the search engine.
The 'Search by Description' would be intended to select a fair number of search engines within a large number of search engines. Impossible to do manually without any references. But that's okay, it is an ulterior useful features. I already have a dedicated list. But what is 'the new hierarchy layout', did I miss something useful?
Ah, I also noticed that by doing the search now the folders are visible. &#128077;

**Comment by ssborbis** [comment]
> Thanks. I enable manually "showDescriptionsInTooltips": true (is that it?). If I hover the mouse over a tile above the Quick Menu or Toolbar I actually see the description as well. On the SEM I only see the name of the search engine.

Hmm... In the SEM, the default behavior should be to show descriptions, if they exist, and titles when they don't. The page will probably need refreshing to see descriptions that have changed. You might be running into an issue where older descriptions aren't showing. For testing, could you edit a description for a known engine, refresh the options page, and see if it shows up? If so, that tells me what to do for a fix.

**Comment by logusergithub** [comment]
I inserted in the 'Description' input element 'Here the descriptions' inside DuckDuckSearch' and restarted the browser: here the pictures:

[![Duck-Duck-Go.png](https://i.postimg.cc/d1Wkt7nt/Duck-Duck-Go.png)](https://postimg.cc/34vJtxPP)

[![Toolbar.png](https://i.postimg.cc/pL168kTD/Toolbar.png)](https://postimg.cc/YvYRB6Q9)

[![SEM.png](https://i.postimg.cc/NM8DNxgC/SEM.png)](https://postimg.cc/1ntDXwVD)

**Comment by ssborbis** [comment]
@logusergithub 

I'm not quite sure why we're seeing different results, but I have a hunch, and I've updated the development branch with a possible fix if you're in a position to test.

**Comment by ssborbis** [comment]
BTW, I love your qm layout / icons

**Comment by logusergithub** [comment]
> I've updated the development branch with a possible fix if you're in a position to test.

As usual I have on about:debugging this alert: 'does not contain a valid manifest'. I don't know where I am wrong.


> BTW, I love your qm layout / icons

Thanks. The folders in the QM\Toolbar are the exact replica of bookmarks, while the CM is organized to simulate 'Open With' menu extension  plus the subfolders and search engines for the common search (External Apps, Maps, Multiple Search, Reverse Image Search, Site Search, Translate). It is simply a dark menu with:

```
.tile { width:28px; }
.tile { height:28px; }
#titleBar { display:none !important; }
```

If you need it I also have all the search engine and folder icons 256x256 (1913\225 work in progress as a hobby). But as I wrote I use now WebP for Data URI generator based on 64x64 'Bilinear' (better results as size\icon converted) XnView conversion settings. Here a comparison (the gain that may make sense on large numbers depends on the starting icon):

Original .ico 256x256
<a href="https://privfile.com/download.php?fid=62e0a8b493110-MTQwMjU=">Encyclopedia Of Life Sciences</a> 

CS imported .ico to PNG 64x64
[![Encyclopedia-Of-Life-Sciences.png](https://i.postimg.cc/tC4V1GMm/Encyclopedia-Of-Life-Sciences.png)](https://postimg.cc/QVvMPwsp)

WebP 64x64
[![Encyclopedia-Of-Life-Sciences.webp](https://i.postimg.cc/1X54NDJN/Encyclopedia-Of-Life-Sciences.webp)](https://postimg.cc/7GdqFJvx)

**Comment by ssborbis** [comment]
> As usual I have on about:debugging this alert: 'does not contain a valid manifest'. I don't know where I am wrong.

How exactly are you loading?

This is what I do:
1.download the source code (ContextSearch-web-ext-master.zip)
2.extract
3.go to about:debugging
4.load temporary addon
5.browse to ContextSearch-web-ext-master/src and select any file ( or manifest.json to be sure )

Keep in mind I'm using the developer edition of Firefox, so that might account for some differences.

**Comment by logusergithub** [comment]
> How exactly are you loading?

Well, I forget about point 2.... :-) I checked and now it works.
