### ISSUE TITLE
Is there a way to add the search engin from https://parse.bqrdh.com/smart

### ISSUE THREAD

**Issue by runningcheese** [ssborbis/ContextSearch-web-ext#512]
i DID a lot of research in "Issues".

but it just not happening, could you please help me up, thanks in advance.

**Comment by ssborbis** [comment]
I have no idea what that pages is supposed to do. I can't read it. You can try dispatching the change event.

```javascript

document.querySelector('input').value = '时长';
document.querySelector('input').dispatchEvent(new Event('change'));
document.querySelector('.ant-input-search-button').click();
```

**Comment by 7peanuts** [comment]
I modified it slightly, maybe the code is a bit bloated :joy:

```js
(async() => {
  let input = document.querySelector('.ant-input.ant-input-lg');
  input.focus();
  input.value = searchTerms;
  input.dispatchEvent(new Event("input"));
  input.dispatchEvent(new Event("change"));
  await new Promise(r => setTimeout(r, 200));
  document.querySelector('.ant-input-search-button').click();
})();
```
不过我随便找了一个视频试了下，没有去掉 logo

**Comment by ssborbis** [comment]
Is it working?

**Comment by runningcheese** [comment]
yeah, it's working!
thanks @ssborbis @7peanuts

**Comment by runningcheese** [comment]
What about this site? https://html2pdf.app/

i have try the code below, but not working correctly.

`
(async() => {
  let input = document.querySelector('.form-control');
  input.focus();
  input.value = searchTerms;
  input.dispatchEvent(new Event("input"));
  input.dispatchEvent(new Event("change"));
  await new Promise(r => setTimeout(r, 200));
document.querySelector('.btn.btn-primary.m-t-24').click();
})();
`

**Comment by ssborbis** [comment]
I'm getting good results with just this. I need to click the prompt to save or download, but it's working fine in FF

```javascript
(async() => {
let input = document.querySelector('.form-control');
input.focus();
input.value = "http://example.com";
document.querySelector('.btn.btn-primary.m-t-24').click();
})();
```

What browser are you on?

**Comment by runningcheese** [comment]
> What browser are you on?

Firefox, firefox is my favorite browser.

**Comment by runningcheese** [comment]
@ssborbis 

> (async() => {
> let input = document.querySelector('.form-control');
> input.focus();
> input.value = "http://example.com";
> document.querySelector('.btn.btn-primary.m-t-24').click();
> })();

i have just try this code in chrome, but it seems not working either.
