### ISSUE TITLE
Is there a way to get a part of the page url?

### ISSUE THREAD

**Issue by runningcheese** [ssborbis/ContextSearch-web-ext#513]
As we know that {searchTerms} is stand for page url when you search a website.

but, is there a way to get a part of the page url?

for example:

https://space.bilibili.com/330821611/video

i would like to get the number 330821611，not the full url.

this picture is what i am trying to add.

<img width="758" alt="iShot2022-07-21 11 34 44" src="https://user-images.githubusercontent.com/4476264/180124803-dd6a2b70-fa23-4f43-8e8d-2a7e21eb99f8.png">

I know that it will be complicated, so thanks in advance.

**Comment by runningcheese** [comment]
@ssborbis 
that is awesome, man!!!

**Comment by runningcheese** [comment]
@ssborbis 
what about this one? 
to match the second number 1445680654
https://space.bilibili.com/11499954/favlist?fid=1445680654

**Comment by ssborbis** [comment]
Probably something like:

`/.*=(\d+)$/$1/g`


Plenty of resources out there on regex matching.

https://regex101.com/

**Comment by runningcheese** [comment]
So, the ContextSearch-web-ext regex is the same as normal regex, i thought it's different, thanks anyway!

**Comment by runningcheese** [comment]
and i am wondering what is the time next realese comes up? thanks for your great work!

**Comment by ssborbis** [comment]
if you're on Firefox, you can install the release candidate I just signed. 

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.40beta/contextsearch_web_ext-1.40rc1.xpi

**Comment by ssborbis** [comment]
1.41 is live

**Comment by runningcheese** [comment]
> 1.41 is live
@ssborbis 

It's a great improvement, thanks for your kind work!
And i have made a full introduction  to my following fans!
Hang in there！
