### ISSUE TITLE
addon uses great amounts of storage space

### ISSUE THREAD

**Issue by sthalik** [ssborbis/ContextSearch-web-ext#514]
After using the addon for a while it starts using extreme amounts of disk space, despite its simple purpose of displaying a few context menu entries.

```console
-rw-r--r-- 1 sthalik None 2.0G Jul 22 09:44 3647222921wleabcEoxlt-eengsairo.sqlite
% sqlite3 3647222921wleabcEoxlt-eengsairo.sqlite
select count(*) from object_data;

217373
```

**Comment by ssborbis** [comment]
That's 200kb, correct? For this addon, that's pretty normal. The icons used to display search engines are cached within the addon's user preferences.

**Comment by sthalik** [comment]
That's two gigabytes on disk for the database, and 200K total *entries* in `object_data`. I only have 13 search engines installed.

**Comment by ssborbis** [comment]
Yeah, that's very unusual. I have hundreds of engines with loads of custom scripts and icons, and my .sqlite is 570kb.

What size file do you get if you export your CS config? 2GB?

**Comment by sthalik** [comment]
The exported config is 46 KB in total. I'm attaching a version with the search history removed.

[ContextSearchOptions_2022-07-22_163322.json.txt](https://github.com/ssborbis/ContextSearch-web-ext/files/9169367/ContextSearchOptions_2022-07-22_163322.json.txt)

**Comment by ssborbis** [comment]
Can we assume the history wasn't adding 2GB? Did you clear the history through CS options and check the size of the db again?

46KB seems right. Maybe re-install the addon and import your recent export. I suppose it's possible the db got corrupted somehow?

**Comment by sthalik** [comment]
> Can we assume the history wasn't adding 2GB? Did you clear the history through CS options and check the size of the db again?

I only removed the search history for privacy reasons. There's not that much of it.

> I suppose it's possible the db got corrupted somehow?

sqlite is ACID complaint. I'm thinking more of a logic error in the addon. Is this useful to you?

```console
sqlite> select a.*, b.file_ids, b.key from object_store a LEFT JOIN object_data b ON a.id == b.object_store_id limit 10;
1|0|storage-local-data|||0274181363:411
1|0|storage-local-data|||0274181363:711
1|0|storage-local-data|||02741813641311
1|0|storage-local-data|||02741813641411
1|0|storage-local-data|||02741813641611
1|0|storage-local-data|||027418136:8411
1|0|storage-local-data|||02741813729711
1|0|storage-local-data|||02741813738611
1|0|storage-local-data|||02741813988211
1|0|storage-local-data|||02741813992111
```

Other than that, are there any particular queries on the oversized database that could be useful for the purpose of debugging this issue?

**Comment by ssborbis** [comment]
> Other than that, are there any particular queries on the oversized database that could be useful for the purpose of debugging this issue?

I've never looked at the database directly. If you open the CS options page, and the console, you can try this command to see the sizes of the javascript objects that would be stored in the db. That might indicate something. If not, I'm at a bit of a loss.

`for (key in userOptions) console.log(key, JSON.stringify(userOptions[key]).length);`

**Comment by ssborbis** [comment]
BTW, what CS version, OS are you on?

**Comment by sthalik** [comment]
You're right. This profile is 3 years old and it's most likely to having been caused by a Firefox bug dealing with addon setting serialization. Thank you for your time.

**Comment by ssborbis** [comment]
I hope you're right about the FF bug. I had seen older bugzilla reports ( 4 years ago ) submitted for the same condition; localstorage using 2GB in some extensions. If it happens again, let me know. I'll see about getting your db and digging through it for answers.
