### ISSUE TITLE
ISSUE: Cannot add a new search engine manually 

### ISSUE THREAD

**Issue by twisteros** [ssborbis/ContextSearch-web-ext#515]
1. I went to Search Engines tan
2. Click Add and enter an engine name
3. Fill Template, Icon URI and Form Path fields

![image](https://user-images.githubusercontent.com/18228956/180528480-979ddd86-47de-443d-bdea-4e57e8d0d3f5.png)

4. Right click on another engine on the list and select Edit
5. Go back to the newly created engine and notice all values vanished

![image](https://user-images.githubusercontent.com/18228956/180535199-c31d1db9-6de7-4024-bcf0-5e853a5773e4.png)

Firefox v102.0.1
ContextSearch v1.8.1

**Comment by ssborbis** [comment]
Woah, that is an ANCIENT version of ContextSearch. Is there any reason why you haven't updated?

**Comment by ssborbis** [comment]
I had to double-check my old submissions. Are you using the "lite" version? That was discontinued 4 years ago. I forget if that version has a button to export your config. If it does, I'd export it and install the latest version of contextsearch ( 1.39 ) and import your config. Don't uninstall the older version until you get your settings back. If the import doesn't work, or if there's no export button, I'll try to walk you through the update.

**Comment by twisteros** [comment]
Yes, that's the lite version. Firefox says I'm already on the latest.
I guess that's the reason I'm still using it. 
Anyway, I've installed the latest version.
It imports nicely. However I'm overwhelmed by number of settings. 
Do you know why I can't add a new search engine in the old version?

**Comment by ssborbis** [comment]
> It imports nicely. However I'm overwhelmed by number of settings.

There is a lot more going on, but I can help you through setting it up how you want to use it.

> Do you know why I can't add a new search engine in the old version?

Probably an old bug. It's been so long, I don't think I can give you any specifics.

**Comment by twisteros** [comment]
I just left the default ones and it's been working fine so far. 
Might it be helpful to add a Basic/Advanced settings toggle?
With the basic one being default and showing  essential settings only. 
Anyway, thank you for your help.

**Comment by justsome12** [comment]
> I just left the default ones and it's been working fine so far. Might it be helpful to add a Basic/Advanced settings toggle? With the basic one being default and showing essential settings only. Anyway, thank you for your help.

I am using it since ages and grew with it, never thought about it being complicated, but nowt that you mention it... it really is an expert addon, compared with most others I have there are no settings at all or maybe a hand full of checkboxes. I am using 54 (yes I counted) addons at the moment and nothing is as deep and customizable as my favorite of them: this (only coming close I think is ublock with both expert modes activated).

**Comment by justsome12** [comment]
@ssborbis  do you have data of how the addon is used? e.g. which functions are used the most/the least?

**Comment by ssborbis** [comment]
@justsome12 

No. I don't collect any usage info for this addon. Privacy has always been a priority.
