### ISSUE TITLE
BUG v1.41: Click on search engine in rapid menu don't work anymore

### ISSUE THREAD

**Issue by DUN-Cosmos** [ssborbis/ContextSearch-web-ext#518]
Since last update: 1.41

When I open rapid menu, the click on a search engine don't do anything.
The copy, option, expend menu button still work.

I rollback to 1.39 and all work again, click on a search engine in rapid menu open new tab with the search.

**Comment by ssborbis** [comment]
can you send me your config export?

**Comment by ssborbis** [comment]
Also, what OS / browser are you on?

**Comment by DUN-Cosmos** [comment]
Here: [ContextSearchOptions_2022-07-26_132721.json.txt](https://github.com/ssborbis/ContextSearch-web-ext/files/9190180/ContextSearchOptions_2022-07-26_132721.json.txt)

I use FireFox 102.0.1 on Win7
