### ISSUE TITLE
Request about 'Close menu when typing' Option

### ISSUE THREAD

**Issue by lucky80** [ssborbis/ContextSearch-web-ext#521]
Hello.

First of all, thank you for adding the "Close menu when typing" option to this version.

I'm writing because there seems to be a bug while using that option.

As in the first image, if I double-click the text in the text box to specify a block, or if the cursor is located on the right side of the block by specifying a block before and after the word, the 'Close menu when typing' option works normally.

But like in the second image, if I drag the word in the text box from the back to the front, that is, from right to left, the cursor will be on the left side of the block. In this case, 'Close menu when typing' is not working normally.

Please check and review this part.

Have a good day
![Cap 2022-07-29 15-24-04-627](https://user-images.githubusercontent.com/1419119/181697017-bda0bd22-a810-4faf-a44f-6eb7a0531cd2.png)
![Cap 2022-07-29 15-24-14-952](https://user-images.githubusercontent.com/1419119/181697030-35bb3ed9-1ea4-493d-bb68-db705ff3a6cd.png)
!

**Comment by ssborbis** [comment]
Got it. Looks like an old typo causing issues. I'll do some testing on the repercussions of fixing it, as it might have some cascading effects. I'll let you know.

**Comment by ssborbis** [comment]
I believe this is fixed. You can test out this beta before the official release ( assuming you're on firefox ) https://github.com/ssborbis/ContextSearch-web-ext/releases/download/v1.42rc1/contextsearch_web_ext-1.42rc1.xpi

**Comment by lucky80** [comment]
Thank you for the correction and development.
However, I am using a Chrome-based browser.
I'll be waiting for the official release.
