### ISSUE TITLE
[BUG] Error searching for non-English letters in the search bar

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#523]
As shown in the figure, the search for Chinese characters gives incomplete results, and punctuation marks cannot be searched.

![20220730111455](https://user-images.githubusercontent.com/82173614/181870450-a45e9de9-17dd-4189-90e3-fad56c3ec465.gif)
![20220730111531](https://user-images.githubusercontent.com/82173614/181870454-e06712fb-4803-46a0-a12f-f21c6c4ac394.png)

**Comment by ssborbis** [comment]
In regards to the punctuate, you seem to have the `ignore punctuation` button enabled on the Find Bar ( the `!` symbol )

I'm not sure about the incomplete results. The library I'm using (mark.js) might not be able to see all the matches the built-it search can, or it may be a matter of finding the right combination of Find Bar options to enable/disable, or maybe there's a conflict with character encoding. I'll take a look.

**Comment by 7peanuts** [comment]
> In regards to the punctuation, you seem to have the `ignore punctuation` button enabled on the Find Bar ( the `!` symbol )
> 
Indeed, I forgot about this option 😂
I think I know why, because I have exactly match turned on 😣
Thank you so much, I wasted a few minutes of your time again 🤪

**Comment by ssborbis** [comment]
No worries.
