### ISSUE TITLE
Something started to appear at the top of the popup.

### ISSUE THREAD

**Issue by stserkan1** [ssborbis/ContextSearch-web-ext#525]
![image](https://user-images.githubusercontent.com/104198046/182817757-8dbfed20-50db-4db3-bb68-850c1a5eef9c.png)

How can I disable this?

**Comment by ssborbis** [comment]
open the quick menu, then the layout editor and uncheck the contexts toolbar

If you don't have the layout editor tool enabled, you can open it with a shortcut ( CS Shortcuts -> quickMenuEdit ). If it's enabled already, the default shortcut is Ctrl-Alt-e. The qm needs to have focus for the shortcut to work. I've noticed, without a search bar, the qm can be difficult to get in focus, even if you click in blank space. I'll look into that.


![Peek 2022-08-04 12-37](https://user-images.githubusercontent.com/24310997/182915089-ed29d25a-00d6-4063-9406-6a580bd23b34.gif)

**Comment by ssborbis** [comment]
I'm adding an option to options page to make it easier.
![contexts_toobar](https://user-images.githubusercontent.com/24310997/182937756-3d0f58ad-80d8-45e1-a76d-66a241b853a0.jpg)

**Comment by ssborbis** [comment]
Assuming you're on Firefox, you can try https://github.com/ssborbis/ContextSearch-web-ext/releases/download/v1.42rc1/contextsearch_web_ext-1.42rc1.xpi

**Comment by stserkan1** [comment]
Using g chrome. I disabled it. Thank you.
 
![image](https://user-images.githubusercontent.com/104198046/183361718-a747e953-a915-476a-bed5-5be7ae47eb0f.png)

**Comment by ssborbis** [comment]
No prob
