### ISSUE TITLE
[BUG] Access key for the ContextSearch Menu doesn't Work?

### ISSUE THREAD

**Issue by runningcheese** [ssborbis/ContextSearch-web-ext#526]
1. The Access key for the ContextSearch Menu seems not working？

<img width="965" alt="iShot2022-08-05 10 20 55" src="https://user-images.githubusercontent.com/4476264/182987933-ac04a92b-185a-4de8-ba23-2af014f061a3.png">

and nothing happen here.

<img width="1121" alt="iShot2022-08-05 10 17 12" src="https://user-images.githubusercontent.com/4476264/182988052-808f2b56-51b8-488f-82f0-9003a8308167.png">

2. is it possible to make a hotkey combine with modifier key, such as "ctrl+alt+o" to launch chrome browser.

<img width="829" alt="iShot2022-08-05 10 19 50" src="https://user-images.githubusercontent.com/4476264/182988744-405e5f82-86c9-4e68-a66a-b7324ed037d4.png">

Thanks in advance.

**Comment by ssborbis** [comment]
It looks like the access key only works when NOT using the contextual layout. I'll see about adding it. The context menu gets a bit messy when there are multiple contexts for the current selection ( possibly submenus like PAGE, LINK, etc ).

> is it possible to make a hotkey combine with modifier key, such as "ctrl+alt+o" to launch chrome browser.

Not currently. In this addon's backend code, there's a distinction between shortcuts ( keys + modifiers ) and hotkeys ( keys only ). Currently, hotkeys intended to launch search engines, or in this case, app engines, are a single key only. It may take substantial work to allow key + modifier (shortcuts) to be used. I'll look into it, but no promises.

**Comment by runningcheese** [comment]
Thanks for your kind reply! @ssborbis

**Comment by ssborbis** [comment]
I'm going to reopen this issue so I don't forget. I'll close it when I get a fix into the repository.

**Comment by ssborbis** [comment]
Please try https://github.com/ssborbis/ContextSearch-web-ext/releases/download/v1.42rc1/contextsearch_web_ext-1.42rc1.xpi

**Comment by runningcheese** [comment]
Wonderful!
But the access key should move to  the right side.

<img width="871" alt="iShot2022-08-07 10 30 08" src="https://user-images.githubusercontent.com/4476264/183272462-32ebcf80-599b-43f9-bc1c-30c2b9ac939d.png">

**Comment by ssborbis** [comment]
> But the access key should move to the right side.

Oh, is that the common standard? If so, I'll move it. I've never really taken notice.

**Comment by runningcheese** [comment]
> Oh, is that the common standard? If so, I'll move it. I've never really taken notice.

Yes! Page, Link, Selection, Image, Frame, all the same.
