### ISSUE TITLE
How to disable shortcuts in the text input area

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#527]
When typing in text box, single-key shortcut will be triggered, such as the number key 2.

![20220805204707](https://user-images.githubusercontent.com/82173614/183093943-8a8a1d88-6ae7-4e0e-b170-947b0a3d9f46.jpg)

**Comment by ssborbis** [comment]
Fix in the dev branch going up now.

**Comment by ssborbis** [comment]
Please try https://github.com/ssborbis/ContextSearch-web-ext/releases/download/v1.42rc1/contextsearch_web_ext-1.42rc1.xpi

**Comment by 7peanuts** [comment]
1.42 works well 😍
