### ISSUE TITLE
[Request] Add shortcut key for menu item "Add to ContextSearch"

### ISSUE THREAD

**Issue by wordpure** [ssborbis/ContextSearch-web-ext#529]
1.42 Added shortcut keys for search-related menu items, but the menu item "Add to ContextSearch" of the search box does not have it. I hope to add one to it.

![图片](https://user-images.githubusercontent.com/68013962/183376014-afe476f8-deeb-4979-b131-e5af4880d18d.png)

**Comment by ssborbis** [comment]
Got it. Changes will be in the next release.

**Comment by ssborbis** [comment]
Fix should be live in 1.42.1+

**Comment by wordpure** [comment]
Great work.

But the default shortcut &C of ContextSearch is duplicated with the browser menu item - Copy (&C), we have to press &C twice to trigger the menu item of ContextSearch.

![图片](https://user-images.githubusercontent.com/68013962/184544895-e397f6c7-4aff-4188-bfef-54b19449bffd.png)

![图片](https://user-images.githubusercontent.com/68013962/184544953-397d79db-c020-4d74-b921-41bbb35a3521.png)

Is it possible to switch to a key that is easier to click but less likely to conflict with the existing menu items, for example, &A?

![图片](https://user-images.githubusercontent.com/68013962/184545090-0a6965af-a2b4-4dd2-9401-af4c2e47cfb0.png)

**Comment by ssborbis** [comment]
> Is it possible to switch to a key that is easier to click but less likely to conflict with the existing menu items, for example, &A?

I think you're right in that the default should be something other than a character already used in the default menu. Since the user can change it, it's not exactly a big deal, but I'll swap it for `Z` maybe.

**Comment by wordpure** [comment]
Yes, `Z` does work better than `A` as the default shortcut. I switched to A as the trigger key for Context Search because another extension was already using `Z`.
