### ISSUE TITLE
Is there a way to add the contextmenu to photopea.com？

### ISSUE THREAD

**Issue by runningcheese** [ssborbis/ContextSearch-web-ext#535]
Here is the offical API：https://www.photopea.com/api/

but when i use

`https://www.photopea.com/#{%22files%22:[%22https://tva1.sinaimg.cn/large/7a6a15d5gy1g4rjevu5p2j209y05m3z2.jpg%22]}`

it seems not working.

thanks in advance!

<img width="1304" alt="iShot2022-08-17 17 10 23" src="https://user-images.githubusercontent.com/4476264/185081186-580b6431-5f3b-4d04-ad2c-e78eabb784fa.png">

**Comment by ssborbis** [comment]
What is your current template?

**Comment by ssborbis** [comment]
I assume you got this sorted out? If not, I'll reopen
