### ISSUE TITLE
[Help] CSS:  Toolbar\Quick Menu

### ISSUE THREAD

**Issue by logusergithub** [ssborbis/ContextSearch-web-ext#536]
Hi,
I'm messing around a little bit with styles and doing pretty poorly. Currently this is what I've put in:

<details>
:root { 
--background: #2b2a33;
--tools-color: #c0c0c0;
--folder-color: #708090;
--folder-color-singlecolumn: unset;
--folder-label-color: #c0c0c0;
--folder-label-color-singlecolumn: #ffffff;
/* --border: #3A3946; */
--border: unset;
--hover: rgba(128, 128, 128, 0.5);
--selected: white;
color: #ffffff;
}

#quickMenuElement {
max-width: 280px;
min-width: 280px;
}

.tile {
background-color:unset;
border-radius: 5px;
margin: 1px;
width: 26px;
height: 26px;
}

.tile.singleColumn {
background-color: unset;
height: 17px;
font-size: 8pt;
max-width: 274px;
min-width: 274px
}

.tile.singleColumn[data-type="folder"] {
background-color:unset;
}

#searchBar {
background: #1c1b22;
border: none;
}

#searchBar:focus {
border: 0px;
}

#suggestions {
border: none;
}

#titleBar {
display: none !important;
}

.CS_resizeWidget {
display: none;
}
</details>

Unless I (probably) missed some options, one of the goals is to avoid width resizing respectively:
- Toolbar and Quick Menu when I switch Grid\List views;
- Quick Menu when a folder contains less search engines than the maximum number of search engine icons per row.

More or less I solved with max-width\min-width, but I have a 'feeling' that it can be done better, also from the following image if you look at the 'Options' and 'Close' icons there is a slight offset:

[![Great-Extension.gif](https://i.postimg.cc/1zBtpJxK/Great-Extension.gif)](https://postimg.cc/PLLTHb5L)

Lastly, I did not understand how to:
- disable the highlighted text (#0078d7) in the Toolbar (something like "quickMenuSearchBarFocus"?;
- if feasible set in 'List' view the color of the folders limited however only to the icon.

PS: not CSS. Is it possible to tell CS not to remember the folders where I temporarily set the 'List' view and then forgot to put it back as it is by default?

Thanks.

**Comment by ssborbis** [comment]
> More or less I solved with max-width\min-width, but I have a 'feeling' that it can be done better, also from the following image if you look at the 'Options' and 'Close' icons there is a slight offset:

If you're interested, I can add your style to the styles folder ( logusergithub.css or something ) and you can maintain the file for others to use as well.

> disable the highlighted text (#0078d7) in the Toolbar (something like "quickMenuSearchBarFocus"?;

Unless you disable `General -> History -> Display the last used search terms in the search box` the text will be highlighted. I can throw in a hidden option for you, though.

> if feasible set in 'List' view the color of the folders limited however only to the icon.

I read this a few times, but I don't quite understand.

> PS: not CSS. Is it possible to tell CS not to remember the folders where I temporarily set the 'List' view and then forgot to put it back as it is by default?

Currently, it always remembers. I'll see about an option.

**Comment by logusergithub** [comment]
Sorry for the late reply, but I had to buy a new PC, the previous one abandoned me with bad timing. Good thing is that now I no longer have problems with the slowdown in loading tabs even with a huge number of search engines (even all settings panels has improved in speed).

> If you're interested, I can add your style to the styles folder ( logusergithub.css or something ) and you can maintain the file for others to use as well.

That's fine by me, it's simply a color adjustment to match Firefox dark mode without borders and resizing grid\list. The 'feeling' referred to whether I choose the right CSS to avoid resizing (maybe there was some parameter more dinamic like 'min-content' that worked better, I just go by trial and error).
I didn't look much into it but in any case max-width\min-width parameters will still need to be adjusted based on own configurations (number of search engines per row) or parameters in about:config like "layout.css.devPixelsPerPx". Well, for now I only know that with the new PC I went from 274px to 275px.

> Unless you disable `General -> History -> Display the last used search terms in the search box` the text will be highlighted. I can throw in a hidden option for you, though.

If I remember well it was already disabled, but seems to me that something has happened in the meantime, now that I have reopened the advanced options the 'SearchBarSelect' item existed before or was it added in the last update? In any case thank you.

> I read this a few times, but I don't quite understand.

I'll try to explain better with the image, if I'm not mistaken currently the background color when set covers the entire row along with the text (but that's really a matter of liking):

[![CSS-Folder.png](https://i.postimg.cc/pTcCWZLP/CSS-Folder.png)](https://postimg.cc/gXR843h7)

> Currently, it always remembers. I'll see about an option.

Thanks. An option to choose whether or not to remember when switching to a non-default mode that is grid or list by surfing through folders seems like an improvement to me.
For my preferences it currently reminds me of Firefox bookmarks in the sidebar whose folders remain expanded. Fortunately I found the uc.js 'AutoCloseBookMarkFolder' that solves this behavior.

**Comment by ssborbis** [comment]
> if I'm not mistaken currently the background color when set covers the entire row along with the text (but that's really a matter of liking)

Ok, I see what you're trying to do. I don't think it's possible with the way the list view is currently displayed. The icon isn't a separate element that can have it's own colors, borders, etc. 

> An option to choose whether or not to remember when switching to a non-default mode that is grid or list by surfing through folders seems like an improvement to me.

`saveMenuDisplayMode` is in the dev branch for testing. It will be in the next release ( default=true ) so just disable it to get what you're wanting.

**Comment by logusergithub** [comment]
> The icon isn't a separate element that can have it's own colors, borders, etc.

I assumed that, but honestly it's fine as it is on second thought, I've tortured the CS (trial and error) interface enough that if it could it would appeal to Amnesty. At most I can use transparency.

> `saveMenuDisplayMode` is in the dev branch for testing. It will be in the next release ( default=true ) so just disable it to get what you're wanting.

Just tried it on a new profile and everything seems ok, thanks! Please send the CV for the CEO position at Microsoft...
