### ISSUE TITLE
1.42.2 Context Menu search the entire folder Bug

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#538]
Unable to save the Search Entire Folder option.

When there are multiple search engines in a folder that use different elements, using Search All will open all search engines, not just the ones shown in the right-click menu.

If the search element is not text, such as an image or a link, then will get blank search terms.

This problem occurs on Chromium, where the option can be saved on Firefox, but it doesn't show up in the context menu.

![-gif-2](https://user-images.githubusercontent.com/82173614/185789241-773dc04a-a6d0-46fb-b60b-083e00068156.gif)

**Comment by ssborbis** [comment]
Looks like there are several separate issues happening here. I have some fixes posted to the development branch for testing.

**Comment by ssborbis** [comment]
See if this is fixed in new release 1.43

**Comment by 7peanuts** [comment]
V1.43 

Unable to save the Search Entire Folder option on FF, maybe. Chrome works well.

On Chromium 86.0.4240.198, I don't get a response when I copy `Google Site Search`, but I end up with a lot more duplicate engines, and cannot delete them.

This problem has occurred once a long time ago, and it has happened again today.

![-gif](https://user-images.githubusercontent.com/82173614/187018387-e9afb6e8-4a49-4670-8332-038bc7bc15b6.gif)

I imported the configuration into another browser and was unable to remove these duplicate engines.

Here's the file I'm having trouble with.
[CSOptions_2022-08-27.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/9437440/CSOptions_2022-08-27.zip)

**Comment by ssborbis** [comment]
> Can I delete them directly on the quick menu?

You should be able to if you enable `allowDeleteEnginesFromTileMenu` and use the layout editor tool to edit the menus. Then drag the tiles to the `X` that should be at the bottom of the menu.

**Comment by 7peanuts** [comment]
> You should be able to if you enable `allowDeleteEnginesFromTileMenu` and use the layout editor tool to edit the menus. Then drag the tiles to the `X` that should be at the bottom of the menu.

It's no use. It's still there after refresh.

**Comment by ssborbis** [comment]
That will work. I'm looking into the root issue now. I should have a fix for the next release.

Thanks for the bug report

**Comment by 7peanuts** [comment]
v1.43
Don’t know why the `search all` can’t work anymore.

![-gif-](https://user-images.githubusercontent.com/82173614/188045650-813f0a2b-33a1-4f8a-a0bf-92fc1ed800e1.gif)

**Comment by ssborbis** [comment]
That's odd. I just tested on FF and Chromium, and it's working. Is the the same for all folders / engines?

**Comment by ssborbis** [comment]
I checked again. It's failing on PAGE and FRAME contexts. I'll take a look.

**Comment by ssborbis** [comment]
Possible fix in the development branch
