### ISSUE TITLE
Bookmarklets scripts can't use the instant search string variables

### ISSUE THREAD

**Issue by zichenw** [ssborbis/ContextSearch-web-ext#539]
text in the input box not assigned searchTerms variables

![chrome_ItvZhz3aUS](https://user-images.githubusercontent.com/19666814/186912450-bdc8bc54-fada-4969-beeb-031d1d82ddee.png)
![searchterm](https://user-images.githubusercontent.com/19666814/186912461-9ee929e1-cab1-4b46-b932-4be622dfd7b3.gif)

**Comment by ssborbis** [comment]
fix in new release 1.43

**Comment by zichenw** [comment]
@ssborbis Tanks,it work well
