### ISSUE TITLE
Relax Template format restrictions

### ISSUE THREAD

**Issue by wordpure** [ssborbis/ContextSearch-web-ext#542]
I want to use ContextSearch to open links in Firefox sidebar, but when I create a new search engine, I find that only filling in `{searchTerms}` in the Template will report an error.

Is it possible to consider using `{searchTerms}` as Template when the context object does not contain `selection`?

![图片](https://user-images.githubusercontent.com/68013962/187603241-97aead6e-ea8f-4177-a26c-d88a392d95a7.png)

**Comment by ssborbis** [comment]
It may report an error, but it should work fine. I'll double, check though.

**Comment by ssborbis** [comment]
You're probably having issues because the default encoding is set to UTF-8. Choose `no encoding` from the edit modal, and you should be ok.

**Comment by wordpure** [comment]
After modifying the coding to `no encoding` I solved the problem, thanks for your reply.
