### ISSUE TITLE
Display text search Engines when links triggered

### ISSUE THREAD

**Issue by wordpure** [ssborbis/ContextSearch-web-ext#543]
Context Search supports pressing Ctrl to switch the trigger object of Links to url or text, but when I trigger the quick menu of the link, it will not display the text search engine.

Whether it is possible to display text search engines when triggering links. Or even further, depending on the settings of General, and whether the user pressed Ctrl, intelligently switch the filter to 'selection' or `link`?

![图片](https://user-images.githubusercontent.com/68013962/187605509-322bba60-bb4d-4bff-9f33-29ac02cfa56c.png)

![图片](https://user-images.githubusercontent.com/68013962/187605449-17c4c0ef-b3e7-42c3-bcf6-8260e2b650a2.png)

**Comment by ssborbis** [comment]
Makes sense. I'll look into it.

**Comment by ssborbis** [comment]
Fixes in the development branch.

There were some changes to the context menu code too that needs some additional testing before I can push a new release.

**Comment by wordpure** [comment]
This issue is fixed in Firefox extension version 1.44.1.

Thank you very much.

**Comment by wordpure** [comment]
@ssborbis 

If the link is triggered through the right-click menu instead of quick menu, it will still only display the `link` search engine😂

**Comment by wordpure** [comment]
In addition, I found that when the context menu is activated on an image, the ContextSearch's menu item hotkeys move from the first level to the second level.

![图片](https://user-images.githubusercontent.com/68013962/190425209-341716c7-96d6-40a8-aefb-1d09dce6f174.png)

I guess this may be because the image contains both `link` and `image` contexts. But I can't find another element that belongs to both contexts, so I can't verify it.

**Comment by wordpure** [comment]
> But I can't find another element that belongs to both contexts, so I can't verify it.

This also happens with ContextSearch when link text is selected, so the problem is most likely related to multiple  contexts.

![图片](https://user-images.githubusercontent.com/68013962/190429915-576d61b9-68fd-4241-910b-9e7cfa2f60ae.png)

> If the link is triggered through the right-click menu instead of quick menu, it will still only display the `link` search engine😂

Isn't the context menu of "select link text" and "trigger directly on link" activated in reverse?

We usually select link text to search or copy the selected text. Wouldn't it be better not to show the link context menu?

**Comment by ssborbis** [comment]
> f the link is triggered through the right-click menu instead of quick menu, it will still only display the link search engine

I'm still working this out. The context menu API is not great.

> In addition, I found that when the context menu is activated on an image, the ContextSearch's menu item hotkeys move from the first level to the second level.

Another API issue. In the event of multiple menus ( link + selection ), a parent menu is automatically created that I have no control over.

> We usually select link text to search or copy the selected text. Wouldn't it be better not to show the link context menu?

Probably, but I can't always anticipate how users expect things to work.

**Comment by ssborbis** [comment]
I have some fixes for the context menu in the development branch for testing.

**Comment by ssborbis** [comment]
Go ahead and close if this was fixed. Otherwise, please let me know what's still broken and I'll try to clear it up before the next release. TBH, I rarely use the Context menu, so I don't get exposed to the bugs like another user might.

**Comment by wordpure** [comment]
> If the link is triggered through the right-click menu instead of quick menu, it will still only display the `link` search engine😂

> In addition, I found that when the context menu is activated on an image, the ContextSearch's menu item hotkeys move from the first level to the second level.
> 
> ![图片](https://user-images.githubusercontent.com/68013962/190427977-3c118abf-f7d1-455c-b350-b3936e3bd6cd.png)

These two issues remain in 1.46b3.

**Comment by ssborbis** [comment]
Ok, I think this is worked out now. If an image has a link associated, the menu will only show either the link or image context, not both, depending on whether you're holding CTRL when the menu is opened. Defaults to image, but I can add a setting for that later. Code is in the dev branch.

**Comment by wordpure** [comment]
In 1.46.3, `Ctrl` can be used to toggle whether the link displays the link context menu or the text context menu, but the text context menu only displays the search link text, and the submenu item is still the link search engine.

![图片](https://user-images.githubusercontent.com/68013962/200602601-ebec0c02-9d81-4e09-b2df-89d4758f8850.png)

![图片](https://user-images.githubusercontent.com/68013962/200602685-a6c67a02-d21e-4635-8a4a-153269dfd347.png)

The image press `Ctrl` to switch the context menu behaves normally, expect to see it in General with a links-like setting.

![图片](https://user-images.githubusercontent.com/68013962/200603545-89edabe3-a25c-46cc-95cf-0b20086651f3.png)

**Comment by ssborbis** [comment]
> In 1.46.3, Ctrl can be used to toggle whether the link displays the link context menu or the text context menu, but the text context menu only displays the search link text, and the submenu item is still the link search engine.

To be clear, the problem is, when opening the context menu on a link and getting LINK TEXT, the engines displayed in the submenu are associate with the `link` context instead of the `selection` context? 

> but the text context menu **only** displays the search link text

Is there another problem here? I'm able to get link or link text depending on whether I'm holding CTRL. Is that not the case for you?

**Comment by ssborbis** [comment]
v1.46.4 going up. Give that a shot and see if the problems you're seeing are fixed.

**Comment by wordpure** [comment]
> To be clear, the problem is, when opening the context menu on a link and getting LINK TEXT, the engines displayed in the submenu are associate with the `link` context instead of the `selection` context?

Yes, that's exactly what I'd like feedback on.

> Is there another problem here? I'm able to get link or link text depending on whether I'm holding CTRL. Is that not the case for you?

What I want to express is that when the context menu of the link text is activated, **although** the first-level menu of Content Search displays `Search for LINK TEXT`, the submenu still displays the search engine of the `link` context  instead of the `selection` context.

This sentence is just a further description of the current problem, but my English level is not good, and the translation into English with the help of machine translation has brought misunderstandings😂

> v1.46.4 going up. Give that a shot and see if the problems you're seeing are fixed.

The problem is solved after the update, thanks。

**Comment by ssborbis** [comment]
> This sentence is just a further description of the current problem, but my English level is not good, and the translation into English with the help of machine translation has brought misunderstandings

Most users who post issues here are not native English speakers and also use translation software.  Describing technical problems and be difficult when there is a language barrier, and sometimes I need clarification to be certain I understand the issue fully. I appreciate the explanation.
