### ISSUE TITLE
CSS Selector for Font Size

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#544]
Hey there,

just a minor thing:
I use `* {font-size: 18px !important;}` but this changes both the font size in the quick-menu *AND* in the toolbar-menu simultaneously.

Is there a separate css selector for changing only the font size in the Quick-Menu?

Best Greetings,
Thomas

**Comment by ssborbis** [comment]
Yeah, you can specify menu like this
`
[data-menu="quickmenu"] * {font-size: 18px !important;}
`

Options are `quickmenu` and `searchbar`

**Comment by ThomasSeeker** [comment]
Ah, wonderful! 
Thank you very much!
:-)

**Comment by ssborbis** [comment]
No prob
