### ISSUE TITLE
Quick menu doesn't open again

### ISSUE THREAD

**Issue by bottleblue** [ssborbis/ContextSearch-web-ext#545]
This same problem is back https://github.com/ssborbis/ContextSearch-web-ext/issues/399

I downgraded to previous versions and it looks like starting with 1.42 the problem happens.

**Comment by ssborbis** [comment]
Some recent changes knocked out the ability to open the qm from an iframe. If you can, you might check the code in the development branch. I think this was fixed.

**Comment by bottleblue** [comment]
how do I use development branch?

**Comment by ssborbis** [comment]
What browser are you on?

**Comment by bottleblue** [comment]
Firefox

**Comment by ssborbis** [comment]
I'll get you a beta

**Comment by ssborbis** [comment]
https://github.com/ssborbis/ContextSearch-web-ext/releases/tag/v1.44b1

**Comment by bottleblue** [comment]
Seems to be working now! Thx!

**Comment by ssborbis** [comment]
No prob. Thanks for the report. Expect a new release in a few days.

**Comment by bottleblue** [comment]
cool ty again
