### ISSUE TITLE
Engine filtering problem again

### ISSUE THREAD

**Issue by StrollStars** [ssborbis/ContextSearch-web-ext#547]
It's a bit similar to [#537](https://github.com/ssborbis/ContextSearch-web-ext/issues/537), but it's too complicated to discuss, so I'm opening a new one.
1.Are there some duplications between Context Menu and Quick Menu? I haven't figured out the difference yet.
2.Search Engines → Edit：
> Display this engine when opening menus from the selected contexts. Works with Context and Quick menus when Advanced -> Filter Engines is enabled, otherwise ignored.

I only checked selection in one search engine, and unchecked all others, but it didn't have any effect, and other search engines were still there after the text was selected.

**Comment by ssborbis** [comment]
What menu is having problems? Both?

> I only checked selection in one search engine, and unchecked all others,

I'll have to look, but unchecking all might default to "selection" in some cases.

**Comment by ssborbis** [comment]
Using the latest code and a new profile, things seem to be working as expected. Admittedly, the qm gets a bit weird with 1 engine. I couldn't screenshot the context menu, but it also displayed only the one engine.

![1](https://user-images.githubusercontent.com/24310997/189298105-b2232ff7-4e46-406e-8bd7-a042832f2218.jpg)
![2](https://user-images.githubusercontent.com/24310997/189298125-dadb6978-6e50-48dd-9708-53b7e6fe44cc.jpg)
![3](https://user-images.githubusercontent.com/24310997/189298141-ef2addb5-8004-46f6-8a2c-e8306212247f.jpg)

![4](https://user-images.githubusercontent.com/24310997/189298155-e8bd80bf-d29e-4555-a1c6-e753f5f8e4c7.jpg)

**Comment by ssborbis** [comment]
If you have similar settings to what I screenshot and it's still not working correctly, you might send me your config and I'll take a closer look.

**Comment by StrollStars** [comment]
Thank you for your help. After checking Filter search engines based on the target element ( link, image, selection, ... ), the expected effect is achieved, but if you don't check it, the setting of the second point will be invalid?

**Comment by ssborbis** [comment]
> However, the instructions in the settings interface need to be updated.

Do you mean this ? 
![Screenshot_2022-09-10_18-52-49](https://user-images.githubusercontent.com/24310997/189505579-75d8eeaf-6f3e-451c-b58b-cee6b6cca329.jpg)

**Comment by StrollStars** [comment]
I'm sorry, I didn't read carefully, you're right.
