### ISSUE TITLE
The template for Multi-Search

### ISSUE THREAD

**Issue by StrollStars** [ssborbis/ContextSearch-web-ext#548]
I can't directly see which search engines are called from the content of the template. I will only know after using it. It is recommended to change it to a more easily identifiable display mode for easy modification.

**Comment by ssborbis** [comment]
> I can't directly see which search engines are called from the content of the template.

Multi-search is a bit underdeveloped. The easiest way to code something useful would be to put the names of the engines used in the description field. Would that be suitable?

**Comment by StrollStars** [comment]
I don't think so, put the engine name in the description field, it will still be unclear after more.
Is the template field in the Multi-Search now showing the internal code of the engine? Can it be displayed so that it is easy to find what engine it is.

**Comment by ssborbis** [comment]
> Is the template field in the Multi-Search now showing the internal code of the engine? 

Yeah, internal ID

> Can it be displayed so that it is easy to find what engine it is.

It may be a bit tricky but I'll see what can be done.

**Comment by StrollStars** [comment]
Thank you and waiting for your good news.

**Comment by StrollStars** [comment]
@ssborbis In the Context Menu, can I click on a folder item to directly invoke the search in the folder (Multi-Search)?

**Comment by ssborbis** [comment]
Are you using `forceOpenResultsTabsAdjacent = true` ?

**Comment by StrollStars** [comment]
@ssborbis ①Thanks, I understand.
②Do you think it's easy to do?

**Comment by ssborbis** [comment]
> In the Context Menu, can I click on a folder item to directly start all the search in the folder(Multi-Search)?

Not on a folder. The Context Menu API doesn't allow any actions on a folder aside from opening, so as a developer, I can't see when a user clicks a folder. The workaround is to enable `CS Options -> Context Menu -> General -> "Show an option to search the entire folder at the top of the menu"`

**Comment by ssborbis** [comment]
How's this for showing the engines in a multisearch?

![Screenshot_2022-09-18_23-00-07](https://user-images.githubusercontent.com/24310997/190947756-787416b8-6fc7-402f-b3a0-b5c2cd20a381.png)

**Comment by ssborbis** [comment]
Or are you wanting to know what engines are used in a multisearch from the search menus? I thought you meant from the options page.

**Comment by StrollStars** [comment]
> The workaround is to enable `CS Options -> Context Menu -> General -> "Show an option to search the entire folder at the top of the menu"`

It meets my needs, thanks for your help.

**Comment by 7peanuts** [comment]
> How's this for showing the engines in a multisearch?
> 
> ![Screenshot_2022-09-18_23-00-07](https://user-images.githubusercontent.com/24310997/190947756-787416b8-6fc7-402f-b3a0-b5c2cd20a381.png)

That's great, it looks very intuitive.

Can multisearch be added to the recently used as a complete engine?
