### ISSUE TITLE
Suggest to add Yandex Reverse Image Search

### ISSUE THREAD

**Issue by StrollStars** [ssborbis/ContextSearch-web-ext#549]
like the built-in Google Reverse Image Search
https://yandex.com/images/
It's too difficult for normal users to add manually.

**Comment by ssborbis** [comment]
> It's too difficult for normal users to add manually.

I'm not sure what you mean. It added normally for me, unless I'm missing something.

Just so we're on the same page, you're adding engines by right-click on the website search bar and choosing 'Add to ContextSearch', correct?

**Comment by StrollStars** [comment]
I mean people who don't know web technology, it's hard to add Yandex Reverse Image Search, and it can't be done by adding engines by right-click on the website search bar and choosing 'Add to ContextSearch', it will report an error: 
> Click OK and perform a new search using the form you are attempting to add

So i hope you can have it built in like the Google Reverse Image Search. This way I don't have to add it, just use the engine you've already added.

For manual use, I need to paste the image link in the red box below.
![2022-09-11_110712](https://user-images.githubusercontent.com/10942225/189510675-80b2b80a-c0f1-4beb-9197-0fd671e1f377.png)

**Comment by ssborbis** [comment]
Oh, ok I didn't realize the reverse search was a separate modal.

FYI, you can also find most engines at mycroftproject too. If you have this addon installed, you should see an icon next to engine links you can click to install.

https://mycroftproject.com/search-engines.html?name=yandex+reverse for instance.

**Comment by StrollStars** [comment]
Thank you for sharing, I use Chrome more, and I want to use ContextSearch to manage searches in a unified way.

**Comment by ssborbis** [comment]
> I use Chrome more, and I want to use ContextSearch to manage searches in a unified way.

That method works the same in Chrome and Firefox

![addto](https://user-images.githubusercontent.com/24310997/189555996-7499c423-0d21-40d8-af00-9e5a28982af8.jpg)

**Comment by 7peanuts** [comment]
> Thank you for sharing, I use Chrome more, and I want to use ContextSearch to manage searches in a unified way.

如同 **ssborbis** 上面回复的，Mycroft Project 这个网站提供了非常丰富的搜索引擎，点击 ContextSearch 图标即可添加，只有极少数的失效了，对于普通人来说足够了。

但除此之外，还有很多网站无法用 `GET` 方法获取搜索参数，需要使用 `POST` 请求，常见于各种论坛的搜索，以及少数不开放 `GET/POST` 接口的网站，比如需要鼠标点击、按下 Enter 或执行选择后搜索，这种需要稍微能看懂一些简单的 `HTML` `CSS` `JS` 代码。
因此，搜索引擎并没有一个统一的添加方案，大多数情况下还是需要靠大家分享。

在 README 中也提供了几个简单的 `JS` 搜索代码 ➡️ [6.4 Javascript-Driven Search Engines](https://github.com/ssborbis/ContextSearch-web-ext#toc)
当然，这几个例子是远远不够的，可以看下 Issues 里其他人的求助 ➡️ #488 ，此类网站原理大多是相通的，可以举一反三，如果有不会的可以提问，作者是很乐于帮忙的。

此外，在上图中你还能看到在 ContextSearch 图标旁边有一个小圆脸图标，那是脚本 [搜索酱](https://github.com/hoothin/SearchJumper) 的搜索配置，安装脚本后同样可以一键导入。

搜索酱功能同 ContextSearch 高度相似，中文使用环境，作者陆续还添加了许多小功能，可以尝试一下。我个人认为搜索酱的添加方式更简单、对新手友好，界面和调出方式各有亮点吧。

**Comment by 7peanuts** [comment]
> Thank you for sharing, I use Chrome more, and I want to use ContextSearch to manage searches in a unified way.

如同 **ssborbis** 上面回复的，Mycroft Project 这个网站提供了非常丰富的搜索引擎，点击 ContextSearch 图标即可添加，只有极少数的失效了，对于普通人来说足够了。

但除此之外，还有很多网站无法用 `GET` 方法获取搜索参数，需要使用 `POST` 请求，常见于各种论坛的搜索，以及少数不开放 `GET/POST` 接口的网站，比如需要鼠标点击、按下 Enter 或执行选择后搜索，这种需要稍微能看懂一些简单的 `HTML` `CSS` `JS` 代码。
因此，搜索引擎并没有一个统一的添加方案，大多数情况下还是需要靠大家分享。

在 README 中也提供了几个简单的 `JS` 搜索代码 ➡️ [6.4 Javascript-Driven Search Engines](https://github.com/ssborbis/ContextSearch-web-ext#toc)
当然，这几个例子是远远不够的，可以看下 Issues 里其他人的求助 ➡️ #488 ，此类网站原理大多是相通的，可以举一反三，如果有不会的可以提问，作者是很乐于帮忙的。

此外，在上图中你还能看到在 ContextSearch 图标旁边有一个小圆脸图标，那是脚本 [搜索酱](https://github.com/hoothin/SearchJumper) 的搜索配置，安装脚本后同样可以一键导入。

搜索酱功能同 ContextSearch 高度相似，中文使用环境，作者陆续还添加了许多小功能，可以尝试一下。我个人认为搜索酱的添加方式更简单、对新手友好，界面和调出方式各有亮点吧。

**Comment by StrollStars** [comment]
> That method works the same in Chrome and Firefox

Thanks for your help again, I got it.

**Comment by StrollStars** [comment]
@7peanuts 多谢指教，Mycroft Project是个不错的网站，感谢你们分享。

我只会添加最简单的方式——能直接从网址到搜索代码——这种浏览器本身也能完成吧？再复杂的就不知道该怎么分析了。包括这回提到的Yandex和你说到的`POST`方式。
我略懂一些`HTML`和`CSS`，`JS`就不懂了，所以[6.4 Javascript-Driven Search Engines](https://github.com/ssborbis/ContextSearch-web-ext#toc)不能完全看明白，只能从词义了解大概做了什么。另个问题是，最后关键的Search Code部分，是不是要填在Post-Search Script中？
PS：顺带问下搜索设置中`Post-Search Script`和`Modify Terms Regex`的使用场景是什么？我在翻译的时候真不知该如何翻译。

搜索酱我晚点时候试用下，Context Search我本意是想取代原来的右键搜，后者简单又有中文，上手极易；而前者强大没有中文，需要花点时间了解。

**Comment by 7peanuts** [comment]
> 另个问题是，最后关键的Search Code部分，是不是要填在Post-Search Script中？

是的，模板处填写搜索页面网址，因为要在此页面使用脚本，代码处填写脚本。
> PS：顺带问下搜索设置中`Post-Search Script`和`Modify Terms Regex`的使用场景是什么？我在翻译的时候真不知该如何翻译。

`Post-Search Script` 我也不是很理解字面意思，其作用是在此处输入 JS 脚本来执行搜索，类似的还有 `Post-App Script`。我的理解是向浏览器发出查询请求和向系统发出打开请求之后执行的脚本，比如打开网页后使用脚本在搜索框输入关键词然后点击查询，打开其它浏览器后使用 Google 进行搜索，可以问问作者具体意思。
`Modify Terms Regex` 是使用正则修改搜索关键词，比如可以提取网址域名、转换大小写、替换部分关键词等等，`CS` 本身提供域名 `{domain}` 和子域名 `{subdomain}` 关键词，一般用于页面搜索和站内搜索。
> 
> PS：Yandex以图搜图的代码是yandex.com/images/search?rpt=imageview&url={searchTerms}，其中关键的rpt=imageview部分是怎么分析出来的，你方便简单讲下吗？

说实话我也不懂，我是使用 CS 之后才开始接触这些网页知识，之前是通过观察搜索时的网址变化来添加。

我使用 CS 快一年了，刚开始看着满满十数页配置文件也是很头疼，只能挨个去试，真正深入使用脚本搜索、调用小书签和外部应用还是近半年的事。前段时间使用熟悉了，本打算写一个详细的中文介绍，但是看着这密密麻麻的配置选项还是放弃了，而且还有很多我还没用到的功能，以及正在开发中的功能。前几个月奔跑的奶酪发过一个 CS 使用的教程，只不过只有调用外部应用的介绍。
正好看到你提交了翻译，就很棒，这样新手用起来就不会很茫然 😆

**Comment by StrollStars** [comment]
> `Modify Terms Regex` 是使用正则修改搜索关键词，比如可以提取网址域名、转换大小写、替换部分关键词等等，`CS` 本身提供域名 `{domain}` 和子域名 `{subdomain}` 关键词，一般用于页面搜索和站内搜索。

`Post-Search Script`我理解了，上手难度有点大，而`Modify Terms Regex` 我感觉用到得很少吧。

> 我是使用 CS 之后才开始接触这些网页知识

CS是指Creative Suite？它的教程应该很多吧？我倒是希望你有机会，可以讲讲网页分析，就如我之前所说，直接在网址中的搜索引擎好找，再深入就难了。

> 正好看到你提交了翻译，就很棒，这样新手用起来就不会很茫然

实不相瞒，我是先用谷歌翻译了一遍，然后对照设置界面一一看过来，发现很多地方没有更好的译法（当然一部分原因也是对这个扩展不熟）……你发现有不妥的地方还请告知我下。
PS：我也是从奔跑的奶酪知道这款扩展的。

**Comment by 7peanuts** [comment]
> CS是指Creative Suite？它的教程应该很多吧？我倒是希望你有机会，可以讲讲网页分析，就如我之前所说，直接在网址中的搜索引擎好找，再深入就难了。
> 
不是，ContextSearch-web-ext 的简称 😄
其实也不用怎么分析，目前 CS 扩展和搜索酱脚本都支持一键添加当前页面的搜索引擎，CS 是右键搜索框，搜索酱是 `Ctrl+Alt+鼠标左键` 。
如果无法添加或是搜索参数错误，那么就需要使用脚本来解决了，搜索酱默认的引擎列表和 [Issues](https://github.com/hoothin/SearchJumper/issues) 里也有许多此类网站的例子。

> `Post-Search Script`我理解了，上手难度有点大，而`Modify Terms Regex` 我感觉用到得很少吧。
> 
脚本可以参考 `Isseues` 里的例子，使用 CSS 选择器找到输入文本的地方和鼠标点击的地方，多数网站是类似的。
比如 52 论坛内搜索：

> Template
> `https://www.52pojie.cn/search.php?`
> Post-Search Script
> ```js
> let input = document.querySelector('#scform_srchtxt');
> input.value = searchTerms;
> document.querySelector('#scform_submit').click();
> ```
> Method
> `GET`

至于正则修改搜索关键词，用到的地方确实不多，但是却挺有用的，比如下面这几个例子。
- 提取 B 站视频 `av` `ep`  号进行下载 ➡️ #513 
- 空白关键词替换，用于快速调用外部程序 ➡️ [#459](https://github.com/ssborbis/ContextSearch-web-ext/issues/459#issuecomment-1051276134)
- 使用脚本指定多个关键词的格式 ➡️ [[Request] Multiply Search terms #508](https://github.com/ssborbis/ContextSearch-web-ext/issues/508#issuecomment-1188018285)
- 
还有一些其它的用途，由于没有遇到也没法一一列举。我自己是用来提取网址域名，自带的 `{domain}` 和 `{subdomain}` 有时候不太能准确提取到想要的网址字段。

**Comment by StrollStars** [comment]
> 不是，ContextSearch-web-ext 的简称

我又重读了上面你的回复，发现我影响了你写详细中文介绍，可否再捡回来，我觉得我很需要……
你看这个项目的[Wiki](https://github.com/ssborbis/ContextSearch-web-ext/wiki)还空着，这不是虚位以待么。
或者你定位有一定基础的用户，像我问的问题方向，你举例说明一下？不然这款扩展发挥不了其应有的价值。

> 比如 52 论坛内搜索

看来你也是同好啊，不过吾爱的质量大不如前了，这个也没办法。
它的论坛内搜索不是百度的站内搜索么？可以直接从网址获得啊。
你给的脚本，我怎么测试关键词跟不进去？而且scform_srchtxt和scform_submit这两个ID我怎么找不到，是不是网站写在脚本里了？

https://github.com/ssborbis/ContextSearch-web-ext/issues/513看到了奔跑的奶酪……
感觉我的基础不够，这部分对我来说太难了，主要是JS基础是吧？有没有速成的教程（当然你能写就更好了^_^），或者[菜鸟学院的JavaScript 教程](https://www.runoob.com/js/js-tutorial.html)看看？

**Comment by 7peanuts** [comment]
> 它的论坛内搜索不是百度的站内搜索么？可以直接从网址获得啊。 你给的脚本，我怎么测试关键词跟不进去？
> 
52 有两个搜索，一个论坛内部的，一个是百度站内搜索。
也不需要多深入学习，看上面的例子就差不多了，我也是照葫芦画瓢，没怎么系统学习过，遇到了不明白的现去查的。

<img src="https://user-images.githubusercontent.com/82173614/190065766-13d4ebe9-6b40-4585-8412-1c0a95b90efc.jpg" width = "80%" />

我也没显示中文，可能需要在高级选项里打开。

我会看看补充下翻译，介绍的话感觉写起来太多太杂，光英文的就很多了，而且还有很多没写到的，有了中文界面的话其实也不太需要。

**Comment by StrollStars** [comment]
> 52 有两个搜索，一个论坛内部的，一个是百度站内搜索。

还真是这么回事，登录前用的百度站内搜索，登录后用的自己搜索，不过后者好像也能通过CS自带的菜单添加。

> 我也没显示中文，可能需要在高级选项里打开。

应该和高级选项无关，我当初翻译的时候，是直接在_locales文件夹下新建的zh-CN文件夹，把翻译后的messages.json放进去，然后就可以使用了。但是更新后就不行了，卸载重装扩展也无效，你知道是为什么吗？

**Comment by 7peanuts** [comment]
> 还真是这么回事，登录前用的百度站内搜索，登录后用的自己搜索，不过后者好像也能通过CS自带的菜单添加。
> 
你观察通过 CS 添加的参数里有个数字 id 之类的东西，那个可能与 cookies 有关，如果登录过期，这个搜索模板就失效了，多数论坛都是如此。

> 但是更新后就不行了，卸载重装扩展也无效，你知道是为什么吗？

我也不太清楚，等作者上线吧。

**Comment by StrollStars** [comment]
> 你观察通过 CS 添加的参数里有个数字 id 之类的东西，那个可能与 cookies 有关，如果登录过期，这个搜索模板就失效了，多数论坛都是如此。

还有个问题，你的代码和开发者的略有差异，是都能达到效果？
你的代码比开发这的好懂。

> 我也不太清楚，等作者上线吧。

你方便那个帖子也回复下么？因为你的英语比我好，比较容易表达清楚问题。

**Comment by 7peanuts** [comment]
> ①草料二维码解码，代码如下，但是没反应：

是这个吗？https://cli.im/text
方法使用 `GET`
```js
document.querySelector('#text-content').value = searchTerms;
document.querySelector('#click-create').click();
```

> ②还有个问题，如果遇到网址需要跳转后输入的呢，是不是处理更复杂？因为直接访问会出错。

跳转后的页面有没有搜索框？有的话直接在这个页面搜索行不行？好像还没碰到过这种，可以让作者帮忙解决。
或者看看搜索酱里面的 [规则](https://github.com/hoothin/SearchJumper/issues/1#issuecomment-1150641854) 有没有需要的，一般我遇到没有搜索框的会直接使用百度或谷歌站内搜索。

**Comment by StrollStars** [comment]
> 是这个吗？https://cli.im/text

不好意思忘记给了链接：https://cli.im/deqr/url
我是想直接解析网页二维码图片。

> 跳转后的页面有没有搜索框？有的话直接在这个页面搜索行不行？

你看看[这个链接](https://kzurl01.cn/LfJrE)。

**Comment by 7peanuts** [comment]
> 不好意思忘记给了链接：https://cli.im/deqr/url 我是想直接解析网页二维码图片。

我试了你那个没问题，能解析。
> 你看看[这个链接](https://kzurl01.cn/LfJrE)，站内搜索恐怕没用。

这个应该可以直接搜索，里面有 id 和 token，token 是变动的，不带 token 搜索不全。
`http://kelezj.com/apps/index.html?name={searchTerms}&id=211229kl`
使用脚本的话，网址里也要带 id
`http://kelezj.com/apps/index.html?id=211229kl`
```js
document.querySelector('#search.input').value = searchTerms;
document.querySelector('#submitSearch').click();
```

**Comment by StrollStars** [comment]
> 我试了你那个没问题，能解析。

我的期望是在https://cli.im/deqr/url上用以下代码搜索时可以解析出图片中的内容：
```
let input = document.querySelector('#deqr_urls');
input.value = searchTerms;
document.querySelector('#deqr_url_btn').click();
```
但我测试[这个图片](https://www.liantu.com/images/2013/case/3.jpg)，发现就跟打开这个网址一样，输入框是空的，只能手动把图片地址粘贴进去，再点击解码，你那边直接可以跳出解码结果的窗口？

> 这个应该可以直接搜索，里面有 id 和 token，token 是变动的，不带 token 搜索不全。

看来是我不带token的缘故了，我试试token不变能不能一直用下去。

**Comment by StrollStars** [comment]
> 这个应该可以直接搜索，里面有 id 和 token，token 是变动的，不带 token 搜索不全。

你有没有试过之前建立的搜索？我今天测试已经得不到结果了，刷新提示“此链接失效，请重新获取”。
所以还是需要从最开始那个连接入手，有办法链接重定向后使脚本生效吗？以下设置没有效果。
链接：`https://kzurl01.cn/LfJrE`
脚本：
```
document.querySelector('#search').value = searchTerms;
document.querySelector('#submitSearch').click();
```

**Comment by 7peanuts** [comment]
> 你有没有试过之前建立的搜索？我今天测试已经得不到结果了，刷新提示“此链接失效，请重新获取”。 所以还是需要从最开始那个连接入手，有办法链接重定向后使脚本生效吗？

这我也不会，看了下原链好像是个生成的短链接，重定向的地址是变动的。
脚本应该可以做到，不过我不会写，得问作者和其他大佬了 🤪

**Comment by StrollStars** [comment]
@ssborbis Can you help me write the search engine for [this url](https://kzurl01.cn/LfJrE)? The search needs to be done at the redirected URL, and the redirected URL changes.

**Comment by ssborbis** [comment]
> Can you help me write the search engine for [this url](https://kzurl01.cn/LfJrE)? The search needs to be done at the redirected URL, and the redirected URL changes.

I think @7peanuts solution works. 

Ignore the initial redirect by setting http://kl.kelezj.com/apps/index.html?id=211229kl as your template.

Search Script: 
```js
document.querySelector('#search').value = searchTerms;
document.querySelector('#submitSearch').click();
```

Is that not working for you?

**Comment by StrollStars** [comment]
> Ignore the initial redirect by setting http://kl.kelezj.com/apps/index.html?id=211229kl as your template.

I can't set http://kl.kelezj.com/apps/index.html?id=211229kl, because it will expire after a certain time.

**Comment by ssborbis** [comment]
> I can't set http://kl.kelezj.com/apps/index.html?id=211229kl, because it will expire after a certain time.

I see. I'll look into a solution.

**Comment by ssborbis** [comment]
@StrollStars 

I have code that specifically blocks searches and scripts from executing on redirects. I can't remember why this was put in. I think it had to do with POST engines, but I need to do a lot of testing to be sure. Removing one line of code fixes the issue with the engine you're asking about.

**Comment by hoothin** [comment]
> > 你有没有试过之前建立的搜索？我今天测试已经得不到结果了，刷新提示“此链接失效，请重新获取”。 所以还是需要从最开始那个连接入手，有办法链接重定向后使脚本生效吗？
> 
> 这我也不会，看了下原链好像是个生成的短链接，重定向的地址是变动的。 这个 id 好像还与 UA 和 IP 有关，电脑和手机重定向的地址也不一样
> 
> 脚本应该可以做到，不过我不会写，得问作者和其他大佬了 🤪

7企鹅兄好，看到 mentioned 来瞅瞅，这个夸克网盘搜索搜索酱已经加上了

**Comment by StrollStars** [comment]
@ssborbis Thanks for your help, at your pace.

**Comment by StrollStars** [comment]
@7peanuts https://www.sojson.com/qr/deqr.html
它的按钮没有ID，只能通过类，又不是第一个，querySelector和querySelectorAll都不行，有没有别的办法？

**Comment by 7peanuts** [comment]
> @7peanuts https://www.sojson.com/qr/deqr.html 它的按钮没有ID，只能通过类，又不是第一个，querySelector和querySelectorAll都不行，有没有别的办法？

这个我也不太清楚。

@ssborbis Hi, this site [https://www.sojson.com/qr/deqr.html](https://www.sojson.com/qr/deqr.html) can parse the QR code, but there are many buttons of the same class name `layui-btn`, could you help me?
This is a QR pic sample
`https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=https://www.google.com/`

![20220919113838](https://user-images.githubusercontent.com/82173614/190946615-1f323413-4f6e-4e7f-ba9a-7b29c7511fd4.jpg)

> 还有https://tuzim.net/decode/，它中间的图片链接貌似难度更大。
> 
兔子二维码改版了，之前可以正常搜索。
下面这个脚本倒是可以了，但我不知道有没有其它更简洁的写法 😆
编码选 `UTF-8` ，选其它的好像不能解析一般的图片链接。
```js
(async() => {
  let input = document.querySelector('.ant-input.ant-input-lg');
  input.focus();
  await new Promise(r => setTimeout(r, 200));
  input.value = searchTerms;
  input.dispatchEvent(new Event("input"));
  await new Promise(r => setTimeout(r, 200));
  document.querySelector('button.ant-btn.ant-btn-primary.ant-btn-lg.ant-input-search-button').click();
})();
```

**Comment by ssborbis** [comment]
@StrollStars

v1.45 ( going up now ) has a hidden setting `ignoreSearchRedirects`. If you set this to false, that should fix issues on https://kzurl01.cn/LfJrE.

**Comment by StrollStars** [comment]
> 下面这个脚本倒是可以了，但我不知道有没有其它更简洁的写法

膜拜大神，完全可用，厉害。

> a hidden setting `ignoreSearchRedirects`

Where is it? How can i find it.
BTW, please take a look at the content by @7peanuts above.

**Comment by ssborbis** [comment]
@StrollStars 

CS Options -> Advanced -> Manual Edit -> `ignoreSearchRedirects`

**Comment by ssborbis** [comment]
@StrollStars 

> BTW, please take a look at the content by @7peanuts above.

Google Translate isn't working on that page, so I don't exactly know what's going on. But, if you're trying to click the button below the `<textarea>` on the right side, the simplest CSS selector is `document.querySelector('a.layui-btn').click();`

**Comment by StrollStars** [comment]
> CS Options -> Advanced -> Manual Edit -> `ignoreSearchRedirects`

Thank you very much.

> the simplest CSS selector is `document.querySelector('a.layui-btn').click();`

@7peanuts 你看看你这边行不行，我好像不行。

**Comment by 7peanuts** [comment]
> 你看看你这边行不行，我好像不行。 显示复制成功，其实没有复制。

ssborbis 因为没有翻译，给的是复制按钮。
根据 hoothin 大佬的指点，使用属性名稍微改一下就行了。
> 抓取可以用属性名选择器，例如`[lay-filter="subQr"]` 或者用 xpath 例如 `//button[contains(@lay-filter, "Qr")]`

```js
document.querySelector('#url.layui-input').value = searchTerms;
document.querySelector('[lay-filter="subQr"]').click();
```

**Comment by StrollStars** [comment]
感谢 @7peanuts @hoothin 大佬指点，原来还能这么写。
顺带请教下，#url.layui-input其实后半部分没有意义吧？

**Comment by hoothin** [comment]
@StrollStars 不一定的，id 不一定惟一，如果页面中有两个 id 为 url 的元素，那后半部分就有用了。另外 css 选择器也不是万能的，例如一些站点按钮文字会变化，id class 又不固定，选择器就不适合了。

**Comment by StrollStars** [comment]
> id 不一定惟一

早先看的时候，好像说ID是唯一的，后面可能改了。

> 例如一些站点按钮文字会变化，id class 又不固定

这个我知道，不过选择器简单且容易上手，不行的时候再来请教。

**Comment by StrollStars** [comment]
@7peanuts 麻烦看下https://m2t.lolicon.app/，手动操作的时候，链接粘贴进去就直接识别，但是如果用`document.querySelector('#magnet').value = searchTerms;`就没有效果。

**Comment by hoothin** [comment]
搜索酱的话，直接用`https://m2t.lolicon.app/#p{#magnet=%s}`就行，否则用 ContextSearch 的脚本的话我估计要手动 dispatch change 事件

**Comment by StrollStars** [comment]
> #p{#magnet=%s}

请教下，这个是什么写法？我看了几个搜索引擎都没出现这样的写法。

PS：搜索酱的搜索引擎，建议支持搜索，不然搜索引擎多了，找一个比较费时。

**Comment by hoothin** [comment]
那是搜索酱专用的。
引擎一直都支持筛选的啊，可以通过类别、站名、描述或者url筛选

**Comment by StrollStars** [comment]
@ssborbis how can i add https://m2t.lolicon.app/?

**Comment by 7peanuts** [comment]
> @7peanuts 麻烦看下https://m2t.lolicon.app/，手动操作的时候，链接粘贴进去就直接识别，但是如果用`document.querySelector('#magnet').value = searchTerms;`就没有效果。

咦，我没收到提醒，不知道是不是问题被关闭的原因。
- https://m2t.lolicon.app/
```js
(() => {
  let input = document.querySelector('#magnet');
  input.value = searchTerms;
  input.dispatchEvent(new Event("input"));
})();
```
- https://magnet-vip.com/
```js
(() => {
  let input = document.querySelector('[class="form-control"]');
  input.value = searchTerms;
  input.dispatchEvent(new Event("input"));
  document.querySelector('button.btn.btn-outline-secondary').click();
})();
```
有一些可以参考我之前那个提问，或者更早一些的提问，里面有些特殊的例子，火狐的控制台能看到需要哪些事件，像大佬说的再复杂一些的我就不会了。

**Comment by StrollStars** [comment]
@7peanuts 谢谢帮忙，测试了下可用，可否简单讲下控制台输入什么命令可以看到事件？直接搜索没能搞定。
let是类似定义变量吧？这么写是不是为了后续不用写一长串了？
PS：问题并没有关闭，我能收到提醒。

**Comment by 7peanuts** [comment]
> @7peanuts 谢谢帮忙，测试了下可用，可否简单讲下控制台输入什么命令可以看到事件？直接搜索没能搞定。 let是类似定义变量吧？这么写是不是为了后续不用写一长串了？ PS：问题并没有关闭，我能收到提醒。

看这个
https://github.com/ssborbis/ContextSearch-web-ext/issues/488#issuecomment-1141252133

**Comment by StrollStars** [comment]
@ssborbis @7peanuts 内置的Google Reverse Image Search搜索失效了，会被重定向到 https://www.google.com/imghp?sbi=1 ，可否看一下？

**Comment by StrollStars** [comment]
@7peanuts 果然可用，谢谢，下回我新开帖吧，这个关了。
