### ISSUE TITLE
Suggest to modify the way to open in new tabs

### ISSUE THREAD

**Issue by StrollStars** [ssborbis/ContextSearch-web-ext#551]
Currently opened in a new tab, the new tab is placed after the last tab, can it be placed after the current tab instead?

**Comment by ssborbis** [comment]
check advanced -> Manual Edit -> `forceOpenResultsTabsAdjacent` and set to true. Be aware, you may see a very similar option `forceOpenReultsTabsAdjacent` which is a typo and does nothing.

**Comment by StrollStars** [comment]
@ssborbis  Thank you for your help, and I didn't see `forceOpenReultsTabsAdjacent`.
