### ISSUE TITLE
1.44 Search for LINK can't work on Chrome

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#556]
But it still works on FF.

![-gif-](https://user-images.githubusercontent.com/82173614/190075640-f54675f3-e4f8-4706-8a2e-fb00863b3ca6.gif)

**Comment by ssborbis** [comment]
Got it. Thanks!

**Comment by ssborbis** [comment]
FIx going up, v1.44.2
