### ISSUE TITLE
Clipboard conflict issue

### ISSUE THREAD

**Issue by nollinvoyd** [ssborbis/ContextSearch-web-ext#560]
Firefox 104.0.,1, Windows 10, ContextSearch-web-ext 1.44.2

I'm recently became a ContextSearch-web-ext user.

Perhaps there is an option in settings I must adjust, but I experience using ContextSearch-web-ext interferes with copy/paste actions.  

In some instances, if I use ContextSearch-web-ext to copy, and afterwards copy something else by another method, the item I first copied using ContextSearch-web-ext is persistent, remaining in my clipboard and becomes the data that is pasted.  

I must disable ContextSearch-web-ext to resolve the conflict.

**Comment by ssborbis** [comment]
How are you copying via this addon? The quick menu + the copy tool, or are you using autocopy?

**Comment by nollinvoyd** [comment]
I'll try to do a better, simpler job of explaining.  Please try this.

From your reply to this post, go to my original post, copy the words "I'm recently", and then paste the words into you replay field.  .

Then, once again go back to my original post, and copy the words "Perhaps there".  Go back to your replay field, double click on "I'm recently" to highlight the words, then try to paste the words "Perhaps there"  

"Perhaps there" will not be pasted to replace "I'm recently".. The words "I'm recently" will remain.  

Whatever text you highlight goes to the clipboard.  When you disable ContextSearch-web-ext, this behavior stops.

**Comment by ssborbis** [comment]
Do you have CS Options -> General -> Auto Copy enabled?

![Screenshot_2022-09-16_15-23-36](https://user-images.githubusercontent.com/24310997/190726843-ef914a51-d59b-4060-8d1f-55a7b4b60e03.png)

**Comment by nollinvoyd** [comment]
Yes, that's what I figured from the beginning, that it was a setting I missed, since I just started using it.

I think it's great that there is such a vast array of options, but if you will allow a suggestion, perhaps that feature should not be enables by default. Not a criticism, just a thought.

Great extension, great work.. Thanks

**Comment by ssborbis** [comment]
>  perhaps that feature should not be enabled by default. Not a criticism, just a thought.

It isn't. I had to double-check just to be certain. I'm confused as to why it would be enabled for you if you didn't enable it yourself. I'll do some digging around in the code in case I have some test code that should have been removed.

**Comment by nollinvoyd** [comment]
> I'm confused as to why it would be enabled for you if you didn't enable it yourself

Please forgive me.  I just added it to another profile, and, as you said, it is not enabled  I don't remember doing it, but obviously I did.  Sorry to put you to all this trouble.

Thanks again.

**Comment by ssborbis** [comment]
No prob. Glad you got things sorted out.
