### ISSUE TITLE
Enhance page tiles

### ISSUE THREAD

**Issue by wordpure** [ssborbis/ContextSearch-web-ext#562]
1. Support dragged images and link contexts.
    The page tiles currently only supports dragging and dropping text for searching, which I think limits it to a large extent.
2. Perform more actions via modifier keys + drag, or modifier keys + mouse keys (when triggered by shortcut keys) like context menu and quick menu.
    For the space of the entire web page, one way to open is still too little, it can do more.

**Comment by ssborbis** [comment]
I haven't looked at pageTiles in a while. Looks like there are multiple issues, mostly on Chrome.

In the dev branch, pageTiles should be using the searchActions set under Quick menu when opened by shortcut, and using a mouse button to search ( vs drag ).

Links and images should also work when dragging, and when pageTiles is opened by hotkey, provided Shortcuts -> Hotkeys -> Enable on [img / link] are enabled.

**Comment by ssborbis** [comment]
There are some mostly cosmetic updates to the pageTiles feature coming the next release ( code in the master branch for testing ) . If you have any trouble after the update ( 1.46.15 ), please open a new issue.
