### ISSUE TITLE
Icon size issue

### ISSUE THREAD

**Issue by awalkonthebeach** [ssborbis/ContextSearch-web-ext#563]
Hello, I've been using this extension on my PC for a while with no issues.  Here is what the quick menu looks like, which I"m used to:

![normal](https://user-images.githubusercontent.com/7669787/190729326-4f31f20c-6e09-4cde-a27b-ae3cfa820af0.png)

But when I install it fresh on a new computer, the icons are much larger and low res. 

![2022-09-16_233010](https://user-images.githubusercontent.com/7669787/190729441-a361bdc6-f8ab-48df-a2f3-74deb7352170.png)

On both computers I have the icon size set to 100%, so I don't know why they look so different.  I would appreciate some help.
Thanks!

**Comment by awalkonthebeach** [comment]
I forgot to add that if I transfer the extension configuration using export/import, I get the nice small icons that I like.  I just don't know which setting controls that.

**Comment by ssborbis** [comment]
It appears you're using different CS themes on the two computers. Dark on the first, and Modern on the second. 

You can change themes via the 'Toggle Theme' tool, or CS Options -> General -> Menu Theme.

**Comment by awalkonthebeach** [comment]
Thank you!  That did it.  
So what if I want to use one of the modern themes, but with the normal icon size (small)?  I like the modern sunset background but I can't really use it with those giant icons.

**Comment by ssborbis** [comment]
> So what if I want to use one of the modern themes, but with the normal icon size (small)? I like the modern sunset background but I can't really use it with those giant icons.

If you're familiar with CSS, you can use CS Options -> General -> User Styles to stylize the menus however you see fit. The `Icon Size` option was added long before user styles, and is mostly depreciated.

You could try something like this
```css
.tile {
background-size:50%;
}
```

That would force icons in all themes to only fill a small amount of the tile.

**Comment by awalkonthebeach** [comment]
Alas I'm not familiar with CSS, so I will not risk doing anything with that.  I am perfectly happy with the normal dark theme so I will use that.
Thank you for your help and for the great add-on!

**Comment by ssborbis** [comment]
No prob
