### ISSUE TITLE
How to disable drag and drop blur

### ISSUE THREAD

**Issue by StrollStars** [ssborbis/ContextSearch-web-ext#565]
Drag and drop the selection, the webpage will become blurred, how to disable it?

**Comment by ssborbis** [comment]
I think that only happens if you have pageTiles enabled.

**Comment by StrollStars** [comment]
@ssborbis Thanks, I disabled it, but what does it do?

**Comment by ssborbis** [comment]
I didn't realize it until a day or 2 ago, but pageTiles is broken until you edit the gid under CS Options -> Page Tiles -> Layout

**Comment by 7peanuts** [comment]
Page Tiles Options ➡ Drag the engine from the list on the left to the grid on the right, then you can drag and drop text onto the full-screen tile to search.
Just like drag-and-drop mouse search ➡ [鼠标拖拽](https://greasyfork.org/zh-CN/scripts/426334-%E9%BC%A0%E6%A0%87%E6%8B%96%E6%8B%BD)

**Comment by ssborbis** [comment]
> @ssborbis Is it possible to display tiles without a full screen, for example using dartboard, triangular or square curtains.

I have definitely been thinking about this, since I use a 4K monitor and a large browser window, so the fullscreen pageTiles is way too big IMO. Styles like `#CS_pageTilesIframe, #CS_pageTilesOverDiv { transform:scale(.5);}` work ok on Firefox for shrinking the UI, but I've never tried anything more elaborate than that. If you have any UI examples, I'll take a look..

**Comment by 7peanuts** [comment]
> but I've never tried anything more elaborate than that. If you have any UI examples, I'll take a look..

It was just an idea for me and I'm not sure if changing the UI would be more helpful in searching, I found two reference images.

Concentric disks
![Concentric disks](https://user-images.githubusercontent.com/82173614/190950605-22892447-489e-463c-b2fd-4d8835ea3067.png)

Pyramid type
![Pyramid type](https://user-images.githubusercontent.com/82173614/190950611-6d2e596a-9d36-4c85-ab75-46303a987c6d.jpeg)

**Comment by hoothin** [comment]
哇，居然在这里发现搜索酱的搜索圆盘，献丑了。这个我也是仿照着[网友给的](https://github.com/hoothin/SearchJumper/issues/12)quicker 搜索面板做的。当时我还向他推荐了 ContextSearch-web-ext

**Comment by 7peanuts** [comment]
> 哇，居然在这里发现搜索酱的搜索圆盘，献丑了。这个我也是仿照着[网友给的](https://github.com/hoothin/SearchJumper/issues/12)quicker 搜索面板做的。当时我还向他推荐了 ContextSearch-web-ext 这个无比强大的插件。

大佬给力，圆盘和磁贴是最好的展示方式了，其它的就是我瞎建议了哈哈。
两个我都用，还在学习相关网页知识，争取以后可以自己解决问题 😃

**Comment by StrollStars** [comment]
> Page Tiles Options  Drag the engine from the list on the left to the grid on the right, then you can drag and drop text onto the full-screen tile to search.
> Just like drag-and-drop mouse search  [鼠标拖拽](https://greasyfork.org/zh-CN/scripts/426334-%E9%BC%A0%E6%A0%87%E6%8B%96%E6%8B%BD)

感谢解释，总算搞懂这个是怎么用的了，话说下回希望中文回我

@hoothin 谢谢推荐搜索酱，这个 @7peanuts 也跟我提过，我想等先搞懂了CS再去试试。
感觉这两个都是可以帮助学习的扩展^_^

**Comment by hoothin** [comment]
关于你在另一个帖子里的提问，那几个站点搜索酱都加上了，包括二维码解析和夸克网盘跳转，你可以参考一下用在 ContextSearch-web-ext 上。
抓取可以用属性名选择器，例如`[lay-filter="subQr"]`

**Comment by StrollStars** [comment]
@hoothin 我看到了，内置了好多搜索，有问题我去你那儿提问。
