### ISSUE TITLE
Quick menu has gap on the right

### ISSUE THREAD

**Issue by scharmach** [ssborbis/ContextSearch-web-ext#567]
Since the extension was updated to 1.45, my quick menu now looks like this:

![grafik](https://user-images.githubusercontent.com/9080980/191108062-f493887b-f0c8-42b6-8f70-6b49a6e6e265.png)

Where does the gap on the right suddenly come from?

ContextSearch 1.45
Firefox 104.0.2

**Comment by ssborbis** [comment]
It's a result of the new minimum columns setting. I have a fix going up now ( v1.45.1 )

**Comment by scharmach** [comment]
Thanks for the quick fix!

However, there is one more thing I noticed, now that my focus was more on the spot. You can still see a very thin gap on the right:

![grafik](https://user-images.githubusercontent.com/9080980/191202952-3e09179d-c5b9-4c24-bc08-5103e159a4df.png)

Maybe this was even there before the 1.45 update and I just never noticed it.

**Comment by ssborbis** [comment]
There will always be some issues due to scaling, pixel ratio, zoom and rounding off pixel widths, but this may still be the result of recent changes. I have a new version going up ( 1.45.2 ) that may handle the qm width better.

**Comment by scharmach** [comment]
Thanks for looking into this again! The gap on the right is now completely gone:

![grafik](https://user-images.githubusercontent.com/9080980/191977098-5a07aa9b-5b68-4ba6-9684-a439f2591fc2.png)

With that, this issue can be closed.
