### ISSUE TITLE
Issue with quick menu

### ISSUE THREAD

**Issue by maggotb** [ssborbis/ContextSearch-web-ext#571]
Hello,

These two search engines are set to only show on selected text

![59033363](https://user-images.githubusercontent.com/62154223/191558247-78329b68-402b-426a-a447-36dbd5330260.jpg)

But they show on image links (here google images)

![Screenshot 2022-09-21 at 18-16-13 image – Recherche Google](https://user-images.githubusercontent.com/62154223/191558664-f6456b48-c5ee-4f86-8aa3-95a6e741860b.png)

"Filter search engines" is enabled in the options.  Is there any way to fix this? thanks

**Comment by ssborbis** [comment]
Ah, it's because links will show selection contexts in order to use the link text ( which are normally used by selection engines). In the case of links on images, there is no link text, so I will add code to filter out those cases.

**Comment by ssborbis** [comment]
Can you check what your setting is for CS Options -> General -> Links. If you have it set to `text`, you might be better off with `url`

**Comment by maggotb** [comment]
that did the trick, thanks

**Comment by ssborbis** [comment]
no prob
