### ISSUE TITLE
Open Folders On Hover 

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#572]
I only have this problem with this one browser `chromium 95.0.4638.69`

I've been using mouse hover to open folders and when I cancel that feature, I can't open the folder when I click on it again.

`openFoldersOnHoverTimeout = 0`

Are there any other options that affect opening folders?

**Comment by 7peanuts** [comment]
Ok, I got it, after rebooting the system to normal, it seems that the browser problem.

**Comment by ssborbis** [comment]
Do you have `Browse Folder` set as the search action for the mouse button you're clicking?
![Screenshot_2022-09-23_10-24-09](https://user-images.githubusercontent.com/24310997/191996466-55538b71-02bb-4bf6-b94f-a6fe795006ee.png)

**Comment by 7peanuts** [comment]
> Do you have `Browse Folder` set as the search action for the mouse button you're clicking? ![Screenshot_2022-09-23_10-24-09](https://user-images.githubusercontent.com/24310997/191996466-55538b71-02bb-4bf6-b94f-a6fe795006ee.png)

Ah, I forgot there was an option here, thanks again! 😆
