### ISSUE TITLE
Search problems with special characters

### ISSUE THREAD

**Issue by Parvares** [ssborbis/ContextSearch-web-ext#573]
Hi,
I added this URL to context menu:

[https://www.bibliotechediroma.it/opac/query/%s?context=tmatm](https://www.bibliotechediroma.it/opac/query/%25s?context=tmatm)

 I need to enable some special character like:

 **;/’ ()** 

Here are some examples:

**1)** _Nome della rosa **/** Umberto Eco_
The result string is truncated and becomes _Nome della rosa_ (without text after **/** )

**2)** _Parmenide Platone **;** Ferrari_ 
The result string is truncated and becomes _Parmenide Platone_ (without text after **;** )

 **3)**  _Storia dell **'** arte veneziana_
Result: _The search parameters are incorrect_

I tried in vain setting the encoding for the engine to **_No Encoding_** under CS Options -> _Search Engines_ -> [engine] -> _Encoding_

Thanks very much!

**Comment by ssborbis** [comment]
There is some filtering / processing happening to search strings when you enter titles into the search bar on that site. You can filter out bad characters using the `Modify Terms Regex` field like so:
```
/[';()\/\[\]]//g
```

Or, you can set it up to search using javascript instead of a GET query.

**Comment by Parvares** [comment]
Thanky so much, works perfectly with first option (don't know how to manage with second option)! 
With the above [URL ]([https://www.bibliotechediroma.it/opac/query/%s?context=tmatm](https://www.bibliotechediroma.it/opac/query/%25s?context=tmatm)) I'm also having problem with a search string starting with a _**stop word**_ (articles, simple and complex prepositions) + **_asterisk_**, for example:

L'*acquerello / Marie-Pierre Salé

The search engine doesn't recognize characters before asterisk + asterisk, so the string must be troncated to:

acquerello / Marie-Pierre Salé

Thanks again!

**Comment by ssborbis** [comment]
I think it would be `/[\*']/ /g` - note the space between the last two slashes, and the escape character before the asterisk.

FYI, you can chain regex replacements by entering one regex per line in the field. So, if you wanted to combine the 2 examples. it would be
```
/[;()\/\[\]]//g
/[\*']/ /g
/\s+/ /g
```

The third line replaces all multiple spaces with a single space.

**Comment by Parvares** [comment]
Thanks, I tried, but unfortunally both strings don't work... 

_L'*acquerello / Marie-Pierre Salé_

_Grammatica d'uso della lingua russa_

**Comment by Parvares** [comment]
Thanks a lot, [ssborbis](https://github.com/ssborbis)!! P.S. I changed the addon favicon in the browser toolbar, I'm wondering how can I can change the favicon in the context menu, thanks!


![change favicon](https://user-images.githubusercontent.com/55709458/192163254-fe90f4ee-18a2-4605-9926-10fe2a3928b9.png)

**Comment by ssborbis** [comment]
> I'm wondering how I can change the favicon in the context menu, thanks!

You can't. The webextensions API doesn't allow it.
