### ISSUE TITLE
Change {download_url} folder?

### ISSUE THREAD

**Issue by maggotb** [ssborbis/ContextSearch-web-ext#577]
Is there a way to download the files in desktop for exemple instead of the TEMP folder?

**Comment by ssborbis** [comment]
No, but I can add it

**Comment by ssborbis** [comment]
Ok, the question is, should this be a global setting or a per-engine param setting.

**Comment by maggotb** [comment]
Personally I don't mind but I guess per-engine would be better since it would give more options

**Comment by ssborbis** [comment]
If you want to change it yourself while I get something worked out, it's a pretty easy mod to ContextSearch.py

Instead of 
```
tmpdir = tempfile.gettempdir()
```

change to
```
tmpdir = os.path.expanduser("~/Desktop")
```

or wherever your path is

**Comment by ssborbis** [comment]
latest version 1.46 has hidden option `nativeAppDownloadFolder`. This is a global setting to change your download folder. Future versions will have a way to set folder on a per-engine basis, and a "Ask Me" option that prompts the user with a folder browser so you can choose save location every time

**Comment by maggotb** [comment]
Thanks, I've been trying to figure it out but I can't get it to work. I updated the extension and the external app which is running fine. 

I put "nativeAppDownloadFolder": "D:\test" I save

Am I missing something?

**Comment by ssborbis** [comment]
Python my require a forward slash or a double backslash. Try "D:/test" or maybe "D:\\test". Also, make sure the directory exists. It won't create it.

**Comment by ssborbis** [comment]
FYI, I haven't tested on Windows so there may be something else up. I'll check that too.

**Comment by maggotb** [comment]
It doesn't work, even leaving nativeAppDownloadFolder blank doesn't work anyway. Yes I'm on Windows and I had created the folder of course

"C:\Program Files\XnViewMP\xnviewmp.exe" without "{download_url}" opens Xnview so it "works" if that's of any help

**Comment by ssborbis** [comment]
I'm testing on a virtualbox windows install with the following app launcher template

mspaint {download_url}

with ...

` "nativeAppDownloadFolder": "C:/Users/ssborbis/Desktop",`

... and native app v2.18 

and it seems to be working Can you check with those settings on your rig and report the results?

**Comment by ssborbis** [comment]
I also tried `"C:\Program Files\XnViewMP\xnviewmp.exe" "{download_url}"` and had good results. Double-check you're on the latest versions.

**Comment by maggotb** [comment]
Yes I'm on the latest versions. It works now go figure
