### ISSUE TITLE
what does the contexts toolbar do?

### ISSUE THREAD

**Issue by bottleblue** [ssborbis/ContextSearch-web-ext#578]
What does it do and how do I turn it off for the toolbar if I don't want to use it?

**Comment by ssborbis** [comment]
CS Options -> Quick Menu -> Advanced -> Show the Contexts Toolbar

or 

QM -> Layout Editor tool -> uncheck contexts

It's used with menus displaying contextual layouts ( only show engines intended for particular contexts like images, links, etc ). It shows the current context and allows you to cycle through engines with different contexts. I think a few versions ago, it got displayed by default, and for some users got stuck there.

**Comment by bottleblue** [comment]
It's not in my quick menu it's in the toolbar menu. Any version after 1.44.2 will have it displayed in toolbar menu. I don't see an option to get rid of it but not a big deal. Thx.

**Comment by ssborbis** [comment]
Open the toolbar menu, click the layout editor tool ( enable first it if you need to ) and uncheck contexts bar

**Comment by ssborbis** [comment]
I'm going to add a line that disables displaying the bar when not using a contextual layout

**Comment by bottleblue** [comment]
> Open the toolbar menu, click the layout editor tool ( enable first it if you need to ) and uncheck contexts bar

It worked thx.  


> It's used with menus displaying contextual layouts ( only show engines intended for particular contexts like images, links, etc ). It shows the current context and allows you to cycle through engines with different contexts. I think a few versions ago, it got displayed by default, and for some users got stuck there.

 So I need to assign engines to a particular icon?

**Comment by ssborbis** [comment]
> So I need to assign engines to a particular icon?

Right. When you edit an engine, there are checkboxes at the top of the modal. Or, if you enable CS Options -> [Quick Menu / Context Menu ] -> Advanced -> Contextual Layout and refresh the options page, you'll see icons in the engines list you can click. Any engines you assign the `link` context to, for instance, will be the only engines that show up if you open the menu on a link, or click the `link` context icon. It's a convenient way to filter engines quickly

**Comment by bottleblue** [comment]
Ah I see. It's a nice touch to help be more organized. I don't think I need it though. Plus I've got like 90 engines it's too much hassle lol.
