### ISSUE TITLE
Import settings not working

### ISSUE THREAD

**Issue by ShahedFaisal** [ssborbis/ContextSearch-web-ext#58]
I exported my settings to _ContextSearchOptions.json_ file. But when I try to import the same file I get the following message:

![2018-06-10 2](https://user-images.githubusercontent.com/13907697/41202029-12f5314e-6ce5-11e8-8134-2748ec59a510.png)

Firefox 61.0b12, ContextSearch 1.5.9.

**Comment by ssborbis** [comment]
I'm guessing your exported settings have the quick menu disabled? Had a bad conditional in my parser check. Should be fixed in 1.6.0.1 going up now

**Comment by ssborbis** [comment]
v1.6.0.2 going up. It should work with most older exports

**Comment by ShahedFaisal** [comment]
> I'm guessing your exported settings have the quick menu disabled?

Yes, I had quick menu disabled.
And thanks! It's fixed now with 1.6.0.2.
