### ISSUE TITLE
New user..Please guide me add these search engines

### ISSUE THREAD

**Issue by rakitanc** [ssborbis/ContextSearch-web-ext#580]
Hi there..hope you are doing well

https://www.dogpile.com/
https://www.alltheinternet.com/
https://www.lukol.com/
https://www.onesearch.com/

Also One more request

Is there a way to search  on all engines together at one click. If yes Please let me know how to setup and If no I would urge to add this feature as it will definitely saves a lot of time

Looking forward to hearing from you

Thanks

**Comment by benyaminl** [comment]
No there are none, you must manually put it one by one...

**Comment by ssborbis** [comment]
What is the problem with those engines? Do they use a session token?

**Comment by ssborbis** [comment]
> Is there a way to search on all engines together at one click. If yes Please let me know how to setup and If no I would urge to add this feature as it will definitely saves a lot of time

Yes, there are two ways. 
1. place all engines you want to search at once in a folder and perform a folder search.
2. highlight multiple engines in the search engines manager ( ctrl+click usually ) and right-click -> New Multisearch. It will combine all selected engines into a single "engine"

**Comment by ssborbis** [comment]
Just to elaborate on my first post, how have you been adding engines so far? The most common way is to right-click the search bar on each of those websites and select "Add To ContextSearch" from the context menu. Another way would be to visit mycroftproject.com and install engines by clicking the ContextSearch icon displayed next to each engine in the list. Or you can manually add engines from the search engines manager

**Comment by rakitanc** [comment]
> Just to elaborate on my first post, how have you been adding engines so far? The most common way is to right-click the search bar on each of those websites and select "Add To ContextSearch" from the context menu. Another way would be to visit [mycroftproject.com](http://mycroftproject.com) and install engines by clicking the ContextSearch icon displayed next to each engine in the list. Or you can manually add engines from the search engines manager

Thanks so much for the reply. 
Just to update I have managed to add 3 search engines through mycroftproject.com like the way you explained but Not able to add this one https://www.lukol.com/

can you please guide how i can do it manually?

**Comment by ssborbis** [comment]
I'm not seeing an issue. What exactly isn't working when you try to add the engine?

![Peek 2022-10-04 18-03](https://user-images.githubusercontent.com/24310997/193946393-a6d8cb4a-ef26-4a5e-92c8-ae9d462bbcac.gif)

**Comment by rakitanc** [comment]
But sadly none of the methods not working on chrome

![imageedit_1_4963215245](https://user-images.githubusercontent.com/64612555/194038762-52584a5c-f381-4615-8903-ac6b16c47a3d.png)
![Screenshot from 2022-10-05 15-45-06](https://user-images.githubusercontent.com/64612555/194038786-87d25f95-feaa-467b-8b76-031850ce8ca3.png)

**Comment by MintMain21** [comment]
Alternatively, you could add it using the Taskbar pop-up.

**Comment by rakitanc** [comment]
> > But sadly none of the methods not working on chrome
> 
> Do you have the context menu enabled? CS Options -> `Enable searching via the context menu` + `Enable the context-menu item "Add Custom Search" on INPUT elements`

![Screenshot from 2022-10-06 00-47-45](https://user-images.githubusercontent.com/64612555/194143973-cfb18fa9-a1ff-46c5-be7b-23975126a580.png)
Yeah i already have it enable. Maybe some kind of bug is there

**Comment by ssborbis** [comment]
Using the latest Chromium, I'm not seeing any issues. You might try opening the context menu twice. Sometimes the menu is displayed before the menu entry is built. If that's not it, I'll do some troubleshooting with you.

**Comment by rakitanc** [comment]
> Using the latest Chromium, I'm not seeing any issues. You might try opening the context menu twice. Sometimes the menu is displayed before the menu entry is built. If that's not it, I'll do some troubleshooting with you.

Hey brother.. Thanks for all your support. It means a lot. I hardly see any people nowadays that is helping people with so much passion and patience as well. You are awesome

Btw, i managed to add Luko by using the manual method shared above

https://www.lukol.com/s.php?q=%s

Now the only thing i want is to seach on engines by one click like i shared with you before. Please guide me how to do that

**Comment by ssborbis** [comment]
![Peek 2022-10-05 20-47](https://user-images.githubusercontent.com/24310997/194196081-2244de4f-b597-43af-b492-21f97b9f4dc8.gif)

**Comment by ssborbis** [comment]
I'm still wonder whats up with the `Add to ContextSearch` menu not showing up. I wonder if it could be a conflict with another addon. You seem to have several with context menus. It'd be nice to sort that out.

**Comment by rakitanc** [comment]
Yayy..Got it working the multi engine. All Thanks to you

> I'm still wondering whats up with the `Add to ContextSearch` menu not showing up. I wonder if it could be a conflict with another addon. You seem to have several with context menus. It'd be nice to sort that out.

Yeah Sure Bro.. What can i do for you? Let's figure this out

I have already tried disabling these two extension which i was using before your extension. It didn't work

https://chrome.google.com/webstore/detail/search-by-image/cnojnbdhbhnkbcieeekonklommdnndci
https://chrome.google.com/webstore/detail/context-menu-search/ocpcmghnefmdhljkoiapafejjohldoga

**Comment by rakitanc** [comment]
I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit)
Pop Os linux

Bro..Doing some troubleshooting i managed to find out..It's an extension that is conflicting as after disabling all of them and running your extension..It Worked

How to find which one is conflicting?

**Comment by ssborbis** [comment]
I'll dig through the source code and see if there's a workaround

**Comment by ssborbis** [comment]
That addon appears to capture all right-click mousedown events and doesn't allow them to propagate. So any other addons using the mousedown event on the right mouse button might not work.

**Comment by rakitanc** [comment]
Oh okay brother..Just to use your extension i will remove this one

Btw i had some improvement request for the extension if you can implement it would be mean a lot

![Screenshot from 2022-10-07 18-51-11](https://user-images.githubusercontent.com/64612555/194563873-1a626c96-76ae-4167-9282-6f4f263aef91.png)
On this new tab page ..the context option comes this way. Is there a way to fix it? Because i use it a lot

This is the extension

https://chrome.google.com/webstore/detail/new-tab-draft/nmfjkeiebceinkbggliapgfdjphocpdh

**Comment by ssborbis** [comment]
That's odd you're getting a two-tier menu with only a single item in the 2nd tier. That should not be happening. I may need a copy of your config to see if there's a setting conflict happening.

**Comment by rakitanc** [comment]
How do i send it and where to find it?

**Comment by ssborbis** [comment]
CS Options -> Export ( Left pane ). You can drag & drop it here into your comments

**Comment by rakitanc** [comment]
Bro can't share json in comments😞
![Screenshot from 2022-10-08 19-22-43](https://user-images.githubusercontent.com/64612555/194710992-9e3b4965-a5e4-4bb6-84eb-6f166b2a2a61.png)

**Comment by rakitanc** [comment]
Had to use this online service

https://anonfiles.com/m0BaB2B5ye/ContextSearchOptions_2022-10-08_134906_json

**Comment by ssborbis** [comment]
Ah, I should have said to zip it first. That works, though

**Comment by ssborbis** [comment]
On some tabs that aren't really webpages, you might see the menu labeled `Search With` vs `Search for [searchTerms]`, but you should not be seeing that extra tier in the menu. I'm trying your profile, and nothing looks off. Does it do the same thing with other addons disabled? I can't really think of any reason why that would happen, unless maybe there's a bug with chrome causing a conflict between addons.

**Comment by rakitanc** [comment]
I have to check it out bro as its such a tedious and frustrating process doing the disabling extensions and see which one is the problem

But before that i have other queries to ask..So let's fix that first LOL

![Screenshot from 2022-10-09 03-07-32](https://user-images.githubusercontent.com/64612555/194728612-787b3da0-8653-4fa3-85c8-b1cbdbf74c02.png)

I don't know what setting i have changed that i can't seem to figure out but doing right click enables this pop up everytime, how to fix this?

**Comment by ssborbis** [comment]
> I don't know what setting i have changed that i can't seem to figure out but doing right click enables this pop up everytime, how to fix this?

CS Options -> Quick Menu -> General -> uncheck `Enable searching via popup menu`

**Comment by rakitanc** [comment]
> On some tabs that aren't really webpages, you might see the menu labeled `Search With` vs `Search for [searchTerms]`, but you should not be seeing that extra tier in the menu. I'm trying your profile, and nothing looks off. Does it do the same thing with other addons disabled? I can't really think of any reason why that would happen, unless maybe there's a bug with chrome causing a conflict between addons.

Hey bro..So just got done with this. Tried with all extensions disabled and the problem still persist. Please find a solution for this

**Comment by ssborbis** [comment]
I installed the latest chrome official on linux mint, but I can't get that bug. Have you tried other browsers to see if the bug is there too? I haven't seen anything like that in FF, Chrome, chromium, Waterfox, Vivaldi, or Edge

**Comment by rakitanc** [comment]
Working good on firefox😞

**Comment by rakitanc** [comment]
Having the same problem on Chrome incognito with just Your extension

**Comment by rakitanc** [comment]
My chrome version is this  103.0.5060.114 (Official Build) (64-bit)

**Comment by ssborbis** [comment]
I'm having trouble finding that version to test. I tested using the latest stable version ( 106.0.5249.119-1 ) and didn't have any issues. You may want to try updating Chrome and see if that fixes it.

**Comment by ssborbis** [comment]
Please re-open this thread if you are still having issues with adding engines.
