### ISSUE TITLE
"forceOpenResultsTabsAdjacent" issue

### ISSUE THREAD

**Issue by minawaheed9697** [ssborbis/ContextSearch-web-ext#581]
Hi there, 
When I enable this option "forceOpenResultsTabsAdjacent", it works and opens the tabs next to the parent tab, but it's not in the opened order i.e. every new opened tab will be adjacent to the parent tab not after the other opened tabs from the same parent tab. I want it to be chronological order, i.e. when I open a tab, it comes after the others tabs that are opened from the same parent tab. 
This GIF showing the issue https://imgur.com/wTDtZdC

**Comment by ssborbis** [comment]
What you describe as the behavior you want is the default behavior in my browsers as far as I can tell. Are you using any tab manager addons?

**Comment by minawaheed9697** [comment]
> What you describe as the behavior you want is the default behavior in my browsers as far as I can tell. Are you using any tab manager addons?

So, it opens in order in your browsers?? 
I have some but disabled by extension manager. Which addons can affect this behavior??

**Comment by ssborbis** [comment]
> So, it opens in order in your browsers??

Maybe it's a Chrome issue. Firefox doesn't seem to have that problem, but I am seeing it in Chromium. That must be why that seeing was added in the first place. I'll see if there's an easy way to track tab parents and order them like you're wanting

**Comment by minawaheed9697** [comment]
It was working on Firefox and Vivaldi and I remembered that it was the same issue before I leave Chrome. 
Thank you for help dear ❤️ Waiting for it

**Comment by ssborbis** [comment]
There's a potential fix in the dev branch now, if you're on Chrome

**Comment by ssborbis** [comment]
Wait on that fix for a minute. Something is still not right on a second look

**Comment by ssborbis** [comment]
Ok, I think it's fixed, but worth some testing.

**Comment by minawaheed9697** [comment]
> Ok, I think it's fixed, but worth some testing.

Okay, I'll test it soon and I'll tell you.

**Comment by minawaheed9697** [comment]
> Ok, I think it's fixed, but worth some testing.

But, is there any option I should enable or disable??

**Comment by ssborbis** [comment]
> But, is there any option I should enable or disable??

enable `forceOpenResultsTabsAdjacent` and it should respect the opening order from a parent tab

**Comment by minawaheed9697** [comment]
> it should respect the opening order from a parent tab
Yes, it works fine. Thank you so much.
When will it be updated??

**Comment by ssborbis** [comment]
Might be a while still. I have some other changes that need work before the next release.

**Comment by ssborbis** [comment]
v1.46 is up now. Had to wait on Mozilla to patch an issue with their linter before I could get a new release up.
