### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by logusergithub** [ssborbis/ContextSearch-web-ext#582]
Hi,

I have almost finished translating style.css and I am on about:debuggin to check message.json and apply corrections.

Sorry, a few clarifications:
- Line 339\343: requires a separate app: which app are we talking about to not get confused with the recent native app? I don't see it mentioned in the help section;
- Line 745\747: left\right Windows key: Windows Logo Key + Left\Right arrow?
- Line 1035: Sidebar: floating toolbar? But I obviously leave it as the original. To be honest I never understood when I open the Firefox sidebar what the ContextSearch section is also for.
Line 1169: Text: it seems to me that it includes both URL\Text and Grid\Text. Is it possible to create two separate entries? Absolutely not a big deal.
Line 1746: still experimental?
Line 2164: I have no problem translating this, but now that I am trying all the options when I select this one I don't seem to see changes to transate the meaning well. Would you give me an example screenshot. For example, thanks to a recent post, I understood what is meant by 'tiered' menu issue.

Thanks

PS: Line 2007\2152\2156 (locales\EN\message.json) are written in French

**Comment by ssborbis** [comment]
> Line 339\343: requires a separate app: which app are we talking about to not get confused with the recent native app? I don't see it mentioned in the help section;

That feature was depreciated when Firefox added the Search API allowing access to the FF search engines back in .. hmm FF63 maybe. I wouldn't worry much about the translation. If that message is still used somewhere, I should probably remove it

> Line 745\747: left\right Windows key: Windows Logo Key + Left\Right arrow?

I guess some keyboards have a Windows logo key to the left AND the right side of the Space bar. It should probably say `left Windows key`. To be honest, I'm not sure that key can actually be used with this addon. The translation was included for completeness.

> Line 1035: Sidebar: floating toolbar? But I obviously leave it as the original. To be honest I never understood when I open the Firefox sidebar what the ContextSearch section is also for.

I used the term "Sidebar" for a feature before Firefox ever had one. Mine is essentially a dockable Quick menu with some additional features. 

> Line 1169: Text: it seems to me that it includes both URL\Text and Grid\Text. Is it possible to create two separate entries? Absolutely not a big deal.

I'll look. I assume the dual usage doesn't work well in your language?

> Line 1746: still experimental?

You can leave it out. That feature is due for an overhaul anyway.

> Line 2164: I have no problem translating this, but now that I am trying all the options when I select this one I don't seem to see changes to transate the meaning well. Would you give me an example screenshot. For example, thanks to a recent post, I understood what is meant by 'tiered' menu issue.

I'm assuming you mean Line *1624*? `note: top-tier folders only`. 

I don't think that message is used any more so don't worry about it.

> PS: Line 2007\2152\2156 (locales\EN\message.json) are written in French

Thanks. I needed to convert some hard-coded string literals to i18n messages 

Thanks again for your translations!

**Comment by logusergithub** [comment]
> I guess some keyboards have a Windows logo key to the left AND the right side of the Space bar

Aaaaaaah, ok. I didn't know. I always had only one key with the Windows logo.

> I used the term "Sidebar" for a feature before Firefox ever had one. Mine is essentially a dockable Quick menu with some additional features.

Yep, as described in 'SideBarTooltip'.  Well, considering the icon and also the other translations I leave it that way. I admit that the first few times after installed the extension I was confused by the term.

> I'll look. I assume the dual usage doesn't work well in your language?
It works, but I preferred to translate as 'URL\Text (Testo)' and 'Grid\List (Elenco)' to differentiate all terms. There is a multitude of menus, bars, options and terms... :-)

> I'm assuming you mean Line 1264?

I refer to 'contextMenuContextualLayoutFlattenLimitTooltip'. 
At the moment I have used the French adaptation (in the ReadMe I will include thanks for the author whose translation has suggested some cues to me more than once).
Since I usually don't use many options available now I am trying to experiment to see if by chance I can translate better. Also considered the various entries are scattered I guess because the extension evolves.
In this case I selected this option and changed the limits but I don't see any changes in the context menu, so I translate but I don't know exactly what the result is.

Well, tomorrow night I should be able to fork it and put it online, then between any suggestions (and complains) or better understanding this first version will evolve.
While I'm at it I'll create somewhere a folder with personal external app, site:search, image reverse search settings (including ad hoc icons) and the last CSS in case some basic user like me needs it.

**Comment by ssborbis** [comment]
> I refer to 'contextMenuContextualLayoutFlattenLimitTooltip'.

Ok, so ... If you have [Context menu / Quick menu] > Advanced -> Contextual layout enabled, the menu will only show the engines with the current context ( link, image, selection, video, etc ) in the menus. If a user has some of those matching engines tucked away in folders, they would normally need to click through those folders to get to those context-matched engines. The option to flatten says, "if there are fewer than *n* number of matching engines, forget the folders and just show all the engines in the root menu.

**Comment by logusergithub** [comment]
Hi,

the message.json file should be available, I'll post the rest in a bit. In the meantime if it's helpful to you I post some images where I seem to notice that the option to translate is missing  or doesn't appear to me:

[![2022-10-10-00192.png](https://i.postimg.cc/MG814fF6/2022-10-10-00192.png)](https://postimg.cc/CRmZn50X)

[![2022-10-10-00193.png](https://i.postimg.cc/xTwmJbYv/2022-10-10-00193.png)](https://postimg.cc/D8c0R0S0)

[![2022-10-10-00194.png](https://i.postimg.cc/BQKL0QDX/2022-10-10-00194.png)](https://postimg.cc/VdzL9wK8)

[![2022-10-11-00198.png](https://i.postimg.cc/X7dPydd3/2022-10-11-00198.png)](https://postimg.cc/mtZjvcm6)

[![2022-10-10-00196.png](https://i.postimg.cc/hPTL002y/2022-10-10-00196.png)](https://postimg.cc/ZCYvb6tp)

[![2022-10-10-00197.png](https://i.postimg.cc/2SxnsSRn/2022-10-10-00197.png)](https://postimg.cc/k2BV8955)

Line 2166: (&A)?

**Comment by ssborbis** [comment]
> native app messages, cache, Icon\Inline\Block OK

Are these working or not working? The `OK` is throwing me off

> no more notification appears when adding the search engine on Firefox
> strangely, when I click on 'Add to ContextSearch' now the popup is all in English

These 2 might be related. There's a script missing somewhere. I'll push an update after this post.

> I don't quite understand 'Override context menu title. Use %s instead of searchTerms'. Context menu 'title'?

Normally, the context menu shows `Search xxxxx with ... ` or whatever the actual string is. That setting allows you to make it say whatever you want, where %s is the search term. So, if I set it to `Find me some %s ->`, and I highlight the word *bagels*, the menu will show `Find me some bagels -> `

> to send you changes: fork --> add 'it' folder --> the second option pull a request?

I believe so. I've only ever done it on my own repo, so I'm not 100% sure. I have to approve any changes before they get committed to my code, and I can review the code beforehand, so if something goes wrong I can just cancel the request.

**Comment by logusergithub** [comment]
> Are these working or not working?

They work.

> These 2 might be related. There's a script missing somewhere.

Okay if it's a script, because because if you need to edit message.json again I wait

> Normally, the context menu shows...

It's an option of such finesse that I wouldn't have figured it out! I thought it was related to some search settings (?q=%s) and wondered what the 'title' in the context menu had to do with it.

> I believe so.

I'll try again. I had chosen the first option, then with the last changes I reset that among other things I find it bad to edit online.

**Comment by logusergithub** [comment]
I don't know if actually any message were sent. In any case, I did the fork again and there there is a pull request with the files (1.46). 
Cheers

**Comment by ssborbis** [comment]
Excellent! Thank you so much. I pulled your changes into the development branch on my repo just now. The updates will be in the next release. Sorry it took me a while. I was looking for a push notification that wasn't there. I'm still learning this site's git interface.

**Comment by ssborbis** [comment]
FYI, I had to make some changes to all `messages.json` files, because I had a duplicate string `"Icon"` so one was renamed `"IconURI"`. I made the changes to your translation and pushed to my development branch. You may want to grab and updated copy before you make additional changes to yours.

**Comment by logusergithub** [comment]
Ok, I saved the changes (latest included) on my message.json on PC. 

> Sorry it took me a while. I was looking for a push notification that wasn't there.

Just as well, I had made some minor corrections in the days since my last post. It's probably me not knowing how to send those notifications I see. In case it was missed or you still have to work on it, it seems to me that the menu that pops up after 'Add to ContextSearch' is still displayed in English (it only affects the development branch).

**Comment by ssborbis** [comment]
> it seems to me that the menu that pops up after 'Add to ContextSearch' is still displayed in English (it only affects the development branch).

Hmm... You're on the latest development branch code? Could you post a screenshot just so I'm sure we're talking about the same menu? I"m looking at the code now, and I can't figure out why it wouldn't be reading from `messages.json`

**Comment by logusergithub** [comment]
IIt is the entire popup menu for adding a search engine. I put the screenshot where strangely the lines that should be shared are displayed with different languages. Maybe something is messed up when using about:debugging.

[![2022-10-25.png](https://i.postimg.cc/htW8BWMV/2022-10-25.png)](https://postimg.cc/D864rN9z)

**Comment by ssborbis** [comment]
Ah, I think I found the problem. Pushing a potential fix to dev now.

**Comment by logusergithub** [comment]
Hi,
was the last pull request correct considering that while checking the translation on about:debugging I noticed that there are new entries (Aditional actions)?

**Comment by ssborbis** [comment]
> Hi,
was the last pull request correct considering that while checking the translation on about:debugging I noticed that there are new entries (Aditional actions)?

I don't think I would say 100% correct. The pull was requesting the entire development branch be merged with the master branch, including your recent changes. So I grabbed your files.zip and put your files in the development branch, since I wasn't ready to merge the branches just yet.

I think the only thing that went wrong is you attempted to merge your changes to the master branch, instead of the development branch.

![image](https://user-images.githubusercontent.com/24310997/199625739-4fd85f5a-5e16-4f93-a99c-b5bd19e12782.png)

vs

![image](https://user-images.githubusercontent.com/24310997/199625815-866ad9a5-9ab3-4138-a105-b2fbf969595d.png)


The first would be the one you'd want to use I think. Again, I'm pretty new with using the web interface, so don't fret it.

**Comment by logusergithub** [comment]
Ok, thanks.
Given the useful new option, I await the availability (I guess) of the remaining lines to be translated related to the Additional Actions (Event, Button, Action, Shift \ click, double click, left middle, right, foward, back) and will give it another try as per the image.
At the limit I will appeal to a gif 'pull request for dummies' :-)

**Comment by ssborbis** [comment]
> I await the availability (I guess) of the remaining lines to be translated related to the Additional Actions (Event, Button, Action, Shift \ click, double click, left middle, right, foward, back)

Changes going up. 

Out of curiosity, how are you pulling updates and editing your changes? All on the website? Again, I don't have much experience using the web interface ( I use software that has git integration ), but I noticed a "Sync Fork" button 

![image](https://user-images.githubusercontent.com/24310997/199809095-2d23b1c8-507d-408d-b23d-341befda5676.png)

that I assume will update your fork with the latest changes from my repository. If I were editing via the web interface, I'd click that button to get all the latest updates, then merge/edit my locale files after.

**Comment by logusergithub** [comment]
> Out of curiosity, how are you pulling updates and editing your changes? All on the website?

Well, I am probably the black sheep among all the contributors because I simply download the development branch and then use Notepad++'s 'Compare' plugin (I find it more convenient) to view and edit the changes between the updated message.json and the backup I have on my pc. I also check the English and translated versions if I notice any changes in the final number of lines.
After that about:debugging to see the result, but after the latest corrections I just have to wait for any suggestions from the compatriots if they don't like it or I made some mistakes.

> but I noticed a "Sync Fork" button

I noticed that too, but for example do I have to fork the development as well which if I remember correctly Github asks for it at the beginning? The first time I added the files on the fork of the master and then clicked on the first option. The last time I did the pull request directly on your site. I have tried editing online but I find it better with Notepad++ and then at most I would replace the file to send. I understand the convenience of seeing online the changes, but this is a translation and not code with a language known among developers.

Condidered that the extension has so many options and explanations and for example also @7peanuts has included some additional (or updated) tips, perhaps a dedicated post where you can enter those minimal personal changes to share them (in English) could be useful to interested parties. So you can easily add them to the original version or evaluate.

**Comment by ssborbis** [comment]
> do I have to fork the development as well

I only make ongoing changes to the development branch, then merge with the master branch when I make a release. If you want to get updated code before a release, that's the only way to go.

> [7peanuts](https://github.com/7peanuts) has included some additional (or updated) tips

Where do you mean? The description keys in the messages.json?

**Comment by logusergithub** [comment]
> Where do you mean? The description keys in the messages.json?

In this case the help.htlml like the useful tip about alwaysAllowTileRearranging.

**Comment by ssborbis** [comment]
> In this case the help.html like the useful tip about alwaysAllowTileRearranging.

Gotcha.

v1.46 is live now with your translations. Thank you again. If you see something's still not right, open a new issue and we'll go from there.
