### ISSUE TITLE
Audio Search?

### ISSUE THREAD

**Issue by MintMain21** [ssborbis/ContextSearch-web-ext#588]
Just a simple question: What is Audio Search?

I get right-clicking on an image to reverse search that, but audio? Like, Shazam?

Please explain.

**Comment by ssborbis** [comment]
It was on the list of context types so I added it. I suppose if you had a website with audio elements and wanted to send those through an external app for downloading or processing, it might be useful for narrowing down engines. I've never personally found a use, but who's to say what others might find.
