### ISSUE TITLE
Can multisearch be added to the recently used as a complete and independent engine?

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#590]
Currently after performing a search using multisearch, the last&recently used history shows each engine it contains.

**Comment by ssborbis** [comment]
Is the Last Used tool not showing the multisearch engine? It's showing the last engine in the multisearch list instead?

I know I've looked into this before. If it's not working like it's supposed to, it's due to some recursion issues I never found a workaround for. I'll take another look, though.

**Comment by 7peanuts** [comment]
> It's showing the last engine in the multisearch list instead?
> 

Yes, I tested both on Firefox and Chromium.

**Comment by ssborbis** [comment]
The icon appears to be correct, but the referenced engine is wrong. I think I have a fix read in the dev branch.

**Comment by ssborbis** [comment]
fix is live in 1.46
