### ISSUE TITLE
Automatically load title links after search

### ISSUE THREAD

**Issue by Parvares** [ssborbis/ContextSearch-web-ext#592]
Hi Mike, I'm trying to use your extension with this template URL:

https://www.bibliotechediroma.it/opac/query/%s?context=tmatm

(where **%s** is to be replacede by the search key, for example _Stephen King_). 
I would like all the 15 resulting titles/records to be automatically opened after my search, so to have quickly the detailed records. 
Could you help me if possible (I guess with a Post-Search Script)?
Thanks very much!

**Comment by ssborbis** [comment]
Something like...

```javascript
document.querySelectorAll(".titololistarisultati a[href][title]").forEach( a => {
    window.open(a.href,"_blank");
});
```

**Comment by Parvares** [comment]
Great, really useful for me, thanks very much!!! 
Is there a way to gather all the resulting tabs in only one page? Would be perfect!

**Comment by ssborbis** [comment]
What part of the results page are you wanting on one page?

**Comment by Parvares** [comment]
<img width="945" alt="OPAC" src="https://user-images.githubusercontent.com/55709458/200164695-feb88a5e-41e5-4fc0-a1aa-049c7d00139b.png">

Possibly something like in the attachment (repeated for 15 records)... 
Thanks!

**Comment by ssborbis** [comment]
```javascipt
( async() => {
  
  let links = [...document.querySelectorAll(".titololistarisultati a[href][title]")];

  for ( let i in links ) {
      let link = links[i];
    
      let f = document.createElement('iframe');
      f.style.display = 'none';
      document.body.appendChild(f);
      f.onload = async () => {
        await new Promise(r => setTimeout(r, 100));
        f.contentWindow.document.getElementById("tabDocument_item_tabcata").click();
        await new Promise(r => setTimeout(r, 100));
        let tab = f.contentWindow.document.getElementById("tabcata");
        let content = tab.outerHTML;
        document.querySelector(`#listadocumenti_${i}`).innerHTML = content;     
      }
      
      f.src = link.href;
      await new Promise(r => setTimeout(r, 100));
    }
})();
```

Be aware, it takes time to load all those iframes

**Comment by Parvares** [comment]
Incredible, works like a charm, thanks really so much! Is it possible to have the same result when I pass from page 1 (with 15 results) to page 2 (with other 15 results), to page 3, and so on? Would be perfect! Thanks again!!! :)

**Comment by ssborbis** [comment]
The Post-Search script will only run once, on the results landing page ( page 1 of results ). To run the script anywhere else, you might try copying it to a new **Script**-type engine, and click that engine when you go to the next page. Or, bind a hotkey to that engine and just press a button to run the script.

**Comment by ssborbis** [comment]
This may be a task better suited for tampermonkey. I'm guessing you could reuse that script and have it run on every results page

**Comment by Parvares** [comment]
Thanks Mile! I went to this page: 
_chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/options.html#nav=new-user-script+editor_
pasted and saved your script, but I'm getting "Invalid script", is this the right procedure?

![tampermonkey](https://user-images.githubusercontent.com/55709458/200500190-98da5840-7acb-4131-b535-94cd416deaa0.png)

**Comment by ssborbis** [comment]
> Should I fill the metadata 

You should definitely restrict it to running on `https://www.bibliotechediroma.it/opac/query/*`

**Comment by ssborbis** [comment]
It worked for me using

```javascript
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.bibliotechediroma.it/opac/query/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=bibliotechediroma.it
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    ( async() => {

        let links = [...document.querySelectorAll(".titololistarisultati a[href][title]")];

        for ( let i in links ) {
            let link = links[i];

            let f = document.createElement('iframe');
            f.style.display = 'none';
            document.body.appendChild(f);
            f.onload = async () => {
                await new Promise(r => setTimeout(r, 100));
                f.contentWindow.document.getElementById("tabDocument_item_tabcata").click();
                await new Promise(r => setTimeout(r, 100));
                let tab = f.contentWindow.document.getElementById("tabcata");
                let content = tab.outerHTML;
                document.querySelector(`#listadocumenti_${i}`).innerHTML = content;
            }

            f.src = link.href;
            await new Promise(r => setTimeout(r, 100));
        }
    })();
})();
```

I also set the following
![image](https://user-images.githubusercontent.com/24310997/200662723-f8def65d-9d98-4839-9c72-b3acedd7a241.png)

**Comment by ssborbis** [comment]
If you use that script, remove the Post-Search Script from that engine

**Comment by ssborbis** [comment]
Actually, I take that back. I'm not getting the changes when going to another page. You might need more code for that

**Comment by Parvares** [comment]
Okay, thanks again, now it works with Tampermonkey following your settings (except "Position:1", I haven't position 2)! I noticed the script only works with your extension, is it possible let the script work with and without your extension?

**Comment by ssborbis** [comment]
Try this in tampermonkey
```javascript
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.bibliotechediroma.it/opac/query/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=bibliotechediroma.it
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    let url = window.location.href;

   const main = async() => {

        let links = [...document.querySelectorAll(".titololistarisultati a[href][title]")];

       let startIndex = (() => {
           let id = document.querySelector(".list-document > LI").id;
           return parseInt(id.match(/listadocumenti_(\d+)/)[1]);
       })();

       //console.log('start index', startIndex);

        for ( let i in links ) {
            try {
                let link = links[i];
                let index = parseInt(i) + parseInt(startIndex);

                //console.log("index: " + index, link.href);

                let f = document.createElement('iframe');
                f.style.display = 'none';
                document.body.appendChild(f);
                f.onload = async () => {
                    try {
                    await new Promise(r => setInterval(() => {
                        if ( f.contentWindow.document.getElementById("tabDocument_item_tabcata") )
                            r();
                    }, 100));

                    f.contentWindow.document.getElementById("tabDocument_item_tabcata").click();
                    await new Promise(r => setTimeout(r, 100));
                    let tab = f.contentWindow.document.getElementById("tabcata");
                    let content = tab.outerHTML;
                    document.querySelector(`#listadocumenti_${index}`).innerHTML = content;
                    } catch (error) { console.log(error)}
                }

                f.src = link.href;
            } catch (error) {
                console.log(error);
            }

            await new Promise(r => setTimeout(r, 100));
        }
    }

   main();

   setInterval(() => {
       if ( window.location.href !== url ) {
           //console.log('href change');
           url = window.location.href;
           main();
       }
   }, 1000);


})();
```

**Comment by Parvares** [comment]
Absolutely astonishing, thanks so much, Mike, all is working perfectly!! 
P.S. Is this warning important in line 44?
_eslint: curly - expected { after 'if' condition_


![eslint tampermonkey](https://user-images.githubusercontent.com/55709458/201030973-a6232b92-f97d-4d51-afe4-3b84f7e3f5d8.png)

**Comment by ssborbis** [comment]
> Is this warning important in line 44?

Nah, just a style choice that particular linter config doesn't like. You could rewrite that line as the following and get rid of the warning, but it makes no difference in the code.

```javascript
if ( f.contentWindow.document.getElementById("tabDocument_item_tabcata") ) {
    r();
}
```

**Comment by Parvares** [comment]
Great, thanks again for you time!!

**Comment by Parvares** [comment]
Hi Mike, may I ask a little variotion on this script? Is it possible to have the same kind of list (15 records per page), but getting from the single records not the tab "_Scheda_" as in the above script, but the tab "_Lo trovi in_", possibly opening the label "Biblioteca Elsa Morante", as in the attachment? Thanks ever so much!

![list](https://user-images.githubusercontent.com/55709458/202848212-e4b4e1b3-503b-49fb-9771-3f5ea9cb2381.jpg)

**Comment by ssborbis** [comment]
The difference would be with this line

```javascript
f.contentWindow.document.getElementById("tabDocument_item_tabcata").click();
```

That's where the Scheda tab is clicked. Simply omit that line or comment it out with `//` to see the Lo Trovi in tab, since it's the default shown. Clicking the "Biblioteca Elsa Morante" would be done in the same manner. You just need to replace tabDocument_item_tabcata" with the proper selector. You can inspect the DOM in the browser with CTRL+SHIFT+I to find a selector that works ( usually the id of the element to be clicked ) . I'll check myself later if you haven't found a solution.

**Comment by Parvares** [comment]
Mhm, thank you, but didn't solve. I tryed replacing: 

f.contentWindow.document.getElementById("**tabDocument_item_tabcata**").click();

with:

f.contentWindow.document.getElementById("**bibliosel2**").click();

Don't know if is the right ID (I found only that one).

**Comment by ssborbis** [comment]
Do you have a link to a page with a "Biblioteca Elsa Morante" tab? I'm not sure what search would get me a link that does.

**Comment by ssborbis** [comment]
Nevermind, I found it.

Try this selector

```javascript
document.querySelector('#biblioteche [onclick*="Morante"]').click();
```

**Comment by Parvares** [comment]
Sorry Mike, I replaced:

`f.contentWindow.document.getElementById("tabDocument_item_tabcata").click();
`

with:

`document.querySelector('#biblioteche [onclick*="Morante"]').click();
`

But gives me the same results as the first script.

So I tryed replacing: 

_let tab = f.contentWindow.document.getElementById("tabcata");_

with:

_`document.querySelector('#biblioteche [onclick*="Morante"]').click();_

But the result is the same.

**Comment by Parvares** [comment]
?

**Comment by Parvares** [comment]
.

**Comment by ssborbis** [comment]
I'll check it out. It's the holidays here so I've been preoccupied.

**Comment by ssborbis** [comment]
I'm really not sure what you're trying to achieve, but this script will "click" a Biblioteca Elsa Morante tab, if one exists, and display that instead of the Scheda tab

```javascript
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.bibliotechediroma.it/opac/query/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=bibliotechediroma.it
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    let url = window.location.href;

   const main = async() => {

        let links = [...document.querySelectorAll(".titololistarisultati a[href][title]")];

       let startIndex = (() => {
           let id = document.querySelector(".list-document > LI").id;
           return parseInt(id.match(/listadocumenti_(\d+)/)[1]);
       })();

       //console.log('start index', startIndex);

        for ( let i in links ) {
            try {
                let link = links[i];
                let index = parseInt(i) + parseInt(startIndex);

                //console.log("index: " + index, link.href);

                let f = document.createElement('iframe');
                f.style.display = 'none';
                document.body.appendChild(f);
                f.onload = async () => {
                    try {
                        await new Promise(r => setInterval(() => {
                            if ( f.contentWindow.document.getElementById("tabDocument_item_tabcata") )
                                r();
                        }, 100));

                        let tab;

                        let morante = f.contentWindow.document.querySelector('#biblioteche [onclick*="Morante"]');

                        if ( morante ) {
                            morante.click();
                            await new Promise(r => setTimeout(r, 100));
                            tab = f.contentWindow.document.getElementById("tabloca");
                        } else {
                            f.contentWindow.document.getElementById("tabDocument_item_tabcata").click();
                            await new Promise(r => setTimeout(r, 100));
                            tab = f.contentWindow.document.getElementById("tabcata");
                        }

                        let content = tab.outerHTML;
                        document.querySelector(`#listadocumenti_${index}`).innerHTML = content;
                    } catch (error) { console.log(error)}
                }

                f.src = link.href;
            } catch (error) {
                console.log(error);
            }

            await new Promise(r => setTimeout(r, 100));
        }
    }

   main();

   setInterval(() => {
       if ( window.location.href !== url ) {
           //console.log('href change');
           url = window.location.href;
           main();
       }
   }, 1000);


})();
```

**Comment by Parvares** [comment]
Thanks for your reply, Mike, and thanks for your time! Yes, as you wrote, the script should click "Biblioteca Elsa Morante" tab, but if you try it the results are a bit confusing, even filtering upstream by library ("Biblioteca Morante) and resource ("Libri moderni", so avoiding ebooks, that are without localization). I attach you the desired results, where each record should include the title/abstract part and the "Lo trovi in" tab. 
Thanks again!

![lo trovi in](https://user-images.githubusercontent.com/55709458/204163626-e4280c7f-cb63-455d-85b9-d3c26e0adb7f.jpg)

**Comment by ssborbis** [comment]
If you're just wanting the listings of the original search page replaced with the content of the result page links, that's easy enough. The problem is, the "tabs" will most likely not be clickable because the events won't be copied when displayed on the original results page. So you either need to "click" them programmatically before displaying them, or load each result link into an iframe and display the iframe on the original results page. Again, I don't know what you're doing after getting the results, so I can't say which approach is better.

**Comment by ssborbis** [comment]
From the queries I've run, not every result has a "Biblioteca Morante" tab, so how would the results look then?

**Comment by Parvares** [comment]
Doesn't matter, moreover I can filter the results by library ("Biblioteca Morante") upstream and downstream. 

![upstream](https://user-images.githubusercontent.com/55709458/204990420-395ea321-a222-41fb-9108-b0f5f02cdcde.JPG)

--------------------------------------------------------------------------------------------------------------------------------------------

![downstream](https://user-images.githubusercontent.com/55709458/204990562-c4ce7c69-ed51-4e7f-9cba-58b2200b8a7e.JPG)

**Comment by ssborbis** [comment]
I tested the iframe method and it doesn't seem to work. The host site throws some errors, so you might be stuck copying the DOM and pasting it into the results page.

Are you just trying to get this content to display on the main results page?

```
Inventario 58452
Collocazione ADO  813.5        KIN
```

**Comment by Parvares** [comment]
Wao, thanks, the results seem almost perfect! Yes, that was what I expected, except the fact that not every "Biblioteca Morante" record display the iframe. Isn't it there a workaround that comes to your mind? Thanks again!

**Comment by ssborbis** [comment]
> except the strange fact that not every "Biblioteca Morante" record display the iframe. Isn't it there a workaround that comes to your mind? Thanks again!

Do you have an example URL I can look at?

**Comment by Parvares** [comment]
> Do you have an example URL I can look at? 
Sorry, what do you mean?

**Comment by Parvares** [comment]
> Do you have an example URL I can look at?

Sorry, what do you mean?

**Comment by ssborbis** [comment]
If you perform a search and see a results page where not every Biblioteca Morante result is displayed properly, copy the URL and and paste it here so I can see what you're seeing.

**Comment by Parvares** [comment]
In this example only the last two records display the iframe. So these links for example are not correct:

https://www.bibliotechediroma.it/opac/resource/luomo-vestito-di-nero-stephen-king-illustrazioni-di-ana-juan-traduzione-di-silvia-fornasiero-con-il-/RMB1009634

https://www.bibliotechediroma.it/opac/resource/elevation/RMB0896833

https://www.bibliotechediroma.it/opac/resource/fairy-tale-romanzo/RMB1065955



![Morante](https://user-images.githubusercontent.com/55709458/206119921-e3b8afe5-7408-4e3b-be2e-f2fe5216ee22.png)

**Comment by ssborbis** [comment]
what is the query URL? 

example: 

https://www.bibliotechediroma.it/opac/query/stephen%20king?context=tmatm

**Comment by Parvares** [comment]
https://www.bibliotechediroma.it/opac/query/stephen%20king?bib=RMBO2&context=tmatm

**Comment by ssborbis** [comment]
Gotcha. Oddly, it works fine for me

**Comment by ssborbis** [comment]
Ah, it looks like some links open to this tab `Contiene` and mess up the script.

This script would run much faster if you only checked links that show `Biblioteca Elsa Morante ` in the `Lo Trovi In` list on the results page.

**Comment by Parvares** [comment]
I tryed in different ways, there are always some results that don't display the iframe...

**Comment by ssborbis** [comment]
> I noticed that the script works much better with Firefox. Searching for "Stephen King" and filtering by RMBO2 I get 4 pages, and only 4 records without iframe, not perferct but very near, congrats Mike!!!

It may never work 100% of the time due to the fact it's loading every result in an iframe, but I'm sure the code can be tweaked a bit. One problem is the linked pages aren't consistent in how they display information. I think one bug happens when there is only one `Lo Trovi In`. There are others too that can be accounted for, given enough code.

**Comment by Parvares** [comment]
Yes, the major bug seems to be when there's only one library in` Lo Trovi in`. It would be great if you could find a way to get over it! Thanks again!

**Comment by ssborbis** [comment]
Do you really need this info for every result, or only a few? It may be a lot faster to create a button to click to load the info for only the results you need, vs loading every link into an iframe

**Comment by Parvares** [comment]
Yes, generally I need this info for almost every result (except the records withe `contiene` tab), as I need to compare them through a panoramic view. As to the other method, if I understood I would need to click 15 records per page before displaying the tabs, is that right? Maybe if I see an example I I would better realize. Thank you again, Mike!

**Comment by ssborbis** [comment]
This seems to give the best results so far. 

```javascript
// ==UserScript==
// @name         bibliotechediroma
// @namespace    http://tampermonkey.net/
// @version      0.2
// @description  try to take over the world!
// @author       You
// @match        https://www.bibliotechediroma.it/opac/query/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=bibliotechediroma.it
// @grant        none
// ==/UserScript==

// https://www.bibliotechediroma.it/opac/query/stephen%20king?context=tmatm

(function() {
    'use strict';

    let url = window.location.href;

   const main = async() => {

       await new Promise(r => setTimeout(r, 500));

       if ( window != top ) return;

       let links = [...document.querySelectorAll(".titololistarisultati a[href][title]")];

       let startIndex = (() => {
           let el = document.querySelector(".list-document > LI");

           if ( ! el ) return -999999;

           let id = el.id;

           if ( !id ) return -999999;

           let num = id.match(/listadocumenti_(\d+)/)[1];

           return parseInt(num);
       })();

        for ( let i=0;i<links.length;i++ ) {

            try {
                let link = links[i];
                let index = i + startIndex;

                let id = `#listadocumenti_${index}`;

                let li = document.querySelector(id);

                let container = document.createElement('div');
                container.style = 'margin-left:16px';
                container.innerText = " [ loading ] ";

                container.onclick = () => { f.src = f.src }

                li.appendChild(container);

                let f = document.createElement('iframe');
                f.style.display = 'none';
                document.body.appendChild(f);

                f.onload = async () => {

                    if ( f.src === null ) return;

                    try {
                        await new Promise(r => setInterval(() => {
                            if ( f.contentWindow.document.getElementById("tabDocument_item_tabloca") )
                                r();
                        }, 100));

                        f.contentWindow.document.getElementById("tabDocument_item_tabloca").click();

                        await new Promise(r => setTimeout(r, 100));

                        let morante = f.contentWindow.document.querySelector('#biblioteche [onclick*="Morante"]');

                        if ( morante ) morante.click();

                        await new Promise(r => setInterval(() => {
                            if ( f.contentWindow.document.querySelector('.inventario') )
                                r();
                        }, 100));

                        let tab = f.contentWindow.document.querySelector('.inventario');

                        let content = tab.outerHTML;
                        li.appendChild(tab);
                        container.parentNode.removeChild(container);

                    } catch (error) {
                        container.innerText = " [ failed ] ";
                        console.log(error)
                    }

                    f.src = null;
                }

                f.onerror = () => {
                    container.innerText = " [ failed ] ";
                    f.src = null;
                }

                f.src = link.href;
            } catch (error) {
                console.log(error);
            }

            await new Promise(r => setTimeout(r, 100));
        }
    }

   main();

   setInterval(() => {
       if ( window.location.href !== url ) {
           //console.log('href change');
           url = window.location.href;
           main();
       }
   }, 1000);


})();
```

**Comment by Parvares** [comment]
Thanks Mike, the results are better but seem slower than the other script (on Chrome too)... I think I'll use the previous one, thanks again!

**Comment by Parvares** [comment]
Hi Mike, I installed _TamperMonkey_ extension on Android (I tried both _Kiwi Browser_ and _Firefox Nightly_). I can't get the script working , should I set something in _Tampermonkey_ Settings? Thanks!

**Comment by ssborbis** [comment]
The last script I posted works for me in Firefox Nightly on Android. I haven't checked Kiwi

**Comment by Parvares** [comment]
Sorry, Mike, it works indeed with both browsers, maybe I did some pasting error, thank you!

**Comment by Parvares** [comment]
Hi Mike, may I ask you another related question (I don't know if feasible)? 
Is it possible to aggregate multiple tabs (search results) on one long page?

For example:
1) https://www.bibliotechediroma.it/opac/resource/RMB0067413
2) https://www.bibliotechediroma.it/opac/resource/RMB0125664
3) https://www.bibliotechediroma.it/opac/resource/RMB0000886

should be converted to this...

![single page](https://user-images.githubusercontent.com/55709458/210766414-b2fbb06e-6d08-4c6f-a90e-4fe2d7230c22.jpg)


Thank you very much!

**Comment by ssborbis** [comment]
It's likely possible, but not exactly simple. I'm not familiar with tampermonkey enough to say for sure.

**Comment by Parvares** [comment]
Okay, never mind if it's hard, thanks anyway!

**Comment by Parvares** [comment]
Hi, Mike, may a ask a little variation of the above script (post Dec 11, 2022), if you can help me? 
The iframes of that script display the results of "Lo trovi in" > "Biblioteca Morante" tab, if one exists (post Nov 27, 2022). Is it possible to display instead for every record how many times there is this string "Documento in prestito"? 
For example in this [case](https://www.bibliotechediroma.it/opac/resource/sete/RMB0840047) a record should display: 
Documento in prestito: 3 times

Thanks very much!!







> ```js
> // ==UserScript==
> // @name         bibliotechediroma
> // @namespace    http://tampermonkey.net/
> // @version      0.2
> // @description  try to take over the world!
> // @author       You
> // @match        https://www.bibliotechediroma.it/opac/query/*
> // @icon         https://www.google.com/s2/favicons?sz=64&domain=bibliotechediroma.it
> // @grant        none
> // ==/UserScript==
> 
> // https://www.bibliotechediroma.it/opac/query/stephen%20king?context=tmatm
> 
> (function() {
>     'use strict';
> 
>     let url = window.location.href;
> 
>    const main = async() => {
> 
>        await new Promise(r => setTimeout(r, 500));
> 
>        if ( window != top ) return;
> 
>        let links = [...document.querySelectorAll(".titololistarisultati a[href][title]")];
> 
>        let startIndex = (() => {
>            let el = document.querySelector(".list-document > LI");
> 
>            if ( ! el ) return -999999;
> 
>            let id = el.id;
> 
>            if ( !id ) return -999999;
> 
>            let num = id.match(/listadocumenti_(\d+)/)[1];
> 
>            return parseInt(num);
>        })();
> 
>         for ( let i=0;i<links.length;i++ ) {
> 
>             try {
>                 let link = links[i];
>                 let index = i + startIndex;
> 
>                 let id = `#listadocumenti_${index}`;
> 
>                 let li = document.querySelector(id);
> 
>                 let container = document.createElement('div');
>                 container.style = 'margin-left:16px';
>                 container.innerText = " [ loading ] ";
> 
>                 container.onclick = () => { f.src = f.src }
> 
>                 li.appendChild(container);
> 
>                 let f = document.createElement('iframe');
>                 f.style.display = 'none';
>                 document.body.appendChild(f);
> 
>                 f.onload = async () => {
> 
>                     if ( f.src === null ) return;
> 
>                     try {
>                         await new Promise(r => setInterval(() => {
>                             if ( f.contentWindow.document.getElementById("tabDocument_item_tabloca") )
>                                 r();
>                         }, 100));
> 
>                         f.contentWindow.document.getElementById("tabDocument_item_tabloca").click();
> 
>                         await new Promise(r => setTimeout(r, 100));
> 
>                         let morante = f.contentWindow.document.querySelector('#biblioteche [onclick*="Morante"]');
> 
>                         if ( morante ) morante.click();
> 
>                         await new Promise(r => setInterval(() => {
>                             if ( f.contentWindow.document.querySelector('.inventario') )
>                                 r();
>                         }, 100));
> 
>                         let tab = f.contentWindow.document.querySelector('.inventario');
> 
>                         let content = tab.outerHTML;
>                         li.appendChild(tab);
>                         container.parentNode.removeChild(container);
> 
>                     } catch (error) {
>                         container.innerText = " [ failed ] ";
>                         console.log(error)
>                     }
> 
>                     f.src = null;
>                 }
> 
>                 f.onerror = () => {
>                     container.innerText = " [ failed ] ";
>                     f.src = null;
>                 }
> 
>                 f.src = link.href;
>             } catch (error) {
>                 console.log(error);
>             }
> 
>             await new Promise(r => setTimeout(r, 100));
>         }
>     }
> 
>    main();
> 
>    setInterval(() => {
>        if ( window.location.href !== url ) {
>            //console.log('href change');
>            url = window.location.href;
>            main();
>        }
>    }, 1000);
> 
> 
> })();
> ```

**Comment by ssborbis** [comment]
Ok, after looking a bit more, it seems you'd need your script to "click" each of those locations ( 6 in the image I linked ) to get the page to generate the `div.inventario` elements. I'm still a bit unsure what you're wanting. Do you want to simply count the number of libraries listed ( 6 in this case )?

**Comment by ssborbis** [comment]
Maybe something like this:

```javascript
// ==UserScript==
// @name         bibliotechediroma ( counting )
// @namespace    http://tampermonkey.net/
// @version      0.2
// @description  try to take over the world!
// @author       You
// @match        https://www.bibliotechediroma.it/opac/query/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=bibliotechediroma.it
// @grant        none
// ==/UserScript==

// https://www.bibliotechediroma.it/opac/query/stephen%20king?context=tmatm

(function() {
    'use strict';

    let url = window.location.href;

    const main = async() => {
        await new Promise(r => setTimeout(r, 500));

        if (window != top) return;

        let links = [...document.querySelectorAll(".titololistarisultati a[href][title]")];

        let startIndex = (() => {
            let el = document.querySelector(".list-document > LI");

            if (!el) return -999999;

            let id = el.id;

            if (!id) return -999999;

            let num = id.match(/listadocumenti_(\d+)/)[1];

            return parseInt(num);
        })();

        for (let i = 0; i < links.length; i++) {
            try {
                let link = links[i];
                let index = i + startIndex;

                let id = `#listadocumenti_${index}`;
                let li = document.querySelector(id);

                let container = document.createElement('div');
                container.style = 'margin-left: 16px';
                container.innerText = " [ loading ] ";

                li.appendChild(container);

                let f = document.createElement('iframe');
                f.style.display = 'none';
                document.body.appendChild(f);

                f.onload = async function () {
                    if (f.src === null) return;

                    try {
                        await new Promise(function (r) {
                            setInterval(function () {
                                if (f.contentWindow.document.getElementById("tabDocument_item_tabloca"))
                                    r();
                            }, 100);
                        });

                        f.contentWindow.document.getElementById("tabDocument_item_tabloca").click();

                        await new Promise(function (r) {
                            setTimeout(r, 100);
                        });

                        let occurrences = 0;
                       // let elements = f.contentWindow.document.querySelectorAll('div.inventario');
                        let elements = f.contentWindow.document.querySelectorAll('#biblioteche > UL > LI > A');

                        for ( let element of elements ) {

                            element.click();

                            await new Promise(function (r) {
                                setTimeout(r, 50);
                            });

                            let info = f.contentWindow.document.querySelector('div.inventario');
                            if (info && info.textContent.includes('Rientro previsto')) {
                                occurrences++;
                            }
                        }

                        let infoContainer = document.createElement('div');
                        infoContainer.innerText = "Occurrences: " + occurrences;
                        li.appendChild(infoContainer);
                        container.parentNode.removeChild(container);
                    } catch (error) {
                        container.innerText = " [ failed ] ";
                        console.log(error)
                    }

                    f.src = null;
                };

                f.onerror = function () {
                    container.innerText = " [ failed ] ";
                    f.src = null;
                };

                f.src = link.href;
            } catch (error) {
                console.log(error);
            }

            await new Promise(function (r) {
                setTimeout(r, 100);
            });
        }
    };

    main();

    setInterval(function () {
        if (window.location.href !== url) {
            url = window.location.href;
            main();
        }
    }, 1000);
})();
```

**Comment by Parvares** [comment]
Hi Mike, sorry I didn't get the notification, I only noticed your reply today! :-( 
Regarding the [link](https://www.bibliotechediroma.it/opac/resource/sete/RMB0840047), yes i simply want to count the number of libraries listed which have the string "rientro previsto", but this is the path to detect them: "Apri la lista completa (20)" > "Tutte le biblioteche" [all libraries]. That's it, thank again!!
