### ISSUE TITLE
"Copy to clipboard" doesn't work in v1.46

### ISSUE THREAD

**Issue by krisu5** [ssborbis/ContextSearch-web-ext#596]
Doesn't add the selected text to the clipboard.

**Comment by ssborbis** [comment]
What browser?

**Comment by ssborbis** [comment]
Nevermind, I'm seeing it now. Fix going up 1.46.1. Thanks for the bug report.

**Comment by krisu5** [comment]
Fixed! Yeah sorry, I forgot (it was Firefox 106.0.5).
