### ISSUE TITLE
v1.46.4 Browser toolbar ‘add to blocklist’ button can't be used

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#599]
The block button in the quick menu toolbar can be used.

![-gif-1](https://user-images.githubusercontent.com/82173614/201266436-70b0e60b-50f2-4ca2-80ac-ef0c87003cc9.gif)

**Comment by ssborbis** [comment]
Hmm.. I don't think that's anything new. It doesn't look like I enabled it for the toolbar. I'll see why not.

**Comment by ssborbis** [comment]
Ah yes, now I see why. The toolbar menu wasn't resizing when prompted with a `confirm()` message and the modal was being cut off. I added some logic and pushed to the dev branch.

**Comment by 7peanuts** [comment]
> Hmm.. I don't think that's anything new. It doesn't look like I enabled it for the toolbar.

I remember that the browser toolbar button was available in the version two months ago, I raised the issue at that time.
➡️ [BUG] Websites added to the blocklist cannot be deleted on Firefox #570
