### ISSUE TITLE
Google Images and Google Lens engines

### ISSUE THREAD

**Issue by MW-J97** [ssborbis/ContextSearch-web-ext#600]
Hi, 

I want engines for those above sites for reverse image search. As the old engine for Google Images is not working. 
This is the old: https://www.google.com/searchbyimage?site=search&image_url={searchTerms}

**Comment by 7peanuts** [comment]
https://github.com/dessant/search-by-image/issues/221
It looks like Google has changed the api.
Hoping to find a solution. 😱

**Comment by 7peanuts** [comment]
https://github.com/dessant/search-by-image/issues/221
It looks like Google has changed the api.
Hoping to find a solution. 😱

**Comment by minawaheed9697** [comment]
Yes, I think so, as even iOS Shortcuts for reverse image not working on Google engine.

**Comment by ssborbis** [comment]
This works for me in FF on desktop `https://lens.google.com/uploadbyurl?url=%s`

**Comment by minawaheed9697** [comment]
> https://lens.google.com/uploadbyurl?url=%s

It works. Thank you so much. 
But, for the old view of Google Image search that now called "Find image source", is there any engine for it??

**Comment by ssborbis** [comment]
> But, for the old view of Google Image search that now called "Find image source", is there any engine for it??

I don't know what the old site looked like. When you search an image URL using plain old google, it redirects to google images. Dunno if that's what you're looking for...

**Comment by ssborbis** [comment]
If the results you want are where you are redirected when you click "Find Image Source", just write some post-search script to click that link

**Comment by maggotb** [comment]
> > But, for the old view of Google Image search that now called "Find image source", is there any engine for it??
> 
> I don't know what the old site looked like. When you search an image URL using plain old google, it redirects to google images. Dunno if that's what you're looking for...

He's talking about [this](https://www.google.com/search?tbs=sbi:AMhZZisENpiSnq-G_1jXPCzaTexv_1BmXOA2IIVs8mCHgQzKBQ7pHbVvYGZ_1LIIpAs4xM5wtLgax2dVnz3PzDzanf9wpikY7zCiZxkKXhaPYiWvHkISTX4N4eteSGxSXwQ2cjSLAGt_1-h1778IEvX85Po2P_1jzkag7N_1Y8hjaNyZA-FPNuAUnK3vb1DjsyZ5aO9gko608bIT2TLUyneDS_1f8G3RUS-_1Fvic0B1OmjsiTG863WOuOB0UoPqWneGd8V8puVYIBUslTPmgiggNmig6SIbWtbD6aKYlrN_1YtO10tvZ1dhHNhE0H13qrXW0mE2Pykiq-8_17NKD0WMRgUcsmzNucAQV7pNRykA)

It works with [search image extension](https://github.com/dessant/search-by-image/issues/221) maybe there's a way to fix it

**Comment by 7peanuts** [comment]
> I don't know what the old site looked like. 

Google reverse image search, it is available in the default engine of ContextSsearch, but due to some changes in Google, it doesn't work now. I hope it's only temporary. 😮

**Comment by ssborbis** [comment]
CS can import / export single engines now. Try unzipping this and importing.

It's the google lens engine with code to click the Find Image Source link

[google_lens_to_images.json.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/9993869/google_lens_to_images.json.zip)

**Comment by minawaheed9697** [comment]
> google_images_old.json.zip

So, what should I do with this? Will I use script extension like Tampermonkey?

**Comment by ssborbis** [comment]
> So, what should I do with this? Will I use script extension like Tampermonkey?

Nah, unzip it, then import the json. Latest versions of CS allow individual or groups of engines to be imported / exported

**Comment by maggotb** [comment]
[This add-on](https://addons.mozilla.org/fr/firefox/addon/capture-reverse-image-search/) uses google images directly [Source](https://github.com/schomery/reverse-image-search/blob/master/v3/worker.js)

Maybe an {image} parameter to upload the image could work?

Also [this](https://github.com/ccd0/4chan-x/issues/3307#issuecomment-1318522986) seems to be a fix

**Comment by bohdansok** [comment]
> > https://lens.google.com/uploadbyurl?url=%s
> 
> It works. Thank you so much.

It does woeks but from desktop browsers only. And it doesn't if you are trying to use this URL from mobile device.

**Comment by ssborbis** [comment]
> Maybe an {image} parameter to upload the image could work?

It depends on the website's API for handling requests. I can pretty easily convert images to data URIs to submit to GET/POST engines, but it gets much trickier if the websites rely on file browsers and copy/paste or drag & drop. I'm fine to look into solutions if they have some broader uses than just a one-off website. Of course, if that one-off is Google, it's probably useful to do anyway.

**Comment by 7peanuts** [comment]
> [This add-on](https://addons.mozilla.org/fr/firefox/addon/capture-reverse-image-search/) uses google images directly [Source](https://github.com/schomery/reverse-image-search/blob/master/v3/worker.js)
> 
> Maybe an {image} parameter to upload the image could work?
> 
> Also [this](https://github.com/ccd0/4chan-x/issues/3307#issuecomment-1318522986) seems to be a fix

Wow, it works, and this `sbisrc=` parameter can be filled with any alphanumeric.

`https://www.google.com`/searchbyimage?sbisrc=**_1orwhatever_**&image_url={searchTerms}&safe=off

**Comment by harryray33** [comment]
If I use select image, Google works, but Yandex doesn't. But if I use select URL, the opposite is true.

What I'm having to do is to use the context menu to search Yandex and use the browser toolbar to search Google.
A bit of a nuisance as it means I can't use the context menu to search for Google and Yandex at the same time.

**Comment by ssborbis** [comment]
> What I'm having to do is to use the context menu to search Yandex and use the browser toolbar to search Google.

Could you elaborate on this a bit? Sounds like a bug I should check out.
