### ISSUE TITLE
Update translation

### ISSUE THREAD

**Issue by logusergithub** [ssborbis/ContextSearch-web-ext#601]
Hi,
there is an updated message json (latest 'conflict' line and minor corrections) and also help.htlm from an previous push.
I forked the development as well and edit files online from there; when I see the image below on your site am I the one who has to continue or you should already see such 'push'?

[![Push.png](https://i.postimg.cc/ryrc37VD/Push.png)](https://postimg.cc/grmf6S6p)

**Comment by ssborbis** [comment]
> am I the one who has to continue or you should already see such 'push'?

I believe you click the `Compare & pull request` button, are prompted with a list of changes, then finally submit the pull request. There may be some options as to which branch you merge to ( in this case, choose development ). If you're concerned about messing something up on my end, remember I have to approve all changes, so go ahead and try some things out. If anything goes wrong, I can decline the changes and we can make corrections before any changes go into my source code.

**Comment by ssborbis** [comment]
However you did it was the right way. Thanks!

**Comment by logusergithub** [comment]
Ok, I finally figured out the right steps even though I left the default title 'Development' in the pull request...

A bit of a pain, but if you can add dedicated lines for the left and right mouse buttons ('Additional Actions') in the future, the translation comes out better.

**Comment by ssborbis** [comment]
> A bit of a pain, but if you can add dedicated lines for the left and right mouse buttons ('Additional Actions') in the future, the translation comes out better.

How is it displaying now? Does `left`, `middle`, `right`, `forward`, `back` not translate well in regards to mouse buttons in your language?
