### ISSUE TITLE
Grid view bug

### ISSUE THREAD

**Issue by Bhaalspawn** [ssborbis/ContextSearch-web-ext#607]
i have this bug that every time i restart Vivaldi browser the view of my menu go back to "text" but i want it to be "grid"

**Comment by Bhaalspawn** [comment]
![Cattura](https://user-images.githubusercontent.com/20135076/202038022-2a8d798e-ddc2-48d0-b7b6-8b09c689fd51.JPG)

**Comment by ssborbis** [comment]
1. Did you change the hidden setting `saveMenuDisplayMode`?

2. Can you export and upload your config here or email me at contextsearch.webext@gmail.com for me to test?

**Comment by ssborbis** [comment]
Also, can you verify other settings are being saved and working correctly. When you change the view setting from grid to text, do you see the ( Saved ) notice at the top of the options page?

**Comment by Bhaalspawn** [comment]
i don't lknow what savemenudisplaymode is
i see "saved" message but i found out that also in toolbar (same setting grid/text)

**Comment by ssborbis** [comment]
Ok, I've found the bug. It will be fixed in the next release

**Comment by Bhaalspawn** [comment]
> 

news?

**Comment by ssborbis** [comment]
Oof, did this fix not make it into the release version?

**Comment by Bhaalspawn** [comment]
i still have the bug both on Firefox and Vivaldi

**Comment by ssborbis** [comment]
ok, this should be fixed in the master branch and will be in the next release

**Comment by ssborbis** [comment]
v1.46.14 going up
