### ISSUE TITLE
Add drag to direct search and reduce Context Menu folder level

### ISSUE THREAD

**Issue by 0400H** [ssborbis/ContextSearch-web-ext#610]
Feature request:

1. Need to set a default search folder/group/engine, and will be `direct popup` search result while `drag action`.

2. "Show an option to search the entire folder at the top of the menu" is the most used feature, but it is too deep in the context menu.
  Need to move location 3's action to location 2, and click location 2 to get results.
![image](https://user-images.githubusercontent.com/16373603/203247641-05fc8cc2-1fdc-410d-ab81-1b3dcee37429.png)

**Comment by ssborbis** [comment]
Unfortunately, the Context menu API doesn't listen for mouse events on folders. There's nothing to tell addons how a user has clicked a folder item in a menu, so there is no way to use alternative mouse buttons or modifier keys to do anything but open the folder. 

Alternatively, you could make a multisearch engine using the engines in the folder and place that multisearch engine in tier 2 next to the folder

**Comment by 0400H** [comment]
> Unfortunately, the Context menu API doesn't listen for mouse events on folders. There's nothing to tell addons how a user has clicked a folder item in a menu, so there is no way to use alternative mouse buttons or modifier keys to do anything but open the folder.
> 
> Alternatively, you could make a multisearch engine using the engines in the folder and place that multisearch engine in tier 2 next to the folder

1. Can the drag search action be supported? In fact this action is the most efficient.
2. How to make a multi-search engine? Is it possible to add option to move <xxxxx search all> to level 2?
3. Is it possible to add a `engine/group enable page` to toggle search engine/groups on and off?
```
    |---- Search Engine Registry ----|
    |                                |
    |  |-- Group 1                   |
    |       |-- Engine 1             |
    |       |-- Engine 2             |
    |  |-- Engine 3                  |
    |  |-- Engine 4                  |
    |--------------------------------|
                   |
                   v
    |---- Search Group factory   ----|
    |                                |
    |  |-- Group 1 all - Enable      |
    |  |-- Group 2 - Enable          |
    |  |-- Engine 3 - Enable         |
    |  |-- Engine 4 - Disable        |
    |--------------------------------|
                   |
                   v
    |---- Context/Quick Menu     ----|
    |                                |
    |  |-- Group 1 Search all        |
    |  |-- Group 1                   |
    |       |-- Engine 1             |
    |       |-- Engine 2             |
    |  |-- Engine 3                  |
    |--------------------------------|
```

**Comment by ssborbis** [comment]
> Can the drag search action be supported? In fact this action is the most efficient.

Using the browser UI context menu? No, I don't think there is any drag & drop function. The Quick Menu supports drag & drop, and you can open the menu on drag.

> How to make a multi-search engine?

Click and highlight multiple engines in the search engines manager ( holding CTRL + mouse click ), then right-click and choose `New Multiengine`

> Is it possible to add option to move <xxxxx search all> to level 2?

No, but I can look into adding an option. How would that look? Would a folder be replaced with a search all option, or search all would be placed near the folder?

> Is it possible to add a engine/group enable page to toggle search engine/groups on and off?

The browser UI context menu is fixed after opening. It cannot be changed or altered while open. You can, however, enable an option to only display engines that match the context of the element the menu was opened on. In other words, you can mark engines as "image" or "link" or "selection", etc, and only show engines that match that criteria when you open the menu on images, or links, or selected text, etc. CS Options -> Context menu -> Advanced -> Contextual layout
