### ISSUE TITLE
How to send the enter key?

### ISSUE THREAD

**Issue by StrollStars** [ssborbis/ContextSearch-web-ext#612]
Some websites need to press the Enter key to start searching after entering keywords, and there is no search button, such as [this one](https://u.gitcafe.net/).
@7peanuts 也请帮忙看下如何发送回车键。

**Comment by ssborbis** [comment]
```javascript
(() => {
    let input = document.querySelector('#wp-filter-search-input');
    input.value = searchTerms;
    input.dispatchEvent(new KeyboardEvent('keypress', {key: "Enter"}));
})();
```

**Comment by StrollStars** [comment]
@ssborbis Thank you very much.
