### ISSUE TITLE
Minimum selected characters for quick menu

### ISSUE THREAD

**Issue by MapleGingerOatmeal** [ssborbis/ContextSearch-web-ext#614]
Unless I'm missing this setting somewhere, I would love to be able to set a minimum number of selected characters required for the quick menu to open.

I often copy/paste short strings of numbers, and I'd like to restrict those instances from being affected by the search menu popping up. It would also be nice to be able to prevent the quick menu from popping up on those occasional times when I double click and highlight something accidentally.

**Comment by ssborbis** [comment]
I think both options could be added without too much issue. I assume you're using the auto opening feature for the quick menu?

**Comment by ssborbis** [comment]
I've added both options. They'll be found in the advanced options in the next release. Just fyi, it's going to be a while yet for the next version. I have some major back-end changes that need testing.

**Comment by ssborbis** [comment]
No prob. I'll re-open this as a reminder and post a followup when the next release is out.

**Comment by ssborbis** [comment]
1.46.8 going live now
