### ISSUE TITLE
Right-click Add Custom Search is not working

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#615]
![-gif-2](https://user-images.githubusercontent.com/82173614/211195092-595edf0c-c3b5-429d-85bb-4c81137878c0.gif)

**Comment by ssborbis** [comment]
1. what browser?
2. what version of cs?
3. does it happen everywhere or only github? ( I have noticed some oddities on github, but the menu always showed )

**Comment by 7peanuts** [comment]
v1.46.4, all browser, all sites
I have only updated my windows system in the past few months, and recently I suddenly could not open the add menu

**Comment by ssborbis** [comment]
Could it be your adblocker? I see it jump from 20 to 21 when you open the menu.

**Comment by ssborbis** [comment]
I'll continue checking on my virtual systems. Do you know if it started with v1.46.4?

**Comment by ssborbis** [comment]
You may also check the console for errors when you open the "Add to ContextSearch" menu. That might give us clue.

**Comment by 7peanuts** [comment]
> Could it be your adblocker? I see it jump from 20 to 21 when you open the menu.

Not even after disabling the uBO.
Here is the console log
[github.com-1673236309186.log](https://github.com/ssborbis/ContextSearch-web-ext/files/10370283/github.com-1673236309186.log)

**Comment by ssborbis** [comment]
Thanks. I see where the problem is, but not the why. I'll keep you posted.

**Comment by ssborbis** [comment]
If I'm reading the correct line of code, the issue seems to be that the addon is looking for a text box with focus, which was checked for earlier in the code, but at another point fails, which breaks the addon. The question then is, why is the focus lost? If it's not another addon interfering, it could be a conflicting setting within the addon. Maybe try disabling the quick menu temporarily to see if that could be causing it? If that doesn't work, you might send me your config so i can test with your settings. I can't seem to trigger the bug with mine.

**Comment by 7peanuts** [comment]
It should have nothing to do with the configuration. After uninstalling and reinstalling, it still cannot be used
[1673238984617.log](https://github.com/ssborbis/ContextSearch-web-ext/files/10370383/1673238984617.log)
my config
[ContextSearchOptions_2023-01-09_042942.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/10370384/ContextSearchOptions_2023-01-09_042942.zip)

**Comment by ssborbis** [comment]
I've tried with that config on multiple machines and browsers, but I can't get that bug. Again, I see where it's happening, but I don't see why the form you're right-clicking on to open the context menu is losing focus. Are you using any windows software that would be affecting forms or focus? I think I can work around the issue, but I'm curious as to why it's happening.

**Comment by 7peanuts** [comment]
> Are you using any windows software that would be affecting forms or focus? I think I can work around the issue, but I'm curious as to why it's happening.

I found it, it was caused by this software, version 5.39 and later versions
https://github.com/2dust/v2rayN

I can submit an issue over there, but I don't know what the problem is and how to describe it.

**Comment by ssborbis** [comment]
I'm not it a good position to test that software ( linux ), but I think I have a workaround. I don't understand why the windows software it would cause this particular problem, though.

**Comment by 1353604736** [comment]
same problem, There is no "Add Custom Search" option in the right-click menu
![动画002](https://user-images.githubusercontent.com/12869582/216751615-547ebf6a-bfa7-4a81-b271-a7ad6f21d77e.gif)

**Comment by ssborbis** [comment]
> same problem, There is no "Add Custom Search" option in the right-click menu

Can you confirm you have this option enabled under CS Options -> Context menu -> General -> "Enable the context-menu item "Add Custom Search" on INPUT elements. Disable to prevent a tiered menu in some cases"

Are you also on Windows and running software that is conflicting with this addon? I've tested on Firefox and Chromium and haven't seen this bug yet.

**Comment by 1353604736** [comment]
found the reason
When the ScrollAnywhere plug-in is set the same as the configuration file in the attachment, ContextSearch web-ext will not display the right-click add search menu
[export_2023_02_04___14_37_02.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/10607916/export_2023_02_04___14_37_02.zip)

**Comment by 1353604736** [comment]
> > same problem, There is no "Add Custom Search" option in the right-click menu
> 
> Can you confirm you have this option enabled under CS Options -> Context menu -> General -> "Enable the context-menu item "Add Custom Search" on INPUT elements. Disable to prevent a tiered menu in some cases"
> 
> Are you also on Windows and running software that is conflicting with this addon? I've tested on Firefox and Chromium and haven't seen this bug yet.

then another question
How to use it with the ScrollAnywhere plugin at the same time without affecting the appearance of the right-click add search engine menu?

**Comment by ssborbis** [comment]
> How to use it with the ScrollAnywhere plugin at the same time without affecting the appearance of the right-click add search engine menu?

The right-click capturing appears to conflict between the two addons. You may need to set a modifier key with one or the other addon. For instance, you could enable scrolling only when holding Ctrl through the ScrollAnywhere settings. Or you could open this addon's menu using another opening method.

**Comment by 7peanuts** [comment]
> then another question How to use it with the ScrollAnywhere plugin at the same time without affecting the appearance of the right-click add search engine menu?

Maybe the keys and mouse buttons of the two conflict, you can try other buttons.

Or change the settings of ScrollAnywhere, you can also try this extension **`Scrollbar Anywhere`**
https://chrome.google.com/webstore/detail/scrollbar-anywhere/namcaplenodjnggbfkbopdbfngponici

This is my current configuration.
![20230207102428](https://user-images.githubusercontent.com/82173614/217136039-9f518978-c050-4605-ade2-0371db710d96.jpg)
![20230207105234](https://user-images.githubusercontent.com/82173614/217136045-5776e54a-957f-4652-8cda-09f7800ca5ab.jpg)

**Comment by 7peanuts** [comment]
> > Are you using any windows software that would be affecting forms or focus? I think I can work around the issue, but I'm curious as to why it's happening.
> 
> I found it, it was caused by this software, version 5.39 and later versions https://github.com/2dust/v2rayN
> 
For some reason, this problem has been solved by itself, no matter which version of the software is used, the add menu can be displayed.

**Comment by ssborbis** [comment]
> For some reason, this problem has been solved by itself, no matter which version of the software is used, the add menu can be displayed.

My favorite kind of fix
