### ISSUE TITLE
[Suggestion] Ability to search all search engines in a folder to Quick Menu

### ISSUE THREAD

**Issue by aidinzolghadr** [ssborbis/ContextSearch-web-ext#616]
Hi,

First of all, thank you for this superb extension, it saved me so many time.

I have a suggestion, if I may, though. Currently we have "Show an option to search the entire folder at the top of the menu" in Context Menu, I was wondering if it's possible to add it to Quick Menu as well.

Best regards,

Aidin

**Comment by ssborbis** [comment]
Using the quick menu, click the folder with the middle mouse button to search the whole folder ( default ). You can change the button in CS options -> Quick Menu -> Search Actions -> Folders

![folders](https://user-images.githubusercontent.com/24310997/211253194-a1332559-657f-4ce6-a8a5-a62c5568ba3f.jpg)
