### ISSUE TITLE
[Bug] Context menu "search all" conflicts with engine filters

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#617]
If "Filter search engines based on the target element" is checked, 
then you cannot use the "search all".
![20230110124334](https://user-images.githubusercontent.com/82173614/211464097-4b22c6a7-2504-43e4-b324-742bd75a6191.jpg)

**Comment by ssborbis** [comment]
Gotcha. I think I have this fixed locally now. 

I'm still needing to finish up some heavily modified back-end code before I can drop the next release. It might be a while.

**Comment by ssborbis** [comment]
Are you able to test this before I make a new release? I pushed a potential fix to the master branch.

**Comment by 7peanuts** [comment]
> Are you able to test this before I make a new release? I pushed a potential fix to the master branch.

Ok, I'll test it right away.

**Comment by ssborbis** [comment]
1.46.5 going up
