### ISSUE TITLE
Quick menu gets a gap on the right side when icon folder is created

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#618]
As you can see in the following picture, the quick menu will get a gap on the right side, if an icon folder with two or more search engines inside will be created:
![grafik](https://user-images.githubusercontent.com/1245718/212058988-149e573c-63e7-4b33-ac31-48fbb0a9c1b8.png)

To reproduce this bug:
1. Restore to defaults the search engines and the settings (in the advanced menu).
2. Adjust `Maximum number of rows to display on opening (grid view)` to 4 in the quick menu settings.
3. Watch [this](https://user-images.githubusercontent.com/1245718/212063331-180263e4-7121-4cc3-8f84-3143317faf17.webm) screencast.

This issue appeared after an update a long time ago, maybe half a year or so. Couldn't reproduce it until now.

Happens with v1.46.4 on Firefox 109.

**Comment by ssborbis** [comment]
Thanks for the detailed report. I think I've found the problem. I'll do some testing to see if the fix breaks anything else then I'll look into getting a patch.

**Comment by ssborbis** [comment]
I think a fix for this is in the current Master branch and should be in the next release.

**Comment by sojusnik** [comment]
> I think a fix for this is in the current Master branch and should be in the next release.

I just wanted to let you know that this issue is still there in the latest versions.

**Comment by ssborbis** [comment]
Hmm... I can't trigger that bug any more using your demonstration video. Could you send me a config where the bug is present?

**Comment by ssborbis** [comment]
Oh, I should say I'm using the code from the master branch. Lemme see if there's a difference between the latest code and the latest release...

**Comment by ssborbis** [comment]
I checked the latest release 1.46.14 and I can't get the bug there either. I'll try your config and see if anything stands out.

**Comment by sojusnik** [comment]
Oh, sorry, my bad! It works properly now, had to adjust some settings! Many thanks for this awesome extension!
