### ISSUE TITLE
Search all tabs invalid

### ISSUE THREAD

**Issue by StrollStars** [ssborbis/ContextSearch-web-ext#619]
I click Search All in the right click menu, but nothing happens.

**Comment by StrollStars** [comment]
same as https://github.com/ssborbis/ContextSearch-web-ext/issues/617

**Comment by ssborbis** [comment]
I'll get a hotfix for this. I'll post here and the other thread when it's ready.

**Comment by ssborbis** [comment]
I made a push to the master branch with a possible fix. I cant seem to get the bug, but maybe you could test before I make a release.

**Comment by ssborbis** [comment]
1.46.5 going up

**Comment by StrollStars** [comment]
No problem now, thanks.
