### ISSUE TITLE
bookmarklet testing

### ISSUE THREAD

**Issue by ssborbis** [ssborbis/ContextSearch-web-ext#62]
On request for v.1.6.1+, I've added the ability to execute bookmarklets from the context menu when using the `Use Bookmarks` option for managing search engines. I have nearly zero experience using bookmarklets, so if anyone here uses them, let me know if they're working properly.

**Comment by hg42** [comment]
hey :-) I'm using bookmarklets, too :-)))

the problem is, many of my bookmarklets don't work anymore...cross site something etc...
That's why I was planning to invest some time to test them all and then import the remaining working bookmarklets to CS.
But it still didn't happen -> time restrictions...24 hours limit etc.

**Comment by ssborbis** [comment]
@hg42 
The only bookmarklets I've tested are pretty simple. If you find one that doesn't work with CS that you could really use, paste the code and I'll see if there's a workaround. 

> 24 hours limit

???

**Comment by hg42** [comment]
oh, somehow I didn't read the part about the workaround. Thank you for the offer.

**Comment by dnknn** [comment]
## javascript: Bookmarklet 

Bookmarklet  tools
　　https://w-shadow.com/bookmarklet-combiner/	
　　https://blummy.com/

　　https://mrcoles.com/bookmarklet/	
　　http://subsimple.com/bookmarklets/jsbuilder.htm	
　　https://sandbox.self.li/bookmarklet-to-extension/	

Bookmarklet 
　　http://subsimple.com/bookmarklets/		
　　https://squarefree.com/bookmarklets/
　　http://bookmarklets.com/tools/categor.html
　　https://www.hongkiat.com/blog/100-useful-bookmarklets-for-better-productivity-ultimate-list/

---
⚠tips for ֎Chrome:
　　Bookmarklet does not work in `chrome://` and `chrome-extension://`
`chrome://settings/content/popups` ☑Allowed  👇 to open multi pages (e.g. multi search engines)
![209_01193431](https://user-images.githubusercontent.com/10995302/91844498-2a725780-ec8a-11ea-9211-312249e56e5d.png)

---
Simple example
`javascript:var kw=prompt("💬🔍", window.getSelection()); if(kw!=null){window.open('https://a.com/s?wd=' +kw); window.open('https://b.com/search?q=' +kw);}`
