### ISSUE TITLE
Imgur search engine not working

### ISSUE THREAD

**Issue by MW-J97** [ssborbis/ContextSearch-web-ext#620]
Hi,
A long time ago, I asked if it's possible to make an Imgur search engine to add posts to favorite, and it worked, but now this is not working. It doesn't save to favorite or close the tabs after being opened. 
This is the request post https://github.com/ssborbis/ContextSearch-web-ext/issues/451

I am using Win 11 Version 10.0.22000 Build 22000
Chrome Version 110.0.5481.78 (Official Build) (64-bit)

**Comment by ssborbis** [comment]
Could you post the engine you're using that's no longer working and I'll take a look.

New versions of CS allow you to export a single engine via right-click -> Export from the search engines manager. You'll probably need to zip it before dropping it into the comments.

**Comment by minawaheed9697** [comment]
> Could you post the engine you're using that's no longer working and I'll take a look.

[Imgur.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/10743501/Imgur.zip)

**Comment by ssborbis** [comment]
Try changing the click event to
```javascript
document.querySelector('.GalleryVote-favorite').dispatchEvent(new Event('click', {bubbles: true}));
```

Oh, and the engine didn't export correctly. Not sure what happened. I might need to look into that.

**Comment by minawaheed9697** [comment]
@ssborbis 
Is there anything else I can do?

**Comment by ssborbis** [comment]
Still not working for you? Hmm, I'll double-check on chromium, but it _seems_ to be working for my on Firefox. The Favorite icon is definitely being clicked in my browser. I'll re-read the old thread to be sure I'm understanding exactly what you're trying to accomplish.

**Comment by minawaheed9697** [comment]
No, it's still not working 
I click and not added to favorites and the tab is not closed automatically

**Comment by ssborbis** [comment]
The code _looks_ right. 

You might try increasing the timeout to 5000 or something arbitrarily high, just to be sure it's not a timing issue. If it still doesn't work, something else must be going on.

**Comment by ssborbis** [comment]
You said it doesn't close the tab either... thats odd. Maybe trying putting an `alert('step 1');` line between every line on the script and check how far the code actually gets would be useful. Something must be wrong if the code doesn't complete enough to close the tab.

**Comment by minawaheed9697** [comment]
This above screenshot of the code is not saving the post to favorites or even close the tab. That's what I mean. 
If you can, please write the whole script with the edits you want, it'll be very helpful, as I didn't get what I should do

**Comment by minawaheed9697** [comment]
@ssborbis 
Okay, I think I get the issue now.
When I click on the image itself, it's not saved to favorite or closed. I have to click on the post title itself. 
But, the video can be clicked on the video itself or the title giving the same result, and it's saved to favorites and the tab is closed. 
Like this below image, if I click on 1, the image is not saved, but if I click on 2, the image saved and the tab is closed. 
![image](https://user-images.githubusercontent.com/73688266/219957213-da478d04-8e4c-4d1e-a43d-13a2a5618100.png)

**Comment by ssborbis** [comment]
Hmm, you might need to show me the URLs. Maybe one needs to be modified before opening the imgur page the script uses to click the "favorite" button. I'll try to see what you're seeing and report back.

**Comment by ssborbis** [comment]
And just to be clear, the image you posted is what you see directly in imgur, or what imagus shows?

**Comment by ssborbis** [comment]
> Like this below image, if I click on 1, the image is not saved, but if I click on 2, the image saved and the tab is closed.



The issue appears to be the result of the default handling of images wrapped with a link ( link vs image url ). You may be able to toggle it by holding CTRL. I know that functionality has been reworked in some of the development builds, but I'm not sure fixes made it to the release.

**Comment by minawaheed9697** [comment]
> And just to be clear, the image you posted is what you see directly in imgur, or what imagus shows?

This is what I see in Imgur.
When I click the link, it works fine, but when I click the image itself, it doesn't work.

**Comment by ssborbis** [comment]
It's the difference between the image URL and the link URL

https://i.imgur.com/6kyfRME_d.webp?maxwidth=520&shape=thumb&fidelity=high

vs

https://imgur.com/gallery/peMBHRo

CS may default to the image url, even if you really need the link url. You may try changing the context of that particular engine to "link" and disable "image", or try the CTRL trick. After the next major release, there may be more options as well.

**Comment by minawaheed9697** [comment]
> You may try changing the context of that particular engine to "link" and disable "image", or try the CTRL trick.

 I tried all of these and the same issue. It doesn't work when I click on the image itself.

**Comment by ssborbis** [comment]
I'm trying to think of a workaround. There may not be a way currently.

**Comment by ssborbis** [comment]
Ok, I have a workaround. It will require you to create a new Script-type engine, and use this as the following code, replacing the `menuItemId` with the ID of your current imgur engine, and use the new script in place of the engine.

```javascript
(async() => {
	if ( searchTerms.indexOf("/gallery") == -1 ) {
		let el = document.querySelector(`[src="${searchTerms}"]`);
		let a = el.closest('a');
		searchTerms = a.href;
	}

	browser.runtime.sendMessage({
		action: "search", 
		info: {
			menuItemId: "LE6T39TX7TFM1",
			selectionText: searchTerms,
			openMethod: userOptions.lastOpeningMethod || userOptions.quickMenuLeftClick
		}
	});
})();
```

**Comment by ssborbis** [comment]
Essentially, it checks for a gallery url, and if it doesn't see one, tries to find the correct gallery link. Then it calls your Imgur search engine. You can find the ID of the Imgur engine by inspecting the row in the search engines manager.

**Comment by ssborbis** [comment]
Actually, you might want to change the `openMethod` to "openBackgroundTab"

**Comment by ssborbis** [comment]
Add a new `Script` not a new `Engine` and add that code.

**Comment by minawaheed9697** [comment]
> Add a new `Script` not a new `Engine` and add that code.

Still doesn't work.

**Comment by ssborbis** [comment]
Hmm, working for me, but I am on the latest code. I'll try on the last release and see what my results are.

**Comment by ssborbis** [comment]
What is your CS Options -> General -> Links option set to? Text or URL? If set to Text, you may need to hold CTRL when opening the menu.

You may check the output of the script by adding the line
```
alert(searchTerms);
```

below the line

```
if ( searchTerms.indexOf("/gallery") == -1 ) {
```

That will help troubleshoot what search terms are currently being used

**Comment by minawaheed9697** [comment]
> What is your CS Options -> General -> Links option set to?

It's URL.

I added what you said, and now it's showing this message and doesn't open or save anything to favorites. 
https://imgur.com/TtHhE2x

**Comment by ssborbis** [comment]
ok, that's good it's getting that far in the script at least

What happens if you move the alert here ( be sure to replace the ID with yours )
```
(async() => {
	if ( searchTerms.indexOf("/gallery") == -1 ) {
		let el = document.querySelector(`[src="${searchTerms}"]`);
		let a = el.closest('a');
		searchTerms = a.href;
	}

alert(searchTerms);

	browser.runtime.sendMessage({
		action: "search", 
		info: {
			menuItemId: "LE6T39TX7TFM1",
			selectionText: searchTerms,
			openMethod: userOptions.lastOpeningMethod || userOptions.quickMenuLeftClick
		}
	});
})();
```

**Comment by minawaheed9697** [comment]
> be sure to replace the ID with yours

Do you mean this? https://imgur.com/lRpFbIC

Also, after updating the script, it gives me the same message, but doesn't go away until refreshing the page.

**Comment by ssborbis** [comment]
> Do you mean this? https://imgur.com/lRpFbIC

That's how you'd get the ID, but you need the ID of the original Imgur *engine* and place that id into the *script*

**Comment by minawaheed9697** [comment]
> That's how you'd get the ID, but you need the ID of the original Imgur _engine_ and place that id into the _script_
 Okay, now it pops up the same message and when I press (Ok), it opens the post and close it after some time. But, it doesn't save it to favorites, and it takes much time to close.

**Comment by ssborbis** [comment]
> Okay, now it pops up the same message and when I press (Ok)

Delete the `alert` line

> it opens the post and close it after some time

Ok, good

> But, it doesn't save it to favorites, and it takes much time to close.

Post the code in your Imgur engine ( post-search script )

**Comment by ssborbis** [comment]
If you still need help with this, please re-open
