### ISSUE TITLE
Some options don't work.

### ISSUE THREAD

**Issue by waniaa1** [ssborbis/ContextSearch-web-ext#622]
I'm using Opera USB 95.0.4635.46, and Chromium 89.0.4389.114 x32bit. The icons in the drop-down Quickmenu are not displayed. Sometimes you have to enter the Engines address several times, because it does not remember the settings when manually entered. The icons in the other Menus are displayed. I didn't check the rest of the options because I don't use them.(https://ibb.co/MGSh9tc). Additionally, MultiSearch does not work in Opera. It works in chromium. Trying to open an address starting with (chrome-xtension://ddippghibegbgpjcaaijbacfhjjeafjh/) instead of opera. This is one of the best extensions. I use so far, but it is not compatible with other browsers based on the Chrome engine.

**Comment by ssborbis** [comment]
> The icons in the drop-down Quickmenu are not displayed.

Did you mean the _context menu_ as pictured in your screenshot? If so, that's a chromium-based issue. No icons are allowed in the context menu beyond the top tier for those browsers. Firefox will allow icons, however. I haven't used Opera, but I assume that's what's happening. I'll take a peek when I get a chance.

> Sometimes you have to enter the Engines address several times, because it does not remember the settings when manually entered.

That's been mentioned before. I think I have a fix written for future releases, but I can't be sure. I know it's really annoying. If anything jumps out at me as to why it's happening, I'll get a hotfix made.

> Additionally, MultiSearch does not work in Opera

I'll check on that. I've yet to test on Opera

**Comment by ssborbis** [comment]
> Additionally, MultiSearch does not work in Opera

Does it fail from the menus or only when using the "Test" button?

**Comment by waniaa1** [comment]
Thank you for your answer. Have you dealt with the "web_search_pro-3.0.7-fx.xpi" extension. It works similarly, but it is a search engine with a window where you have to enter the search text. It was a very good search engine with many engines and easy setup. Unfortunately, the author has ended support and does not work with newer Firefox. This extension is worth watching and testing. They can be downloaded from old copies of extensions, or I can upload them. The extension is worth watching. Works on firefox from 2012.

**Comment by ssborbis** [comment]
> Have you dealt with the "web_search_pro-3.0.7-fx.xpi" extension

Somewhat. I think this is the extension the "Page Tiles" options were based on. When enabled, you can drag a selected word and a full page window opens with a grid of tiles representing search engines, where you can then drop the dragged word triggering the search. If there are other specific features from that addon you are looking for, please give a few details and I'll see if this addon can or could do what you're looking for.
