### ISSUE TITLE
Highlighted "&" make the context menu lose the custom quick key

### ISSUE THREAD

**Issue by i2324561w2** [ssborbis/ContextSearch-web-ext#623]
The key I'm talking is: Context Menu > "Access key for the ContextSearch submenu".

**Comment by ssborbis** [comment]
Sorry, are you trying to set a key or unset it?

To set, click the key in the options, notice the spinner gif, and press a key
To unset, click the key in the options, notice the spinner gif, and press ESC

If there's something else going on, please elaboration and I'll take a look

**Comment by i2324561w2** [comment]
Sorry, highlight the text `A&B`, right-click (I don't use Quick Menu) and you'll see `Search "AB" with...(*the key you want*)`. Therefore you have 2 problems: "&" disappears and the chosen key doesn't work.

**Comment by ssborbis** [comment]
Gotcha. Must need an escape character or something. I'll check it out.

**Comment by ssborbis** [comment]
Fix is ready and should be in the next release

**Comment by ssborbis** [comment]
1.46.6 going up now

Let me know if the fix worked
