### ISSUE TITLE
performance problem

### ISSUE THREAD

**Issue by JamYiz** [ssborbis/ContextSearch-web-ext#625]
Hello, I found out that this extension has a huge impact on browser performance. I like its right-click search function, but I don't need other functions. Is there a way to improve performance through settings?

**Comment by ssborbis** [comment]
Which right-click menu are you using? The Context menu ( browser UI ) or the Quick menu ( webpage UI ).

I'm curious where the performance hit is coming from. Browser loading? Page loading? Mouse movement? If you can kinda narrow down where the bottleneck is, I can look into improving things.

**Comment by JamYiz** [comment]
I use right-click menu via Context menu，browser is firefox.
It takes a lot of performance and slows down page loads when opening a new tab.
![Snipaste_2023-03-08_14-50-47](https://user-images.githubusercontent.com/44351690/223640067-eb17db60-76d9-40aa-beec-43c3cf7dd1df.png)

**Comment by ssborbis** [comment]
If I'm seeing the same page load spike you are, I think it is due to the context menu being rebuilt every page load or tab activation. I may be able to skip the rebuild under certain circumstances, but due to some quirks in how addons are limited in managing the UI context menu, there will necessarily be some required rebuilds.

**Comment by ssborbis** [comment]
This particular slowdown ( new tabs, tab activated ) should be greatly reduced in the next major release. The context menu is no longer completely rebuilt when a tab is activated; it is updated with tab-relevant menus instead. The code is in the development branch for testing, but if you try it out make sure you are currently on 1.46.6 or greater to allow for downgrading after testing. Releases prior to 1.46.6 will have problems after installing the development code.

**Comment by ssborbis** [comment]
Assuming you're on FF, I have a beta to try

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.46.9b1/contextsearch_web_ext-1.46.9b1.xpi

The context menu fixes are the only change between the beta and release.

**Comment by ssborbis** [comment]
> ContextSearch-web-ext still generates a large number of dispatches during the first few web pages when the browser is launched,  delaying page loading

I'll continue looking for ways to improve performance.

> The problem has been solved, and I would like to express my gratitude to you once again.

No problem, and I greatly appreciate the input. Software like this simply doesn't evolve without users like you willing to take the time to report issues and make suggestions.
