### ISSUE TITLE
[Feature-Request] Toolbar-Menu Closing-Behaviour

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#627]
Hey there, 

lately I find myself using the Toolbar-Menu more often in addition to the Quick-Menu.

And similar to this old feature-request of mine I'd wish for the same here too.
(https://github.com/ssborbis/ContextSearch-web-ext/issues/289) 

I.e.: I would like the closing of the Toolbar-Menu to behave exactly like the closing of the Quick-Menu. I.E. it should close on a left click outside of the menu-area (which it does already) but without following links (in the case of that left-click happening on a link).

That would be great, wouldn't it!?

**Comment by ssborbis** [comment]
Good idea. I have some code ready to go for the next release. It uses CSS so it may not work on every website, but it's working everywhere I've tested so far. I'll post here again with the option name when I drop the next release.

**Comment by ThomasSeeker** [comment]
Ah, wonderful! ... Glad you like it! :-)

**Comment by ssborbis** [comment]
1.46.6 going up now

Let me know if the fix worked

**Comment by ThomasSeeker** [comment]
Ah, thank you very much Ssborbis! 
It works beautifully. :-)

Only a minor thing: With a click on the page-scrollbar the Toolbar-Menu closes, but the page still moves. ... Whereas with the QM the menu stays open and the page also moves. ... Thinking about this ... if possible, I would prefer both menus to close (with a click on the scrollbar) and the page NOT to move. ... What do you think? ... But again, this is only a minor thing!

Hey ... I wish you  a nice weekend! ;-)

**Comment by ThomasSeeker** [comment]
PS: I love ContextSearch! :-)

**Comment by ssborbis** [comment]
> Only a minor thing: With a click on the page-scrollbar the Toolbar-Menu closes, but the page still moves. ... Whereas with the QM the menu stays open and the page also moves. ... Thinking about this ... if possible, I would prefer both menus to close (with a click on the scrollbar) and the page NOT to move

If it's possible, I'll set it up.

**Comment by ThomasSeeker** [comment]
Thank you Ssborbis! ... You are the best! :-)

BTW, this is also the way my Bookmark-Toolbar-Button behaves with such a click. The opened bookmark-list closes and the page does not move. ... Makes the most sense to me this way. ... Gives one the complete freedom to click where ever one wants (to close the thing and move on).

**Comment by ssborbis** [comment]
Looks like some issues are popping up #631

I've added this feature as an option in 1.47.7 and will continue testing.

**Comment by ssborbis** [comment]
beta to test here if you're interested ( FF ) 

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/v1.46.8b/contextsearch_web_ext-1.46.8b.xpi

**Comment by ssborbis** [comment]
Is the "Bookmark-Toolbar-Button" an addon or are you referring to the built-in button on the browser?

**Comment by ThomasSeeker** [comment]
> Is the "Bookmark-Toolbar-Button" an addon or are you referring to the built-in button on the browser?

It is the built-in button. But I still use an old outdated FF ... so it might be different with a current one. 

> beta to test here if you're interested ( FF )

Ah, great! The bug is gone! :-)
...

One minor thing that I noticed while playing around with this: 

Going manually to the opened search-tab closes the Toolbar-menu.

But going automatically to the new search-tab (with defined mouse-click) the Toolbar-menu stays open during the tab-switch and also in the new tab. ... But there the links are not disabled and one risks clicking them. 

Actually, I'm not sure, what to prefer here. I mean, if the menu should even stay open over in the new tab? I don't know!?  .... I definitely like the QM to stay open in the old tab (after the search(es)). But the toolbar-menu kind of belongs more to the browser than the page ... so it would be a bit strange, if it stayed open with the old tab (if that was even possible technically). But from a usability standpoint, I would prefer this, I guess. ... Second best IMO would be, if the toolbar-menu closes during an automatic tab-switch. ... And third best IMO would be, if the toolbar-menu stays open during the switch (like now), but the links are disabled on the new page. 

Just my 2 cents. ;-)

**Comment by ssborbis** [comment]
> Going manually to the opened search-tab closes the Toolbar-menu.

This behavior is managed by the browser, not the extension, so as an addon dev, I have no control over the menu closing. So I'd consider that the default behavior i guess?

> But going automatically to the new search-tab (with defined mouse-click) the Toolbar-menu stays open during the tab-switch and also in the new tab. ... But there the links are not disabled and one risks clicking them.

Hmm... ok. I'll see if there's a check I can run on new tabs to see if the toolbar menu is open. That may be difficult. That particular browser feature  is a bit lacking in access.

**Comment by ssborbis** [comment]
Do you have the option `Close menu after performing a search` disabled then? I can't see any other way the menu would stay open after performing a search to a new tab.

**Comment by ThomasSeeker** [comment]
> Do you have the option `Close menu after performing a search` disabled then?

Yes, I have it disabled. I like it to stay open for the cases, where I do more than one search. ... it is very handy. ... But it wouldn't need to stay open over in the new tab ... only in the old one. 

> Hmm... ok. I'll see if there's a check I can run on new tabs to see if the toolbar menu is open. That may be difficult. That particular browser feature is a bit lacking in access.

Again, how about rather closing it in the new tab?

**Comment by ssborbis** [comment]
> it wouldn't need to stay open over in the new tab ... only in the old one

Not sure how to implement this. Some users would undoubtedly want the menu to stay open as they send searches to multiple New Tabs. I suppose just an option to close the menu on New Tab searches vs Current Tab

**Comment by ThomasSeeker** [comment]
> Some users would undoubtedly want the menu to stay open as they send searches to multiple New Tabs. I suppose just an option to close the menu on New Tab searches vs Current Tab

Yes, I think, you are right: Some users will probably want this.
Well, if an option to close the menu on New Tab searches vs Current Tab is possible, than I am very much for it! ... That is what I like in CS so much anyways: The high configurability. :-)

**Comment by ssborbis** [comment]
new advanced option `searchBarCloseAfterNewTab` added to the master branch if you want to sideload. If you need a signed beta, I'll get one for testing.

**Comment by ThomasSeeker** [comment]
Yes, please, a signed beta would be good!

**Comment by ssborbis** [comment]
@ThomasSeeker 

Give this a shot. I need to tidy up a few things and do some testing, but this is more or less the next release

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/1.46.8rc/contextsearch_web_ext-1.46.8rc.xpi

**Comment by ThomasSeeker** [comment]
Ah, wonderful! Thank you!
Looks really good so far. 
Will test it further.

**Comment by ssborbis** [comment]
1.46.8 going live now

**Comment by ThomasSeeker** [comment]
Thank you, Ssborbis!

**Comment by ssborbis** [comment]
No prob. Re-open this issue if you have any problems
