### ISSUE TITLE
[Feature-Request] Auto-Highlight Search-Term in Toolbar-Menu

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#628]
Hey, it's me again with a feature request. ... I hope I am not coming across as annoying! ;-)

The main reason, why I use the Toolbar-Menu more often these days, is the search field. ... And every time when I want to start a fresh new search, I need to delete the auto-filled search-term from the clipboard first. 

I know, there exists the option, to auto-clear this field. I tried it, but half of the times I actually want the clipboard-entry to be there. :-D

So the ideal solution for me (and maybe other too) would be: The entry is there all the time, but as soon as I start typing it gets deleted and overwritten by my typing. (Sort of an auto-highlight without the highlight-colouring.)

Can you see some value in this behaviour too? 
And would it even be possible to achieve?

**Comment by ssborbis** [comment]
I'm surprised this doesn't happen. What is your setting for 
![image](https://user-images.githubusercontent.com/24310997/225446533-4858edb5-718a-41f1-98e7-5f9d0bdd7173.png)

under the quick menu options?

**Comment by ThomasSeeker** [comment]
Ohh, I see! 
I didn't know of this option.
Because I don't use the searchbar with the Quick-Menu (only with the Toolbar-Menu), I never looked there. 

Ah, thank you! ... This is exactly what I wanted. ... You really thought this whole thing through to the end! :-) Impressive!

I also now changed the background-color of the now highlighted search terms. The original one was my systems default and a bit to aggressive for this use case for my taste.

In case someone wants this too: The css would be: 
```
#searchBar::selection {color:#xyz!important;}
#searchBar::selection {background-color:#xyz!important;}

Thank you very much, Ssborbis!
```

**Comment by ssborbis** [comment]
No prob
