### ISSUE TITLE
How to modify {url} with REGEX

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#629]
It seems {url} terms can't be modified? Terms {url} uses the entire URL link.

Template
`{url}/favicon.ico`
REGEX
`/(.*:\/\/[^\/]+\.[a-z]+)\/?.*/$1/g`

**Comment by ssborbis** [comment]
{url} is not modified, nor is any other template param besides %s or {searchTerms}

Is this for a search engine or an app launcher?

Can you walk me through your workflow as to why you'd need to modify the current tab's url? I'll see if there's a workaround.

**Comment by 7peanuts** [comment]
> Is this for a search engine or an app launcher?
> 
I use it to get the favicon, like this ➡️ `https://github.com`**/favicon.ico**

> Can you walk me through your workflow as to why you'd need to modify the current tab's url? I'll see if there's a workaround.
> 
I tried {subdomain} or {domain} ➡️ `{subdomain}/favicon.ico`
but it gets this result ➡️ `chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/github.com/favicon.ico`

So I can only use this template ➡️ 
`https://{subdomain}/favicon.ico` or `http://{subdomain}/favicon.ico`

However, I found that using google's icon services doesn't have strict requirements on URL, so this **{url}** can be used directly.
`https://www.google.com/s2/favicons?domain=`**{url}** ➡️ 
`https://www.google.com/s2/favicons?domain=https://github.com/ssborbis/ContextSearch-web-ext/issues/629`

**Comment by ssborbis** [comment]
So this is for an app launcher? I'm still not 100% sure what you're doing. Downloading the favicon?

**Comment by 7peanuts** [comment]
> So this is for an app launcher? I'm still not 100% sure what you're doing. Downloading the favicon?

just for search, so i can download the favicon directly.

**Comment by ssborbis** [comment]
That might be best done with a Script-type vs an Engine-type. You're only grabbing the icon from the current page, correct? Thus, the {url} param?

New Script

```javascript
window.open(location.origin + "/favicon.ico", '_blank');
```

you could actually fancy that up and trigger a download directly I think

**Comment by 7peanuts** [comment]
> New Script
> 
> ```js
> window.open(location.origin + "/favicon.ico", '_blank');
> ```
> 
> you could actually fancy that up and trigger a download directly I think

This script will open a new tab, how to open favicon page only.
![20230325110751](https://user-images.githubusercontent.com/82173614/227688907-6e3a0a01-90c0-403c-935f-3918259aab61.png)

**Comment by ssborbis** [comment]
Add a new entry to the search engines manager, a NEW SCRIPT not a new engine

![image](https://user-images.githubusercontent.com/24310997/227690495-86c1a552-37c3-4aeb-87d0-b17cf3417c55.png)

![image](https://user-images.githubusercontent.com/24310997/227690585-aa88eae0-41e7-47b0-bee5-b4918b5e7d58.png)

**Comment by ssborbis** [comment]
> how to open favicon page only.

In place of the current website?

```javascript
window.location = location.origin + "/favicon.ico";
```

**Comment by 7peanuts** [comment]
> Add a new entry to the search engines manager, a NEW SCRIPT not a new engine

Oh, I know why, script engine doesn't affect on page element.
