### ISSUE TITLE
Issues with first search engine within a folder in quickmenu

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#630]
I've configured that a right mouse click on a folder in the quickmenu should open all containing search engines of this folder in a new window, but in this case the first search engine of that folder isn't opening, instead I just see a blank tab in a new window with tabs from the subsequent search engines.

But when I press a middle mouse click (that should open all search engines within a folder in background tabs), the results from the first search engine, including the following search engines, do appear.

Happens with v1.46.5 on Firefox 111.0.1 on Ubuntu 22.10

**Comment by ssborbis** [comment]
I'll check it out

**Comment by ssborbis** [comment]
Ah, I've seen this bug before. It's a Firefox thing. I have a fix ready for the next release.

**Comment by ssborbis** [comment]
1.46.6 going up now

Let me know if the fix worked

**Comment by sojusnik** [comment]
It does indeed! Thanks!
