### ISSUE TITLE
Feature "prevent page clicks when toolbar menu is open" in 1.46.6 does not work properly at all.

### ISSUE THREAD

**Issue by killpotts** [ssborbis/ContextSearch-web-ext#631]
This feature seems to do a very poor job of determining whether or not the toolbar is open, and will frequently think that a tab you have left and gone back to has the menu open when it in fact does not, causing the page to be completely unclickable until the context menu toolbar actually is opened. In other words, this feature is bugged as it randomly does the exact opposite of what it is supposed to do. None of the advanced options seem to fix this improper behavior, aside from disabling the toolbar entirely, which obviously is not ideal. 

Would recommend having this "feature" disabled by default and only available as an option.

**Comment by ssborbis** [comment]
Thanks for the heads up. New release going up. Added option `toolBarMenuDisablePageClicks` and will test further.

**Comment by ssborbis** [comment]
if this is still a problem, let me know and I'll reopen
