### ISSUE TITLE
导入别人的配置，右键菜单中不显示图标~

### ISSUE THREAD

**Issue by Nightbeauty** [ssborbis/ContextSearch-web-ext#633]
如题，如果导入别人的配置后，选中右键菜单中不显示图标了，应该如何解决呢~

**Comment by ssborbis** [comment]
> "As the title suggests, if the icon is not displayed in the context menu after importing someone else's configuration, how should I solve it"

If you are using a chrome-based browser, the icons will not be shown in the context menu. Chrome does not display icons in submenus

If you are using Firefox, there must be something else going on. If you can, post the config and I'll take a look.

**Comment by Nightbeauty** [comment]
邮件已经收到，谢谢

**Comment by Nightbeauty** [comment]
> > 《如题，导入别人的配置后右键菜单不显示图标，请问如何解决》
> 
> 如果您使用的是基于 chrome 的浏览器，则图标将不会显示在上下文菜单中。Chrome 不在子菜单中显示图标
> 
> 如果您使用的是 Firefox，则一定有其他原因。可以的话把配置发上来，我看看。

收到，确实是用的chrome浏览器，感谢回复。
