### ISSUE TITLE
Issues about the text box of the toolbar of ContextSearch

### ISSUE THREAD

**Issue by c02y** [ssborbis/ContextSearch-web-ext#634]
When I select a string inside a web page to use QuickMenu or Context Menu, the selected string will automatically be put into the text box of the ContextSearch toolbar, when I click the toolbar icon or use shortcut to open the toolbar icon to start typing something in the text box of the toolbar of ContextSearch, the cursor will be put into the end of the text box which contains the string I mentioned, it is annoying since usually when I open the toolbar, I need to paste or start typing what I want to search, but I have to select and delete the text first.

So
1. Is it possible to stop putting the selected string in a web page into the text box of the toolbar?
2. or another better solution, is it possible to auto select all the text in the text box when I click the toolbar icon or open it using shortcut, so I can just start typing what I need or paste the string to replace the text in the text box?

**Comment by ssborbis** [comment]
> or another better solution, is it possible to auto select all the text in the text box when I click the toolbar icon or open it using shortcut, so I can just start typing what I need or paste the string to replace the text in the text box?

Yes. This can be set in the Quick Menu settings. The Toolbar menu and Quick menu share many settings, including this one.

![image](https://user-images.githubusercontent.com/24310997/231373047-de1f53a5-a28e-431c-9983-350f72195166.png)

**Comment by c02y** [comment]
Thanks, it is great. I thought this should be in `Toolbar` section.
