### ISSUE TITLE
open Quick menu only when mouse is above selection

### ISSUE THREAD

**Issue by GiftWolf** [ssborbis/ContextSearch-web-ext#636]
I have enabled "Select text and open using a mouse button" for the Quick menu. The Quick menu opens if I hold the right mouse button anywhere on the website. This often interferes with my chord gesture of the "Foxy Gestures" extension.

I'd like to suggest an option that opens the Quick menu only if the click is done on or near the selection. In addition the user could be able to define a distance in pixels from the selection where a click would still open the menu.

**Comment by ssborbis** [comment]
> The Quick menu opens if I hold the right mouse button anywhere on the website

Does this occur if you disable the `Anywhere` setting?

![image](https://user-images.githubusercontent.com/24310997/235264469-8c72702e-9c99-49ab-b425-8edf9a7418f2.png)

**Comment by GiftWolf** [comment]
yes, it does.
No, I'm not using any gestures and it happens if I disable Foxy gestures.

**Comment by ssborbis** [comment]
> BTW: Enabling the Ctrl checkbox has no effect for me. The menu opens whether Ctrl is pressed or not.

Ok, I'll check that out

**Comment by ssborbis** [comment]
That bug is now fixed in the master branch. Still looking into detecting mouseover on a selection.

**Comment by ssborbis** [comment]
Release 1.47.9 going up with a fix for the CTRL bug. I am, however, having some issues with mozilla's review process, so I'm not sure it's posted yet.

**Comment by ssborbis** [comment]
in the master branch 
CS options -> Advanced -> Manual Edit

new: quickMenuOnlyOpenIfOverSelection - prevent the quick menu from opening when text is selected, but the cursor is not above the selection

**Comment by ssborbis** [comment]
This option should be in the release versions now. If you have any issues with it, please reopen this thread.
