### ISSUE TITLE
Extract substring after stop word

### ISSUE THREAD

**Issue by Parvares** [ssborbis/ContextSearch-web-ext#637]
Hi Mike, may a ask you a question? Given this template URL in _ContextSearch_:

https://www.bibliotechediroma.it/opac/query/%s?context=tmatm

I need to extract the substrings after these stop-words (determinative articles) at the beginning of the input string (when they are present): 
`Il`, `Lo`, `La`, `I`, `Gli`, `Le`, `L'`

Here are some examples: 

`La `vita sulla terra e il futuro del genere umano **>** vita sulla terra e il futuro del genere umano
`Il `nome della rosa **>** nome della rosa
`L'`avaro **>** avaro
`La `globalizzazione e i suoi oppositori **>** globalizzazione e i suoi oppositori
`I `demoni **>** demoni

I found something similar [here](https://stackoverflow.com/a/38200989). 

Thanks very much!

**Comment by ssborbis** [comment]
if the examples you give are contained in the search string `%s` you can use the `Modify Search Terms` field in the search engine edit modal to replace those leading strings.

`/regex/replacement/[giym]`

Something like ( untested )
`/^(Il |Lo |La |I |Gli |Le |L')//g`

mind the spaces, and check https://regex101.com/ for reference

**Comment by Parvares** [comment]
Thanks Mike. how can i make these strings work?

_l'esorcista
Storia dell'arte veneziana_

This didn't work:
`/[']//g`

Thanks again!

**Comment by Parvares** [comment]
/^(Il |Lo |La |I |Gli |Le |L')//g

Thanks Mike, it doesn't seem working...

**Comment by Parvares** [comment]
Strangely it works from some website, but nor from all ones (not from [here](https://www.google.it/) for example)

**Comment by ssborbis** [comment]
Could you clarify a little. 

When you say it's not working "from" a website, are you saying if you select text on those particular websites ( google for instance )  and search through this addon, using the engine with the template `https://www.bibliotechediroma.it/opac/query/%s?context=tmatm`, the search does not work / the search terms are not modified?

**Comment by ssborbis** [comment]
Is the problem due to case sensitivity or a leading space?

**Comment by Parvares** [comment]
Correct, that was the problem, now it works perfectly, thank again , Mike!

`/^(Il |Lo |La |I |Gli |Le |L')//gi`

**Comment by ssborbis** [comment]
No prob. Cheers!
