### ISSUE TITLE
Qm is not working in Reddit new anonymous page 

### ISSUE THREAD

**Issue by MW-J97** [ssborbis/ContextSearch-web-ext#643]
The new Reddit anonymous page is not responding to qm, it even doesn't appear. 
The only solution is to log in into Reddit to work again.

**Comment by ssborbis** [comment]
I'm not familiar. How do you enable anonymous browsing? I see how to using the app, but not on a desktop

**Comment by ssborbis** [comment]
Nvm, i see you mean private browsing. Looks like there's a CSS issue bleeding into the ContextSearch shadow root. Looking into it...

**Comment by ssborbis** [comment]
Fix in the master branch

**Comment by MW-J97** [comment]
> I'm not familiar. How do you enable anonymous browsing? I see how to using the app, but not on a desktop

I do it on the desktop by simply not being logged in. 

> i see you mean private browsing.

Not only, but also normal browsing as I make chrome deleting cookies on exit. So, I log out most of the time. 

> Fix in the master branch

Yes, it works fine now. Thank you so much. Waiting for the update.

**Comment by MW-J97** [comment]
Also, please, I have an issue with the auto-theme. The settings page is always dark and not respecting the system theme. Is there a fix for that?

**Comment by ssborbis** [comment]
> Also, please, I have an issue with the auto-theme. 

Are the other menus respecting the lite / dark system themes?

**Comment by MW-J97** [comment]
> Are the other menus respecting the lite / dark system themes?


Only qm respects the theme. Every single settings page is always dark.

**Comment by ssborbis** [comment]
I'll need to boot up a virtual box to check on this. I'm having no luck in linux. I'll keep you updated.

**Comment by ssborbis** [comment]
fix for reddit going to the chromestore. Still checking on the theme issues

**Comment by ssborbis** [comment]
I'll continue this on #632
