### ISSUE TITLE
Multisearch with a single template URL

### ISSUE THREAD

**Issue by Parvares** [ssborbis/ContextSearch-web-ext#644]
Hi Mike, could you help me, please? I'm using this [search engine](https://opac.sbn.it/ricerca-avanzata#1681232546821) (combobox "Parola chiave"). Is it possible to do a multisearch using a single template URL and using different strings opening multiple tabs? I tried to enable `multilinesAsSeparateSearches` (value: _true_), but I don't get any result from the context menu. 

P.S. Here are some strings that I used, for example:
`La moltiplicazione dei pani Alkuin Heising 1970`
`Architectura in nuce Bruno Zevi 1979`
`Il ritratto di Dorian Gray Oscar Wilde 1994`
`La *crisi della psicoanalisi / Erich Fromm 1980`

This would be the tamplate URL:

https://opac.sbn.it/risultati-ricerca-avanzata/-/opac-adv/all?struct%3A3008=ricerca.frase%3A4%3D1&fieldstruct%5B1%5D=ricerca.parole_tutte%3A4%3D6&fieldvalue%5B0%5D=%s&fieldaccess%5B0%5D=Keywords%3A1035&fieldop2%5B0%5D=AND%3A%40and%40&fieldstruct%5B10%5D=ricerca.frase%3A4%3D1&fieldop%5B3%5D=AND%3A%40and%40&fieldop%5B1%5D=AND%3A%40and%40&fieldstruct%5B2%5D=ricerca.parole_tutte%3A4%3D6

Thanks very much!

**Comment by ssborbis** [comment]
For a brief sanity check, does the multi-line search work from the quick menu?

On the topic, I've been thinking a confirm popup would be a good idea for multi-line searches, when enabled. In other words, if you were to do a search on a block of text that had multiple lines, a YesNoCancel box would pop up, asking if you wanted the search to be multi-line ( search each line separately using the same engine ). What do you think?

**Comment by Parvares** [comment]
No, it doesn't seem working from anywhere ... Yes, Mike, the popup would be I good idea for multi-line searches, when enabled.
Thank you!

**Comment by ssborbis** [comment]
Hmm, ok a few things.

1. Multi-line search is working for me, as expected, when searching from the context menu
2. not working from the quick menu
3. Looks like i already coded a popup menu. The setting `multilinesAsSeparateSearchesLimit` is the number of lines to search separately before asking for confirmation. In other words, if this is set to 4, then 3 lines won't get a popup, but 5 will ask if you really want to search every line separately
4. I'm not seeing leading or trailing whitespace in the searches

Please try searching again using the context menu using the example block of lines you provided using these settings
`multilinesAsSeparateSearches: true
multilinesAsSeparateSearchesLimit: 1
`

and see what happens.

**Comment by Parvares** [comment]
Thanks, I've changed the limit, but I don't see any changing... 

<img width="702" alt="image" src="https://github.com/ssborbis/ContextSearch-web-ext/assets/55709458/9f8327fa-71a2-4ebe-8aac-9ffc007b4341">

**Comment by ssborbis** [comment]
Hmm... what browser? Also, it might be useful if you posted your config for me to test. The code seem pretty basic, but maybe there's a conflict I'm not considering.

**Comment by ssborbis** [comment]
Oh, and did you get a confirm dialog when you tried to search multiple lines? Setting `multilinesAsSeparateSearchesLimit: 1` should force it to pop up on every multi-line search.

**Comment by Parvares** [comment]
Chrome, v. 114. No, I don't get a confirm dialog when I try to search multiple lines. Here are my settings, thanks.

https://pastebin.com/QVAaLndq

**Comment by Parvares** [comment]
Hi Mike, do you need something else?

**Comment by ssborbis** [comment]
> Hi Mike, do you need something else?

Nope, I think i'm seeing the issues. I'll post here when I have a fix to test.

**Comment by Parvares** [comment]
Thanks, I'll wait an "official" fix for the context menu, thank again!

**Comment by ssborbis** [comment]
The context menu appears to be fixed now as well. I'll post here when I get a release out.

**Comment by ssborbis** [comment]
1.46.11 going up now to chromestore & AMO

**Comment by ssborbis** [comment]
Reopen if things are buggy. Looks good so far on FF and chromium

**Comment by Parvares** [comment]
Thank you for your work. The popup opens both in Chrome and in Firefox, but clicking on "ok" the popup does not disappear....

**Comment by ssborbis** [comment]
Thanks for pointing that out. I'm seeing this too. No idea how that glitch popped up.

**Comment by ssborbis** [comment]
Should be fixed in 1.46.12, live now

**Comment by Parvares** [comment]
Thanks Mike, I hope in a soon fix as I'm experiencing some problems with current version (1.46.11): sometimes the context menu doesn't react and the fan begins to rotate, forcing me to restart... :(

**Comment by ssborbis** [comment]
Did you get the update to 1.46.12?

**Comment by Parvares** [comment]
I don't see it in the [store](https://chrome.google.com/webstore/detail/contextsearch-web-ext/ddippghibegbgpjcaaijbacfhjjeafjh)...

**Comment by ssborbis** [comment]
Says "Pending Review". I'm going to republish. Sometimes the chromestore hangs on submissions.

**Comment by Parvares** [comment]
Okay, thank you

**Comment by Parvares** [comment]
Ehi Mike, I finally used your last version, seems working great so far, thank you very much! Is it possible let your extension work from Google Sheets?

**Comment by ssborbis** [comment]
> is it possible let your extension work from [Google Sheets](https://docs.google.com/spreadsheets/u/0/) (simple or multiline search)?

Not currently. I'll need to look at what's possible with the api

**Comment by ssborbis** [comment]
No prob
