### ISSUE TITLE
middle click to open menu

### ISSUE THREAD

**Issue by Bhaalspawn** [ssborbis/ContextSearch-web-ext#646]
i'm trying different way to open the menu and i like middle click, but
1 - Menu is opnening even when text is not select but just clicking on something (and i click on links with middle button)
2 - when clicking with middle button to open menu, normal actions that needs middle click should be prevented: actions like scrolling icon appearing (when clicking on normale text) and link openings (when clicking on links). That's also why fix point 1 is important so i can i use regular middle click actions if i don't select anything and i get the menu when i slect text.

**Comment by ssborbis** [comment]
You may check on the hidden options

```
    "quickMenuPreventLinksOnMiddleButton": true,
    "quickMenuPreventScrollOnMiddleButton": true,
```

**Comment by ssborbis** [comment]
Also, you may need to disable the `Anywhere` option

![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/6c57f38e-8528-42a7-952f-f9f0176aa5e2)

**Comment by Bhaalspawn** [comment]
the problem is that disabling anywhere, it doesn't for me at all

what are the hidden options?? i have "advanced" tab but i can't see the ones you say

**Comment by ssborbis** [comment]
> what are the hidden options?? i have "advanced" tab but i can't see the ones you say

![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/1b8399ea-540a-47b9-8f69-53957c3280f0)

**Comment by Bhaalspawn** [comment]
ok it worked
but for standard users it's not easy to edit setting in this way. "advanced" menu is ok but "hidden".....

**Comment by ssborbis** [comment]
The advanced menus are being reworked, so they'll be perhaps less confusing in the future. It's a slow roll-out though, so nothing soon.
