### ISSUE TITLE
Engines keep coming back after deletion

### ISSUE THREAD

**Issue by Bhaalspawn** [ssborbis/ContextSearch-web-ext#647]
This happens only in firefox, not Vivaldi so maybe there is conflict with some Firefox setting (?)
i delete engines, but after restarting, i see those engines back. they all have the orange FF icon at the end.
i can simply hide them and it's what i do but it's still a bug

They don't even work, in fact they don't have a full template, just the icon URL

**Comment by ssborbis** [comment]
Those are the engines from the Firefox search bar. They are automatically imported. You can either hide them or delete them from the Firefox search bar `Settings -> Search -> Search Shortcuts`

> They don't even work,

Hmm... they should.

**Comment by Bhaalspawn** [comment]
but i didn't even choose to import, so they shouldn't be there.
yes i can hide them, why should i delete them from the searchbar?? i still use it. not everything i search i can highlight and use the popup menu.

**Comment by ssborbis** [comment]
You could put them in a separate folder and hide the folder until there's a better option. They should stay in that folder and not be seen by any menus

**Comment by Bhaalspawn** [comment]
uhm ok, this is not a big problem, i was only asking if there was a way to avoid those engins to recreate after deleting them

if you read this please wait 5 min, i'm going to ask something else

**Comment by ssborbis** [comment]
There's a new option to disable automatically checking for Firefox engines. It should be in the next release. If you want to test, it's currently in the master branch

**Comment by Bhaalspawn** [comment]
> There's a new option to disable automatically checking for Firefox engines. It should be in the next release. If you want to test, it's currently in the master branch

Ok but please fix this
https://github.com/ssborbis/ContextSearch-web-ext/issues/607

it's much more important

**Comment by ssborbis** [comment]
v1.46.14 going up
