### ISSUE TITLE
Can this web-extension be ported to chrome?

### ISSUE THREAD

**Issue by jerryawe** [ssborbis/ContextSearch-web-ext#65]

**Comment by ssborbis** [comment]
It's webextensions-based based so probably. I don't think I use too much moz specific code for the core but I can't say what it would take to port it to chrome. Are you a dev?

**Comment by jerryawe** [comment]
I'm not a dev，thank you. Chrome web store have many similar extensions,  But the function is not as good as your extension. Many users expect to have the opportunity to use ContextSearch-web-ext in chrome in the future.Great extensions are cross-platform.

**Comment by ssborbis** [comment]
Early testing looks promising. Most functionality should be available to Chrome in the next release

**Comment by ssborbis** [comment]
Repo updated with Chrome-compatible code. Needs plenty of testing

**Comment by ssborbis** [comment]
https://chrome.google.com/webstore/detail/ddippghibegbgpjcaaijbacfhjjeafjh/publish-accepted?authuser=0&hl=en-US

**Comment by ssborbis** [comment]
https://chrome.google.com/webstore/detail/contextsearch-web-ext/ddippghibegbgpjcaaijbacfhjjeafjh

**Comment by hg42** [comment]
it's totally awesome to be able to export the settings from firefox an import them in chrome...including all my search engines...thanks...

**Comment by ssborbis** [comment]
Cool. There was a lot less code to change than I thought there would be to port to chrome... that's webext for ya.

**Comment by hg42** [comment]
yes, but unfortunately I lost a lot of beloved features implemented by extensions of firefox that were true advantages over chrome. Extensions like Location Bar enhancer.
On the other hand you came up with my second favorite extension just after Tree Style Tab!
