### ISSUE TITLE
Add-Deepl-in-ContextSearch-web-ext

### ISSUE THREAD

**Issue by milt983** [ssborbis/ContextSearch-web-ext#650]
Hello! Sorry I have no idea how to do, manually, to add Deepl translator in ContextSearch web-ext search engines. Any help? Thanks.

**Comment by ssborbis** [comment]
You can look here and click the "Add to CS" icon on the engine you want. If you don't see the exact language you need, you can add one that you see and edit the template to suit your usage. https://mycroftproject.com/search-engines.html?name=deepl

If you need more help, I'd be happy to guide you through the process.

**Comment by ssborbis** [comment]
I'm cleaning up some old threads. If you need more help with this, please reopen the issue.
