### ISSUE TITLE
Importing Firefox list into Chrome

### ISSUE THREAD

**Issue by nollinvoyd** [ssborbis/ContextSearch-web-ext#656]
I import the list, which has a bunch of engines, and everything below the top 12 on the list is greyed out.  Firefox is ok.

I added "StartPage", in this form "https://startpage.com/do/metasearch.pl?query=%s".

It is not greyed out, but it doesn't work.  

I've gone thru the settings.  Whatever adjustments I tried did not help.  Are a high number of search engines not compatible in Chrome?

**Comment by ssborbis** [comment]
Hmm... are the missing engines listed as Firefox engines ( orange oval with white FF ) in Firefox? Any engines used in the Firefox search bar will not be accessible to Chrome. 

If possible, you can zip and post your config here or email me directly, and I'll try importing to Chrome on my machine to see what happens.

**Comment by nollinvoyd** [comment]
EDIT:  All greyed out look like this

![search2](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/7105aace-aab6-43e2-a546-9ce8ef4e18c1)

Do you still want that zip file?

**Comment by ssborbis** [comment]
Those marked with FF are references to Firefox engines only, and not available for export in their current state. 

If you want to copy those engines to Chrome, you must first fully import them into Firefox.

![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/c280674b-08c6-4f85-99a3-8bbf285004e6)

Click the `Select File` button and browse to your search.json.mozlz4 file in your profile directory.  Doing this will replace references to Firefox engines (FF) with fully imported version of those same engines. These fully imported engines can then be exported, and used with Chrome.

**Comment by ssborbis** [comment]
I just checked and there appears to be a bug with the importer code. I'll take a look and let your know what i find.

**Comment by ssborbis** [comment]
Ok, a fix is in the master branch, and I'll get a new Firefox release out in the next couple days.

**Comment by nollinvoyd** [comment]
Great.  

I don't know if this is related.  I created this in Chrome.  

![MOZ](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/f0c34462-265a-4a6c-b960-082fd6a01ebe)

It creates a search inside of Mozillazine, which is my preference, i.e.,

![mox chrome](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/a1d9bfd9-545a-438c-bbc3-779f9136594f)

I tried to do it in Firefox, this is the result

![mox fire](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/2e0ae1a7-57e5-4fcf-8e9a-4338cb7af328)

**Comment by ssborbis** [comment]
Using the exact same template in Firefox, it blocks your search? That's odd. I'll try it myself.

**Comment by ssborbis** [comment]
1.46.16 is live on AMO. No chrome release, but it's mostly a hotfix for this FF issue.

**Comment by nollinvoyd** [comment]
> 
> (edit) Do you need to be logged in to mozillazine to perform a search

Yes,  but I just updated,  That MOZILLAZINE engine I mentioned now works in Firefox, but yes, I'm must be logged in, so I don't know if that was the case before.   I'm guessing it's not supposed to be like that, I hopefully, since it's not necessary in Chrome?

I've also been exploring the settings.  Extensive.  Impressive.  I'm trying to process.  You wouldn't happen to have a video? I tried a few things that don't seem to be working for me.   Probably something I'm not doing right?

![context add](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/ebb00e88-997c-4317-9070-8f66b7499f81)

![SEARCH BAR](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/119e5a66-6ddd-4335-a58c-edc106069909)

![search side panel](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/a201b1fd-2930-40da-9418-5b59c93095a4)

I got the impression this could be done in text only?  And don't know what all those blank icons are about? 

![search text ](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/2738efa0-17dd-478b-a97e-5df370aa4982)

![context grid](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/c4106262-0497-4b24-b317-ca0809fc74c2)

![search button](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/c132fcf9-209a-4fcc-8387-05ef612c51a3)

**Comment by ssborbis** [comment]
I'm not sure what the first set of screenshots are trying to show, but if you're asking about displaying the engines as a list with text, and not simply icons, you can click the icon in your last image to the right of the mozillazine icon. ( Grid / List )

The screenshot with all the blank icons with the header "Layout" is for a drag & drop feature that opens a full page menu of your chosen layout. If you choose "enable pagetiles" on that same menu, select some text, and start to drag it a ways, it should pop up an overlay showing that grid layout. It's a separate menu from the last screenshot you posted.

**Comment by nollinvoyd** [comment]
> I'm not sure what the first set of screenshots are trying to show, 
>

The top image, I thought it related to this, enabling me to add the search engine for the place I was visiting, but the option is not there

![context add2](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/7f3a87f9-e415-4feb-8157-29689bdc6a27)

> but if you're asking about displaying the engines as a list with text, and not simply icons, you can click the icon in your last image to the right of the top-most mozillazine icon. ( Grid / List )
> 

Got it.

**Comment by nollinvoyd** [comment]
I went here, but I'm don't understand "Right-click the search bar on "any" webpage".  I don't have that elsewhere.

![context add3](https://github.com/ssborbis/ContextSearch-web-ext/assets/20844322/715935a2-fadc-40bb-944d-d180bdec53af)

**Comment by ssborbis** [comment]
You might try on a different website. Mozilla blocks Firefox addons from working on mozilla sites.

**Comment by nollinvoyd** [comment]
Sorry for all the questions.

Can you suggest another site that works for you? Should I be seeing that on Chrome as well?

Any fix for searching Mozillazine without logging in?

**Comment by ssborbis** [comment]
> Any fix for searching Mozillazine without logging in?

I'm not sure. The actual search bar on mozillazine uses a google site search. You could try changing your template to that I suppose.

**Comment by ssborbis** [comment]
I'm doing some housekeeping on old issues. If you still need help with anything in this thread, please reopen it.
