### ISSUE TITLE
Force uppercase/lowercase

### ISSUE THREAD

**Issue by Bhaalspawn** [ssborbis/ContextSearch-web-ext#657]
how do i force the result to have all lowercase letters even if the name has uppercase letters?

Example
From: "Lionel Messi" to "lionel-messi"

i was told to put "/\s+/-/g" to make the "-" appear between the 2 words but i also need the to make L and M uppercase

**Comment by ssborbis** [comment]
Do you mean you need the search terms changed to lowercase before being used with the engine?

Newer versions can use the following in template strings for search engines
 `%s` or `{seachterms}` - as selected / mixed case
`%su` or `{SEARCHTERMS}` - UPPERCASE
`%sl` or  `{searchterms}` - lowercase

TBH, I haven't found a need to verify they work, so please let me know.

**Comment by Bhaalspawn** [comment]
Don't work
Bothe %sl and {searchterms} work when i use test BUT
{searchterms} can't even be saved because t turns back to uppercase when i click "save"
%sl just doesn't work even if test was ok

**Comment by ssborbis** [comment]
I've removed the code that changes {searchterms} back to {searchTerms}.
On my machine, %sl and %su work fine, using the Test button and normal use. Is that what you're seeing or no?

**Comment by ssborbis** [comment]
> what do you mean you removed the code?? i

Sorry for the confusion. What I meant was, based on your bug reporting ( thanks btw ), I've removed the code that replaces `{searchterms}` with `{searchTerms}` when you save the template. The new code will be in the next release.

**Comment by Bhaalspawn** [comment]
ok thanks. at the moment %sl is working so it's ok

**Comment by ssborbis** [comment]
Please re-open this thread if you're still having issues with uppercase / lowercase
