### ISSUE TITLE
Access to settings

### ISSUE THREAD

**Issue by Bhaalspawn** [ssborbis/ContextSearch-web-ext#658]
Specially on firefox because i can't right click on toolbar icon.... 

At the moment if i want CS toolbar i have to nable it also on quick menu (actually i have to go in quick menu section to enable the toolbar). But i would like to have it just on FF toolbar button and not in the quick menu.

On Vivaldi/Edge at least i can right click CS icon and i can access settings, but not on Firefox

**Comment by ssborbis** [comment]
Do you have any screenshots of your toolbar menu? Is it missing the gear icon for accessing settings?

I see what you mean about the `options` option when you right-click the extension's icon on the toolbar in Vivaldi. I guess Firefox doesn't have that listed in the menu.

On Firefox, you'll need to click the toolbar icon, open the menu, and then click the gear icon to get to settings. There's no reason you need this icon to display in the quick menu as well. They have independent layouts and you can choose to have the menu bar on or off by clicking the layout manager tool button. If you do not have that tool showing, you'll need to temporarily enable it through the quick menu settings or add a new tool to the search engines manager. I should add a more direct access like a shortcut for the layout editor... 


![toolbar](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/70a4644e-e3ec-4fd0-8244-e64cf6ab8496)

**Comment by Bhaalspawn** [comment]
it worked but it's not as nice as when using the toolbar. if there was a way to activate the CS toolbar on the button separately from the activation in the quick menu it would be better.
Also because activating the various layouts is not intuitive

**Comment by ssborbis** [comment]
> if there was a way to activate the CS toolbar on the button separately from the activation in the quick menu it would be better

I'm sure we're dealing with a language barrier, so if you could post some screenshots of what you're seeing, and what you're wanting done differently, it may help me understand better.

**Comment by ssborbis** [comment]
Not sure if this helps exactly, but I've added this option to Firefox when right-clicking the toolbar icon

![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/0a7b6cf2-770b-4467-b59b-8daf574247f9)

**Comment by ssborbis** [comment]
New version going up 1.46.17 with the additional changes.

**Comment by Bhaalspawn** [comment]
Sorry for late reply. 
i don't know what you added.
I meant that now i can enable CS toolbar 

![Cattura](https://github.com/ssborbis/ContextSearch-web-ext/assets/20135076/c6402b3f-d73a-4c44-8647-d27f50c895f9)

only from the Quick menu section. and if i enable it there, i see it also in the menu of the Firefox toolbar icon

It would be nice if CS would have its own section and then decide where i want to see it (checking FF toolbar and/or quick menu or nothing)

**Comment by ssborbis** [comment]
![disable_tools](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/f929724c-5895-4bef-987b-b5c1aa17f94e)
