### ISSUE TITLE
The extension is not working on some sites

### ISSUE THREAD

**Issue by Zack11111** [ssborbis/ContextSearch-web-ext#663]
Hi

ContextSearch stopped to work on some sites in Chrome and Firefox.  I tried add that search engines again by clicking on "Add to ContextSearch" in search bar, but useless, no results.

**Comment by ssborbis** [comment]
By "stopped working", do you mean the menus do not open on those sites, or the engine / template you are using does not produce results for those sites?

**Comment by ssborbis** [comment]
![Peek 2023-10-11 01-28](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/2cb127f0-2052-4b8b-b0ec-d445dbc2942a)

**Comment by Zack11111** [comment]
> By "stopped working", do you mean the menus do not open on those sites, or the engine / template you are using does not produce results for those sites?
Template does not produce results for those sites. A week ago it was ok. I copy some parameters below: 

Template
https://rutracker.org/forum/tracker.php
Form Path
https://rutracker.org
POST params
nm={searchTerms}&f[]=-1&o=7&s=2&tm=-1
Method
POST
Encoding
utf-8

**Comment by Zack11111** [comment]
I checked all search engines added to ContextSearch by me. All POST method engines are not working. No search results. It opens just main page of these sites.

**Comment by Zack11111** [comment]
I think I got a clue. I am changing all POST method search engines to GET method. And I cut Post parameters and paste it to Template box with ? symbol in front. Most of them fixed, but some sites not yet.

**Comment by ssborbis** [comment]
> I checked all search engines added to ContextSearch by me. All POST method engines are not working. No search results. It opens just main page of these sites.

Thanks for that. I'll see whats going on with POST engines and let you know.

**Comment by ssborbis** [comment]
I think I've got the fix. 1.46.23 going up now
