### ISSUE TITLE
open search result in chrome on new tab next to current tab

### ISSUE THREAD

**Issue by rezad1393** [ssborbis/ContextSearch-web-ext#664]
when I use this addon to search in chrome and try to search stuff the result is opened at the end of tabs.

normal search (built-in search) opens the result in new tab next to current tab.

how can I make the addon open it next to current tab.

**Comment by ssborbis** [comment]
I think the setting `forceOpenResultsTabsAdjacent` is what you want. CS Options -> Advanced Tab -> Manual Edit button
