### ISSUE TITLE
How to make a search engine default?

### ISSUE THREAD

**Issue by svefn** [ssborbis/ContextSearch-web-ext#667]
Hi, so I removed the DuckDuckGo default search engine made by Firefox because I wanted to add it myself but I can't make DDG the default now even though I added it with ContextSearch. I remember using the + in ContextSearch to install to Firefox One Click Search Engines, but clicking it doesn't seem to add it. How I do I make a search engine default using ContextSearch or it is not possible?

**Comment by ssborbis** [comment]
Default engine is the first in the search engines manager list. Sounds like there may be something else going on though. 

How are you using the default engine? Pressing enter after typing a search into the bar?

**Comment by svefn** [comment]
Yeah the default search in Firefox is just typing the search terms and enter. I did manage to make DDG default by clicking the '+' and then it shows up a green + sign in the search toolbar so you can click that to add it to Firefox's One Click engines, I needed it to be added to Firefox One Click because then only I can select it as the default search engine in settings. I had the search toolbar + address bar combines before so I didn't see the green + sign, and clicking the + in ContextSearch options doesn't do anything then.

**Comment by ssborbis** [comment]
> clicking the + in ContextSearch options doesn't do anything then.

Looks like that's a bug that prevents an error message from showing up, informing the user that the engine you're trying to install is already installed. Should be fixed in the next release. I'm not sure this bug happens if the engine is new, but likely not.
