### ISSUE TITLE
How to have popular search engines on the primary context menu?

### ISSUE THREAD

**Issue by zapta** [ssborbis/ContextSearch-web-ext#669]
I added a few search engines that I use often and they work well. Thanks.

Is it possible to mark a few of them such that they will show up on the primary context menu, rather than in the secondary one that opens with "ContextSearch web-ext" ?  This will speed up their selection.

<img width="594" alt="Screenshot 2023-11-18 at 11 46 42 AM" src="https://github.com/ssborbis/ContextSearch-web-ext/assets/2184769/b0684174-73c6-4285-8401-d91fface8722">

**Comment by ssborbis** [comment]
Unfortunately, no. Extensions are only allowed 1 entry on the main menu.
