### ISSUE TITLE
Settings form shows an error on a valid field value.

### ISSUE THREAD

**Issue by zapta** [ssborbis/ContextSearch-web-ext#671]
This was observed on Chrome and Windows 10. The URL is valid what the error message persists until I save the form. Entering the field and moving to another field doesn't eliminate the error message, just a full form saving.

While editing the form:
![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/2184769/f6de7356-063d-4320-bdec-3b347625a127)

After save:
![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/2184769/e5916539-cfba-4d5e-a715-0b2f5c8524b0)

**Comment by ssborbis** [comment]
Errors are only checked for at save. I'll see about adding checks after changes.

**Comment by zapta** [comment]
Thanks for looking into it.

**Comment by ssborbis** [comment]
I believe this made it into the releases. If it's still an issue, please reopen.
