### ISSUE TITLE
Search engines are not launched from PDF files.

### ISSUE THREAD

**Issue by zapta** [ssborbis/ContextSearch-web-ext#672]
When a PDF is opened in Chrome, launching the default search engine from the context works as expected. Howerver, with the SearchContext custom search engine, the search page is not lancuned.

Default search:
<img width="656" alt="Screenshot 2023-11-20 at 7 25 51 PM" src="https://github.com/ssborbis/ContextSearch-web-ext/assets/2184769/4c413d5f-6815-4255-ba1e-f1366beb50eb">

ContextSearch search:
<img width="656" alt="Screenshot 2023-11-20 at 7 26 22 PM" src="https://github.com/ssborbis/ContextSearch-web-ext/assets/2184769/dcda0ece-2320-413b-9d9d-236f98ba5da3">

**Comment by ssborbis** [comment]
Thanks. Fix in the master branch now. I'll post again when the next release is out.

**Comment by zapta** [comment]
Thanks for fixing it.

**Comment by ssborbis** [comment]
This bug must have reappeared since my last post here. I believe this is now fixed in latest releases.
