### ISSUE TITLE
Default Engine: If Search inquiry contains ".com" go to website.

### ISSUE THREAD

**Issue by MachineThatGoesP1NG** [ssborbis/ContextSearch-web-ext#673]
I'm trying to make it so that if I search "youtube" I get results in Google search for youtube but if I search "youtube.com" then it takes me to the website youtube.com.

I'm sorry i don't know how to code so I'm guessing something like:

Ifinstring, searchTerm, ".com"
Website
Else
Google

I'm pretty much trying to replace ff address bar with your extension — too bad ff doesn't allow custom search engine bars in the toolbar.

**Comment by ssborbis** [comment]
Which menu are you searching from? I'm sure we can make a bookmarklet that does the job.

**Comment by MachineThatGoesP1NG** [comment]
> Which menu are you searching from? I'm sure we can make a bookmarklet that does the job.

Oh I'm sorry I'm searching from the ?quick menu? from the icon in the toolbar.

**Comment by ssborbis** [comment]
You can kinda get away with it with a script like this

```javascript
if ( /\.(.{2,3}$:?)/.test(searchTerms) ) {
     if ( !searchTerms.startsWith("http") ) searchTerms = "http://" + searchTerms;
     window.open(searchTerms, "_blank");
} else 
     window.open("https://www.google.com/search?q=" + searchTerms, "_blank");
```
