### ISSUE TITLE
How to prevent quick menu tool's toolbar from appearing?

### ISSUE THREAD

**Issue by bottleblue** [ssborbis/ContextSearch-web-ext#678]
When I hold right mouse button I get this small toolbar with icons that pops up. It's from Options , Quick Menu, under Tools. I disabled all the icons but I'm still left with this blank toolbar.  Is there any way to disable that?

![bar](https://github.com/ssborbis/ContextSearch-web-ext/assets/3678136/0e98764e-44ad-4e4d-b7bf-a51eb321bbee)

**Comment by ssborbis** [comment]
Are you trying to disable the quick menu entirely? Or just the section with the tools?

To disable QM:
     
![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/f81b6a60-3680-4483-a40e-b7ff5246b39d)

To hide the tools bar:

![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/aabc0931-790b-4a97-82d9-1872225aa771)



If neither fix it, you might need to post your config so I can see exactly what's going on.

**Comment by bottleblue** [comment]
Just the section with the tools. I tried those settings and it didn't work. This never happened before. It must be a new problem but I haven't changed any of my settings. How do I post my config? Just screenshots of all the options?
