### ISSUE TITLE
Right click menu doesn't show

### ISSUE THREAD

**Issue by Moongose83** [ssborbis/ContextSearch-web-ext#68]
I don't know why, but the right click quick menu doesn't show no matter how long do I keep it pressed.  Any ideas how to make it work again?

**Comment by ssborbis** [comment]
It was working and now it doesn't? What version are you using?

**Comment by Moongose83** [comment]
Yes exactly. I'm currently using 1.6.3.2.  W10 64bit. Yes, other metods work just fine.

**Comment by ssborbis** [comment]
Strange. Conflict with another add-on? Mouse button going bad causing signal bounce (this happened to me)?

**Comment by ssborbis** [comment]
How long ago did it stop working?

**Comment by Moongose83** [comment]
Yea, it was conflict with another add-on. It's called "Snap Links". I got rid of it. Thanks for your quick help.

**Comment by ssborbis** [comment]
No prob
