### ISSUE TITLE
Vivaldi - Symbols are not displayed

### ISSUE THREAD

**Issue by merlin555** [ssborbis/ContextSearch-web-ext#680]
Hello everyone,

The symbols are not displayed in Vivaldi Browser.
Just the text.

I highlight a word with the mouse and press the right mouse button.
The icons are missing in this window.
<img>https://i.ibb.co/1nLHBZk/Vivaldi.png</img>

In Firefox it works:
<img>https://i.ibb.co/TgHpGjY/Firefox.png</img>

Send my settings here.

Greetings,

 Merlin

[ContextSearchOptions_2024-02-09_094044.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/14220425/ContextSearchOptions_2024-02-09_094044.zip)

**Comment by ssborbis** [comment]
Chrome variants, like Vivaldi, lack the capability of showing icons in context menus beyond the top tier icon. Firefox can, others cant. At least, this was true last I checked. If you see other addons showing icons beyond the top tier, let me know and I'll look to make those changes here.

**Comment by merlin555** [comment]
@ssborbis 
That's not bad.
What is unfortunately very annoying is the formatting.
Because the symbols are not displayed, it appears as a white empty space and looks strange.
Can you remove that, that blank space?
Would it be possible?

**Comment by ssborbis** [comment]
I think that's just how Vivaldi displays menus. I took a quick look at other menus with a submenu ( Images and Developer Tools ) and it's the same way.

**Comment by merlin555** [comment]
@ssborbis 
Does that mean it's not possible?

**Comment by ssborbis** [comment]
I don't believe it is, at least, not through this addon. Chromium and Edge seem to handle it better though. They remove the extra width when there are no icons in the menu.

**Comment by merlin555** [comment]
@ssborbis 
Do you mean removing the icon URL?
Doesn't work for me.

**Comment by ssborbis** [comment]
It seems to be a Vivaldi issue. I don't think there is anything I can do about the extra space. Sorry :(

**Comment by merlin555** [comment]
@ssborbis 
Not so bad.
Thank you for answering.
