### ISSUE TITLE
Performance impact Speedometer 3.0

### ISSUE THREAD

**Issue by fy0z9b7q** [ssborbis/ContextSearch-web-ext#686]
This is a duplicate of issue #257  [https://github.com/ssborbis/ContextSearch-web-ext/issues/257](url) but updated for Speedometer 3.0.

When "Enable searching via popup menu" is enabled in ContextSearch, the Firefox 123.0.1 scores for Speedometer 3.0 are cut in nearly half (18.4 +/- 0.59 to 9.99 +/- 0.26 on my machine).

Even if this is not a "real world" performance degradation, it is a "bad look". I have no idea whether this is a Firefox issue or a ContextSearch issue, but I hope someone can improve it.

**Comment by fy0z9b7q** [comment]
Additional data: I enabled the context search extension with the most users from addons.mozilla.org, [Context Search](https://addons.mozilla.org/en-US/firefox/addon/contextual-search/). With it enabled (searching via popup menu) there was no measurable Speedometer 3.0 performance degradation.

**Comment by ssborbis** [comment]
I feel like this has been mentioned before. I'll have to look back through past threads, but I though it was an issue regarding how Speedometer runs it's tests (iframes maybe?) and how this addon injects into iframes. I seem to remember the test being misleading as a result, but I can look again.

**Comment by ssborbis** [comment]
The latest code in the master branch moves iframe injection to on-demand and when iframes receive focus. This has the effect of significantly speeding up Speedometer 3.0 results.
