### ISSUE TITLE
I need help in Post-Search Script 

### ISSUE THREAD

**Issue by MW-J97** [ssborbis/ContextSearch-web-ext#687]
Hi there.

When I search in this website e.g., Ricky Rich & ARAM Mafia - Habibi (Official Audio), there is something going wrong in the link.
This is the actual link when I search normally through the website itself: https://beemp3.in/file/ricky-rich-aram-mafia-habibi-official-audio.html
This is when I search with CS: https://beemp3.in/file/Ricky%20Rich%20%26%20ARAM%20Mafia%20-%20Habibi%20(Official%20Audio).html 
 
Edit: when I added this script, `/\s+/-/g`, this is the result: https://beemp3.in/file/Ricky-Rich-%26-ARAM-Mafia---Habibi-(Official-Audio).html 
I think the problem here with &, () and spaces.

Is there any way to modify this link?
Thanks in advance.

**Comment by ssborbis** [comment]
I think you need to filter out all non letters and numbers, then replace spaces with hyphens

Something like...
```
/[^A-Za-z0-9]/ /g
/\s+/-/g
```

There's still an issue of a trailing hyphen, but that should get you close

**Comment by ssborbis** [comment]
Oh, and change your template variable to `%sl` to get all lowercase

**Comment by MW-J97** [comment]
> /[^A-Za-z0-9]/ /g
> /\s+/-/g

> Oh, and change your template variable to `%sl` to get all lowercase

I think it works fine, thanks so much for help. 

> There's still an issue of a trailing hyphen, but that should get you close

Yes, there is a trailing one in the end of the search. Till now, it doesn't affect and I'll give it a try. 
But if it's can be deleted, that'll be perfect.

**Comment by ssborbis** [comment]
I think you could add a regex line `/-$//g` to remove an ending hyphen

**Comment by MW-J97** [comment]
> I think you could add a regex line `/-$//g` to remove an ending hyphen

No, I think it's not working.

**Comment by ssborbis** [comment]
It's working for me using the test string you provided

```
/[^A-Za-z0-9]/ /g
/\s+/-/g
/-$//g
```
`Ricky Rich & ARAM Mafia - Habibi (Official Audio)` -> `ricky-rich-aram-mafia-habibi-official-audio`

**Comment by MW-J97** [comment]
> /[^A-Za-z0-9]/ /g
> /\s+/-/g
> /-$//g

I think it works now. Maybe I wrote it wrongly. 
Thank you so much.
