### ISSUE TITLE
How to use Bookmarklets with Context Menu？

### ISSUE THREAD

**Issue by runningcheese** [ssborbis/ContextSearch-web-ext#690]
#492
There is a same issue  2 years ago.  
Has this problem been resolved now?
Are there any browser restrictions?
Thank you！

**Comment by ssborbis** [comment]
What is your bookmarklet code? I just tested a basic script with both the popup menu and the context menu and it seems to be working.

**Comment by ssborbis** [comment]
It's failing because of CORS. A workaround would be to open the new tab to the current location, then wipe the old HTML before writing the new HTML

```javascript

outText='';
for (i=0;i<document.images.length;i++){
	if (outText.indexOf(document.images[i].src)==-1) {
		outText+='<tr><td><img style=max-width:800px src='+document.images[i].src+'></td><td>'+document.images[i].naturalWidth+'x'+document.images[i].naturalHeight+'</td></tr><p>';
	}
}
if (outText != '') {
	imgWindow=window.open(window.location.href,'imgWin');
  imgWindow.document.innerHTML = null;
	imgWindow.document.write('<table style=margin:auto border=1 cellpadding=10><tr><th>Image</th><th>Size</th></tr><p>'+outText+'</table><p>');imgWindow.document.close();
} else{
	alert('No Images!');
}
```

**Comment by runningcheese** [comment]
thanks for your info,
but try is extension：https://addons.mozilla.org/en-US/firefox/addon/bookmarklets-context-menu
it works well, any alternative solution? @ssborbis

**Comment by ssborbis** [comment]
I have a possible workaround going into the master branch if you want to test. You'll need to enable the advanced setting `scriptsUseBlobs : true`

**Comment by runningcheese** [comment]
hi @ssborbis, 
I just downloaded the master branch file you mentioned, and reload it from browser,
and i am sure the advanced setting scriptsUseBlobs : true is on, 
but the test didn't go through on chrome.

in the end,
when will this new feature be pushed to the new version?

**Comment by ssborbis** [comment]
It appears that the test code you provided is working in chromium without the need for the additional setting. I get the same results whether the setting is enabled or not.

Firefox, however, required the new setting enabled to avoid CORS issues. Are you testing using the code you provided to test with, or some other bookmarklet code?

**Comment by ssborbis** [comment]
If you'd been testing with scripts that contain searchTerms, they would have been failing. Try the latest code in the master branch

**Comment by runningcheese** [comment]
@ssborbis 
Unfortunately,
The new version still not working. I tested it with the simplest code `javascript:alert('hi');` 
I have to select text before I can run it, 
what i hope for is that running it from the context menu.

**Comment by ssborbis** [comment]
Ok, I think the failure was due to needing to select text first. The latest push has a fix for that.

**Comment by runningcheese** [comment]
@ssborbis 
Finally! 
It works now.
That's exactly what I hope for. 
When will the new version to be released? I can't wait any longer!

**Comment by runningcheese** [comment]
@ssborbis
A big thanks for your update!!!
In the latest version, chrome and edge are working fine, 
but in firefox, some bookmarklets will only display a new tab, and the function cannot be executed.
try this code, doesn't work in firefox:

`javascript:outText='';for(i=0;i<document.images.length;i++){if(outText.indexOf(document.images[i].src)==-1){outText+='<tr><td><img style=max-width:800px src='+document.images[i].src+'></td><td>'+document.images[i].naturalWidth+'x'+document.images[i].naturalHeight+'</td></tr><p>'}};if(outText!=''){imgWindow=window.open('','imgWin');imgWindow.document.write('<table style=margin:auto border=1 cellpadding=10><tr><th>Image</th><th>Size</th></tr><p>'+outText+'</table><p>');imgWindow.document.close()}else{alert('No Images!')}`

**Comment by runningcheese** [comment]
Update：
After set "scriptsUseBlobs": true, everything works fine now!

**Comment by rezad1393** [comment]
is scriptsUseBlobs gonna be in a new version soon?

**Comment by rezad1393** [comment]
> is scriptsUseBlobs gonna be in a new version soon?

because I am trying to use this bookmarklet to load broken images:
`javascript: (() => {  (function()%7Bvar%20images%20%3D%20document.querySelectorAll('img')%3Bfor%20(var%20i%20%3D%200%3Bi%3C%20images.length%3Bi%2B%2B)%20%7Bif%20(images%5Bi%5D.naturalWidth%20%3D%3D%3D%200%20%7C%7C%20!images%5Bi%5D.complete)%20%7Bimages%5Bi%5D.src%20%3D%20images%5Bi%5D.src%3B%7D%7Dvar%20allEle%20%3D%20document.querySelectorAll('*')%3Bfor%20(var%20i%20%3D%200%3B%20i%3CallEle.length%3B%20i%2B%2B)%20%7Bvar%20bgimg%20%3D%20getComputedStyle(allEle%5Bi%5D).getPropertyValue('background-image').replace('url(%22'%2C'').replace('%22)'%2C'')%3Bif%20(bgimg%20!%3D%3D%20'none')%20%7BallEle%5Bi%5D.style.backgroundImage%20%3D%20'url(%22'%2B%20bgimg%20%2B'%22)'%3B%7D%7Dimages%20%3D%20%5B%5D%3BallEle%20%3D%20%5B%5D%7D)(); })();`
