### ISSUE TITLE
Search Actions: Open In Current Tab works no more

### ISSUE THREAD

**Issue by 11100010** [ssborbis/ContextSearch-web-ext#692]
No idea why it suddenly doesn't work no more, because I use this feature like every moment browsing the internet.

Only fails on Chrome. The feature works fine on Firefox.

"Open In New Tab" works fine on both browsers.

Anybody has any idea?

**Comment by 11100010** [comment]
update:
It works fine on Chrome Canary
Version 121.0.6110.0 (Official Build) canary (arm64)

Still fails on Chrome
Chrome is up to date
Version 123.0.6312.107 (Official Build) (arm64)

**Comment by ssborbis** [comment]
Ok, found the issue. Fix is in the master branch if you're sideloading.
