### ISSUE TITLE
How to add this searcg engin, it looks rare！

### ISSUE THREAD

**Issue by runningcheese** [ssborbis/ContextSearch-web-ext#693]
Website：
https://kimi.moonshot.cn
I've tried all id and class, but not working.
Thanks in advance.

Update：
It's works with this code.
`document.querySelector('[contenteditable]').textContent = searchTerms;`

But the problem is, 
This website is built with the React framework. 
If we directly insert content, the search icon at the end won't be clickable. Can this issue be resolved?

<img width="500" alt="iShot_2024-05-11_22 04 50" src="https://github.com/ssborbis/ContextSearch-web-ext/assets/4476264/d5cab4ec-0687-4443-af01-053b1b04fdbe">
<img width="600" alt="iShot_2024-05-11_22 05 35" src="https://github.com/ssborbis/ContextSearch-web-ext/assets/4476264/5b5614b1-7797-4a3d-b0c2-0ef0ba582a85">

@ssborbis

**Comment by ssborbis** [comment]
Ok, I got in via VPN but there's some kind of login before I can search.

![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/c277ea33-17c1-485e-bd3e-2dd373a121a6)

**Comment by ssborbis** [comment]
Try something like
```javascript
document.querySelector('[contenteditable]').textContent = searchTerms;
```

**Comment by runningcheese** [comment]
Thanks ssborbis, it works!

**Comment by runningcheese** [comment]
Update：
It's works with this code.
`document.querySelector('[contenteditable]').textContent = searchTerms;`

But the problem is, 
This website is built with the React framework. 
If we directly insert content, the search icon at the end won't be clickable. Can this issue be resolved?

<img width="500" alt="iShot_2024-05-11_22 04 50" src="https://github.com/ssborbis/ContextSearch-web-ext/assets/4476264/d5cab4ec-0687-4443-af01-053b1b04fdbe">
<img width="600" alt="iShot_2024-05-11_22 05 35" src="https://github.com/ssborbis/ContextSearch-web-ext/assets/4476264/5b5614b1-7797-4a3d-b0c2-0ef0ba582a85">

@ssborbis
