### ISSUE TITLE
Possibility? Auto-copy image when i use {searchTerms} with context menu?

### ISSUE THREAD

**Issue by runningcheese** [ssborbis/ContextSearch-web-ext#694]
If i use context menu search,
can it copy image to the clipboard automatically? 
and also automatically paste? 
thanks in advance! 

`https://www.google.com/searchbyimage?sbisrc=4chanx&safe=off&image_url={searchTerms}`

**Comment by ssborbis** [comment]
Copy what? The image from the URL you search for ( the `{searchTerms}` ) to the clipboard?

I think you could do that with some post-search script.

And paste to where?

**Comment by runningcheese** [comment]
Copy image itself to clipboard.
Because some websites don't offer the URL option, you can only copy and paste image.
Anyway, When will the new version to be released? 
Can't wait any longer!
