### ISSUE TITLE
Version 1.46.25 (latest?) not working

### ISSUE THREAD

**Issue by f73** [ssborbis/ContextSearch-web-ext#697]
As per title, extension v1.46.25 no longer works after latest update, tried firefox 124.0.2 just before update to firefox 125.0.2. Not working on chrome 124.0 as well.

I would like to take the opportunity to thank you for great extension!

**Comment by WakeXT** [comment]
Since the latest update to version 1.46.25 it only seems to work partially (browser is Firefox 126B4):
Using the currently active search-engine via context menu which for me defaults to
_Search Google IFL for "xyz"_
works fine but the menu at the bottom where you select
_Search for "xyz"> list of all my search engines_
to select which one to search with for the marked text is broken and won't open a new tab or start a search at all.

**Comment by MarkRH** [comment]
Version 1.46.25 in Firefox 125.0.2 seems to have broken the Context Menu.. I select any of them to do a search and nothing happens.

**Comment by exec228** [comment]
Same here:
home Fx LTS 115 - stopped opening a new window with search engine;
work Fx 125 - stopped opening new window with search engine.

**Comment by ssborbis** [comment]
New version going up with a potential fix. I'm not sure why I wasn't seeing this bug on my test setup.

**Comment by runningcheese** [comment]
@ssborbis
A big thanks for your update!!!
In this issue,  https://github.com/ssborbis/ContextSearch-web-ext/issues/690
there is a little problem.

In the latest version, 
chrome and edge are working fine,
but in firefox, some bookmarklets will only display a new tab, and the function cannot be executed.
try this code, doesn't work in firefox:

javascript:outText='';for(i=0;i<document.images.length;i++){if(outText.indexOf(document.images[i].src)==-1){outText+='<tr><td><img style=max-width:800px src='+document.images[i].src+'></td><td>'+document.images[i].naturalWidth+'x'+document.images[i].naturalHeight+'</td></tr><p>'}};if(outText!=''){imgWindow=window.open('','imgWin');imgWindow.document.write('<table style=margin:auto border=1 cellpadding=10><tr><th>Image</th><th>Size</th></tr><p>'+outText+'</table><p>');imgWindow.document.close()}else{alert('No Images!')}

**Comment by MarkRH** [comment]
Version 1.46.26 looks to have made the Context Menu work again to choose a search engine.  
Thanks for your efforts!

**Comment by ssborbis** [comment]
> Version 1.46.26 looks to have made the Context Menu work again to choose a search engine.
Thanks for your efforts!

Good to hear. Sorry about the inconvenience everyone.

@runningcheese 

I'll take a look and let you know what I find.

**Comment by ssborbis** [comment]
@runningcheese 

Did you set "scriptsUseBlobs": true, on Firefox? That seems to be working for me.

**Comment by runningcheese** [comment]
@ssborbis 
Thanks Mike, it's my fault, i forgot to set "scriptsUseBlobs", It works fine now.
A big thanks for your work!

**Comment by f73** [comment]
Works great again, thanks for all the hard work!
