### ISSUE TITLE
need keyword encoding

### ISSUE THREAD

**Issue by DandyClubs** [ssborbis/ContextSearch-web-ext#7]
some site need keyword encoding 

https://addons.mozilla.org/ko/firefox/addon/context-search-ja/?src=api

**Comment by ssborbis** [comment]
Right now there is limited character encoding for OpenSearch engines.  It should be working with UTF-8, JIS, SHIFT_JS, and EUC-JP although I've done limited testing.  Which OpenSearch plugin is having problems?  I'll take a look.

**Comment by ssborbis** [comment]
Try https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/1.1a7
I've reworked the character encoding.

**Comment by DandyClubs** [comment]
i test 1.1a8 
maybe is work.  thanks

https://addons.mozilla.org/ko/firefox/addon/burning-moth-add-search/?src=api
only added encoding utf-8.

https://addons.mozilla.org/en-US/firefox/addon/add-to-search-bar/
encoding is correct.

**Comment by ssborbis** [comment]
If you can post the .xml of a search plugin that's not working and a search term that fails, I'll see what's going on.
