### ISSUE TITLE
Show/Hide options

### ISSUE THREAD

**Issue by Tubelerczyk** [ssborbis/ContextSearch-web-ext#70]
Show/Hide options not work correctly. After unchecking the search engines, they are still visible.

**Comment by ssborbis** [comment]
What version/platform/browser/menu?

I just tested the quick menu and context menu on Chrome and Firefox v1.6.6 on Windows and it seems to be working.

**Comment by ssborbis** [comment]
I found the bug. That was an old one. I'm surprised no one brought it up before. Fixed for 1.6.7.1
