### ISSUE TITLE
the highlight feature doesn't work anymore?

### ISSUE THREAD

**Issue by 11100010** [ssborbis/ContextSearch-web-ext#706]
ContextSearch-web-ext Version: 1.46.26
Chrome Version: 125.0.6422.114 (Official Build) (arm64)

Anyone notices that the highlight feature doesn't work anymore in google search?

**Comment by ssborbis** [comment]
Highlighting search results doesn't work when the results page is a google.com address? I'm not seeing that locally. Does it work elsewhere?

![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/aab542da-062b-4770-a5d6-e11dfc4d943c)

**Comment by 11100010** [comment]
Sorry, I mean in google search results page
![Screenshot 2024-06-01 at 16 11 11](https://github.com/ssborbis/ContextSearch-web-ext/assets/87060114/6b1f13ee-0df5-4e38-b2d8-57b7b0f14869)
![Screenshot 2024-06-01 at 16 10 56](https://github.com/ssborbis/ContextSearch-web-ext/assets/87060114/b44b21af-47f4-4bb8-b01a-3710e03ad8af)

**Comment by ssborbis** [comment]
Just a quick sanity check... In all the examples you posted, you are showing the results page of a search performed from this addon, correct?

**Comment by ssborbis** [comment]
It looks like there's a bug when using the "continue highlighting" options that is causing some issues, but I'm not sure if that's you're particular issue.

**Comment by 11100010** [comment]
> Just a quick sanity check... In all the examples you posted, you are showing the results page of a search performed from this addon, correct?

geeez, my bad, you really pointed out the issue, it only works for the results page of a search performed from this extension. now it totally makes sense, thank you for spending time on my silly issue. !_ __
