### ISSUE TITLE
"Search engines manager" invisible buttons 

### ISSUE THREAD

**Issue by simonbcn** [ssborbis/ContextSearch-web-ext#708]
```
Google Chrome 
Context Search v1.46.26
```

See picture:
![Captura de pantalla 2024-06-08 a las 14 32 25](https://github.com/ssborbis/ContextSearch-web-ext/assets/428231/6685988d-3617-490a-bd7d-a96ab5017d5d)

The buttons of each search engine (_I suppose they are for reordering, deleting, etc..._) come out without any text or image.

**Comment by ssborbis** [comment]
Those are placeholders for hotkeys and keywords. You click them and type. If you hover over them, you should see the label. Maybe not the best layout for them, but it's a holdover from earlier versions. A header might be a useful addition though.
