### ISSUE TITLE
Input Cursor 

### ISSUE THREAD

**Issue by YaBoyJon23** [ssborbis/ContextSearch-web-ext#709]
Everytime I make a search ie. Google, when I want to add to the search terms, the input cursor moves to the beginning when I want to add to it at the end.

![cursor issue](https://github.com/ssborbis/ContextSearch-web-ext/assets/72160555/9eb3e309-da88-4c7c-a4cd-8d88679f27e9)

**Comment by ssborbis** [comment]
As far as I'm aware, this addon doesn't do anything with the cursor position. I'm not sure why that would happen, but you could probably add some post-search script to your google engine that moves the cursor to the end.

**Comment by ssborbis** [comment]
Something like...

```javascript
{
  let input = document.querySelector('textarea');
  input.focus();
  input.selectionStart = input.value.length;
}
```

**Comment by YaBoyJon23** [comment]
Thanks for the suggestion. Unfortunately  it doesnt seem to work.
I also tried reinstalling the extension so it loads with most defaults and only thing I changed was it to auto show quick menu. That didn't work so I thought maybe its one of the many many other extensions I have installed so I tried in private mode just enabling this extension and I tried it on the Edge Beta I have installed that has no extensions except this one. I captured a video and I my observation is it doesn't seem to move the cursor all the time. Its more than half the time so its just so frustrating.

https://github.com/ssborbis/ContextSearch-web-ext/assets/72160555/b677293f-97f0-4d64-9b23-957d8f75f3bd

**Comment by ssborbis** [comment]
When you land on google.com, are you clicking anything to get the dropdown menu (suggestions) on the search field? It seems to be opening by itself. I don't seem to have that as my default behavior in either Firefox, Edge, or Chrome.

**Comment by YaBoyJon23** [comment]
I am clicking anywhere but usually at the end of the search term last letter so I can start typing. As soon as I do the search suggests dropdown comes out.

**Comment by YaBoyJon23** [comment]
https://github.com/ssborbis/ContextSearch-web-ext/assets/72160555/63c95378-ee22-495b-9e49-d34c3b4b9038

**Comment by ssborbis** [comment]
Could you disable the search results highlighting and see if it continues to happen? I cant seem to get that bug and I'm trying to narrow it down for you.

![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/49c45358-5715-4d62-8df4-9341eba39fcd)

**Comment by YaBoyJon23** [comment]
Thank you. That fixed it I think. I did 10 tests and the issue did not appear once.
This is great
