### ISSUE TITLE
Does bug 1352598 help with this extension in any way?

### ISSUE THREAD

**Issue by Fanolian** [ssborbis/ContextSearch-web-ext#71]
[Bug 1352598 - Add an API to list installed search engines and execute searches using only those engines](https://bugzilla.mozilla.org/show_bug.cgi?id=1352598)
I know nothing about programming, but I see that this recently added API is well sought after by search engine related extensions authors.

Thank you for your extension.

**Comment by Gristrosia** [comment]
The new api is live in the beta version of firefox 63 it seems

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search

**Comment by ssborbis** [comment]
v1.8.2 is going to integrate the new browser.search API. I'll leave import and native code for now, but it's unnecessary at this point after FF63+

See changes here #104
