### ISSUE TITLE
Open Image in external Viewer

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#713]
Hey there, 

I'm trying to open images in Gwenview with an App Launcher.
This command works some of the time:

`curl "{searchTerms}" -o /tmp/image & gwenview /tmp/image`

But it doesn't work on some images, e.g. here:
https://www.kleinanzeigen.de/s-anzeige/sattelstuetze-rs-lite-concept-rs-bikes-31-4mm/2792055486-217-9294

What is causing the command to fail on the example image?

**Comment by ssborbis** [comment]
The url to the actual image is `https://img.kleinanzeigen.de/api/v1/prod-ads/images/2f/2fae58c4-5ec9-4fe5-8a9f-5e4252dc27dc?rule=$_59.JPG` and I think the dollar sign ($) may be causing problems in a terminal command

**Comment by ssborbis** [comment]
I'm trying to figure out if the problem is with this addon or not. I'll let you know.

**Comment by ThomasSeeker** [comment]
Thank you ssborbis!

I tried to only grab the url of the image via:

`echo  "{searchTerms}"  > /home/user/file`

The result is: 

`https://img.kleinanzeigen.de/api/v1/prod-ads/images/2f/2fae58c4-5ec9-4fe5-8a9f-5e4252dc27dc?rule=.JPG
`

This url does not even work in the browser.
Whereas the slightly different url you shared, works at least in the browser. And if I escape the dollar sign ($) it even works with gwenview. ... How did you get your url?

**Comment by ssborbis** [comment]
The problem appears to be with python. Apparently dollar signs ($) are special characters in python strings. The latest ContextSearch.py corrects this, and has some additional improvements ( maybe ) . Try clicking the gear icon in the edit modal for your native app engine to update to v2.20.

![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/b9db99d2-eb8e-46d8-a3dc-96567eee93ba)

**Comment by ThomasSeeker** [comment]
Thank you so much, ssborbis!

Now it works beautifully!

:-)

**Comment by ssborbis** [comment]
No problem The python code hasn't been thoroughly tested (obviously) so if you notice any weirdness with launching other apps, let me know.

**Comment by ThomasSeeker** [comment]
I gladly will!

In my early linux-days I was very hesitant to report bugs etc. And even these days it is kind of hard for me to wrap my head around the idea, that my complaining is actually of help for a project. 

:-D
