### ISSUE TITLE
Feature request: Automatically select Google as search engine after selecting text

### ISSUE THREAD

**Issue by 3ber123** [ssborbis/ContextSearch-web-ext#714]
Is it possible to default select Google search after selecting the text?

**Comment by 3ber123** [comment]
I already found it in Tools under Quick Menu. I love this extension so much!

**Comment by ssborbis** [comment]
Thanks. You can also assign a keyboard key (g for instance) and enable hotkeys under CS Options -> Shortcuts, then select text, press g, no menu needed.

BTW, which tool did you find? The repeat search / instant search?

**Comment by 3ber123** [comment]
I found Repeat Search. Glad I found this feature after using this extension for almost three years!
