### ISSUE TITLE
How to disable items for non-images?

### ISSUE THREAD

**Issue by exec228** [ssborbis/ContextSearch-web-ext#715]
Hi!

Repro:
1) Browser: Firefox 118 on Windows 10x64.

2) Extension Engine 1:
https://lens.google.com/uploadbyurl?url={searchTerms} ;only "image" checked
Extension Engine 2:
https://yandex.ru/images/search?rpt=imageview&img_url={searchTerms} ;only "image" checked
Extension Engine 3:
https://www.bing.com/images/search?view=detailv2&iss=sbi&q=imgurl:{searchTerms} ;only "image" checked

3) Visit https://example.com

4) Select any text
5) Right-click mouse

Expected:
«Google Lens with Image» is absent in the context menu
«Yandex Images with image» is absent in the context menu
«Bing Images with image» is absent in the context menu

Actual result:
«Google Lens by Image» is present in the context menu
«Yandex Images with image» is present in the context menu
«Bing Images with image» is present in the context menu

What am I doing wrong?
What should I do?

And why https://addons.mozilla.org/firefox/addon/selection-context-search/ can hide menu elements according to context?

Thank you!
![image0](https://github.com/ssborbis/ContextSearch-web-ext/assets/275328/65d8112c-4df1-4ea2-af06-38d841ed49d4)
![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/275328/1fec798c-9420-4439-bfdf-600219ae958d)

**Comment by ssborbis** [comment]
Did you enable context filtering for the menu you are using?

CS Options -> Context Menu -> Filter search engines based on the target element ( link, image, selection, ... )

and 

CS Options -> Quick Menu -> Filter search engines based on the target element ( link, image, selection, ... )

**Comment by exec228** [comment]
Hmm. Failed to find and realize these options earlier.

Switched on now, as you instructed. Yes, it worked! Thank you!
