### ISSUE TITLE
Make quick menu also appear on PDF files in Firefox

### ISSUE THREAD

**Issue by 3ber123** [ssborbis/ContextSearch-web-ext#716]
Hi, ssborbis. I wonder if is it possible to make the Quick Menu also appear on PDF files opened on Firefox? I tried to enable it on input, link, image, et cetera, but it doesn't work.

**Comment by ssborbis** [comment]
Not the quick menu, no. There is no DOM to attach the menus to when viewing pdfs afaik. The context menu should sitll work though.

**Comment by 3ber123** [comment]
Okay. Yeah, the context menu still works, though. Thanks, ssborbis!

**Comment by ssborbis** [comment]
no prob
