### ISSUE TITLE
[Suggestion] Option to put Tools buttons after search engines in Quick Menu

### ISSUE THREAD

**Issue by Fanolian** [ssborbis/ContextSearch-web-ext#72]
I pop my Quick Menu below my cursor. I prefer my most used search engines to be as close to my cursor as possible, while still enable some Tools buttons in case I need them.

Freely re-arrange each Tools buttons between search engines would be the ideal option. This certainly over-complicates the stuff however. 
Therefore I suggest adding an option to put Tools button after search engines. This benefits users preferring popping Quick Menu either above or below the cursor.

Thank you for your extension.

**Comment by ssborbis** [comment]
K, ready for 1.6.7

![untitled](https://user-images.githubusercontent.com/24310997/42817336-6f7c2aa6-8993-11e8-83d9-8ca7bec45668.png)

![untitled](https://user-images.githubusercontent.com/24310997/42817406-a30a4344-8993-11e8-8dd1-690468241a78.png)

**Comment by Fanolian** [comment]
Got the update from AMO. Thanks.
