### ISSUE TITLE
Is there an option to disable contextmenu hotkeys, but still works on ominibox?

### ISSUE THREAD

**Issue by runningcheese** [ssborbis/ContextSearch-web-ext#727]
Hi Mike,
Is there an option to disable contextmenu hotkeys when selecting words,

<img width="879" alt="iShot_2024-09-14_22 30 00" src="https://github.com/user-attachments/assets/f81cf08e-fea2-4969-8f33-d8a2782f2d05">

 but still works on ominibox?

<img width="698" alt="iShot_2024-09-14_22 31 47" src="https://github.com/user-attachments/assets/8320bff4-ad6b-4401-a4ba-d70293c27783">

Thanks in advance.

**Comment by ssborbis** [comment]
Under CS Options -> Shortcuts, you can try disabling the `Search Engine Hotkeys` option.
