### ISSUE TITLE
What are the parameters to get the clipboard contents?

### ISSUE THREAD

**Issue by fengshaoye9945** [ssborbis/ContextSearch-web-ext#729]
What are the parameters to get the clipboard contents?

**Comment by ssborbis** [comment]
Hmm... there isn't a variable or parameter at the moment. What are you trying to do?

**Comment by fengshaoye9945** [comment]
> Hmm... there isn't a variable or parameter at the moment. What are you trying to do?

I want to implement some combined convenient operations, such as: using a search engine to accurately search for combined keywords (clipboard content + selected text or link text)

**Comment by ssborbis** [comment]
Hmm... okay so you're storing some string in your clipboard and want to make an engine that uses that string but also uses a string from the current browser as the query string. Do I have that about right?

**Comment by ssborbis** [comment]
It may depend on your browser and settings, but I've added a template parameter `{clipboard}` to the master branch. If you're sideloading, it's available to test.

**Comment by fengshaoye9945** [comment]
> It may depend on your browser and settings, but I've added a template parameter `{clipboard}` to the master branch. If you're sideloading, it's available to test.

Thank you very much for your update, but after testing, the latest modified source code cannot open custom search engines (such as Google search) for search in any case:
When I select a text and click the search engine in the shortcut menu that appears or right-click a link text and click the search engine in the right-click menu to search, nothing happens.
My system and browser information are as follows:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by fengshaoye9945** [comment]
> > It may depend on your browser and settings, but I've added a template parameter `{clipboard}` to the master branch. If you're sideloading, it's available to test.
> 
> Thank you very much for your update, but after testing, the latest modified source code cannot open custom search engines (such as Google search) for search in any case: When I select a text and click the search engine in the shortcut menu that appears or right-click a link text and click the search engine in the right-click menu to search, nothing happens. My system and browser information are as follows: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

After repeated testing, the problem seems to be this code:
.replace(/{clipboard}/g, await navigator.clipboard.readText())
Only after commenting it out can the search be restored

**Comment by ssborbis** [comment]
Thanks, I'll check the new code in chrome. It was working in Firefox but that doesn't always mean cross-browser support.

**Comment by ssborbis** [comment]
Looks like chrome may be problematic with this option. I'll try some workarounds... Nerfed code is in the repo. I'm still testing things.

**Comment by ssborbis** [comment]
There's a new workaround in the repo to test.

**Comment by fengshaoye9945** [comment]
> 仓库中有一个新的解决方法可供测试。

Thank you for your hard work. The latest modification can open the page search, but {clipboard} is invalid. No matter what the clipboard is, the search result will default to the symbol "}"

**Comment by fengshaoye9945** [comment]
> > 仓库中有一个新的解决方法可供测试。
> 
> Thank you for your hard work. The latest modification can open the page search, but {clipboard} is invalid. No matter what the clipboard is, the search result will default to the symbol "}"

不过我在搜索引擎设置页面中的POST-SEARCH SCRIPT选项加入了折中的方法(但是它反应很慢):
// 获取剪贴板内容并在当前页面中打开 URL
navigator.clipboard.readText().then(function(clipboardText) {
    // 构建要访问的 URL，剪贴板内容和 searchTerms 之间加入空格，并进行编码
    const url = 'https://www.google.com/search?q=' + encodeURIComponent(clipboardText + ' ' + searchTerms);
    
    // 在当前页面中打开 URL
    window.location.href = url;
}).catch(function(err) {
    console.error('无法读取剪贴板内容:', err);
});
![image](https://github.com/user-attachments/assets/9aa6d23e-f62f-413a-a8fd-a08223a59c9d)

**Comment by ssborbis** [comment]
whoops, put a typo in right before I posted to the repo. It should be fixed now. I've tested in Firefox and Chrome. You can use `{clipboard}` or `%c`

**Comment by fengshaoye9945** [comment]
> whoops, put a typo in right before I posted to the repo. It should be fixed now. I've tested in Firefox and Chrome. You can use `{clipboard}` or `%c`

Thank you, it is perfect after testing now, great!
