### ISSUE TITLE
[Suggestion] Keyboard shortcut to open the right-click menu

### ISSUE THREAD

**Issue by AdKiller** [ssborbis/ContextSearch-web-ext#73]
It would be very useful if you could for example search for a video on Youtube like this:

- highlight word
- right-click
- keyboard shortcut to open ContextSearch-web-ext, X for example.
- press Y (for Youtube)

or alternatively

move ContextSearch-web-ext sub-menu to the main right click menu so that you could achieve the same result with keyboard shortcuts.

Anyway, thank you for the great addon.

**Comment by ssborbis** [comment]
So you want a way to set a simple hotkey for each search engine? That's doable but pretty sure it would only be available to the quick menu. I don't think you can track keystrokes in the UI for obvious security reasons.

> move ContextSearch-web-ext sub-menu to the main right click menu so that you could achieve the same result with keyboard shortcuts.

I assume you mean in the context menu? I think webextensions only allows for a single top-tier menu entry. Two or more automatically becomes a submenu.

**Comment by ssborbis** [comment]
Hotkeys are ready for testing in the repo

- Set hotkeys for search engines in the Search Engines Manager. Click the Hotkey icon and press a key
- Set hotkey behavior under Quick Menu->Search Actions (current tab, background tab, etc)
- Setting behavior to anything but NoAction will override Quick menu search bar focus behavior and apply focus to the quick menu document to activate key listeners.
- A few keys are off limits for hotkeys (Tab, arrows).

**Comment by ssborbis** [comment]
Ok, you're talking specifically about the context menu. I didn't realize after opening the `Search for...` menu, typing a letter would toggle through all entries starting with that letter. That's not part of the API or my doing.

I'm looking through the docs and don't see where I could set a key to expand the `Search for ...` menu. That's at the browser UI level, not something I can program for unless there's a manifest key I'm missing.

After adding the hotkey option to the quick menu, I'm kinda liking it. It makes searches, especially multiple searches quite a bit faster. Are you exclusively using the context menu for your searches? 

> or alternatively, bringing the same first letter hotkeys to Quick Menu of ContextSearch-web-ext
I regards to the quick menu, I can see where using the first letter to toggle through potentially multiple search engines beginning with the same letter would have some pros and cons vs setting a specific letter to each search engine. Some users have a TON of search engines so toggling through 10 'g' engines isn't going to save any time. I'll mull over the implementation and get a release out for testing before I decide.

**Comment by AdKiller** [comment]
Thanks for looking into this.

FYI this legacy addon achieves what I requested (I am still hanging on to ESR 52).
https://github.com/yarulan/search-via-url-firefox-addon

That is: highlight search term, right click, press first letter of search engine name, done.

![image](https://user-images.githubusercontent.com/13304436/42880365-5b5b2124-8a94-11e8-80ab-9148b6bc713a.png)

**Comment by ssborbis** [comment]
Unfortunately, you can't currently do that with the webextensions API (Firefox 57+). I only started developing this app to replace a legacy app I heavily relied on that no longer worked. The closest I can get you with this add-on is hotkey + Old Firefox Style in the quick menu + open quick menu on right-click

**Comment by AdKiller** [comment]
anything to optimize the process would be appreciated. thanks again.

**Comment by ssborbis** [comment]
no prob

**Comment by ssborbis** [comment]
I'm checking it out now. Looks like the hotkey can only be bound to a letter in the menu title string. Right now, I'm prepending a `&` to the menu title resulting in `Search ...` with the `S` underlined. Because there is another `S` hotkey for the Firefox built-in search, you need to press `S` twice, then `Enter` to access the menu. How would that work for you?

**Comment by ssborbis** [comment]
I've also tried adding an X to the beginning of the string ( `X Search With ...`). It looks a bit weird, but it functions better if there are no other `X` menus.

**Comment by AdKiller** [comment]
> 
> 
> I've also tried adding an X to the beginning of the string ( `X Search With ...`). It looks a bit weird, but it functions better if there are no other `X` menus.

I installed the latest version, I see the "X search with" but when click it or press X nothing happens. this X shortcut is good for me but would it be possible to make the shortcut user configurable?

**Comment by ssborbis** [comment]
> I installed the latest version, I see the "X search with" but when click it or press X nothing happens

That's weird. Works for me ok with FF63 on Win10. What FF version and platform are you on?

>  this X shortcut is good for me but would it be possible to make the shortcut user configurable?

Yep, that's what I was thinking. I'll set it up.

**Comment by ssborbis** [comment]
... also, are your search engines where they should be under the "X Search With.." submenu? If you mouse-click, do they show up, but pressing X does nothing?

**Comment by ssborbis** [comment]
> this X shortcut is good for me but would it be possible to make the shortcut user configurable?

That option is now in the repo

**Comment by ssborbis** [comment]
1.8.0 going up

**Comment by ssborbis** [comment]
The new option under Context Menu should give you what you're wanting. I'll re-open this thread if you have any issues.
