### ISSUE TITLE
How do I replace a space with an underscore?

### ISSUE THREAD

**Issue by procobain** [ssborbis/ContextSearch-web-ext#737]
There is a search engine website that uses _ between spaces. How do I do this automatically?

When selecting a phrase like "what day was that person born?"
It searches for "what_day_was_that_person_born"

Would that be possible?

**Comment by ssborbis** [comment]
Use the modify terms regex field

Something like...
`/\s+/_/g`

**Comment by procobain** [comment]
> Use the modify terms regex field
> 
> Something like... `/\s+/_/g`

Perfect, it worked!

Then I asked Chatgpt how it worked.

Cheers.
