### ISSUE TITLE
Copy - no action

### ISSUE THREAD

**Issue by spacedingo** [ssborbis/ContextSearch-web-ext#76]
I have tested both _ContextSearch web-ext_ and _ContextSearch web-ext Lite_ version 1.6.7.1., and the copy button in the quick menu does not do anything.  After installation, I just enabled Quick-menu to open auto.

**Comment by ssborbis** [comment]
Do you have the search bar hidden? I had to change some code to work with Chrome and it looks it fails without the search bar.

**Comment by ssborbis** [comment]
Try updating to 1.6.8

**Comment by spacedingo** [comment]
I don't have search bar hidden. Updated and tested 1.6.8 and it remains same..can't copy

**Comment by ssborbis** [comment]
What browser/platform are you on?

**Comment by spacedingo** [comment]
Firefox 62.0b10 on Windows 10 64bit

**Comment by spacedingo** [comment]
Sorry it was a fault on my part. I had user preference _dom.allow_cut_copy_ set to _false_. I'm using [ghacks-user.js](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview)

**Comment by ssborbis** [comment]
Good deal
