### ISSUE TITLE
Search several search engines at once

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#78]
In certain circumstances it's handy to have a way to search several search engines at once, with one click only. This was possible with an add-on before WebExtensions came. There you could arrange Firefox's OpenSearch engines into folders and then click on one of them in the context menu, in order so search through several sites with one click.

Your elaborate extension is currently missing this feature. I'm wondering if it's even viable with the restrictions of WebExtensions?

One way to realize this would be by means of the bookmarks menu. Create a bookmark folder and fill it with some search engines. Then make the folders clickable in the context menu and voilà!

BTW, there must be a certain reason why the middle mouse click configuration is missing for the context menu, right?

Actually I would prefer the elegance of the quick menu, but this is the only practical way that comes to my mind at the moment. Maybe you know a better one?

**Comment by ssborbis** [comment]
> In certain circumstances it's handy to have a way to search several search engines at once, with one click only. This was possible with an add-on before WebExtensions came. There you could arrange Firefox's OpenSearch engines into folders and then click on one of them in the context menu, in order so search through several sites with one click.Your elaborate extension is currently missing this feature. I'm wondering if it's even viable with the restrictions of WebExtensions?

It's doable. I've toyed around with a few implementations but didn't release anything. I tried allowing multiple engines to use the same hotkey with the quick menu. It worked fine but didn't allow grouped engines to be accessed individually via hotkey.

> BTW, there must be a certain reason why the middle mouse click configuration is missing for the context menu, right?

Yeah, context menu only recognizes left-click, else I'd have more Search Action options.

> One way to realize this would be by means of the bookmarks menu. Create a bookmark folder and fill it with some search engines. Then make the folders clickable in the context menu and voilà!

By bookmarks menu, do you mean enabling the Use Bookmarks option with the context menu so you can use subfolders? 

The default behavior when clicking a subfolder/submenu is to expand the menu. I wouldn't want to override that, but the context menu does recognizes modifier keys [shift, ctrl, alt] so I could set one of those to search all engines in that subfolder. It would only be available in Firefox, as Chrome does not allow for subfolders. Trivial to code for.

**Comment by ssborbis** [comment]
> The default behavior when clicking a subfolder/submenu is to expand the menu. I wouldn't want to override that, but the context menu does recognizes modifier keys [shift, ctrl, alt] so I could set one of those to search all engines in that subfolder. It would only be available in Firefox, as Chrome does not allow for subfolders. Trivial to code for.

Whoops, doesn't look like FF throws an event when clicking a subfolder. Might not be doable that way. I did see another context-menu add-on for Chrome that displayed a custom right-click menu as an expandable folder menu mimicking a bookmarks folder. That might be the way to go.

**Comment by sojusnik** [comment]
> By bookmarks menu, do you mean enabling the Use Bookmarks option with the context menu so you can use subfolders?
Exactly!

Ideally, those subfolders should somehow be shown in the quick menu, since it makes it possible to search with less mouse clicks.

> (edit) In the meantime, you could try setting hotkeys for a number of search engines, set hotkey behavior to open in background tabs and launch them from the quickmenu

Thanks for the hint!

Even without the "multiple search engines at once" search functionality, your extension is a pleasure to use. Thanks for that!

**Comment by ssborbis** [comment]
I'll look into extending / adding the Use Bookmarks option for the quick menu. It's going to take some time.

**Comment by ssborbis** [comment]
1.6.9 is ready for testing in the repo. I could use some feedback before I drop a release.

* Added checkbox 'Manage With Bookmarks' to the Quick menu options
* Middle-click on a folder will search using all engines within that folder, but not within subfolders

**Comment by sojusnik** [comment]
> I could use some feedback before I drop a release.

With pleasure! What's the proper way to install it?

**Comment by ssborbis** [comment]
Easiest way is to grab the zipped beta

https://github.com/ssborbis/ContextSearch-web-ext/releases/download/v1.6.9b1/contextsearch_web-ext-1.6.9.zip

1) download the beta
2) open `about:debugging` in the address bar
3) Enable add-on debugging
4) Click `Load Temporary Addon` and browse to the beta zip

The beta will remain loaded until you close Firefox

**Comment by sojusnik** [comment]
Basically, it seems to work well! Thank you!

I only discovered that you have to enable "Manage With Bookmarks" in the context menu section and also in the quick menu one, in order to see the blue bookmark icons to the left of the search engines in the search engine list. As I don't use the context menu at all for searching, this confused me at the beginning.

Regarding aesthetics, the font size of the folder's name could adjust its size to the width of a box. At the moment the name of one of my folders is truncated, although it has only 5 letters. But this is not crucial, since we can use abbreviations instead.

Do you plan to implement a dedicated menu for search actions (left-click, middle-click etc.) for folders, like you already have for the context and quick menu respectively, or leave the middle-click as default?

**Comment by ssborbis** [comment]
> I only discovered that you have to enable "Manage With Bookmarks" in the context menu section and also in the quick menu one, in order to see the blue bookmark icons to the left of the search engines in the search engine list. As I don't use the context menu at all for searching, this confused me at the beginning.

Fixed. Thanks

> Regarding aesthetics, the font size of the folder's name could adjust its size to the width of a box. At the moment the name of one of my folders is truncated, although it has only 5 letters. But this is not crucial, since we can use abbreviations instead.

There's really no perfect solution for this. I'm open to suggestions. Long folder names could end up being illegible if the font is scaled to the container width. I chose the smallest font size I felt I could get away with and hid the overflow. It's a compromise. You can get the full folder names by hovering over the icon.  Using the 'Old Firefox Style' option handles this a bit better 

> Do you plan to implement a dedicated menu for search actions (left-click, middle-click etc.) for folders, like you already have for the context and quick menu respectively, or leave the middle-click as default?

I can. What other actions did you have in mind?

**Comment by sojusnik** [comment]
> There's really no perfect solution for this. I'm open to suggestions. Long folder names could end up being illegible if the font is scaled to the container width. I chose the smallest font size I felt I could get away with and hid the overflow. It's a compromise. You can get the full folder names by hovering over the icon. Using the 'Old Firefox Style' option handles this a bit better.

I'm with you on that. Let's just leave is as it, since it's totally sufficient.

> I can. What other actions did you have in mind?

I'm perfectly fine with the current solution, but you could add the default ones from the [quick menu](https://i.imgur.com/lIiyhvm.png). Also the action "open folder", like it is now with left-click, should be added to the menu. Thus, one could open the folder with a right-click and perform the search in the background with a normal left-click, instead of a middle-click.

**Comment by ssborbis** [comment]
v1.6.9 going up. I didn't get to the mouse action options for folders but I'll have something for future releases.

**Comment by sojusnik** [comment]
Many thanks!

**Comment by sojusnik** [comment]
Oh, and centering the folder's text would, imho, look better than aligning it to the left.

**Comment by ssborbis** [comment]
> Oh, and centering the folder's text would, imho, look better than aligning it to the left.

I think centering with overflow hidden was causing both sides to clip on long names. I'll continue looking for a better style.

**Comment by ssborbis** [comment]
added options "Background Tab", "New Window", "New Incognito Window" for right, middle, left+shift, left+alt, left+ctrl clicks on folders

![untitled](https://user-images.githubusercontent.com/24310997/43879755-0ab472f6-9b6b-11e8-8fa3-341fcf5b0cda.png)

**Comment by sojusnik** [comment]
Great! Does it take a lot of effort to make those commands available for the left button too? My motive is always to use one button, in my case the left one, for searching. At the moment if often mistakenly left click on a folder with the expectation to carry out a search, but instead it just opens the folder.

**Comment by ssborbis** [comment]
Sure I can add it.

**Comment by ssborbis** [comment]
![untitled](https://user-images.githubusercontent.com/24310997/43983560-cdaf02ca-9cc0-11e8-9a8c-74849f6fefd9.png)

**Comment by sojusnik** [comment]
Works like a charm in the new version!
