### ISSUE TITLE
Difficulties creating a search engine

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#79]
I struggle to create a search engine from the following site: http://isynonym.com

Experimenting with different GET or POST attributes didn't help either.

Could you kindly have a look on this?

**Comment by ssborbis** [comment]
Added fine for me from the Add Custom Search option in the context menu using the values that were generated. I tried both the simple method and Advanced -> Create and they worked. How did you add yours? What error messages are you getting?

![untitled1](https://user-images.githubusercontent.com/24310997/43369119-fa41dd4a-932d-11e8-8159-293a64d572d1.png)
![untitled2](https://user-images.githubusercontent.com/24310997/43369120-fa5a73d2-932d-11e8-975b-acf22edd86a6.png)

**Comment by sojusnik** [comment]
The reason was that I've tested the search engine with the "test" button while creating it. When doing so, I only see the homepage of this site after "test searching" for a keyword, but after finally adding the search engine, it works as expected.

So it's a new bug that led to this kind of confusion.
