### ISSUE TITLE
possible quick menu style change?

### ISSUE THREAD

**Issue by DandyClubs** [ssborbis/ContextSearch-web-ext#8]
Quick Menu Style change?

select text and mouse left-click( not hold) 

Quick Context Search
https://addons.mozilla.org/ko/firefox/addon/quickcontextsearch/

**Comment by ssborbis** [comment]
I'll see about adding that.  In the meantime, you might like the latest betas where I added an option for opening the quick menu automatically after selecting text.

https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta

**Comment by ssborbis** [comment]
If you're wanting the grid in the context menu like in the add-on you linked to, it's not possible with the new web extensions api

**Comment by DandyClubs** [comment]
thanks.
