### ISSUE TITLE
Description is missing in the search engine list

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#81]
When creating a custom search engine, there's a description field that can filled out. But this field is missing, when clicking on a search engine in the second tab of your add-on's settings.

Would be nice to see the description there, since I sometimes use it for notes.

Happens on Ubuntu 18.04 with Firefox 61.0.1 and ContextSearch 1.6.9.

**Comment by ssborbis** [comment]
The description field is only necessary for generating OpenSearch engines for use with Firefox's One-Click search engines. ContextSearch doesn't use them at all so I left that field out. I'll see about putting it back.

**Comment by ssborbis** [comment]
I've added a description field to the edit form from Options->Search Engines for the next release. If you have one-click engines installed with descriptions you wish to retrieve, you can delete those search engines from ContextSearch and re-import your search.json.mozlz4 file to update the descriptions. You could also manually enter descriptions for search engines.
