### ISSUE TITLE
Search bar isn't focused

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#82]
Although both corresponding checkboxes are enabled in the settings, the search bar of the quick search menu isn't focused and the search term isn't selected. I remember that it used to work in previous versions, but can't say after which version it got broken.

Happens on Ubuntu 18.04 with Firefox 61.0.1 and ContextSearch 1.6.9.

**Comment by ssborbis** [comment]
Do you have the Search Action for Hotkeys set to something other than No Action? I need to add a note that enabling hotkeys will prevent search bar focus or vice versa.

**Comment by sojusnik** [comment]
Yes, that was it!
