### ISSUE TITLE
Plus signs when searching on deepl.com

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#83]
When searching on [DeepL](https://www.deepl.com/translator) for a phrase with an OpenSearch-Engine, then plus signs "+" appear between words. This only happens if the search was carried out from the address bar of Firefox and **not** by your add-on.

Any ideas why the search works flawlessly from your add-on and not from the OpenSearch-Engine of Firefox?

You can install the Deepl search from [Mycroft](http://mycroftproject.com/search-engines.html?name=deepl) or use my parameters to create one with your add-on:

Name: DeepL (de-en)
Template: https://www.deepl.com/translator#de/en/{searchTerms}
Path: https://www.deepl.com/translator

Happens on Ubuntu 18.04 with Firefox 61.0.1 and ContextSearch 1.6.9.

Very interested to hear your opinion on that!

**Comment by ssborbis** [comment]
Looks like Firefox converts spaces to + signs when searching using the address bar or One-Click search bar. This seems to work fine on most major websites (perhaps that is part of the OpenSearch standard) whereas ContextSearch leaves them as spaces.

**Comment by ssborbis** [comment]
I've added an option to modify search strings using regex on a per-engine basis. This should allow users to adapt search terms to different query standards. See #99 for more info
