### ISSUE TITLE
icon not displaying (no SVG?)

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#84]
I added a custom search engine for IMDB at:

https://www.imdb.com/find?ref_=nv_sr_fn&q=&s=all

resulting in
template: https://www.imdb.com/find?q={searchTerms}&ref_=nv_sr_fn&s=all

and found that the icon doesn't work:

https://m.media-amazon.com/images/G/01/imdb/images/safari-favicon-517611381._CB471604984_.svg

Opening the URL, the icon is shown. It is also shown in the firefox search box drop-down.

Is SVG supported in ContextSearch?

**Comment by ssborbis** [comment]
Hmm interesting. I tested with a different svg (http://www.phrogz.net/tmp/svg/tiger.svg) and it did work. I can't seem to get your icon to load in canvas, which I use to resize larger icons before base64 -> localstorage. You icon ends up being treated as a blank canvas.

**Comment by hg42** [comment]
I played a bit with SVGs.
Even loading the svg and saving it again with inkscape (which changes a lot at least in the header) doesn't make it work.
If I edit it a bit, e.g. removing the frame and resizing (I think the latter makes the difference) makes it work.
So I compared the header.
I found that the original image and the only-saved image didn't contain a width and height attribute.
The viewBox seems to be sufficient usually, but doesn't with ContextSearch.

If I add width and height to the svg it works, no matter if I choose 10 or 10000 for these dimensions. So they don't seem to be necessary for the functionality, but someone cannot live without.
May be, you could add a width and height in some of your conversion code to make it work.

**Comment by ssborbis** [comment]
I took a quick look at setting dimensions. I think I'd have to load the svg as XML, add a width/height attribute, reload the svg as an image, and send to canvas. Doable, but a pain. I'll look around for a shortcut.

**Comment by hg42** [comment]
As I wrote in the wrong place/issue, FF has a bug displaying SVGs without width or height.

I recently tried FF nightly (63.x) and found that it still has the bug.

**Comment by hg42** [comment]
oh, nonebat all, thanks for asking.
It's only one engine (IMDB) and I made my own icon for that. I only thought, other users might not understand the reasons. Unfortunately the whole engine looks like non-existing.
May be you could detect the empty icon (compare before/after? count background colored pixels?) and set some default icon?
But this seems to be non-trivial, too.
So just wait for the fix...

**Comment by ssborbis** [comment]
Cleaning house. Looks like either Firefox fixed some canvas svg issues, or the source svg changed.
