### ISSUE TITLE
1.7.0 POST search bug

### ISSUE THREAD

**Issue by DandyClubs** [ssborbis/ContextSearch-web-ext#89]
test site 
https://www.hdreactor.club/

post params

story={searchTerms}&do=search&subaction=search

context search not work. just moving search page

**Comment by Tubelerczyk** [comment]
This problem has already been reported here.

[Websites where the Add Custom Search fails](https://github.com/ssborbis/ContextSearch-web-ext/issues/67#issuecomment-413464396)

For now, use version 1.6.9.

**Comment by ssborbis** [comment]
hotfix going up v1.7.0.1
