### ISSUE TITLE
Open URL and copy text funcations?

### ISSUE THREAD

**Issue by graycatgrayhat** [ssborbis/ContextSearch-web-ext#9]
Any chance of seeing a few more utility functions added to the search quick menu?  

Currently I use an Firefox extension called Swift Selection Search, built in it has the option to open a selected URL or copy the text.  It does not have the same options to open on varies conditions(hold click, left/right and so on) and the settings menu is rather raw, function over form.

Swift Selection Search (SSS) https://github.com/CanisLupus/swift-selection-search

**Comment by ssborbis** [comment]
I do like the way SSS adds a clipboard icon for copying text.  I've thought about adding something similar.  I'll see what I can do.

**Comment by ssborbis** [comment]
Out of curiosity, are you using the Automatic setting for opening the quick menu?  I assume Daniel (CanisLupus) added the Copy Text and Open Url buttons to replace the normal right-click context menu functionality you lose when choosing to open the popup automatically.

**Comment by ssborbis** [comment]
Check the latest betas (1.2.1b2+)
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta

Copy does not work in text fields and I haven't tested the Open in link much.  Let me know how it goes.

**Comment by graycatgrayhat** [comment]
Perfect just what I was looking for, just installed the beta version and everything works great!  

Oddly I prefer to use the left click hold option, I might open the same text in several different search engines.  Being able to simply hold down left click again is nice, but my use cases are more fringe then most.

I am impressed to see the extra functions implemented so fast! and hope to see more options like toggling them on/off or universally present.  I will be switching over to ContextSearch from SSS, both are great just really love the refinded UI for settings and sharper looking quick menu IMO.
