### ISSUE TITLE
Own text in the context menu

### ISSUE THREAD

**Issue by Tubelerczyk** [ssborbis/ContextSearch-web-ext#91]
Is it possible to add an option to give your own command name in the context menu? I am from Poland and I would prefer this option in my own language.

![screen](https://user-images.githubusercontent.com/41324346/44207358-30f20d00-a15d-11e8-8796-df0b2f41efb9.jpg)

### **Is icon in context menu could stand out more?**

**Comment by ssborbis** [comment]
If you want to contribute a language pack, simply edit this file, translating the English messages into your language, paste it here and I'll add a locale. to the repository.

https://github.com/ssborbis/ContextSearch-web-ext/blob/native-app-support/src/_locales/en/messages.json

Or you can create a fork and submit changes that way. If you're unfamiliar with github, the first option would be easiest.

**Comment by Tubelerczyk** [comment]
OK, I try... When I find some time.
