### ISSUE TITLE
Problem when importing search engines

### ISSUE THREAD

**Issue by toto-1** [ssborbis/ContextSearch-web-ext#96]
Hi,
recently, after changing to the extended support release of Firefox (or maybe the change to version 60), I am experiencing some trouble with ContextSearch web-ext Light, also after reinstalling the extension.

When trying import search engines, I locate the "search.json.mozlz4" file in my profile folder, but the action of opening this files does not seem to finish as "Loading remote content" keeps being displayed along with the waiting circle animation.
Furthermore, the options changed in ContextSearch settings menu don't seem to be saved (like activating the context menu or quick menu search). But maybe this is just a consequence of failing to import search engines?

Any ideas what to do do make it work again?

**Comment by ssborbis** [comment]
Only happens on ESR edition? Last I looked, the ESR releases (based on FF52) didn't include webextensions (FF57+) support which is required by this addon. If that's still true, this addon will not work on ESR editions. Sorry :(

**Comment by ssborbis** [comment]
I'm now reading ESR 60 is supposed to include webextensions support. I'll check it out and get back to you.

**Comment by ssborbis** [comment]
Just tested 60.2.0esr (32-bit) under windows 7 and didn't have any issues importing or changing settings. Want to do some debugging to see if any errors pop up?

* open `about:debugging` in the url bar
* Check `Enable add-on debugging` at the top
* scroll to ContextSearch web-ext Lite and click `debug`
* click `ok` in the confirmation dialog that pops up
* the debugging window should open up. Try opening options and importing your engines and check the debugging window for errors
* post results here

If options are not saving, it sounds like something is going wrong with loading the addon or with the javascript in the options page. Try clearing the debugging window and reloading the options page to see fresh errors.

**Comment by toto-1** [comment]
I have no experience in this, so I thanks for the detailed explanation, I hope I got it right.
This is what happens:

When opening ContextSearch web-ext Lite options:
> error  options.js:1449:3
> TypeError: arr is undefined[Saber más]  options.js:1026:1
> loaded @ moz-extension://d9db677c-7fd1-42e1-a1d5-ea9b1afe7eaf/_locales/en/help.html  options.js:1453:3
> NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIWebProgress.DOMWindow]  WebNavigationContent.js:218


When selecting the search.json.mozlz4 file:
> TypeError: userOptions.searchEngines is undefined[Saber más]

Details that show when clicking the small arrow:

> <anónimo> moz-extension://d9db677c-7fd1-42e1-a1d5-ea9b1afe7eaf/options.js:30:1
> 	readMozlz4File/reader.onload moz-extension://d9db677c-7fd1-42e1-a1d5-ea9b1afe7eaf/mozlz4.js:84:9



I also installed FF60esr on a different machine (Windows 7, like the firstone), no problems with ContextSearch web-ext Lite there.

**Comment by ssborbis** [comment]
looks like maybe something went wrong with the contextsearch options file. 

Can you type `userOptions` into the debugging window and paste the values of `searchEngines` and `quickMenuHotkey` here?

**Comment by ssborbis** [comment]
oh and I don't need your list of search engines, just whether it's an array or not

**Comment by ssborbis** [comment]
the same debug window you opened to view the errors (Console tab of the debugger window) should have an input field at the bottom you can type in commands

**Comment by toto-1** [comment]
That's strange...
`userOptions`

> ReferenceError: userOptions is not defined

**Comment by ssborbis** [comment]
that's a problem. Just to be sure, you opened the developer console through the about:debugging -> ContextSearch web-ext Lite -> debug button?

**Comment by toto-1** [comment]
Yes.
On the other machine, where ContextSearch works, this command works and has an output.
So probably it's a problem with Firefox? I will reinstall it when I have time (because I guess have to create a new profile).
Anyway, thanks for the nice and quick help.

**Comment by ssborbis** [comment]
I'd start with removing ContextSearch and reinstalling after restarting Firefox. If that doesn't work, maybe it is a FF issue. Let me know.

**Comment by toto-1** [comment]
Perfect!
After reinstalling ContextSearch everything works.
I thought I had done this before.

Also the `userOptions` command works:

> searchEngines: Array[12]

> quickMenuHotkey: Array[3]

Thank you again. Maybe it was a singular problem.
If you would suspect some cause, I'd be happy help you look for traces of the problem.

**Comment by ssborbis** [comment]
> After reinstalling ContextSearch everything works.

Good deal

> If you would suspect some cause, I'd be happy help you look for traces of the problem.

No need. Sounds like an isolated problem.
