### ISSUE TITLE
Firefox crashes while browsing for "search.json.mozlz4" in Mac OS Mojave

### ISSUE THREAD

**Issue by betamod** [ssborbis/ContextSearch-web-ext#97]
First ContextSearch-web-ext Lite lost my search preferences. 

I noticed this shortly after installing the latest Mac OS, Mojave 10.14.

I tried to fix this in Settings, under the "Search Engines" tab > Import One-Click Search Engines:
Browse to your profile folder and select your search.json.mozlz4 file ... 

However, Firefox crashes while browsing to my Firefox profile, before I can even get to the folder where the  "search.json.mozlz4" is. I have to force quit. 

Happens every time I try to brows for the file. I tried 5 times over two days. 

I can still see my list of search engines in the search/address bar and I can use Finder to navigate to the search.json.mozlz4. It only crashes when I brows to the file from the plugin settings UI.  

I have tried uninstalling and reinstalling both Firefox and ContextSearch-web-ext Lite and rebooting Mac OS. The problem persists.

**Comment by ssborbis** [comment]
> However, Firefox crashes while browsing to my Firefox profile, before I can even get to the folder where the "search.json.mozlz4" is. I have to force quit.

That's very odd. I'm unfamiliar with MacOS so I might not be able to troubleshoot adequately. Is there a permissions issue with the directory itself? I can't think of another reason why you wouldn't be able to even browse to the profile directory besides some type of data corruption or read error. 

I might suggest copying the search.json.mozlz4 file from the profile directory to a different directory you can browser to and import from there.

**Comment by ssborbis** [comment]
@betamod 

Did you ever find a solution to this problem?
